docs/content/en/docs/getting-started/install/_index.md
I added a short intro to the install doc to make it clear that the page (install/_index.md) describes how to set up the Administrative machine to begin a cluster creation process. Since the "Cluster creation workflow" page is now done, I added a pointer to that as well.
=> Added an intro to install doc

docs/content/en/docs/tasks/cluster/cluster-connect.md
This PR changes the name of the link on the bottom of the page from "AWS Connector" to "AWS EKS Connector" , per a request from the docs team. While I was in there, I changed some of the other wording as well.
=> Change connector wording per docs team

OWNERS, cmd/integration_test/build/script/set_profile.sh, release/scripts/bundle-release.sh, release/scripts/eks-a-release.sh, release/scripts/release.sh, release/scripts/setup-aws-config.sh, scripts/attribution_helpers.sh, scripts/make_attribution.sh
Remove year from the license headers on files.
=> Remove year from license verbiage

docs/content/en/docs/community/contributing.md
Hi, Amazon OSPO here,
I've removed the CLA line from the website page on contributing. You'll note that it's no longer in the CONTRIBUTING.md file that is setup by default.
---
=> Dropping the CLA line

release/pkg/prepare_release.go
Use source ECR registry for regex replace during release.
Dev release - private ECR (build)
Staging release - private ECR (build)
Prod release - public ECR (staging)
=> Use source ECR registry name for regex

README.md
Point people towards the build tooling repo for dependency updates.
=> add build tooling repo link to the readme

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, test/e2e/flux_test.go
Enabling Flux e2e test runs. Also modified the flux tests to run only currently supported k8s versions.
=> Enabling Flux e2e test

release/pkg/assets_kube_rbac_proxy.go
This enables proper regex replacement in manifests.
=> Add org name to kube-rbac-proxy override

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, internal/pkg/ssm/command.go
* Decrease verbosity of logs
* Increase timeout and max retries for SSM `SendCommand` call
=> Decrease log verbosity and increase retry wait during e2e tests

cmd/eksctl-anywhere/cmd/generateclusterconfig.go
Adds a current list of providers to the help output text. This likely would need to change in the future as we add more providers but it's helpful to know what provider strings can be used.
Maybe in the future we add a `anywhere get providers` to show a full list.
=> Add provider options to help output

test/framework/conformance.go
Parsing conformance test result logs to check for failed tests.
Since by default we run 2 plugins, the Sonobuoy logs should contain two failed tests messages, `Failed: 0`
Example log
`Plugin: e2e
Status: passed
Total: 5668
Passed: 311
Failed: 0
Skipped: 5357`
=> Check for failed conformance tests

pkg/executables/builder.go, pkg/executables/troubleshoot.go
Initial setup for the use of troubleshoot executable. 
This will be followed by porting over, piecemeal, the functionality of the `support` package to interface with this binary rather than using the troubleshoot go library. 
The `replicatedhq/troubleshoot` binary is already built into our tools image -- see https://github.com/aws/eks-anywhere-build-tooling/pull/42
part of https://github.com/aws/eks-anywhere/issues/188
=> initial setup of troubleshoot executable

.github/labeler.yml
My regex was wrong for subdirectories. I tested this on my own repo and it works for subdirs.
=> Fix labeler regex

pkg/executables/builder.go, pkg/executables/troubleshoot.go
I can't NOT type `troulbeshoot`, pronounced troll-b-shoot
=> fix typo in troubleshoot executable

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, test/e2e/README.md
Increasing the max on the number of EC2s we create for e2e tests. Also added a note on the readme to increase the count when adding new tests.
=> Bumping max EC2 count for e2e tests

.github/workflows/label.yml, cmd/integration_test/build/script/upload_artifacts.sh, docs/content/en/docs/concepts/clusterworkflow.md, release/scripts/release.sh
From a blog I read online
> GitHub Actions has always been about more than just continuous integration. Our goal is to enable repository maintainers to automate a variety of workflows and reduce manual effort. In order to protect public repositories for malicious users we run all pull request workflows raised from repository forks with a read-only token and no access to secrets. This makes common workflows like labeling or commenting on pull requests very difficult.
>
>In order to solve this, we’ve added a new pull_request_target event, which behaves in an almost identical way to the pull_request event with the same set of filters and payload. However, instead of running against the workflow and code from the merge commit, the event runs against the workflow and code from the base of the …
=> Fix issue with labeling workflow

pkg/providers/vsphere/config/template.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_external_etcd.yaml
Writing file to `/var/lib/kubeadm` instead of `/etc`, and hosting from there.
=> Fix Bottlerocket filepaths in template

pkg/api/v1alpha1/cluster.go, pkg/providers/vsphere/vsphere.go
Moved control plane and external etcd count logs from provider specific file to cluster.go file. 
=> Moved controlplane count and externaletcd count logs to cluster spec file

docs/content/en/docs/reference/clusterspec/vsphere.md
`controlPlaneConfiguration.endpoint.host` should be outside the dhcp range so your dhcp server doesn't assign this IP to another machine. If this happens, the cluster creation can get stuck.
Specifying this requirement in the docs
=> Clarify controlPlaneConfiguration.endpoint.host requirements

test/kube-bench/README.md, test/kube-bench/jobs/controlplane/kube-bench-default.yaml, test/kube-bench/jobs/controlplane/kube-bench-stacked-etcd.yaml, test/kube-bench/jobs/worker/kube-bench-node.yaml
Add Readme and Job YAMLs for running kube-bench tests on EKS Anywhere clusters.
=> Add README and jobs for kube-bench

release/cmd/release.go, release/pkg/prepare_release.go
Adding the functionality to update existing EKS-A releases with new bundle versions. This will allow customers to pull down base-image updated versions of the same bundle.
=> Allow existing EKS-A releases to be updated

pkg/addonmanager/addonclients/testdata/cluster-config-default-path.yaml, pkg/addonmanager/addonclients/testdata/cluster-config-user-provided-path.yaml, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/gitopsconfig_types.go, pkg/api/v1alpha1/object_meta.go, pkg/api/v1alpha1/oidcconfig_types.go, pkg/api/v1alpha1/vspheremachineconfig_types.go, pkg/clustermarshaller/clustermarshaller.go, pkg/providers/provider.go, release/pkg/prepare_release.go
https://github.com/aws/eks-anywhere/issues/191
Exclude fields from getting written to the github repo if flux is enabled.
This pr takes care of removing these fields from the `cluster`, `gitops`, and `oidc` configs.
=> Exclude fields like `Status` and `creationTimestamp`

pkg/providers/docker/config/template.yaml, pkg/providers/docker/docker.go, pkg/providers/docker/docker_test.go, pkg/providers/docker/testdata/capd_valid_full_oidc_expected.yaml, pkg/providers/docker/testdata/capd_valid_minimal_oidc_expected.yaml, pkg/providers/docker/testdata/valid_deployment_custom_cidrs_expected.yaml, pkg/providers/docker/testdata/valid_deployment_expected.yaml
At the moment, the pod and service cidr values are all hard coded for docker. With this change, these values will be read from the cluster spec file. This should fix #219.
Test output result:
> eks-anywhere bnrjee$ kubectl cluster-info dump --kubeconfig abc/abc-eks-a-cluster.kubeconfig | grep -i cidr
"io.cilium.network.ipv4-pod-cidr": "10.10.1.0/24",
"podCIDR": "10.10.1.0/24",
"podCIDRs": [
"io.cilium.network.ipv4-pod-cidr": "10.10.0.0/24",
"podCIDR": "10.10.0.0/24",
"podCIDRs": [
"--allocate-node-cidrs=true",
"--cluster-cidr=10.10.0.0/16",
I0921 17:04:45.014930       1 range_allocator.go:116] No Secondary Service CIDR provided. Skipping filtering out secondary service addresses.
I0921 17:04:45.115527       1 range_allocator.go:172] …
=> Read cidr blocks from the cluster config file for docker

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml
Till we have a way of cleaning up only VMs associated with failed tests while their ec2 instances are being cleaned up
=> Add back vsphere vm cleanup for failed tests

internal/pkg/ssm/command.go
E2e tests use ssm commands for running tests, which includes downloading
the required binaries and running the command for e2e tests.
SSM by default starts a session with /usr/bin path. This is why all binaries
and test folder created by an e2e test gets saved under that path.
This commit adds a command to change directory to a new path /home/e2e
before running any other commands so that the generated test output is saved
under /home/e2e and not under /usr/bin
=> Change directory used by ssm commands

pkg/providers/vsphere/config/machine-health-check-template.yaml, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
Modify the template that generates MachineHealthChecks (MHC) to use the
eksa-system namespace (the same used by other CRs).
During cluster creation if the MHCs are created on a separate namespace they will not be available.
=> Fix Namespace for MachineHealthCheck Objects

controllers/controllers/resource/fetcher.go, controllers/controllers/resource/fetcher_test.go
… specified
Fix an error in https://github.com/aws/eks-anywhere/pull/177
https://github.com/aws/eks-anywhere/pull/177/files#diff-901e66a5eff9a6cdcca9fcdd1534b0b670184b4af721ee46530fbd87aa28b995R141
Handle case when externalEtcdConfiguration is not defined in cluster spec.
=> Fix controller nil pointer error when cluster externalEtcdConfiguration not specified

pkg/executables/govc.go, pkg/executables/govc_test.go
Adding retries to govc preflight validations to minimize creation failures. 
Additional improvements for validations related to the template(library, tags, etc.) will be in a separate PR.
=> Add retries for govc preflight validations

controllers/buildspec.yml
We don't need this since the Makefile is at root.
=> Remove project path from cluster-controller buildspec

docs/content/en/docs/reference/clusterspec/vsphere.md, docs/content/en/docs/reference/vsphere/vsphere-prereq.md
Add more specific instructions on keeping control plane endpoint IP from being handed out by DHCP server
=> Exclude Control Plane Endpoint IP from DHCP

Makefile, cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, cmd/integration_test/cmd/run.go, config/manifest/eksa-components.yaml, internal/test/e2e/run.go, internal/test/e2e/setup.go, scripts/e2e_test_docker.sh, scripts/eksa_components_override.sh, test/framework/e2e.go
Sometimes, our PRs include changes to spec structs which would also be accompanied by changes in the `config/` folder. During every run of the E2E presubmit, the latest bundle from S3 is pulled down and is parsed to know what images to use and what manifests to apply for cluster creation. One of the steps in cluster creation is installtion of custom components and EKS-A CRDs that are defined in the `eksa-components.yaml` manifest from the bundle release. 
However due to local changes in spec, the eksa-components manifest that was pulled down from S3 will no longer work, since it corresponds to an outdated spec. This PR fixes that by detecting changes under `config/`, that imply that the spec CRD was changed, and generates a local compatible version of the eksa-components to be used in the …
=> Use local bundle release override when changing spec

cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/deletecluster.go, cmd/eksctl-anywhere/cmd/generatebundleconfig.go, cmd/eksctl-anywhere/cmd/supportbundle.go, cmd/eksctl-anywhere/cmd/upgradecluster.go, pkg/clients/flux/client.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/dependencies/testdata/cluster_vsphere.yaml, pkg/executables/builder.go, pkg/providers/factory/providerfactory.go, pkg/providers/factory/providerfactory_test.go
Resolves #310 
In order to facilitate adding/removing/changing the dependencies for our types and at the same time reduce the duplicated code/work at the `cmd` level (that's where we usually do DI), this OR add a factory to build a dependency graph.
It's a pretty simple implementation but it achieves:
* Only building whatever is necessary based on the input
* Only build each entity once
* Graph encapsulation (the caller doesn't need to know anything about the dependencies)
* Changing the graph is fairly simple
Some drawbacks:
* It requires to write a bit of boring code every time we want to add a new entity to the graph
* It requires to mark the dependencies for a certain entity explicitly (no inference)
There is definitely room for improvement but I believe the current state is good …
=> Dependency factory

controllers/controllers/resource/fetcher.go
Misleading log msg. Instead of "looking up cluster", the function looks up resource in a set of resource types.
=> Fix controller fetch cluster log

pkg/features/features.go, pkg/features/features_test.go, pkg/features/mutexmap.go, pkg/features/mutexmap_test.go
Closes #311 
This adds a little package to manage feature toggles. It uses envvars for now, but it could potentially be expanded to use anything else if necessary (I don't think it will)
=> Package for feature toggles

go.mod, go.sum
Bump up runc module to secure version.
=> Bump up go mods to mitigate vulnerability

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, internal/test/e2e/setup.go, test/framework/e2e.go
*Issue #, if available:* [#306](https://github.com/aws/eks-anywhere/issues/306)
For tests running in the e2e job, assign instanceID as the test name.
=> Assigned instanceID as the test name for e2e jobs

Makefile, pkg/constants/constants.go, pkg/diagnostics/analyzer_types.go, pkg/diagnostics/analyzers.go, pkg/diagnostics/collectors.go, pkg/diagnostics/interfaces.go, pkg/diagnostics/interfaces/mocks/diagnostics.go, pkg/diagnostics/interfaces/mocks/support.go, pkg/diagnostics/runsupportbundle.go, pkg/diagnostics/runsupportbundle_test.go
https://github.com/aws/eks-anywhere/issues/239
Add system to associate log text analyzers with logs collected from a given namespace.
Move namespace names to `constants` package.
Add initial log text analyzer for `capi-kubeadm-control-plane-system`, which checks for failed API server pods in the logs.
Log text analyzers parse the logs collected by the associated Collector for regex matches (or, alternatively, regex group matches -- see https://troubleshoot.sh/docs/analyze/regex/) and produce an outcome based on the result.
We can now add new entires to the `logTextAnalyzersMap` for each namespace; each of the associated analyzers will then be included if the logs for that namespace are being collected. This allows us to compose the log text analyzers based on the collectors that are …
=> add process for generating log text analyzers based on collectors present

docs/content/en/_index.html, docs/content/en/docs/concepts/clusterworkflow.md, docs/content/en/docs/getting-started/install/_index.md, docs/content/en/docs/getting-started/production-environment/_index.md, docs/content/en/docs/overview/_index.md, docs/content/en/docs/reference/vsphere/customize-ovas.md, docs/content/en/docs/reference/vsphere/vsphere-ovas.md, docs/content/en/docs/reference/vsphere/vsphere-prereq.md, docs/content/en/docs/tasks/cluster/cluster-flux.md, docs/content/en/docs/tasks/troubleshoot/_troubleshooting.md, docs/content/en/docs/tasks/workload/ingress.md, docs/content/en/docs/tasks/workload/loadbalance/kubevip/arp.md, docs/content/en/docs/tasks/workload/loadbalance/kubevip/bgp.md, docs/content/en/docs/tasks/workload/loadbalance/metallb.md, docs/content/en/docs/tasks/workload/test-app.md, docs/layouts/shortcodes/content.html
If we are going to support docs without github branches, these links need to be relative.
=> Make docs links relative

controllers/controllers/resource/fetcher.go, internal/test/cluster.go, pkg/cluster/fetch.go, pkg/cluster/fetch_test.go, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go
Resolves #313 
Move logic to get `Bundles` and build a cluster spec for a certain `Cluster` to the `cluster` package
=> Add centralized method to fetch Bundles for a particular Cluster

pkg/providers/vsphere/vsphere.go
If proxy is configured, the endpoints ".svc" are going through the proxy which shouldn't happen. This PR adds ".svc" to the default noProxy list so they don't go through the proxy
=> Add ".svc" to noProxy list

docs/content/en/docs/reference/security/_index.md, docs/content/en/docs/reference/security/kube-bench.md
Adding a section in docs for CIS benchmark self-assessment guide using Kube-bench.
=> Add CIS benchmark scan info to docs

pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_cp.yaml
For both BR and ubuntu, etcdadm bootstrap provider will accept proxy and registry mirror config fields. The etcdadm bootstrap provider controller configures the required files/commands for BR and cloudinit respectively ([merged PR](https://github.com/mrajashree/etcdadm-bootstrap-provider/pull/7) for reference)
=> Add registry mirror and proxy support for etcd

go.sum, release/go.mod, release/go.sum
Bumping up containerd mods to make Dependabot happy.
=> Bump up containerd mod to secure version

cmd/eksctl-anywhere/cmd/generateclusterconfig.go, pkg/clusterapi/upgrader.go, pkg/constants/constants.go, pkg/executables/clusterctl.go, pkg/executables/clusterctl_test.go, pkg/providers/docker/docker.go, pkg/providers/factory/providerfactory.go, pkg/providers/factory/providerfactory_test.go, pkg/providers/vsphere/vsphere.go, pkg/types/upgrades.go
This is part of #314 
In order to have smaller PRs, splitting this issue into multiple parts
This one adds the `upgrade apply` command wrapper to `clusterctl` and the skeleton for a `clusterapi` upgrader
The idea is that the `clusterapi.Upgrader` is a higher level entity that takes care of comparing versions and determine what has changed and needs to be upgraded. And `clusterctl` just generates the proper command to update those components to those specific versions
The `clusterapi.Upgrader` will probably be called from the upgrade workflow or from `ClusterManager` directly
=> Add upgrade wrapper for `clusterctl` and skeleton for `clusterapi` upgrader

config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, config/manifest/eksa-components.yaml, release/api/v1alpha1/bundle_types.go, release/cmd/release.go, release/config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, release/pkg/assets_capa.go, release/pkg/assets_capd.go, release/pkg/assets_capi.go, release/pkg/assets_cilium.go, release/pkg/assets_eksa_tools.go, release/pkg/assets_etcdadm_bootstrap.go, release/pkg/assets_etcdadm_controller.go, release/pkg/assets_flux.go, release/pkg/assets_vsphere.go, release/pkg/generate_spec.go, release/pkg/versions.go
Closes #312 
* Adds `Version` field to all components where it was missing
* Populates the `Version` field in all components with semver `vX.X.X+metadata`
=> Version with metadata for all component bundles

release/pkg/prepare_release.go, release/pkg/versions.go
Without this, the context of Git would be inside the CLI repo that's checked out by Codebuild for dev release, while the query path is in the build-tooling repo that is cloned locally. This would lead to errors of the form
```
fatal: <Build-tooling projectPath>: '<Build-tooling project path>' is outside repository at '<CLI repo root>
```
during release.
=> Change path to build-tooling repo before running git log

docs/content/en/docs/reference/artifacts.md
Update artifacts section in docs to reference the newly-generated OVAs for Ubuntu, along with EKS-D release tags on vCenter.
=> Update docs to point to latest OVAs

docs/content/en/docs/tasks/cluster/cluster-flux.md, pkg/api/v1alpha1/vspheremachineconfig_webhook.go, pkg/api/v1alpha1/vspheremachineconfig_webhook_test.go
To allow worker nodes update on fields:
- folder
- resourcePool
- datastore
- diskGiB
- numCPUs
- memoryMiB
- template
=> Fix VsphereMachineConfig Webhook validation on worker nodes

release/pkg/assets_capa.go, release/pkg/assets_capd.go, release/pkg/assets_capi.go, release/pkg/assets_certmanager.go, release/pkg/assets_etcdadm_bootstrap.go, release/pkg/assets_etcdadm_controller.go, release/pkg/assets_vsphere.go
- Adding version field to cert-manager bundle during generation.
- Make error messages more precise.
=> Generate version field for certmanager bundle

internal/pkg/ssm/command.go, internal/test/e2e/run.go, internal/test/e2e/setup.go
Add an option which adds CW logging to a ssm session run.
Logs will be output to the base log group, `/eks-anywhere/test/e2e`; if they have a 'parent job', in this case the job ID of the parallel configuration, it will be appended to the log group path; and then the job ID. So for a full path, it'd be like...
`/eks-anywhere/test/e2e/$JOB_ID/$JOB_ID_$TEST_NUMBER`
we will then be able to look at the logs for individual tests in isolation (solving the non-blocking io issue with print and goroutines which was messing with the ordering) and make it easier to look at non-truncated log outputs.
don't merge this yet, we need to ensure that the instance profile has sufficient permissions to write to the logstream
By submitting this pull request, I confirm that you can …
=> output logs to cw for e2e tests

pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_types_test.go, pkg/clustermanager/cluster_manager.go
When we check if the cluster config has changed (EKSAClusterSpecChanged), in order to determine if we need to upgrade or not, we use reflect.DeepEqual(cc.Spec, newClusterSpec.Spec)
Currently, that always returns false, because cc doesn’t have the management boolean (it’s a nil pointer) and newClusterSpec has it, bc we set it in the upgrade flow
- Add clusterSpec.Equal method that replaces DeepEqual
- Unit tests
=> Add clusterSpec.Equal method that replaces DeepEqual to compare spec

internal/test/e2e/run.go
We started using the 'jobId' as the CloudWatch log group name for the SSM jobs in e2e tests -- turns out, there's a `:` in those job IDs. This is a quick fix to address this right now, a follow-up pr will come with a regex to validate each section prior and default to no cw logging if the log groups are constructed incorrectly.
=> quick fix for integ test job name not matching cw log group

internal/test/e2e/cleanup.go
quick adjustment to ensure we're retaining test artifacts. 
this will ensure we're retaining the binaries (reproducable executions) alongside artifacts like the support bundle.
=> increase s3 object retention to one week

internal/pkg/ssm/command.go, internal/test/e2e/run.go, internal/test/e2e/setup.go
Fix SSM CW output.
By default, if CW logging is enabled, SSM run command outputs the logs to `/aws/ssm/SystemsManagerDocumentName` in the format:
```
CommandID/InstanceID/PluginID/stdout
CommandID/InstanceID/PluginID/stderr
```
Be default, it will create the log-group if it dosen't exist.
I thought this auto-creation would also happen with a user-specified log group. Turns out, that's not the case.
So, I've created the log group (already merged) and now we're just telling the SSM command to use that base log group, and the command execution should save the stdout and stderr as indicated above. 
so …
=> specify only base log group for SSM cw output

pkg/clustermanager/cluster_manager.go, pkg/executables/kubectl.go, pkg/providers/docker/docker.go, pkg/providers/docker/mocks/client.go, pkg/providers/vsphere/mocks/client.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
This commit includes two changes:
* Post upgrade eks-a waits for ControlPlaneReady and ManagedEtcdReady conditions
on the cluster. This check in the UpgradeCluster method in cluster_manager.go is
done on the workload cluster. In case of single management cluster, the workload
cluster in this method ends up being the management cluster itself since that maintains
all the CAPI objects. So this check will happen always only for the management cluster
instead of the target cluster undergoing upgrade.
This commit fixes this by passing the target workload cluster's name to the methods
that wait for the conditions post-upgrade
* Passes in the exact target cluster's name to retrieve the EtcdadmCluster CR
from the management cluster. This is how the KCP and MD objects are retrieved too
*Issue #, …
=> Fix cluster name used during upgrade for CAPI objects

pkg/clustermanager/cluster_manager_test.go
The `newClusterChangedTest` method in the cluster manager unit tests has been found to be useful for any test where the spec changes & we need to call `BuildSpecForCluster`. This PR renames this method to a more suitable name since it is now used for more than just the `...ClusterChanged` tests.
=> Rename clusterChanged method in unit tests

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/providers/vsphere/mocks/client.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
Update `vsphere-cloud-controller-manager` image manually after upgrades
Unfortunately, the capv controller doesn't do this even if we update the `VSphereCLuster`, so we need to do it manually for now
In new versions of the capv provider, this is not managed by the controller directly anymore but just with a `ClusterResourceSet`
Which means that adding update capabilities to the `ClusterResourceSe` controller and updating our capv provider version will solve this problem
=> Patch `vsphere-cloud-controller-manager` daemonset image

pkg/providers/docker/docker.go, pkg/providers/mocks/providers.go, pkg/providers/provider.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go, pkg/task/task.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
Sometimes, the spec doesn't change and there isn't a new eks-d release in the bundle. However, it's possible that some of the components in the bundle used by a provider have changed, and a new "upgrade" (just reapply the templates) is needed.
This PR adds a new method to providers to allow them to trigger upgrades even when cluster manager doesn't detect a change.
I think we should eventually move the provider specific code we have in cluster manager to these methods (that's why I added the `Context` as an argument), but I'll leave that refactor for a separate PR.
=> Add the ability for providers to trigger upgrades based on spec changes

pkg/diagnostics/analyzers.go, pkg/diagnostics/collectors.go, pkg/diagnostics/diagnostic_bundle.go, pkg/diagnostics/diagnostic_bundle_test.go, pkg/diagnostics/interfaces.go, pkg/diagnostics/interfaces/mocks/diagnostics.go
Previously, we assumed all clusters were self-managed when generating a support bundle.
Now, we check the `isSelfManaged()` method of the spec to determine if the we should collect and analyze management resources (CAPI crds, cluster crd, bundle, etc) when generating a support bundle for a cluster.
the method `WithManagementCluster(isSelfManaged bool)` will determine if a bundle uses the mgmt cluster collectors/analyzers or not.
generated default support bundles w/out spec input
generated support bundles w/spec input
generated support bundles for workload and management clusters
=> Support bundle for mgmt cluster

.gitignore, cmd/eksctl-anywhere/cmd/download.go, cmd/eksctl-anywhere/cmd/downloadartifacts.go, cmd/eksctl-anywhere/cmd/list.go, cmd/eksctl-anywhere/cmd/listovas.go, pkg/cluster/spec.go
This PR adds a command to list the OVA URLs corresponding to the Kubernetes version of the current EKS Anywhere cluster configuration along their checksums.
Sample output for `eksctl anywhere list ovas`:
```
$ eksctl anywhere list ovas -f eks-a-test.yaml
Bottlerocket:
SHA256: ...
SHA512: ...
URI: https://...
Ubuntu:
SHA256: ...
SHA512: ...
URI: https://...
```
Sample output for `eksctl anywhere download artifacts`:
```bash
$ eksctl anywhere download artifacts -f bin/arnchlm-test.yaml
$ ls *.tar.gz
eks-anywhere-downloads.tar.gz
$ tar -tzf eks-anywhere-downloads.tar.gz 
eks-anywhere-downloads
eks-anywhere-downloads/bundle-release.yaml
eks-anywhere-downloads/capi-kubeadm-bootstrap
eks-anywhere-downloads/capi-kubeadm-bootstrap/bootstrap-components.yaml …
```
=> Add commands to list OVAs and download artifacts used by EKS Anywhere

release/pkg/assets_cluster_controller.go
This PR refactors how we assign the git tag for cluster-controller project based on the release type.
For dev release, run `git describe --tag` to get the tag.
For staging and prod releases, we want the image/manifests for the cluster-controller to be aligned with the current CLI version, so we read it from the ReleaseVersion parameter.
=> Refactor git tag assignment for EKS-A cluster controller project

cmd/eksctl-anywhere/cmd/common.go, cmd/eksctl-anywhere/cmd/importimages.go, cmd/eksctl-anywhere/cmd/listimages.go
This commit adds a new generate subcommand called image-list, which
generates a file containing all images and their checksums that are used
by EKS-Anywhere.
Command: 
```
./bin/eksctl-anywhere list images -f eks-a.yaml
```
Generates a list of all images used in this format:
```
imageRepository/imageName:imageTag@imageDigest
```
for instance:
```
public.ecr.aws/l0g8r8j6/eks-anywhere-cli-tools:v0.1.0-eks-a-v0.0.0-dev-build.312@sha256:817b1278165ae65bf051e556fcd983c984b49de02ed01566f8ce1ed4e5415424
```
This way `docker pull` can be run directly against each image from the output only the expected checksums from the release manifests will get used
*Issue #, if available:* https://github.com/aws/eks-anywhere/issues/476
By submitting this pull request, I confirm that …
=> Add command to generate a list of images used by eks-anywhere

go.mod, go.sum, release/go.mod, release/go.sum
The EKS-D release API was [updated](https://github.com/aws/eks-distro-build-tooling/commit/7cedd37fb487e9e5b5c629d2b69e3815b3b3285f) to add image digests, so we need to modify the EKS-A go mods to consume the latest version of that module.
=> Update EKS-D module version to consume API updates

pkg/clusterapi/upgrader.go, pkg/clusterapi/upgrader_test.go
This is mostly for completion and correctness, but `clusterctl` doesn't need this info. It will help with logging and with a future `upgrade plan` command
=> Generate cert-manager changediff from capi upgrader

internal/pkg/ssm/command.go, internal/test/e2e/oidc.go, internal/test/e2e/registryMirror.go, internal/test/e2e/run.go, internal/test/e2e/setup.go
bubble up the SSM command id from the execution of each test run, and include it in the final log message for completed tests. This is useful for indexing various things include the CW log streams generated by each command
=> log SSM command ID in e2e test run outcome

pkg/providers/docker/docker.go, pkg/providers/docker/docker_test.go, pkg/providers/vsphere/vsphere.go
Added the check for bundles version change when deciding if we need a new template for etcd and worker machines
=> Add bundles version check for etcd and workload template update

cmd/eksctl-anywhere/cmd/deletecluster.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/executables/kubectl.go, pkg/providers/docker/docker.go, pkg/providers/mocks/providers.go, pkg/providers/provider.go, pkg/providers/vsphere/mocks/client.go, pkg/providers/vsphere/vsphere.go, pkg/workflows/delete.go, pkg/workflows/delete_test.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go
Delete EKSA resources when deleting a workload cluster (GitOpsConfig, OIDCCOnfig, VSphereMachineConfig and VsphereDatacenterconfig)
=> Clean up EKSA resources

pkg/api/v1alpha1/gitopsconfig_webhook.go, pkg/api/v1alpha1/gitopsconfig_webhook_test.go
To upgrade a GitOps enabled cluster with the new 0.6.0 release, we need to manually update the Git repo file structure with GitOpsConfig's clusterConfigPath field change.
=> Make Flux clusterConfigPath mutable during upgrade through controller

pkg/clusterapi/installer_test.go, pkg/executables/kubectl_test.go
https://github.com/aws/eks-anywhere/issues/569
=> Add unit tests for capi installer and kubectl get provider

docs/content/en/docs/reference/changelog.md
Small fix to remove duplicate heading from this page.
=> Removed extra heading from Whats New page

pkg/executables/executables.go
All eksa commands run inside docker using the mr-tools image.
When creating management cluster, users only have to specify a spec file,
and the cli will mount tha path that contains the spec as a volume to be
used by the mr-tools image.
With the introduction of workload clusters, users can pass an extra flag (--kubeconfig)
that points to the kubeconfig of a management cluster.
If this kubeconfig is not in the same path as the spec then it is necessary to
mount an extra volume to make it availalbe for the cli.
Fix #581
=> Mount extra volume when necessary

release/Makefile
Make the AWS_REGION overrideable from environment variables.
=> Set AWS_REGION only when there is no env var set

docs/content/en/docs/community/contributing.md
LICENCE was pointing to a url which was not available. Corrected the URL.
=> Doc change : Add correct url for LICENCE

internal/pkg/api/cluster.go, test/e2e/flux_test.go, test/e2e/oidc_test.go, test/e2e/proxy_test.go, test/e2e/registry_mirror_test.go, test/e2e/simpleflow_test.go, test/e2e/stackedetcd_test.go, test/e2e/upgrade_test.go, test/e2e/vsphere_autoimport_test.go, test/e2e/workload_clusters_test.go, test/framework/cluster.go, test/framework/commands.go, test/framework/conformance.go, test/framework/flux.go, test/framework/git.go, test/framework/multicluster.go, test/framework/oidc.go, test/framework/proxy.go, test/framework/registryMirror.go, test/framework/vsphere.go, test/framework/workload.go
First take for adapting our e2e test framework to management+workload clusters
The changes are lengthy but super super simple, I recommend going commit by commit, that will make the review way easier
Some ideas:
* This uses the same patterns and syntax that we are used to for self managed clusters, but applied to multicluster tests.
* Management and workload clusters are defined the same way.
* Operations over clusters syntax is the same (`CreateCluster` `DeleteCluster`, etc.).
* All the code to validate single cluster tests will work here as well, hopefully transparently
* This should make writing new tests for workload clusters almost a copy paste excercise
* A multicluster test allows for one management cluster and multiple workload clusters
I added a "demo" …
=> Multiclusters E2E test framework

docs/content/en/docs/reference/changelog.md
We only want to keep the unreleased section for the main branch and not listed on the public website.
=> Remove unreleased section for v0.6.0 branch

cmd/integration_test/build/buildspecs/conformance-eks-a-cli.yml, cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, release/buildspecs/bundle-release.yml, release/buildspecs/dev-release.yml, release/buildspecs/eks-a-release.yml
- As of [this](https://github.com/aws/eks-distro-build-tooling/commit/7943b5b81b1f499efcbdc3c090440cfa3e431418) commit, the function calls to start the Docker daemon have been removed from this script. So it needs to be sourced and run.
- Skopeo doesn't need the Docker daemon to be running during copy operations, so we don't need it in the release buildspecs.
=> Remove/refactor Docker script invocation in buildspecs

cmd/integration_test/build/buildspecs/conformance-eks-a-cli.yml, cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, cmd/integration_test/build/script/setup_profile.sh, cmd/integration_test/build/script/start_docker.sh
The AWS config setup profile needs to be sourced, while the Docker startup script needs to be run directly.
=> Source AWS profile setup script in buildspec

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/executables/kubectl.go
When creating a workload cluster from a management cluster, the generated aws-iam-authenticator Kubeconfig was using the TLS cert of the management cluster and not the workload cluster. Fix to pass in the right cluster name.
=> Workload cluster tls cert fix for iam-auth kubeconfig

cmd/eksctl-anywhere/cmd/common.go, cmd/eksctl-anywhere/cmd/downloadartifacts.go, cmd/eksctl-anywhere/cmd/generatebundleconfig.go, cmd/eksctl-anywhere/cmd/importimages.go, cmd/eksctl-anywhere/cmd/listovas.go, cmd/eksctl-anywhere/cmd/options.go, cmd/eksctl-anywhere/cmd/supportbundle.go, internal/test/cluster.go, pkg/cluster/manifest_reader.go, pkg/cluster/spec.go, pkg/cluster/spec_test.go, pkg/files/reader.go, pkg/files/reader_test.go, pkg/files/testdata/file.yaml
It had become a bit difficult to work with, we had added too many things and we came up with a bunch of usecases to read different manifests that didn't necessary require the `Spec`
* Move the low level logic to `files.Reader`
* Move the logic to read manifests (`Release`, `Bundles` and eks-d release) to `cluster.ManifestReader`
=> Small refactor to make cluster.Spec smaller and more reusable

docs/content/en/docs/reference/clusterspec/gitops.md, pkg/addonmanager/addonclients/fluxaddonclient.go, pkg/addonmanager/addonclients/fluxaddonclient_test.go, pkg/addonmanager/addonclients/testdata/cluster-config-default-path-management.yaml, pkg/addonmanager/addonclients/testdata/cluster-config-default-path-workload.yaml, pkg/api/v1alpha1/gitopsconfig_types.go, pkg/cluster/spec.go, pkg/clustermarshaller/testdata/expected_marshalled_cluster.yaml, pkg/executables/flux.go, pkg/executables/flux_test.go, pkg/validations/createvalidations/gitops.go, pkg/validations/createvalidations/gitops_test.go
Update gitops clusterConfigPath definition to be the root both management and its workload clusters
#551 
- make default clusterConfigPath values same between 0.5.0 and 0.6.0
- update flux bootstrap code to reflect changes
- update create validation so that workload cluster's clusterConfigPath has to be the same as management's
- update flux doc
=> Update gitops clusterConfigPath definition

pkg/addonmanager/addonclients/fluxaddonclient.go
=> Only check flux clusterConfigPath exists when bootstrapping management cluster

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml
Currently, the tests generate random IPs for cp endpoint within the entire subnet range, which can conflict with the DHCP range. This can result in a situation where the DHCP can assign the same IP to other machines which can cause problems.
In this PR, I'm restricting the CIDR range for generating random IPs to avoid conflicts with DHCP.
CIDR `x.x.128.0/17` corresponds to IP range `x.x.128.0-x.x.255.255` which is outside the DHCP ranges for both networks
=> Use controlplane endpoint IPs outside DHCP ranges for e2e

pkg/providers/docker/config/template-cp.yaml, pkg/providers/docker/testdata/capd_valid_full_oidc_cp_expected.yaml, pkg/providers/docker/testdata/capd_valid_minimal_oidc_cp_expected.yaml, pkg/providers/docker/testdata/no_machinetemplate_update_cp_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_expected.yaml, pkg/providers/docker/testdata/valid_deployment_custom_cidrs_cp_expected.yaml, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_external_etcd_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_full_oidc_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_no_machinetemplate_update_cp.yaml, pkg/providers/vsphere/testdata/expected_results_minimal_cp.yaml, pkg/providers/vsphere/testdata/expected_results_minimal_oidc_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/original_077.yaml
Api server creates the audit log file under the parent directory provided in the api-server argument `--audit-log-path`. Api server handles log rotation as well. If the file already exists, api server runs into an error when trying to rename the log file to enable rotation.
Before this change, api-server logs would have the following error message and would not do any log rotation on audit logs.
```
E1115 19:51:34.586712       1 metrics.go:110] Error in audit plugin 'log' affecting 1 audit events: can't rename log file: rename /var/log/kubernetes/api-audit.log /var/log/kubernetes/api-audit-2021-11-15T19-51-34.586.log: device or resource busy
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
=> Remove log file create for api-server audit logs

pkg/providers/docker/docker.go, pkg/providers/mocks/providers.go, pkg/providers/provider.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go, pkg/task/task.go, pkg/task/task_test.go, pkg/workflows/create.go, pkg/workflows/delete.go, pkg/workflows/delete_test.go, pkg/workflows/diagnostics.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
Include the fix for diagnostic bundle collection during setup and validation in the 0.6.1 patch release
3992ec57de953137f10ebcb8360dd2768d19e1db
* remove unused provider infrastucture cleanup method
* add common diagnostic collection workflow task
* add diagnostic collection tasks to create workflow
* add diagnostic collection tasks to delete workflow
* add diagnostic collection tasks to upgrade workflow
* update tests
* gofmt changed files
* adjust tests after merge from main
* remove unused rollback functionality from tasks and workflows
* decompose Diagnostics task into WC and MG diag tasks
* remove 'rollback' tasks form create workflow
* rename common to diagnostics
* remove unused delete-kind-cluster block from create workflow
* remove error check from bootstrap cluster delete …
=> Add diagnostic collection workflow task (#606)

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_types.go
So that `eksctl-anywhere generate clusterconfig` won't include `default` namespace for cluster resource.
=> Update NewClusterGenerate not use ConvertConfigToConfigGenerateStruct

pkg/api/v1alpha1/cluster.go, pkg/crypto/tls.go, pkg/crypto/tls_test.go
Environment variable `EKSA_REGISTRY_MIRROR_CA` was not being used to validate the cert. This was causing the CLI to fail validations in case of self-signed certs. This PR fixes that issue
=> fix issue with using EKSA_REGISTRY_MIRROR_CA env var

pkg/api/v1alpha1/cluster.go, pkg/cluster/spec.go, pkg/crypto/tls.go, pkg/crypto/tls_test.go
Pull the following changes for to the release branch to cut a patch release:
#639 
#641 
=> Add registry mirror env var and import-images bug to 0.6 patch release

internal/pkg/files/files.go, pkg/semver/semver.go, test/framework/releaseVersions.go
This PR allows us to extract the binary of the desired EKS-A release version for E2E tests.
We also changed the compare function in the semver package to increase its readability.
=> Get binary for specific version of EKS-A release in E2E tests

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml, pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_types_test.go, pkg/providers/docker/config/template-cp.yaml, pkg/providers/docker/docker.go, pkg/providers/docker/docker_test.go, pkg/providers/docker/testdata/valid_deployment_cp_pod_iam_expected.yaml, pkg/providers/vsphere/testdata/expected_results_pod_iam_config.yaml, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
*Issue #, if available:* https://github.com/aws/eks-anywhere/issues/601
*Description of changes:* EKS-A users can leverage the IAM Role for Service Account (IRSA) feature following the [special instructions for DIY Kubernetes](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md) to enable AWS authentication. This commit enables that by allowing the configuration of service-account-issuer flag for kube-apiserver with the identity issuer URL as per the self-hosted setup guide.
=> Accept service account issuer for Pod based IAM

pkg/clusterapi/extraargs.go, pkg/clusterapi/extraargs_test.go, pkg/providers/docker/config/template-cp.yaml, pkg/providers/docker/docker.go, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/vsphere.go
The commit changes how the extra arg for Pod IAM gets added to the api-server.
It uses the existing methods for appending extraArgs.
For reference this was the original PR that added this flag: https://github.com/aws/eks-anywhere/pull/640
It contains unit tests for generating template with pod iam config configured
=> Use ExtraArg functions to add service-account-issuer for api-server

README.md, docs/developer/cherry-picks.md, hack/cherry_pick_pull.sh
We pulled this from upstream for use in eks-anywhere-build-tooling.  You can see an example PR that was opened using the script here https://github.com/aws/eks-anywhere-build-tooling/pull/61.
Added doc to the docs/developer folder, not sure if this is the best spot for development docs or not?  This obviously doesn't need to show up on the docs website.
=> add cherry-pick-pull from upstream along with docs for backporting

release/Makefile, release/cmd/release.go, release/pkg/file_reader.go, release/pkg/generate_spec.go, release/pkg/prepare_release.go, release/scripts/bundle-release.sh, release/scripts/eks-a-release.sh, release/scripts/release.sh
The branch name env variables will be set when the release pipeline is triggered, and will override the default values set in the Makefile.
/hold for CDK changes.
=> Pass in source branch information to release process

pkg/diagnostics/collectors.go, pkg/diagnostics/diagnostic_bundle.go, pkg/diagnostics/diagnostic_bundle_test.go, pkg/diagnostics/interfaces.go, pkg/diagnostics/interfaces/mocks/diagnostics.go
Add diagnostic collectors based on datacenter type, including the CAPV system namespace which was missing. 
=> add diagnostic collectors based on datacenter type

pkg/executables/govc.go, pkg/executables/govc_test.go
Setting `GOVC_PERSIST_SESSION=false` to prevent multiple sessions to be created during cli execution.
=> Enabling GOVC_PERSIST_SESSION for all govc commands

pkg/diagnostics/collectors.go
add capv and eks-a vsphere specific CRDs to the crd collection routine
=> add vsphere crd collectors to diagnostic bundle collection

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml
The current private network cidr for e2e conflicts with the VPN connection. Changing this to avoid the conflict and fix the private network tests.
=> Change the private network cidr

test/framework/flux.go
- remove duplicate setting for branch
- set default namespace to "default" instead of "main"
- set default branch to "main" instead of "default"
=> Update Flux e2e cofig default setting

internal/test/e2e/setup.go
If the bundle override is present, check for a components override; if it is present, add it to the required files; otherwise, warn.
This is so that we can use a bundle override in release branch e2e test execution while retaining the functionality needed to test component changes locally. 
=> Required test upload mods

release/Makefile, release/README.md, release/cmd/release.go, release/pkg/clients.go, release/pkg/file_reader.go, release/pkg/generate_spec.go, release/pkg/prepare_release.go, release/runbook.md, release/scripts/release.sh, release/scripts/setup.sh
This PR adds logic to generate a bundle manifest spec locally to visualize changes to release tooling. The dry-run mode will skip the artifacts download and upload, and only print the resulting manifest.
=> Add dry-run mode for local bundle manifest generation

Makefile, controllers/build/create_binaries.sh, controllers/docker/linux/eks-anywhere-cluster-controller/Dockerfile
This adds arm64 builds of both the controller and cli.  We are doing testing with arm on linux with the hope to one day support arm based macs for at least running the bootstrap kind cluster (if not a full capd based cluster).  This is one of the last components which need an arm build.
Note, this makefile could use some cleanup, esp with some of the techniques we have started using in the build tooling repos.  I plan on make a pass at it in a future PR.  For now, I added to the mess a bit...
=> enable arm builds of controller and cli

config/manifest/eksa-components.yaml, internal/test/e2e/setup.go
This PR re-adds Dan's changes from #690, which were reverted in #697. It also adds a tiny fixup to the filepath that was being `stat`ed in that commit.
*Note:* Split into two commits for showing authorship.
=> Fix filepath for checking presence of local EKS-A components

docs/content/en/docs/tasks/cluster/cluster-upgrades.md
Manual step is no longer needed after v.0.6.1.
=> Remove flux manual steps in upgrade doc

cmd/eks-a-tool/cmd/validatecluster.go, cmd/eks-a-tool/cmd/versions.go, cmd/eks-a-tool/cmd/vspherermvms.go, cmd/eksctl-anywhere/cmd/cleanup.go, cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/deletecluster.go, cmd/eksctl-anywhere/cmd/generatebundleconfig.go, cmd/eksctl-anywhere/cmd/options.go, cmd/eksctl-anywhere/cmd/supportbundle.go, cmd/eksctl-anywhere/cmd/upgradecluster.go, internal/test/e2e/vsphere.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/executables/awscli.go, pkg/executables/builder.go, pkg/executables/clusterawsadm.go, pkg/executables/clusterctl.go, pkg/executables/docker.go, pkg/executables/dockercontainer.go, pkg/executables/dockerlinux.go, pkg/executables/executables.go, pkg/executables/flux.go, pkg/executables/govc.go, pkg/executables/kind.go, pkg/executables/kubectl.go, pkg/executables/mocks/executables.go, pkg/executables/sonobuoy.go, pkg/executables/troubleshoot.go, pkg/types/closer.go, test/framework/executables.go
Before this, we were creating a new container for every command and destroying it after running it.
This is a tentative attempt at trying to reuse containers. It will create a long running container in the background during initialization and use the same one for every command.
Once the CLI is done, it will destroy the container and the volumes.
This opens the option to doing things like sharing the same vsphere auth session between multiple `govc` commands.
PD: sorry for the long PR, reviewing commit by commit might help
=> Reuse executable container

cmd/eksctl-anywhere/cmd/deletecluster.go, test/framework/cluster.go
When running `create` and `upgrade` on a release branch, we use a bundle-override to specify the bundle associated with the release. However, we don't do this when running `delete`, as the option didn't even exist. This PR adds the option and configures the tests to use the correct bundle override when executing `delete` cluster. This way, we have a consistent execution throughout the E2E tests. This may be related to delete failures in the current release branch tests which show CAPI move and flux cleanup failing in unexpected ways.
=> use bundle override for delete cluster calls

cmd/eksctl-anywhere/cmd/deletecluster.go, test/framework/e2e.go
Backport bundle override in delete cluster calls in e2e tests to 0.6
=> use bundle override for delete cluster calls (#695)

Makefile, cmd/integration_test/build/script/upload_artifacts.sh, release/pkg/assets_cli.go
The current make target for arm overwrites the amd binary when running the cross platform target. This will separate out the builds and also only upload the binaries that are supported for tests.
=> Add arch folders for building cross platform binary

controllers/controllers/resource/fetcher.go, controllers/controllers/resource/fetcher_test.go, controllers/controllers/resource/reconciler_test.go, controllers/controllers/resource/template.go, controllers/main.go, go.sum, pkg/clusterapi/resourceset.go, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/providers/docker/docker.go, pkg/providers/docker/docker_test.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go, pkg/validations/createvalidations/cluster_test.go, pkg/validations/upgradevalidations/cluster_test.go, pkg/validations/upgradevalidations/preflightvalidations.go
*Issue #, if available:* https://github.com/aws/eks-anywhere/issues/634
This PR renames import aliases used for capi/capv/etcdadm to make it generic across versions. This is just to minimize changes required when upgrading to newer api versions. This does not affect any functionality. This is same as how these packages are imported upstream in [capi](https://github.com/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/controllers/controller.go#L32-L35) and [capv](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/controllers/vspherecluster_controller.go#L25-L38) 
=> Make capi import aliases generic across versions

Makefile, cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, cmd/integration_test/build/script/upload_artifacts.sh, scripts/e2e_test_docker.sh
* Fix shasum computation path
* Using S3 `cp` dry-run option in e2e presubmits to verify the upload paths
=> Fix shasum generation in artifacts upload script

go.sum, release/go.mod, release/go.sum
Bump up Go mods and remove cyclic depdendency of release module on main module.
=> Fix go mod pseudoversions and remove cyclic dependency

release/pkg/generate_spec.go
The key already has a slash prefix.
=> Fix dev release bundle manifest url generation

release/pkg/generate_spec.go
For images not present in the bundle manifest, we can bump them to the current dev release version.
=> Handle images not present in bundle manifest

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go
We normally wait 60m for control plane to be ready. However after we move cluster management, we only wait for 5m. This causes some premature failures so bumping the moveCAPIWait time to 15m 
=> Use longer wait time when waiting for control plane to be ready after move

release/cmd/release.go, release/pkg/assets_bottlerocket_bootstrap.go, release/pkg/assets_capa.go, release/pkg/assets_capd.go, release/pkg/assets_capi.go, release/pkg/assets_certmanager.go, release/pkg/assets_cilium.go, release/pkg/assets_cli.go, release/pkg/assets_eksa_tools.go, release/pkg/assets_eksd.go, release/pkg/assets_etcdadm_bootstrap.go, release/pkg/assets_etcdadm_controller.go, release/pkg/assets_flux.go, release/pkg/assets_kindnetd.go, release/pkg/assets_vsphere.go, release/pkg/clients.go, release/pkg/file_reader.go, release/pkg/generate_spec.go, release/pkg/prepare_release.go
The methods to set artifacts parameters like S3/ECR URIs were being called twice, once in `GenerateBundleArtifactsTable` and again for each bundle where that artifact is required. This PR refactors the code to only call it once, for the inital artifacts table generation, after which the generated table is re-used.
Additional changes:
* Beautified release output with demarcated sections and success icon
* Minor renames of methods
[Sample output](https://prow.eks.amazonaws.com/log?container=test&id=1466117328339996672&job=eks-anywhere-release-tooling-presubmit)
=> Avoid redundant method invocations during release

test/framework/vsphere.go
The multi-cluster E2E test always fails because when creating the second cluster, it tries to use the host IP from the `T_VSPHERE_HOST` env var. However, that IP is already in use by the first cluster so it fails. This adds a check to only use the IP from the env var if it is unique, if not it will generate a new one. 
=> Make sure IP is unique in e2e tests

release/pkg/assets_bottlerocket_bootstrap.go, release/pkg/assets_cluster_controller.go, release/pkg/assets_eksd.go, release/pkg/file_reader.go, release/pkg/generate_spec.go
* Adding the git tag so that the `strings.NewReplacer` works properly.
* Adding branch name to dev release version if not releasing from `main`.
* Remove dry-run check for generating release version since we have replaced S3 API calls with `HEAD` requests.
=> Add git tags to EKS-A cluster controller and kind image options

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go
=> Use longer wait time when waiting for control plane to be ready (#734)

pkg/addonmanager/addonclients/fluxaddonclient.go, pkg/addonmanager/addonclients/fluxaddonclient_test.go
Use the correct repository path when deleting a workload cluster
#751
=> Use correct repository path when deleting workload cluster

release/pkg/artifacts_types.go, release/pkg/assets_bottlerocket_bootstrap.go, release/pkg/assets_capa.go, release/pkg/assets_capd.go, release/pkg/assets_capi.go, release/pkg/assets_capv.go, release/pkg/assets_certmanager.go, release/pkg/assets_cilium.go, release/pkg/assets_cluster_controller.go, release/pkg/assets_cri_tools.go, release/pkg/assets_diagnostic_collector.go, release/pkg/assets_eksa_tools.go, release/pkg/assets_eksd.go, release/pkg/assets_etcdadm.go, release/pkg/assets_etcdadm_bootstrap.go, release/pkg/assets_etcdadm_controller.go, release/pkg/assets_flux.go, release/pkg/assets_kindnetd.go, release/pkg/assets_kube_rbac_proxy.go, release/pkg/assets_kube_vip.go, release/pkg/assets_local_path_provisioner.go, release/pkg/assets_vsphere.go, release/pkg/assets_vsphere_cloud_provider.go, release/pkg/assets_vsphere_csi.go, release/pkg/file_reader.go, release/pkg/file_reader_test.go, release/pkg/generate_spec.go, release/pkg/prepare_release.go, release/pkg/versions.go
When performing dev release, artifacts for some branches may be sourced from `main` if they don't exist in the branch that triggered the release. The support for using those artifacts was added in #744. In the same vein, this PR adds logic to set the bundle version based on the branch the bundle's artifacts were sourced from.
=> Assign bundle version based on branch artifact was built from

docs/content/en/docs/reference/changelog.md, pkg/clusterapi/extraargs.go, pkg/clusterapi/extraargs_test.go, pkg/crypto/tls.go, pkg/crypto/tls_test.go, pkg/providers/docker/config/template-cp.yaml, pkg/providers/docker/docker.go, pkg/providers/docker/testdata/capd_valid_full_oidc_cp_expected.yaml, pkg/providers/docker/testdata/capd_valid_minimal_oidc_cp_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_pod_iam_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_taints_expected.yaml, pkg/providers/docker/testdata/valid_deployment_custom_cidrs_cp_expected.yaml, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_external_etcd_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_no_machinetemplate_update_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_with_taints_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_pod_iam_config.yaml, pkg/providers/vsphere/vsphere.go
Adding support for passing in cipher suites to external etcd. Continuation from #657 
Moved string generation to crypto package to be able to use that function directly instead of through cluster-api package.
=> Add support for secure cipher suites with external etcd

docs/content/en/docs/reference/changelog.md, pkg/clusterapi/extraargs.go, pkg/clusterapi/extraargs_test.go, pkg/crypto/tls.go, pkg/crypto/tls_test.go, pkg/providers/docker/config/template-cp.yaml, pkg/providers/docker/docker.go, pkg/providers/docker/testdata/capd_valid_full_oidc_cp_expected.yaml, pkg/providers/docker/testdata/capd_valid_minimal_oidc_cp_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_pod_iam_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_taints_expected.yaml, pkg/providers/docker/testdata/valid_deployment_custom_cidrs_cp_expected.yaml, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_external_etcd_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_no_machinetemplate_update_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_with_taints_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_pod_iam_config.yaml, pkg/providers/vsphere/vsphere.go
This reverts commit 1f57eec1434b9f974cf337532a81e380621fc0b3.
Tests are failing so need to see if these changes are causing it.
=> Revert "Add support for secure cipher suites with external etcd (#759)"

docs/content/en/docs/reference/changelog.md, pkg/clusterapi/extraargs.go, pkg/clusterapi/extraargs_test.go, pkg/crypto/tls.go, pkg/crypto/tls_test.go, pkg/providers/docker/config/template-cp.yaml, pkg/providers/docker/docker.go, pkg/providers/docker/testdata/capd_valid_full_oidc_cp_expected.yaml, pkg/providers/docker/testdata/capd_valid_minimal_oidc_cp_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_pod_iam_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_taints_expected.yaml, pkg/providers/docker/testdata/valid_deployment_custom_cidrs_cp_expected.yaml, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_external_etcd_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_no_machinetemplate_update_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_with_taints_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_pod_iam_config.yaml, pkg/providers/vsphere/vsphere.go
Tested locally and it seems to be working as expected. Just need to make sure we release the cluster controller image and ensure that it is being used. Can merge https://github.com/aws/eks-anywhere/pull/782 after this PR to trigger that build too
=> Redo "Add support for secure cipher suites with external etcd (#759)"

pkg/executables/govc.go, pkg/executables/govc_test.go, pkg/executables/sync_slice.go, pkg/providers/vsphere/defaults.go, pkg/providers/vsphere/mocks/client.go, pkg/providers/vsphere/paths.go, pkg/providers/vsphere/setup.go, pkg/providers/vsphere/validator.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
* Move the logic to validate vcenter setup to the `validator`
* Remove side effects, all the code updating the vsphere api structs now is in the `defaulter`
* Prevents modifying global vars in runtime (store required env vars in `govc` struct)
=> Govc validate vcenter no side effects

Makefile
if the CODEBUILD_SOURCE_VERSION is not set, use 'release-0.6' and the corresponding bundle; if it is set, use standard bundle.
=> Backport select bundle based on branch

pkg/providers/vsphere/vsphere_test.go
All the tests still run by default (including `make unit-tests`. `go test` and prow jobs
If you want to skip the vsphere slow tests, add `-short` to your go test command
=> Add ability to skip slow vsphere tests

pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/executables/govc.go
This prevents execs for docker clusters to try to logout from vCenter
Drawbacks: it duplicates the logic around the datacenter type and it bleeds out of the provider factory what are the dependencies of each provider
The other option is to get rid of the provider factory and move the logic to the dependency factory
=> Avoid building all deps for all providers

cmd/eksctl-anywhere/cmd/validations.go, pkg/validations/docker.go
When running on Mac, check if Docker Desktop version is less than `4.3` before proceeding with cluster creation.
Addresses #792
=> Validate Docker desktop version on Mac

pkg/dependencies/factory.go
Avoid attempting to close un-instantiated dependencies (leading to segfault)
=> add nil check to dependency closer to avoid segfault

cmd/eksctl-anywhere/cmd/cleanup.go, cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/deletecluster.go, cmd/eksctl-anywhere/cmd/upgradecluster.go
This will change the cleanup function to use a pointer to an error.
The cleanUp function is currently deleting the "generated" folder because the "commandErr" parameter is always nil.
the previous code was following this pattern
```
if err != nil {
return err
}
defer cleanup(ctx, deps, err)
err := update|create|deleteCluster(...)
```
the problem is that the deferred call's arguments are evaluated immediately, so commandErr (inside the cleanup function) was always nil
=> Fix cleanup function

Makefile, cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, cmd/integration_test/build/script/upload_artifacts.sh, scripts/e2e_test_docker.sh
* Removing cross-platform builds in e2e presubmits
* Faking cross-platform folder structure to support tarball creation/upload dry-run
* Parametrize os and archs for tarball creation, so we can pass in different list per usecase
=> Parametrize os and arch list to upload script

pkg/dependencies/factory.go
temporal solution. Prevents:
```
180 panic: runtime error: invalid memory address or nil pointer dereference
181 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16bbe2b]
182
183 goroutine 1 [running]:
184 github.com/aws/eks-anywhere/pkg/executables.(*Docker).Close(0x0, 0x1f326c8, 0xc00004c028, 0x0, 0x0)
185         <autogenerated>:1 +0x2b
```
=> Prevent nil pointer by checking for nil in interface value

internal/test/e2e/ipmanager.go
Adding Interface key for `logger.Info` during e2e generate IP
=> Adding object key to logger info

cmd/eksctl-anywhere/cmd/upgradeplan.go, pkg/addonmanager/addonclients/upgrader.go
#499 
Move the flux check inside `FluxChangeDiff` method.
=> Move flux check to avoid repetitive checks

cmd/eksctl-anywhere/cmd/upgradeplan.go, pkg/clusterapi/upgrader.go
#499 
Upgrade plan displaying CAPI components.
=> Upgrade plan for CAPI components

test/framework/cluster.go
Was getting the following error, possibly after our cluster-name validation got fixed here https://github.com/aws/eks-anywhere/pull/781. Not sure why it was only seen locally instead of in our test infra.
```
cluster.go:289: Running shell command [ eksctl anywhere generate clusterconfig 53ee980-eksa-test -p vsphere > cluster.yaml ]
Error: 53ee980-eksa-test is not a valid cluster name, cluster names must start with lowercase/uppercase letters and can include numbers and dashes. For instance 'testCluster-123' is a valid name but '123testCluster' is not. 
Usage:
anywhere generate clusterconfig <cluster-name> (max 80 chars) [flags]
Flags:
-h, --help              help for clusterconfig
-p, --provider string   Provider to use (vsphere or …
```
=> Change generated cluster name order for tests

controllers/controllers/reconciler/main_test.go, controllers/controllers/reconciler/reconcile.go, controllers/controllers/reconciler/reconcile_test.go, controllers/controllers/reconciler/yaml.go, controllers/controllers/reconciler/yaml_test.go, internal/test/envtest/environment.go
* Utils to reconcile yaml manifests and generic `client.Object` by using server side apply
* Utils to convert a yaml manifest to individual objects accepted by the controller client
* Helper method in `envtest` to create a namespace for a test and clean it up after the test. This is super useful when sharing the same environment among multiple tests since it avoids most of the overlap problems (except for tests that need specific namespaces).
=> Controller reconcile utils

Makefile, config/crd/bases/anywhere.eks.amazonaws.com_tinkerbelldatacenterconfigs.yaml, config/crd/bases/anywhere.eks.amazonaws.com_tinkerbellmachineconfigs.yaml, config/manifest/eksa-components.yaml
- Adding Tinkerbell Datacenter config and machine config manifests.
- Add Tinkerbell bundle to EKS-A components manifest.
=> Add Tinkerbell CRDs and update EKS-A components manifest

release/pkg/assets_capt.go
Adding Image override for CAPT to override manifest.
=> Adding image override for CAPT image uri

cmd/integration_test/build/buildspecs/build-eks-a-cli.yml
with this there, we're not using the built-in release bundle, but rather the prod bundle. This may effect the tests.
=> Remove Get Bundle script invocation from 0.6 e2e tests

pkg/validations/docker.go
Incorrect log invocation with odd number of params. Changed to `logger.Error`
Added return to avoid doing the memory comparison in the error scenario
=> Avoid panic from logger with incorrect number of params

Makefile, config/crd/kustomization.yaml, config/manifest/eksa-components.yaml
Adding Tinkerbell CRDs to the EKS-A components yaml manifest.
=> Add Tinkerbell CRDs to EKS-A components yaml

cmd/eks-a-tool/cmd/validatecluster.go, cmd/eks-a-tool/cmd/versions.go, cmd/eks-a-tool/cmd/vspherermvms.go, internal/test/e2e/vsphere.go, pkg/dependencies/factory.go, pkg/executables/builder.go, pkg/executables/dockercontainer.go, pkg/executables/executables.go, pkg/executables/govc.go, pkg/executables/mocks/executables.go, test/framework/executables.go
* Decouples closing executables from closing the long running container. This allows for more control in the closing order
* The deps factory now only closes the deps that have been built
* Now only `govc` is a closer, the rest of executable don't need to be
=> Close container independently from executables

pkg/executables/command.go, pkg/executables/dockerlinux.go, pkg/executables/executables.go, pkg/executables/mocks/executables.go
I'm gonna need a `ExecuteWithStdInAndEnvVars` soon, so instead of keeping bloating the interface, I propose a composable command: `e.Command(ctx, args...).WithStdIn(in).WithEnvVars(envs).Run()`
Ideally we will slowly refactor existing calls for `ExecuteWithEnv` and `ExecuteWithStdin` to use the new approach. I think leaving `Execute` as a shortcut is fine
=> Composable command for executables

cmd/eksctl-anywhere/cmd/common.go, cmd/eksctl-anywhere/cmd/importimages.go, cmd/eksctl-anywhere/cmd/listimages.go, test/framework/e2e.go
Add the `bundle-overrides` flag to `list-images` and `import-images`, and adjust the tests to use this flag.
This is necessary for the release branch E2E testing of the registry mirror -- without it, we'll just be attempting to import the standard images rather than the overrides, and the process fails. 
Once this is confirmed to have solved the issues with the 06 registry mirror tests, we will forward port it to `main` for parity. 
=> Override for import and list images

test/framework/e2e.go
0.6 is different from main, in the regard that `anywhere` is required in the command argument prefix. Will need to backport these changes later.
=> Fix error in e2e

pkg/executables/helm.go, pkg/executables/helm_test.go, pkg/executables/helpers_test.go
Adding `HELM_EXPERIMENTAL_OCI` env var to helm executions. This is required to use oci registries
=> Run helm template with OCI support env var

Makefile, controllers/build/upload_artifacts.sh, release/pkg/file_reader.go, release/pkg/file_reader_test.go, release/pkg/generate_spec.go, scripts/common.sh
Adding logic to get kube version directly from EKS-D releases manifest instead of from the [EKS-D releases file](https://github.com/aws/eks-anywhere-build-tooling/blob/main/EKSD_LATEST_RELEASES).
This method is a Golang version of
```zsh
$ curl -fsSL https://distro.eks.amazonaws.com/kubernetes-1-21/kubernetes-1-21-eks-7.yaml |
yq e '.status.components[] |
select(.name=="kubernetes") |
.gitTag' -
v1.21.5
```
=> Get Kube version from EKS-D release manifest instead of file

pkg/providers/vsphere/defaults.go, pkg/providers/vsphere/validator.go, pkg/providers/vsphere/vsphere_test.go
https://github.com/aws/eks-anywhere/issues/875
Validate osFamily field to ensure it is set to either `ubuntu` or `bottlerocket`
This PR also resolves an issue where the cli crashes during importing the template to vSphere and the osFamily is invalid.
=> Validate osFamily before import

designs/multiple-worker-node-groups.md
=> Design doc for multiple worker node groups support

DEVELOPMENT.md
GOPATH may not be available on an environment and in such case  `go env GOPATH` is helpful. Updated the file to export GOPATH to a default value.
=> [Doc Change]export GOPATH if not available.

pkg/executables/kubectl.go, pkg/executables/kubectl_getter_helper_test.go, pkg/executables/kubectl_test.go, pkg/executables/testdata/kubectl_daemonset.json, pkg/executables/testdata/kubectl_deployment.json
* Add kubectl methods to get deployment and daemonset
* Added some helpers to speed up writing kubectl getters. I realized most of the time I spent with the kubectl executable is writing getters, so hopefully this will help to speed up the process in the future. However, we take the risk of drying too much the tests and making them more difficult to read/debug. I think the code is fairly simple so hopefully this won't be an issue. Open to other opinions
=> Kubectl methods to get deployment and daemonset

pkg/providers/vsphere/defaults.go, pkg/providers/vsphere/validator.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
Prep for #870 
- Move vsphere datacenter validation and setDefaults to its own method
=> Separate vsphere datacenterconfig validation from rest of the cluster validation

Makefile
This fixes a regression from [this change](https://github.com/aws/eks-anywhere/pull/855/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L424)
Since I don't know why `update-kustomization-yaml` was removed, I'm adding it manually instead of putting it back in the prerequisites (in case the original change was trying to fix something else)
We might want to add a new target that runs both `update-kustomization-yaml` and `release-manifests` once we know more about the original change
This was causing all the dev bundles to include an eksa manifest with a very old version of the controller. Because of this, some of the E2E were fail, since the controller wasn't even registering all the validation webhooks …
=> Fix controller images kustomization for manifest in controller build

designs/dns-resolver.md
Mini design doc for the addition of this feature to allow customers to provide custom DNS resolver configuration by specifying the path to the custom file in the cluster spec.
=> Mini design doc for custom DNS resolver configuration

internal/pkg/ssm/command.go, internal/pkg/ssm/run_output.go, internal/test/e2e/oidc.go, internal/test/e2e/registryMirror.go, internal/test/e2e/run.go, internal/test/e2e/setup.go
Minor changes to make the logs a bit more readable
* Avoid logging command output by default
* Allow caller to handle output manually
* Log e2e command output from main routine so they are all ordered
* Omit logs for commands like s3 upload and download
=> Improve e2e logs coming from ssm in instance

Makefile, pkg/executables/clusterctl.go, pkg/executables/clusterctl_test.go, pkg/features/features.go, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_external_etcd_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_full_oidc_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_no_machinetemplate_update_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_with_taints_cp.yaml, pkg/providers/vsphere/testdata/expected_results_minimal_cp.yaml, pkg/providers/vsphere/testdata/expected_results_minimal_oidc_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_pod_iam_config.yaml, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
This will remove the v1beta1 feature flag to make that functionality the default. We can't merge this until the bundle is built from this PR and tested against it: https://github.com/aws/eks-anywhere-build-tooling/pull/318
=> Remove v1beta1 feature flag

release/go.mod, release/go.sum
Resolves [this](https://github.com/aws/eks-anywhere/security/dependabot/release/go.sum/github.com%2Fcontainerd%2Fcontainerd/open) Dependabot vulnerability.
=> Bump containerd go mod to mitigate vulnerabilities

release/pkg/aws/ecrpublic/ecrpublic.go, release/pkg/prepare_release.go
This PR adds logic to prevent an existing image tag from being inadvertently pushed to ECR Public.
=> Do not push tag to ECR public if it already exists

release/api/v1alpha1/bundle_types.go, release/pkg/assets_certmanager.go
Splitting up bundle release logic and actually consuming the manifest from the following PR: https://github.com/aws/eks-anywhere/pull/914
This can't be merged until the artifact gets uploaded from this: https://github.com/aws/eks-anywhere-build-tooling/pull/320
=> Add cert-manager manifest to bundle

pkg/executables/clusterctl.go, pkg/executables/clusterctl_test.go, pkg/executables/config/clusterctl.yaml, pkg/executables/testdata/clusterctl_expected.yaml
These include the changes to actually consume the new cert-manager.yaml manifest file, following up from this PR: https://github.com/aws/eks-anywhere/pull/914
=> Add cert-manager manifest from bundle

pkg/executables/config/clusterctl.yaml, pkg/executables/testdata/clusterctl_expected.yaml
cert-manager.yaml gets downloaded at path `"{{.dir}}/cert-manager/{{.CertManagerVersion}}/cert-manager.yaml"`, where CertManagerVersion is the one from bundle-release so it ends up being a semver tag instead of the git tag. This PR specifies the cert manager version in the overrides section for clusterctl as per [the docs](https://cluster-api.sigs.k8s.io/clusterctl/configuration.html#cert-manager-configuration)
=> Specify version for cert-manager overrides

pkg/executables/clusterctl.go, pkg/executables/clusterctl_test.go
Cluster API 1.0.1 removes usage of management-group flag from clusterctl as a part of [this](https://github.com/kubernetes-sigs/cluster-api/pull/4668) PR.
Earlier eks-a was setting management-group to capi-system/cluster-api to indicate that's the core provider group that should be updated. The above linked PR from capi does it by default, so there's no replacement needed for this flag
=> Remove usage of deprecated clusterctl flag management-group

internal/test/e2e/artifacts.go, internal/test/e2e/commands.go, internal/test/e2e/commands_test.go, internal/test/e2e/run.go
Following up on [this](https://github.com/aws/eks-anywhere/pull/901#discussion_r778315004)
Just minor refactor, dry a bit constants and add a builder for the s3 copy commands
=> Cleanup s3 copy commands in e2e setup code

README.md
K8s 1.20 certificates expire 1/8/2022
=> Remove expired CNCF cert

Makefile, pkg/cluster/config/releases.yaml
This builds a binary with a different tag and also zips it with the bundle embedded, and can only be used by `eksctl anywhere` plugin
=> Add new make targets to build custom release binaries

pkg/networking/cilium/templater.go, pkg/networking/cilium/templater_test.go
* Use oci uri and version from bundle
* Set preflight image and tag
* Remove suffix from operator image when passing it to helm
=> Multiple fixes to Cilium templater

release/pkg/assets_cilium.go
Readds the chart to the bundle after the build tooling repo has been updated with support for it
Also make a distcition between name and image for the image artifacts since the chart and the cilium image have the same image name (just a different tag). When using the image as the map key, we got some overlapping.
=> Readd cilium helm chart to bundle

pkg/features/features.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
Remove feature toggle, run by default during upgrade flow
=> Enable Cilium upgrades

.golangci.yml, Makefile
This was only needed when importing throubleshoot as a module
=> Remove unnecessary build tags

test/e2e/simpleflow_test.go
because the new dns field makes new specs incompatible with old CLIs
=> Delete TestEksa060LatestPatchDockerKubernetes121SimpleFlow test

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, test/e2e/upgrade_from_latest_test.go, test/e2e/upgrade_test.go, test/framework/api.go, test/framework/cluster.go, test/framework/commands.go, test/framework/envars.go, test/framework/releaseVersions.go, test/framework/wait.go
*Resolves* https://github.com/aws/eks-anywhere/issues/324
* Run upgrade flow e2e tests by creating the cluster with the latest minor release and upgrading with current code
* Latest release is dynamic, it uses the `T_BRANCH_NAME` env var to determine the branch where the tests are being run:
* If in `main`, this is the latest available eksa release (eg. `v0.6.1`)
* If in a release branch, this is the latest release from the previous minor version (eg. for `release-0.6`, `v0.5.0`)
* Removes paths from the cluster yaml config to avoid validation errors from old CLIs that don't know how to read new api fields. This is a bit hacky and it involves maintaining a list of incompatible fields in code. Ideally, we should refactor the api fillers package to not use the …
=> E2E tests creating cluster with latest release & upgrading with main

pkg/providers/vsphere/vsphere.go
With CAPV 1.0.1, cloud-controller-manager can be specified in the spec
and is not deployed from within capv. So we can add tolerations for CP taints
on this daemonset within the spec. This change is already merged, and logic
for patching the daemonset with tolerations post upgrade has been removed.
This commit removes the post controlplane creation action of applying these
tolerations to the daemonset since that's also not needed anymore.
=> Remove logic for patching cloud-controller-manager with tolerations

config/rbac/manager_extraroles_patch.yaml
Controller needs additional permissions based on the new v1beta1 cpi manifest changes for capi.
=> Add necessary controller permissions for v1beta1 capi manifests

docs/content/en/docs/reference/vsphere/customize-ovas.md, docs/content/en/docs/reference/vsphere/vsphere-ovas.md
https://github.com/aws/eks-anywhere/issues/940
- Add warning in docs to warn users to not power on the OVA directly
- Add steps to reset the machine-id if users customize the OVA template
=> Add warning in docs to warn users to not power on the OVA directly

cmd/eksctl-anywhere/cmd/upgradeplan.go, cmd/eksctl-anywhere/cmd/upgradeplancluster.go
Resolves #822 
This is more in sync with our 'verb + resource' pattern for commands
plus it opens the possibility to write upgrade plan commands for other
types of resources.
=> Move `upgrade plan` functionality to `upgrade plan cluster`

pkg/networking/cilium/client.go, test/e2e/upgrade_from_latest_test.go, test/framework/vsphere.go, test/framework/wait.go
* Fixes validation issues by using the default vsphere template
* Increases reliability by bumping up a timeout
* Makes tests faster by using less machines
=> Improvements for 'upgrades from latest release' e2e tests

pkg/executables/govc.go, pkg/executables/govc_test.go, pkg/providers/vsphere/internal/templates/factory.go, pkg/providers/vsphere/internal/templates/factory_test.go, pkg/providers/vsphere/internal/templates/mocks/govc.go, pkg/providers/vsphere/mocks/client.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
Currently, during auto-import we don't provide a datastore to deploy the template to. This results in the template being deployed in a random datastore. This PR specifies the datastore for the template to be deployed in.
=> Provide datastore for deploying the os template

internal/test/e2e/run.go
Hide all the summary sections from `gotestsum` and leave only the original
go test output
=> Avoid duplicated logs in failed e2e tests

pkg/networking/cilium/ready.go, pkg/networking/cilium/ready_test.go
By using by using `observedGeneration` we make sure we are always looking
to a refreshed status. This should avoid a few race conditions when checking
and object that has just been updated.
=> Make cilium checks more reliable

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/validations/createvalidations/gitops_test.go
* Check observedGeneration when validating kubeadm control plane
* Use full eksa cluster resource type when retrieving it
Related with errors I have seen in the e2e tests:
```
2022-01-18T22:58:59.077Z        V0      ❌ Validation failed    {"validation": "vsphere Provider setup is valid", "error": "failed validate machineconfig uniqueness: error getting eksa cluster: error: the server doesn't have a resource type \"clusters\"\n", "remediation": ""}
```
```
2022-01-18T22:55:08.619Z        V0      ❌ Validation failed    {"validation": "upgrade preflight validations pass", "error": "validation failed with 1 errors: 1 control plane replicas are unavailable", "remediation": ""}
``` …
=> Kubectl executable improvements

controllers/controllers/resource/reconciler_test.go, controllers/controllers/resource/testdata/eksa-cluster.yaml, controllers/controllers/resource/testdata/eksa-cluster_no_changes.yaml
Controller unit tests were using two different specs as the source of truth for the machine configs. This lead to names of objects being mismatched throughout the reconciler workflow. 
These changes set the specs from the testdata file as the only source of truth for the reconciler unit tests.
=> Update controller unit tests

docs/package-lock.json, docs/package.json
Using the version based on [this Dependabot alert](https://github.com/aws/eks-anywhere/security/dependabot/docs/package-lock.json/postcss/open).
=> Bump postcss version for security fixes

pkg/providers/docker/config/template-cp.yaml, pkg/providers/docker/config/template-md.yaml, pkg/providers/docker/testdata/capd_valid_full_oidc_cp_expected.yaml, pkg/providers/docker/testdata/capd_valid_full_oidc_md_expected.yaml, pkg/providers/docker/testdata/capd_valid_minimal_oidc_cp_expected.yaml, pkg/providers/docker/testdata/capd_valid_minimal_oidc_md_expected.yaml, pkg/providers/docker/testdata/no_machinetemplate_update_cp_expected.yaml, pkg/providers/docker/testdata/no_machinetemplate_update_md_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_pod_iam_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_stacked_etcd_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_taints_expected.yaml, pkg/providers/docker/testdata/valid_deployment_custom_cidrs_cp_expected.yaml, pkg/providers/docker/testdata/valid_deployment_custom_cidrs_md_expected.yaml, pkg/providers/docker/testdata/valid_deployment_md_expected.yaml, pkg/providers/docker/testdata/valid_deployment_node_labels_cp_expected.yaml, pkg/providers/docker/testdata/valid_deployment_node_labels_md_expected.yaml
*Issue #, if available:* https://github.com/aws/eks-anywhere/issues/636
=> Update CAPD manifests to use v1beta1

internal/test/e2e/setup.go
This is not needed anymore, now we include `eksctl` in the test image.
=> Avoid eksctl download on e2e test instances

scripts/e2e_test_docker.sh
=> Fix e2e test docker script: move comment out of multiline command

pkg/api/v1alpha1/vspheredatacenterconfig_webhook.go, pkg/api/v1alpha1/vspheredatacenterconfig_webhook_test.go
This will change the webhook to allow vspheredatacenterconfig objects to be
created if the FULL_LIFECYCLE_API is set to true.
=> Modify the behavior of VSphereDatacenterConfig Webhook

pkg/diagnostics/diagnostic_bundle.go, pkg/diagnostics/factory.go
A user supplied support-bundle config caused a nil pointer when we attempted to access the non-existent 'bundle' in the diagnostic bundle struct; adding a default name to prevent this.
=> add default cluster name for cases where no cluster spec is provided

cmd/eksctl-anywhere/cmd/generatebundleconfig.go, cmd/eksctl-anywhere/cmd/validations.go, pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_defaults.go, pkg/api/v1alpha1/cluster_defaults_test.go
Separated cluster defaults from validations. Now validations don't have
side effects and don't modify the Cluster object.
Simplified the api package interface to have one method for parsing, one
for parsing + defaults and one for parsing, defaults and validation. The
all build on top of each other so that should prevent us from "missing"
parts of the logic in some flows in the future.
Added doc comments to api package public methods to get a Cluster
object.
=> Improve and fix API Cluster validations/defaults

controllers/controllers/cluster_controller_test.go, controllers/controllers/clusters/vsphere.go
This will change the controller to use a bundle linked to a management cluster when creating workload clusters  
=> Use management clusters bundle

docs/content/en/docs/reference/changelog.md, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_external_etcd_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_with_cert_cp.yaml
https://github.com/aws/eks-anywhere/issues/937
Adding support for passing in cipherSuites to cluster-api spec for etcdadm in bottlerocket. For bottlerocket to actually spin up nodes with these change, changes need to be made to https://github.com/mrajashree/etcdadm-bootstrap-provider and the bottlerocket-bootstrap code in https://github.com/aws/eks-anywhere-build-tooling as well, which will come as a follow-up
=> Add cipherSuites arg to bottlerocket etcdadm

docs/content/en/docs/reference/clusterspec/iamauth.md, docs/content/en/docs/tasks/cluster/cluster-iam-auth.md
EKS-A does not support configuring clusterID value for IAM Authenticator. Updating docs accordingly. 
=> Removing IAM Auth ClusterID references in docs

internal/pkg/api/yaml.go, internal/pkg/api/yaml_test.go, test/framework/api.go
The CLI does not allow extra fields in the cluster configuration file.
Old versions of the CLI don't support names for worker node groups,
since that a new field. This means we need to remove that field in the
E2E tests before passing the cluster config file to the old CLI.
Moved helpers to delete paths from a yaml object to the internal api
package and added tests.
=> Delete worker node group name in old CLI E2E tests

release/pkg/artifacts_types.go, release/pkg/assets_capi.go, release/pkg/assets_cluster_controller.go, release/pkg/git/git.go
This check was causing the incorrect URL to be assigned to CAPI metadata manifests.
=> Fix URLs for CAPI manifests

pkg/networking/cilium/client.go, pkg/networking/cilium/client_test.go, pkg/networking/cilium/mocks/upgrader.go, pkg/networking/cilium/upgrader.go, pkg/networking/cilium/upgrader_test.go
This should avoid transient errors like "connection reset by peer" when
talking to the api server.
=> Wrap kubectl delete call in a retrier for Cilium

release/pkg/generate_spec.go
Tinkerbell is still in development phase behind feature flag, so we don't want these images to feature in the production bundle.
=> Add Tinkerbell assets only to dev release manifest

controllers/controllers/resource/fetcher.go
Nit fix.
Modifying error message to reflect the CRD kind that fetcher is trying to do an eksa cluster lookup.
=> Modifying eks-a controller error message

pkg/validations/cluster.go, pkg/validations/createvalidations/cluster.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/preflightvalidations.go, pkg/validations/upgradevalidations/cluster.go, pkg/validations/upgradevalidations/preflightvalidations.go, pkg/validations/utils.go
Refactoring preflight validations so we have common code instead of repeating validation code in both create and upgrade. Also changed bool name to `Silent` so that it can be more flexible than just for feature flags and explains what is actually happening. 
This PR addresses comments from https://github.com/aws/eks-anywhere/pull/1036
=> Refactor preflight validations and change bool name for bypassing LogPass call

docs/content/en/docs/reference/clusterspec/etcd.md, docs/content/en/docs/reference/clusterspec/vsphere.md, docs/content/en/docs/tasks/cluster/cluster-flux.md, docs/content/en/docs/tasks/cluster/cluster-upgrades.md, docs/content/en/docs/tasks/cluster/cluster-verify.md, docs/content/en/docs/tasks/troubleshoot/_troubleshooting.md
=> Update docs for multiple worker node groups & resolvConf

docs/README.md
Rebase for https://github.com/aws/eks-anywhere/pull/625
This adds docs to deploy the site to a personal Amplify app.
=> Add docs to delpoy to a personal amplify app

docs/content/en/docs/tasks/cluster/cluster-upgrades.md
Documentation of [Issue #499](https://github.com/aws/eks-anywhere/issues/499) 
* Show example of `eksctl anywhere upgrade plan` options and output.
* Add Cilium to list of upgraded components.
=> Add upgrade plan options to cluster upgrade docs

pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
This will fix the code that sets the the "anywhere.eks.amazonaws.com/managed-by" on VSphereMachineConfig objects.
=> Do not set annotation on machineconfig that belongs to a management cluster

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, cmd/integration_test/cmd/run.go, internal/test/e2e/run.go, internal/test/e2e/setup.go, test/framework/releaseVersions.go
`BRANCH_NAME` env var is already available in codebuild runs and the e2e tests understand `T_BRANCH_NAME` and are able to use to determine the prior available release.
This just closes the bridge, passing the value to the e2e test runner binary and from them to the e2e tests through the ssm command. It defaults to `main` when not set.
=> Pass branch name from codebuild to e2e tests

config/manifest/eksa-components.yaml, config/rbac/role.yaml, controllers/controllers/cluster_controller_legacy.go
Fixes #1087 
This avoids a error log from the cached client after retrieving an
OIDCConfig object from the controller.
More info about why this was happening in the issue.
=> Add watch permission for OIDCConfig to controller

designs/vcenter-template-import.md
These changes came from users having the ability to import templates that we vend beforehand as well as make it easier to test with templates provided by our bundles in our e2e workflows.
=> Design for new vcenter template import command

pkg/providers/tinkerbell/config/template-md.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md.yaml
Our CLI was showing wrong count for the total Nodes (CP + worker). It was not taking workernodes into consideration for tinkerbell provider. This PR is for solving this error. 
=> Nodes ready total count issue for the tinkerbell workernodes

pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_types_test.go, pkg/providers/docker/docker_test.go, pkg/validations/cluster.go
couple of cosmetic and legibility cleanups pertaining to the taints implementation --
- replacing var name `wngc` with `nodeGroup`; `wngc` was classified as "pure madness" by @g-gaston 😆 🧠 😵‍💫 
- clarify test setup by using struct and slice literals instead of chaining appends
=> Taints cleanup

pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_external_etcd_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_custom_resolv_conf.yaml, pkg/providers/vsphere/testdata/expected_results_full_oidc_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_121_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_no_machinetemplate_update_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_node_labels_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_with_taints_cp.yaml, pkg/providers/vsphere/testdata/expected_results_minimal_cp.yaml, pkg/providers/vsphere/testdata/expected_results_minimal_oidc_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_pod_iam_config.yaml
When migrating to v1beta1 the insecure option got removed. This PR
adds it back
The way cloud-controller-manager is launched has changed when moving to capv v1.0.1, it is now deployed through the manifest through CRS. So we directly create the configmap containing vsphere.conf file, which has the field named `insecureFlag` as per the [documentation](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.0/vmware-vsphere-csp-getting-started/GUID-0C202FC5-F973-4D24-B383-DDA27DA49BFA.html)
*Issue #, if available:* https://github.com/aws/eks-anywhere/issues/1117
=> Accept insecure flag for vsphere cloud-controller-manager config

pkg/api/v1alpha1/cluster_types.go
Simplify and correct worker node group configuration slice comparisons:
- take `name` into account when comparing worker node groups
- ignore order of taints when comparing worker node group configuration taints
- use existing, correct method for taint slice comparison
=> wngc comparison takes name, taints into proper account

config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, release/api/v1alpha1/bundle_types.go, release/api/v1alpha1/zz_generated.deepcopy.go, release/config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, release/pkg/assets_pbnj.go, release/pkg/assets_tinkerbell.go, release/pkg/generate_spec.go
Adding PBNJ image to the bundle manifest.
=> Add PBNJ assets to bundle manifest

config/manifest/eksa-components.yaml, config/rbac/manager_extraroles_patch.yaml, controllers/controllers/cluster_controller.go, controllers/controllers/cluster_controller_test.go, controllers/controllers/clusters/vsphere.go, controllers/controllers/testdata/release.yaml
This will create CAPI objects form a EKS-Anywhere spec and apply them. 
Next steps will be applying extra objects and the CNI plugin.
=> Create CAPI objects from EKS-A spec

cmd/eks-a-tool/cmd/validatecluster.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/executables/kubectl.go, pkg/validations/kubectl.go, pkg/validations/mocks/kubectl.go, pkg/validations/upgradevalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations_test.go, test/framework/flux.go
Prep for #396 
Update the kubectl exec `ValidateWorkerNodes` method to use kubeconfig as arg directly instead of passing the `types.cluster`. It's easier to validate workload cluster's nodes in management cluster for Flux e2e tests.
=> Update kubectl ValidateWorkerNodes arg to pass in kubeconfig

release/designs/artifact-table-generation.md
Adding a mini design doc for project artifacts generation refactor.
=> Add mini design doc for release artifacts generation

Makefile, controllers/build/upload_artifacts.sh, release/pkg/assets_cluster_controller.go, release/pkg/assets_kindnetd.go
Release tool changes for aws/eks-anywhere-build-tooling#406
=> Move eks-a components and kindnetd manifests to versioned folder

release/pkg/assets_eksd.go, release/pkg/file_reader.go, release/pkg/file_reader_test.go, release/pkg/generate_spec.go
Change looping through the supported releases using the new supported branches file in the build tooling repo, as well as support being able to generate a bundle without having bottlerocket support for the respective eksd release. Also add support to be able to pull the dev release version of eksd from the appropriate s3 bucket.
=> Support bundle builds without br support for an eksd release

test/e2e/tools/eks-anywhere-test-tool/pkg/logfetcher/logfetcher.go, test/e2e/tools/eks-anywhere-test-tool/pkg/logfetcher/stdout.go
Fixes null pointer when not using filter by name flag
The flag to only print tests logs to stdout now prints
different logs with different colors depending on the
origin and info: e2e test logs, go test logs, V5-9 CLi logs,
error/warning logs, etc.
=> Fixes and missing code for eks-a test tool

test/e2e/workload_clusters_test.go
The Flux e2e test envs are only set up when the test name includes "Flux" in it (https://github.com/aws/eks-anywhere/blob/main/internal/test/e2e/flux.go#L12). 
Change the newly added GitOps test name to include "Flux" so that the envs can be properly set. Also to keep it consistent with the existing tests. Later we can change all flux tests name to "GitOps" which makes more sense.
=> Update newly added GitOps e2e test name to include "Flux"

Makefile
=> Build eks-a with path trimmed from stack traces for release builds

.gitignore, Makefile, internal/test/e2e/ipmanager.go, internal/test/e2e/run.go, internal/test/e2e/setup.go, internal/test/e2e/vsphere.go, pkg/networkutils/ippool.go, test/e2e/README.md, test/e2e/upgrade_from_latest_test.go, test/e2e/workload_clusters_test.go, test/framework/cluster.go, test/framework/ippool.go, test/framework/vsphere.go
#743 
Update the test run to provide a pool of ips for cluster tests. Each test ec2 instance gets an ippool of ip addresses seeded via an env var reserved for the test clusters created by that e2e test session.
This PR is still in progress, but I needed to submit PR in order to get feedback from the CI to test e2e with ippool.
=> (#743) support passing multiple ips to cluster tests

docs/content/en/docs/getting-started/install/_index.md, docs/content/en/docs/overview/_index.md
Using EKS in these contexts (atleast the second) would be a bit misleading.
=> Replace EKS with EKS-A in docs

internal/pkg/api/cluster.go, internal/pkg/api/nodegroups.go, internal/pkg/api/vsphere.go, internal/pkg/api/vspheremachines.go, pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/vspheremachineconfig.go, test/e2e/multiple_worker_node_groups_test.go, test/e2e/simpleflow_test.go, test/e2e/upgrade_from_latest_test.go, test/e2e/upgrade_test.go, test/e2e/vsphere_autoimport_test.go, test/framework/cluster.go, test/framework/vsphere.go, test/framework/workergroups.go
Expands current e2e testing framework to support multiple worker node
groups. It allows to add/remove/update worker node groups to the initial
spec and during upgrades.
Adds one simple vSphere tests that starts with two worker node groups.
During the upgrade, it scales down one of them to 1 replica, it deletes
the other one and creates a new one.
This will need to be refactored eventually. The framework api is becoming a bit convoluted and expanding the framework itself is quite difficult. We will create tickets to refactor this in the near future. We don't do it now because it requires to rethink a bit the framework internals and in particular the way we apply api object updates and that will take some time.
We are postponing that refactor because at least this …
=> E2E tests for multiple worker node groups

internal/test/e2e/vsphere.go, test/e2e/README.md, test/framework/vsphere.go
no issue
Update e2e test flow so cluster ip pool is not required
Ran local e2e tests
=> Update e2e test flow so cluster ip pool is not required

pkg/providers/docker/config/template-cp.yaml, pkg/providers/docker/docker.go, pkg/providers/docker/docker_test.go, pkg/providers/docker/testdata/capd_valid_full_oidc_cp_expected.yaml, pkg/providers/docker/testdata/capd_valid_minimal_oidc_cp_expected.yaml, pkg/providers/docker/testdata/no_machinetemplate_update_cp_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_pod_iam_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_stacked_etcd_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_taints_expected.yaml, pkg/providers/docker/testdata/valid_deployment_custom_cidrs_cp_expected.yaml, pkg/providers/docker/testdata/valid_deployment_node_labels_cp_expected.yaml, release/api/v1alpha1/artifacts.go
CAPD was initially hardcoded to use `kindest/haproxy` as the loadbalancer image. They made this configurable in `v1alpha4` by adding a `LoadBalancer` field to the `DockerClusterSpec` type. This PR sets this field to use the HAProxy image we build and distribute.
=> Use Kind Haproxy image for CAPD loadbalancing

pkg/hardware/config.go, pkg/providers/tinkerbell/testdata/hardware_config.yaml, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go, pkg/providers/tinkerbell/validator.go
Adding support to parse tinkerbell hardware config file and perform hardware to bmc validations.
1. Every hardware has a unique BmcRef
2. Hardware's BmcRef is present in the hardwareConfig
*Testing:*
Tested by running `eksctl-anywhere create cluster`
=> Hardware to bmcRef validation

go.mod, go.sum, test/e2e/tools/eks-anywhere-test-tool/go.mod, test/e2e/tools/eks-anywhere-test-tool/go.sum
Using the `pseudo-version` of release tag `v.2.8.0` for dependency `github.com/docker/distribution`. Hopefully fixes [issue](https://github.com/aws/eks-anywhere/security/dependabot/3) 
*Testing:*
go mod tidy
=> Using pseudo-version for go mod replace

release/api/v1alpha1/bundle_types.go, release/pkg/assets_eksd.go
Design doc: #1162 
This PR adds the `components` field to the EKS-D bundle. The `components` field points to the release CRD for EKS-D.
More details on these changes are in the design doc linked above.
=> Add `components` field to EKS-D bundle

pkg/hardware/config.go, pkg/providers/tinkerbell/validator.go
Added validations for BMC and Secret CRDs in hardware config. Main validations are
- BMC's secretRef is present in the hardwareConfig
- BMC's have unique IPs
- BMC IP format is valid
- Secrets have keys username, password
- Non empty fields validations
=> Bmc Secret validations for hardware config

pkg/api/v1alpha1/cluster_types.go
Make this field a pointer support backwards compatibility with previous releases
Ran e2e tests with latest minor release for docker & vsphere
=> Make eksdReleaseRef a pointer to support previous releases

internal/pkg/api/cluster.go, internal/pkg/api/nodegroups.go, pkg/executables/kubectl.go, test/e2e/taints_test.go, test/framework/taints.go
https://github.com/aws/eks-anywhere/issues/1121
*Update*
Ok, so after discussion with @jiayiwang7 , I've improved the validation logic.
We're now going through the whole process of deducing the `node` from the `workerNodeGroupConfiguraton`, by:
- map wngc to machine deployment
- map machineDeployment to machineSpec
- iterate through the nodes, checking their 'owner' annotations, and mapping that back to the mahcineSpec.
This way, we get a robust 1-1 validation of taint to node.  This mapping should be trivial but is not (espeically on BR, where the node names are the IP of the hosts, and not related to the node group configuration name), so I've filed a ticket to simplify it (perhaps by putting an annotation on the nodes which has their wngc?) -- …
=> End to end tests for taints

pkg/hardware/config.go, pkg/providers/tinkerbell/testdata/hardware_config.yaml, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/validator.go, pkg/providers/tinkerbell/validator_helper_test.go, pkg/providers/tinkerbell/validator_test.go
Add pre-flight validation to assert there are sufficient Tinkerbell CRs to satisfy the requested provisioning of control plane, etcd and worker nodes.
There is a tight coupling between a few methods as the `ValidateHardwareConfig()` assumes responsibility for loading and parsing the hardware config that's required by `ValidateMinimumRequiredTinkerbellHardwareAvailable()`. This made it difficult to declare the `ValidateMinimumRequiredTinkerbellHardwareAvailable()` dependencies explicitly as parameters; we should really decoupled that to create much better testability.
=> Validate requested node provisioninging against available cr hardware

config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, config/manifest/eksa-components.yaml, release/api/v1alpha1/bundle_types.go, release/config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml
Without this, old `Bundle`'s become invalid since the api server makes them required
=> Make new bundle fields optional

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/executables/testdata/kubectl_eksa_cs_datacenterconfig.json, pkg/executables/testdata/kubectl_eksa_cs_machineconfig.json, pkg/executables/testdata/kubectl_no_cs_datacenterconfigs.json, pkg/executables/testdata/kubectl_no_cs_machineconfigs.json
This PR is a continuation of the integration of the CloudStack provider into EKS-A. It adds support for querying cloudstack items using the kubectl executable. Most of the code is copied/pasted from vsphere.
Cluster creation succeeded locally (with other changes). EKS-A builds, and all older unit tests succeed.
=> Adding kubectl for cloudstack

controllers/controllers/resource/fetcher.go, controllers/controllers/resource/reconciler_test.go, controllers/controllers/resource/testdata/kubeadmconfigTemplateSpec.yaml, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go, pkg/providers/vsphere/vsphere.go
https://github.com/aws/eks-anywhere/issues/1053
Adding support for node labels upgrade through Flux and `upgrade`. This builds off of the changes from the taints work here https://github.com/aws/eks-anywhere/pull/1175 in leveraging replacing the `kubeadmconfigtemplate`. Also changing the `ControlPlaneConfiguration` validation in the webhook to leverage the `Equal` method for the struct.
Tested with modifying multiple labels both for control plane and worker nodes with `upgrade` and with Flux.
Also fixed the controller unit tests to properly test for taints and labels changes. …
=> Support node label reconciliation

controllers/controllers/clusters/vsphere.go, controllers/controllers/resource/fetcher.go, controllers/controllers/resource/mocks/resource.go, controllers/controllers/resource/reconciler_test.go, controllers/controllers/resource/template.go, controllers/controllers/resource/testdata/expectedMachineDeploymentTemplateChanged.yaml, controllers/controllers/resource/testdata/kubeadmconfigTemplateSpec.yaml, controllers/main.go, pkg/providers/docker/docker.go, pkg/providers/provider.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/vsphere/config/template-md.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_external_etcd_md.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_md.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_with_cert_md.yaml, pkg/providers/vsphere/testdata/expected_results_main_121_controller_md.yaml, pkg/providers/vsphere/testdata/expected_results_main_121_md.yaml, pkg/providers/vsphere/testdata/expected_results_main_md.yaml, pkg/providers/vsphere/testdata/expected_results_main_multiple_worker_node_groups.yaml, pkg/providers/vsphere/testdata/expected_results_main_no_machinetemplate_update_md.yaml, pkg/providers/vsphere/testdata/expected_results_main_node_labels_md.yaml, pkg/providers/vsphere/testdata/expected_results_main_with_taints_md.yaml, pkg/providers/vsphere/testdata/expected_results_minimal_add_worker_node_group.yaml, pkg/providers/vsphere/testdata/expected_results_minimal_md.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_md.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_with_cert_md.yaml, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
* vsphere provider checks if new kubeadmconfig template is needed based on WN config
* method to fetch kubeadmconfigtemplate
* regenerate kubeadmconfigtemplate spec if neccessary
* controller tests, testdata, and mocks
* update vsphere md template to accomodate mutable kubeadmconfigtemplate name
* vsphere provider tests, testdata, and mocks
* docker, tink and generic provider methods to support kubeadmconfigtemplate changes
* gofmt controller tests
* add kubeadmconfigtemplate to scheme
* check if new kubeadmconfigtemplate is needed during upgrade
* standardize method calls in templater
* update tests, mocks
* shorten kubeadmconfigtemplate generated name
* make sure to pass kubeadmconfigtemplate during upgrade
* update vsphere multiworkernode tests to properly pull the machine deployment …
=> Backport Controller Support for Reconciling Taints (#1175)

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_types_test.go, pkg/api/v1alpha1/testdata/cluster_invalid_taints.yaml, pkg/api/v1alpha1/testdata/cluster_valid_taints_multiple_worker_node_groups.yaml, pkg/providers/docker/docker_test.go, pkg/validations/cluster.go
https://github.com/aws/eks-anywhere/commit/cbf03fd2a76be81076724321f31b15ecbf50c07f
https://github.com/aws/eks-anywhere/commit/71b969705dd2ef8275ffc4a3e54f61b4bd61f2c4
https://github.com/aws/eks-anywhere/commit/249cf6c62f4eec888220877aa7c80fa85bb7c5c3
Backport three ancillary cleanup commits pertaining to the taints support to release-0.7
=> Backport taints support ancillary

pkg/validations/cluster.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations.go, test/e2e/taints_test.go
https://github.com/aws/eks-anywhere/issues/189
Remove the feature flag for Taints and allow it to be free.
End-to-end tests for taints have been executed in various configurations.
Extensive manual testing.
=> Remove feature flag for taints

internal/pkg/api/cluster.go, internal/pkg/api/nodegroups.go, pkg/awsiamauth/awsiamauth.go, pkg/awsiamauth/config/aws-iam-authenticator.yaml, pkg/executables/kubectl.go, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_with_taints_cp.yaml, test/e2e/taints_test.go, test/framework/controlplaneNodes.go, test/framework/taints.go, test/framework/workerNodes.go
https://github.com/aws/eks-anywhere/issues/189
Commit to backport all of the taints end-to-end tests to the release-0.7 branch. Once this is merged, the tests will run in the release-0.7 pipeline and be executed in-context.
=> Backport taints tests

internal/test/files.go
The test.NewWriter() method uses a directory prefix of fileWriter. When
multiple tests fail its difficult to know what directory relates to what
test. This ensures we have a delineation between test artifacts
=> Use test name for temporary test directories.

Makefile
Ensure the `release-0.7` tests are using the correct bundle override when executed.
=> ensure release-0.7 e2e tests are using the correct bundle

cmd/eksctl-anywhere/cmd/generateclusterconfig.go, pkg/api/v1alpha1/snowdatacenterconfig.go, pkg/api/v1alpha1/snowdatacenterconfig_types.go, pkg/api/v1alpha1/snowmachineconfig.go, pkg/api/v1alpha1/snowmachineconfig_types.go, pkg/constants/constants.go
#1105 
Add Snow provider to `generate clusterconfig` command.
- skipped unstacked etcd when generating default template (will add back after testing out)
- add recommended `instanceType` and `sshKeyName`
Ran `eksctl-anywhere generate clusterconfig test-snow -p snow`
```yaml
kind: Cluster
metadata:
name: test-snow
spec:
clusterNetwork:
cni: cilium
pods:
cidrBlocks:
- 192.168.0.0/16
services:
cidrBlocks:
- 10.96.0.0/12
controlPlaneConfiguration:
count: 3
endpoint:
host: ""
machineGroupRef:
kind: SnowMachineConfig
name: test-snow-cp
datacenterRef:
kind: SnowDatacenterConfig
name: test-snow
kubernetesVersion: "1.21"
managementCluster:
name: test-snow …
```
=> Add snow provider to generate clusterconfig command

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml, config/manifest/eksa-components.yaml, config/rbac/manager_extraroles_patch.yaml
allow the manager clusterrole to create kubeadmconfigtemplates, required for reconciling taints.
directly modified the controller clusterrole to allow create and everything worked as expected.
=> Manager rbac for taints

internal/pkg/api/cluster.go, internal/pkg/api/nodegroups.go, pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go, test/e2e/constants.go, test/e2e/labels_test.go, test/e2e/taints_test.go, test/framework/labels.go
https://github.com/aws/eks-anywhere/issues/1053
Adding end to end tests for labels. With these changes, I am also bringing in some cluster validations we have for `create cluster` for the webhook. 
Ran e2e tests with these changes.
=> Add e2e tests for labels upgrade

cmd/eksctl-anywhere/cmd/downloadartifacts.go, pkg/cluster/spec.go, release/api/v1alpha1/artifacts.go
The `download artifacts` command downloads all manifests linked in the bundle-release.yaml corresponding to the eks-a cluster spec, and saves them at the path specified by --downloads-dir (defaults to eks-anywhere-downloads).
The structure looks like this:
```
➜  ls eks-anywhere-downloads
bundle-release.yaml             cert-manager                    cluster-api-provider-docker     eks-a-release.yaml              etcdadm-controller
capi-kubeadm-bootstrap          cilium                          cluster-api-provider-vsphere    eks-anywhere-cluster-controller kindnetd
capi-kubeadm-control-plane      cluster-api-provider-aws        core-cluster-api                etcdadm-bootstrap-provider
```
The goal behind adding this command was so that …
=> Modify bundle-release.yaml to use downloaded artifacts

docs/content/en/docs/reference/clusterspec/vsphere.md
https://github.com/aws/eks-anywhere/issues/189
Include the taints in the reference cluster spec, along with descriptions of the fields and a note about the Control Plane taints behavior.
=> Update cluster spec reference doc to include taints fields

pkg/cluster/node_groups.go, pkg/cluster/node_groups_test.go
The old cluster spec (coming from v0.6.1 or prior) doesn't have a
default name for the first worker node group, since the default is
only set at the cli level and not at the api server level. So when
retrieving the cluster object from the kube api server, the name
is empty.
This is just a quick fix for this specific bug. We should find a more
robust way of implementing these defaults (probably with a mutation
webhook) so we don't need to implement the same logic again and again.
We should create tickets for this follow up work.
Added unit tests and run E2E test `TestVSphereKubernetes120BottlerocketUpgradeFromLatestMinorRelease`
/cherrypick release-0.7 …
=> Fix nodes to delete calculation for empty name

Makefile
Mock packages don't contain any logic that needs testing so they can be excluded from the unit test make recipe cutting down on the amount of output. In doing so, its easier to spot what packages have good coverage/no coverage.
=> Exclude mock packages from unit test make recipe

internal/test/files.go
Assertion funcs called by test funcs add to the call stack creating
incorrect assertion reporting. Declaring an assertion function as a
helper ensure the assertion function is skipped when inspecting the call
stack.
=> Define assertion functioins as helpers.

cmd/eksctl-anywhere/cmd/downloadartifacts.go, pkg/cluster/spec.go, release/api/v1alpha1/artifacts.go
Backport of https://github.com/aws/eks-anywhere/pull/1280
Had to remove [cloudstack](https://github.com/aws/eks-anywhere/pull/1280/files#diff-00d7b0c26d532f9a18cd3bdde12c9e6449353a24533ebbce194b69dcd98e0ebbR35) and [eksD.Components](https://github.com/aws/eks-anywhere/pull/1280/files#diff-00d7b0c26d532f9a18cd3bdde12c9e6449353a24533ebbce194b69dcd98e0ebbR62)  from the list of artifacts to download as opposed to the main branch, since these are not part of the release-0.7 manifest.
```
make eks-a
./bin/eksctl-anywhere download artifacts -f cluster.yaml
```
=> [release-0.7] Modify bundle-release.yaml to use downloaded artifacts

release/Makefile
=> Get branchname from Prow env var instead of hardcoding to main

Makefile, release/pkg/assets_cluster_controller.go, release/pkg/git/git.go
This PR fixes the logic for assigning the git tag to the EKS-A cluster controller image/manifests.
=> Fix git tag assignment to get absolute latest tag

pkg/cluster/config.go, pkg/cluster/parse.go, pkg/cluster/parse_test.go, pkg/cluster/testdata/docker_cluster_oidc_awsiam_flux.yaml
* We lack an entity that represents a full cluster configuration.
* We have `cluster.Spec` but it doesn't have provider specific api structs (like machine configs or datacenter). 
* This has created duplicated logic, pushing providers into implementing the same thing again and again.
* It complicates providers: since they don't receive their specific api structs as method arguments, they need to store them as members. This introduces complexity for both data management and construction. Moreover, it tides providers to a specific cluster config as a side effect.
* The api package has grown a lot, assuming too many responsibilities. It unmarshals, sets defaults and validates. And all of this tied to an inflexible public api that only takes paths to files in local disk as input.
* This makes …
=> Cluster config parsing

internal/test/envtest/crd.go, internal/test/envtest/crd_test.go, internal/test/envtest/environment.go
When adding CRDs to `envtest` we depend on the path the source modules are
on disk. These paths obviously change when go.mod has a replace
directive. With this changes we are able to handle those replaces and we
feed `envtest` with the path of the replacing module instead of the
replaced one.
=> Handle replace directives for modules with CRDs

pkg/api/v1alpha1/awsiamconfig.go, pkg/api/v1alpha1/awsiamconfig_types.go, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/dockerdatacenterconfig_types.go, pkg/api/v1alpha1/gitopsconfig.go, pkg/api/v1alpha1/gitopsconfig_types.go, pkg/api/v1alpha1/oidcconfig.go, pkg/api/v1alpha1/oidcconfig_types.go, pkg/api/v1alpha1/vspheredatacenterconfig_types.go, pkg/api/v1alpha1/vspheremachineconfig_types.go, pkg/cluster/parse_test.go, pkg/cluster/testdata/cluster_1_19.yaml, pkg/cluster/testdata/docker_cluster_oidc_awsiam_flux.yaml, pkg/cluster/validate.go, pkg/cluster/validate_test.go
This continues the work started on #1343
Context unaware validations rely on having a Validate method in the api
structs.
This adds the option to run context aware validations at the cluster
Config level. These should have no external dependencies and depend
solely on the data in cluster Config.
=> Cluster Config validation

test/e2e/awsiam_test.go, test/e2e/conformance_test.go, test/e2e/flux_test.go, test/e2e/labels_test.go, test/e2e/oidc_test.go, test/e2e/proxy_test.go, test/e2e/registry_mirror_test.go, test/e2e/simpleflow_test.go, test/e2e/stackedetcd_test.go, test/e2e/taints_test.go, test/e2e/upgrade_from_latest_test.go, test/e2e/upgrade_test.go, test/e2e/vsphere_autoimport_test.go
Modifying the e2e tests to either add a new test case for 1.22 or replace the 1.21 test cases with 1.22. This will give us more visibility on EKS-A with 1.22, which is still behind a feature flag.
`make e2e`
=> Add/modify e2e tests to use 1.22

controllers/controllers/cluster_controller_legacy.go, controllers/controllers/clusters/vsphere.go, controllers/controllers/resource/fetcher.go, pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go, pkg/api/v1alpha1/oidcconfig_types.go, pkg/api/v1alpha1/oidcconfig_webhook.go, pkg/api/v1alpha1/oidcconfig_webhook_test.go, pkg/cluster/fetch.go, pkg/cluster/spec.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/providers/vsphere/vsphere.go, pkg/validations/upgradevalidations/immutableFields.go, pkg/validations/upgradevalidations/preflightvalidations_test.go, test/e2e/constants.go
#676
In these code changes, we let users update (add/remove/change) their OIDC config settings for the EKSA clusters.
These changes include CLI and controller changes.
**- CLI** : Users can update their OIDC config settings for their management as well as workload clusters by making changes to the existing cluster specs for their clusters.
**- Flux** : If users have flux enabled, they can update the eks-a-cluster spec from their Github repository, however this can only be done for workload clusters. Management clusters can not update OIDC config via flux.
- Unit tests
- Manual cluster creation and upgrading the same with OIDC settings using the cli
- Manual cluster creation and upgrading the same with OIDC …
=> Update OIDC settings after cluster creation

pkg/executables/tink.go, pkg/executables/tink_test.go, pkg/providers/tinkerbell/hardware/config.go, pkg/providers/tinkerbell/mocks/client.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go, pkg/providers/tinkerbell/validator.go
This PR is a part of pre-flight validation for Tinkerbell provider. Before creating a cluster our CLI will check whether a workflow exists in the Tinkerbell stack or not. It will fail the cluster creation if there is any workflows associated with any of the hardwares provided in the hardware yaml file.
=> Tinkerbell hardware workflow mapping - pre flight validation

test/e2e/taints_test.go, test/e2e/upgrade_test.go
This PR fixes configuration for `TestVSphereKubernetes122Taints` and `TestVSphereKubernetes122UbuntuWorkerNodeUpgrade` tests
=> Fix 1-22 tests

cmd/eksctl-anywhere/cmd/constants.go, cmd/eksctl-anywhere/cmd/get.go, pkg/kubeconfig/kubeconfig.go
The `KUBECONFIG` environment variable has semantics within the Kubernetes community and isn't really customizable. This change acknowledges that by defining it in the `kubconfig` package as opposed to in the `cmd` package.
=> Define kubeconfig env var in kubeconfig package

pkg/crypto/ssh.go
Fix generated key path so it doesn't appear int he `generated` file and is considered 'permanent'.
=> Declare ssh keys persistent

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml
Decreasing the limit to see if it will help with the load on the vsphere CI cluster
=> Decrease max ec2 instances to 40

pkg/api/v1alpha1/awsiamconfig.go, pkg/api/v1alpha1/awsiamconfig_types.go, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/gitopsconfig.go, pkg/api/v1alpha1/gitopsconfig_types.go, pkg/cluster/defaults.go, pkg/cluster/defaults_test.go
Continues the work started by #1343
Separates validations from some defaults in the api package.
Implements SetDefaults method in some api structs for context unware
defaults.
Adds some context aware defaults at the cluster Config level. These
defaults should have no other dependencies but the cluster.Config
itself.
=> Cluster Config defaults

internal/test/e2e/run.go
This should fix the e2e tests in order to properly pass in more than one test as a regex. Currently the tests fail due to the following error, and it is because of how the string is represented in unix without the quotes, with the `|` being interpreted as separating two commands.
Error:
```
TestVSphereKubernetes121ThreeReplicasFiveWorkersSimpleFlow: command not found
failed to run commands: exit status 127
```
make integration-test-binary
=> Fix ability to run multiple tests in one instance

docs/content/en/docs/community/docs_contributing.md
This is a first cut at guidelines to contribute to EKS Anywhere documentation. It includes help on where to put content, style issues and considerations when documenting third-party software.
=> Adding docs contributors guide

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml
Our sequential e2e logic doesn't work as expected right now and fails to upload the JUnit reports due to how the test name is constructed. It could also be that some of the flux tests are failing due to resources not being cleaned up. Changing it back to a higher number to get a test run in and see if we are going to run into the resource limits again.
=> Increase e2e instance count to 85

release/pkg/utils/utils.go, test/kube-bench/jobs/controlplane/kube-bench-default.yaml
The error lines getting written to stdout were not being returned, and hence not printed to stdout in the job run.
=> Print command execution errors to stdout

internal/test/e2e/run.go
Latest changes here cause the files to be uploaded/downloaded with the string quotes. https://github.com/aws/eks-anywhere/pull/1400
There will still be an issue running multiple tests in the same instance as the test name would be `test1|test2`, which will result in the junit reports to not upload properly, so will be following up with a fix for that.
=> Fix junit file upload/download

cmd/integration_test/build/buildspecs/conformance-eks-a-cli.yml, cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, cmd/integration_test/cmd/run.go, internal/test/e2e/run.go
This makes use of a blocking channel to queue the test executions we want to run based on the limit defined. This should allow our tests to not run into the vcenter limits we are hitting.
`make integration-test-binary`
=> Add ability to limit number of concurrent e2e test executions

release/pkg/prepare_release.go
This comparison is done to determine whether to overwrite an existing release or append a new one to the list of current EKS-A releases. It won't be proper to compare the whole release version, for example, `v0.0.0-dev+build.100` since the build metadata keeps monotonically increasing. Instead it would suffice to just compare the part before the `+`, i.e. semver and pre-release information.
=> Compare only semver and prerelease information when overwriting releases

pkg/cluster/spec.go, pkg/clustermanager/cluster_manager_test.go, pkg/diagnostics/diagnostic_bundle_test.go, pkg/validations/upgradevalidations/preflightvalidations_test.go
While continuing the work from #1343, I found some tests that were building the Spec manually, which makes more difficult to make changes in bulk to its structure.
This just updates the tests to make use of existing tooling, so the necessary future changes to embed Config in Spec become more centralized. The behavior is the same.
=> Update test to make use of cluster Spec tooling

pkg/providers/cloudstack/config/template-cp.yaml, pkg/providers/cloudstack/testdata/expected_results_main_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_mirror_config_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_mirror_config_with_cert_cp.yaml
This PR enables us to pass the specified account/domain down to CAPC. We were already consuming it in the EKSA cluster spec and doing preflight checks on it, but never passing it to CAPC
Successfully created cluster with all machines in specified account/domain, unlike the prior behavior where they defaulted to admin and root. 
=> Adding account/domain to the capc template

designs/cilium-configuration-policy.md
We support Kindnetd as the CNI plugin for CAPD clusters. This PR updates the design doc for CNIConfig to include a field for KindnetdConfig
=> Update CNI design doc to include kindnetd config for CAPD

Makefile
When building locally from a release branch it was still using the main eks-a-release.yaml and 0.0.0-dev version.  This meant by default the build would end up using the latest main bundle, which is not what we want.  The makefile was setup to handle the embed case, but this is the default for people and has burned us in the past.  
I think this change makes sense and I would "backport" it to main for future release branches.  
The change to spec.go is def up for debate.  Currently every build from a specific branch adds the new build into the eks-a-release.yaml, but they all point to the same bundle.  @abhay-krishna fixed the release tooling to point to the release branch bundle from release branches so the latest build in the 0.7 …
=> fix bundle usage in release branches

internal/test/e2e/run.go
Moving the wait outside of the go routine so that all executions can run. Currently for presubmits, the test is not executing because it is a single case, and it is only running for n-1 executions.
presubmit should show that the test is actually executing now
=> Move wait for queue outside of go routine

controllers/controllers/resource/reconciler_test.go, controllers/controllers/resource/template.go, pkg/api/v1alpha1/vspheremachineconfig_types.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
#1208 
These code changes allows an user to update the ssh keys and the user name for vsphere machine configs.
If the user updates the `etcd` or the `control plane` machine configs, we update the `template-cp` and this change triggers CAPI to roll out new nodes.
In case of worker node machine config updates, we create a new `kubeadm config template` and update the worker nodes with the new user/ssh keys.
- Upgrade management cluster's `etcd`, `control plane` and `worker node` machine configs with new users and ssh keys using `upgrade cluster` (CLI only). Logged into the vms with the updated keys.
- Upgrade workload cluster's `etcd`, `control plane` and `worker node` machine configs with new users and ssh keys …
=> Update ssh keys and user name using CLI

cmd/eksctl-anywhere/cmd/createcluster.go
The `hardwarefile` flag is required when creating a cluster with a tinkerbell provider. We noticed the 'missing flag' error was taking unnecessarily long to appear.
The flag can't be modeled as required using Cobra because its only required if the cluster configuration uses a `TinkerbellDatacenterConfig`. Consequently, we need to establish what provider is in use with the `create cluster` command via the yaml before we can make the flag required. The cause for the delay (approximately 2s) stems from the app performing disk io, network io, sub process management and validation activities.
The launching of child processes and performing network io (the majority of the wait) was performed by a bulk `commonValidations` function that's shared between sub commands. This function makes it …
=> Improve missing hardwarefile flag error speed

docs/content/en/docs/community/docs_contributing.md
This was one comment that didn't get it when the new "Contributing to documentation" guide before it was published, so I'm making the fix here.
=> Minor change to docs contrib guide

pkg/providers/tinkerbell/hardware/config.go
When submitting `Hardware` manifests during `create cluster` for the Tinkerbell provider, we need to ensure the hardware ID they reference is unique.
=> Ensure Tinkerbell Hardware objects have unique IDs

pkg/api/v1alpha1/tinkerbelltemplateconfig_defaults.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/validator.go
Added initial validation for the metadata_url field for the the template config crd. I will be adding unit tests for this in my next PR. 
=> Added validation for metadata_url of the template config  field

pkg/executables/clusterctl.go, pkg/executables/clusterctl_test.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/docker/docker.go, pkg/providers/mocks/providers.go, pkg/providers/provider.go, pkg/providers/snow/snow.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/vsphere/vsphere.go
CAPAS image was hardcoded in the snow provider. Now that the image is built in the release bundle, we can fetch it from there instead.
Notice this is still a tmp solution before we automate the build for snow `infrastructure-components.yaml` with proper image  version.
=> Pull CAPAS image from release bundle

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml
This PR forces the VM cleanup to happen in the postbuild stage, that always runs irrespective of the success or failure of the build stage. This will ensure test VMs get properly deleted.
=> Re-add VM cleanup command in postbuild stage

pkg/providers/tinkerbell/hardware/validator.go, pkg/providers/tinkerbell/hardware/validator_test.go
Depends on: https://github.com/aws/eks-anywhere/pull/1336
As part of the Tinkerbell provider end-user workflow we generate files for registration in the Tinkerbell stack and management clusters.
This PR introduces a Validator implementation to be used with the Translate functions. It performs, by default, basic data validation such as unique hostnames and IP addresses within the machine set.
=> Add Tinkerbell hardware generation validation

internal/test/e2e/artifacts.go, internal/test/e2e/run.go, internal/test/e2e/setup.go
Consolidate cluster name generation into one place
make sure to use proper cluster name for uploading logs to s3
=> use proper cluster ID for uploading test logs

pkg/cluster/fetch.go
E2E tests for prev release versions failed during upgrade because we now embed the eksd release objects to the cluster, so they were failing with this error: 
`Error: failed to upgrade cluster: failed fetching EKS-D release for cluster: error getting releases.distro.eks.amazonaws.com with kubectl: error: the server doesn't have a resource type "releases"`
We already have the logic in place to get the eksd release object if it isn't on the cluster, so this PR updates the eksdReleaseFetcher method to only return the `nil` eksd release object if it isn't on the cluster (instead of returning an error). From here, if it sees the eksd object as nil, it will install it & continue with the upgrade.
Created cluster with …
=> Update eksdReleaseFetcher to support previous versions

test/e2e/flux_test.go
the current validation occurs too soon before the cluster upgrade flow begins and can cause preflight validations to fail due to machine deployments still being in scaling up/down phase. Validating flux after the upgrade, as we had done prior to 11 days go, is sufficient for testing the feature.
=> only validate flux after upgrade of cluster

controllers/controllers/resource/fetcher.go, controllers/controllers/resource/fetcher_test.go, controllers/controllers/resource/reconciler_test.go, controllers/controllers/resource/template.go, pkg/api/v1alpha1/vspheremachineconfig_types.go, pkg/api/v1alpha1/vspheremachineconfig_webhook.go, pkg/api/v1alpha1/vspheremachineconfig_webhook_test.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
https://github.com/aws/eks-anywhere/issues/1208
These code changes allows an user to update the ssh keys and the user name for vsphere machine configs.
If the user updates the etcd or the control plane machine configs, we update the `template-cp` and this change triggers CAPI to roll out new nodes.
In case of worker node machine config updates, we create a new `kubeadm config template` and update the worker nodes with the new user/ssh keys.
**Controller Changes**
Created management cluster
- Updated worker node's user name and ssh keys, tested by logging in using new keys and name
- Updated control plane and etcd node's user name and ssh keys, got an error saying the update was immutable
Created workload cluster …
=> Make User names and SSH keys mutable

test/e2e/upgrade_from_latest_test.go
The upgrade from latest tests were incorrectly using the `ClusterFiller` function instead of the `ClusterUpgrade` function, which was probably resulting in updating the wrong file. 
Ran the `TestDockerKubernetes121to122UpgradeFromLatestMinorRelease` test locally
=> Fix upgrade tests to use WithClusterUpgrade

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml
Modify the build spec to run a subset of tests against against the latest CLI.
due to the structure of our build system (using a pipeline to build the artifacts and pass them to the build phase) this is the easiest and most straight forward way to kick off a test run with a subset of tests. Will revert back to 'Test' after this kicks off, and look into a better way to be able to use codeebuild jobs with advanced overrides and the correct artifacts outside of the pipeline.
=> trigger test of only a subset of EKS Anywhere test cases

pkg/cluster/awsiam.go, pkg/cluster/cluster.go, pkg/cluster/docker.go, pkg/cluster/gitops.go, pkg/cluster/oidc.go, pkg/cluster/validate.go, pkg/cluster/vsphere.go
Following up on https://github.com/aws/eks-anywhere/pull/1432
No change in behavior, just refactor to use dynamic registerable config
=> Update `cluster.Config` validation to config manager

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml
Reenable tests after confirming that subset of tests are passing, and decreasing the amount of parallel tests more to see if it will help with vsphere limits. Follow up will be to see if changing cleaning up failed tests to within the subroutine is going to help as well.
=> Reenable all tests and decrease concurrency to 20

pkg/providers/tinkerbell/hardware/yaml.go, pkg/providers/tinkerbell/hardware/yaml_test.go, pkg/providers/tinkerbell/hardware/yamlparser.go
We are introducing validation and distinct parsing and hardware registration steps to the anywhere generate hardware command.
This PR introduces the Tinkerbell manifest writer that compliments the `MachineWriter` interface allowing us to pass the writer to the `Translate*` family of functions.
A separate PR will address writing JSON files as it requires a mechanism for recording what files were written so we can later register them with Tinkerbell. A final PR will be written to start leveraging the new constructs.
=> Implement tinkerbell manifest writer for hardware generation

pkg/executables/tink.go, pkg/executables/tink_test.go
Pass the tinkerbell grpc authority and tinkerbell cert url as flags to tink cli's get calls instead of environment variables.
This is needed because the env var approach is deprecated and tink cli prints out a warning if we don't provide these values as flags.
=> Pass the required info to tink as flags instead of env

Makefile
Test folders for writers now follow `{TestName}-[9 digits]`
=> Fix delete test folders in clean target

test/framework/flux.go
It looks like we never specified the namespace here, so we will just return an empty list and assume that everything is all good and ready. However, this might be explaining some of the flakiness in flux tests where it fails in a later stage because we didn't allow adequate time to check beforehand as it was bypassing the checks here.
Line at question below:
```
flux.go:586: Waiting for worker node MachineDeployment to scale to target value 3
flux.go:604: All worker node MachineDeployments have reached target scale 3
```
```
2022-03-17T20:30:25.041Z	V3	e2e	Pushing to remote	{"repo": "eksa-test-c02bf12/git/eksa-e2e-"}
flux.go:617: Successfully updated version controlled cluster configuration
flux.go:451: Successfully updated …
```
=> Specify namespace when describing deployments

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml, config/manifest/eksa-components.yaml, pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_defaults.go, pkg/api/v1alpha1/cluster_defaults_test.go, pkg/api/v1alpha1/cluster_test.go, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_types_test.go, pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go, pkg/dependencies/factory.go, pkg/validations/upgradevalidations/immutableFields.go, pkg/validations/upgradevalidations/preflightvalidations_test.go
This PR adds the new field CNIConfig to specify cni plugin proposed in this design doc: https://github.com/aws/eks-anywhere/blob/main/designs/cilium-configuration-policy.md#api-changes
The exiting CNI field will be deprecated.
The reason behind adding this new type is to allow users to specify more configuration options for the different CNI plugins where possible. For instance, eks anywhere installs cilium through a helm chart, which can accept values from the user. So the new CNIConfig type has separate fields to configure each plugin, like CiliumConfig that can accept values from the user and configure the cilium helm chart with it.
1. Cluster creation & upgrade
2. Upgrade existing cluster from release-0.7
3. …
=> Add CNIConfig type

test/framework/flux.go
Reverts aws/eks-anywhere#1519
This may be causing issue with the tests.
=> Revert "Specify namespace when describing deployments"

internal/test/cluster.go, pkg/addonmanager/addonclients/fluxaddonclient.go, pkg/addonmanager/addonclients/fluxaddonclient_test.go, pkg/addonmanager/addonclients/testdata/cluster-config-default-path-management.yaml, pkg/addonmanager/addonclients/testdata/cluster-config-default-path-workload.yaml, pkg/addonmanager/addonclients/testdata/cluster-config-user-provided-path.yaml, pkg/cluster/config.go, pkg/cluster/spec.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermarshaller/clustermarshaller_test.go, pkg/validations/upgradevalidations/immutableFields.go
Continues the work started by #1343 
This makes `cluster.Config` available almost everywhere in the CLI, since
we pass cluster.Spec as argument to most calls.
Removed a few parsed api structs from `cluster.Spec` that are not used
anymore.
Removed the GitOps default method from `cluster.Spec` and use the one for
`cluster.Config` when necessary (just in tests).
I ran all unit test and a couple e2e for vsphere and docker, all good.
However, I want to keep this on hold until we release, to avoid extra noise if any of the e2e tests fail.
=> Embed `cluster.Config` in `cluster.Spec`

go.mod, pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/api/v1alpha1/cluster_types.go
This PR validates the input for cilium's policy enforcement mode, allowed values are "default", "always", "never" as per cilium docs https://docs.cilium.io/en/v1.8/policy/intro/
Design doc for reference: https://github.com/aws/eks-anywhere/blob/main/designs/cilium-configuration-policy.md
The PR to set this value in the cilium chart values isn't merged yet, so an e2e test will follow with the PR that sets this value
unit tests
=> Validate input for cilium policy enforcement mode

pkg/networking/cilium/network_policy.yaml, pkg/networking/cilium/templater.go, pkg/networking/cilium/templater_test.go, pkg/networking/cilium/testdata/network_policy_mgmt_capt_flux.yaml, pkg/networking/cilium/testdata/network_policy_mgmt_capv.yaml, pkg/networking/cilium/testdata/network_policy_workload_120.yaml, pkg/networking/cilium/testdata/network_policy_workload_121.yaml
If user selects "always" policy enforcement mode for cilium, all communication between pods including core k8s and CAPI pods will be disallowed, blocking cluster creation/upgrades. To avoid this, EKS-A will create NetworkPolicy objects to allow communication between pods crucial to EKS-A. Refer this design doc to see which network policies will be created based on the cluster spec: https://github.com/aws/eks-anywhere/blob/main/designs/cilium-configuration-policy.md
This new templater method will be called while generating manifest for cilium during create and upgrade if the policy enforcement mode is set to "always". The part of calling this during cilium installation/upgrade will follow in a separate PR along with an e2e test
*Testing …
=> Generate network policy based on cluster spec and provider

cmd/eksctl-anywhere/cmd/generatehardware.go, test/framework/cluster.go
When generating Tinkerbell manifests the `--dry-run` option should follow as closely as possible the normal path of operation. This includes performing the validation we would expect if the tool were to run normally. The change ensures validation does run even with `--dry-run`.
Additionally, change the `--dry-run` flag to `--skip-registration` so its clear what behavior to expect. Typical dry run behavior would still perform validations, for example, where as we don't want validation on the Tinkerbell stack config if we don't want to register the hardware.
=> Always validate on tinkerbell hardware generate

docs/content/en/docs/reference/changelog.md, pkg/features/features.go, pkg/validations/cluster.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations.go, test/e2e/awsiam_test.go, test/e2e/conformance_test.go, test/e2e/flux_test.go, test/e2e/labels_test.go, test/e2e/multiple_worker_node_groups_test.go, test/e2e/oidc_test.go, test/e2e/proxy_test.go, test/e2e/registry_mirror_test.go, test/e2e/simpleflow_test.go, test/e2e/stackedetcd_test.go, test/e2e/taints_test.go, test/e2e/upgrade_from_latest_test.go, test/e2e/upgrade_test.go, test/e2e/vsphere_autoimport_test.go
Removing the 1-22 feature flag to get ready for support
`make`
`make e2e`
=> Remove 1-22 feature flag

pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/cloudstack/decoder/decoder.go, pkg/providers/cloudstack/decoder/decoder_test.go
*Issue #, if available:*'
None
verify-ssl value in the cloudstack cloud config secret should be optional and its default value should be "true".
Unit testing
`ok  	github.com/aws/eks-anywhere/pkg/providers/cloudstack/decoder	0.746s	coverage: 100.0% of statements`
=> Make verify-ssl optional and Add unit tests for decoder.go

controllers/controllers/clusters/vsphere.go, internal/pkg/api/cluster.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/networking/cilium/cilium.go, pkg/networking/cilium/cilium_test.go, pkg/networking/cilium/network_policy.yaml, pkg/networking/cilium/templater.go, pkg/networking/cilium/templater_test.go, pkg/networking/cilium/testdata/manifest_network_policy.yaml, pkg/networking/cilium/upgrader_test.go, pkg/networking/kindnetd/kindnetd.go, pkg/networking/kindnetd/kindnetd_test.go, pkg/workflows/create.go, pkg/workflows/create_test.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go, test/e2e/simpleflow_test.go
*Issue #, if available:* https://github.com/aws/eks-anywhere/issues/726
Design doc for reference: https://github.com/aws/eks-anywhere/blob/main/designs/cilium-configuration-policy.md
This PR sets the value of policyEnforcementMode in the cilium chart's values if provided by the user, and calls GenerateNetworkPolicy (added in [this](https://github.com/aws/eks-anywhere/pull/1539) PR) to install required Network Policy objects if `always` mode is selected during cluster creation.
This same method will be called in cilium upgrader in a follow-up PR
- `TestVSphereKubernetes121CiliumAlwaysPolicyEnforcementModeSimpleFlow` (new e2e test added for creating cluster with `always` policy enforcement mode to ensure cluster gets created successfully) …
=> Install required NetworkPolicy objects during cluster creation

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/networking/cilium/upgrader.go, pkg/networking/cilium/upgrader_test.go, pkg/networking/kindnetd/upgrader.go, pkg/networking/kindnetd/upgrader_test.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go, test/e2e/upgrade_from_latest_test.go, test/e2e/upgrade_test.go
*Issue #, if available:* https://github.com/aws/eks-anywhere/issues/726
Refer design doc: https://github.com/aws/eks-anywhere/blob/main/designs/cilium-configuration-policy.md
[Previously merged PR](https://github.com/aws/eks-anywhere/pull/1552) creates NetworkPolicy objects during cluster creation if policy enforcement mode is set to `always`
This PR does the same during cluster upgrade, if the policy enforcement mode value has changed.
Along with this, it also upgrades cilium if the values passed to cilium chart have changed. Right now we only accept and configure the value for the policy enforcement mode so only that is checked
- `TestVSphereKubernetes121UbuntuTo122UpgradeCiliumPolicyEnforcementMode`
-  Created a cluster with no …
=> Create NetworkPolicy if required during cilium upgrade

pkg/api/v1alpha1/cluster.go
=> Change default to 1.22

pkg/networking/cilium/upgrader.go
design doc for reference: https://github.com/aws/eks-anywhere/blob/main/designs/cilium-configuration-policy.md
This [previous PR](https://github.com/aws/eks-anywhere/pull/1559) added checks to see if policy enforcement mode was modified. But the existing check works only for cases where the existing cluster has the cniConfig case and does not cover clusters that don't have cniconfig set (clusters on versions release-0.7 and lower). This PR checks if the existing spec does not have cniConfig initialized (only possible for clusters created with older version), and if the current policy enforcement mode is the non-default option
- Created cluster using release-0.7, upgraded with cluster.spec containing non-default …
=> Modify policy enforcement changed check to include clusters created from 0.7

pkg/networking/cilium/upgrader.go, pkg/networking/cilium/upgrader_test.go
Just adding the check to be on the safe side based on this discussion: https://github.com/aws/eks-anywhere/pull/1564#discussion_r831716980
=> Check if ciliumConfig on older cluster spec is nil before upgrade

pkg/providers/tinkerbell/hardware/config.go, pkg/providers/tinkerbell/hardware/validator.go
Added Kubernetes validation for Tinkerbell hardware name field for the generate hardware and create cluster command.
=> Added Kubernetes validation for Tinkerbell hardware name field

cmd/eks-a-tool/cmd/vspherelogoutsessions.go
Add a basic command to the `eks-a-tool vsphere rm` command which allows the removal of VSphere sessions, given a comma separated list of session cookies.
This will be combined with a query of created sessions to automatically close out vsphere sessions after end-to-end test runs.
usage:
`eks-a-tool vsphere rm sessions --sessionTokens=token1,token2 --tlsInsecure false -e https://myVsphereEndpoint.com`
=> Vsphere rm session cmd

test/e2e/workload_clusters_test.go, test/framework/docker.go
Right now the e2e test is rewriting the config file in git without the namespace field for DockerDatacenterConfig, which is resulting in the flux controllers throwing an error because it is required. This will marshal the structs properly when making a configuration update.
Ran `TestDockerUpgradeWorkloadClusterWithFlux`
=> Fix docker e2e gitops test by reading datacenter config from repo

release/pkg/images/images.go, release/pkg/prepare_release.go
In case of failures, these print statements could give us useful info.
=> Print command output before returning error

cmd/eksctl-anywhere/cmd/downloadartifacts.go, cmd/eksctl-anywhere/cmd/importimages.go, pkg/executables/helm.go, pkg/executables/helm_test.go, release/api/v1alpha1/artifact_types.go, release/api/v1alpha1/artifacts.go
Cilium is now installed as helm chart. This PR adds the following changes required for offline installation:
- `import-images` will pull + push the cilium chart to the registry mirror endpoint
- `download artifacts` will update the downloaded bundle-release.yaml's cilium helmChart to the one from the registry mirror
```
./bin/eksctl-anywhere download artifacts -f bin/mandaor.yaml -v=9
```
The downloaded bundle-release.yaml has following contents for cilium helm chart:
```
cilium:
helmChart:
description: Helm chart for cilium-chart
imageDigest: sha256:5982a9b5feded74c14a0b410006bba6d748655f8bc01f393b4519c9b10a463d0
name: cilium-chart
uri: <registryMirror>/cilium-chart/cilium:1.9.13-eksa.2
```
By submitting this …
=> Import cilium chart as part of import-images

controllers/controllers/resource/fetcher.go, controllers/controllers/resource/mocks/resource.go, controllers/controllers/resource/template.go, controllers/main.go, go.mod, go.sum
Updating KubernetesVersion through GitOps for Docker is currently not supported, so this will update the machine templates appropriately with the kind node image. It checks to see if there is a difference in version compared to what is specified on KubeadmControlPlane. For worker nodes because we can roll them out on a self managing cluster as well, we will check if there is a newer kind image in the bundle as well in order to decide whether we need a new template or not.
Followup: Need to enable support for changes to the KubeadmConfigTemplate spec as well.
Local testing with tilt against the TestDockerUpgradeWorkloadClusterWithFlux …
=> Add support to upgrade Kubernetes version through GitOps for Docker

pkg/networkutils/ipgenerator.go, test/e2e/tools/eks-anywhere-test-tool/pkg/artifacts/artifactFetcher.go, test/e2e/tools/eks-anywhere-test-tool/pkg/s3/s3.go
Stop seeding the default rand source midway through program execution.
The default rand source should be seeded on program startup as a bootstrapping task, not midway through program execution. This change alters algorithms seeding the default rand by switching to a separate `Rand` instance. In doing so, we remove possible side effects/introducing unintended dependencies in logic executed at later stages.
=> Fix ip generator rand source

test/framework/flux.go
Use the injected gitVersion for marshalling cluster configuration during flux tests, rather than hard-coding the dev release.
This will ensure that we have the proper git version for release branch tests (e.g. v0.0.0-dev-release-0.8 vs v0.0.0-dev)
=> use injected git dev version for tests

go.mod, go.sum, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go
This change adds the necessary functions into Kubectl.go to support the e2e tests and upgrade operations used by the controller.
Unit tests, tested e2e in cloudstack branch
=> Adding necessary cloudstack functionality into kubectl

pkg/providers/cloudstack/config/template-cp.yaml, pkg/providers/cloudstack/testdata/expected_results_main_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_main_no_machinetemplate_update_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_minimal_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_minimal_proxy_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_mirror_config_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_mirror_config_with_cert_cp.yaml
The current CAPC template has a regression in that the audit log is being managed by eks-a instead of the api-server controller, so it doesn't get rotated.
Unit tests pass, cluster created in customer environment
=> Fix Audit log constant error on api-server

release/pkg/generate_spec.go
The CAPC assets are added to bundle for only dev releases (L281). This is a duplication that causes it go get applied for prod releases too.
=> Remove CAPC asset packaging in prod releases

pkg/providers/cloudstack/testdata/cluster_main.yaml, pkg/providers/cloudstack/testdata/cluster_mirror_config.yaml, pkg/providers/cloudstack/testdata/cluster_mirror_with_cert_config.yaml, pkg/providers/cloudstack/validator.go, pkg/providers/cloudstack/validator_test.go
The compromise discussed exposes the managementApiEndpoint for the cloudstack provider in two ways: environment variable, and cluster spec. This decision was made to be future-proof. This PR adds validation on cluster creation to ensure that the two values are the same.
=> Adding validation on managementApiEndpoints to be consistent

cmd/eksctl-anywhere/cmd/importimages.go, pkg/executables/helm.go
As talked about in https://github.com/aws/eks-anywhere/pull/1587, we actually don't need the auth here as initially expected like docker. We thought we needed it because the repo we were testing against was private, so after I made it public, it works now.
Ran both `import-images` and `create cluster`
=> Remove need for auth with helm

designs/embed_eksd_manifest.md
Instead of using `eksdReleaseRef` in the cluster status, we will fetch the eks-d object using the eks-d bundle name from the versions bundle. We already have access to this bundle. However, we currently grab it based on the cluster name, which is usually the case, but a more accurate way to get this object is by introducing a `bundlesRef` & directly referring to that object instead of assuming the name based on the cluster
=> Use bundlesRef instead of eksdReleaseRef to get eksd bundle

.github/workflows/golangci-lint.yml, pkg/clustermanager/cluster_manager.go, pkg/providers/vsphere/defaults.go, pkg/workflows/create.go, pkg/workflows/delete.go, pkg/workflows/upgrade.go
The `make` target pulls the latest version of `golangci-lint` but the version is hardcoded to `v1.42.1` in the GitHub action.
This PR changes it to the latest version to be consistent with the `make` target.
=> Use `latest` version of golangci-lint in GitHub actions

pkg/api/v1alpha1/tinkerbelltemplateconfig.go, pkg/api/v1alpha1/tinkerbelltemplateconfig_defaults.go, pkg/api/v1alpha1/tinkerbelltemplateconfig_defaults_test.go
The patches for eliminating local registry in Tinkerbell stack merged. Hence reading tink-worker action image URIs from bundle release.
*Testing:*
`eksctl-anywhere generate clusterconfig`
=> Picking Tinkerbell action image URI from bundle

docs/content/en/docs/tasks/cluster/cluster-overview.md, docs/content/en/docs/tasks/cluster/cluster-terraform.md
Move the guide to managing a cluster with terraform from `examples` to the `tasks/clusters` section of the docs.
Add a section to the cluster mgmt overview which notes the ability to manage a cluster with terraform, including a link to the docs.
=> move terraform how-to into the official docs site

pkg/workflows/delete.go, pkg/workflows/upgrade.go
Diagnostic bundle collection on delete was broken.
We were referencing uninitialized nested unnamed fields, resulting in a nil pointer. 
This will eliminate the nil pointer exception when collecting diagnostic bundles from mgmt clusters during `delete`.
created and deleted a cluster, forcing an error during delete and observing the behavior.
=> fix diagnostic bundle collection during delete

pkg/clusterapi/apibuilder_test.go, pkg/clusterapi/config/containerd_config_append.toml, pkg/providers/snow/apibuilder.go, pkg/providers/snow/apibuilder_test.go
#1105 
Snow apibuilder should append to existing kcp PreKubeadmCommands. So that the registry mirror command won't be overridden.
- unit tests
- local e2e
=> Fix snow registry mirror prekubeadmcommand overrides

pkg/executables/kubectl.go, pkg/providers/tinkerbell/hardware/config.go, pkg/providers/tinkerbell/mocks/client.go, pkg/providers/tinkerbell/tinkerbell.go
Our CLI was throwing an error for create cluster command Tinkerbell provider if the given hardware yaml is not within the same directory. This PR has changes that will read the hardware objects from the memory and not from the file itself.
=> Tinkerbell hardware file read from the memory

cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/deletecluster.go, cmd/eksctl-anywhere/cmd/generatebundleconfig.go, cmd/eksctl-anywhere/cmd/generatehardware.go, cmd/eksctl-anywhere/cmd/supportbundle.go, cmd/eksctl-anywhere/cmd/upgradecluster.go, cmd/eksctl-anywhere/cmd/upgradeplancluster.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/providers/factory/providerfactory.go, pkg/providers/factory/providerfactory_test.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go
We want the force flag to create behavior that ensures machines are
usable when creating a new cluster even if they appear to have been
provisioned previously.
We can't model the behavior using dynamic construction logic so we're
passing the force flag all the way into the Tinkerbell provider where
we'll implement the behavior.
=> Pass force flag to Tinkerbell provider

internal/test/e2e/setup.go
We ran into an issue where when the BRANCH_NAME env var was not set in a pipeline the test cluster names generated started with `-`, which cobra interpreted as a flag (e.g. `-i-asdflksj`) and caused test runs to fail. If the BRANCH_NAME passed to the cluster name func is "", we now just go ahead and use the instance id.
=> test cluster name wont start with -

cmd/eksctl-anywhere/cmd/importimages.go, pkg/executables/helm.go, test/framework/registryMirror.go
We reverted the commit in #1609 after doing some testing that didn't require us to be logged in to the registry, but when testing in our ci environment it seemed like it didn't work as expected. The creds might have been cached or the set up for dev is different. Now, we will be asking users to specify the username and password when running import images so helm that is running inside our docker container will be allowed to push. We could have used the `--registry-config` if we had access to the `~/.docker/config.json` to avoid the user from having to login to the registry mirror for docker and also provide these env vars for helm, but I am not sure if there is a quick way for us to do that apart from mounting the `config.json` file after …
=> Bring back auth for helm with import-images

pkg/docker/mover.go, pkg/docker/mover_test.go, pkg/types/lookup.go, pkg/types/lookup_test.go
Part of https://github.com/aws/eks-anywhere/issues/1166
Will complement https://github.com/aws/eks-anywhere/pull/1478
Builds on top of #1518 
=> Avoid processing duplicated images in image mover

controllers/controllers/clusters/vsphere.go
*Description of changes:
Fix invalid memory reference in the new cluster controller 
=> Pass a valid Helm executable to fix nil pointer dereference

docs/content/en/docs/reference/changelog.md, pkg/features/features.go, pkg/validations/cluster.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations.go, test/e2e/awsiam_test.go, test/e2e/conformance_test.go, test/e2e/flux_test.go, test/e2e/labels_test.go, test/e2e/multiple_worker_node_groups_test.go, test/e2e/oidc_test.go, test/e2e/proxy_test.go, test/e2e/registry_mirror_test.go, test/e2e/simpleflow_test.go, test/e2e/stackedetcd_test.go, test/e2e/taints_test.go, test/e2e/upgrade_from_latest_test.go, test/e2e/upgrade_test.go, test/e2e/vsphere_autoimport_test.go
Reverts aws/eks-anywhere#1663
Ensure that the 1.22 feature flag is not present in EKS-A
=> Revert "Revert "Remove 1-22 feature flag (#1549)""

test/e2e/tools/eks-anywhere-test-tool/pkg/filewriter/writer.go
Tests with more than one directory for its artifacts, like Flux and OIDC, had some misplaced files when using the `fetch artifacts` command due to recent changes. This PR fixes those issues to place those files in their correct directories.
`fetch artifacts` command
=> Fix fetch artifacts command for extra flux and oidc files

config/crd/bases/anywhere.eks.amazonaws.com_tinkerbelldatacenterconfigs.yaml, config/manifest/eksa-components.yaml, pkg/api/v1alpha1/testdata/cluster_1_21_valid_multiple_tinkerbell_templates.yaml, pkg/api/v1alpha1/testdata/cluster_1_21_valid_tinkerbell.yaml, pkg/api/v1alpha1/testdata/cluster_invalid_kinds_tinkerbell.yaml, pkg/api/v1alpha1/testdata/not_parseable_cluster_tinkerbell.yaml, pkg/api/v1alpha1/tinkerbelldatacenterconfig_types.go, pkg/api/v1alpha1/tinkerbelltemplateconfig_defaults.go, pkg/providers/tinkerbell/envars.go, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_external_etcd.yaml, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_missing_ssh_keys.yaml, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_multiple_node_groups.yaml, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_stacked_etcd.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_external_etcd.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_stacked_etcd.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_missing_ssh_keys.yaml, pkg/providers/tinkerbell/testdata/expected_results_tinkerbell_md_multiple_node_groups.yaml, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go, pkg/providers/tinkerbell/validator.go, pkg/providers/tinkerbell/validator_test.go
Added tinkerbellHegelURL field in the clusterconfig file to replace metadata_url in the template field. I haven't added e2e test changes in this PR. 
=> Added tinkerbellHegelURL field in the Tinkerbell clusterconfig file

pkg/providers/tinkerbell/mocks/client.go, pkg/providers/tinkerbell/pbnj/client.go, pkg/providers/tinkerbell/tinkerbell.go
Builds on #1661
Implement the force node reset to PXE behavior desired when the --force-cleanup flag is specified. Node should power off, be set to PXE boot and power on again where they'll sit waiting for the Tinkerbell stack to respond.
Manually tested by powering machines on and observed the logging to power off during create cluster cmd.
=> Tinkerbell implement force create cluster

docs/content/en/docs/reference/clusterspec/registrymirror.md
We switched to installing cilium through helm chart, so for a disconnected setup, this chart will be used from the registry mirror. Import-images command pushes the chart under a project `cilium-chart`. Users will have to create this project under their registry
=> Add cilium-chart as a project to be created for registry mirror

pkg/api/v1alpha1/tinkerbelltemplateconfig_defaults.go, pkg/api/v1alpha1/tinkerbelltemplateconfig_defaults_test.go, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_external_etcd.yaml, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_missing_ssh_keys.yaml, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_multiple_node_groups.yaml, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_stacked_etcd.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_external_etcd.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_stacked_etcd.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_missing_ssh_keys.yaml, pkg/providers/tinkerbell/testdata/expected_results_tinkerbell_md_multiple_node_groups.yaml
In the new ubuntu image we have enabled uefi which requires dev/sda1 partition. So for all other actions we have changed DEST_DISK to sda2.
=> Changed DEST_DISK to /dev/sda2

pkg/executables/tink.go, pkg/executables/tink_test.go, pkg/providers/tinkerbell/mocks/client.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/validator.go
When force creating a cluster the program should remove all workflows associated with the hardware that's been submitted. This is to ensure we pass validation and can correctly provision the hardware with a new workflow.
- Make MAC address checks case insensitive.
- Whatever unit tests we can write.
- Manual e2e test.
=> Impl tinkerbell workflow removal on force.

pkg/providers/tinkerbell/pbnj/client.go
Remove accidental complete request logging that includes IPMI credentials.
=> Patch logging of ipmi credentials

.github/workflows/golangci-lint.yml
Checking if we can set goversion this way for the linter
=> pin linter execution in github actions to specific go version

pkg/providers/tinkerbell/hardware/config.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/validator.go
Builds on #1727
We don't separate static and interactive validation in Tinkerbell. Consequently, the static yaml validation and interactive workflow validation happen in the same function. This means we don't have an opportunity post yaml validation to clean up workflows before we validate none exist.
This change passes the force flag all the way down to validation logic so it can warn in stead of error when it sees workflows already in the Tinkerbell stack. In doing so, we gain yaml validation but have to assume something will clean up the workflows (the scrub function) later in the call path.
=> Fix delete workflows in Tinkerbell provider

cmd/eksctl-anywhere/cmd/downloadartifacts.go, cmd/eksctl-anywhere/cmd/importimages.go, pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/executables/builder.go, pkg/executables/helm.go, pkg/executables/helm_test.go, pkg/executables/kind.go, pkg/utils/urls/replace.go, pkg/utils/urls/replace_test.go
Related to https://github.com/aws/eks-anywhere/issues/1166
Instead of modifying the downloaded bundle manifests to point the helm
charts to the registry mirror, we leave them untouched, and we make helm
patch the requests urls on the fly.
The main advantage is that downloaded artifacts remain agnostic from the
registry. This allows to download them before having access to the
registry or even used the same artifacts for different registries.
* Added unit tests
* ~I'll test the whole flow e2e before merging~ Tested e2e manually
=> Helm registry mirror

.github/workflows/golangci-lint.yml, Makefile
This also fixes a bug when retrieving the linter version from the github
action file in mac. Now it uses yq instead of sed.
Tested in linux and mac
=> Run go linter on fix version in PRs and Makefile

pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go, pkg/providers/tinkerbell/validator.go
Add validation to check if machines are powered off.
If machines are powered on we want customers to have the opportunity to check they configured the correct machine. Users can force power off machines with the `--force-cleanup` flag.
This was tested locally by ensuring the machine was powered on and no `--force-cleanup` flag and again with `--force-cleanup`. The first case received the error below and the second proceeded to power off the machine and set PXE boot as expected.
```
❌ Validation failed    {"validation": "tinkerbell Provider setup is valid", "error": "validating machines are powered off: expecting host machines to be powered off; use --force-cleanup flag to power off machine and set pxe boot: hosts = [10.61.250.59]", "remediation": ""}
```
=> Validate host machines are powered off when provisioning with Tinkerbell

pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/snowmachineconfig.go, pkg/api/v1alpha1/snowmachineconfig_test.go, pkg/api/v1alpha1/snowmachineconfig_types.go, pkg/cluster/snow.go, pkg/cluster/snow_test.go
#1573 
Add snowmachineconfig defaulters to better separate api setDefaults vs provider context aware defaults.
Unit tests
=> Add snowmachineconfig context unaware defaulters

cmd/eksctl-anywhere/cmd/downloadartifacts.go
*Issue #, if available:* https://github.com/aws/eks-anywhere/issues/1753
CAPC/CAPT providers are not GA and not a part of the bundle-release.yaml corresponding to releases 0.7.x and 0.8.x
But all providers are part of the dev bundle-release.yaml when they get added to the manifest list to download for `download artifacts`. This PR adds a check to see if the provider's artifacts exist in the bundle-release.yaml
This will ensure download artifacts runs against any bundle-release.yaml irrespective of which providers are added in a release.
Tested against release-0.8 branch
=> Check if manifest exists before downloading

test/e2e/tools/eks-anywhere-test-tool/pkg/cloudwatch/cloudwatch.go, test/e2e/tools/eks-anywhere-test-tool/pkg/constants/constants.go
#1679 
The `eks-a-test-tool e2e fetch logs` command would error out if the log stream for a test did not exist. This PR changes that behavior to send a warning that the log stream does not exist & continue fetching the logs for the rest of the tests.
=> Gracefully handle non-existent CW log streams

cmd/eksctl-anywhere/cmd/downloadartifacts.go
*Issue #, if available:* https://github.com/aws/eks-anywhere/issues/1753
*Description of changes:* Cherry-pick https://github.com/aws/eks-anywhere/pull/1763
manual testing of the download artifacts command
=> [release-0.8] Check if manifest exists before downloading

cmd/eksctl-anywhere/cmd/internal/commands/artifacts/download.go, cmd/eksctl-anywhere/cmd/internal/commands/artifacts/download_test.go, cmd/eksctl-anywhere/cmd/internal/commands/artifacts/mocks/download.go, pkg/manifests/reader.go
Before this change, the code was depending on bundles.Charts, which calls
Bundles.Charts, which return a map. This is made the order non
predictable, hence making any tests depending on it, flaky.
This change has the added benefit that it makes the tests independent
from the number of charts stored in the bundles manifest. Hence we can
keep adding more info in the VersionsBundle without having to update
unrelated unit tests every time.
=> Make artifacts download tests more robust

internal/pkg/files/files.go, pkg/tar/packager.go, pkg/tar/router.go, pkg/tar/tar.go, pkg/tar/untar.go, pkg/tar/untar_test.go, pkg/tar/walker.go
Will complement https://github.com/aws/eks-anywhere/pull/1478
This adds tooling to untar files. It supports untaring from an `io.Reader`
which allows two chain this with other readers like gzip. It also
supports to route extracted files to different destinations, including
completely skipping their extraction.
Helpers are provided to extract a tarball into a folder.
Tar logic was updated to support nested folders.
`GzipFileDownloadExtract` was updated to use this new untar util.
Unit tests
=> Untar tools

release/api/v1alpha1/artifacts.go
Temporarily disabling this chart until we fix the error when pushing it
to an external registry.
=> Skip eks-a packages helm chart

pkg/providers/tinkerbell/tinkerbell.go
skip machine power validation when skipping power actions
=> skip machine power validation when skipping power actions

pkg/docker/registry_test.go
Before this change, the processing of the second image could be
triggered before the error from the second one was returned. This would
trigger a panic (since there was no expectation set for such calls in
the mock). The panic would kill the routine without reducing the counter
in the wait group, effectively creating a deadlock.
=> Avoid race concition in docker concurrent tests

cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/deletecluster.go, cmd/eksctl-anywhere/cmd/generatebundleconfig.go, cmd/eksctl-anywhere/cmd/supportbundle.go, cmd/eksctl-anywhere/cmd/upgradecluster.go, cmd/eksctl-anywhere/cmd/upgradeplancluster.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/features/features.go, pkg/providers/factory/providerfactory.go, pkg/providers/factory/providerfactory_test.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go
Adding the `--setup-tinkerbell` flag to the create command for Tinkerbell, which will be used to signify that the tinkerbell stack should be set up during create.
Also adding a feature flag `TINKERBELL_ENABLE_STACK_CREATION` to limit this feature for now
=> Add Tinkerbell stack setup flag and feature gate

pkg/executables/config/kind.yaml, pkg/executables/kind.go, pkg/executables/kind_test.go, pkg/executables/testdata/kind_config_extra_port_mappings.yaml
Adding support for extraPortMappings in Kind. This is needed for Tinkerbell provider
=> Add support for extraPortMappings in Kind

pkg/cluster/default_manager.go, pkg/cluster/tinkerbell.go
The Tinkerbell provider isn't represented in the cluster parsing code
resulting in warnings that could mislead the customer in logging. This
cl adds Tinkerbell type so the parsing logic is at least aware of them
but won't do anything with them.
=> Add Tinkerbell to new cluster parsing code

pkg/providers/snow/aws.go, pkg/providers/snow/defaults.go, pkg/providers/snow/defaults_test.go, pkg/providers/snow/mocks/aws.go
Currently we create a default ssh key with name `eksa-default` and import it to snow devices. 
There is a race. If multiple users create clusters in the same device set at the same time, eks-a creates default key for first cluster. The second cluster validation will fail at ec2 import-key-pair step because the key already exists in devices.
Before creating default ssh key, we check if the key exists on devices first. If the key exists on all devices, we skip the key generation and only assign the key name to machine config.
- unit tests
=> Use default ssh key if already exists in snow devices

pkg/executables/kubectl.go
This:
```
Error: failed to display upgrade plan: failed getting EKS-A cluster to build current cluster Spec: cluster mgmt7 not found of custom resource type clusters.anywhere.eks.amazonaws.com
```
Instead of:
```
Error: failed to display upgrade plan: failed getting EKS-A cluster to build current cluster Spec: getting eksa cluster: error: error executing jsonpath "{.items[0]}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
template was:
{.items[0]}
object given to jsonpath engine was:
map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
```
=> Print a better cluster not found error

docs/content/en/docs/reference/clusterspec/irsa.md
The pod identity webhook repository has some recent changes due to which its installation doesn't work. This PR updates the link of the pod identity webhook repo to an older commit that does work, and updates the image to a previous tag instead of latest.
Installed pod identity webhook with the updated Readme and IRSA worked as expected
=> Update IRSA doc to point to the working commit and image tag

go.mod, go.sum
Upgrading eks-a to use latest CAPC in anticipation of next release
CAPC version is already updated in build-tools, so we can update it here to use the latest type definitions for CAPC structs
Unit tests pass. CloudStack cluster successfully created without using bundle overrides. Upgrading now using shared network with kube-vip
=> Upgrading eks-a to use capc v0.4.2

pkg/cluster/fetch.go
Fetching the EKS-D release manifest could return a number of different errors if those release objs aren't present on the cluster. We should default to fetching the EKS-D object from the URL & then applying it to the cluster after upgrade.
Tilt, cluster created with 0.7 and upgraded with 0.8.1
=> Default to fetching eks-d release from url if it can't be fetched from the cluster

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/docker/docker.go, pkg/providers/mocks/providers.go, pkg/providers/provider.go, pkg/providers/snow/snow.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
*Issue #, if available:* https://github.com/aws/eks-anywhere/issues/1669
This PR removes the cloudstack-specific logic (in a backwards compatible way) from the cluster-manager and moves it to the provider for both CloudStack and VSphere
=> Refactoring cluster manager to invoke provider's SpecChanged method

test/e2e/upgrade_test.go
When running the cloudstack Upgrade test as is, it fails immediately with error `Error: the cluster config file provided is invalid: control plane node count cannot be an even number`. This PR sets the control plane node count to an odd number for this test
E2e test passed locally
=> Fixing cloudstack upgrade test

pkg/cluster/config.go
https://github.com/aws/eks-anywhere/issues/1826
Make sure that the FluxConfig is included in the cluster DeepCopy
=> make sure FluxConfig is included in cluster deepcopy

pkg/providers/vsphere/testdata/expected_results_main_cp_cloud_provder_and_csi_driver_credentials.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp_cloud_provider_credentials.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp_csi_driver_credentials.yaml, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
This will allow users to configure cloud provider and CSI Driver with different credentials using new environment variables.
The new environment variables are optional, and if not set, the required variables (EKSA_VSPHERE_USERNAME and EKSA_VSPHERE_PASSWORD) will be used.
Currently the same credentials are used when configuring CAPV, cloud provider and CSI driver. This change will allow users to set new environment variables to be used when configuring cloud provider and CSI credentials:
```
// cloud provider credentials
"EKSA_VSPHERE_CP_USERNAME"
"EKSA_VSPHERE_CP_PASSWORD"
// CSI driver credentials 
"EKSA_VSPHERE_CSI_USERNAME"
"EKSA_VSPHERE_CSI_PASSWORD"
```
The new credentials are optional, if not set then the following credentials will …
=>  Allow users to configure cloud provider and CSI Driver with different credentials 

test/framework/cloudstack.go
Return the proper required env var array.
=> Fix cloudstack e2e tests

docs/content/en/docs/community/docs_contributing.md
There are a few formatting problems in the [Contributing to EKS Anywhere documentation](https://anywhere.eks.amazonaws.com/docs/community/docs_contributing/) guide that this seeks to address.
=> Corrected formatting issues on Docs contrib guide

controllers/controllers/resource/template.go, pkg/providers/docker/config/template-md.yaml, pkg/providers/docker/docker.go, pkg/providers/docker/docker_test.go, pkg/providers/docker/testdata/capd_valid_full_oidc_md_expected.yaml, pkg/providers/docker/testdata/capd_valid_minimal_oidc_md_expected.yaml, pkg/providers/docker/testdata/no_machinetemplate_update_md_expected.yaml, pkg/providers/docker/testdata/valid_deployment_custom_cidrs_md_expected.yaml, pkg/providers/docker/testdata/valid_deployment_md_expected.yaml, pkg/providers/docker/testdata/valid_deployment_md_taints_expected.yaml, pkg/providers/docker/testdata/valid_deployment_multiple_md_taints_expected.yaml, pkg/providers/docker/testdata/valid_deployment_node_labels_md_expected.yaml, pkg/providers/vsphere/vsphere.go, test/e2e/labels_test.go, test/e2e/taints_test.go, test/framework/vsphere.go, test/framework/workergroups.go
https://github.com/aws/eks-anywhere/issues/1626
Add support for upgrading labels and taints for the Docker provider which was missing before.
Ran e2e tests while running tilt to update the controller
=> Add upgrade support of labels/taints for Docker

test/e2e/download_artifacts_test.go, test/framework/cluster.go
*Issue #, if available:* https://github.com/aws/eks-anywhere/issues/1329
Runs download artifacts command only to make sure it generates the tarball
Ran the test locally 
=> Add e2e test for download artifacts command

test/e2e/taints_test.go
These changes were missed from https://github.com/aws/eks-anywhere/pull/1851 causing the test to fail. 
Ran `TestDockerKubernetes122Taints`
=> Fix e2e taint test for docker

pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go
One customer not using kube-vip has identified an issue where the eks-a controller is attempting to enable kube-vip after a cluster is created which is triggering an upgrade. They have found a workaround by setting this environment variable on the eks-a controller pod, and this PR is codifying that.
=> Adding environment variable setting on the eksa controller for kube-vip

pkg/clustermanager/cluster_manager.go, pkg/workflows/create.go
It was confusing that we were logging this for all providers, even when
there wasn't any storage class being installed. Now it only logs when
the provider returns a storage class.
=> Log storage class install only for supported providers

controllers/controllers/resource/testdata/eksa-cluster-cloudstack_no_changes.yaml, pkg/api/v1alpha1/cloudstackdatacenterconfig_types.go, pkg/api/v1alpha1/cloudstackmachineconfig_types.go, pkg/cluster/cloudstack.go, pkg/cluster/config.go, pkg/cluster/default_manager.go, pkg/cluster/parse_test.go, pkg/cluster/testdata/cluster_1_20_cloudstack.yaml
This PR was implemented at the suggestion of @jiayiwang7 to enable marshalling of cloudstack yamls, and it uncovered a broken unit test. The implementation is heavily based on VSphere's
=> Adding cloudstackEntry to enable marshalling cloudstack yamls

test/framework/tinkerbell.go
Remove unused tinkerbell e2e method which wrongly returns vsphere vars.
=> Remove unused RequiredTinkerbellEnvVars method

test/framework/cloudstack.go
Adding the base64 encoded secret env var to list of required env vars for CloudStack e2e tests
E2e test started successfully.
=> Adding base64 encoded secret as required env var for cloudstack e2e tests

Makefile, scripts/generate_checksum.sh
Creates a make target for generating checksums' script. Also cleans up extra unnecessary files.
`make generate-checksums`
=> Create a make target and clean up for generating checksums

internal/pkg/api/snow.go, test/e2e/README.md, test/e2e/simpleflow_test.go, test/framework/snow.go
#1108 
Add simple flow e2e test for snow
- TestSnowKubernetes121SimpleFlow (create and delete w K8s version 1.21)
- `make local-e2e`
=> Add snow simple flow e2e test

.gitignore
It can be useful to keep files around in a repository that you use
frequently but we don't have a dedicated directory for housing them.
Now we do, `.ignore` :)
=> Add .ignore directory to .gitignore

pkg/docker/registry.go
It used to use half the number of machine cores. Now it uses the full
number of cores. This saves around 1 minute in download and import with
8 cores.
=> Bump number of workers for docker image processing

cmd/eksctl-anywhere/cmd/downloadimages.go, cmd/eksctl-anywhere/cmd/import_images.go, pkg/tar/gzip.go, pkg/tar/gzip_packager.go, pkg/tar/gzip_test.go, pkg/tar/tar.go
This decreases the tarball size from 9.5GB to 2.9 GB.
It increases the time `download images` takes from ~6:30 to ~12:30
Run download and import images manually
=> Gzip artifacts tarball

cmd/eksctl-anywhere/cmd/internal/commands/artifacts/download.go, cmd/eksctl-anywhere/cmd/internal/commands/artifacts/download_test.go
Since the eks-a tools image is already packaged individually, we don't
need to include it in the big tar with the rest of the images.
Ran download-import flow manually.
=> Avoid packaging tools image twice in tarball

go.sum, pkg/providers/cloudstack/cloudstack.go, pkg/providers/docker/docker.go, pkg/providers/mocks/providers.go, pkg/providers/provider.go, pkg/providers/snow/snow.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/vsphere/vsphere.go, pkg/workflows/create.go, pkg/workflows/create_test.go
For tinkerbell provider, we need to install and set tinkerbell up on the bootstrap cluster before installing CAPI/CAPT resources. 
This PR adds a new step to the create workflow to do operations after the bootstrap cluster is installed but before the CAPI components are installed on it 
=> Add PreCapiInstallOnBootstrap

test/e2e/download_artifacts_test.go
This test needs the env vars for vsphere clusters. Adding 'VSphere' in
the test name will take care of this automatically.
=> Rename TestVSphereDownloadArtifacts E2E test

pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
=> Make insecure flag and thumbprint in datacenter config mutable

pkg/aws/creds_test.go, pkg/clusterapi/apibuilder.go, pkg/clusterapi/apibuilder_test.go, pkg/clusterapi/identity.go, pkg/clusterapi/identity_test.go, pkg/clusterapi/registryMirror.go, pkg/clusterapi/registryMirror_test.go, pkg/providers/snow/apibuilder_test.go
#1574 
Add support in snow provider:
- OIDC
- AWS IAM Auth
- Pod IAM
- unit tests
** adding identity support exceeds snow ec2 user data limit. will test once we increase the data limit.
=> Add OIDC, pod IAM and AWS IAM support for snow

pkg/addonmanager/addonclients/files.go, pkg/addonmanager/addonclients/fluxaddonclient.go, pkg/addonmanager/addonclients/upgrader.go, pkg/dependencies/factory_test.go
removing internal use of the unneeded `gitOpts` struct from the FluxAddonClient. The whole options argument will be removed in favor of directly injecting dependencies in an upcoming pr.
this is an intermediate step to factoring out the `git.Provider` interface into two parts, a GitClient (responsible for local repo actions) and a GitProvider (responsible for actions on a remote provider), which will be generated by the factory and injected directly into the FluxAddonClient (along with the writer) rather than using the intermediate `gitOpts` struct.
`make`, created a cluster with gitops, upgrade it, and deleted it.
created a cluster w/out gitops.
By submitting this pull request, I confirm that you can use, …
=> Remove internal use of `gitOpts` struct from FluxAddonClient

test/e2e/download_artifacts_test.go
This test doesn't need registry mirror configuration. It's failing currently because it expects those vars to be set but the test name doesn't have the required regex. This PR removes the registry mirror config and so the need for those env vars
=> Remove registry mirror from download artifacts e2e

controllers/Tiltfile, controllers/main.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/features/features.go, pkg/features/internal.go, pkg/features/mutexmap.go, pkg/features/mutexmap_test.go
As of now we had these as local changes whenever we wanted to test the full lifecycle api work so checking some of the automation in. I added the ability to read and set the env var for Tilt, as well as set the env var when running create cluster. 
I debated using the bundle manifest for getting the controller image and copying the govc and helm binaries from that image using a multi-stage build, but for this use case it didn't feel necessary to have to write the logic to parse that file in the Tiltfile and use an image that is built from main instead of from local. I also looked into setting the env vars using kustomize substitutions like they do in cluster-api, but realized that that is more effort than needed for this use case due to …
=> Add env var support for lifecycle api work with tilt

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml
This new environment variable will be used in the forthcoming e2e test for the generic Git provider
=> Add Git SSH key env variable for e2e tests

test/e2e/flux_test.go, test/e2e/upgrade_test.go, test/e2e/workload_clusters_test.go, test/framework/flux.go
#1961 
Renaming this from `WithFlux` to `WithFluxLegacy` since GitOpsConfig will eventually be deprecated. 
=> Rename existing WithFlux spec opt to WithFluxLegacy

internal/pkg/api/cluster.go, test/framework/cluster.go, test/framework/flux.go
#1960 
Adds method to generate FluxConfig in e2e tests
=> Add method to generate FluxConfig in e2e tests

pkg/executables/helm.go, pkg/executables/helm_test.go, pkg/executables/helpers_test.go, test/e2e/curated_packages_test.go, test/e2e/simpleflow_test.go, test/framework/cluster.go, test/framework/executables.go, test/framework/helm.go
Adding E2E tests for curated packages install workflow. This test performs Helm install of eks-anywhere-packages helm chart on the e2e test cluster.
```bash
$ helm list --kubeconfig /etc/kubernetes/admin.conf 
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                                                   APP VERSION                                    
eks-anywhere-packages   default         1               2022-04-28 02:58:40.9813308 +0000 UTC   deployed        eks-anywhere-packages-0.1.6+3fec792b394e5eae46937edaa2b14afa32a9ad77    v0.1.6-3fec792b394e5eae46937edaa2b14afa32a9ad77
$ kubectl get po --kubeconfig=/etc/kubernetes/admin.conf -n eksa-packages
NAME                                    READY …
```
=> Add e2e test for curated packages

test/framework/flux.go
Forgot to assign the git client to the e2e test. caused a failure in the tests when attempting to use the client.
also found a quick rename that needed to happen.
=> make sure to assign a git client for the tests, DAN

test/framework/flux.go
we were not setting the GitClient in the flux validation flow. This was a miss on my part that caused an issue with the tests.
=> set git client in Flux Validation flow

test/e2e/curated_packages_test.go
The test name was not matching the regex required to set up vSphere environment.
=> Fix packages install test name

pkg/docker/concurrent.go
When using a WaitGroup its important to add the managed routines to the wait group from _outside_ the managed routine. This is because goroutine scheduling is non-deterministic making it possible for wg.Wait() to be called _before_ all wg.Add() calls resulting in a panic.
=> Fix concurrent image push race condition

pkg/dependencies/factory.go, pkg/git/git.go, pkg/git/gitclient/gitclient.go, pkg/git/gitclient/gitclient_test.go, pkg/git/gitclient/mocks/client.go, pkg/git/mocks/git.go
https://github.com/aws/eks-anywhere/issues/1956
Adding validation to see if the provider git repo is valid. Used https://github.com/go-git/go-git/blob/master/_examples/ls-remote/main.go as a reference.
Note that https://github.com/aws/eks-anywhere/pull/1934 needs to be merged and integrated with to properly test this feature.
/hold
e2e testing tbd
=> Add validation for byo git

pkg/git/factory/gitfactory.go, pkg/git/factory/gitfactory_test.go, test/framework/flux.go, test/framework/git.go
Recent changes in refactoring resulted in the clone path to follow the same path as where we edit the cluster config file for the flux tests, causing the tests to fail. Added the option to override the default path that is set so we don't affect the CLI code as well just for e2e test validations.
Ran e2e test
=> Fix flux tests to clone repository in the right path

config/crd/kustomization.yaml, controllers/controllers/clusters/vsphere.go, controllers/controllers/resource/fetcher.go, pkg/addonmanager/addonclients/fluxaddonclient.go, pkg/cluster/fetch.go, pkg/cluster/fetch_test.go, pkg/cluster/spec.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/validations/kubectl.go, pkg/validations/mocks/kubectl.go, pkg/validations/upgradevalidations/immutableFields.go
https://github.com/aws/eks-anywhere/issues/1986
Set up to support `eksctl anywhere upgrade cluster` with the `fluxConfig` present on the cluster.
Many of the methods in the fetcher and cluster spec builder shadow the existing GitOpsConfig methods. I've captured an issue to come back and remove these redundant methods once we deprecate the GitOpsConfig, will link this PR so that in +2 minor versions we can remove the redundant methods. https://github.com/aws/eks-anywhere/issues/1987 
create a cluster with the `fluxConfig`; upgrade the cluster.
=> support `upgrade cluster` with `FluxConfig` present

pkg/cluster/fetch.go, pkg/cluster/spec.go
when converting the GitOpsConfig to a FluxConfig in the cluster spec option, it is possible to override it as nil if `WithFluxConfig()` is called as an option after `WithGitOpsConfig()`, as is happening here when performing an upgrade across versions.
By moving the conversion up a level we can ensure that the conversion takes place without being overridden. 
re-ran failing upgrade test.
=> convert GitOpsConfig to flux config when reading spec from cluster

pkg/providers/tinkerbell/hardware/catalogue.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/validator.go, pkg/providers/tinkerbell/validator_helper_test.go, pkg/providers/tinkerbell/validator_test.go
We lazily load hardware manifests during a set of validation functions. Consequently, validation functions must be called in a specific order creating fragility and hard to understand validation logic.
=> Remove lazy loading of hardware in tinkerbell validation

pkg/clients/kubernetes/mocks/kubectl.go, pkg/clients/kubernetes/unauth.go, pkg/clients/kubernetes/unauth_test.go, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go
Part of https://github.com/aws/eks-anywhere/issues/1106, needed only in snow cli provider and not in the controller for now
Uni tests
=> Add `Delete` method to kube client

release/pkg/images/images.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/utils/utils.go
Skopeo copy sometimes fails due to flaky reasons. This PR
(i) implements retry logic around skopeo copy
(ii) Returns the combined standard output and standard error of command executions for debugging
=> Implement retry logic for Skopeo copy

pkg/clusterapi/apibuilder.go, pkg/clusterapi/name.go, pkg/clusterapi/name_test.go
#1106 
Break down the POC upgrade PR #1968 
Part of the snow upgrade flow. 
unit tests
=> Add name util functions for capi apibuilder

pkg/providers/snow/apibuilder.go, pkg/providers/snow/apibuilder_test.go, pkg/providers/snow/fetch.go, pkg/providers/snow/objects.go, pkg/providers/snow/objects_test.go, pkg/providers/snow/snow.go, pkg/providers/snow/snow_test.go, pkg/providers/snow/testdata/expected_results_main_cp.yaml, pkg/providers/snow/testdata/expected_results_main_md.yaml
#1106 
Break down the POC upgrade PR #1968 
This PR compares the existing snowmachinetemplate in cluster and the snowmachinetemplate generated from cluster spec, to determine whether to create new machinetemplate since the object is immutable.
The `snow.CAPIObjects(ctx context.Context, clusterSpec *cluster.Spec, kubeClient kubernetes.Client)` is sharable between cli and controller.
- unit tests
=> Generate CAPI objects for snow upgrade and create

README.md
The Certified Kubernetes Marks and Participant Kubernetes Combinations may be used with a Qualifying Offering for a particular version of Kubernetes (e.g., Kubernetes x.y) until the later of:
12 months after the release date of Kubernetes x.y, or
9 months after the release date of the next minor release (e.g., Kubernetes x.y+1)
v1.21.0 was released on April 8, 2021
https://github.com/kubernetes/kubernetes/releases/tag/v1.21.0
v1.22.0 was released on August 4, 2021
https://github.com/kubernetes/kubernetes/releases/tag/v1.22.0
Therefore, the expiration date for v1.21 is May 4, 2022.
=> k8s 21 certification expires 5/4

pkg/providers/snow/snow.go, pkg/providers/snow/snow_test.go
#1106 
Add set defaults and validation step for snow. Compare snow eks-a and bundle resources to see if provider upgrade is needed.
unit tests
=> Add SetupAndValidateUpgradeCluster, UpgradeNeeded for snow

pkg/config/config.go, pkg/git/factory/gitfactory.go
#2000 
Set `SSH_KNOWN_HOSTS` to same value as `EKSA_GIT_KNOWN_HOSTS` to avoid key mismatch errors
=> Set SSH_KNOWN_HOSTS to same value as EKSA_GIT_KNOWN_HOSTS

cmd/eksctl-anywhere/cmd/apply.go, cmd/eksctl-anywhere/cmd/applypackages.go, cmd/eksctl-anywhere/cmd/createpackages.go, cmd/eksctl-anywhere/cmd/deletepackages.go, cmd/eksctl-anywhere/cmd/describe.go, cmd/eksctl-anywhere/cmd/describepackages.go, cmd/eksctl-anywhere/cmd/upgradepackages.go, go.mod, go.sum, pkg/curatedpackages/bundle.go, pkg/curatedpackages/packageclient.go, pkg/curatedpackages/packageclient_test.go
This PR includes the following the functionalities:
Using Kubectl, delete all curated packages provided by the user through eksctl anywhere delete packages.
Using Kubectl, describe all curated packages requested by the user.
Find the active bundle controller and update the active bundle used. 
Using Kubectl, create curated packages from file(s) provided by the user.
Using kubectl, apply curated packages from file(s) provided by the user.
=> Add Kubectl Wrappers for Curated Packages

cmd/eksctl-anywhere/cmd/createcluster.go, cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, pkg/api/v1alpha1/cluster.go, pkg/config/config.go, pkg/executables/flux.go, pkg/executables/flux_test.go, pkg/git/factory/gitfactory.go, pkg/validations/createvalidations/gitops_test.go
This PR makes a few changes:
1. Renames git variables to use `Passphrase` instead of `Password` to avoid ambiguity & maintain consistency with git terminolgy
2. Adds repository URL for the generic git repo to the e2e test environment variables
3. Adds validations to ensure that the known hosts and private key file environment variables are set
=> Generic git env var validations and repository

docs/content/en/docs/reference/clusterspec/vsphere.md
https://github.com/aws/eks-anywhere/pull/1730
Documentation showing how to configure Cloud Provider and CSI Driver
with separate credentials
=> Add documentation about new environment variables

release/api/v1alpha1/artifacts.go, release/pkg/test/testdata/main-bundle-release.yaml
This had been disabled because of a problem pushing the packages to
harbor (apparently something to do with semver), gaslor@ gave us the
go ahead to re-enable this.
=> Re-enabling eks-anywhere-packages controller

pkg/api/v1alpha1/cluster.go
Temporarily remove git env var validations to unblock github provider operations. Will find a more effective way to validate this
=> Temporarily remove git env var validations

release/api/v1alpha1/artifacts.go
The intent here is to make sure that artifacts for curated packages (namely our controller image and our helm chart) get included in builds.
/cc @jonahjon  @ivyostosh
=> Add the packages controller to the build artifacts.

pkg/providers/cloudstack/cloudstack.go, pkg/providers/docker/docker.go, pkg/providers/provider.go, pkg/providers/tinkerbell/template.go, pkg/providers/vsphere/vsphere.go
We had a latent bug (see #2011) for a while and we never discovered it because none
of the providers were actually using the cluster argument. This change
makes a bit more clear what is being used and what is not.
=> Cleanup providers for generate CAPI spec on create

pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/delete.go, pkg/providers/tinkerbell/ssh.go, pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go, pkg/providers/tinkerbell/upgrade.go
The provider is in tinkerbell package and should be exported, hence its renamed to `Provider` meaning consumers refer to it as `tinkerbell.Provider`.
_There are no functional changes_
=> Rename tinkerbellProvider to Provider

docs/content/en/docs/reference/changelog.md, pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/clustermanager/retrier_client.go, pkg/dependencies/factory.go, pkg/executables/helm.go, pkg/executables/helm_test.go
https://github.com/aws/eks-anywhere/issues/2009
Adding support for passing in proxy configuration env vars if specified to the helm template command. This was not seen before when using the manifest directly because it just applies the yaml, not through oci. Refactoring some of the building of these env vars and will follow up with another issue to make use of these functions for the providers. 
unit tests and E2E tests with proxy configuration
/hold
/approve
=> Fix bug in specifying proxy configuration for helm template

controllers/controllers/resource/reconciler_test.go, controllers/controllers/resource/testdata/cloudstackDatacenterConfigSpec.yaml, controllers/controllers/resource/testdata/cloudstackEtcdadmcluster.yaml, controllers/controllers/resource/testdata/cloudstackKubeadmconfigTemplateSpec.yaml, controllers/controllers/resource/testdata/cloudstackKubeadmcontrolplane.yaml, controllers/controllers/resource/testdata/cloudstackMachineConfigSpec.yaml, controllers/controllers/resource/testdata/cloudstackMachineDeployment.yaml, controllers/controllers/resource/testdata/cloudstackMachineTemplate.yaml, controllers/controllers/resource/testdata/eksa-cluster-cloudstack.yaml, controllers/controllers/resource/testdata/eksa-cluster-cloudstack_no_changes.yaml, controllers/controllers/resource/testdata/eksa-cluster.yaml, controllers/controllers/resource/testdata/eksa-cluster_no_changes.yaml, controllers/controllers/resource/testdata/expectedCloudStackMachineDeployment.yaml, controllers/controllers/resource/testdata/expectedCloudStackMachineDeploymentOnlyReplica.yaml, controllers/controllers/resource/testdata/expectedCloudStackMachineDeploymentTemplateChanged.yaml, controllers/controllers/resource/testdata/expectedVSphereMachineDeployment.yaml, controllers/controllers/resource/testdata/expectedVSphereMachineDeploymentOnlyReplica.yaml, controllers/controllers/resource/testdata/expectedVSphereMachineDeploymentTemplateChanged.yaml, controllers/controllers/resource/testdata/vsphereDatacenterConfigSpec.yaml, controllers/controllers/resource/testdata/vsphereEtcdadmcluster.yaml, controllers/controllers/resource/testdata/vsphereKubeadmconfigTemplateSpec.yaml, controllers/controllers/resource/testdata/vsphereKubeadmcontrolplane.yaml, controllers/controllers/resource/testdata/vsphereMachineConfigSpec.yaml, controllers/controllers/resource/testdata/vsphereMachineDeployment.yaml, controllers/controllers/resource/testdata/vsphereMachineTemplate.yaml, pkg/cluster/spec.go
We weren't validating the cluster config for new specs. That PR adds that call in `pkg/cluster/spec.go`. Now that we validate that, the unit tests caught cluster naming errors in some test files so renaming all of those to fix that error
=> Call ValidateConfig for new cluster specs

pkg/providers/tinkerbell/hardware/index.go, pkg/providers/tinkerbell/hardware/index_test.go
Validations on Tinkerbell hardware involve various lookups in the Hardware catalogue. Providing an indexing capability yields an efficient lookup and reverse lookup mechanism for validation logic.
The next PR will leverage a `FieldIndexer` for Hardware, BMCs and Secrets read from the hardware YAML. Then, the validation logic can be simplified before being extracted into a set of validator constructs.
=> Add indexing capability for Tinkerbell hardware.

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/fluxconfig.go, pkg/api/v1alpha1/fluxconfig_test.go
We needed a way to access the FluxConfig spec for validations. We already have a `ParseClusterConfigFromContent` function that accepts any `KindAccessor` type (such as Cluster, FluxConfig, etc.) to parse those contents. So I renamed that function to `ParseConfigFromContent` since it isn't exclusive to the cluster config, and I am using it to pass in the FluxConfig type and parse those contents so that we can have access to that spec is the gitops validations function.
=> Add more validations for FluxConfig

pkg/addonmanager/addonclients/fluxaddonclient.go
when using a custom path, we need to validate that the cluster configuration file path does not exist, rather than the base path; when using the base path, this validation fails if the fluxConfig is present (which it is, as we push it prior to pushing the cluster configuration)
=> check that full cluster path exists in git validations

test/framework/flux.go
if the git repository does not exist (failed to clone, already cleaned up by delete, etc) do not attempt to clean it up after running FluxGit tests.
ran this via the framework from my local and confirmed working
=> only clean up git tests if file is left behind

config/crd/bases/anywhere.eks.amazonaws.com_fluxconfigs.yaml, config/manifest/eksa-components.yaml, designs/generic-git-provider-gitops.md, pkg/api/v1alpha1/fluxconfig.go, pkg/api/v1alpha1/fluxconfig_test.go, pkg/api/v1alpha1/fluxconfig_types.go, pkg/api/v1alpha1/fluxconfig_webhook_test.go, pkg/api/v1alpha1/testdata/cluster_1_19_flux_git.yaml, pkg/api/v1alpha1/testdata/cluster_1_19_flux_validgit_sshkey.yaml, pkg/api/v1alpha1/testdata/cluster_invalid_flux_unset_gitrepourl.yaml, pkg/api/v1alpha1/testdata/cluster_invalid_flux_wrong_gitsshkeyalgo.yaml, pkg/executables/flux.go, pkg/executables/flux_test.go, pkg/validations/upgradevalidations/immutableFields.go, pkg/validations/upgradevalidations/preflightvalidations_test.go
These code changes let the users set the ssh key algorithm field in the cluster spec.
The new cluster spec would look like:
````
kind: FluxConfig
metadata:
name: fc-byog
spec:
git:
repositoryUrl: ssh://git@github.com/owner/byog.git
sshKeyAlgorithm: ed25519
```
- Unit tests
- Cluster creation
=> Set ssh key algorithm for Git Provider Config

cmd/eksctl-anywhere/cmd/applypackages.go, cmd/eksctl-anywhere/cmd/common.go, cmd/eksctl-anywhere/cmd/createpackages.go, cmd/eksctl-anywhere/cmd/deletepackages.go, cmd/eksctl-anywhere/cmd/describepackages.go, cmd/eksctl-anywhere/cmd/generatepackage.go, cmd/eksctl-anywhere/cmd/get.go, cmd/eksctl-anywhere/cmd/installpackagecontroller.go, cmd/eksctl-anywhere/cmd/installpackages.go, cmd/eksctl-anywhere/cmd/listpackages.go, cmd/eksctl-anywhere/cmd/upgradepackages.go, pkg/curatedpackages/bundle.go, pkg/curatedpackages/curatedpackages.go, pkg/curatedpackages/packageclient.go, pkg/curatedpackages/packagecontrollerclient.go, pkg/workflows/create.go
Provides the capability to print a license during the following scenarios:
- When installing curated packages as part of cluster creation
- When installing curated packages controller through install packagecontroller
- When creating curated packages through create, apply, and install commands
- Fixes bug with upgrade to use apply instead of create
- Fixes bug for get commands to print a new line carriage
- Fixes bug for kubeconfig outside of current directory
- Unify curatedpackages dependencies creation. 
=> Curated packages bugfixes

release/api/v1alpha1/artifacts.go, release/pkg/test/testdata/main-bundle-release.yaml
We expect all the artifacts URIs to be http/s urls to publicly downloadable
files. These two are OCI artifacts.
=> Remove packages image and chart from manifest list

release/Makefile, release/pkg/assets_eksd.go, release/pkg/test/files.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.8-bundle-release.yaml
This prevents us from having to update the testdata files for every new commit on eks-anywhere-build-tooling.
=> Make git commit field static for dry run

pkg/addonmanager/addonclients/fluxaddonclient.go, test/framework/flux.go
make the path that the tests use to write the Git config to the test git repo variable based on the cluster name (which is a hash of the test name).
change the path validation back so that if something writes to the top-level path we validate it and fail faster.
=> make test git path unique depending on test

Makefile
Updating the Makefile branch name to release-0.9
/hold
=> Update branch name in Makefile

pkg/bootstrapper/bootstrapper.go, pkg/bootstrapper/mocks/client.go, pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/mocks/client.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go
This PR covers the following:
- Adds extraPortMappings on the Kind cluster if the `--setup-tinkerbell` flag is specified
- Installs `tink-server` and `tink-controller` on the bootstrap cluster
- TODOs for installing boots, hegel and rufio when those are built and added to the bundle. This step is pending on Tinkerbell changes to support K8S model.
=> Initial Implementation of Tinkerbell stack installation

Makefile, release/pkg/assets_cluster_controller.go
The cluster-controller git tag is obtained by getting the latest git tag across all branches, but this doesnt work for new release branches because the new tag corresponding to the release branch has not been cut yet, so there would be a mismatch between the tag and the branch.
Hence removing this tag name from the S3 URI path.
=> Remove git tag from cluster-controller manifest path

test/framework/flux.go
we previously created a new git repo for each test. now, we re-use the same repo for BYO git tests. 
this means we need to pull changes before pushing updates when validating flux, since we'll run into non-fast-forward updates otherwise. 
we already do pull-before-push in the actual business logic of the product, this is a test framework issue that didn't show up previously. 
=> pull before push to avoid non-fast-forward updates in gitops validations

test/framework/flux.go
we can end up with the same cluster name if the tests run on the same instance, leading to collision between gitops test configurations; let's use jobId (unique based on instance and test name) as the path to always avoid this.
=> use jobId not cluster name as config path in gitops tests

pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/hardware/catalogue.go, pkg/providers/tinkerbell/hardware/catalogue_bmc.go, pkg/providers/tinkerbell/hardware/catalogue_bmc_test.go, pkg/providers/tinkerbell/hardware/catalogue_hardware.go, pkg/providers/tinkerbell/hardware/catalogue_hardware_test.go, pkg/providers/tinkerbell/hardware/catalogue_secret.go, pkg/providers/tinkerbell/hardware/catalogue_secret_test.go, pkg/providers/tinkerbell/hardware/catalogue_test.go, pkg/providers/tinkerbell/hardware/catalogue_validations.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/validator.go, pkg/providers/tinkerbell/validator_test.go
This PR wires indexing into the `Catalogue` construct and introduces the method set required to operate with the `Catalogue`. The slices the `Catalogue` maintains for Hardware, BMCs and Secrets are still exposed to accommodate existing validation logic. A subsequent PR will unexport these fields and change the validation logic to take advantage of indexing and the various behaviors. 
There are 4 indexes defined for the `Catalogue` as options. These indexes are based on the existing needs of the validation logic. A future PR will introduce a builder that considers `force` and `skip-power-actions` flags to construct the right indexes and validations for validating hardware configuration. This, in turn, will remove the need for any business logic to know about flags.
Existing validation …
=> Implement Tinkerbell hardware catalogue indexes

pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/hardware/catalogue.go, pkg/providers/tinkerbell/hardware/catalogue_bmc.go, pkg/providers/tinkerbell/hardware/catalogue_hardware.go, pkg/providers/tinkerbell/hardware/catalogue_secret.go, pkg/providers/tinkerbell/hardware/catalogue_test.go, pkg/providers/tinkerbell/hardware/catalogue_validations.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/validator.go, pkg/providers/tinkerbell/validator_test.go
Build on #2016 
Having implemented indexing this change swaps out existing functions to use the public API of the catalogue construct and unexports fields that need to be controlled by the catalogue. This ensures indexing capabilities are consistently applied and avoids any accidental mutation of internal data structures.
=> Wire hardware catalogue with Tinkerbell provider

release/pkg/assets_eksd.go, release/pkg/generate_spec.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.8-bundle-release.yaml
As part of incorporating the CAPC artifacts into the prod release, we need to build them here so they are populated in the bundle manifest. This PR was based on https://github.com/aws/eks-anywhere/pull/2052/files
=> Adding CAPC artifacts into prod bundle

pkg/git/git.go, pkg/git/gitclient/gitclient.go, test/framework/flux.go
When a remote repository is 'up to date' and we pull, go-git returns an error, which they intentionally call [`NoErrAlreadyUpToDate`
](https://github.com/go-git/go-git/blob/f0b111ab70e4e90013658b0835929b2083902017/remote.go#L32).
In our code, we mimic that, and return our own up-to-date error if we pull and the repo is up-to-date.
This change makes sure that the git test validations catch that up-to-date error and continue if it's present.
I've created [a ticket to re-visit this and simplify it](https://github.com/aws/eks-anywhere/issues/2092); there's a place in the FluxAddonClient where we use a retrier to Pull, and it retries on this up-to-date error, creating noisy logs; we do this because in our original testing if we pulled from the …
=> Catch up to date pull err

Makefile
`eksctl anywhere download images` was failing with the following error:
```
Error: unable to initialize executables: retrieving executable tools image from bundle in dependency factory: invalid version v0.9.0, no matching release found
```
It seems like we had some refactoring that changed where this variable was injecting, so this wasn't actually injecting the value here like it was supposed to and using the default dev release url instead: https://github.com/aws/eks-anywhere/blob/2318acd63b7fffae95937bedac49feba08fbeff0/pkg/manifests/releases/read.go#L15
Tested binary after building binary with the following target
```
GOOS=darwin GOARCH=amd64 /usr/local/go/bin/go build -tags "" -ldflags "-s -w -X …
```
=> Fix manifestURL injection in Makefile

Makefile
In AWSIAM e2e test:
```
awsiam.go:56: Error downloading aws-iam-authenticator client: getting EKS-D release spec from bundle: invalid version v0.0.0-dev-release-0.9, no matching release found
```
Staging CLI fails to find the matching version of eks-a from the default eks-a-release.yaml ("https://dev-release-prod-pdx.s3.us-west-2.amazonaws.com/eks-a-release.yaml"). 
We should build the e2e binary that uses the release manifest url with corresponding release version.
Override default release manifestURL w RELEASE_MANIFEST_URL when building e2e binary.
=> Fix e2e binary build

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml
the cluster names are based off of the branch name but have `.` replaced with `-`; this is a quick fix to get the release branch tests to clean up the right clusters by doing a replace on `.` with `-` in the branch name var
=> make sure to replace . with - in cluster names

docs/content/en/docs/tasks/packages/_index.md
The original command includes an invalid (long) dash
*Description of changes:* Update eksctl command
*Testing (if applicable):* Ran the updated command and it worked locally
=> Fix doc typo

pkg/networking/cilium/templater.go, pkg/networking/cilium/templater_test.go
The new verison of cilium added clustermesh to the helm chart
but we are not enabling that for eks-a clusters
Goes with https://github.com/aws/eks-anywhere-build-tooling/pull/802
=> Add clustermesh.enabled false to cilium template override

pkg/diagnostics/analyzers.go, pkg/diagnostics/collectors.go, pkg/diagnostics/collectors_test.go
I noticed the capc-system resources and logs were not being populated in the support bundle generated by eks-a so this PR attempts to mitigate that issue
E2E test failure resulted in desired logs and CRD's present in support-bundle. Unit test
=> Adding cloudstack support bundle components for debugging

release/pkg/git/git.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.8-bundle-release.yaml
Cloning the CLI repo from Codecommit sometimes fails on the following error:
```
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```
I was also able to reproduce this locally too on Git 2.34.1 and Git 2.36.1. It is possible that something changed on Codecommit's end but not sure.
Breaking apart the full clone into a shallow clone followed by fetch/pull seems to be a more robust approach.
=> Handle large repo clones in release process

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/networking/cilium/client.go, pkg/networking/cilium/client_test.go, pkg/networking/cilium/mocks/clients.go, pkg/networking/cilium/mocks/upgrader.go, pkg/networking/cilium/upgrader.go, pkg/networking/cilium/upgrader_test.go, pkg/networking/kindnetd/kindnetd.go, pkg/networking/kindnetd/kindnetd_test.go
#2061 
Follow up to #2057. We run the rollout restart cilium daemonset operation on the target cluster, across all providers during cluster upgrade if using cilium as CNI.
I add a `RunPostControlPlaneUpgradeSetup(ctx context.Context, cluster *types.Cluster) error` method in the networking interface in `cluster_manager` pkg. So that we can define CNI provider specific tasks that need to run after control plane vm is updated.
- unit tests
=> Rollout restart cilium during upgrade

release/pkg/assets_tinkerbell.go, release/pkg/test/testdata/main-bundle-release.yaml
We are currently tracking a commit for CAPT in build-tooling. This causes the bundle to have the commit hash as the version for CAPT which `clusterctl` doesn't like. This PR just hardcodes the CAPT version to `v0.1.0` to make `clusterctl` happy. 
This change should be reverted when [CAPT](https://github.com/tinkerbell/cluster-api-provider-tinkerbell/releases) releases a new version.
Ran `make unit-test` and verified the changes
=> Temporarily hardcode version for CAPT

pkg/networking/cilium/templater.go, pkg/networking/cilium/templater_test.go
Reverts aws/eks-anywhere#2160
The chart was fixed in 1.10.11 so we no longer need this override.
=> Revert "Add clustermesh.enabled false to cilium template override"

docs/content/en/docs/concepts/clusterworkflow.md, docs/content/en/docs/tasks/troubleshoot/packages.md, docs/content/en/docs/tasks/troubleshoot/supportbundle.md, docs/content/en/docs/tasks/troubleshoot/troubleshooting.md
Remove underscores from docs urls and add aliases to redirect to new location. Add description for curated packages as well.
=> Change doc urls to remove underescore

pkg/executables/govc.go, pkg/executables/govc_test.go
vSphere preflight validation can fail when validating template and tags.
Add retrier to govc SearchTemplate and GetTag.
Unit tests
=> Add retry for govc search template and get tag

pkg/providers/cloudstack/config/template-cp.yaml, pkg/providers/cloudstack/testdata/expected_results_main_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_main_no_machinetemplate_update_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_main_node_labels_cp.yaml
diskSetup and mount are not supported in etcdadm controller.
=> Remove diskSetup and mount for etcdadmcluster in cloudstack

pkg/providers/tinkerbell/tinkerbell.go
Remove `tinkerbellCertURLKey`, `tinkerbellGRPCAuthKey`, `tinkerbellPBnJGRPCAuthorityKey` and `tinkerbellHegelURLKey` from required env as they are no longer needed
=> Remove unused envs from required env for tinkerbell

pkg/dependencies/factory.go, pkg/providers/snow/entry.go, pkg/providers/snow/snow.go, pkg/providers/snow/snow_test.go
During upgrade, we do not need to check control plane IP uniqueness since the cluster with that IP exists during create.
=> Remove control plane ip uniqueness check for snow upgrade

pkg/providers/snow/snow.go, pkg/providers/snow/snow_test.go
When generating CAPI objects for snow upgrade, we need to pass in the cluster that has CAPI components.
After #1814 , we also need to update `GenerateCAPISpecForUpgrade` to use `eksaMgmtCluster` instead of the original managementCluster. So that we can fetch CAPI from the cluster holds these components.
- Unit tests
- Manual e2e
=> Fix snow upgrade flow

cmd/eksctl-anywhere/cmd/generatebundleconfig.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/diagnostics/analyzers.go, pkg/diagnostics/analyzers_test.go, pkg/diagnostics/diagnostic_bundle.go, pkg/diagnostics/diagnostic_bundle_test.go, pkg/diagnostics/factory.go, pkg/diagnostics/interfaces.go, pkg/diagnostics/interfaces/mocks/diagnostics.go, pkg/workflows/diagnostics.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go, pkg/workflows/upgrade_test.go
I was trying to debug a failure in the eks-a cloudstack e2e tests when I noticed that the bootstrap support bundle doesn't actually have logs for the capc controller, so I am blocked to continue debugging the e2e test failures.
This PR plumbs the spec through to the bundle generation logic so we can grab the provider specific logs and crds even on the bootstrap/management cluster
Tested by setting control plane ready timeout to 1 minute and observed capc logs were captured.
=> Adding provider specific collectors/analyzers to management cluster support bundle

pkg/clusterapi/identity.go, pkg/clusterapi/identity_test.go
#1574 
Fix API builder IAM kubeconfig indentation.
- Unit test
- Manual local e2e on snow
=> Fix AWS IAM auth format

pkg/providers/tinkerbell/tinkerbell.go
Nothing in the Tinkerbell stack requires the tinkerbell IP so its no longer an environment variable requirement (arguably it never should have been).
This was verified by inspecting the environment variables required by the `tink` repository using `grep -R --exclude-dir ".git" -I "TINKERBELL" .` No controllers/servers or anything requires the env variable or one synonymous with it/how it was being used in EKS-A.
=> Remove TINKERBELL_IP requirement from Tinkerbell provider

pkg/clients/kubernetes/scheme.go, pkg/clusterapi/apibuilder.go, pkg/clusterapi/apibuilder_test.go, pkg/clusterapi/name.go, pkg/clusterapi/name_test.go, pkg/providers/snow/apibuilder_test.go, pkg/providers/snow/fetch.go, pkg/providers/snow/objects.go, pkg/providers/snow/objects_test.go, pkg/providers/snow/snow_test.go, pkg/providers/snow/testdata/expected_results_main_md.yaml
#1574 
Run `eksctl anywhere create cluster -f snow-workload-1.yaml --kubeconfig mgmt.kubeconfig` and create a eks-a workload cluster on snow.
- Add snow api v1beta1 to kube runtime scheme
- Update `MachineDeployment` and `KubeConfigTemplate` name so that clusters under the same management cluster set have unique names
- Unit tests
- Created a workload cluster on snow
=> Add support for snow workload cluster creation

go.mod, go.sum
The go.mod was missing a set of imports that were being resolved at build time. This ensures the go.mod reflects our codebase appropriately and applies some patch version updates.
=> Fix go.mod and apply patch updates

cmd/eks-a-tool/cmd/cloudstackrmvms.go, cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, cmd/integration_test/cmd/cleanupcloudstack.go, internal/test/e2e/cleanup.go
One of the issues we have observed with the cloudstack e2e tests is the inability of the tests to clean up after itself, so it leaves all the VM's dangling after the test run. This change makes it so cloudstack can clean up after itself instead
`make e2e`, followed by
```
➜  eks-anywhere git:(cleanup-cloudstack-e2e) ✗ ./bin/test e2e cleanup cloudstack -n main-i -v 4
2022-05-23T11:06:13.341-0500	V4	Logger init completed	{"vlevel": 4}
2022-05-23T11:06:13.342-0500	V2	Pulling docker image	{"image": "public.ecr.aws/l0g8r8j6/eks-anywhere-cli-tools:v0.7.2-eks-a-v0.0.0-dev-build.1864"}
2022-05-23T11:06:19.421-0500	V3	Initializing long running container	{"name": "eksa_1653321973342049000", "image": …
```
=> Adding cleanup script for cloudstack vms for e2e test

pkg/dependencies/factory.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go
Remove now redundant fields from the Tinkerbell provider. These fields are redundant because of an overhaul in validation logic and a change in design.
=> Remove old flag fields from Tinkerbell provider

controllers/controllers/resource/template.go, pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/tinkerbell.go
Rename the `TinkerbellTemplateBuilder` construct to `TemplateBuilder` given its resides in the `tinkerbell` package. 
This aligns with the coding guidelines.
=> Rename TinkerbellTemplateBuilder to TemplateBuilder

pkg/providers/tinkerbell/cluster.go
As part of the Tinkerbell validation refactoring we isolated datacenter config validation. It was left out of the core set of assertions we run. This adds it ensuring we validate everything in there.
=> Validate Tinkerbell datacenter config on create

cmd/eksctl-anywhere/cmd/generatehardware.go, pkg/providers/tinkerbell/create.go
With the kubeification of the Tinkerbell stack we no longer need flags pecific to registering with a pre-deployed Tinkerbell stack.
This doesn't update anything to generate new `Hardware` types. That work will be on a separate PR.
=> Remove obsolete flags from generatehardware cmd

codecov.yml
This won't gate PRs based on the patch coverage but will still provide
coverage information.
=> Make codecov patch check optional

codecov.yml
This makes the project check just informational. It also adds a 0.5%
threshold to account for flakiness when measuring coverage.
=> Make codecov project optional

pkg/providers/tinkerbell/tinkerbell.go
Define the `TINKERBELL_IP` that gets propogated to CAPT installation code where its used as a value replacement so CAPT knows what address to specify in `Userdata` for contacting Hegel. 
This, in our context, is totally unnecessary. The only code that uses it is https://github.com/chrisdoherty4/cluster-api-provider-tinkerbell/blob/main/controllers/machine.go#L192 which renders a default template. Given we override the template the configuration is meaningless for us and only necessary to satisfy CAPT's [`Deployment` spec](https://github.com/chrisdoherty4/cluster-api-provider-tinkerbell/blob/main/config/manager/manager.yaml#L23).
=> Set TINKERBELL_IP when retrieving Tinkerbell provider environment

pkg/providers/tinkerbell/hardware/machine.go, pkg/providers/tinkerbell/hardware/validator.go, pkg/providers/tinkerbell/hardware/validator_test.go
Builds on #2268 
Add `Disk` to the Tinkerbell CSV so it can be consumed for `TinkerbellMachineTemplate` generation. The `Disk` will be validated in a subsequent PR where it will need to be consistent among hardware expected to be provisioned for control plane, external etcd or individual node groups.
The PR only adds CSV input data - it doesn't introduce any functional changes beyond that.
=> Add disk to Tinkerbell CSV input

cmd/eksctl-anywhere/cmd/createcluster.go, pkg/dependencies/factory.go, pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/hardware/catalogue_bmc.go, pkg/providers/tinkerbell/hardware/catalogue_hardware.go, pkg/providers/tinkerbell/hardware/catalogue_secret.go, pkg/providers/tinkerbell/hardware/csv.go, pkg/providers/tinkerbell/testdata/hardware.csv, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go, pkg/providers/tinkerbell/upgrade.go
Builds on #2266 
Wire the CSV into the Tinkerbell provider such that we can pass a CSV path to the `create` cmd and it is used by the Tinkerbell provider to catalogue hardware ready for submission post-boostrap cluster creation.
=> Wire hardware CSV into Tinkerbell provider on create

pkg/providers/tinkerbell/hardware/csv_test.go, pkg/providers/tinkerbell/hardware/machine.go, pkg/providers/tinkerbell/hardware/testdata/hardware.csv
Labels in the Tinkerbell hardware CSV required separation by comma which, for hopefully obvious reasons, doesn't work in CSVs (🤦). This changes to using pipe delimeted which is consistent with other multi-value fields.*Issue #, if available:*
=> Fix Tinkerbell hardware CSV labels format

cmd/eksctl-anywhere/cmd/createcluster.go
The hardware csv flag required for tinkerbell provider provisioning has some additional checks that used the old flag.
=> Fix create cluster hardware csv flag.

cmd/eksctl-anywhere/cmd/generateclusterconfig.go, pkg/api/v1alpha1/tinkerbelltemplateconfig.go, pkg/api/v1alpha1/tinkerbelltemplateconfig_test.go, pkg/providers/tinkerbell/template.go
We are hiding TinkerbellTemplateConfig from the tinkerbell cluster config file and defaulting all the values of the field to avoid human error. However, a user can pass their own TinkerbellTemplateConfig to override default template.
=> Hide/default TinkerbellTemplateConfig

pkg/providers/tinkerbell/hardware/catalogue_hardware.go
The title says it all. These fields additions correspond to missing fields relative to the JSON we used to generate.
=> Add missing hardware fields for Tinkerbell

internal/pkg/api/hardware.go, pkg/providers/tinkerbell/hardware/catalogue_hardware.go, pkg/providers/tinkerbell/hardware/csv.go, pkg/providers/tinkerbell/hardware/csv_test.go, pkg/providers/tinkerbell/hardware/machine.go, pkg/providers/tinkerbell/hardware/multi_test.go, pkg/providers/tinkerbell/hardware/testdata/hardware.csv, pkg/providers/tinkerbell/hardware/translate_test.go, pkg/providers/tinkerbell/hardware/validator.go, pkg/providers/tinkerbell/hardware/validator_test.go, pkg/providers/tinkerbell/hardware/yaml.go, pkg/providers/tinkerbell/hardware/yaml_test.go, test/e2e/forceflow_test.go, test/e2e/simpleflow_test.go, test/framework/cluster.go
Builds on #2288. This PR is composed of a single commit.
The ID and BMC Vendor fields are no longer required by the Kubeified stack. This PR strips them from the system.
=> Remove redundant Tinkerbell CSV fields

pkg/dependencies/factory.go, pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go
Delete flow does not require or take a hardware csv file. So the reading of CSV file should only be done for the create flow.
=> Hardware CSV file reading is only needed for create flow

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml
To help ensure the vsphere cluster is clean before kicking off a new test run as well as validating that the api server is accessible.
=> Adds vm cleanup to pre-build step for e2e tests

internal/pkg/api/cluster.go, test/framework/cluster.go
This is a temporary fix to avoid overloading the CI system.
It should be removed eventually or added explicitly to all tests.
=> Make all e2e tests default to 1:1:1 topology

internal/test/e2e/crypto.go, internal/test/e2e/fluxGit.go, internal/test/e2e/github.go, pkg/git/git.go, pkg/git/gitclient/gitclient.go, pkg/git/gitclient/gitclient_test.go, pkg/git/gogithub/gogithub.go, pkg/git/gogithub/gogithub_test.go, pkg/git/gogithub/mocks/client.go, pkg/git/mocks/git.go, pkg/git/providers/github/github.go, pkg/git/providers/github/mocks/github.go, test/framework/flux.go
The Git Flux tests have been using the same git repository, pushing and pulling their flux configs and cluster configs at the same time. These concurrent git actions have caused frequent failures in the validations. Specifically, multiple simultaneous 'local' commits by validation code led to divergent histories among the clones on the test instances, causing the validation code to fail when attempting to push and pull from the remote and encountering non-fast-forward updates. This was not resolved by setting the default behavior to `rebase`, and it seems that the `pull` behavior of `go-git`, the library we are using for git actions, can't handle non-fast-forward updates even when the given branch is configured to rebase instead of merge. …
=> Git Flux tests create their own repository for use during test

release/pkg/assets_etcdadm_bootstrap.go, release/pkg/assets_etcdadm_controller.go, release/pkg/generate_spec_test.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.9-bundle-release.yaml
Backporting #2309 to release-0.9 branch.
=> Update etcdadm controller references to use AWS org

cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/deletecluster.go, cmd/eksctl-anywhere/cmd/generatebundleconfig.go, cmd/eksctl-anywhere/cmd/supportbundle.go, cmd/eksctl-anywhere/cmd/upgradecluster.go, cmd/eksctl-anywhere/cmd/upgradeplancluster.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go
For GA, --setup-tinkerbell is enforced as we don't support additional
cluster creation. We anticipate being able to detect Tinkerbell Enabled
Management Clusters and suspect this won't ever be required. If it is,
we can add it back in which is easier than removing it.
--skip-power-actions is superfluous as power actions are implied when a
user provides BMC configuration in the hardware CSV.
=> Remove --setup-tinkerbell and --skip-power-actions

pkg/providers/tinkerbell/hardware/catalogue_hardware.go, pkg/providers/tinkerbell/stack/stack.go, pkg/providers/tinkerbell/stack/stack_test.go
This PR updates the cli to pull the Hook images from the URIs listed in the bundle instead of being hardcoded.
It also bumps up the lease duration for IPs handed out by boots to 1 month
Created the cluster with the hook from bundle
=> Pull hook from the bundle

cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/generatehardware.go, cmd/eksctl-anywhere/cmd/tinkerbell.go, cmd/eksctl-anywhere/cmd/upgradecluster.go, cmd/eksctl-anywhere/cmd/upgradeplancluster.go
The hardware CSV flag is necessary for upgrade in-case the user wishes to provide the additional Hardware per node group (including control plane). The flag is optional as hardware may already be registered with the cluster that satisfies the upgrade requirements.
A following PR will leverage the input CSV by validating it and cataloging the additional hardware along with existing hardware so we can validate sufficient hardware is available.
=> Add Hardware flag to upgrade cmd

cmd/eksctl-anywhere/cmd/upgradecluster.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/docker/docker.go, pkg/providers/mocks/providers.go, pkg/providers/provider.go, pkg/providers/snow/snow.go, pkg/providers/tinkerbell/upgrade.go, pkg/providers/vsphere/vsphere.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
* Install tinkerbell stack on bootstrap cluster for upgrade flow
* Delete local boots container off the bootstrap machine for
upgrade flow
* Make hardware CSV file an optional parameter for upgrade
* Read hardware CSV file if provided for upgrade
TODO: Input validations for upgrade
=> Fix up cluster upgrade for kubefied tinkerbell stack changes

internal/pkg/ssm/command.go
Increase ssm execution timeout to solve potential timeout issues in our tests
=> Increase SSM execution timeout for e2e tests

go.mod, go.sum, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/providers/tinkerbell/delete.go, pkg/providers/tinkerbell/mocks/client.go, pkg/providers/tinkerbell/tinkerbell.go
With the new Kubified Tinkerbell stack eks-a no longer uses the older CAPT CRDs. 
Removing old logic from the delete cluster workflow.
=> Removing old tinkerbell delete workflow code

pkg/providers/tinkerbell/stack/stack.go, pkg/providers/tinkerbell/stack/stack_test.go
Use tinkerbell helm chart from bundle instead of using a hardcoded one
=> Use helm chart from bundle in Tinkerbell

pkg/providers/tinkerbell/hardware/catalogue_hardware.go
Set hardware DHCP lease duration to 1 month temporarily while we figure out how to set static IPs on the nodes
=> Set hardware lease time to 1 month

internal/test/e2e/fluxGit.go
getting 404s when attempting to add a deploy key to the newly created repositories in the Github tests; I ran into this on my local one time out of dozens of tests; I'm wondering if this is related to eventual consistency int he GitHub API, want to try a sleep to see if it influences the problem.
=> Quick sleep in git setup

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/executables/testdata/kubectl_tinkerbellhardware.json, pkg/providers/tinkerbell/mocks/client.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/upgrade.go
When upgrading a Tinkerbell Enabled Management Cluster we need to ensure there is sufficient hardware. We allow applying additional hardware as well as leveraging existing unprovisioned hardware during upgrade execution. This PR populates the in-memory catalogue using CSV data and existing Hardware resource data, retrieved from the cluster, where it can be validated for the desired operation (scale-up, upgrade, etc). 
A future PR will introduce the assertions given they're different dependent on what kind of upgrade activity the user is invoking.
=> Read Hardware CSV and existing cluster Hardware on Tinkerbell Enabled Management Cluster upgrade

pkg/executables/docker.go, pkg/executables/docker_test.go, pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/stack/mocks/stack.go, pkg/providers/tinkerbell/stack/stack.go, pkg/providers/tinkerbell/stack/stack_test.go, pkg/providers/tinkerbell/tinkerbell_test.go
This PR adds a validation to check if boots is already running as a docker container on the local machine so the cli doesn't error out later on.
The PR to remove the local boots using the `force-cleanup` option is coming as part of a follow-up PR
=> Add validation to check if boots is already running on docker

pkg/task/mocks/task.go, pkg/task/task.go, pkg/task/task_test.go, pkg/workflows/create.go, pkg/workflows/delete.go, pkg/workflows/diagnostics.go, pkg/workflows/upgrade.go
This PR adds a skeleton for the methods needed to rerun CLI commands. The `Restore()` method will restore the necessary information from the completed tasks & return the next task. The `Checkpoint()` method will return the information needed to save to the checkpoint file for that task. 
=> Skeleton for methods to rerun CLI commands

release/cmd/release.go, release/pkg/generate_spec.go, release/pkg/generate_spec_test.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.9-bundle-release.yaml
Part of implementing https://github.com/aws/eks-anywhere/pull/2353 and required for https://github.com/aws/eks-anywhere/pull/2371 to work
Until now, all `Bundles` were being generated with an empty name.
Unit tests
=> Add name to Bundles objects during release

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml, pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/api/v1alpha1/cluster_types.go, pkg/clusterapi/extraargs.go, pkg/clusterapi/extraargs_test.go, pkg/constants/constants.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/docker/docker.go, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/testdata/cluster_main.yaml, pkg/providers/vsphere/vsphere.go, pkg/validations/createvalidations/preflightvalidations.go
#488 
Currently we default the ipv4 node cidr mask size to 24, which can restrict some users from spinning up lesser number of pods on each node. Defaulting to 24 gives the cluster 256 IPs to use for nodes.
In this PR we expose that flag in our eksa config for users to set. This needs to be tied in with the pod CIDR mask as well as that value decides the number of IPs that are available for the entire network to use.
This is how the new clusterNetwork config would look like:
```
clusterNetwork:
nodes:
cidrMaskSize: 28
```
This field is an optional field, and would not be generated using `generate clusterconfig` …
=> Support node CIDR mask config

pkg/providers/tinkerbell/tinkerbell.go
Baremetal nodes generally take longer to provision than the VMs which sometimes cause the kubeadm join tokens to surpass their TTL and expire.
This PR sets `KUBEADM_BOOTSTRAP_TOKEN_TTL` to 120m for Tinkerbell provider to give nodes enough time to provision and join the cluster.
=> Set `KUBEADM_BOOTSTRAP_TOKEN_TTL` to 120m for Tinkerbell provider

pkg/providers/tinkerbell/hardware/catalogue_hardware.go
Set boots dhcp lease duration to the max allowed value.
This value only applies for BottleRocket nodes as the IPs are set statically on Ubuntu nodes.
This is a temporary solution until BottleRocket support static IPs.
=> Set boots lease duration to max

pkg/providers/tinkerbell/hardware/csv_test.go, pkg/providers/tinkerbell/hardware/testdata/hardware_no_bmc_headers.csv, pkg/providers/tinkerbell/hardware/yaml_test.go
When reading hardware some users don't wish to specify any BMC
information for any hardware. This renders the BMC columns in the
hardware CSV redundant. This test ensures users can specify a CSV
without any BMC columns simplifying their CSV.
=> Add missing BMC headers test

cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/deletecluster.go, cmd/eksctl-anywhere/cmd/generatebundleconfig.go, cmd/eksctl-anywhere/cmd/supportbundle.go, cmd/eksctl-anywhere/cmd/upgradecluster.go, cmd/eksctl-anywhere/cmd/upgradeplancluster.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/providers/tinkerbell/tinkerbell.go
Add option to override the local tinkerbell bootstrap ip.
This is needed for cases where tink needs to run on a different interface than the default interface ip that we infer.
Equinix requested this for their workflow. Also, testing using dhcp relay over vpn required this.
=> add option to override the local tinkerbell IP in the bootstrap cluster

pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/hardware/csv.go, pkg/providers/tinkerbell/hardware/csv_test.go, pkg/providers/tinkerbell/hardware/normalize.go, pkg/providers/tinkerbell/hardware/normalize_test.go, pkg/providers/tinkerbell/upgrade.go
When reading hardware data for Tinkerbell we need to apply normalizations so we can perform comparison operations. MAC Addresses are a culprit for incorrect comparisons because comparators don't take into consideration case insensitivty of a MAC.
We're lower-casing MAC as it seems to be lower-case more often than not.
This won't protect us against all failures. A real fix would be to edit all locations within Tinkerbell that perform a MAC comparison to be case-insensitive.
=> Add normalizations and lower case MAC address

go.mod, pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/stack/stack.go, pkg/providers/tinkerbell/stack/stack_test.go, pkg/providers/tinkerbell/tinkerbell_test.go
`hostPort` is needed for `hegel` and `tink-server` on local Kind cluster but it's not needed when the Tinkerbell stack on the workload cluster. This PR enables `hostPort` for tink services only for bootstrap phase.
These are the helm chart values that are used to control hostPort for deployments https://github.com/aws/eks-anywhere-build-tooling/blob/main/projects/tinkerbell/tinkerbell-chart/chart/values.yaml#L32-L34
=> Enable hostPort for tink services only on bootstrap

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/executables/testdata/kubectl_machine_deployments_provisioned.json, pkg/executables/testdata/kubectl_machine_deployments_unavailable.json, pkg/executables/testdata/kubectl_machine_deployments_unready.json
Currently it waits zero seconds between retries when waiting for all machine deployment replicas are ready. This PR introduces a wait time adaptive to unready replicas between retries. 
=> Wait adaptive duration per unready replicas between retries

pkg/providers/tinkerbell/hardware/csv.go, pkg/providers/tinkerbell/hardware/csv_test.go, pkg/providers/tinkerbell/hardware/machine.go
Previously users would receive an error about missing data when an entire column is missing. This improves the error to explicitly call out a missing column.
=> Improve error when hardware CSV has missing required columns

pkg/cluster/fetch.go, pkg/cluster/fetch_test.go, pkg/cluster/spec.go, pkg/cluster/spec_test.go, pkg/cluster/testdata/cluster_tinkerbell_1_19.yaml
*Issue #, if available:* part of https://github.com/aws/eks-anywhere/issues/1090 and https://github.com/aws/eks-anywhere/issues/1109
Builds (fully) a `cluster.Spec` using a kubernetes client:
* Builds the `cluster.Config` with the default builder
* Retrieves Bundles and the eksd release from the cluster
* Some data massaging to complete the Spec
Please, look at comments in PR for more localized explanations.
=> Add logic to build cluster.Spec from cluster

pkg/clusterapi/apibuilder.go, pkg/clusterapi/apibuilder_test.go, pkg/clusterapi/identity_test.go
#1574 
Add labels support to KubeadmControlPlane and KubeadmConfigTemplate.
Unit tests
=> Add labels support in apibuilder

pkg/executables/config/deploy-opts.json, pkg/executables/govc.go, pkg/executables/govc_test.go, pkg/providers/vsphere/defaults.go, pkg/providers/vsphere/internal/templates/factory.go, pkg/providers/vsphere/internal/templates/factory_test.go, pkg/providers/vsphere/internal/templates/mocks/govc.go, pkg/providers/vsphere/mocks/client.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
Provide a network when deploying VM from a template in the content library.
If the network is not provided, vSphere will pick some network and try to deploy the vm on that network which can have unintended consequences.
Tested and verified with both bottlerocket and ubuntu
=> Specify the network when deploying the VM from content library

internal/pkg/api/tinkerbell.go, pkg/api/v1alpha1/tinkerbellmachineconfig.go, pkg/api/v1alpha1/tinkerbellmachineconfig_types.go, pkg/executables/kubectl_test.go
Currently, the generate command prints a `TinkerbellMachineConfig` with an empty `templateRef` section. This PR makes the `templateRef` a pointer so it doesn't get placed in the generated config by default 
Before:
```yaml
kind: TinkerbellMachineConfig
metadata:
name: tdsfds-cp
spec:
hardwareSelector: {}
osFamily: ubuntu
templateRef: {}
users:
- name: ec2-user
sshAuthorizedKeys:
- ssh-rsa AAAA...
```
After:
```yaml
kind: TinkerbellMachineConfig
metadata:
name: tdsfds
spec:
hardwareSelector: {}
osFamily: ubuntu
users:
- name: ec2-user
sshAuthorizedKeys:
- ssh-rsa AAAA...
``` …
=> Don't include templateRef in TinkerbellMachineConfig on generate

pkg/api/v1alpha1/tinkerbelltemplateconfig_defaults.go, pkg/api/v1alpha1/tinkerbelltemplateconfig_defaults_test.go
Added nvme disk support for Tinkerbell template config. 
=> Added nvme disk support for Tinkerbell template config

internal/test/e2e/setup.go
The docker e2e tests are failing because of kubelet errors regarding too many open files.
It is a known issue and based on kind documentation [here](https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files), this pr fixes the issue.
=> Increase fs inotify resources for e2e tests

release/.gitignore, release/pkg/assets_capa.go, release/pkg/assets_capas.go, release/pkg/assets_capc.go, release/pkg/assets_capd.go, release/pkg/assets_capi.go, release/pkg/assets_certmanager.go, release/pkg/assets_eksa_tools.go, release/pkg/assets_etcdadm_bootstrap.go, release/pkg/assets_etcdadm_controller.go, release/pkg/assets_kindnetd.go, release/pkg/assets_package_controller.go, release/pkg/assets_tinkerbell.go, release/pkg/assets_vsphere.go, release/pkg/generate_spec_test.go, release/pkg/prepare_release.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/versions.go
This PR removes the step of downloading and renaming artifacts from the release-tooling unit tests. This step was being run since the test code was common with the main release code that ran download/rename/upload artifacts. But we don't need to do this since it's just unit tests.
=> Avoid downloading artifacts when running release tooling unit tests

Makefile, release/pkg/file_reader.go, release/pkg/test/testdata/main-bundle-release.yaml
* Adding linker flags to build a static, stripped executable for the EKS-A CLI.
* Updating golden files
Fixes #2232.
=> Add flags to build static binary for EKS-A CLI

release/Makefile, release/pkg/assets_eksd.go, release/pkg/file_reader.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.9-bundle-release.yaml
aws/eks-anywhere-build-tooling#946 added Raw image downloads for Bottlerocket. This PR adds them to the bundle manifest for use in cluster creation workflows.
=> Add Bottlerocket Raw images to bundle

pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_multiple_node_groups.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_external_etcd.yaml, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go, pkg/providers/tinkerbell/upgrade.go
For GA, bare metal doesn't support external etcd. This change explicitly rejects invocations that use an external etcd config.
=> Reject cluster operations with external etcd for bare metal

pkg/api/v1alpha1/tinkerbellmachineconfig_types.go, pkg/providers/tinkerbell/assert.go, pkg/providers/tinkerbell/assert_test.go, pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/validate.go
We found an issue in CAPT where even the most basic of cases can result in clusters not being provisioned. It stems from the fact `TinkerbellMachines` are reconciled in a non-deterministic order and any hardware selectable by more than 1 selector could cause another selector to be left without hardware. 
This change introduces a new constraint that ensures hardware is mapped to a single selector preventing any subsets or intersections between selectors and hardware. In doing so, we ensure deterministic reconciliation in CAPT avoiding accidental selection of hardware required by other selectors.
Additionally, it replaces a total hardware required constraint with one that accounts for selectors being the same across MachineConfigs. This ensures we have sufficient hardware to meet the …
=> Correct bare metal hardware validations on create

controllers/controllers/clients/kubernetes.go, controllers/controllers/clients/kubernetes_test.go, pkg/clients/kubernetes/kubeconfig.go, pkg/clients/kubernetes/mocks/kubeconfig.go, pkg/cluster/client_builder.go, pkg/cluster/mocks/client_builder.go, pkg/clusterapi/fetch.go, pkg/clusterapi/mocks/fetch.go
*Issue #, if available:* part of #1090
The controller runtime client implementation takes client.Client as an
input, which is a superset of runtime.Object. To make things easier, we
just make that a requirement in our kube client interface. To avoid
polluting our interface with something defined in controller runtime,
we just create a our own kubernetes.Object interface.
Unit tests
=> Add kubernetes.Client controller implementation

internal/test/e2e/fluxGit.go, pkg/git/gogithub/gogithub.go
additional logging to assist in debuging GitFlux test failures
=> add additional logging for debugging failing gitflux tests

codecov.yml
=> Ignore E2E framework code in codecov

docs/content/en/docs/reference/changelog.md, pkg/crypto/validator.go, pkg/crypto/validator_test.go, pkg/validations/cluster.go, pkg/validations/mocks/tls.go, pkg/validations/tls.go
https://github.com/aws/eks-anywhere/issues/1857
As described in the issue above, we weren't checking for the validity of the cert if the caCert passed in is not the self-signed server cert instead. This allows for checking the validity of the cert against the server itself instead of just checking for whether the cert is valid without actually making a call to the server. Also modified the unit tests to spin up a test http server to test the cert setup.
Ran against ci registry mirror configuration and another public one
=> Validate server cert against ca cert for registry mirror

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, test/e2e/curated_packages_test.go, test/framework/cluster.go, test/framework/curatedpackages.go
The first of what will eventually be many end-to-end tests for curated
packages. This test will:
* Bring up a cluster
* Install the curated packages controller (via helm)
* Install the hello-eks-anywhere package (via CLI)
* Forward a port to the hello-eks-anywhere service
* Verify the function of the hello-eks-anywhere package
* Tear down the cluster
There's plenty of room for future work, but some highlights include:
* Modify the Executable framework to allow the usage of exec.Command.Start()
and reading Stdout and Stderr before the process exits.
* Find a better way (than polling) to determine when a service is ready.
https://github.com/aws/eks-anywhere-packages/issues/96 …
=> Packages: First end-to-end test

cmd/integration_test/build/buildspecs/conformance-eks-a-cli.yml, cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, test/framework/vsphere.go
This is to account for govc envvars being needed by test runners and vsphere tests. To account for this we name them differently on code build box and override to govc vars at time of vm creation
=> fix vsphere env var race conditions during e2e tests

internal/pkg/vsphere/deploy.go, internal/test/e2e/testRunner.go, pkg/executables/builder.go, pkg/executables/govc.go
This is required to support targeting 2 different vpshere from the same machine using govc executable int the bundle. With this change we now have option to pass custom env map directly to container env rather than it always picking the envs from the cli environment.
=> enable option to override govc envmap that gets passed to container

controllers/controllers/cluster_controller.go, controllers/controllers/cluster_controller_test.go, controllers/controllers/cluster_controller_test_test.go, controllers/controllers/main_test.go, controllers/controllers/utils/handlerutil/childobjects.go, controllers/controllers/utils/handlerutil/childobjects_test.go, controllers/main.go, internal/test/envtest/environment.go, pkg/cluster/config.go, pkg/cluster/config_test.go
*Issue #, if available:* part of #1090
On every reconciliation loop, check if the cluster child objects contain
an owner reference linked to that cluster. If they don't, add it and
update them.
When watching child objects, use their OwnerReferences to enqueue
reconcile requests for Clusters.
Unit and integration tests
=> Watch child objects with OwnerReferences

pkg/api/v1alpha1/tinkerbelltemplateconfig.go, pkg/api/v1alpha1/tinkerbelltemplateconfig_defaults.go, pkg/api/v1alpha1/tinkerbelltemplateconfig_defaults_test.go, pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/stack/mocks/stack.go, pkg/providers/tinkerbell/stack/stack.go, pkg/providers/tinkerbell/stack/stack_test.go, pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/tinkerbell_test.go
Expose tinkerbell services, hegel and tink-server, using a LoadBalancer to allow the clusters to scale up. 
A LoadBalancer is required because when the new nodes come up, they need to contact tink-server and hegel to provision, which requires these 2 services to be externally accessible.
This also required a change to the tinkerbell helm chart https://github.com/aws/eks-anywhere-build-tooling/pull/957
which will need to merge before this PR
Created baremetal clusters and verified that the tinkerbell services were exposed properly
=> Expose tinkerbell services on workload cluster using an lb

controllers/controllers/utils/handlerutil/capiobjects.go, controllers/controllers/utils/handlerutil/capiobjects_test.go, pkg/clusterapi/apibuilder.go, pkg/clusterapi/apibuilder_test.go, pkg/providers/snow/apibuilder_test.go, pkg/providers/snow/testdata/expected_results_main_cp.yaml, pkg/providers/snow/testdata/expected_results_main_md.yaml
*Issue #, if available:* part of #1090
Using labels in CAPI objects to reference the parent eksa Cluster by its
name and namespace.
Unit tests
=> Implement backreferences from CAPI to EKSA cluster

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, test/e2e/curated_packages_test.go, test/framework/cluster.go, test/framework/curatedpackages.go
**Cherry picking from main into release-0.10**
The first of what will eventually be many end-to-end tests for curated
packages. This test will:
* Bring up a cluster
* Install the curated packages controller (via helm)
* Install the hello-eks-anywhere package (via CLI)
* Forward a port to the hello-eks-anywhere service
* Verify the function of the hello-eks-anywhere package
* Tear down the cluster
There's plenty of room for future work, but some highlights include:
* Modify the Executable framework to allow the usage of exec.Command.Start()
and reading Stdout and Stderr before the process exits.
* Find a better way (than polling) to determine when a service is ready.
https://github.com/aws/eks-anywhere-packages/issues/96
*Testing (if …
=> Packages: First end-to-end test (#2432)

internal/test/e2e/fluxGit.go
=> Avoid ":" in github repository names for E2E tests

pkg/dependencies/factory.go, pkg/providers/tinkerbell/hardware/catalogue_hardware.go, pkg/providers/tinkerbell/hardware/catalogue_hardware_test.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go
The disk extractor is used to extract disks from hardware so it can be
used to populate tinkerbell actions. The matching algorithm prevented
matches on hardware with labels other than those specified on the
selector which is inconsistent with how other code matches machines to
selectors.
The change uses the same matching function as all other parts of the
code base.
=> Fix tinkerbell disk extractor

release/api/v1alpha1/artifacts.go, release/api/v1alpha1/artifacts_test.go, release/pkg/test/testdata/main-bundle-release.yaml
It seems like the production Bundles is being generated without the Snow
sub bundle. This includes the images for kubevip and the manager. When
running "import images", the code retrieves the list of all images from
the Bundles and it fails because these two have an empty URI. This patch
avoids adding the snow images ot the list of the URI is empty.
We should remove this once the Bundles is fixed and the Snow components
are populated.
Unit tests
=> Avoid processing Snow images if the URI is empty

Makefile
Referencing branch name release-0.10 in the Makefile
=> Referencing branch name release-0.10

config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, config/manifest/eksa-components.yaml, internal/test/testdata/bundles.yaml, internal/test/testdata/bundles_template.yaml, pkg/executables/clusterctl_test.go, pkg/executables/testdata/clusterctl_expected.yaml, release/api/v1alpha1/bundle_types.go, release/api/v1alpha1/zz_generated.deepcopy.go, release/config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, release/pkg/assets_certmanager.go, release/pkg/generate_spec.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.10-bundle-release.yaml
Updating cert manager org from `jetstack` to `cert-manager`. 
Also updated unit tests and bundle.
=> Cert manager org update

release/pkg/assets_cli.go
Instead of hardcoding the download URL for the CLI tarball to latest, we should use the branch name to determine which URL to use.
=> Use branch name to construct S3 URI for CLI tarball

pkg/api/v1alpha1/tinkerbellmachineconfig.go
Make Bottlerocket default OS for Tinkerbell.
=> Tinkerbell - OSFamily defaulted to bottlerocket

pkg/api/v1alpha1/cloudstackmachineconfig_types.go, test/e2e/upgrade_from_latest_test.go
In order to ensure our users are able to smoothly upgrade between eks-a versions, we need a test running automatically in our pipeline to make sure the changes we're making preserve backwards compatibility. Identified one bug as a result of this issue where some optional field was not parseable.
Testing locally against CI environment
=> Fixing backwards compatibility bug and adding new e2e test

release/triggers/snsAnnounce.json
Adding a dummy sns trigger file. This file should be modified to house the proper announcement after cutting the release on the release branch. Any updates to this file on main branch will not trigger an sns announcement.
=> SNS trigger file

docs/content/en/docs/reference/clusterspec/baremetal.md
This PR creates the Bare metal configuration reference page, used to build bare metal EKS-A clusters.
=> Configuration reference doc for Bare Metal

go.mod, go.sum, pkg/providers/vsphere/config/secret.yaml, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
Closes: https://github.com/aws/eks-anywhere/issues/1639
Base 64 encode the VSphere username and password secret data in the VSphere credentials secret.
This will ensure that passwords containing special characters like escape characters and line seperators are properly accepted by the API server at secret create time, as well as adding another small layer of obfuscation. 
create/upgrade/delete vsphere cluster
=> Base64 encode VSphere secrets

internal/test/e2e/tinkerbell.go, test/framework/cluster.go, test/framework/tinkerbell.go
During CI multiple Tinkerbell tests run from the same test runner. If one of the tests fail, the subsequent tests also fail since kind cluster and boots container from previous test are still running and cause issue. This cleans up kind and docker environment after each tinkerbell test that runs during CI build.
=> cleanup tinkerbell test environment between test runs

cmd/eksctl-anywhere/cmd/common.go, cmd/eksctl-anywhere/cmd/downloadimages.go, cmd/eksctl-anywhere/cmd/import_images.go, cmd/eksctl-anywhere/cmd/importimages.go, cmd/eksctl-anywhere/cmd/installpackagecontroller.go, controllers/controllers/clusters/vsphere.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/dependencies/testdata/cluster_tinkerbell.yaml, pkg/executables/helm.go, pkg/executables/helm_test.go, test/framework/executables.go
Currently, helm performs all actions using `--insecure-skip-tls-verify`
This PR makes this flag optional and users have to specify `WithInsecure()` option when creating Helm to add this flag to the helm calls.
Right now, all the packages that were using insecure will continue to use them. This flag is currently only being disabled for the `tinkerbell` provider.
=> Add option in helm to operate with TLS

cmd/eksctl-anywhere/cmd/generateclusterconfig.go
Adding Tinkerbell to help
*Testing:*
```code
./bin/eksctl-anywhere generate clusterconfig -h 
This command is used to generate a cluster config yaml for the create cluster command
Usage:
anywhere generate clusterconfig <cluster-name> (max 80 chars) [flags]
Flags:
-h, --help              help for clusterconfig
-p, --provider string   Provider to use (vsphere or tinkerbell or docker)
Global Flags:
-v, --verbosity int   Set the log level verbosity
```
=> Adding tinkerbell provider to help

docs/content/en/docs/reference/baremetal/bare-custom-hookos.md, docs/content/en/docs/reference/baremetal/bare-custom-ova.md
The procedure in this PR describes how to create a custom HookOS to use with EKS Anywhere Bare Metal. It also removes the file which was scheduled to hold the Custom OS procedure. But that procedure will be added at a later date.
=> Create docs for building your own HookOS

docs/content/en/docs/reference/packagespec/metallb/_index.md
Upstream's description uses the term "bare metal" which might be
confusing to EKS-A customers since we currently consider "bare metal" as
being non-virtualized environment.
=> Modify description of MetalLB to avoid confusion

docs/content/en/docs/tasks/cluster/cluster-rebootnode.md
Added a warning about the problem of rebooting a Bottlerocket node in a Bare Metal cluster while it is running the boots service.
=> Added warning about rebooting Bottlerocket nodes

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/api/v1alpha1/testdata/cluster_valid_domainname_proxy.yaml
This PR was split off from https://github.com/aws/eks-anywhere/pull/2598 to decouple two separate development efforts.
This PR expands the current implementation of the proxy server settings to support passing in domain names as well as IP addresses.
Ran TestCloudStackKubernetes121RedhatProxyConfig locally against CI Cloudstack environment with proxy server's hostname instead of static IP
=> Adding validation and support for hostnames for proxy server

docs/content/en/docs/tasks/cluster/cluster-scale.md, docs/content/en/docs/tasks/cluster/cluster-scale/_index.md, docs/content/en/docs/tasks/cluster/cluster-scale/baremetal-scale.md, docs/content/en/docs/tasks/cluster/cluster-scale/vsphere-scale.md
Added a new section on scaling worker and control plane nodes for EKS Anywhere bare metal clusters to the cluster scaling task docs. I'm not sure of the implication of bare metal on the other sections of that doc, so further research is needed.
=> Added bare metal info to cluster scaling docs

pkg/diagnostics/collector_types.go, pkg/diagnostics/collectors.go, pkg/diagnostics/collectors_test.go
Leverage the `podSpec` field in the latest version of troubleshoot to be able to schedule the collector pods with host networking and tolerations. This will allow us to properly retrieve the support bundle in the workload cluster, especially for the changes described here: https://github.com/aws/eks-anywhere/pull/2431
The other option is to avoid appending these CRD collectors by checking for the existence of those resources on the cluster before actually trying to pull them. However, this is a much simpler change than doing that refactoring, so decided on going forward with this approach.
unit testing and testing generating the support bundle when networking fails to install …
=> Enable host networking and tolerations for collector pods

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go
When upgrading a cluster sometimes, it appears to be when the machine is stressed and the bootstrap cluster is running slow, control plane nodes are not upgraded and etcd nodes are left behind.  This adds a similar fix to https://github.com/aws/eks-anywhere/pull/1542 for external etcd nodes to ensure the cli is waiting for it to upgrade before moving on.
Should fix https://github.com/aws/eks-anywhere/issues/2636
Note: @jiayiwang7 is going to finish this by adding tests.
=> Adds wait for not ready for external etcd before upgrade

docs/content/en/docs/concepts/eksafeatures.md
Added "Metallb" to the loadbalancer line in the EKS/EKS-A comparison table. This caused the EKS loadbalencer information to go into the proper column.
=> Fixed loadbalancer info in comparison table

Makefile
Update Makefile for M1 mac user.
*Issue
When you run `make` on the eks-anywhere repository on a Mac with M1 chip, you may see the error `unable to find a version that was supported for platform darwin/arm64`. It will cause the issue that binaries cannot be compiled. 
change the line on Makefile 
`unit-test: KUBEBUILDER_ASSETS ?= $(shell $(SETUP_ENVTEST) use --use-env -p path $(KUBEBUILDER_ENVTEST_KUBERNETES_VERSION))`
to 
`unit-test: KUBEBUILDER_ASSETS ?= $(shell $(SETUP_ENVTEST) use --use-env -p path --arch amd64 $(KUBEBUILDER_ENVTEST_KUBERNETES_VERSION))
`
=> Update Makefile for M1 mac user

internal/test/e2e/run.go
Re-enabling tinkerbell e2e tests on main branch.
=> Enabling Tinkerbell e2e tests on main branch

docs/content/en/docs/reference/artifacts.md
The current directory will always exist, so these docs do not work
Closes: https://github.com/aws/eks-anywhere/issues/2639
=> Fix tuftool command docs

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/types/resources.go
*Issue #, if available:* #2665
This PR adds a validation step prior to executing a clusterctl move to make sure the workload clusters are ready for a self-managed cluster. This PR does the same thing to https://github.com/aws/eks-anywhere/pull/2668 but it uses `kubectl wait` instead of polling
Manual testing for upgrading two 1-1-1 clusters. It waited for the workload cluster's rolling upgrade to be done before moving.
```
2022-07-07T11:05:16.877-0500    V3      Waiting for all clusters to be ready before move
2022-07-07T11:05:16.877-0500    V6      Executing command       {"cmd": "/usr/local/bin/docker exec -i eksa_1657209528309481000 kubectl get clusters.cluster.x-k8s.io -o json --kubeconfig wk-mgmt/wk-mgmt-eks-a-cluster.kubeconfig …
```
=> Adding check before move to make sure workload clusters are ready using kubectl wait

config/manifest/eksa-components.yaml, config/webhook/manifests.yaml, pkg/api/v1alpha1/snowmachineconfig_webhook.go, pkg/api/v1alpha1/snowmachineconfig_webhook_test.go
#2669 
Validating the Snow Machine Config via the validating webhook.
- Create docker cluster with tilt and attach a snow machine config on the cluster with specific values set. Check once attached if the values are validated.
- Unit tests
=> Snow machine config validation webhook for static validations

pkg/providers/snow/mocks/client.go, pkg/providers/snow/snow.go, pkg/providers/snow/snow_test.go
#1106 
Preflight validation for snow machine config fields immutability.
Unit tests
=> Add sow machine config immutable field validation

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/docker/docker.go, pkg/providers/mocks/providers.go, pkg/providers/provider.go, pkg/providers/snow/snow.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/vsphere/vsphere.go
currently MachineDeploymentsToDelete method is within each provider code, but the logic is provider agnostic.
Moved the code to cluster manager. Use single method to generate machinedeployment name.
Unit tests
=> Move machineDeploymentsToDelete out of provider code

pkg/clusterapi/machine_health_check.go, pkg/clusterapi/machine_health_check_test.go, pkg/clusterapi/name.go, pkg/clusterapi/name_test.go, pkg/clustermanager/cluster_manager.go, pkg/executables/builder.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/docker/docker.go, pkg/providers/mocks/providers.go, pkg/providers/provider.go, pkg/providers/snow/apibuilder.go, pkg/providers/snow/objects.go, pkg/providers/snow/snow.go, pkg/providers/snow/snow_test.go, pkg/providers/snow/testdata/expected_results_machine_health_check.yaml, pkg/providers/tinkerbell/template.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go, pkg/workflows/create.go, pkg/workflows/create_test.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go
#1105 
Add machine health check in api builder, for both control plane and worker machines. Currently it's only used in Snow provider.
While adding this feature to snow, I realize all the other providers only have machine health check for single worker node group. We should add multiple worker node group support for vsphere, cloudstack, docker, and tinkerbell machine health check. Created issue #2722 
Unit tests
=> Add machine health check for snow

pkg/diagnostics/analyzers.go, pkg/diagnostics/analyzers_test.go
capi Kubeadm Control Plane System Log Analyzers cannot locate the log file due to the wrong file path. Output of the analyzer showed `message: No matching files`.
Fix the bug by giving the analyzer the full manager pod log path and removing the collector name which should not be partial of it.
- run `make` to complie binaries
- then run `./bin/eksctl-anywhere generate support-bundle -f myCluster.yaml`
- the output of that analyzer shows "message: API server pods launched correctly" instead of "No matching files". 
- Details show below: 
`- URI: ""
isFail: false
isPass: true
isWarn: false
message: API server pods launched correctly
title: 'log analysis:: API server pod missing. Log: …
=> Fix bug of textAnalyzer

pkg/clients/kubernetes/scheme.go, pkg/providers/snow/objects_test.go, pkg/providers/snow/snow.go, pkg/providers/snow/snow_test.go
Found this bug while testing label upgrade in snow provider. The kubeconfig used for upgrade to fetch existing CAPI object in the cluster should be bootstrap cluster (where CAPI resources live) instead of workload cluster.
- Unit tests
- e2e label upgrade passed w new kubeadmconfigtemplate generated
=> Fix snow upgrade

pkg/api/v1alpha1/snowmachineconfig.go, pkg/api/v1alpha1/snowmachineconfig_test.go, pkg/api/v1alpha1/snowmachineconfig_webhook_test.go
Temporarily remove the device non empty validation since it is a newly added, required field.
This validation runs in snowmachineconfig webhook and ValidateUpdate fails when upgrading from older eks-a version without the `devices` field. We will add this validation back once users update their clusters to latest version.
unit tests
=> Remove snowmachine devices non empty validation

release/pkg/assets/config/bundle_release.go
We don't push `latest` tag for Tinkerbell charts, so need to use the ECR API to get the latest tag pushed by time.
=> Get latest ECR tag for Tinkerbell charts

docs/content/en/docs/tasks/cluster/cluster-scale/baremetal-scale.md
eksctl generate hardware is missing the 'anywhere' subcommand.
I'm simply adding the missing 'anywhere' subcommand
Tested locally
=> Add missing 'anywhere'

pkg/clustermanager/cluster_manager.go, pkg/diagnostics/diagnostic_bundle.go
Issue:
In certain failure cases, the logs for tinkerbell infrastructure pods
were empty. This was because the support bundle log collection duration
was set to one hour. For certain timeout scenarios in bare metal world,
the failure and hence the support bundle collection could take more an
hour since start of cluster creation. Tinkerbell infrastructure pods are
mostly inactive once provisioning finishes or fails, and may not be
actively logging resulting in empty hourly logs for these pods.
=> Increase support bundle pod logs collection 'since' time to 3 hours.

docs/content/en/docs/getting-started/production-environment/vsphere-getstarted.md, docs/content/en/docs/tasks/packages/_index.md
The instruction for running curated packages for initial v.s. separate workload clusters are different. Therefore I'm adding some clarification on how to do so for workload clusters.
*Description of changes:* Two doc files.
*Testing (if applicable):* Built locally and made sure there were no format issues.
=> Add instructions for running packages on workload clusters

pkg/addonmanager/addonclients/fluxaddonclient.go, pkg/addonmanager/addonclients/fluxaddonclient_test.go, pkg/addonmanager/addonclients/upgrader.go, pkg/addonmanager/addonclients/upgrader_test.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
First part of #2755 
This PR only handles the case of installing new Flux controllers in a Flux disabled cluster through upgrade command.
During components upgrade, when FluxConfig does not exist in the existing cluster, but specified in the new cluster spec, we install the flux controllers **without** adding EKS-A spec in the git repo. `UpdateGitEksaSpec` in the "updateClusterAndGitResources" step will then add the new EKS-A spec to the repo once cluster is fully upgraded. 
Logic behind this setting:
- It makes logical sense to install controllers as part of the EKS-A components during components upgrade step
- Only install the Flux controller with its controller configs during components upgrade so that none of the EKS-A resources will …
=> Install flux controllers during components upgrade if not exist before

docs/content/en/docs/getting-started/install/_index.md
This PR adds a note to the [install guide](https://anywhere.eks.amazonaws.com/docs/getting-started/install/) that Docker Desktop is not supported for EKS-A Bare Metal.
=> Docker desktop not supported for bare metal

Makefile, internal/test/testdata/bundles.yaml, internal/test/testdata/bundles_template.yaml, pkg/manifests/releases/read.go
Replace dev release S3 bucket references with Cloudfront domain `dev-release-assets.eks-anywhere.model-rocket.aws.dev`.
=> Replace dev release S3 bucket references with Cloudfront domain

pkg/clusterapi/name.go, pkg/clusterapi/name_test.go, pkg/constants/constants.go, pkg/executables/clusterctl.go, pkg/providers/snow/objects.go, pkg/providers/snow/objects_test.go, pkg/providers/snow/snow.go, pkg/providers/snow/snow_test.go
#1106 
- Support snow upgrade from beta with different CAPI objects naming format
- Add ChangeDiff to upgrade CAPAS provider during components upgrade
- Unit tests
- Manually upgrade snow cluster from beta to latest
=> Fix snow upgrade bugs encountered during upgrade from beta

cmd/eksctl-anywhere/cmd/installpackagecontroller.go, pkg/constants/constants.go, pkg/curatedpackages/curatedpackages.go, pkg/curatedpackages/packageinstaller.go, pkg/curatedpackages/packageinstaller_test.go
The existence of cert-manager is required to ensure proper operation of the PackageController. We modify the cluster creation workflow and imperative package installation command to add in the CertManagerExits logic, and guide users to handle the case where cert-manager is not present in the cluster.
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/278
*Description of changes:* Modified the cluster creation workflow and imperative package installation command to add in the CertManagerExits logic
*Testing (if applicable):* Tested in cluster creation workflow and imperative package installation
=> Add CertManagerExits logic for PackageController Installation

docs/content/en/docs/tasks/packages/_index.md
Closes: https://github.com/aws/eks-anywhere-packages/issues/279
There didn't seem to be any other missing mentions
/cherry-pick release-0.10
=> Add feature gate env to packages docs

pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/common/common.go, pkg/providers/docker/docker.go, pkg/providers/mocks/providers.go, pkg/providers/provider.go, pkg/providers/snow/snow.go, pkg/providers/tinkerbell/create.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go, pkg/workflows/create.go, pkg/workflows/create_test.go, pkg/workflows/delete.go, pkg/workflows/delete_test.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
Cloudstack provider has datacenter config but it contains the original values before transforming using Defaulters. This PR uses the passed-in clusterSpec instead of the stored datacenter config when preflight checking and template generation.
=> Support backward compatibility cloudstack datacenter config

controllers/resource/reconciler.go, controllers/resource/reconciler_test.go, controllers/resource/testdata/cloudstackCPMachineTemplate.yaml, controllers/resource/testdata/cloudstackEtcdMachineTemplate.yaml, controllers/resource/testdata/eksa-cluster-cloudstack-etcd.yaml, pkg/constants/constants.go, pkg/providers/common/common.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
#2710 
We are pausing reconciliation before the upgrade-core-components task to avoid premature rolling upgrades. See issue above for more details.
We also added a validation in the controller to never apply the CP and etcd templates on the management cluster through the controller.
=> Pause reconcile before upgrading core components

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, internal/test/e2e/testRunner.go, pkg/executables/govc.go, pkg/executables/govc_test.go, pkg/providers/vsphere/envars.go, pkg/providers/vsphere/envars_test.go, pkg/providers/vsphere/vsphere.go
#2614 
Specify the datacenter as an env var to avoid having govc infer based on the datacenters it is able to retrieve.
unit test and e2e
=> Add datacenter to govc env vars

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, test/framework/vsphere.go
Tests are currently failing from #2796 due to the env var not being set for all operations. Instead of only setting it for cleanup, setting it as part of the entire list of env vars so it can cover the cleanup phase in the prebuild as well as other operations like deploy.
=> Set govc datacenter variable for e2e tests

pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go
https://github.com/aws/eks-anywhere/issues/1090
Add cluster validations that we use in the CLI to the cluster webhook for creation on CRs.
- Unit tests
- Manual testing with tilt
-By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> Cluster webhook validation for create

docs/content/en/docs/getting-started/install/_index.md
This moves the note that describes how newer versions of Ubuntu that have cgroup v2 enabled are not supported. It is now right next to where the supported Ubuntu version is listed.
=> Newer Ubuntu versions not supported

cmd/eksctl-anywhere/cmd/generatepackage.go, cmd/eksctl-anywhere/cmd/installpackages.go, cmd/eksctl-anywhere/cmd/listpackages.go, cmd/eksctl-anywhere/cmd/upgradepackages.go, pkg/curatedpackages/bundle.go, pkg/curatedpackages/bundle_test.go
It wasn't being used anywhere anyway.
=> Remove kubeVersion argument to bundle reader

docs/content/en/docs/getting-started/install/_index.md, docs/content/en/docs/tasks/troubleshoot/troubleshooting.md
The EKS Anywhere docs currently state that only Ubuntu 20.04.2 is
supported as the administration machine due to Ubuntu 21 and 22 using
cgroups v2. This commit explains how to configure Ubuntu 21 and 22 to
use cgroups v1 if the administration machine is using the latest Ubuntu
versions.
This has been tested using `make serve` from the docs path.
=> Include documentation on Ubuntu cgroups v2

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/providers/vsphere/mocks/client.go, pkg/providers/vsphere/vsphere.go, test/e2e/upgrade_test.go, test/framework/cluster.go
Adds a new env var `EKSA_EXTERNAL_ETCD_TIMEOUT` to configure the timeout when waiting for external etcd to be ready
The new upgrade e2e test uses an invalid resource pool on the first attempt to upgrade the cluster, we then change the resource pool field to valid option & resume upgrade, in which it should now succeed. 
=> E2E test for re-running upgrade command

pkg/api/v1alpha1/cluster_webhook.go
CAPI uses the `Forbidden` error type for immutable fields. As we follow the CAPI convention, changing the field type to Forbidden.
Reference https://github.com/kubernetes-sigs/cluster-api/blob/main/api/v1beta1/machine_webhook.go#L130
- Unit tests
=> Update Invalid to Forbidden for immutable fields in cluster webhook

.golangci.yml
Current config format is deprecated
=> Update gci linter config to new format

controllers/snow_machineconfig_controller.go, controllers/snow_machineconfig_controller_test.go
Address further comments from https://github.com/aws/eks-anywhere/pull/2724
TODO:
- Work on a builder so that we can mock the validator functions instead of the client ones https://github.com/aws/eks-anywhere/pull/2724#discussion_r931324391
unit test
=> Improve error handling for snowmachineconfig controller

config/crd/bases/anywhere.eks.amazonaws.com_snowmachineconfigs.yaml, config/webhook/manifests.yaml, pkg/api/v1alpha1/awsiamconfig.go, pkg/api/v1alpha1/awsiamconfig_webhook.go, pkg/api/v1alpha1/awsiamconfig_webhook_test.go
*Description of changes:* 1) Add mutating webhook for awsiamconfig 2) make generate-manifests 
1. Unit Test
2. Tilt Up
```
1.6594634882760844e+09	INFO	awsiamconfig-resource	Setting up AWSIamConfig defaults for	{"name": "eksa-unit-test"}
```
=> Add mutating webhook for awsiamconfig

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, pkg/config/config.go, test/e2e/upgrade_test.go
E2E test for checkpoint feature cleaned up VMs too early. This should fix that issue.
=> Fix upgrade with checkpoint e2e test

release/pkg/assets/assets.go, release/pkg/assets/config/bundle_release.go, release/pkg/assets/types/types.go, release/pkg/bundles/certmanager.go, release/pkg/bundles/cilium.go, release/pkg/bundles/cloudstack.go, release/pkg/bundles/cluster-api-provider-aws.go, release/pkg/bundles/cluster-api-provider-docker.go, release/pkg/bundles/cluster-api.go, release/pkg/bundles/eksd.go, release/pkg/bundles/etcdadm-bootstrap.go, release/pkg/bundles/etcdadm-controller.go, release/pkg/bundles/flux.go, release/pkg/bundles/kindnetd.go, release/pkg/bundles/package-controller.go, release/pkg/bundles/snow.go, release/pkg/bundles/tinkerbell.go, release/pkg/bundles/vsphere.go, release/pkg/constants/constants.go, release/pkg/filereader/file_reader.go, release/pkg/operations/download.go, release/pkg/operations/rename.go, release/pkg/operations/upload.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/util/bundles/bundles.go
At the time of release tooling refactor, the CAPI providers had dropped usage of `kube-rbac-proxy` in their manifests, so we removed the functionality of replacing that URI in components manifests with the release URI for the `kube-rbac-proxy` image. Now, CAPC has a new release that uses kube-rbac-proxy for authz, so need to bring back that replacement functionality.
=> Replace kube-rbac-proxy in CAPI provider components manifest

pkg/networking/cilium/cilium.go, pkg/networking/cilium/cilium_test.go, pkg/networking/cilium/templater.go, pkg/networking/cilium/templater_test.go, pkg/networking/cilium/testdata/manifest_network_policy.yaml, pkg/networking/cilium/upgrader.go
Reduced the templater api to just one method for manifests and added
options for the different scenarios. This reduces the complexity and
allows for better reusability, specially from the controller side.
Unit tests 
=> Simplify cilium templater code

pkg/gitops/flux/cluster.go, pkg/gitops/flux/flux_test.go
My last flux refactoring PR #2843 changed the `setupRepository` method in flux package. It skipped git clone step when specifying git provider, which can cause git repo add failure.
Change the `initializeProviderRepositoryIfNotExists` to always return a non empty repo when using git provider.
Successfully create a git provider enabled docker cluster.
=> Always clone repo for git provider

docs/content/en/docs/reference/vsphere/domains.md, docs/content/en/docs/reference/vsphere/vsphere-prereq.md
Added wording to [vSphere prerequisite docs](https://anywhere.eks.amazonaws.com/docs/reference/vsphere/vsphere-prereq/) to emphasize the need to have the vCenter endpoint be accessible to EKS-A clusters.
=> Update vSphere prereq docs to highlight network access

pkg/controller/serverside/reconcile.go
This is recommended practice for most controllers. It ensures they
recover ownership of any field they need to control in case an external
entity updates them.
=> Use force ownership in controller serverside apply

pkg/validations/upgradevalidations/immutableFields.go, pkg/validations/upgradevalidations/immutableFields_test.go
#2755 
Enable flux upgrade in preflight flux immutability validation:
- old gitOpsRef nil, new gitOpsRef not nil -- validation succeeds, as we support installing flux in existing cluster
- old gitOpsRef not nil, new gitOpsRef nil -- validation fails, as we don't support removing flux in existing cluster rn
- both old and new gitOpsRef nil -- validation succeeds
- both old and new gitOpsRef not nil -- compare objects and fail if diff
Unit tests
=> Make gitOpsRef mutable in upgrade preflight check

pkg/networking/cilium/client.go, pkg/networking/cilium/ready.go, pkg/networking/cilium/ready_test.go
This is necessary in order to be reused from other packages, like the
cilium reconciler.
This is part of the original cilium reconciler PR, I'm just splitting it into independent chunks.
=> Make some cilium constants and methods public

pkg/api/v1alpha1/fluxconfig_webhook.go, pkg/api/v1alpha1/fluxconfig_webhook_test.go
*Description of changes:* Add fluxconfg.Validate() func call in validate/update webhook
1. Unit test
2. `make run controller`, `kubectl apply -f fluxconfig.yaml` for create and update
```
1.6595422910437675e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/validate-anywhere-eks-amazonaws-com-v1alpha1-fluxconfig", "UID": "c988d1d8-685c-4bc1-abb3-3e8a64fca1dc", "kind": "anywhere.eks.amazonaws.com/v1alpha1, Kind=FluxConfig", "resource": {"group":"anywhere.eks.amazonaws.com","version":"v1alpha1","resource":"fluxconfigs"}}
1.6595422910441718e+09	INFO	fluxconfig-resource	validate create	{"name": "test-gitops"}
1.6595422910475402e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": …
```
=> Add fluxconfig.Validate() func call in validate/update webhook

pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go
*Issue #2830*
Changes to fix an issue with webhook validations when Identity providers order is swapped. 
=> Cluster webhook immutable fields validation fix

pkg/gitops/flux/client.go, pkg/gitops/flux/client_test.go, pkg/gitops/flux/flux.go, pkg/gitops/flux/flux_test.go, pkg/gitops/flux/mocks/client.go
#2755 
When installing flux in existing cluster using upgrade command, we pause flux kustomization before components upgrade. The flux suspend step is not properly skipped since the new spec has gitops ref specified. For this case, we need to fetch the existing cluster object and check if `gitOpsRef` exist or not. If not, it means flux is not enabled in existing cluster and we skip the `SuspendKustomization` step.
Unit tests
=> Fix flux suspend failed during cluster upgrade

pkg/networking/cilium/installation.go, pkg/networking/cilium/installation_test.go, pkg/networking/cilium/upgrade_plan.go, pkg/networking/cilium/upgrade_plan_test.go
In combination with the cilium installation, this allows to represent
the currently installed Cilium components and make an upgrade plan based
on the desired state defined in a cluster Spec.
Unit tests
=> Add cilium upgrade planner

pkg/controller/clientutil/delete.go, pkg/controller/clientutil/delete_test.go
Intended to be used from controllers with `client.Client`
Unit tests
=> Add tooling to delete kube objects defined in yaml

pkg/config/proxy.go, pkg/config/proxy_test.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go
#2837
This PR fixes a bug in our proxy configuration logic. Prior to this PR, we only derived proxy configs from cluster config files.
This meant commands such as `eksctl anywhere download images` could not be used with a proxy.
This PR allows the CLI to derive a proxy config from the following env vars:
```
HTTPS_PROXY
HTTP_PROXY
NO_PROXY
```
I tested the `eksctl anywhere download images` command manually on an ec2 instance that could only communicate to the internet via a second ec2 instance that ran a proxy service.
I'm more than happy to add unit tests, I just wanted a review on the implementation first in case I was very off base. …
=> Derive Proxy Config From Env Vars

docs/content/en/docs/reference/changelog.md, pkg/features/features.go, pkg/validations/cluster.go, pkg/validations/cluster_test.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations.go, test/e2e/awsiam_test.go, test/e2e/conformance_test.go, test/e2e/flux_test.go, test/e2e/labels_test.go, test/e2e/multiple_worker_node_groups_test.go, test/e2e/oidc_test.go, test/e2e/proxy_test.go, test/e2e/registry_mirror_test.go, test/e2e/simpleflow_test.go, test/e2e/stackedetcd_test.go, test/e2e/taints_test.go, test/e2e/upgrade_from_latest_test.go, test/e2e/upgrade_test.go, test/e2e/vsphere_autoimport_test.go
#2159 
Remove feature flag for kubernetes version 1.23
- make
- make e2e
=> Remove feature flag for kubernetes version 1.23

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go
#2159 
- Change default kubernetes version to 1.23
- make
=> Change default kubernetes version to 1.23

docs/content/en/docs/reference/clusterspec/baremetal.md, pkg/api/v1alpha1/tinkerbelltemplateconfig_defaults.go
N/A
Related to Bottlerocket issue: https://github.com/bottlerocket-os/bottlerocket/issues/2291
```
docs: Add additional information about Bottlerocket console settings
This change adds additional information regarding console setup to the
Bottlerocket section of "Advanced Bare Metal cluster configuration".  It
removes the default console settings from the spec itself and provides a
bit more information and references about how you could set up consoles
on your Bottlerocket host.
For additional context and reference, see the Bottlerocket issue:
https://github.com/bottlerocket-os/bottlerocket/issues/2291
```
```
tinkerbell template defaults: Remove Bottlerocket console settings
With the current default settings, Bottlerocket nodes are …
```
=> Remove Bottlerocket default console settings and update documentation

pkg/providers/tinkerbell/config/template-cp.yaml, pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_awsiam.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_awsiam.yaml, pkg/providers/tinkerbell/tinkerbell_test.go, test/e2e/awsiam_test.go
*Issue #2749*
Also addresses #2885 
Changes to enable support for `aws-iam-authenticator` integration for EKS-A with provider tinkerbell.
=> IAM Authenticator for provider Tinkerbell

release/pkg/assets/config/bundle_release.go, release/pkg/bundles/tinkerbell.go, release/pkg/test/testdata/main-bundle-release.yaml
The dev-release process was failing since we removed pbnj from build-tooling.
=> Removing pbnj from dev-release flow

pkg/executables/helm.go, pkg/executables/helm_test.go, pkg/providers/tinkerbell/stack/stack.go, pkg/providers/tinkerbell/stack/stack_test.go, pkg/providers/tinkerbell/tinkerbell.go
https://github.com/aws/eks-anywhere/issues/2772
Update tinkerbell stack to use the updated tinkerbell helm chart with envoy and LoadBalancerClass here https://github.com/aws/eks-anywhere-build-tooling/pull/1091
Also, add a `--wait` to the helm install command so helm waits for deployments to be ready before moving forward
Created a new bare-metal cluster with the updated tinkerbell chart
=> Update tinkerbell stack to use the latest tinkerbell helm chart

pkg/cluster/cloudstack.go, pkg/cluster/cloudstack_test.go, pkg/cluster/docker.go, pkg/cluster/docker_test.go, pkg/cluster/snow.go, pkg/cluster/snow_test.go, pkg/cluster/testdata/cluster_cloudstack_missing_datacenter.yaml, pkg/cluster/testdata/cluster_docker_missing_datacenter.yaml, pkg/cluster/testdata/cluster_snow_missing_datacenter.yaml, pkg/cluster/testdata/cluster_vsphere_missing_datacenter.yaml, pkg/cluster/vsphere.go, pkg/cluster/vsphere_test.go
Objects.GetFromRef() can return a nil value that cannot be cast to a provider datacenter datatype.
Added nil check to prevent casting in provider processors.
=> adding nil check to cluster config datacenter

pkg/diagnostics/analyzers.go, pkg/diagnostics/analyzers_test.go, pkg/diagnostics/collector_types.go, pkg/diagnostics/collectors.go, pkg/diagnostics/collectors_test.go, pkg/diagnostics/diagnostic_bundle.go, pkg/diagnostics/diagnostic_bundle_test.go, pkg/diagnostics/interfaces.go, pkg/diagnostics/interfaces/mocks/diagnostics.go
Move the the api server collector to be one of collectors of vSphere provider. This collector will only work when need to generate support bundle for the vSphere cluster. It won't bother the process of creating/getting support bundle for docker cluster. Same change on control plane analyzer. 
=> Isolated the api server collector and analyzer to vsphere cluster only

test/e2e/simpleflow_test.go, test/framework/tinkerbell.go
Updated baremetal e2e tests to use custom Ubuntu images and removed redundant test case.
=> Update e2e tests to use new ubuntu images

controllers/factory.go, controllers/mocks/snow_machineconfig_controller.go, controllers/snow_machineconfig_controller.go, controllers/snow_machineconfig_controller_test.go, pkg/aws/snow.go, pkg/aws/snow_test.go, pkg/dependencies/factory.go, pkg/providers/snow/reconciler/clientbuilder.go, pkg/providers/snow/reconciler/clientbuilder_test.go, pkg/providers/snow/reconciler/credentials.go
Adding ability to read credentials from the credentials secret provided by the capas provider in order to construct the aws client maps.
unit testing
=> Load snow env vars from secret for controller

pkg/clusterapi/extraargs.go, pkg/clusterapi/extraargs_test.go, pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_awsiam.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_external_etcd.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_full_oidc.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_minimal_oidc.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_node_labels.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_node_taints.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_stacked_etcd.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_missing_ssh_keys.yaml
Enable LBClass feature gate for baremetal v1.21 cluster
Created a baremetal v1.21 cluster and verified the changes
```
k get pod -n kube-system kube-apiserver-eksa-da04 -oyaml | grep gate
- --feature-gates=ServiceLoadBalancerClass=true
```
https://v1-21.docs.kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#:~:text=field%20on%20Services.-,ServiceLoadBalancerClass,-%3A%20Enables%20the%20loadBalancerClass
=> Enable LBClass feature gate for baremetal v1.21 cluster

cmd/eksctl-anywhere/cmd/checkimages.go, cmd/eksctl-anywhere/cmd/common.go, cmd/eksctl-anywhere/cmd/generatebundleconfig.go, cmd/eksctl-anywhere/cmd/importimages.go, cmd/eksctl-anywhere/cmd/installpackagecontroller.go, cmd/eksctl-anywhere/cmd/listovas.go, cmd/eksctl-anywhere/cmd/options.go, cmd/eksctl-anywhere/cmd/supportbundle.go, pkg/cluster/spec.go
Splitting cluster config validation out from clusterSpec creation
=> Separating clusterConfig validation from creation

pkg/providers/tinkerbell/assert.go, pkg/providers/tinkerbell/assert_test.go, pkg/providers/tinkerbell/cluster.go
Add a preflight for k8s v1.20 for bare metal deployment so it fails early
Tried to create a v1.20 bare metal cluster and verified that it fails preflight
```
❌ Validation failed	{"validation": "tinkerbell Provider setup is valid", "error": "kubernetes version v1.20 is not supported for Bare Metal", "remediation": ""}
```
=> Add preflight for k8s v1.20 on baremetal

pkg/api/v1alpha1/cloudstackdatacenterconfig_webhook.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go
From manual testing, we uncovered a possible panic when removing AvailabilityZones. Since this discovery, making the logic safer and adding unit tests
Unit tests
=> Fixing panic on ImmutableFieldChanges comparison

test/e2e/vsphere_autoimport_test.go
Ubuntu OVAs autoimport is not supported anymore.
=> Remove vpshere ubuntu auto-import e2e tests

pkg/curatedpackages/packagecontrollerclient.go
Remove noisy messaging during secret creation failure and cron job failure.
=> Change secret creation failure messaging

controllers/resource/fetcher.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go
in the e2e tests, we observed two issues:
1. Many errors in the EKS-A controller log like `cloudstackmachinetemplate not found`
2. Replacement of worker nodes because
After setting up the debugger, the issue was isolated to the moment the EKS-A controller was paused, and we were able to analyze that comparison between the CSDC generated from the CloudStackCluster and the CSDC in the cluster would not be apples-to-apples, and would be missing the ManagementAPIEndpoint attribute
Unit testing, and e2e testing behavior is improved. No more errors in EKS-A controller logs, and no more recycling of worker machines. …
=> Resolving eks-a controller spec discrepancy

docs/content/en/docs/reference/clusterspec/optional/proxy.md
Follows https://github.com/aws/eks-anywhere/pull/2849
This change documents support for using EKS-Anywhere behind a Proxy via environment variables.
Previously, only commands using a cluster config file could use a proxy.
Now, you can use a proxy for any command by setting the documented environment variables.
Additionally, I added documentation that to successfully use a proxy you will need to update your docker daemon's configuration as described in docker's own documentation.
=> Document Proxy Env Vars

release/pkg/assets/images/images.go
Fixes the invalid reference format error during release
```
time="2022-08-18T01:09:13Z" level=fatal msg="Invalid destination name docker://public.ecr.aws/w9m0f3l5/-cli-tools:v0.11.0-eks-a-14: invalid reference format"
```
=> Trim leading dash in repo name

pkg/executables/config/kind.yaml, pkg/executables/testdata/kind_config.yaml, pkg/executables/testdata/kind_config_docker_mount.yaml, pkg/executables/testdata/kind_config_docker_mount_networking.yaml, pkg/executables/testdata/kind_config_extra_port_mappings.yaml, pkg/executables/testdata/kind_config_registry_mirror_insecure.yaml, pkg/executables/testdata/kind_config_registry_mirror_with_ca.yaml
When not specified, kind will use the right apiVersion for the desired
kubernetes version. However, when specified, the patch will only apply
if the kubernetes version requires the specified kubeadm version. This
made it a problem when supporting 1.20 and 1.23 and the same time, since
1.20 requires v1beta2 and 1.23 requires v1beta3. By removing this line,
we let kind select the right one dynamically. This only works if the
specified fields in patch are compatible with both kubeadm versions,
otherwise, one patch per apiVersion is required. For now, we only use
stable fields available in both versions, so this is the easiest
solution.
More info:
https://github.com/kubernetes-sigs/kind/issues/1839#issuecomment-1148968204 …
=> Remove kubeadm apiVersion from kind config

release/pkg/assets/config/bundle_release.go, release/pkg/operations/bundle_release_test.go, release/pkg/test/testdata/release-0.11-bundle-release.yaml
Ubuntu references were removed from the bundle spec in #2952, but we also need to remove the download/upload operations for Ubuntu artifacts.
=> Remove Ubuntu artifacts from release process

cmd/eksctl-anywhere/cmd/deletecluster.go, pkg/workflows/delete.go, pkg/workflows/delete_test.go
I observed a panic overnight in an e2e test which referenced a nil writer being dereferenced inside the TaskRunner's`RunTask` method. It appears that the writer in this workflow was never passed in or set, so this PR adds a writer in. Full panic below:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x2664a05]
goroutine 1 [running]:
github.com/aws/eks-anywhere/pkg/task.(*taskRunner).saveCheckpoint(0xc0002dfd10, {0x2da535d}, {0xc0003bcb70, 0x27})
/codebuild/output/src406348551/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/pkg/task/task.go:194 +0x165
github.com/aws/eks-anywhere/pkg/task.(*taskRunner).RunTask(0xc0002dfd10, …
```
=> Setting filewriter so it's non-nil to avoid panic

release/pkg/assets/config/bundle_release.go, release/pkg/images/images.go
Instead of getting the latest tag by timestamp, this PR just sources the latest tag followed by `-helm` in case of dev release and staging release.
=> Source latest tag for EKS-A packages Helm chart

docs/content/en/docs/reference/artifacts.md
This PR updates the artifacts.md page to tell users that:
- EKS Anywhere no longer distributes Ubuntu images and
- They can use image-builder to create their own Ubuntu-based node images
=> Updated artifacts page for image-builder

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml
Tests take a while to run, so we don't want the release to be blocked by them.
=> Upload EKS-A tarballs before running tests

docs/content/en/docs/tasks/packages/prereq.md
*Issue #, if available:* Package prerequisites is currently not showing in the side bar
=> Add pkg prerequisites to sidebar

docs/content/en/docs/tasks/cluster/etcd-backup-restore.md
https://anywhere.eks.amazonaws.com/docs/tasks/cluster/
Etcd Backup and Restore section is missing description in the cluster management overview page.
=> Add description for etcd backup and restore

cmd/integration_test/build/script/upload_artifacts.sh, release/pkg/bundles/eksctl-anywhere.go
This will prevent CLI tarballs uploaded by staging release from being overwritten by the e2e pipelines.
=> Upload tarballs to different folder for staging EKS-A release

docs/content/en/docs/tasks/cluster/cluster-upgrades.md
#2846 
Added documentation about manual cluster reconciliation pause in the cluster management upgrade section. Pausing eks-a cluster controller is more of an internal operation and not meant to be used frequently by user. Thus I'm adding it in the upgrade page instead of a separate section.
=> Add instruction for manually pausing cluster reconcile

test/e2e/flux_test.go
Flux Git upgrade tests #3030 in are failing
```
2022-08-19T15:44:46.138Z	V3	Cleaning up long running container	{"name": "eksa_1660923081000441388"}
envars.go:11: Required env var [EKSA_GIT_KNOWN_HOSTS] not present
```
Update the e2e method names to follow the regex pattern: https://github.com/aws/eks-anywhere/blob/main/internal/test/e2e/fluxGit.go#L37 so that the required git envs will be set in CI.
=> Fix flux git e2e

test/e2e/upgrade_test.go, test/framework/cluster.go
For checkpoint tests, the first run of `upgrade cluster` will fail. If we return the error in the framework, this will signal the e2e test to end there. So if the checkpoint feature is enabled, we won't return the error in the framework. The error will still happen in the logs as usual, but the e2e test will continue, allowing us to accurately test the checkpoint feature.
Example output after the first upgrade failure with these changes:
```
2022-08-05T17:26:04.543Z	V4	Task finished	{"task_name": "collect-cluster-diagnostics", "duration": "2m41.519058791s"}
2022-08-05T17:26:04.543Z	V4	----------------------------------
2022-08-05T17:26:04.543Z	V4	Saving checkpoint	{"file": "eksa-test-5d81cdf-checkpoint.yaml"}
2022-08-05T17:26:04.544Z	V4 …
```
=> Continue e2e test after failure when checkpoint is enabled

cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/import_images.go
`import images` command has also a similar issue described in https://github.com/aws/eks-anywhere/issues/2878
Adding --insecure flag to `import images` command (Refer to https://github.com/aws/eks-anywhere/pull/2879)
Mount `certs` directories if EKSA_CLOUDSTACK_HOST_PATHS_TO_MOUNT env var is defined
Manual test on a customer environment. 
=> Add mounts and insecure to import images

docs/content/en/docs/getting-started/local-environment/_index.md, docs/content/en/docs/getting-started/production-environment/baremetal-getstarted.md, docs/content/en/docs/getting-started/production-environment/vsphere-getstarted.md, docs/content/en/docs/tasks/packages/_index.md, docs/content/en/docs/tasks/troubleshoot/packages.md
The docs claim that curated packages installation is optional and that is not the case anymore. The package controller gets installed every time, but may not be used.
I also pulled out the repeated text and moved it to the packages tasks docs.
=> Generalize the package installation

pkg/eksd/installer.go, pkg/eksd/installer_test.go, pkg/eksd/upgrader_test.go
While performing some scaling testing, I observed several occasions where EKS-A was unable to fetch EKS-D CRDs/manifests and never retried. This connection failure resulted in cluster creation failing. This felt like a defect as we work to make EKS-A more robust, so this PR adds retry logic to the reader calls.
Adding this retry logic does slow down the unit tests to account for the retries and waits.
This logic could also be added at the Reader level itself. However, that leads to a myriad of other issues, including unit tests failing in the cluster_manager because the gomock matcher no longer recognizes two cluster.Specs as equivalent because their nested Reader resources differ. 
Created cluster using …
=> Adding retries for reading remote EKS-D CRD's/manifests

docs/content/en/docs/reference/packagespec/_index.md
The column defined in the parent template is called "GitHub" so update the link to their github page.
=> Update metallb link to their github page

internal/pkg/api/cloudstack.go, test/e2e/upgrade_test.go, test/framework/cloudstack.go
Deprecating old CloudStack schema for e2e tests in favor of using AvailabilityZones, and removing some unused methods
Running the following e2e tests locally succeeded
TestCloudStackKubernetes120GitopsOptionsFluxLegacy
TestCloudStackKubernetes120RedhatTo121MultipleFieldsUpgrade
TestCloudStackKubernetes120RedhatTo121Upgrade
TestCloudStackKubernetes120RedhatWorkerNodeUpgrade
TestCloudStackKubernetes120UpgradeFromLatestMinorRelease
TestCloudStackKubernetes121RedhatAndRemoveWorkerNodeGroups
=> Upgrading CloudStack e2e tests to use AvailabilityZones

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/mocks/client.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go, pkg/providers/tinkerbell/upgrade.go
*Issue #2748*
Adding a kubectl wait for BaseboardManagement objects once created to ensure the connection is successful.
*Testing :*
` ./eksctl-anywhere create cluster -f cluster.yaml -z hardware.csv`
=> BMC connection wait

internal/test/envtest/client.go, internal/test/envtest/client_test.go, pkg/networking/cilium/reconciler/reconciler_test.go
Add util to create objects with a kube client and wait until the client
cache gets refreshed with them. This avoid race conditions where the
tested code gets executed before those objects are available, making it
seem like they don't exist.
Ran all the package tests in loop 200 times.
=> Fix Cilium reconciler flaky tests

pkg/controller/clientutil/yaml.go, pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/upgrade.go, pkg/utils/unstructured/yaml.go, pkg/utils/unstructured/yaml_test.go
TinkerbellMachineTemplate is immutable and does not need to be reapplied during
upgrade. templateOverride string field in TinkerbellMachineTemplate may have
changed build numbers for action images across different versions of EKS Anywhere.
Not unnecessarily reapplying TinkerbellMachineTemplate mitigates this issue.
=> Omit TinkerbellMachineTemplate from upgrade specs.

docs/content/en/docs/tasks/troubleshoot/troubleshooting.md
Issue #, if available:
Current documentation has an errata when enabling Cgroups v1 on Ubuntu 21 and 22 versions:
%sudo /etc/default/group
It should be:
%sudo /etc/default/grub
Also, when modifying this file, it is needed to execute update-grub command to apply changes included on this file. If you don't do this, Cgroups v2 will be used.
Include in troubleshooting.md the changes needed to set Cgroups v1 in Ubuntu.
This has been tested using make serve from the docs path.
=> Fix Ubuntu 22.04 troubleshooting instructions

pkg/api/v1alpha1/awsiamconfig_webhook.go, pkg/api/v1alpha1/cloudstackdatacenterconfig_webhook.go, pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/fluxconfig_webhook.go, pkg/api/v1alpha1/gitopsconfig_webhook.go, pkg/api/v1alpha1/oidcconfig_webhook.go, pkg/api/v1alpha1/vspheredatacenterconfig_webhook.go, pkg/api/v1alpha1/vspheremachineconfig_webhook.go
Change immutable field errors to type Forbidden instead of Invalid so as to follow CAPI.
Reference: https://github.com/kubernetes-sigs/cluster-api/blob/main/api/v1beta1/machinehealthcheck_webhook.go#L135
- Unit tests
=> Change immutable field errors to type Forbidden

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/mocks/client.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go, pkg/providers/tinkerbell/upgrade.go
*Issue #2748*
Running` kubectl wait --all` for baseboardmanagements.
=> Kubectl wait all for bmc

Makefile, scripts/e2e_test_docker.sh, scripts/eksa_components_override.sh
This PR adds logic to build the cluster-controller image in the E2E presubmit and consume it for the E2E tests. This enables the controller image to be tested in presubmits.
=> Build cluster-controller image for consumption in E2E presubmit

docs/content/en/docs/reference/baremetal/netbooting-and-tinkerbell.md, docs/content/en/docs/reference/clusterspec/baremetal.md
*Issue #, if available:* #3179
The existing example for Bottlerocket did not have the required fields for a successful provision to occur. A copy/paste of the Bottlerocket template config would fail to provision the cluster.
This change allows a copy/paste to provide a successful
provision. Also, template action images were updated
to their latest versions.
=> Update Baremetal tinkerbelltemplateconfig:

controllers/resource/fetcher.go, controllers/resource/fetcher_test.go, pkg/api/v1alpha1/cloudstackmachineconfig_test.go, pkg/api/v1alpha1/cloudstackmachineconfig_types.go, pkg/api/v1alpha1/cloudstackmachineconfig_types_test.go, pkg/api/v1alpha1/cloudstackmachineconfig_webhook_test.go, pkg/executables/kubectl_test.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/cloudstack/validator.go, pkg/providers/cloudstack/validator_test.go
`DiskOffering: {}` is present when marshaling a CloudStackMachineConfig without defining it. This might break the backward compatibility and cause unwanted rolling upgrade. 
Unit testing
Manual testing
1. Create a cluster without DiskOffering
2. Upgrade the cluster with DiskOffering
3. Upgrade the cluster without DiskOffering 
=> Make DiskOffering in CloudStackMachineConfig optional

test/e2e/flux_test.go
Attempt to fix the test `estDockerInstallGithubFluxDuringUpgrade`.
This test was not boostraping flux during upgrade; the test would report that there was no FluxConfig present and so it did not need to bootstrap Flux during upgrade.
However, when looking at the cluster config, there WAS both a GitOpsRef and a FluxConfig; but notice the mismatched names.
GitOpsRef:
```
gitOpsRef:
kind: FluxConfig
name: eksa-test
```
FluxConfig: 
```
kind: FluxConfig
metadata:
creationTimestamp: null
name: eksa-test-plrd4
```
It appears that we're constructing the 'upgraded' cluster spec using the wrong GitOpsRef name; therefore, tho a GitOps ref is present, it does not point to an existing FluxConfig. This …
=> unset explicit GitOpsref name, as it is set in WithFluxGithub

docs/content/en/docs/reference/clusterspec/optional/gitops.md, docs/content/en/docs/tasks/cluster/cluster-flux.md
Document the correct format for SSH URLs provided to the generic git provider. This is in response to https://github.com/aws/eks-anywhere/pull/3197.
=> improve gitops docs with ssh url format

internal/pkg/api/flux.go, test/e2e/flux_test.go
alright, let's see if this addresses the issue with the name overrides -- we're adding an option to explicitly set the name in the FluxConfig, so that it uses the same name as we're expecting in the upgrade filler.
=> Fix GitHub upgrade tests

controllers/cluster_controller_test.go, pkg/executables/clusterctl_test.go, pkg/providers/snow/reconciler/reconciler_test.go, release/api/v1alpha1/artifacts.go
We made AWS a pointer and we don't include it in the bundle manifest
anymore, which means that all the code the references that field (while
assuming it was a struct a not a pointer) blows up when with a nil
pointer when facing the new bundle.
=> Remove all references to AWS bundle

test/e2e/curated_packages_test.go, test/e2e/harbor_test.go
A short term goal of the CP team is to have our E2E tests run against the
current builds of our packages. These hard-coded registries are preventing
that, so we're planning to replace them. As a first step towards that,
separating these variables will allow for smaller-step refactoring towards
that goal.
=> cp e2e: Define constants where they're used.

pkg/api/v1alpha1/cloudstackmachineconfig_test.go, pkg/api/v1alpha1/zz_generated.deepcopy.go
PR #3181 updated the CloudStack types but did not trigger `make generate`
to update the `zz_generated.deepcopy.go`. This causes a few unit tests
to fail when others try to regenerate the file. This PR updates the generated
code and fixes the broken testcases for CloudStackMachineConfig.
=> Update the generated go code for pkg/api/v1alpha1

pkg/controller/clusterapi.go, pkg/controller/clusterapi_test.go, pkg/providers/snow/reconciler/reconciler.go
Follow up from this [discussion](https://github.com/aws/eks-anywhere/pull/3192#discussion_r957774271)
=> Move capi obj key method to controller capi file

pkg/diagnostics/collector_types.go, pkg/diagnostics/collectors.go, pkg/diagnostics/collectors_test.go
From [Troubleshoot.sh](https://troubleshoot.sh/docs/collect/deprecated/run/), the Run collector has been deprecated. The Run Pod collector will cover its job. It's better to keep it up-to-date in our repo. 
Another trivial change: set timeout for the collectors so that the collecting process cannot be blocked if one collector stalls or fails. 
=> Replace deprecated run collector to run pod and Set timeout for collectors

cmd/eksctl-anywhere/cmd/deletecluster.go, cmd/eksctl-anywhere/cmd/supportbundle.go, cmd/eksctl-anywhere/cmd/upgradecluster.go, pkg/kubeconfig/kubeconfig.go, pkg/kubeconfig/kubeconfig_test.go, pkg/validations/input.go
Instead of just checking that the file exists, the k8s client-go library is
used to load the file's data, which validates its basic structure, as well as
its existence.
This small step is a precursor to further work to concentrate how kubeconfig
files are handled across the various eksctl-anywhere subcommands.
=> Improved validation of kubeconfig files

docs/content/en/docs/tasks/packages/emissary/_index.md, docs/content/en/docs/tasks/workload/ingress.md
=> Fixes for emissary and ingress docs

pkg/diagnostics/analyzers.go, pkg/diagnostics/collectors.go, pkg/diagnostics/collectors_test.go, pkg/diagnostics/config/diagnostic-collector-rbac.yaml
Extend the functionality of support bundle by
- adding a run-pod collector--vmsAccessCollector. It supposes to collect logs from vsphere cloud controller manager on control plane.
- since the pod need to be deployed on control plane node, specific tolerations have been set.
- It is also able to accept customized taints that given by user in cluster defination yaml.
- adding a vmsAccess analyzer. Based on the log from the collector, the analyzer is able to analyze if the vms have access to vsphere api server.
- Now, the analyzer starts to work from bootstrap cluster, although we expect that the analyzer only does its work on workload cluster. A clarification was temporarily added to the output to avoid confusion.
- Also, more work on …
=> Add analyer to analyze if vms have access to api server

pkg/crypto/validator_test.go
We need to add this check as newer version of macos require the adding trusted certs manually,
through `security add-trusted-cert`, so we are only able to run this test on linux for now. This is a known issue here: https://github.com/golang/go/issues/52010
Created https://github.com/aws/eks-anywhere/issues/3267 to track our fix for the above issue
Refer to https://go-review.googlesource.com/c/go/+/353132 and https://github.com/helm/helm/pull/11160 for some explanations and an example
unit tests
=> Skip cert validator unit test for darwin

pkg/kubeconfig/kubeconfig.go, pkg/kubeconfig/kubeconfig_test.go
The KUBECONFIG environment variable is defined to contain a list of filenames. If it is a list, return the first one. If it's not a list, returns the entire string (as before).
In theory, a program using this environment variable would merge the kubeconfig files listed into a larger structure containing contexts, users, and clusters. At this time however, the eksctl-anywhere command is always expecting a single user/context/cluster to be defined in a single kubeconfig file.
=> kubeconfig: Modify FromEnvironment to handle lists
