aws/eks-anywhere

docs/config.toml
Add a "Contact us" link to the top of all docs pages that points to https://aws.amazon.com/contact-us/sales-support-eks/
=> Add Contact us link to all docs pages

pkg/providers/vsphere/setupuser/testdata/configs/missing_objects.yaml, pkg/providers/vsphere/setupuser/testdata/configs/not_yaml.yaml, pkg/providers/vsphere/setupuser/testdata/configs/valid.yaml, pkg/providers/vsphere/setupuser/testdata/configs/valid_minimal.yaml, pkg/providers/vsphere/setupuser/validator.go, pkg/providers/vsphere/setupuser/validator_test.go, pkg/validations/errors.go
https://github.com/aws/eks-anywhere/issues/3248
This adds business logic to read and validate a config file for the vSphere setup user command.
=> Setup vSphere User Config Read & Validation

pkg/cluster/spec.go, pkg/cluster/spec_test.go
This method always pulls the latest available Bundles from S3, that's
what the callers expect (create and upgrade commands). We should update
the ref to make sure the cluster.Spec is consistent and the cluster
references the Bundles included in the Spec.
=> Update BundlesRef when building a Spec from file

Makefile
Adds a make target to EKS A for executing `govulncheck`.
`govulncheck` is:
> a low-noise, reliable way for Go users to learn about known vulnerabilities that may affect their projects. Govulncheck analyzes your codebase and only surfaces vulnerabilities that actually affect you, based on which functions in your code are transitively calling vulnerable functions.
For the whole story, check out: https://go.dev/blog/vuln
To use this, just run `make vulncheck` to execut the command against the EKS Anywhere module.
The use of this command in the EKS Anywhere module highlights the importance of regular Go updates and the need to migrate to the latest patch version of 1.18.
`make vulncheck`
By submitting this pull …
=> add govulncheck make target

cmd/eksctl-anywhere/cmd/applypackages.go, cmd/eksctl-anywhere/cmd/createpackages.go, cmd/eksctl-anywhere/cmd/deletepackages.go, cmd/eksctl-anywhere/cmd/describepackages.go, cmd/eksctl-anywhere/cmd/get.go, cmd/eksctl-anywhere/cmd/getpackage.go, cmd/eksctl-anywhere/cmd/getpackagebundle.go, cmd/eksctl-anywhere/cmd/getpackagebundlecontroller.go, cmd/eksctl-anywhere/cmd/installpackages.go, cmd/eksctl-anywhere/cmd/listpackages.go, cmd/eksctl-anywhere/cmd/upgradepackages.go
Previously kubeconfig information was only loaded from an environment file. Now each of the curated packages commands takes an optional --kubeconfig flag, that if specified, loads the kubeconfig from that file, and errors if the file doesn't exist or fails to load. When no --kubeconfig is specified, it uses the previous behavior of loading kubeconfig info from the KUBECONFIG environment variable.
Flags have also been reorganized to be consistent with the style introduced in aws/eks-anywhere#3299.
=> feat(CLI): Add --kubeconfig flag to curated packages commands

pkg/providers/snow/defaults.go, pkg/providers/snow/defaults_test.go, pkg/providers/snow/validator.go, pkg/providers/snow/validator_test.go
Relates to #2809 
In snow post beta, we introduce a `devices` field in `snowmachineconfig`. All the existing validations and default logics run against all the devices specified in the aws creds file. We should only run those logics for specific devices listed in each `snowmachineconfig`.
Unit tests
=> Run snow machine validation and defaulters for the specific devices

release/Makefile, release/api/v1alpha1/artifacts.go, release/buildspecs/github-bundle-release.yml, release/cmd/release.go, release/pkg/assets/archives/archives_test.go, release/pkg/assets/images/images_test.go, release/pkg/assets/manifests/manifests_test.go, release/pkg/bundles/bundles.go, release/pkg/bundles/eksctl-anywhere.go, release/pkg/constants/constants.go, release/pkg/filereader/file_reader.go, release/pkg/images/images.go, release/pkg/operations/bundle_release_test.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.11-bundle-release.yaml, release/pkg/types/types.go, release/pkg/util/artifacts/artifacts.go, release/pkg/util/release/release.go, release/scripts/github-bundle-release-notes.tmpl, release/scripts/github-bundle-release.sh, release/scripts/release.sh
This PR adds a new weekly release mode to the release tool that generates a bundle release every week with a different tagging scheme. It also adds a script that will publish this bundle release manifest as a GitHub release with a date-based tag on main branch. The release notes will contain the commit information pertaining to this release.
=> Add support for weekly bundle creation and Github release

cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/generateclusterconfig.go, pkg/constants/constants.go, pkg/features/features.go, pkg/features/features_test.go
Add the case for adding Nutanix DatacenterConfig and MachineConfig
to cluster config options when generate clusterconfig and create cluster commands
are run for Nutanix provider with NUTANIX_PROVIDER environment variable
set to true.
=> Handle Nutanix Provider in create cluster and generate clusterconifg commands

docs/content/en/docs/tasks/troubleshoot/troubleshooting.md
NTP time sync issue between master and worker node could cause unauthorized errors from dataplane perspective
NTP time sync issue between master and worker node could cause unauthorized errors from dataplane perspective
Added warning in troubleshooting section
*Testing (if applicable):* NA
=> Added NTP out of sync issue warning

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/api/v1alpha1/testdata/cluster_without_worker_nodes.yaml, pkg/api/v1alpha1/testdata/cluster_without_worker_nodes_has_cp_taints.yaml
For creating single-node cluster
1. Allow workerNodeGroupConfigs to be empty
2. Check if control plane taints is empty when there is no worker node
3. Warn when there is no worker node
1. unit-test
2. Invoke eksa create cluster without workerNodeGroups. Validation pass
```
2022-09-09T11:26:48.464-0400    V0      Private key saved to single-node/eks-a-id_rsa. Use 'ssh -i single-node/eks-a-id_rsa <username>@<Node-IP-Address>' to login to your cluster node
2022-09-09T11:26:50.968-0400    V0      ✅ Tinkerbell Provider setup is valid
2022-09-09T11:26:50.968-0400    V0      ✅ Validate certificate for registry mirror
2022-09-09T11:26:50.968-0400    V0      ✅ Validate authentication for git provider …
```
=> Allow workerNodeGroupConfigs to be empty

release/Makefile, release/cmd/release.go, release/pkg/filereader/file_reader.go, release/pkg/git/git.go, release/pkg/images/images.go, release/pkg/operations/upload.go, release/pkg/util/artifacts/artifacts.go, release/scripts/github-bundle-release-notes.tmpl, release/scripts/github-bundle-release.sh
This PR includes the EKS-A releases manifest in the weekly release assets.
=> Upload EKS-A release manifest as part of weekly release

cmd/eksctl-anywhere/cmd/common.go, cmd/eksctl-anywhere/cmd/installpackagecontroller.go, pkg/curatedpackages/mocks/packageinstaller.go, pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go, pkg/curatedpackages/packageinstaller.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go
- Currently curated packages don't work behind a proxy. This enables curated packages to be installed behind a proxy.
=> Package proxy fix

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml, config/manifest/eksa-components.yaml, pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_types_test.go, pkg/clusterapi/apibuilder.go, pkg/clusterapi/apibuilder_test.go, pkg/clusterapi/autoscaler.go, pkg/clusterapi/autoscaler_test.go, pkg/providers/snow/apibuilder_test.go
Resolves #3188 
Introduce `AutoScalingConfiguration` field in `WorkerNodeGroupConfiguration`. When specified, we add the Cluster Autoscaler annotation to the CAPI `MachineDeployment` resource.
API
```go
type AutoScalingConfiguration struct {
// MinCount defines the minimum number of nodes for the associated resource group.
// +optional
MinCount int `json:"minCount,omitempty"`
// MaxCount defines the maximum number of nodes for the associated resource group.
// +optional
MaxCount int `json:"maxCount,omitempty"`
}
```
Also add validations for the field.
Something we need to follow up:
1. In the original design: https://github.com/aws/eks-anywhere/blob/main/designs/autoscaler.md#api-design, we plan to change …
=> Enable node autoscaling option with Cluster Autoscaler

cmd/eksctl-anywhere/cmd/installpackagecontroller.go
- If package controller doesn't exist in the cluster, install the controller
- If an error is returned during package controller installation, there is a good reason it is due to lack of crds in which case go ahead and try installing anyways.
=> Add comment for ignoring error

pkg/providers/cloudstack/cloudstack.go, pkg/providers/docker/docker.go, pkg/providers/mocks/providers.go, pkg/providers/provider.go, pkg/providers/snow/snow.go, pkg/providers/tinkerbell/upgrade.go, pkg/providers/vsphere/vsphere.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
BMC wait check fails for `cluster upgrade` flow for Tinkerbell provider, if new hardware is  not provided via hardware csv.
Added a provider specific call after management is moved to bootstrap cluster during upgrade, this enables checking all the BMCs (pre-existing and newly loaded from csv).
=> Upgrade bmc wait check after CAPI move

release/pkg/git/git.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.11-bundle-release.yaml
This PR fixes the logic of fetching repo tags to list only those that match semver format.
=> Fetch only repo tags that match semver

pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go
Dev bundles always have the name 'bundles-1'. Which means that when upgrading from latest prod version, the upgrade gets detected as a downgrade, hence failing. Removing this for now until we make dev bundles naming more consistent with prod.
Building the controller image, pushing to my registry and manually running e2e tests with a custom bundle
=> Remove bundlesRef downgrade validation temporarily

docs/content/en/docs/tasks/packages/metallb/_index.md
The namespace must be created manually and the docs don't state that.
=> Mention namespace creation in metallb docs

controllers/resource/reconciler.go, controllers/resource/reconciler_test.go, controllers/resource/template.go, controllers/resource/testdata/nutanix/cpMachineConfig.yaml, controllers/resource/testdata/nutanix/datacenterConfig.yaml, controllers/resource/testdata/nutanix/eksa-cluster.yaml, controllers/resource/testdata/nutanix/etcdMachineConfig.yaml, controllers/resource/testdata/nutanix/workerMachineConfig.yaml
Currently, this is more of a placeholder to start with as the TemplateResources method
just returns an empty array.
=> Handle the nutanix provider case in cluster reconciler

pkg/config/config.go, pkg/constants/constants.go, pkg/dependencies/factory.go, pkg/executables/dockerlinux.go, pkg/executables/executables.go, pkg/executables/executables_test.go
Add snow creds & certs to redacted env vars
`eksctl-anywhere create cluster` with Snow & vSphere and viewed logs with redacted values
=> Redact snow creds in verbose logs

manager/README.md
Updating based on changes made in #3217 
The IMG is now named `eks-a-controller-manager` so the ECR repo name needs to reflect that. 
=> ECR repo name change for Tilt

cmd/integration_test/cmd/run.go, internal/pkg/ssm/command.go, internal/test/e2e/artifacts.go, internal/test/e2e/awsiam.go, internal/test/e2e/cloudstack.go, internal/test/e2e/flux.go, internal/test/e2e/fluxGit.go, internal/test/e2e/ipmanager.go, internal/test/e2e/oidc.go, internal/test/e2e/proxy.go, internal/test/e2e/registryMirror.go, internal/test/e2e/run.go, internal/test/e2e/setup.go, internal/test/e2e/testRunner.go, internal/test/e2e/tinkerbell.go, internal/test/e2e/vsphere.go
* Don't print output from e2e tests from instance (this is already included in their own logstream)
* Pass a logger to all downstream entities
* Use logger with values in parallel runners
* Avoid noisy debug logs when running SSM commands by using a discard logger
* Unify instance test result log
In only built the binary, so this could break the tests
=> Improve logging in eks-a e2e test runner

pkg/aws/client_test.go, pkg/aws/snow.go
Fix snowballdevice validation errors
```
Post \"https://snowballdevice.snow.amazonaws.com/\": dial tcp: lookup snowballdevice.snow.amazonaws.com on 34.223.14.129:53: no such host
```
=> Add snowballdevice endpoint

pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go
This should allow no-op updates for management clusters like Flux periodic server-side apply reconciliations and adding/removing annotations (`paused`, for example)
Unit tests
=> Allow no-change updates for management clusters

pkg/eksd/installer.go, pkg/eksd/installer_test.go, pkg/eksd/upgrader_test.go
When upgrading a new cluster using the full lifecycle api, we can't upgrade the kubernetes version if it differs from the mgmt cluster version because only the eksd manifest for that version is applied to the cluster. To avoid needing a network connection in the controller, we will apply eks-d versions for all kubernetes versions in the bundle to the mgmt cluster.
Create docker cluster
*Testing with new api now...
=> Apply eksd manifest for each kubernetes version to cluster

pkg/networkutils/networkutils.go, pkg/networkutils/networkutils_test.go, pkg/providers/tinkerbell/assert.go, pkg/providers/tinkerbell/assert_test.go, pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/validate.go
#3238 
Added a preflight to ensure ports 80, 42113, and 50061 are not in use for baremetal
Tried creating a cluster and verified:
`❌ Validation failed	{"validation": "tinkerbell Provider setup is valid", "error": "port 42113 of host is already in use, please clean up ports", "remediation": ""}`
=> Add preflight to check port availability on the host for baremetal

pkg/providers/tinkerbell/config/template-cp.yaml, pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_single_node.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_single_node.yaml, pkg/providers/tinkerbell/tinkerbell_test.go
Pass taints = [] to cluster-api when workerNodeGroupConfigurations is empty
Related PR (allow workerNodeGroupConfigurations = nil): https://github.com/aws/eks-anywhere/pull/3321/files
- Unit test
- Manually created a tinkerbel single-node cluster with this change
=> Pass empty taints to cluster-api when there is no worker node

controllers/resource/fetcher.go, pkg/cluster/fetch.go, pkg/cluster/fetch_test.go, pkg/cluster/spec.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/mocks/client_and_networking.go
*Issue #3390*
Changes enable detection of diff in the cluster config for AWSIamConfig `MapRoles` and `MapUsers` during upgrade.
*Testing:*
```bash
./eksctl-anywhere upgrade cluster -f ./eks-a-cluster.yaml
```
=> Fix iam auth role upgrades

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/workflows/create.go
During CLI upgrade w controller v2, the `Applying eksa yaml resources to cluster` step failed due to the eksa cluster webhook validation error: `admission.anywhere.amazonaws.com\" denied the request: upgrading self managed clusters is not supported`
We are adding the paused annotation to cluster/datacenterconfig during CLI upgrade, similar to create.
=> Pause cluster and datacenter webhook validation during upgrade

docs/content/en/docs/reference/vsphere/vsphere-preparation.md, pkg/config/static/globalPrivs.json
After working with a user on this, we found out that missing the `Sessions.ValidateSession` permission results in the capv caching mechanism for sessions to not work, resulting in new sessions to be created all the time. This results in the session limit being breached if there are a lot of nodes running in the vcenter environment.
Error observed in capv logs:
```
E0921 19:13:06.002439       1 session.go:124] session "msg"="error checking if session is active" "error"="ServerFaultCode: Permission to perform this operation was denied." "datacenter"="Datacenter" "server"="10.61.250.74" 
```
Tested manually creating a cluster and running a create with the validation
By submitting this pull request, I confirm that …
=> Add validate session permission for vcenter global role

pkg/diagnostics/analyzers.go, pkg/diagnostics/analyzers_test.go
Add analyzer for checking `Sessions.ValidateSession` permission global role that was added as part of https://github.com/aws/eks-anywhere/pull/3416
This won't cause the cluster creation to fail if it is missing, but if cluster creation or upgrade fails for any other reason, the analyzer will point this issue out as well.
Also changed an existing analyzer to return a single analyze object instead of an array as it seems like we aren't creating multiple in that method.
make and ran manual cluster creation generating support bundle with and without permission
Success:
```
{
"name": "log.analysis.session.validate.permission.missing.log.logs.capv.system.capv.controller.manager.log",
"labels": {
"desiredPosition": …
```
=> Add vcenter session validate permission analyzer

release/pkg/assets/config/bundle_release.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.11-bundle-release.yaml
Removing tink CLI that was originally removed in #2540 but re-added to assets list during the release refactor #1161.
=> Remove Tink CLI image from assets list

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/api/v1alpha1/testdata/cluster_invalid_docker_with_endpoint.yaml, pkg/providers/docker/docker.go, pkg/providers/docker/docker_test.go
Moves docker validation to api level to use both with eksa cli commands & in the controller
=> Move docker validation to api level

Makefile
All curated packages e2e tests have been renamed to start with "TestCPackages" for convenience. Plus changing this to a docker test will make it easier to potentially run on presubmit as part of docker-e2e-test.
=> (docs)Makefile: update the default CP E2E test name

cmd/eksctl-anywhere/cmd/downloadimages.go, cmd/eksctl-anywhere/cmd/import.go, cmd/eksctl-anywhere/cmd/import_images.go
Remove redundant copyright notices in cmd files. These notices keep getting edited by IDEs as they have unnecessary newline characters but the notices are redundant anyway.
=> Remove redundant copyright notices

pkg/diagnostics/analyzers.go, pkg/diagnostics/analyzers_test.go, pkg/diagnostics/collectors.go, pkg/diagnostics/collectors_test.go
Add snow crd, controller analyzers and collectors in the support bundle.
Unit tests
=> Add snow analyzers and collectors in support bundle

test/e2e/curated_packages_test.go
The test was previously deleted in https://github.com/aws/eks-anywhere/pull/2801/files#diff-e04741f3b0c5b687abeb91625437530ddf182779c1b1b5fa4df95b9c59717c5eL28
Rebase brought it back by mistake.
=> Remove test re-added due to rebase

controllers/resource/internal/vsphere.go, controllers/resource/internal/vsphere_test.go, controllers/resource/reconciler_test.go, controllers/resource/template.go, pkg/providers/vsphere/config/secret.yaml, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
https://github.com/aws/eks-anywhere/issues/3404
The EKSA Controller didn't have necessary vsphere credentials. As a result, when it reconciled eksa-system:csi-vsphere-config it deleted the username and password.
How I tested:
* create:
* create cluster on main
* upgrade:
* create cluster on v0.11.1
* upgrade on release-0.11 with my changes on top of it. Secret `eksa-system:vsphere-credentials` was correctly updated.
* ran old controller while upgrading. `eksa-system:vsphere-credentials` was unaffected but controller continued to did still overwrite csi-vsphere-config secret
* ran new controller after upgrade and csi-vsphere-config reconciled correctly with appropriately populated config information derived from …
=> Inject vSphere Creds in Controller

cmd/eksctl-anywhere/cmd/applypackages.go, cmd/eksctl-anywhere/cmd/createpackages.go, cmd/eksctl-anywhere/cmd/deletecluster.go, cmd/eksctl-anywhere/cmd/deletepackages.go, cmd/eksctl-anywhere/cmd/describepackages.go, cmd/eksctl-anywhere/cmd/getpackage.go, cmd/eksctl-anywhere/cmd/getpackagebundle.go, cmd/eksctl-anywhere/cmd/getpackagebundlecontroller.go, cmd/eksctl-anywhere/cmd/installpackages.go, cmd/eksctl-anywhere/cmd/listpackages.go, cmd/eksctl-anywhere/cmd/supportbundle.go, cmd/eksctl-anywhere/cmd/upgradecluster.go, cmd/eksctl-anywhere/cmd/upgradepackages.go, pkg/kubeconfig/kubeconfig.go, pkg/kubeconfig/kubeconfig_test.go
Refactors the curated packages CLI commands to use the new functions introduced in ac5db7f. The non curated packages commands were not refactored, because I'm not 100% sure it's safe to do so. I'll leave that exercise for a later PR.
This helps simplify our k8s go client creation for CP CLI commands, which will be coming in a follow-up commit.
=> refactor(CLI): Use the new kubeconfig functions in CP CLI commands

pkg/curatedpackages/packageclient_test.go
Suppresses output generated from fmt.Println during tests.
=> Fix Go tests

pkg/api/v1alpha1/cloudstackmachineconfig_types.go, pkg/api/v1alpha1/cloudstackmachineconfig_types_test.go
As described in the comment below, clusters created with older versions of eks-a will have an empty diskoffering included on the CloudStackMachineConfig, like
```
diskOffering:
mountPath: ""
filesystem: ""
label: ""
device: ""
```
However, we have since made this field into a pointer and optional, so new versions of eks-a expect an unset diskoffering to have 
```
diskOffering: nil
```
This resulted in unintended rollingupgrades taking place where the eks-a controller would think there's a [difference between the diskofferings in old and new](https://github.com/aws/eks-anywhere/blob/main/pkg/providers/cloudstack/cloudstack.go#L608), and create a new CloudStackMachineTemplate. This change serves to align the two definitions to make them …
=> Fixing unintended rollingupgrade from older clusters related to diskoffering

controllers/resource/internal/vsphere.go, controllers/resource/internal/vsphere_test.go, controllers/resource/reconciler_test.go, controllers/resource/template.go, pkg/providers/vsphere/config/secret.yaml, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
The controller was not injecting the extra CSI/CP credentials.
https://github.com/aws/eks-anywhere/issues/3404
The EKSA Controller didn't have necessary vsphere credentials. As a result, when it reconciled eksa-system:csi-vsphere-config it deleted the username and password.
* create:
* create cluster on main
* upgrade:
* create cluster on v0.11.1
* upgrade on release-0.11 with my changes on top of it. Secret `eksa-system:vsphere-credentials` was correctly updated.
* ran old controller while upgrading. `eksa-system:vsphere-credentials` was unaffected but controller continued to did still overwrite csi-vsphere-config secret
* ran new controller after upgrade and csi-vsphere-config reconciled correctly with …
=> Inject CSI and CP vSphere Creds (#3424)

pkg/executables/clusterctl.go
=> Fix linter in clusterctlNetworkErrorRegex

pkg/executables/clusterctl.go
=> Use raw string in clusterctlNetworkErrorRegex

pkg/git/gitclient/gitclient.go
In some cases, errors.As was being used instead of errors.Is. The primary difference being that errors.As alters the target error. This can make for awkward error initializations, but also costs a bit of time to process.
More to the point, tests were failing with specific versions of go (namely 1.19).
Docs:
https://pkg.go.dev/errors#As
https://pkg.go.dev/errors#Is
=> refactor: Replace errors.As with errors.Is

release/api/v1alpha1/artifacts.go
Since this image was not part of the artifacts list, it wasn't going through the previous bundle digest check and added a new tag each time, leading to hitting ECR tag limits for the same digest.
=> Add cert-manager-ctl image to artifacts list

pkg/providers/tinkerbell/hardware/catalogue.go, pkg/providers/tinkerbell/hardware/catalogue_hardware.go, pkg/providers/tinkerbell/hardware/catalogue_hardware_test.go, pkg/providers/tinkerbell/upgrade.go
*Issue #3447*
Adding logic to remove list of provisioned hardware objects obtained from the management cluster during cluster upgrade. This prevents prevents the scenario where user had provisioned hardware in their `hardware.csv` input from getting applied and messing up the cluster.
*Testing:*
Tested different use cases where user provides varied inputs.
```bash
./eksctl-anywhere upgrade cluster -f ./tink/tink-eks-a-cluster.yaml
./eksctl-anywhere upgrade cluster -f ./tink/tink-eks-a-cluster.yaml -z hardware.csv
```
=> Remove repeated hardware during cluster upgrade

pkg/curatedpackages/bundle.go, pkg/curatedpackages/bundle_test.go
Previously, this didn't error out, which led to other processes failing, and often with much harder to debug error messages.
The most likely reason this would be called with an empty bundle name is the case where a packages controller has come online, but has not yet activated a bundle. In that case, it's Spec.ActiveBundle value will be the empty string.
More quick PRs in this series will follow. Be on the lookout!
=> feat(CLI): error getting a bundle without providing a name

cmd/eksctl-anywhere/cmd/installpackagecontroller.go, pkg/curatedpackages/mocks/packageinstaller.go, pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go, pkg/curatedpackages/packageinstaller.go
Any error indicates that the controller isn't installed, so this simplifies
the logic.
IsInstalled has only one caller, to the impact is minimal.
Depends on #3510
=> refactor(CLI): IsInstalled returns a single boolean.

pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/cloudstack/validator.go, pkg/providers/cloudstack/validator_test.go
Similar to VSphere's IP check, we want to prevent clusters from being created if the IP:port are already in use. If we don't have this check, they continue to be created and start reporting an x509 certificate error. 
During upgrades, we want to skip this validation. Previously the skipIpCheck parameter was unused in the CloudStack provider, now it's being plumbed to the validator.
Unit tests pass. Also, tried creating two clusters with the same IP and observed
```
2022-09-29T11:27:25.478-0400	V6	Executing command	{"cmd": "/usr/local/bin/docker exec -i eksa_1664465238305760000 cmk -c /Users/dribinm/workspaces/eksa/eks-anywhere/drib-rollingupgrade-copy/generated/cmk_global.ini list networks …
```
=> Adding IP check for cloudstack cluster creation

pkg/bootstrapper/bootstrapper.go, pkg/bootstrapper/mocks/client.go, pkg/executables/config/kind.yaml, pkg/executables/kind.go, pkg/executables/kind_test.go, pkg/workflows/create_test.go, pkg/workflows/delete_test.go, pkg/workflows/upgrade_test.go
The WithoutDefaultCNI is a relic from when we tried installing a different CNI into the KinD cluster. We have no desire to do this any longer.
=> Remove WithoutDefaultCNI bootstrapper option

pkg/yamlutil/apiobject.go, pkg/yamlutil/apiobject_test.go, pkg/yamlutil/parser.go, pkg/yamlutil/parser_test.go
This uses the same mechanism and the config manager to parse a kubernetes yaml manifest, allowing to dynamically register logic to fill a particular type with the parsed API structs.
This will be used to parse CAPI manifests generated by our providers (using go templates). The generated structs will be used from the full cluster cluster lifecycle controller.
Ref: https://github.com/aws/eks-anywhere/pull/3432
Unit tests
=> Add generic yaml parser for Kubernetes manifests

pkg/curatedpackages/kubectlrunner.go, pkg/curatedpackages/mocks/kubectlrunner.go, pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go
This adds to InstallController to have it wait until a bundle has been
activated, before returning, and thus indicating that the controller is
"Installed". This help prevent subsequent activity (like package installation)
from failing because the controller isn't yet ready.
Depends on #3513
=> feat(CLI): wait for bundle activation at package controller install

cmd/eksctl-anywhere/cmd/deletecluster.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/workflows/delete.go, pkg/workflows/delete_test.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go
When a workload cluster is deleted, there are package resources on the management cluster that should be cleaned up. These package resources are the PackageBundleController and the Package custom resources. If they are not removed there are several negative consequences:
1) The controller will try to reconcile them to a non-existent cluster
2) If someone created a new cluster of the same name, it would get the configuration from the previous cluster
This change makes deleting these custom resources part of the delete workflow
=> Delete package resources on cluster delete

release/pkg/operations/upload.go
Currently if we are doing a dev release we skip helm chart.yaml fix. 
We should only do the packages chart upload skip if it's not dev release too, otherwise it will fail on dev releases.
=> attempt fix for devrelease helm move

cmd/eksctl-anywhere/cmd/listpackages.go, pkg/curatedpackages/cptabwriter.go, pkg/curatedpackages/cptabwriter_test.go, pkg/curatedpackages/packageclient.go, pkg/curatedpackages/packageclient_test.go
The DisplayPackages function is modified to take an io.Writer into which it'll write. This better conforms with go idioms and makes testing easier.
In the process of doing so, a customized tabwriter is implemented to make working with tabwriter more uniform. Helpers for instantiation and writing a table from a 2-D slice of strings make the code easier to read, and should make changes to the output less error prone (less fiddling with '\t' and other spacings).
For testing, among other things, I did:
```sh
diff <(bin/eksctl-anywhere list packages --source cluster) <(~/bin/eksctl-anywhere list packages --source cluster)
diff <(bin/eksctl-anywhere list packages --source registry --kube-version 1.23)  <(~/bin/eksctl-anywhere list packages --source registry --kube-version 1.23)
```
Which …
=> refactor(CLI): more idiomatic output writing for "list packages"

Makefile
New (or modified) Makefile variables:
COVER_PROFILE - has its default renamed from coverage.html to coverage.out, as it's not HTML, but rather a coverage profile in plain-text.
COVER_HTML - is introduced, which defaults to coverage.html, and will contain the HTML output from the coverage-html target.
New Makefile targets:
coverage - is an alias for coverage-unit-test
coverage-html - will generate HTML output you can view in your browser
coverage-view - will open your browser to view the coverage info
=> feat(Makefile): adds a couple of small coverage based targets

cmd/eksctl-anywhere/cmd/generatepackage.go, cmd/eksctl-anywhere/cmd/installpackages.go, cmd/eksctl-anywhere/cmd/listpackages.go, cmd/eksctl-anywhere/cmd/upgradepackages.go, pkg/curatedpackages/bundle.go, pkg/curatedpackages/bundle_test.go, pkg/curatedpackages/packageclient.go, pkg/curatedpackages/packageclient_test.go
Supporting remote management of packages requires that the user specify the cluster they want to take an action on. The management cluster may be managing packages for several workload clusters. This PR adds support for the list packages, generate packages, install package and upgrade packages commands.
=> Add cluster name to several package commands

pkg/validations/createvalidations/gitops.go, pkg/validations/createvalidations/gitops_test.go
Fix a validation bug introduced in #3517 
When using the deprecated `gitopsConfig`, CLI converts the object to `fluxConfig` and adds it in Spec. We need to skip the fluxConfig validation for this case since it's actually a gitOpsConfig validation that is covered in different method.
Unit tests
=> Fix gitopsConfig validation for workload cluster

release/pkg/assets/config/bundle_release.go, release/pkg/bundles/package-controller.go, release/pkg/constants/constants.go, release/pkg/helm/helm.go, release/pkg/images/images.go
This PR modifies the Tinkerbell chart tagging to follow the format `<gitTag>-latest-helm`.
=> Fix source image format for Tinkerbell chart

release/pkg/assets/config/bundle_release.go, release/pkg/test/testdata/main-bundle-release.yaml
This PR fixes the repository name for the CAPX ECR image.
=> Fix image repo name for CAPX

controllers/resource/reconciler.go, pkg/awsiamauth/awsiamauth.go, pkg/awsiamauth/awsiamauth_test.go, pkg/awsiamauth/config/aws-iam-authenticator.yaml, pkg/awsiamauth/testdata/want-aws-iam-authenticator-upgrade.yaml, pkg/awsiamauth/testdata/want-aws-iam-authenticator.yaml, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/mocks/client_and_networking.go
*Issues #3391 #3560*
Changes include steps in the cluster upgrade workflow to upgrade aws-iam-authenticator components for workload clusters. Also added a check to prevent `eks-a-controller` from reconciling on management for workload cluster spec. 
*Testing:*
```bash
./eksctl-anywhere upgrade cluster -f ./test/test-eks-a-cluster.yaml
./eksctl-anywhere upgrade cluster -f ./test-workload/test-workload-eks-a-cluster.yaml --kubeconfig ./test/test-eks-a-cluster.kubeconfig
```
=> AWS IAM Auth upgrade workload cluster

pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go
- Curated packages will be installing controller only on management clusters: https://github.com/aws/eks-anywhere-packages/blob/main/docs/design/remote-management.md. This is a start to get the management cluster. 
=> Feature remote management

pkg/workflow/task/bootstrap/bootstrap.go, pkg/workflow/workflowcontext/bootstrap.go, pkg/workflow/workflowcontext/contextutil.go, pkg/workflow/workflowcontext/key.go
`contextutil` was too ambiguous for how closely related to workflow execution it is. While `workflowcontext` creates an undesirable directory hierarchy, it provides clarity for consumers when leveraging the behavior it provides.
For example
```go
func foo(ctx context.Context) {
_ = contextutil.BootstrapCluster(ctx) // Not clear its specific to workflows
}
```
```go
func foo(ctx context.Context) {
_ = workflowcontext.BootstrapCluster(ctx) // Clear its specific to workflows
}
```
=> Rename contextutil to workflowcontext

release/pkg/bundles/package-controller.go, release/pkg/bundles/tinkerbell.go, release/pkg/helm/helm.go, release/pkg/operations/upload.go, release/pkg/test/testdata/main-bundle-release.yaml
Due to the way the code is structured, the release code was performing a ECR Public lookup to fetch the image digest even before the modified Helm chart had been pushed. This PR modifies the code to modify and push Helm charts at the same time as other images so we shouldn't see this problem.
=> Push Helm charts along with other image uploads

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go
When EKSA is used to upgrade single-node cluster, there is no MachineDeployment for worker nodes. Thus EKSA is trying to `kubectl apply` empty bytes input.
"error: no objects passed to apply"
Skipping applying empty kube spec.
1. Unit test
2. Manual test with single-node cluster
=> Skipping deploying machine deployment when there is none

release/pkg/operations/upload.go
`strings.Trim`'s second argument is a cutset, so it trims any character in the set if found at the start or end. The method that we want is `strings.TrimSuffix`.
=> Fix trimming of Helm chart asset name

release/pkg/helm/helm.go
Helm push command takes in a tarball and a remote URI as arguments. If the destination repo name has many parts like `foo/bar/baz`, the tarball should be baz.tar.gz while the remote URI would be `oci://registry/foo/bar`. Currently, the release code does not append the prefix to the registry URI, which causes errors.
=> Fix URI argument to helm push command

internal/test/envtest/environment.go, internal/test/kubernetes.go, pkg/clusterapi/controlplane.go, pkg/clusterapi/controlplane_test.go
This allows to represent a provider specific CAPI control plane for both stacked and unstacked etcd. It implements logic to generate new names for immutable objects when these change. It does this by comparing the new spec to the current state of the objects in the cluster.
This is part of a bigger effort, allowing a transition from yaml go templates to go structs. For context: https://github.com/aws/eks-anywhere/pull/3432
Unit tests
=> Add provider CAPI control plane

PROJECT, config/manifest/eksa-components.yaml, config/webhook/manifests.yaml, pkg/api/v1alpha1/vspheremachineconfig.go, pkg/api/v1alpha1/vspheremachineconfig_types.go, pkg/api/v1alpha1/vspheremachineconfig_webhook.go, pkg/api/v1alpha1/vspheremachineconfig_webhook_test.go, pkg/cluster/vsphere.go, pkg/providers/vsphere/defaults.go, pkg/providers/vsphere/validator.go, pkg/providers/vsphere/vsphere.go
This PR adds a mutation webhook to set defaults on vsphere machine configs. This is especially useful when creating clusters using the full lifecycle API via tools like `kubectl apply` or `Gitops`.
=> Add mutation webhook for vsphere machine configs

release/pkg/assets/config/bundle_release.go, release/pkg/test/testdata/main-bundle-release.yaml
EKS-A cluster controller artifacts are being uploaded to a different path now but the release tool is still getting it from the old path where artifacts are not being updated.
=> Update project path for EKS-A cluster controller

PROJECT, config/manifest/eksa-components.yaml, config/webhook/manifests.yaml, pkg/api/v1alpha1/vspheredatacenterconfig_webhook.go, pkg/api/v1alpha1/vspheredatacenterconfig_webhook_test.go
This PR adds a mutation webhook to set defaults on vsphere datacenter configs. This is especially useful when creating clusters using the full lifecycle API via tools like `kubectl apply` or `Gitops`.
=> Add mutation webhook for vsphere datacenter configs

cmd/eksctl-anywhere/cmd/applypackages.go, cmd/eksctl-anywhere/cmd/createpackages.go, cmd/eksctl-anywhere/cmd/deletepackages.go, cmd/eksctl-anywhere/cmd/describepackages.go, cmd/eksctl-anywhere/cmd/generatepackage.go, cmd/eksctl-anywhere/cmd/getpackage.go, cmd/eksctl-anywhere/cmd/getpackagebundle.go, cmd/eksctl-anywhere/cmd/getpackagebundlecontroller.go, cmd/eksctl-anywhere/cmd/installpackages.go, cmd/eksctl-anywhere/cmd/listpackages.go, cmd/eksctl-anywhere/cmd/upgradepackages.go
These two small commits are a precursor to a series of PRs I'll be opening to bring a go-native k8s client to the curated packages CLI commands.
=> go-native client preparations (1 of 6)

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/api/v1alpha1/cluster_webhook_test.go, pkg/providers/vsphere/validator.go, pkg/providers/vsphere/vsphere_test.go
This PR moves some cluster validations from the provider to the Cluster object API. This removes the need to redefine the same validations across providers because they will now happen at he cluster level. These changes also allow us to validate these fields in the controller during cluster reconciliation. These changes are particularly important for the new full lifecycle API that will allow us to also create additional workload clusters managed by an initial EKS-A cluster
=> Move some cluster validations to api

config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, config/manifest/eksa-components.yaml, release/api/v1alpha1/artifacts.go, release/api/v1alpha1/bundle_types.go, release/api/v1alpha1/zz_generated.deepcopy.go, release/config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, release/pkg/assets/config/bundle_release.go, release/pkg/bundles/tinkerbell.go, release/pkg/test/testdata/main-bundle-release.yaml
`cloudflare/cfssl` is no longer used by tinkerbell project. Removing reference from bundle.
=> Removing unused cfssl from bundle

pkg/networking/cilium/templater.go, pkg/networking/cilium/templater_test.go
*Issue #, if available:* On single-node cluster, an extra pod for cilium-operator is scheduled, but it will never run since the cluster has only 1 host.
*Description of changes:* Add replicas = 1 [parameter](https://github.com/cilium/cilium/blob/v1.11.8/install/kubernetes/cilium/values.yaml#L1362) to cilium chart.
1. Unit test
2. Manual e2e test on Dell single-node cluster
=> Remove extra replica of cilium operator on single-node

pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/cloudstack/config/template-cp.yaml, pkg/providers/cloudstack/testdata/expected_results_affinity_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_main_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_main_no_machinetemplate_update_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_main_node_labels_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_main_with_taints_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_minimal_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_minimal_proxy_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_mirror_config_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_resourceids_cp.yaml
Resolves https://github.com/aws/eks-anywhere/issues/3609
Previously we had missed an attribute to pass through from EKS-A to CAPC. This PR enables the pass-through to occur. Without it, clusters would fail to start if only zone name/network name were not specified. If both id and name were specified, we observed a continuous rollingupgrade on the EKS-A manager because the controller expected ID's and names to both be passed through both ways.
Unit tests pass. Manual cluster creation test allowed successful creation of a cluster when zoneId and network id were specified without rolling upgrade.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
=> Passing zone and network ID through to CAPC

cmd/eksctl-anywhere/cmd/generatepackage.go, cmd/eksctl-anywhere/cmd/installpackages.go
The package name is supposed to be specified on the command line as an argument.
Closes: https://github.com/aws/eks-anywhere-packages/issues/491
=> Better package argument error

Makefile, scripts/go-packages-in-patch.sh
Two new Makefile targets:
1. unit-test-patch
Does a little git magic to figure out from the files that've changed
from upstream which go packages have had changes, and then runs only
those unit tests. This is convenient when running the tests
frequently, as in red-green development or for careful refactoring.
2. coverage-view-patch
Like unit-test-patch, but generates and opens in your browser a
coverage report for your changes. This is different from "make
coverage-view" in that it only generates reports for files in the
packages that are modified from upstream. What that means is that you
have far fewer files to sort through to find useful test coverage
information in the report, as it's likely to include only a handful of
files, as opposed to every source file in the repo.
=> feat(Makefile): run unit tests for only modified packages

pkg/providers/tinkerbell/config/template-md.yaml, pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_autoscaler_md.yaml, pkg/providers/tinkerbell/tinkerbell_test.go
Epic: https://github.com/aws/eks-anywhere/issues/3186
Ticket: https://github.com/aws/eks-anywhere/issues/3570
Applies autoscaling annotations to bare metal machine deployments.
Manually tested on a bare metal cluster running kubernetes 1.23.
=> Autoscaling Annotations for Tinkerbell

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/types/resources.go, test/e2e/workload_clusters_test.go, test/framework/cluster.go, test/framework/multicluster.go
Resolves https://github.com/aws/eks-anywhere/issues/3543
The test performs a management cluster upgrade to a newer EKS-A version and checks if the workload cluster also observed a rolling upgrade.
Tested end to end and observed expected rollingupgrade detected. I was able to work around the current nutanix bundles issue by manually applying eks-a components to the mgmt cluster during the mgmt cluster's upgrade.
```
2022-10-06T12:27:13.094-0400	V2	Executing command	{"cmd": "/usr/local/bin/docker exec -i eksa_1665072583805575000 kind delete cluster --name eksa-test-047cdee-eks-a-cluster"}
2022-10-06T12:27:24.380-0400	V0	🎉 Cluster upgraded!
2022-10-06T12:27:24.380-0400	V4	Task finished	{"task_name": …
```
=> Adding new test for detecting workload cluster rollingupgrade

scripts/go-packages-in-patch.sh
My ability to somehow miss these things today is amazing. At least to me.
=> bugfix(Makefile): adds a missing '\'

pkg/awsiamauth/awsiamauth.go, pkg/awsiamauth/awsiamauth_test.go, pkg/awsiamauth/config/aws-iam-authenticator-ca-secret.yaml, pkg/awsiamauth/testdata/want-aws-iam-authenticator-ca-secret.yaml, pkg/clusterapi/identity.go, pkg/clusterapi/identity_test.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/providers/cloudstack/config/template-cp.yaml, pkg/providers/docker/config/template-cp.yaml, pkg/providers/tinkerbell/config/template-cp.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_awsiam.yaml, pkg/providers/vsphere/config/template-cp.yaml, pkg/workflows/create.go, pkg/workflows/create_test.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go
*Issue #2814*
Changes enable setting up `aws-iam-authenticator` on a workload cluster when its not configured on the management cluster.
We now prepend cluster name to the `aws-iam-authenticator-ca` that is needed on the bootstrap/management cluster before adding it on a workload cluster.
*Testing:*
```bash
eksctl-anywhere create cluster -f br-cluster-workload.yaml --kubeconfig ./br/br-eks-a-cluster.kubeconfig
```
=> IAM authenticator only on workload support

pkg/clusterapi/controlplane.go, pkg/clusterapi/controlplane_test.go, pkg/clusterapi/name.go, pkg/clusterapi/name_test.go, pkg/clusterapi/workers.go, pkg/clusterapi/workers_test.go
This allows to represent a provider specific CAPI workers for both. It implements logic to generate new names for immutable objects when these change. It does this by comparing the new spec to the current state of the objects in the cluster.
This is part of a bigger effort, allowing a transition from yaml go templates to go structs. For context: https://github.com/aws/eks-anywhere/pull/3432
Unit tests
=> Add CAPI provider Workers

internal/test/helpers.go, pkg/curatedpackages/kubeclient.go, pkg/curatedpackages/kubeclient_test.go, pkg/kubeconfig/kubeconfig_test.go
This adds functions for creating a go-native kubernetes client to be used by
CLI commands.
The client is not yet used, that will be coming in follow-up commits/PRs. I've
split them up because of their size. This will work as an expand-contract
process[1], where new features like this kubernetes client are added, then
existing code will be modified to use these new features, then the old
solutions for these operations will be removed. Hopefully this will keep the
PR sizes manageable, without leaving the main branch in a broken state.
[1]: https://martinfowler.com/bliki/ParallelChange.html
Depends on #3601
=> feat(CLI): go-native client for CLI commands (2 of 6)

internal/pkg/api/cluster.go, test/framework/registryMirror.go
Added port to the local registry cluster config file for e2e tests. It now creates certificate in the /etc/docker/certs.d file which is needed for baremetal e2e cluster.
=> local registry e2e test change - added port to the cluster config

pkg/api/v1alpha1/vspheremachineconfig.go, pkg/api/v1alpha1/vspheremachineconfig_test.go, pkg/api/v1alpha1/vspheremachineconfig_types.go, pkg/api/v1alpha1/vspheremachineconfig_webhook.go, pkg/api/v1alpha1/vspheremachineconfig_webhook_test.go, pkg/cluster/parse_test.go, pkg/cluster/testdata/cluster_1_19.yaml, pkg/providers/vsphere/validator.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
This PR moves some vsphere machine config validations to the api level. This is especially important for the full lifecycle api to validate the fields during both create and upgrade through the controller
=> Move vsphere machine config validations to api

Makefile
Changed BRANCH_NAME to the new release branch in release-0.12
=> changed BRANCH_NAME to the new release branch in release-0.12

pkg/api/v1alpha1/tinkerbelltemplateconfig_defaults.go, pkg/api/v1alpha1/tinkerbelltemplateconfig_defaults_test.go, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_single_node.yaml
Fixes `metadataUrls` for Bottlerocket for baremetal cluster creation
Currently, we are putting quotes around the metadata URLs (`'http://1.2.3.4:50061'`) because RHEL expects it.
But adding the quotes breaks the metadata url parsing for Bottlerocket. 
With this change, the quotes are conditionally added only to RHEL since that's the only OS that expects it.
=> Fix metadata urls for bottlerocket

scripts/go-packages-in-patch.sh
When git status retrieved info, in some cases, it could include the status of a file, e.g. "added" or "modified". Stripping that off ensures that just the filename is reported and can be matched to the proper Go package for use in the unit-test-patch target (and friends).
=> bugfix: strip status information for proper package id

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_defaults.go, pkg/api/v1alpha1/cluster_defaults_test.go, pkg/api/v1alpha1/cluster_test.go
Additionally, validate that count is within bounds of autoscaling minCount and maxCount, if present
Epic: https://github.com/aws/eks-anywhere/issues/3186
Ticket: https://github.com/aws/eks-anywhere/issues/3582
Allows count to be omitted in worker node configuration when autoscaling configuration is present. Count will default to minCount of autoscaling configuration.
Manually tested creating a cluster with a worker node configuration missing a count value and saw it correctly set to the autoscaling configuration minCount.
=> Autoscaling Config Validations

test/framework/cluster.go
ref: https://github.com/aws/eks-anywhere/pull/3479
before the change
<pre>
2022-10-12T11:02:15.777-0700	V6	Executing command	{"cmd": "/usr/local/bin/docker rm -f -v eksa_1665597120452455000"}
cluster.go:675: Running shell command [ bin/eksctl-anywhere install package hello-eks-anywhere --source=cluster --package-name=test -v=9 --kubeconfig=eksa-test-33c83fb/eksa-test-33c83fb-eks-a-cluster.kubeconfig  ]
2022-10-12T11:02:16.088-0700	V4	Logger init completed	{"vlevel": 9}
Error: required flag(s) "cluster" not set
cluster.go:712: Command bin/eksctl-anywhere [install package hello-eks-anywhere --source=cluster --package-name=test -v=9 --kubeconfig=eksa-test-33c83fb/eksa-test-33c83fb-eks-a-cluster.kubeconfig ] failed …
=> now passing recently made mandatory parameter named cluster

pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/testdata/hardware_nobmc.csv, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go, pkg/providers/tinkerbell/upgrade.go
The changes add a check to only call `kubectl wait` if there are bmcs in the catalogue.
=> Adding check before bmc wait

docs/content/en/docs/getting-started/production-environment/cloudstack-getstarted.md, docs/content/en/docs/reference/cloudstack/_index.md, docs/content/en/docs/reference/cloudstack/cloudstack-preparation.md, docs/content/en/docs/reference/cloudstack/cloudstack-prereq.md, docs/content/en/docs/reference/clusterspec/cloudstack.md
*Issue #, if available:* [#3658](https://github.com/aws/eks-anywhere/issues/3658)
Add placeholder files for CloudStack provider documentation. This allows us to begin adding links to the EKS-A CloudStack docs as those docs are being created, without breaking the docs build process.
=> Add placeholder files for CloudStack docs

pkg/api/v1alpha1/vspheredatacenterconfig_types.go, pkg/api/v1alpha1/vspheredatacenterconfig_webhook.go, pkg/api/v1alpha1/vspheredatacenterconfig_webhook_test.go, pkg/cluster/parse_test.go, pkg/cluster/testdata/cluster_1_19.yaml, pkg/providers/vsphere/vsphere.go
Move vsphere datacenter config validation to api level
=> Validate vsphere datacenter config at api level

.github/workflows/golangci-lint.yml, .golangci.yml, Makefile
* All exported package members need a doc comment
* Doc comments should start with capital letter and end with a period
* Minimum permissions for new created directories and files
* No naked returns
* Avoid method with high cyclomatic complexity. We are starting with a limit of 10, which is the most strict config in the recommended range 10-20. We’ll start here and we’ll make it less restrictive as we go if we see need.
* `revive`: replacement for the deprecated golint. Enabled 3 issues that are disabled by default for exported member comments and file/dir permissions. We used to run `golint`, but then it got deprecated and dropped from golangci-lint. This means we have a bunch of issues in the code we wrote in between then and now. We should try to fix those over time.
* godot: checks …
=> Enable linters: cyclo comp, docs and naked returns

release/pkg/assets/images/images.go, release/pkg/assets/images/images_test.go, release/pkg/images/images.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/util/bundles/bundles.go
If there is no build corresponding to release branches for some project, the release process falls back to sourcing artifacts built from `main`. At that time, it reads the git tag for the project from main, in order to construct the appropriate tag. But this fallback doesn't consider release-branched projects which may have their git tag at a nested folder. This PR fixes that.
=> Construct git tag path properly when falling back to artifacts from main

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/types/resources.go, test/e2e/workload_clusters_test.go, test/framework/cluster.go, test/framework/multicluster.go
This reverts commit 26480c33d215237199b3aa9814995a778f5f1a41.
The commit was causing the build to fail with error
```
test/e2e/workload_clusters_test.go:42:12: undefined: latestMinorRelease
make[1]: *** [e2e-tests-binary] Error 2
```
presumably due to a missing prerequisite change which introduced the `latestMinorRelease` function. This test itself is not necessary for this release branch and can be excluded from the branch.
=> Revert "Adding new test for detecting workload cluster rollingupgrade"

pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/hardware/translate.go
*Issue #, if available:* 
When running `eksctl anywhere create cluster --hardware-csv hardware.csv -f eksa-single-node-cluster.yaml -v` and there is an issue with hardware.csv, it will now tell you that "hardware.csv is not correct" along with the specific problem whereas before it would just say the problem.
=> Invalid hardware.csv message

docs/content/en/docs/reference/baremetal/bare-preparation.md
Using RHEL images for EKS-A bare metal clusters requires that legacy bios be enabled on those machines. This PR adds a note about that to the docs.
=> Added note on RHEL to bare metal docs

go.mod, release/api/v1alpha1/artifacts.go, release/pkg/test/testdata/main-bundle-release.yaml
Nutanix is not added to the release bundle so retrieve it only if it's in the bundle.
This resolves issue with `import-images` where it fails trying to import an empty image
=> Retrieve Nutanix CAPX image only if it is in the bundle

release/pkg/assets/images/images_test.go, release/pkg/helm/helm.go
We were dropping the errors from the Helm pusher's `Run` command, which shouldn't have been the case.
=> Surface errors emitted by Helm push operation

cmd/eksctl-anywhere/cmd/installpackagecontroller.go, pkg/cluster/spec.go
- Remove redundant code from cluster spec
- Check whether controller is installed or not only on self managed clusters.
=> Fix install package controller for workload clusters

config/crd/bases/anywhere.eks.amazonaws.com_vspheredatacenterconfigs.yaml, config/manifest/eksa-components.yaml, docs/content/en/docs/reference/clusterspec/vsphere.md, internal/pkg/api/vsphere.go, pkg/api/v1alpha1/vspheredatacenterconfig_types.go, pkg/api/v1alpha1/vspheredatacenterconfig_webhook.go, pkg/api/v1alpha1/vspheredatacenterconfig_webhook_test.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/executables/kubectl.go, pkg/executables/kubectl_getter_helper_test.go, pkg/executables/kubectl_test.go, pkg/executables/testdata/kubectl_storageclass.json, pkg/providers/nutanix/provider_test.go, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/template.go, pkg/providers/vsphere/testdata/cluster_minimal_disable_csi.yaml, pkg/providers/vsphere/testdata/expected_results_minimal_disable_csi_cp.yaml, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go, test/e2e/vsphere_disable_csi_test.go, test/framework/vspherecsi.go
#3148 
Adding ability to not deploy csi driver for vsphere provider. We are adding a call to `InstallStorageClass` in the upgrade flow as it is easier to just reapply the object even without any changes vs checking to see if we need to apply if it doesn't exist. Due to the limitations of `ClusterResourceSet`, we will have users manually remove the CSI resources for vsphere if they would like to remove it for an existing cluster. 
Most of the code are unit tests and test files along with e2e code, the actual code change is less than 100 lines. Please take a look at the doc changes, the non test files, and the template changes in the vsphere provider package 
Unit tests and manual testing. 
E2E test result:
``` …
```
=> Add option to disable vsphere csi

pkg/providers/tinkerbell/config/template-cp.yaml, pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_single_node_skip_lb.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_single_node_skip_lb.yaml, pkg/providers/tinkerbell/tinkerbell_test.go
*Issue #, if available:* Services can be exposed as LoadBalancer type supported by kube-vip. But in single-node cluster, kube-vip daemonset cannot be deployed correctly as it has to run in controlplane nodes. So we need this adjustment, to let the kube-vip daemonset of cp nodes to handle LoadBalancer services.
1. Unit test
2. Manual tested SkipLoadBalancerDeployment on single-node cluster, when the field is set to false/true
=> Handle kube-vip deployment in single-node cluster

controllers/resource/reconciler_test.go, pkg/api/v1alpha1/fluxconfig_test.go, pkg/api/v1alpha1/vspheredatacenterconfig_webhook_test.go, pkg/aws/creds_test.go, pkg/dependencies/factory_test.go, pkg/eksctl/eksctl_test.go, pkg/executables/cmk_test.go, pkg/executables/flux_test.go, pkg/executables/govc_test.go, pkg/executables/kind_test.go, pkg/features/features_test.go, pkg/git/factory/gitfactory_test.go, pkg/git/providers/github/github_test.go, pkg/networking/cilium/templater_test.go, pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/nutanix/provider_test.go, pkg/providers/snow/snow_test.go, pkg/providers/vsphere/vsphere_test.go, pkg/validations/cluster_test.go, pkg/workflows/upgrade_test.go
A testing cleanup.
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
```go
func TestFoo(t *testing.T) {
// before
key := "ENV"
originalEnv := os.Getenv(key)
if err := os.Setenv(key, "new value"); err != nil {
t.Fatal(err)
}
defer func() {
if err := os.Setenv(key, originalEnv); err != nil {
t.Logf("failed to set env %s back to original value: %v", key, err)
}
}()
// after
t.Setenv(key, "new value")
}
```
=> test: use `T.Setenv` to set env vars in tests

.gitignore, docs/content/en/docs/reference/clusterspec/baremetal.md
Adding docs for `skipLoadBalancerDeployment` changes from this PR https://github.com/aws/eks-anywhere/pull/3608
=> Add docs for `skipLoadBalancerDeployment` for Tinkerbell

controllers/resource/reconciler.go, controllers/resource/reconciler_test.go, controllers/resource/template.go, controllers/resource/testdata/eksa-cluster.yaml, controllers/resource/testdata/eksa-cluster_no_changes.yaml, controllers/resource/testdata/vsphereKubeadmconfigTemplateSpec.yaml, controllers/resource/testdata/vsphereKubeadmcontrolplane.yaml, controllers/resource/testdata/vsphereMachineConfigSpec.yaml, controllers/resource/vsphere.go, controllers/resource/vsphere_wb_test.go, pkg/providers/vsphere/defaults.go, pkg/providers/vsphere/reconciler/reconciler.go, pkg/providers/vsphere/spec.go, pkg/providers/vsphere/template.go, pkg/providers/vsphere/template_test.go, pkg/providers/vsphere/validator.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
While integrating the template builder with the full cluster lifecycle controller, I faced some issues. I started unraveling the code and I ended up with this. It's not perfect by any means but it does simplify the code a little bit and reduces coupling, which makes reusing the template builder easier. 
* This avoids modifying user's API input by moving SSH key normalization to the template builder level as opposed to defaulting. It's a good practice and makes the template builder more reusable, specially from controllers. This is the main behavioral change: if users include the `user@host` comment in the ssh key, this will be kept in the eks-a vsphere machine config and just removed from the vsphere machine template.
* It simplifies template builder by making use of the API structs in …
=> Simplify vsphere templater and ssh key defaults

pkg/constants/constants.go, pkg/executables/executables.go
Now it will show following instead of actual data
<pre>
NUTANIX_USER=***** -e NUTANIX_PASSWORD=*****
</pre>
ran create cluster and observed above
=> redacting the nutanix user and password from log stmts

docs/content/en/docs/reference/cloudstack/cloudstack-prereq.md
*Issue #:* [#3658](https://github.com/aws/eks-anywhere/issues/3658) 
This PR creates the requirements page for creating EKS Anywhere clusters on a CloudStack provider.
Feel free to comment. It's still on hold as I work through a couple of issues.
=> Adding requirements docs for CloudStack provider

cmd/eksctl-anywhere/cmd/downloadimages.go, cmd/eksctl-anywhere/cmd/import.go, cmd/eksctl-anywhere/cmd/import_images.go
Godot was recently turned on as part of our linting. Some sources in the `/cmd` directory violate it with IDEs auto-correcting the mishaps. This commits those auto-corrections.
=> Patch cmd comments to satisfy godot requirements

docs/content/en/docs/reference/artifacts.md
*Issue #* [3658](https://github.com/aws/eks-anywhere/issues/3658)
Added descriptions of how to build RHEL-Based images for use with EKS Anywhere. This will include new descriptions of how to use RHEL-based images with an EKS Anywhere CloudStack provider.
=> Reworked artifacts file to add RHEL image instructions

docs/content/en/docs/reference/artifacts.md
*Issue #: [#3658](https://github.com/aws/eks-anywhere/issues/3658)
Added description of using image-builder to create RHEL-based images to use for EKS Anywhere with a CloudStack provider.
=> Add Cloudstack doc for building RHEL images

test/e2e/awsiam_test.go, test/e2e/conformance_test.go, test/e2e/registry_mirror_test.go, test/e2e/single_node_test.go, test/e2e/tinkerbell_test.go, test/e2e/upgrade_test.go
Add cp timeout on all tinkerbell tests and ensure all tests power off hardware prior to test. This guards against orphaned machines from previous test run that timeout and were left in provisioned state.
=> fix orphaned machines left after timeout of a tinkerbell upgrade test

pkg/cluster/snow.go, pkg/cluster/snow_test.go, pkg/providers/snow/reconciler/reconciler.go, pkg/providers/snow/reconciler/reconciler_test.go
GA AppSec review finding: Potential Memory Violation / NULL Pointer Dereference when specifying a machineRef that does not exist in cluster spec.
Add validation to check all the machine refs point to objs that exist. For controller we requeue and wait till the snow machine config object exists in the cluster.
Unit tests
=> Fix nil pointer when fetching snowmachineconfig that does not exist

docs/content/en/docs/reference/cloudstack/cloudstack-preparation.md
*Issue #*: [#3658](https://github.com/aws/eks-anywhere/issues/3658)
*Description*:
References to two images in the CloudStack Preparation doc were broken. This fixes them.
=> Fix broken image links in docs

docs/content/en/docs/reference/changelog.md
Adding change log for the 0.12 release. 
=> Adding changelog for release-0.12

pkg/providers/snow/reconciler/reconciler.go, pkg/providers/snow/reconciler/reconciler_test.go
Change #3795 
We already check the machine config existence in controller here: https://github.com/aws/eks-anywhere/blob/main/pkg/cluster/snow.go#L157-L160.
=> Remove snow machine objects exist check in controller

pkg/clusterapi/extraargs.go, pkg/clusterapi/extraargs_test.go, pkg/providers/common/auditpolicy.go, pkg/providers/docker/config/template-cp.yaml, pkg/providers/docker/config/template-md.yaml, pkg/providers/docker/docker.go, pkg/providers/docker/docker_test.go, pkg/providers/docker/testdata/capd_valid_full_oidc_cp_expected.yaml, pkg/providers/docker/testdata/capd_valid_full_oidc_md_expected.yaml, pkg/providers/docker/testdata/capd_valid_minimal_oidc_cp_expected.yaml, pkg/providers/docker/testdata/capd_valid_minimal_oidc_md_expected.yaml, pkg/providers/docker/testdata/no_machinetemplate_update_cp_expected.yaml, pkg/providers/docker/testdata/no_machinetemplate_update_md_expected.yaml, pkg/providers/docker/testdata/valid_autoscaler_deployment_md_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_expected_124onwards.yaml, pkg/providers/docker/testdata/valid_deployment_cp_pod_iam_expected.yaml, pkg/providers/docker/testdata/valid_deployment_cp_stacked_etcd_expected.yaml, pkg/providers/docker/testdata/valid_deployment_custom_cidrs_cp_expected.yaml, pkg/providers/docker/testdata/valid_deployment_custom_cidrs_md_expected.yaml, pkg/providers/docker/testdata/valid_deployment_md_expected.yaml, pkg/providers/docker/testdata/valid_deployment_md_expected_124onwards.yaml, pkg/providers/docker/testdata/valid_deployment_md_taints_expected.yaml, pkg/providers/docker/testdata/valid_deployment_multiple_md_taints_expected.yaml, pkg/providers/docker/testdata/valid_deployment_node_labels_cp_expected.yaml, pkg/semver/utils.go, pkg/semver/utils_test.go
Remove cgroup driver arg for docker 1.24 onwards
[Extra reference
](https://github.com/kubernetes-sigs/cluster-api/blob/69ab7870322d4e69eeb5c616299564ba78655ae0/test/e2e/data/infrastructure-docker/v1beta1/v1.2/clusterclass-quick-start.yaml#L92)*Testing (if applicable):*
=> Remove cgroup driver arg for docker 1.24 onwards

pkg/constants/constants.go, pkg/providers/vsphere/controlplane.go, pkg/providers/vsphere/controlplane_test.go
This PR adds the CP object `ControlPlane` and CP builder `ControlPlaneBuilder` for the VSphere provider.
`ControlPlaneBuilder` processes the CP objects from the parsed yaml file, so that we can get those CP objects using the `ControlPlane.Objects()`
Unit tests 
=> Add Vsphere control plane builder

Makefile, scripts/go-packages-in-patch.sh
One quick fix and one quick "feature" for the patch-based Makefile targets I recently added.
The fix is for changes that modify package source files without modifying a _test.go file in the same package---those packages would have been ignored.
The new "feature" is to continue running the Make recipe when there's a test failure, so that the coverage report will still open.
=> Coverage view fix

pkg/dependencies/factory.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
It makes the code easier to follow, given the cluster spec is passed to most methods as an argument. This reduces api structs copies to one, removing ambiguity around which one contains the most updated data. It also avoids bugs where updates are only performed in one place but not the other.
If needed, a stateful version of the provider can be implemented by composing on top of this one.
This also fixes a bug where the controller rolled out new machines immediately after the cluster was created. It was detecting a change in machine configs due to a default not being applied in the cluster spec machine configs. I could have patched that alone and the change would have been smaller, but I decided to do this and avoid these kinds of bugs all together.
* Unit tests
* Upgrade e2e test run …
=> Remove vsphere provider dependency on api structs

docs/content/en/docs/reference/clusterspec/cloudstack.md
Removed trailing slash from symlink path in sample CloudStack cluster spec
=> Fixed sample CloudStack spec

pkg/api/v1alpha1/cloudstackmachineconfig_types.go, pkg/api/v1alpha1/cloudstackmachineconfig_types_test.go, pkg/api/v1alpha1/cloudstackmachineconfig_webhook.go, pkg/providers/cloudstack/validator_test.go
When attempting to create a cluster with some symlinks, we observed failures such as 
```
error when creating \"STDIN\": admission webhook \"validation.cloudstackmachineconfig.anywhere.amazonaws.com\" denied the request: symlinks symlinks:/var/lib/, preventing CloudStackMachineConfig resource creation\n", "retries": 30}
```
which were unclear and confusing. The issue turned out to be that symlinks cannot end with a `/` character
Debugged unit test to observe extended error message
=> Plumbing validation error back to user

docs/content/en/docs/reference/vsphere/customize-ovas.md
*Issue #, if available:*  #3840
Without these changes the hostname would get preserved. Etcd nodes while coming up would not take in the proper names from postkubeadm commands that would result in etcd not coming up properly.
=> Fix customize ubuntu docs to clean the vm properly

pkg/providers/nutanix/template.go, pkg/providers/tinkerbell/assert.go, pkg/providers/tinkerbell/assert_test.go, pkg/providers/tinkerbell/tinkerbell_test.go, pkg/providers/tinkerbell/upgrade.go
The `workerNodeGroupConfiguration.Count` was made an Integer pointer #3624. Adding a fix for places where the pointer was not dereferenced when the value needed to be compared.
=> Worker count pointer dereference fix

docs/content/en/docs/reference/ports.md
The reference should have been to the Kubernetes docs instead of to our own docs.
Fixes #3791.
=> Fix reference to NodePort service docs

pkg/providers/tinkerbell/upgrade.go
Updates some commented out code to treat the WorkerNodeGroupConfiguration.Count field as a pointer rather than an int.
N/A
=> Update Commented Code To Use Count Pointer

docs/content/en/docs/tasks/packages/adot/_index.md, docs/content/en/docs/tasks/packages/cert-manager/_index.md, docs/content/en/docs/tasks/packages/cluster-autoscaler/_index.md, docs/content/en/docs/tasks/packages/emissary/_index.md, docs/content/en/docs/tasks/packages/harbor/_index.md, docs/content/en/docs/tasks/packages/metallb/_index.md, docs/content/en/docs/tasks/packages/metrics-server/_index.md, docs/content/en/docs/tasks/packages/prereq.md
I found the prereqs on every package I bit long winded, so this makes it so the user doesn't have to scroll past as much
=> Pull the prerequisites out of each package task

controllers/resource/reconciler_test.go, controllers/resource/template.go
Avoid overwriting ssh keys for CP and etcd machines since the vsphere template builder is already capable of doing it and runs more robust logic. This was causing new machine rollouts when the specified ssh key had a comment due a difference in kubeadm control plane, etcdadm cluster and vsphere machine templates. The CLI strips them out before creating the vsphere capi objects because it uses the template builder logic.
This was causing some e2e tests to fail due to cluster instability: the controller kept rolling out new machines so the cluster didn't become ready fast enough and the delete operation timed out waiting for it. 
Unit tests and manual e2e tests
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
=> Fix bug in controller vsphere template generator

docs/.htmltest.yml, docs/Makefile, docs/config.toml, docs/content/en/docs/community/_index.md, docs/content/en/docs/concepts/clusterworkflow.md, docs/content/en/docs/getting-started/install/_index.md, docs/content/en/docs/reference/changelog.md, docs/content/en/docs/reference/cloudstack/cloudstack-preparation.md, docs/content/en/docs/reference/clusterspec/optional/autoscaling.md, docs/content/en/docs/reference/clusterspec/vsphere.md, docs/content/en/docs/reference/eksctl/_index.md, docs/content/en/docs/reference/security/kube-bench.md, docs/content/en/docs/reference/support/support-scope.md, docs/content/en/docs/reference/vsphere/vsphere-ovas.md, docs/content/en/docs/tasks/cluster/cluster-scale/baremetal-scale.md, docs/content/en/docs/tasks/cluster/cluster-scale/cloudstack-scale.md, docs/content/en/docs/tasks/cluster/cluster-scale/vsphere-scale.md, docs/content/en/docs/tasks/packages/cluster-autoscaler/_index.md
This PR fixes some of the broken links and references in the docs. It also adds a make target to run `htmltest` CLI to ensure that all the links, images, scripts references work.
Example output for htmltest:
```
docs/reference/changelog/index.html
hash does not exist --- docs/reference/changelog/index.html --> /docs/reference/artifacts/#building-ubuntu-based-node-images
target does not exist --- docs/workshops/provision/prerequistes/index.html --> ../production-environment/
```
=> Fix broken links in docs and add HTML test

pkg/providers/nutanix/template.go, pkg/providers/tinkerbell/assert.go, pkg/providers/tinkerbell/assert_test.go, pkg/providers/tinkerbell/tinkerbell_test.go, pkg/providers/tinkerbell/upgrade.go
* Fixing worker node group count dereference error for tinkerbell
* Fixing worker node group count dereference for nutanix
(cherry picked from commit 91f1ae10d7ba93d91e315812799d38184087a8fe)
=> Worker count pointer dereference fix (#3852)

test/e2e/awsiam_test.go, test/e2e/conformance_test.go, test/e2e/registry_mirror_test.go, test/e2e/tinkerbell_test.go, test/e2e/upgrade_test.go
(cherry picked from commit 48ea520604612441996333e314656a20dd54d18b)
=> fix orphaned machines left after timeout of a tinkerbell upgrade test (#3784)

pkg/clustermanager/cluster_manager.go
Resolves https://github.com/aws/eks-anywhere/issues/3822
As described in the issue above, we're seeing 0-second retries with the current implementation. We're multiplying the retry time by 0 in some instances. This PR changes the retry policy to have a minimum threshold for the retry wait policy
Unit tests succeed
=> Setting minimum wait time for nodes and machinedeployments

docs/content/en/docs/reference/vsphere/vsphere-preparation.md, pkg/config/static/globalPrivs.json
https://github.com/aws/eks-anywhere/issues/3692
Adds a missing ContentLibrary permission.
This permission is required to automatically import a template.
Verified that my user could successfully import images when this permission was added to the globalRole.
=> Add missing ContentLibrary permission to GlobalRole

Makefile
Allows to
```sh
make bundles-override-local-e2e-tests IMAGE_REPO=public.ecr.aws/xxx
```
This will:
1. Build the controller image
2. Push it to your registry
3. Reference that image in a custom bundle in local disk
The bundle will be in `bin/local-bundle-release.yaml` and the custom eksa manifest in `bin/local-eksa-components.yaml`. This is compatible with the e2e test suite, you just need to `export T_BUNDLES_OVERRIDE=true`.
=> Add target to build controller for custom bundle

docs/content/en/docs/getting-started/production-environment/cloudstack-getstarted.md, docs/content/en/docs/getting-started/production-environment/vsphere-getstarted.md
*Issue #, if available:* [#3843](https://github.com/aws/eks-anywhere/issues/3843)
Add step for assigning a support license for workload clusters on a vSphere or CloudStack EKS Anywhere provider.
=> Add license info for workload cluster docs

pkg/curatedpackages/packagereader_test.go, pkg/curatedpackages/reader.go
See https://github.com/aws/eks-anywhere/issues/3881
=> Skip failing curated packages test.

pkg/api/v1alpha1/vspheremachineconfig.go, pkg/api/v1alpha1/vspheremachineconfig_types.go, pkg/api/v1alpha1/vspheremachineconfig_webhook.go, pkg/api/v1alpha1/vspheremachineconfig_webhook_test.go
https://github.com/aws/eks-anywhere/issues/3856
The current controller implementation already skips the codepath that auto-imports a template if it is not present and throws an error if the template cannot be found:
https://github.com/aws/eks-anywhere/blob/6e032751ae1a7b04e94de0c41b34ab275050e053/pkg/providers/vsphere/validator.go#L171-L171
This PR just fails the create webhook if the template field is empty so that the user does not end up in a confusing state.
Manually tested creating a workload cluster on a management cluster by kubectl apply-ing a workload cluster definition file.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
=> Fail VSphereMachineConfig Create Webhook on Missing Template

cmd/eksctl-anywhere/cmd/createcluster.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/docker/docker.go, pkg/providers/mocks/providers.go, pkg/providers/provider.go, pkg/providers/snow/snow.go, pkg/providers/tinkerbell/template.go, pkg/providers/vsphere/hook.go, pkg/providers/vsphere/testdata/TestProviderInstallStorageClass_expect.yaml, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
Dependencies: https://github.com/aws/eks-anywhere/pull/3476
This change removes the `GenerateStorageClass()` from the provider interface and shifts the responsibility of storage class installation to providers. The only provider performing storage class installation is vSphere. A new workflow hook has been written using the same install method that the cluster manager now tests for and calls ensuring existing code paths are unaffected.
The implementation in the cluster manager uses an anonymous interface type assertion to determine if the provider has the necessary behavior for storage class installation. It was written this way acknowledging that the cluster managers storage class installation orchestration will be deleted when we switch to new workflows as the storage class will be …
=> Implement storage class installation hook

.github/workflows/golangci-lint.yml
Both setup-go and golangci-lint actions offer dependency caching capabilities. Using both results in redherring errors that obscure actual linting errors.
https://github.com/aws/eks-anywhere/issues/3897
=> Rely on setup-go action for caching

test/framework/taints.go
Update taints e2e test to add control plane taint for 1.24
- Based on the [changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#no-really-you-must-read-this-before-you-upgrade) from Kubernetes, kubeadm is going to move away from the master taint and only add the control plane taint. The `master` taint will be deprecated from 1.25.
- Run the e2e tests locally for docker
=> Update taints e2e test to add control plane taint for 1.24

internal/test/e2e/registryMirror.go
Tinkerbell registry mirror tests are failing currently because the tests try to mount the ca cert for a different harbor registry resulting in ` x509: certificate signed by unknown authority`
This change ensures the proper registry cert is mounted for Tinkerbell tests to avoid this issue.
=> Fix registry mirror tests for tinkerbell

pkg/providers/nutanix/provider.go, pkg/providers/nutanix/provider_test.go
This PR returns appropriate ChangeDiff to help decide if upgrade is required for CAPX
<pre>
bin/eksctl-anywhere upgrade plan cluster -f nutanix-dev-cluster.yaml
Checking new release availability...
NAME      CURRENT VERSION                 NEXT VERSION
EKS-A     v0.0.0-dev+build.4610+08d8345   v0.0.0-dev+build.4615+bf67b82
</pre>
TODO for testing, yet to figure out how to have the new spec deployed
=> added upgradeclusterplan support for nutanix provider capx

pkg/diagnostics/collectors.go, pkg/diagnostics/collectors_test.go
<pre>
bin/eksctl-anywhere generate support-bundle-config -f nutanix-dev-cluster.yaml
</pre>
show output with following contents 
<pre>
collectors:
- logs:
name: logs/capx-system
namespace: capx-system
selector: null
- runPod:
collectorName: nutanixclusters.infrastructure.cluster.x-k8s.io
name: crds/nutanixclusters.infrastructure.cluster.x-k8s.io
namespace: eksa-diagnostics
podSpec:
containers:
- args:
- get
- nutanixclusters.infrastructure.cluster.x-k8s.io
- -o
- json
- --all-namespaces
command:
- kubectl
image: public.ecr.aws/l0g8r8j6/eks-anywhere-diagnostic-collector:v0.12.0-eks-a-v0.0.0-dev-build.4603
name: crds/nutanixclusters.infrastructure.cluster.x-k8s.io
resources: {}
hostNetwork: true
tolerations:
- …
=> now collecting capx logs in support-bundle

pkg/clusterapi/controlplane.go, pkg/clusterapi/controlplane_test.go
When changes are detected in the provider machine templates for the control plane or etcdadm cluster, we generate a new name because these objects are immutable. If that happens, we also need to update their corresponding references in the KubeadmControlPlane and EtcdadmCluster or new machines will be never be rolled out. 
=> Update CP infra machine template names if changes

pkg/clusterapi/controlplane.go, pkg/clusterapi/controlplane_test.go, pkg/clusterapi/name.go, pkg/clusterapi/workers.go, pkg/clusterapi/workers_test.go, pkg/clusterapi/yaml/controlplane.go, pkg/clusterapi/yaml/workers.go, pkg/providers/vsphere/controlplane_test.go, pkg/providers/vsphere/template.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/workers.go, pkg/providers/vsphere/workers_test.go
Part of the cluster lifecycle project. Generate CAPI spec in yaml with the vsphere template builder and parse it into api structs. Generate new immutable changes if a difference is detected (upgrades).
=> Add vSphere workers CAPI spec generator

pkg/clusterapi/name.go, pkg/clusterapi/name_test.go, pkg/constants/constants.go, pkg/providers/snow/objects.go, pkg/providers/vsphere/controlplane.go, pkg/providers/vsphere/controlplane_test.go
Builds VSphere control plane spec by generating the control plane yaml and parsing that yaml to obtain the CP objects
=> Build Vsphere CP spec to directly access CP objects

.github/workflows/go-coverage.yml, .github/workflows/golangci-lint.yml
checkout@v2 is using node.js 12, which is deprecated.
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
=> Update actions to checkout@v3

docs/content/en/docs/tasks/packages/_index.md
Following the example on how to login to ECR with docker does not work:
```
You must specify a region. You can also configure your region by running "aws configure".
```
It is also important to use the proper region:
```
Error response from daemon: login attempt to https://783794618700.dkr.ecr.us-west-2.amazonaws.com/v2/ failed with status: 400 Bad Request
```
The solution is to use the same region where the registry resides:
```
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Login Succeeded
```
The proposed PR adds this to the documentation.
By submitting this pull request, I confirm that you can …
=> docs: add us-west-2 region to the "aws ecr get-login-password" command in curated packages docs

pkg/executables/clusterctl_test.go, pkg/executables/testdata/clusterctl_expected.yaml, release/pkg/test/testdata/main-bundle-release.yaml
Upgrade to latest capx version with delete cluster fixes
Depends on https://github.com/aws/eks-anywhere-build-tooling/pull/1513
=> use latest nutanix capx release version

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/mocks/client.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go
Currently a user can only create a management cluster for the provider Tinkerbell. This PR will add creating workload cluster from management cluster functionality for Tinkerbell. 
=> Create workload cluster from management cluster for baremetal

pkg/clusterapi/workers.go, pkg/clusterapi/workers_test.go, pkg/providers/vsphere/reconciler/reconciler.go, pkg/providers/vsphere/reconciler/reconciler_test.go
https://github.com/aws/eks-anywhere/issues/3916
Makes API call to reconcile CAPI worker objects.
Unit test
=> Add worker reconciliation call and test

docs/content/en/docs/tasks/packages/_index.md
Some commands in the docs of curated packages does not work anymore with v0.12
```
v0.12.1
Error: unknown flag: --source
Error: required flag(s) "cluster" not set
```
The proper commands are:
```
Package			Version(s)							
-------			----------							
hello-eks-anywhere	0.1.2-a6847010915747a9fc8a412b233a2b1ee608ae76			
adot			0.21.1-971c31238aeea5f1bda6ec95caaf24993b304157			
cert-manager		1.9.1-dc0c845b5f71bea6869efccd3ca3f2dd11b5c95f			
cluster-autoscaler	9.21.0-1.23-5516c0368ff74d14c328d61fe374da9787ecf437		
harbor			2.5.1-0d4e0476a740b48a232041597ded2031595d9409			
metallb			0.13.5-0c9bc01066c2b8e8006c60d09f55015501ad2fc2			
metallb-crds		0.13.5-0c9bc01066c2b8e8006c60d09f55015501ad2fc2			
metrics-server …
```
=> docs: update command examples in curated packages docs to work with v0.12

.golangci.yml
The capital letter linting rule in the godot linter doesn't consider parameter names. A common convention when documenting APIs is to reference parameter names including with the first word for a sentence.
=> Disable capital letter for first word linting rule

test/framework/cluster.go
E2E test for packages timing out, increasing timeout for all waits to 5 mins.
=> Increasing packages e2e test timeouts

cmd/eksctl-anywhere/cmd/createcluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/dependencies/factory.go, pkg/validations/cluster.go, pkg/validations/cluster_test.go
Moved registry validation from api/v1alpha1/cluster.go to createcluster.go
Tested manually to check that it works
=> Fix registry-auth validation

pkg/awsiamauth/config/aws-iam-authenticator.yaml, pkg/awsiamauth/template.go
Since 1.24 Kubernetes added the control-plane taint to the control plane nodes along with the master taint, so added the toleration accordingly for aws iam auth daemonsets.
=> Add control-plane toleration for aws iam auth for 1.24

pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go
- Don't create cronjob if credentials are not provided for curated packages controller installation
=> Refactor credential creation

pkg/cluster/build.go, pkg/cluster/docker.go, pkg/cluster/docker_test.go, pkg/providers/vsphere/reconciler/reconciler_test.go
Add client processor for docker datacenter config and register it in the default Config Client Builder.
- unit test
=> Add client processor for docker datacenter config

docs/content/en/docs/reference/vsphere/vsphere-preparation.md
Fixes a typo in permissions docs.
=> Fix Permissions Doc Typo

pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go, pkg/curatedpackages/testdata/awssecret_test_empty.yaml
If the AWS secret key is NOT set, do not enable the cron job or run the one-off job.
=> Enable cron job if credentials

internal/test/envtest/environment.go, manager/main.go, pkg/providers/vsphere/controlplane.go, pkg/providers/vsphere/reconciler/reconciler.go, pkg/providers/vsphere/reconciler/reconciler_test.go
Issue #3917 
Implement the ProviderClusterReconciler interface: ControlPlane reconciliation
unit test
=> Reconcile control plane in vsphere

internal/test/envtest/client.go, internal/test/envtest/crd.go, internal/test/envtest/environment.go, pkg/controller/clientutil/annotations.go, pkg/controller/clientutil/annotations_test.go, pkg/controller/clusters/controlplane.go, pkg/controller/clusters/controlplane_test.go, pkg/controller/clusters/main_test.go, pkg/providers/vsphere/reconciler/reconciler.go, pkg/providers/vsphere/reconciler/reconciler_test.go
When using a control plane with external etcd, upgrades can't be done by just applying al changes, and depending on the changes, it needs to be orchestrated through annotations.
Marking the etcdadm cluster as upgrading, signals the kcp to not react
to changes in the etcd endpoints until the annotation is removed. This
will be done by the etcdadm cluster controller once the rolling upgrade
is finished.
Pausing the kcp reconciliation avoids having a unnecessary rolling
upgrade of the control plane when there are both cp and etcd changes
(for example, a k8s version upgrade). The CAPI cluster controller will
remove the pause annotation once the etcdadm cluster becomes ready.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
=> Add custom logic to reconcile a CAPI control plane

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/api/v1alpha1/testdata/tinkerbell_121cluster_without_worker_nodes.yaml
*Issue #, if available:* Empty worker nodes doesn't work with kube version <= 1.21, due to the limitation of cluster-api
*Description of changes:* Add kube version check when worker nodes is empty
*Testing (if applicable):* unit test
=> Validate kube version when creating cluster without worker nodes

.github/workflows/golangci-lint.yml
The golangci-lint-action has a history of being slow. We've observed the tool timeout on several occasions now and its possibly due to a defecft in the action.
https://github.com/golangci/golangci-lint-action/issues/297
=> Increase lint timeout from 5m to 10m

release/scripts/github-bundle-release.sh
* Actually invoke yq command to get EKS-A CLI tarball URI.
* Fix source manifest for imagebuilder CLI tarball URI.
=> Fix yq command in Github release script

internal/pkg/ec2/terminate.go, internal/pkg/ec2/terminate_test.go
The AWS API has a limit of a 1000 instances per request. If the cleanup job fails to run a couple times, the accumulated instances number can exceed this limit. The API docs recommend to split this into even smaller chunks, so going with 500 for now.
=> Split instances in chunks for termination

pkg/executables/cmk.go, pkg/executables/cmk_test.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/cloudstack/mocks/client.go, pkg/providers/cloudstack/validator.go, pkg/providers/cloudstack/validator_mocks.go, pkg/providers/cloudstack/validator_registry.go, pkg/providers/cloudstack/validator_test.go
E2e tests fail with slow call to `cmk sync`. From the [cmk docs](https://cwiki.apache.org/confluence/display/CLOUDSTACK/CloudStack+cloudmonkey+CLI): 
> The sync command in cloudmonkey pull a list of apis which are accessible to your user role, along with help docs etc. and stores the cache in ~/.cloudmonkey/cache
We do not need this functionality in EKS-A since we are not using cloudmonkey interactively in a CLI. It also pulls an enormous amount of data and tends to be slow. Lastly, the data we get from this call in case of failure is the same as we would get from any other cloudmonkey query failure, so it's not explicitly needed. It was also recently removed in CAPC due to enormous resource consumption
E2E test …
=> Removing initial slow cloudmonkey call to verify connection to cloudstack

controllers/factory.go
We were not building the CNI reconciler before, causing nil pointer accesses.
Manual
=> Build CNIReconciler with vSphere reconciler

pkg/clusterapi/apibuilder.go, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/controlplane_test.go, pkg/providers/vsphere/testdata/expected_results_bottlerocket_external_etcd_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_custom_resolv_conf.yaml, pkg/providers/vsphere/testdata/expected_results_main_121_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp_cloud_provder_and_csi_driver_credentials.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp_cloud_provider_credentials.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp_csi_driver_credentials.yaml, pkg/providers/vsphere/testdata/expected_results_main_no_machinetemplate_update_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_node_labels_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_with_taints_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_with_auth_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_pod_iam_config.yaml
The controller needs the namespace ref to be set correctly to lookup the etcd cluster for reconciliation.
Manual. I can add a unit test.
=> Set eksa-system namespace in etcd cluster object ref

test/e2e/tools/eks-anywhere-test-tool/pkg/filewriter/writer.go
The test log fetcher tool currently doesn't fetch Tinkerbell logs because the filename is too big.
This change clips the filename so the logs can be fetched properly for failed Tinkerbell tests.
=> Fix fetch logs for Tinkerbell failed tests

pkg/providers/vsphere/controlplane_test.go, pkg/providers/vsphere/machinetemplate.go, pkg/providers/vsphere/workers_test.go
When looking for changes in immutable objects, we only care about the spec field. Any other change is allowed and doesn't require a new name. If we don't do it, we create a new machine template on every single reconciliation loop, which trigger an infinite rollout of new machines.
Unit tests and manual testing with tilt by @jonathanmeier5 and @mitalipaygude 
=> Fix vsphere machine template equal compare

release/scripts/github-bundle-release.sh
Allow overriding of date in Github bundle release
=> Allow overriding date in Github bundle release

test/e2e/tools/eks-anywhere-test-tool/pkg/artifacts/artifactFetcher.go
Fixing the e2e tests fetch artifacts. Was failing with an index error.
=> Fixing e2e tests artifacts download

pkg/executables/cmk_test.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/cloudstack/mocks/client.go, pkg/providers/cloudstack/validator.go, pkg/providers/cloudstack/validator_test.go
Manually cherrypick changes from #4016 into release branch to unblock e2e tests
=> [release-0.12] Removing initial slow cloudmonkey call to verify connection to cloudstack

test/e2e/tools/eks-anywhere-test-tool/cmd/fetchartifacts.go, test/e2e/tools/eks-anywhere-test-tool/pkg/fileutils/fileutils.go, test/e2e/tools/eks-anywhere-test-tool/pkg/filewriter/writer.go, test/e2e/tools/eks-anywhere-test-tool/pkg/logfetcher/logfetcher.go, test/e2e/tools/eks-anywhere-test-tool/pkg/logfetcher/testswriter.go, test/e2e/tools/eks-anywhere-test-tool/pkg/providerProxy/logFetcher.go, test/e2e/tools/eks-anywhere-test-tool/pkg/providerProxy/requestWriter.go
- Don't make output directories until a file is written
This prevents useless and empty directories from being created when there's a usage error or something.
- Change colons to underscores in directory names
Just a small quality of life improvement. Most terminals, by default, will recognize a colon as a word-stop, and so double-clicking will select to the colon but no further. Changing to underscore lets a nice double-click select the whole directory.
https://user-images.githubusercontent.com/169516/201174235-0a39a057-6c8a-43c6-ba3a-89d74fc174f8.mp4
=> minor rework for eks-a-test-tool

pkg/providers/vsphere/reconciler/reconciler_test.go
[Follow up testing on other CAPI objects](https://github.com/aws/eks-anywhere/pull/3950#discussion_r1016876099)
=> Ensure CAPI objects are created during tests

docs/content/en/docs/reference/vsphere/vsphere-preparation.md
Clients can specify `Cluster/Resources` for the cluster config file, but for some reason govc will not assign permissions on this object.
Instead, for user.yaml, users need to just specify `Cluster`.
Manually validated.
=> Clarify ResourcePool Documentation

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, pkg/executables/govc.go, pkg/executables/govc_test.go, pkg/providers/vsphere/defaults.go, pkg/providers/vsphere/internal/templates/factory.go, pkg/providers/vsphere/internal/templates/factory_test.go, pkg/providers/vsphere/internal/templates/mocks/govc.go, pkg/providers/vsphere/mocks/client.go, pkg/providers/vsphere/validator.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go, test/e2e/awsiam_test.go, test/e2e/flux_test.go, test/e2e/oidc_test.go, test/e2e/upgrade_from_latest_test.go, test/e2e/upgrade_test.go, test/e2e/workload_clusters_test.go, test/framework/releaseVersions.go, test/framework/vsphere.go
Due to the the speed at which we bump eks-d versions, template config gets out of sync frequently. This makes the E2E tests fail. The solution is easy, updating the config with the new templates and importing if they are haven't been yet. However, due to the lenght of a full suite run, it takes up to a full day to get feedback on the fix.
This PRs introduces extra logic to try to select the right template even if the configuration is missing while still accepting explicit config to override the defaults. It follows these steps:
1. Look for explicit configuration through an env var: "T_VSPHERE_TEMPLATE_{osFamily}_{eks-d version}".
This should be used for explicit configuration, mostly in local development for overrides.
2. If not present, look for a template if the default templates …
=> Improve E2E vSphere template selection logic

pkg/clients/kubernetes/scheme.go, pkg/providers/docker/controlplane.go, pkg/providers/docker/controlplane_test.go, pkg/providers/docker/machinetemplate.go, pkg/providers/docker/machinetemplate_test.go
Added functionality to build Docker Control Plane(CP) Spec by generating the CP yaml and parsing that to obtain the corresponding objects
=> Add Docker ControlPlaneSpec to generate capi objects

cmd/eksctl-anywhere/cmd/downloadimages.go, cmd/eksctl-anywhere/cmd/import_images.go, release/api/v1alpha1/artifacts.go
- Fetch curated packages bundle by default since it is needed by package controller to function properly.
=> Download and import curated packages package bundle by default

docs/content/en/docs/tasks/cluster/cluster-upgrades/baremetal-upgrades.md
The command for upgrade does not take in `--kubeconfig` for management cluster upgrades.
=> Removing --kubeconfig reference from upgrade docs for tinkerbell

internal/test/e2e/nutanix.go, internal/test/e2e/setup.go, test/framework/nutanix.go
Pass the required Nutanix env vars to the test runner instances 
=> Pass Nutanix env var to test runners

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, test/framework/vsphere.go
The new name fits the prefix for templates, so it will get passed to the test instances if it's present in the host running the test runner binary.
=> Rename e2e env var to pass it to test instances

release/Makefile, release/buildspecs/release-announce.yml, release/pkg/test/testdata/main-bundle-release.yaml, release/scripts/announce_eksa_release.sh
Add script to publish a release notification to the `eks-anywhere-updates` SNS topic after an EKS-A release.
=> Publish SNS message for EKS-A releases

docs/content/en/docs/reference/changelog.md, pkg/features/features.go, pkg/features/features_test.go, pkg/validations/cluster.go, pkg/validations/cluster_test.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations.go, test/e2e/awsiam_test.go, test/e2e/conformance_test.go, test/e2e/curated_packages_test.go, test/e2e/flux_test.go, test/e2e/labels_test.go, test/e2e/multiple_worker_node_groups_test.go, test/e2e/oidc_test.go, test/e2e/proxy_test.go, test/e2e/registry_mirror_test.go, test/e2e/simpleflow_test.go, test/e2e/single_node_test.go, test/e2e/stackedetcd_test.go, test/e2e/taints_test.go, test/e2e/tinkerbell_test.go, test/e2e/upgrade_from_latest_test.go, test/e2e/upgrade_test.go, test/e2e/vsphere_autoimport_test.go, test/e2e/vsphere_disable_csi_test.go
#3491 
[Remove feature flag for 1.24](https://github.com/aws/eks-anywhere/commit/c440dda22f8d5380b6976261cd10eb486a990f68)
- make
- make e2e
=> Remove feature flag for 1.24

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go
#3491 
Update default kube version to 1.24
=> Update default kube version to 1.24

test/e2e/conformance_test.go
Output: before fix
<pre>
Using standard BUNDLE_MANIFEST_URL https://dev-release-assets.eks-anywhere.model-rocket.aws.dev/bundle-release.yaml and RELEASE_MANIFEST_URL https://dev-release-assets.eks-anywhere.model-rocket.aws.dev/eks-a-release.yaml fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
/Library/Developer/CommandLineTools/usr/bin/make e2e-tests-binary E2E_TAGS=conformance_e2e Using standard BUNDLE_MANIFEST_URL https://dev-release-assets.eks-anywhere.model-rocket.aws.dev/bundle-release.yaml and RELEASE_MANIFEST_URL https://dev-release-assets.eks-anywhere.model-rocket.aws.dev/eks-a-release.yaml fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
GOOS=darwin GOARCH=amd64 /usr/local/bin/go …
=> fixed the test build failure

internal/test/e2e/nutanix.go, internal/test/e2e/run.go, internal/test/e2e/vsphere.go, test/framework/network.go
Nutanix tests are currently failing because it doesn't have an IP pool 
This PR reserves the IP pool for Nutanix tests
=> Reserve IP pool for Nutanix tests

internal/test/e2e/awsiam.go, internal/test/e2e/cloudstack.go, internal/test/e2e/flux.go, internal/test/e2e/fluxGit.go, internal/test/e2e/nutanix.go, internal/test/e2e/oidc.go, internal/test/e2e/packages.go, internal/test/e2e/proxy.go, internal/test/e2e/registryMirror.go, internal/test/e2e/tinkerbell.go, internal/test/e2e/vsphere.go
There are certain logs of the form `Not running X tests, skipping Env variable setup` that get printed for every test that doesn't match the test regex. These logs aren't very meaningful and mostly just spam the logs
In the most recent e2e test run, there were `1612` instances of these logs
```
$ cat 2022-11-15T23_39_14-08_00-logs/codebuild-log.txt| grep "Not running" | wc -l
1612
```
This PR removes these logs
=> Remove unnecessary logging in e2e tests

pkg/providers/snow/reconciler/reconciler.go, pkg/providers/snow/reconciler/reconciler_test.go, pkg/providers/vsphere/reconciler/reconciler.go, pkg/providers/vsphere/reconciler/reconciler_test.go
If datacenter or machine configs are invalid for a cluster, reconciliation should stop to prevent any further changes.
When the failure message is not set, it's safe for us to assume the object hasn't been validated yet but still might be valid. In this case, we shouldn't bubble an error to the cluster status and just return and wait for the object to updated, either to be valid or to have a failure message.
=> Stop reconciliation if child objects are invalid

cmd/integration_test/build/buildspecs/conformance-eks-a-cli.yml, cmd/integration_test/build/buildspecs/test-eks-a-cli.yml
Set Nutanix memory and disk size as vars instead of pulling from secrets manager
=> Set Nutanix memory and disk size as vars

pkg/providers/tinkerbell/config/template-cp.yaml, pkg/providers/tinkerbell/config/template-md.yaml, pkg/providers/tinkerbell/stack/mocks/stack.go, pkg/providers/tinkerbell/stack/stack.go, pkg/providers/tinkerbell/stack/stack_test.go, pkg/providers/tinkerbell/stack/testdata/expected_with_registry_mirror.yaml, pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_registry_mirror_with_auth.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_registry_mirror_with_auth.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md_registry_mirror_with_auth.yaml, pkg/providers/tinkerbell/tinkerbell_test.go
#3349
Added registry auth support for tinkerbell
created baremetal cluster using private registry
=> Add authenticated registry mirror support for tinkerbell

.github/workflows/stale-issue-mgr.yaml
Add GH workflow to mark and auto close stale issues. Can easily be extended to apply to PRs as well
Tested on my fork and works as expected 
=> Add stale issue manager to GH actions

cmd/integration_test/build/buildspecs/test-eks-a-cli.yml
From previous changes, leftover VM's from e2e tests in CloudStack are already being cleaned up at the single test level. We do not need this suite-level cleanup as well. It also doesn't work in our CI environment due to networking issues between the build machines and the CloudStack environment, so to avoid further confusion it's being removed.
=> Removing postbuild to cleanup CloudStack resources

pkg/clusterapi/workers.go, pkg/providers/docker/controlplane_test.go, pkg/providers/docker/docker.go, pkg/providers/docker/workers.go, pkg/providers/docker/workers_test.go, pkg/providers/vsphere/workers_test.go
Add docker workers CAPI spec generator
=> Add docker workers CAPI spec generator

test/e2e/curated_packages_test.go
Adding the following test for packages E2E
1. TestCPackagesDockerUbuntuKubernetes123SimpleFlow
2. TestCPackagesVSphereKubernetes123SimpleFlow
3. TestCPackagesVSphereKubernetes123BottleRocketSimpleFlow
4. TestCPackagesVSphereKubernetes123UbuntuWorkloadCluster
5. TestCPackagesVSphereKubernetes123BottleRocketWorkloadCluster
=> Adding Packages E2E test for k8s 1.23

pkg/providers/nutanix/provider.go, pkg/providers/nutanix/provider_test.go
Move Nutanix UpdateSecrets call to GenerateCAPISpec functions so it gets applied for both management and workload cluster creation/upgrade
Created/Upgraded management cluster
Created/Upgraded workload cluster
=> Move Nutanix UpdateSecrets call to GenerateCAPISpec

docs/content/en/docs/reference/artifacts.md
Instead of pointing to a static version of the image-builder CLI, this instructs users to fetch the latest weekly development build of the image-builder tarball.
=> Ensure users download latest version of imagebuilder CLI for building node images

docs/content/en/docs/tasks/troubleshoot/packages.md
Updating doc to add command for un-suspending the cronjob in cases of forgotten credentials.
=> Update packages troubleshooting doc to re-enable cronjob

internal/test/envtest/client.go, internal/test/envtest/client_test.go, internal/test/testdata.go, pkg/providers/snow/reconciler/reconciler.go
If we don't wait for the subresource to be updated, there can be race conditions where the status still has the default value when reading from the cache. If the tests rely on the status to be updated to spec, this could cause flakiness.
=> Wait until status is refreshed in cache in envtest

.github/workflows/stale-labeler.yaml, .github/workflows/stale-mgr.yaml
Makes some changes to the stale labeler after talking with @drewvanstone :
* Toggles off labeler for PRs but puts a few values in place for if we turn it on. 
* Renames the file to be more general
* Checks against issues already labeled with `status/needinfo` and `priority/p2` only, instead of `external`
Tested on my fork
=> Update stale labeler with new requirements

pkg/curatedpackages/packagecontrollerclient.go
=> Add some extra messaging when secret creation fails

.gitignore
Adding a gitignore on files downloaded by e2e tool.
=> Adding artifacts and logs generated by e2e tool to gitignore

cmd/eksctl-anywhere/cmd/constants.go, cmd/eksctl-anywhere/cmd/options.go, pkg/clusterapi/machine_health_check.go, pkg/clusterapi/machine_health_check_test.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go
Before this change, an unhealthy machine health check would timeout after five minutes. This leads to an endless loop for a RolingUpgrade on a slow system. Disabling the health checks circumvents this issue, but is not ideal. This change adds a flag `--unhealthy-machine-timeout` which customers can use to make the upgrade process more reliable without sacrificing health checks.
*Issue #, if available:*  Resolves https://github.com/aws/eks-anywhere/issues/3918
*Description of changes:* Allow users to override the default unhealthy machine condition timeout using an `--unhealthy-machine-timeout` flag
Created unit tests for the scenarios:
1. No environmental variable sets the timeout to the default value
2. Invalid environmental variable (e.g negatives, NaNs, …
=> Add flag to set machine health check timeout (#3918)

pkg/collection/set.go, pkg/collection/set_test.go, pkg/controller/clusters/workers.go, pkg/controller/clusters/workers_test.go, pkg/providers/snow/objects.go, pkg/providers/snow/objects_test.go, pkg/providers/snow/reconciler/reconciler.go, pkg/providers/snow/reconciler/reconciler_test.go, pkg/providers/snow/testdata/expected_results_main_md.yaml, pkg/providers/vsphere/reconciler/reconciler.go, pkg/providers/vsphere/reconciler/reconciler_test.go
Fixes a bug where machines didn't get deleted when removing worker node groups from the eks-a cluster object.
Unite tests and manual e2e with tilt
=> Delete unwanted MachineDeployments in reconcile

pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_types_test.go, pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go, pkg/networking/cilium/client.go, pkg/networking/cilium/installation.go, pkg/networking/cilium/reconciler/fetch.go, pkg/networking/cilium/reconciler/reconciler.go, pkg/networking/cilium/reconciler/reconciler_test.go, pkg/networking/cilium/upgrade_plan.go, pkg/networking/cilium/upgrade_plan_test.go
https://github.com/aws/eks-anywhere/issues/4089
Before this, the reconciler only reacted to changes in the Cilium
version specified in the Bundles. Now it will detect changes in the
Cilium config as well and reapply the manifest without going through the
version upgrade process.
Manual and unit test
=> Reconcile Cilium Enforcement Policy

pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go
We now allow users to update worker node configs for the self-managed clusters through the controller, so we can remove this check
Unit tests + upgraded self-managed Docker cluster (scaled nodes up/down  + added a new wn group) using `kubectl apply` 
=> Remove old check to prevent self-managed cluster upgrades with controller

internal/test/kubevip.go, pkg/clusterapi/apibuilder_test.go, pkg/clusterapi/bottlerocket.go, pkg/clusterapi/bottlerocket_test.go, pkg/clusterapi/kubevip.go, pkg/clusterapi/kubevip_test.go, pkg/clusterapi/proxy.go, pkg/clusterapi/proxy_test.go, pkg/clusterapi/registry_mirror.go, pkg/clusterapi/registry_mirror_test.go, pkg/clusterapi/systemctl.go, pkg/clusterapi/systemctl_test.go, pkg/providers/snow/apibuilder.go, pkg/providers/snow/apibuilder_test.go, pkg/providers/snow/objects.go, pkg/providers/snow/objects_test.go, pkg/providers/snow/reconciler/reconciler.go, pkg/providers/snow/snow.go, pkg/providers/snow/snow_test.go, pkg/providers/snow/testdata/expected_results_main_cp.yaml
#4050 
Add bottlerocket support for Snow
- move kube-vip pod manifest to user data
- update proxy, registry mirror config option for BR
Unit tests
=> Support bottlerocket OS for snow provider

pkg/api/v1alpha1/cluster_webhook_test.go, pkg/clustermanager/cluster_manager_test.go, pkg/providers/snow/clientregistry_test.go
Some tests are assuming the values of environment variables when they're run, instead of setting them to known values first. This can cause test failures when running in environments where those variables are already set to different values than expected.
=> Don't assume env vars when running tests

pkg/providers/tinkerbell/tinkerbell_test.go, pkg/providers/tinkerbell/upgrade.go, test/e2e/workload_clusters_test.go, test/framework/cluster.go, test/framework/multicluster.go
Added workload cluster upgrade functionality for Tinkerbell. Added e2e tests for workload cluster create and upgrade functionality.
--- PASS: TestTinkerbellKubernetes122BottlerocketWorkloadCluster
--- PASS: TestTinkerbellKubernetes122UbuntuWorkloadCluster
--- PASS: TestTinkerbellUpgradeMulticlusterWorkloadClusterWorkerScaleup
--- PASS: TestTinkerbellUpgradeMulticlusterWorkloadClusterK8sUpgrade
=> Added workload cluster upgrade functionality for tinkerbell

go.mod, go.sum, pkg/clusterapi/apibuilder_test.go, pkg/clusterapi/bottlerocket.go, pkg/clusterapi/bottlerocket_test.go, pkg/providers/snow/apibuilder.go, pkg/providers/snow/apibuilder_test.go, pkg/providers/snow/bottlerocket.go, pkg/providers/snow/snow_test.go, pkg/providers/snow/testdata/expected_results_main_cp.yaml, pkg/providers/snow/testdata/expected_results_main_md.yaml
#4050 
Base on #4208 
- Override default BR admin, control container images URL
- Add bottlerocket-bootstrap-snow to custom bootstrap container image
Hold till #4208 is merged first.
=> Add snow specific Bottlerocket settings: admin, control, bootstrap snow containers

test/e2e/workload_clusters_test.go
*Issue #, if available:* 
*Description of changes:* Add e2e test for creating ubuntu/bottlerocket single-node workload clusters
*Testing (if applicable):* Manually tested creating ubuntu single-node workload cluster with "eks-a" command.
=> Add e2e test for creating single-node workload cluster

test/e2e/emissary_test.go
This function was trying to spin up two bootstrap clusters during the flow, and caused failures.
```
func runCuratedPackageEmissaryInstallAdvancedFlow(test *framework.ClusterE2ETest) {
test.WithCluster(runCuratedPackageEmissaryInstall)
test.WithCluster(runCuratedPackageEmissaryIngressTest)
}
```
Adding a different way to execute the advanced tests only on docker provider for now.
=> Modifying docker test no double cluster run

controllers/cluster_controller.go, controllers/cluster_controller_test.go, internal/test/envtest/client.go
The CLI still allows to delete workload clusters and it doesn't yet use the controller to do this. This means that the controller shouldn't try to reconcile deletions for workload clusters that are paused, so the CLI can perform its own logic.
----
=> Avoid deleting paused workload clusters

config/crd/bases/anywhere.eks.amazonaws.com_nutanixdatacenterconfigs.yaml, internal/pkg/api/nutanix.go, internal/pkg/api/nutanix_test.go, pkg/api/v1alpha1/nutanixdatacenterconfig_types.go, pkg/dependencies/factory.go, pkg/providers/nutanix/template.go, pkg/providers/nutanix/template_test.go, pkg/providers/nutanix/testdata/datacenterConfig_with_insecure.yaml, pkg/providers/nutanix/validator.go, pkg/providers/nutanix/validator_test.go, test/framework/nutanix.go
To accommodate for the scenario where the user has not replaced the default Certificate that ships with Prism Central, we allow the user to skip TLS verification. Insecure is the optional property to skip TLS verification.
Nutanix Prism Central installation by default ships with a self-signed certificate that will fail TLS verification because of two reasons:
1. The certificate is not issued by a publicly trusted CA
2. The certificate does not have the IP SANs for the Prism Central endpoint
As such, in order for these services to establish a connection with Prism Central, client has three options:
1. Use Legitimate certificates: [Replace the default certificate](https://portal.nutanix.com/page/documents/details?targetId=Nutanix-Security-Guide-v6_1:mul-security-ssl-certificate-pc-t.html) …
=> Add `insecure` property for NutanixDatacenterConfig

pkg/providers/nutanix/config/cp-template.yaml
after this, we can do following steps to install nutanix csi driver 
<pre>
#Add the official Nutanix Helm repo and get the latest update
helm repo add nutanix https://nutanix.github.io/helm/
helm repo update
helm install nutanix-csi-snapshot nutanix/nutanix-csi-snapshot -n ntnx-system --create-namespace
helm install nutanix-storage nutanix/nutanix-csi-storage -n ntnx-system  
</pre>
for more details: https://opendocs.nutanix.com/capx/latest/addons/install_csi_driver/
After above helm charts were installed, i created following
- [create secret](https://portal.nutanix.com/page/documents/details?targetId=CSI-Volume-Driver-v2_6:csi-csi-plugin-create-secret-t.html) 
- [create storage class](https://portal.nutanix.com/page/documents/details?targ …
=> adding pre-requisites for nutanix csi driver

controllers/resource/vsphere.go, pkg/api/v1alpha1/cluster_types.go, pkg/clusterapi/workers.go, pkg/clusterapi/workers_test.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/docker/docker.go, pkg/providers/docker/workers_test.go, pkg/providers/nutanix/provider.go, pkg/providers/tinkerbell/upgrade.go, pkg/providers/vsphere/vsphere.go, test/framework/labels.go
We need to directly compare the labels maps to ensure a new name for the immutable kubeadm config template object when removing worker node labels
Unit test. Upgrade with new API on Docker cluster
=> Remove labels for worker node groups

controllers/cluster_controller.go, controllers/cluster_controller_test.go, pkg/api/v1alpha1/cluster_types.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/retrier_client.go
The new full lifecycle controller adds a finalizer to eks-a Clusters to be able to orchestrate its deletion. This interferes with the delete CLI operation, since it doesn't yet make use of the controller and it implements its own logic. The CLI tried to delete the eks-a cluster and get blocked forever since the controller wouldn't remove the finalizer for a paused cluster.
To solve this, we introduce a new annotation that signals the controller that the cluster is being managed the CLI and hence it should allow to be deleted without going through its normal deletion process.
There were also other hidden problems in the way cluster manager implemented the deletion, by wrapping a bunch of API operations in one big retry block. Some of these are not idempotent in combination with the others …
=> Fix delete workload clusters from CLI

controllers/cluster_controller.go, controllers/cluster_controller_test_test.go, pkg/cluster/client_builder.go
This should help users debug issues when misspelling object names or when a child object is not created successfully (think flux erroring in out in a machine config validation). This way we avoid having them checking the controller logs and can get everything from the API.
----------
=> Bubble up not found errors to cluster status

release/pkg/assets/config/bundle_release.go, release/pkg/test/testdata/main-bundle-release.yaml
Add UsesKubeRbacProxy for CAPX
This is needed because CAPX uses `kube-rbac-proxy` and adding this should replace `kube-rbac-proxy` image with the proper `public.ecr.aws` URI 
```
curl -s https://dev-release-assets.eks-anywhere.model-rocket.aws.dev/artifacts/v0.0.0-dev-build.5064/cluster-api-provider-nutanix/manifests/infrastructure-nutanix/v1.0.1/infrastructure-components.yaml | grep "image: .*"
image: 857151390494.dkr.ecr.us-west-2.amazonaws.com/brancz/kube-rbac-proxy:latest
image: public.ecr.aws/l0g8r8j6/nutanix-cloud-native/cluster-api-provider-nutanix:v1.0.1-eks-a-v0.0.0-dev-build.4684
```
=> Add UsesKubeRbacProxy for CAPX

pkg/dependencies/factory.go
Fixed nil pointer for vsphere cluster commands
=> Build IPValidator for vSphere provider

docs/content/en/docs/reference/changelog.md, test/e2e/awsiam_test.go, test/e2e/conformance_test.go, test/e2e/curated_packages_test.go, test/e2e/flux_test.go, test/e2e/oidc_test.go, test/e2e/simpleflow_test.go, test/e2e/stackedetcd_test.go, test/e2e/upgrade_dev_test.go, test/e2e/upgrade_from_latest_test.go, test/e2e/upgrade_test.go, test/e2e/vsphere_autoimport_test.go, test/e2e/workload_clusters_test.go
Remove 120 e2e tests and clean up 1.18 AND 1.19 tests.
- make e2e
=> Remove 120 e2e tests

pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/reconciler/reconciler_test.go, pkg/providers/vsphere/testdata/expected_results_bottlerocket_external_etcd_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_custom_resolv_conf.yaml, pkg/providers/vsphere/testdata/expected_results_full_oidc_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_121_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp_cloud_provder_and_csi_driver_credentials.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp_cloud_provider_credentials.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp_csi_driver_credentials.yaml, pkg/providers/vsphere/testdata/expected_results_main_no_machinetemplate_update_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_node_labels_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_with_taints_cp.yaml, pkg/providers/vsphere/testdata/expected_results_minimal_cp.yaml, pkg/providers/vsphere/testdata/expected_results_minimal_disable_csi_cp.yaml, pkg/providers/vsphere/testdata/expected_results_minimal_oidc_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_with_auth_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_pod_iam_config.yaml
If there is a mgmt cluster and a workload cluster, the resources in the clusterresourceset conflict, so adding the cluster name so that those resources can be managed separately
unit tests, functional test with tilt
=> Add cluster name to resources defined in clusterresourceset

Makefile
In Go 1.18, go get will no longer build packages: https://go.dev/doc/go-get-install-deprecation
Kubebuilder also deprecated `go get` in the `Makefile` template: https://github.com/kubernetes-sigs/kubebuilder/pull/2486
Use `go install` to install the tool binaries instead of with `go get`
=> Use go install instead of go get to install executables

docs/content/en/docs/reference/changelog.md, pkg/clusterapi/extraargs.go, pkg/clusterapi/extraargs_test.go, pkg/providers/docker/docker.go, pkg/providers/docker/testdata/valid_deployment_cp_expected_124onwards.yaml, pkg/providers/docker/testdata/valid_deployment_md_expected_124onwards.yaml
- `TestDockerKubernetes123to124UpgradeFromLatestMinorRelease` has been failing for the last few runs. This PR fixes that for unstacked topology.
- make e2e
- Run manual upgrade test
- Run e2e test `TestDockerKubernetes123to124UpgradeFromLatestMinorRelease`
=> Add systemd kubelet extra arg

cmd/eksctl-anywhere/cmd/options.go
If you attempt to create a cluster using the management cluster in your current context, it fails in vsphere because it is supposed to use a management cluster, but no ManagementCluster is set. https://github.com/aws/eks-anywhere/blob/main/pkg/providers/vsphere/vsphere.go#L301:L303
The only place it seems to make a ManagementCluster object is https://github.com/aws/eks-anywhere/blob/main/cmd/eksctl-anywhere/cmd/options.go#L107:L113 which requires kubeconfig to be passed in.
Not sure if this is the best way to fix this, but it does.
=> Fix management cluster from current context

test/e2e/harbor_test.go
Packages E2E Test for Nutanix for Harbor and Emissary.
Harbor will use local-provisioner untill storage class for Nutanix is figured out.
=> Adding Nutanix E2E Test for Emissary and Harbor

pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/tinkerbell_test.go
Override tinkerbellIP of workload cluster with the tinkerbellIP of management cluster while cluster creation. 
=> TinkerbellIP of management cluster and workload cluster should be same

docs/content/en/docs/reference/clusterspec/optional/oidc.md
The current oidc reference doc states that OIDC can only be setup at cluster creation. That is not true for VMWare and Cloudstack.
*Issue #, if available:* None, sorry
The current oidc reference doc states that OIDC can only be setup at cluster creation. That is not true for VMWare and Cloudstack.
=> docs: Clarify OIDC create/update documentation

pkg/providers/nutanix/config/md-template.yaml, pkg/providers/nutanix/template.go, pkg/providers/nutanix/template_test.go, pkg/providers/nutanix/testdata/eksa-cluster-autoscaler.yaml, pkg/providers/nutanix/testdata/expected_results_autoscaling_md.yaml
Adding autoscaling annotations to nutanix to support cluster-autoscaler package
=> Adding autoscaling annotations to nutanix

test/e2e/simpleflow_test.go, test/framework/nutanix.go
Give Nutanix tests unique names to avoid running multiple tests on the same instance
Also, fix UUID tests to correctly set UUID for os image
=> Fix Nutanix UUID tests

internal/pkg/api/nutanix.go, pkg/api/v1alpha1/nutanixmachineconfig.go, pkg/api/v1alpha1/nutanixmachineconfig_test.go, pkg/api/v1alpha1/nutanixmachineconfig_types.go, pkg/api/v1alpha1/testdata/nutanix/machineconfig-with-no-osfamily.yaml, pkg/api/v1alpha1/testdata/nutanix/machineconfig-with-no-ssh-key.yaml, pkg/api/v1alpha1/testdata/nutanix/machineconfig-with-no-users.yaml, pkg/dependencies/factory.go, pkg/providers/nutanix/provider.go, pkg/providers/nutanix/provider_test.go, pkg/providers/nutanix/testdata/eksa-cluster-multiple-machineconfigs.yaml
provided following yaml for machine config. note the zero ssh key below
<pre>
...
kind: NutanixMachineConfig
metadata:
name: nutanix-dev-cluster
namespace: default
spec:
cluster:
name: ganon
type: name
uuid: null
image:
name: eksa-dm-image-ubuntu-2004-kube-v1.23
type: name
uuid: null
memorySize: 4Gi
osFamily: ubuntu
subnet:
name: sherlock_net
type: name
uuid: null
systemDiskSize: 40Gi
users:
- name: nutanix-user
sshAuthorizedKeys:
-
vcpuSockets: 2
vcpusPerSocket: 1
...
</pre>
<pre>
ssh-key-gen ±  bin/eksctl-anywhere create cluster -f ./${CLUSTER_NAME}.yaml
Provided sshAuthorizedKey is not set or is empty, auto-generating new key …
=> Generate ssh key for Nutanix if user has not provided

test/e2e/adot_test.go
Added test cases for Cloudstack, Nutanix, and Tinkerbell; updated test cases for Docker and vSphere
=> Add / update ADOT e2e test cases

cmd/eksctl-anywhere/cmd/flags.go, pkg/providers/tinkerbell/create.go
Skip checking for hardware-csv flag for tinkerbell creation if kubeconfig flag is given
=> Skip checking hardware-csv flag for workload cluster tinkerbell

cmd/eks-a-tool/cmd/root.go, cmd/eksctl-anywhere/cmd/root.go, cmd/integration_test/cmd/root.go, pkg/diagnostics/collector_types.go, pkg/diagnostics/collectors.go, pkg/diagnostics/collectors_test.go, pkg/diagnostics/diagnostic_bundle.go, pkg/diagnostics/diagnostic_bundle_test.go, pkg/diagnostics/interfaces.go, pkg/diagnostics/interfaces/mocks/diagnostics.go, pkg/logger/logger.go, pkg/logger/logger_wb_test.go, pkg/logger/zap.go, pkg/logger/zap_test.go, test/e2e/simpleflow_test.go, test/e2e/tools/eks-anywhere-test-tool/cmd/root.go
This PR customizes the zap logger to log verbose logs to a file, and then include a copy of it in the support bundles when one is generated. This offers an easier way for the customer recover CLI run logs for debugging, when there are errors and interruptions of some kind.
=> Save CLI log output to file included in support bundle

pkg/workflows/delete.go
*Issue #, if available:* #4345
*Description of changes:* Passing a right number of params (an odd number) to logger.Info function
=> Pass a right number params to logger.Info function

test/framework/cluster.go
Occasionally, some tests will fail due to an error daemonsets.apps "generated-adot-aws-otel-collector-agent" not found. It appears that after the package changed to the "installed" state, some time buffer is still needed in between before we can check the daemonset status. The time needed may vary by machine. We will start with 15s.
=> Fix ADOT e2e daemonset not found error

go.mod, go.sum
Consume the tag that points to https://github.com/abhay-krishna/cluster-api/pull/6
(This got resolved, was an upstream Go issue) In order to get `go mod tidy` to work, I also needed to set `GOPRIVATE=github.com/abhay-krishna/cluster-api`
=> Update tag to consume bug fix for clusterresourceset

internal/pkg/api/cluster.go, internal/pkg/api/cluster_test.go, test/e2e/autoscaler_test.go, test/framework/cluster.go, test/framework/testdata/autoscaler_package.yaml, test/framework/testdata/hpa_busybox.yaml, test/framework/testdata/metrics_server_package.yaml
Adding a simple flow to test cluster autoscaler and metrics-server packages. This test 
- Deploys both cluster autoscaler and metrics-server packages. 
- Uses a HorizontalPodAutoscaler on a sample busybox workload. 
- Verifies that the machine deployments scale up to meet the new demand.
=> Cluster Autoscaler with Metrics-server e2e

pkg/api/v1alpha1/vspheremachineconfig_webhook_test.go
Update webhook test failure messages vsphere machine config
=> Update webhook test failure messages vsphere machine config

test/e2e/adot_test.go
Occasionally, tests fail due to "no bundle name specified". This is because package bundle controller didn't activate the bundle by the given time.
=> Add manual activate bundle step for ADOT e2e

internal/pkg/api/cluster.go, internal/pkg/api/cluster_test.go
On some networks, the default pod CIDR conflicts, and must be overridden in order for tests to pass successfully.
=> test: Allow override of Pod CIDR blocks w/ Docker provider

test/framework/docker.go
On some networks, the default pod CIDR conflicts, and must be overridden in order for tests to pass successfully.
=> test: Allow setting Pod CIDR blocks w/ Docker provider (2 of 2)

pkg/api/v1alpha1/vspheredatacenterconfig_webhook.go, pkg/api/v1alpha1/vspheredatacenterconfig_webhook_test.go
Make `disableCSI` mutable in the vsphere datacenter config webhook
=> Allow disableCSI from vsphere datacenter config webhook

designs/snow-integration.md, go.mod, go.sum, pkg/clusterapi/bottlerocket.go, pkg/clusterapi/bottlerocket_test.go, pkg/providers/snow/apibuilder.go, pkg/providers/snow/apibuilder_test.go, pkg/providers/snow/bottlerocket.go, pkg/providers/snow/testdata/expected_results_main_cp.yaml
#3283
- override the default admin, control images in etcd cluster to support bootstraping etcd nodes on snowball
- update pre/post kubeadm commands to use single bootstrap.sh script
Unit tests
=> Add admin, control and snow bottlerocket bootstrap container image in etcd cluster

pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/executables/builder.go, pkg/executables/builder_test.go
fixed bug where pulling kind/node during bootstrap-cluster-init phase failed with "unauthorized to access repository: eks-anywhere/l0g8r8j6/kubernetes-sigs/kind/node"
=> Add in missing docker login to long running container

internal/test/cleanup/cleanup.go, test/framework/nutanix.go
Implementing the cleanup step for Nutanix E2E so any leftover VMs get cleaned up
=> Add cleanup step for Nutanix E2E tests

docs/content/en/docs/reference/artifacts.md
While working through the image building instructions I noticed a few inconsistencies and ambiguity. This change set seeks to clarify the differences in steps between Ubuntu and RHEL builds and simplifies `image-builder` installation instructions.
* Simplify the download and install of image-builder to a single line.
* Clarify niche steps for RHEL vs Ubuntu with respec to invoking image-builder.
=> Update baremetal image build instructions.

cmd/eksctl-anywhere/cmd/importimages.go, docs/content/en/docs/reference/clusterspec/optional/registrymirror.md
Make it clearer that the `import-images` command is deprecated.
```
% eksctl anywhere import-images 
Command "import-images" is deprecated, use `eksctl anywhere import images` instead
Error: required flag(s) "filename" not set
```
No longer shows up in general help:
```
% eksctl anywhere help          
Use eksctl anywhere to build your own self-managing cluster on your hardware with the best of Amazon EKS
Usage:
anywhere [command]
Available Commands:
apply         Apply resources
check-images  Check images used by EKS Anywhere do exist in the target registry
completion    Generate the autocompletion script for the specified shell
create        Create resources
delete        Delete resources
describe      Describe resources
download      Download resources
exp           experimental …
```
=> Deprecate import-images command

test/framework/commands.go, test/framework/eksaVersions.go, test/framework/releaseVersions.go
Noticed some unused e2e test helper methods while looking into other things related to e2e tests. This PR removes them
=> Removed unused latest minor release e2e test helper methods

test/framework/cluster.go
15s wait time appears to be not sufficient in some cases, mainly Nutanix and vSphere Bottle Rocket (about 75% pass rate). Increase sleep time to 30s.
=> Adjust ADOT e2e sleep time while waiting on daemonset

docs/content/en/docs/reference/artifacts.md, docs/content/en/docs/reference/support/support-versions.md
* Make command snippets copyable
* Enforce `pip3` installation for image builds
* Run `wget` and `tar` commands without `sudo` to fix issue of `/tmp` directory being owned by `root`
* Remove dev-release note for usage of image-builder for AMI builds
* Remove 1-20/1.20 references.
=> Improve and fix docs for EKS-A artifacts and version support

test/framework/awsiam.go
When upgrading to kube 1.24 I noticed in some cases the aws-iam-authenticator rollout took a few extra seconds and hence e2e tests were failing intermittently.
*Testing:*
```bash
--- PASS: TestVSphereKubernetes124AWSIamAuth (655.03s)
PASS
[1]+  Done.   ./bin/e2e.test -test.v -test.run TestVSphereKubernetes124AWSIamAuth
```
=> Add wait awsiam e2e

docs/content/en/docs/getting-started/install/_index.md
The manuall install instructions for eksctl and eksctl-anywhere do not include kubectl. For completeness, we should include this.
Refs: #4482
=> docs: Add kubectl to manual install instructions

.gitignore, pkg/clients/kubernetes/runtimeclient.go, pkg/clients/kubernetes/runtimeclient_test.go, pkg/clients/kubernetes/runtimeclient_wb_test.go, pkg/clients/kubernetes/scheme.go, pkg/cluster/fetch.go, test/e2e/vsphere_workload_api_test.go, test/framework/cluster.go, test/framework/clustervalidator.go, test/framework/workload.go
This PR includes some infrastructure needed to write e2e tests for the Cluster Lifecycle API and a vSphere workload cluster e2e test that utilizes it.
Run `TestVSphereMulticlusterWorkloadClusterAPI` e2e test
=> Add infrastructure for Cluster Lifecycle API e2e tests

docs/content/en/docs/reference/clusterspec/vsphere.md
In many cases we require a fully qualified path, rather than a name. For example, a network must be referenced with a fully qualified path, where as a datacenter is simply a name. I have tried to call out "path" vs "name" where applicable.
Additionally, I have added example govc commands to see what values exist.
=> docs: Add additional details for VMware docs

pkg/clusterapi/etcd.go, pkg/clusterapi/etcd_test.go
Cluster creation failed bc of KCP missing etcd.external.endpoints.
```
2022-12-21T21:28:44.302Z        V5      Error happened during retry     {"error": "executing apply: error: error validating \"STDIN\": error validating data: ValidationError(KubeadmControlPlane.spec.kubeadmConfigSpec.clusterConfiguration.etcd.external): missing required field \"endpoints\" in io.x-k8s.cluster.controlplane.v1beta1.KubeadmControlPlane.spec.kubeadmConfigSpec.clusterConfiguration.etcd.external; if you choose to ignore these errors, turn validation off with --validate=false\n", "retries": 8}
``` …
=> Fix kubeadmcontrolplane with unstacked etcd template

pkg/clusterapi/apibuilder.go, pkg/clusterapi/apibuilder_test.go, pkg/clusterapi/bottlerocket.go, pkg/clusterapi/bottlerocket_test.go, pkg/clusterapi/etcd.go, pkg/clusterapi/etcd_test.go, pkg/providers/snow/apibuilder_test.go
When osFamily is bottlerocket, `etcd.Spec.EtcdadmConfigSpec.Format` needs to be `bottlerocket` or etcd bootstrap controller will trigger the cloud init config which won't work for BR.
- Unit tests
- Manual e2e on snow
=> Fix etcd cluster template for bottlerocket

cmd/eksctl-anywhere/cmd/upgradeplancluster.go, pkg/constants/constants.go, pkg/curatedpackages/curatedpackages.go, pkg/providers/nutanix/validator_test.go, pkg/types/upgrades_test.go
Add a nil check for CAPI diff for upgrade plan. Customer saw a nil pointer thrown while running the upgrade plan.
CAPI change diff does not have the Components Reports initialized because of empty Flux Change Diff.
- make and manual testing
=> Add a nil check for CAPI diff for upgrade plan

pkg/clusterapi/apibuilder.go, pkg/clusterapi/apibuilder_test.go, pkg/clusterapi/etcd.go, pkg/clusterapi/etcd_test.go, pkg/providers/snow/apibuilder.go, pkg/providers/snow/apibuilder_test.go
Fix snow unstacked etcd cluster creation on ubuntu.
- Add the snow bootstrap.sh in preEtcdadmCommands
- Remove the hostname configuration from apibuilder since snow does not need it. The hostname is set through CAPAS via userdata. AWS IMDS uses internal ip as hostname, which can be same on different devices.
Unit tests
=> Fix snow etcd cluster object

pkg/cluster/fetch.go, pkg/filewriter/writer.go, test/e2e/vsphere_workload_api_flux_test.go, test/framework/cluster.go, test/framework/clustervalidator.go, test/framework/flux.go, test/framework/multicluster.go, test/framework/workload.go
This PR includes some infrastructure needed to write Gitops e2e tests for the Cluster Lifecycle API and vSphere workload cluster e2e tests that utilizes it.
```
--- PASS: TestVSphereMulticlusterWorkloadClusterAPIGitHubFlux (1312.20s)
PASS
```
=> Add infrastructure for Cluster Lifecycle API GitOps e2e tests

test/e2e/multiple_worker_node_groups_test.go, test/e2e/upgrade_test.go, test/framework/cluster.go, test/framework/vsphere.go
Update vSphere api test to setup using `WithCusterConfig` for the first cluster definition, since we’re trying to enforce this structure for the new tests.
```
--- PASS: TestVSphereKubernetes124UbuntuUpgradeAndRemoveWorkerNodeGroupsAPI (1257.54s)
PASS
```
=> Update vSphere api test to use new structure

pkg/providers/snow/apibuilder.go, pkg/providers/snow/apibuilder_test.go, pkg/providers/snow/objects_test.go, pkg/providers/snow/testdata/expected_results_main_cp.yaml
Kubeadm checks if /etc/kubernetes/manifests is empty when running kubeadm join. However, we add the kube-vip static pod manifest there in control plane nodes, which makes the join command to fail. Bottlerocket runs kubeadm in a different way, so it doesn't face this issue. Other providers use useExperimentalRetryJoin, which runs kubeadm from a bash script which adds a flag to ignore this same preflight check.
=> Ignore kubeadm manifest preflight for ubuntu snow

config/crd/kustomization.yaml, config/manifest/eksa-components.yaml, manager/main.go, pkg/api/v1alpha1/snowippool_test.go, pkg/api/v1alpha1/snowippool_type.go, pkg/clustermanager/eksa_installer_test.go, pkg/clustermarshaller/clustermarshaller.go, pkg/clustermarshaller/clustermarshaller_test.go, pkg/clustermarshaller/testdata/expected_marshalled_snow.yaml, pkg/providers/snow/snow_test.go
Controller error with `SnowIPPool` kind not exists.
```
{"ts":1672820348229.5503,"caller":"controller/controller.go:326","msg":"Reconciler error","controller":"cluster","controllerGroup":"anywhere.eks.amazonaws.com","controllerKind":"Cluster","C
luster":{"name":"test-snow-2","namespace":"default"},"namespace":"default","name":"test-snow-2","reconcileID":"37fdc63b-2de9-47ab-8a33-0bf16537c443","err":"building Config from a cluster cl
ient: no matches for kind \"SnowIPPool\" in version \"anywhere.eks.amazonaws.com/v1alpha1\"","errVerbose":"no matches for kind \"SnowIPPool\" in version \"anywhere.eks.amazonaws.com/v1alpha
1\"\nbuilding Config from a cluster client\ngithub.com/aws/eks-anywhere/pkg/cluster.(*ConfigClientBuilder).Build\n\t/codebuild/output/src575995265/sr …
```
=> Add snowippool crd and register webhook

test/e2e/multiple_worker_node_groups_test.go, test/framework/clustervalidator.go, test/framework/docker.go
We currently only support upgrading worker node config fields for mgmt clusters when using the API, so here's a docker e2e test for that.
=> Add Docker API e2e test upgrading worker node for mgmt cluster

controllers/mocks/provider.go, pkg/controller/clusters/registry.go
This method won't be needed and not used anywhere.
=> Remove method from provider reconciler interface

config/crd/bases/anywhere.eks.amazonaws.com_snowmachineconfigs.yaml, config/manifest/eksa-components.yaml, pkg/api/v1alpha1/snowmachineconfig_types.go, pkg/clustermarshaller/testdata/expected_marshalled_snow.yaml
Below warning shows when applying eksa spec in cluster to create workload cluster.
```
$ k apply -f joeywang-snow-workload.yaml 
error validating "joeywang-snow-workload.yaml": error validating data: ValidationError(SnowMachineConfig.spec): missing required field "amiID" in com.amazonaws.eks.anywhere.v1alpha1.SnowMachineConfig.spec; if you choose to ignore these errors, turn validation off with --validate=false
```
amiID is optional since capas will fill in a match with its image lookup logic.
=> Make snow amiID optional

PROJECT, config/manifest/eksa-components.yaml, config/webhook/manifests.yaml, manager/main.go, pkg/api/v1alpha1/tinkerbelldatacenterconfig_webhook.go, pkg/api/v1alpha1/tinkerbellmachineconfig_webhook.go, pkg/clusterapi/apibuilder.go
[Skeleton for webhooks#982](https://github.com/aws/eks-anywhere-internal/issues/982)
- run `make hack/tools/bin/kubebuilder` to build kubebuilder
- run `./hack/kubebuilder.sh create api --group anywhere --version v1alpha1 --kind TinkerbellDatacenterConfig` to add api to [PROJECT](https://github.com/aws/eks-anywhere/blob/main/PROJECT)
- run `./hack/kubebuilder.sh create webhook --group anywhere --version v1alpha1 --programmatic-validation --kind TinkerbellDatacenterConfig` to generate webhook.go
- run `make release-manifests` to generate manifests
=> Generate tinkerbell validation webhook skeleton

test/framework/testdata/prometheus_package_deployment.yaml
Mode is not an acceptable property for Prometheus helm json validation.
=> Fix prometheus e2e test file

test/framework/cluster.go, test/framework/envars.go, test/framework/executables.go, test/framework/testingt.go, test/framework/vspherecsi.go
The *testing.T provided in tests is handy, but it panics when used outside of a running unit test's goroutine. Replacing it with an interface allows alternative implementations that can provide select logging and utility without having to be executed from within a test's goroutine. This is useful for setting up or tearing down test scaffolding (like reusable k8s clusters for E2E tests) before or after a test execution.
=> Replaces *testing.T with framework.T implementations

test/framework/testdata/hpa_busybox.yaml
E2E test failures for metric server and autoscaler caused by new busybox image not triggering the scaling targets for test. Tagging to an older known working version and to avoid using the latest image.
=> E2E Tagging busybox image with tag for consistency

pkg/clusterapi/apibuilder.go, pkg/clusterapi/apibuilder_test.go, pkg/clusterapi/bottlerocket.go, pkg/clusterapi/bottlerocket_test.go, pkg/clusterapi/identity_test.go, pkg/providers/snow/apibuilder_test.go, pkg/providers/snow/testdata/expected_results_main_cp_bottlerocket.yaml
During Snow BR cluster upgrade, one new CP node will come up and be in running state, while other CPs are not able to join the cluster. 
For stacked etcd case, we see
```
I0105 23:00:10.429921       1 scale.go:212]  "msg"="Waiting for control plane to pass preflight checks" "cluster-name"="test-snow" "name"="test-snow" "namespace"="eksa-system" "failures"="[machine test-snow-hnxjn reports APIServerPodHealthy condition is false (Error, Missing node), machine test-snow-hnxjn reports ControllerManagerPodHealthy condition is false (Error, Missing node), machine test-snow-hnxjn reports SchedulerPodHealthy condition is false (Error, Missing node), machine test-snow-hnxjn reports EtcdPodHealthy condition is false (Error, Missing node), machine test-snow-hnxjn reports …
```
=> Fix snow bottlerocket kube scheduler and controller-manager crash during upgrade

test/e2e/workload_api_flux_test.go
The `TestVSphereMulticlusterWorkloadClusterAPIGitHubFlux` keeps failing in the pipeline. This PR updates the name of the of test. Seeing if this may fix it because there is another test with the same prefix and it seems like the pipeline is running this twice, and failing only on the second run.
=> Update vSphere API flux test name 

pkg/providers/tinkerbell/assert_test.go, pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/validate.go
Move Tinkerbell datacenter config validations. This makes all datacenter config validations invokable from once place for webhooks.
=> Move Tinkerbell datacenter config validations

test/e2e/multiple_worker_node_groups_test.go, test/e2e/workload_api_test.go, test/framework/cloudstack.go, test/framework/cluster.go, test/framework/docker.go, test/framework/nutanix.go, test/framework/snow.go, test/framework/tinkerbell.go, test/framework/vsphere.go, test/framework/workload.go
This PR renames a file adds two docker e2e tests for the full lifecycle API, updates a vSphere API test with labels and taints to improve coverage without using more resources, and implements the `UpdateKubeConfig` to e2e Provider interface, which is required implementation for the docker provider. 
This is part 1 of a bigger PR. There will be another one adding validations for labels and taints to the controlplane and worker nodes validations.
`--- PASS: TestDockerUpgradeWorkloadClusterLabelsAndTaintsAPI (1086.90s)
`
`--- PASS: TestDockerUpgradeKubernetes123to124WorkloadClusterScaleWorkerNodesAPI (1418.77s)
` …
=> Add docker e2e api tests workload cluster k8s upgrade, taints and labels

internal/pkg/api/snowmachines.go, pkg/api/v1alpha1/snowmachineconfig.go, pkg/api/v1alpha1/snowmachineconfig_test.go
1. default generated ssh key to "" so eks-a can auto create and import the key to snow ec2
2. default os to ubuntu
3. add devices since its a required field
4. remove ContainersVolume since its optional, and the field may be deprecated after
=> Update snowmachineconfig defaults for generate clusterconfig cmd

pkg/providers/snow/snow_test.go
`TestUpgradeNeededMachineConfigChanged` fails half of the time because the method being tested loop a machineconfig map and order of the machine config is not fixed.
Loose check on machine config of any name and validate.
=> Fix snow flaky test

pkg/api/v1alpha1/tinkerbelldatacenterconfig.go, pkg/api/v1alpha1/tinkerbelldatacenterconfig_types.go, pkg/api/v1alpha1/tinkerbelldatacenterconfig_types_test.go, pkg/api/v1alpha1/tinkerbelldatacenterconfig_webhook.go, pkg/api/v1alpha1/tinkerbelldatacenterconfig_webhook_test.go, pkg/providers/tinkerbell/assert.go, pkg/providers/tinkerbell/validate.go, test/e2e/multiple_worker_node_groups_test.go
Add validations webhook for Tinkerbell Datacenter config
- unit tests
- manual test with tilt
=> Add validations webhook for Tinkerbell Datacenter config

pkg/validations/cluster.go, pkg/validations/cluster_test.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/createvalidations/preflightvalidations_test.go, pkg/validations/upgradevalidations/immutableFields.go, pkg/validations/upgradevalidations/preflightvalidations_test.go
Added additional validations to ensure that we are able to retrieve the EKS-A cluster object from the management cluster and also confirm that the cluster we have referenced is indeed a management cluster by checking if the management cluster name for that cluster references itself.
unit tests and testing these scenarios functionally
=> Add validation for management cluster referenced in workload cluster spec to be valid

controllers/factory.go, controllers/factory_test.go, controllers/tinkerbell_datacenter_controller.go, controllers/tinkerbell_datacenter_controller_test.go
Build Tinkerbell datacenter controller
The controller does not call the Tinkerbell IP validations yet.
=> Build Tinkerbell datacenter controller

test/e2e/workload_api_test.go, test/framework/cluster.go, test/framework/clustervalidator.go
Previous worker node validation didn't work for BottleRocket. This PR updates it and also does some refactoring.
```
--- PASS: TestVSphereUpgradeLabelsTaintsBottleRocketAPI (1615.58s)
PASS
```
=> Update worker node validation for API e2e tests

pkg/registry/certificates.go
My (possibly newer than the original author's) version of gofumpt complains about this.
=> prefer os.ReadFile, as it's not deprecated

pkg/registry/credentials_test.go
This fix isn't much better, as it matches against the text in a generic error, but it should work regardless of platform.
=> Fixes a platform-dependent test

pkg/api/v1alpha1/snowmachineconfig_types.go, pkg/api/v1alpha1/snowmachineconfig_webhook.go, pkg/api/v1alpha1/snowmachineconfig_webhook_test.go
We do not auto create and import ssh key to snow devices when creating a cluster through cluster lifecycle API.
Add in validation webhook.
=> Add sshkeyname check in snowmachineconfig validation webhook

test/e2e/metallb_test.go
Package test need to have CPackages in name to properly pass credentials from https://github.com/aws/eks-anywhere/blob/fc63a6efa1bb506593224216f48f530824d2088e/internal/test/e2e/packages.go#L11
=> Updating test name for Metallb Packages Test

internal/pkg/api/cluster.go, test/e2e/upgrade_from_latest_test.go, test/e2e/workload_api_test.go, test/framework/cluster.go
This PR adds a docker API E2E test for upgrading from the latest minor release test. The runs through the flow of upgrading a workload cluster to a new version of EKS-A through the API after first upgrading the management cluster.
```
--- PASS: TestDockerKubernetes123to124UpgradeFromLatestMinorReleaseAPI (1291.08s)
PASS
```
=> Add docker API E2E test upgrade from latest minor release

config/manager/manager.yaml, config/manifest/eksa-components.yaml, pkg/awsiamauth/config/aws-iam-authenticator.yaml, pkg/awsiamauth/installer_test.go, pkg/awsiamauth/template.go, pkg/awsiamauth/testdata/InstallAWSIAMAuth-manifest.yaml, pkg/awsiamauth/testdata/UpgradeAWSIAMAuth-manifest.yaml, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_external_etcd_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_custom_resolv_conf.yaml, pkg/providers/vsphere/testdata/expected_results_full_oidc_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_121_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp_cloud_provder_and_csi_driver_credentials.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp_cloud_provider_credentials.yaml, pkg/providers/vsphere/testdata/expected_results_main_cp_csi_driver_credentials.yaml, pkg/providers/vsphere/testdata/expected_results_main_no_machinetemplate_update_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_node_labels_cp.yaml, pkg/providers/vsphere/testdata/expected_results_main_with_taints_cp.yaml, pkg/providers/vsphere/testdata/expected_results_minimal_cp.yaml, pkg/providers/vsphere/testdata/expected_results_minimal_disable_csi_cp.yaml, pkg/providers/vsphere/testdata/expected_results_minimal_oidc_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_config_with_cert_cp.yaml, pkg/providers/vsphere/testdata/expected_results_mirror_with_auth_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_pod_iam_config.yaml
For kubernetes 1.25+, `node-role.kubernetes.io/master`is deprecated, but it is still the only default taint on control plane nodes for 1.22, so we must add this toleration for both of those options.
=> Update usage of control plane node role

pkg/validations/cluster.go, pkg/validations/cluster_test.go
Fix bug introduced in https://github.com/aws/eks-anywhere/pull/4596. Current management clusters can have the management cluster name as empty, so need to account for that as well. Utilizing the `IsManaged()` function in the cluster types that checks for this anyways.
unit testing and functional testing
=> Fix validation where management cluster name is empty

pkg/providers/snow/defaults.go, pkg/providers/snow/defaults_test.go, pkg/providers/snow/entry.go, pkg/providers/snow/validator_test.go
This is to address the issue where a user creates a new cluster but doesn't have access to the previously generated key by default as it is stored in AWS. There is no way to retrieve the key to access the nodes in those situations. Instead, we are adding the cluster name to the default key so that there are more unique default keys. We are also appending a generated uuid in the cases that you have multiple clusters from different admin machines with the same name for additional uniqueness. 
Also needed to move around the code a little to resolve a cyclic complexity lint issue, which doesn't like too many if statements in one function. 
unit test and functional testing
By submitting this pull request, I confirm …
=> Setup default ssh key based on cluster name and uuid for snow

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go
Preflights check if machine deployments are in an appropriate state before an upgrade can proceed. The check eneds to retrieve machines associated with the target cluster only, not all machine deployments.
=> Patch erroneous machine deployment state check on upgrade

pkg/cluster/build.go, pkg/cluster/tinkerbell.go, pkg/cluster/tinkerbell_test.go
[Implement Client processor for Tinkerbell datacenter config#983](https://github.com/aws/eks-anywhere-internal/issues/983)
=> Add client processor for Tinkerbell datacenter config

Makefile
It can be convenient to have make targets to perform formatting fixes instead of relying on IDE configurations.
=> Add run-gci target to make file

.gitignore, Makefile, pkg/executables/govc.go, pkg/executables/govc_test.go
Use predefined structs instead of generic `map[string]interface{}` to unmarshal `govc devices.info` response.
=> Use concrete structs for govc devices.info

pkg/cluster/build.go, pkg/cluster/tinkerbell.go, pkg/cluster/tinkerbell_test.go
[Implement Client processor for Tinkerbell machine config#984](https://github.com/aws/eks-anywhere-internal/issues/984)
=> Add client processor for Tinkerbell machine config

pkg/providers/tinkerbell/hardware/catalogue.go, pkg/providers/tinkerbell/hardware/catalogue_hardware.go
*Issue #4655*
Removing metadata.state from the default generated hardware objects for tinkerbell.
*Testing:*
```
eksctl-anywhere generate hardware -z .ignore/node1214hardware.csv
```
=> Removing setting provisioning field on the hardware metadata

test/e2e/upgrade_from_latest_test.go, test/e2e/workload_api_flux_test.go, test/e2e/workload_api_test.go, test/framework/flux.go, test/framework/vsphere.go
This PR adds docker E2E tests for the API with GitOps + one leftover vSphere API tests
=> Add Docker API Gitops tests

pkg/curatedpackages/reader.go
We were copying the bundle twice. Once for charts and once for images. This PR removes one of those copies.
=> Copy the package bundle once

pkg/providers/nutanix/config/cp-template.yaml, pkg/providers/nutanix/config/md-template.yaml, pkg/providers/nutanix/template_test.go, pkg/providers/nutanix/testdata/expected_results_autoscaling_md.yaml
Use VM Guest Customization Metadata to set the hostname on Nutanix.
This aligns the templates with what CAPX is expecting in v1.1.1.
* Modified the bundle-release.yaml by substituting CAPX entries to get latest CAPX version
```yaml
nutanix:
clusterAPIController:
arch:
- amd64
- arm64
description: Container image for cluster-api-provider-nutanix image
imageDigest: sha256:708c4e1a2049f37c8840b5516dca6fc4d96a7b073ab5ea1fd80b4430c7d03b1f
name: cluster-api-provider-nutanix
os: linux
uri: ghcr.io/nutanix-cloud-native/cluster-api-provider-nutanix/controller:v1.1.1
clusterTemplate:
uri: https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix/releases/download/v1.1.1/cluster-template.yaml
components:
uri: …
```
=> Update preKubeadmCommands for Nutanix

cmd/integration_test/build/buildspecs/snow-test-eks-a-cli.yml, cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml
Adding buildspec for Snow E2E tests. Curremtly the e2e test will be a no-op since we skip all tests until we have the hardware we need to run e2e tests.
=> Add buildspec for Snow E2E test

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go
1033
Tinkerbell external etcd is currently unsupported. Added a validation to prevent this configuration.
Added tests to cluster validations
=> adding external etcd unsupported for Tinkerbell check

controllers/cluster_controller_legacy.go
Adding Tinkerbell watches to legacy cluster controller for parity
=> adding Tinkerbell watches to legacy cluster controller

test/e2e/SKIPPED_TESTS.yaml
Skip Nutanix 1.25 packages e2e tests until 1.25 packages bundle is available. 
=> Skip Nutanix 1.25 packages e2e tests

test/e2e/upgrade_from_latest.go
We don't use Gitops in any of LatestMinorRelease tests, so this validation was causing a nil pointer in all of the test runs. Removing this since it is unnecessary
```
--- PASS: TestDockerKubernetes122to123UpgradeFromLatestMinorRelease (1148.88s)
PASS
```
=> Remove step to ValidateFlux in LatestMinorRelease tests

test/e2e/curatedpackages.go, test/e2e/emissary.go, test/e2e/multicluster.go
This adds the cluster config generation prior to the actual CLI call to create the management cluster. This method was renamed and those changes were probably lost with the refactor to split the tests by provider.
This should fix the e2e failures we saw got flux tests.
=> Update calls to CreateManagementClusterWithConfig

pkg/providers/nutanix/config/cp-template.yaml, pkg/providers/nutanix/template.go, pkg/providers/nutanix/template_test.go, pkg/providers/nutanix/testdata/eksa-cluster-oidc.yaml, pkg/providers/nutanix/testdata/expected_results_oidc.yaml, test/e2e/nutanix_test.go
Ensure OIDC config is propogated to KubeAdmControlPlane via
API Server extra args for the Nutanix provider.
=> Propagate OIDC Config for Nutanix

controllers/factory.go, controllers/factory_test.go, manager/main.go
This guarantees that things like govc sessions are destroyed before the container is stopped, avoiding lingering resources.
=> Close controller dependencies before manager exits

test/framework/cluster.go
The API e2e tests seem to be failing to connect to the kubeapi server sometimes when building the cluster validator client. This PR increases the max retries assuming it just needs more time to be ready.
=> Increase max retries when trying to build cluster validator

cmd/eksctl-anywhere/cmd/copypackages.go, pkg/curatedpackages/reader.go, pkg/registry/client.go, pkg/registry/copy.go, pkg/registry/copy_test.go, pkg/registry/mocks/storage.go, pkg/registry/storage.go
This change tags the helm charts with the versions were are in the package bundle. It seems a lot of work just for that, but we'll want to use this to tag the other images as well once those versions are available.
=> Copy package tag charts with versions

pkg/providers/tinkerbell/upgrade.go
1035
Removing control plane host endpoint check for new cp template since this is an immutable field.
=> removing redundant control plane host check

pkg/providers/cloudstack/cloudstack.go, pkg/providers/nutanix/provider.go, pkg/providers/nutanix/provider_test.go, pkg/providers/vsphere/vsphere.go
Removing redundant control plane host check for all affected providers.
=> removing redundant cp host check for multiple providers

docs/content/en/docs/reference/nutanix/_index.md
*Description of changes:* I noticed an EKS Anywhere on Nutanix blog pointing to the Nutanix reference page instead of to the getting started guide. I added a pointer to the getting started guide in case someone lands on that reference page first.
=> Add pointer to Nutanix getting started guide

pkg/validations/createcluster/createcluster.go, pkg/validations/createcluster/createcluster_test.go, pkg/validations/createcluster/mocks/createcluster.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/createvalidations/preflightvalidations_test.go, pkg/validations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations_test.go, pkg/workflows/create.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go, pkg/workflows/upgrade.go
Reorganize preflight validations so that we have only the runner that processes the validations, allowing for each preflight validation to be separate and have the remediation steps print, which was not printed before.
Before:
```
✅ Connected to server
✅ Authenticated to vSphere
✅ Datacenter validated
✅ Network validated
Warning: VSphereMachineConfig MemoryMiB for etcd machines should not be less than 8192. Defaulting to 8192
Warning: Your VM template includes snapshot(s). LinkedClone mode will be used. DiskGiB cannot be customizable as disks cannot be expanded when using LinkedClone mode. Using default of 25 for DiskGiBs.
Warning: Your VM template includes snapshot(s). LinkedClone mode will be used. …
```
=> Refactor preflight validations so remediation steps can be printed

cmd/integration_test/build/buildspecs/nutanix-test-eks-a-cli.yml
This should cleanup any leftover Nutanix VMs at the end of Nutanix e2e tests
=> Add `cleanup-vms` flag to nutanix e2e test

release/pkg/bundles/eksctl-anywhere.go
Architecture is an array so we should flatten it to a string for use with `Sprintf`.
=> Flatten arch array to string

cmd/eks-a-tool/cmd/nutanix.go, cmd/eks-a-tool/cmd/nutanixrm.go, cmd/eks-a-tool/cmd/nutanixrmvms.go
Adds `eks-a-tool nutanix rm vms <cluster-name>` command to easily cleanup Nutanix VMs 
```bash
$ make eks-a-tool
$ export EKSA_NUTANIX_USERNAME="..."
$ export EKSA_NUTANIX_PASSWORD="..."
$ ./bin/eks-a-tool nutanix rm vms main --endpoint pc.nutanix.local --insecure true -v 4
2023-01-30T12:03:27.181-0800    V4      Logger init completed   {"vlevel": 4}
2023-01-30T12:03:56.382-0800    V4      Deleting Nutanix VM     {"Name": "main-i-0b1f1-7aedd81-control-plane-template-1674779404886-88x88", "UUID:": "4836cc45-467a-45cc-97f0-f1f05d4c24d9"}
2023-01-30T12:03:56.907-0800    V4      Deleting Nutanix VM     {"Name": "main-i-05c46-a8ce162-control-plane-template-1674779490983-fdgd9", "UUID:": "34e3f7ac-c9a2-4d9a-b80c-5c416ef9715b"} …
```
=> Add rm vms command for Nutanix in eks-a-tool

cmd/eksctl-anywhere/cmd/common.go
Uses registry mirror for package controller install if specified in cluster spec.
=> Update packagecontroller install command for registry mirror

pkg/curatedpackages/config/secrets.yaml, pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go, pkg/curatedpackages/testdata/values_empty.yaml, pkg/curatedpackages/testdata/values_empty_awssecret.yaml, pkg/curatedpackages/testdata/values_empty_registrymirrorsecret.yaml, pkg/curatedpackages/testdata/values_test.yaml
The cluster spec has `insecureSkipVerify`, but we were not passing that to packages
=> Add passing the insecure flag to packages

pkg/curatedpackages/config/packagebundlecontroller.yaml, pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go, pkg/curatedpackages/testdata/packagebundlectrl_registrymirror.yaml, pkg/curatedpackages/testdata/packagebundlectrl_test.yaml
Use helm chart to create credential secrets and PackageBundleController for workload clusters
=> Create secrets for workload clusters

cmd/eksctl-anywhere/cmd/common.go
E2E seems to be failing because of aws/eks-anywhere#4801. Revert while we investigate.
=> Revert "[release-0.14] Update packagecontroller install command for registry mirror"

cmd/eksctl-anywhere/cmd/common.go
E2E seems to be failing because of aws/eks-anywhere#4797. Revert while we investigate.
=> Revert "Update packagecontroller install command for registry mirror"

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go
if either pod cidr or service cidr conflicts with control plane endpoint, cluster provision will fail after installing cilium
check if pod cidr or service cidr has conflicts with control plane endpoint in preflight validation.
built new eksa binary, and tested, worked as expected
```
[ec2-user@ip-34-223-14-233 ~]$ eksctl anywhere create cluster -f eksa-cluster.yaml -v6  --force-cleanup
2023-02-01T00:55:19.266Z	V4	Logger init completed	{"vlevel": 6}
Error: the cluster config file provided is invalid: control plane endpoint 192.168.1.245 conflicts with pods CIDR block 192.168.1.0/16
[ec2-user@ip-34-223-14-233 ~]$ vim eksa-cluster.yaml
[ec2-user@ip-34-223-14-233 ~]$ eksctl anywhere create cluster -f …
```
=> Validate control plane endpoint with pods and services CIDR blocks

internal/pkg/ec2/create.go
When building images, require the ec2 instance executing to use imdsv2.
=> Require imdsv2 On Run Instance

pkg/providers/tinkerbell/controlplane.go, pkg/providers/tinkerbell/controlplane_test.go
This PR adds registers a Secret Kind mapping to the control plane parse which seems to be missing when generating Tinker-bell CP Spec.
=> Add Secret registry mapping when generating Tinkerbell CP Spec

pkg/providers/vsphere/defaults.go, pkg/providers/vsphere/testdata/cluster_main_121_cp_only.yaml, pkg/providers/vsphere/vsphere_test.go
vSphere fullClone currently fails if the user doesn't specify `diskGiB` for a machine and the template disk size is greater than 20 GiB. This is because `diskGiB` for a machine can't be less than the template's disk size but EKS-A defaults diskGiB to 20, if not specified.
```
Error getting disk config spec for primary disk: can't resize template disk down, initial capacity is larger: 23068672KiB > 20971520KiB
```
With this change, the new default for `diskGiB` will be the `max(20, templateDiskSize)`
=> Determine diskGiB default using template disk size for vSphere

release/scripts/github-bundle-release.sh
Use correct field name when fetching EKS-A CLI URL.
=> Use correct field name when fetching EKS-A CLI URL

pkg/aws/client.go, pkg/aws/ec2_test.go, pkg/aws/snow.go, pkg/aws/snowballdevice_test.go, pkg/providers/snow/reconciler/clientbuilder.go
Prepare for including an IMDSv2 for checking instance ip. https://github.com/aws/eks-anywhere/issues/4844 
Add `ClientOpt` for easier aws client testing. Avoid to add a `NewClientFromXXX` testing method every time we add a new client.
Unit tests
=> Refactor aws client for future easier unit testing

internal/test/envtest/environment.go, manager/main.go, pkg/clients/kubernetes/scheme.go, pkg/features/features.go, pkg/features/features_test.go, pkg/providers/tinkerbell/hardware/catalogue_hardware.go, pkg/providers/tinkerbell/hardware/catalogue_hardware_test.go, pkg/providers/tinkerbell/reconciler/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler_test.go
This PR implements the Tinkerbell Cluster Reconciler phase: `ReconcileControlPlane`.
Additionally, a `TinkerbellUseDiskExtractorDefaultDisk` flag has been added that forces the diskExtractor to use `/dev/sda` disk by default as discussed. This is temporary until the diskExtractor logic can be removed from the reconciler.
Unit tests
=> Implement Tinkerbell reconcile CP

controllers/factory.go, pkg/api/v1alpha1/tinkerbellmachineconfig.go, pkg/api/v1alpha1/tinkerbellmachineconfig_webhook.go, pkg/api/v1alpha1/tinkerbellmachineconfig_webhook_test.go, pkg/providers/tinkerbell/assert_test.go, pkg/providers/tinkerbell/cluster_spec_builder_test.go
Ran into `Index out of bound` and `invalid memory address or nil pointer dereference [recovered]` errors when testing the controller for tinkerbell. Added fixes.
=> Fixing panic errors for tinkerbell FLC

docs/content/en/docs/tasks/packages/_index.md
The current IAM policy example for curated packages is too open. It would allow the IAM User to pull from any repository anywhere, including any repository in the account. The intent is for this user to pull curated packages from the curated packages repository. This change in the policy example reflects that.
Note that the `ecr:GetAuthorizationToken` action does not have a resource, so its resource must be '*'.
None
See above.
Tested in AWS account with `aws ecr get-login-password --region us-east-1 |docker login --username AWS --password-stdin 783794618700.dkr.ecr.us-east-1.amazonaws.com` and `docker pull 783794618700.dkr.ecr.us-east-1.amazonaws.com/emissary-ingress/emissary:v3.3.0-cbf71de34d8bb5a72083f497d599d …
=> docs: Restrict the curated packages IAM example further

pkg/providers/tinkerbell/reconciler/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler_test.go
This PR adds CheckControlPlaneReady reconciliation phase to the Tinkerbell reconciler
Tested sufficiently by `TestReconcilerReconcileSuccess` and the tests in `pkg/controller/clusters/clusterapi_test.go`
=> Check Control Plane is ready during Tinkerbell reconciliation

docs/content/en/docs/reference/clusterspec/snow.md
Remove containersVolume fields that are not supported in CAPAS yet. 
=> Remove unsupported fields in snow doc

pkg/providers/tinkerbell/stack/stack.go
The TLS flag is required in v0.8.0 of the Tink Server.
=> Patch tls flag in Tinkerbell stack deployment

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/constants/constants.go
We do have a validation where if a user specify node cidr mask size in `clusterNetwork` field, it validates against pod cidr blocks. With this PR, we will validate pod cidr block size against node cidr mask size with the default value too so we can validate user config data before it fails at the later stage.
=> Validate pod cidr mask size with the default value of node cidr size

pkg/providers/tinkerbell/reconciler/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler_test.go
[1041](https://github.com/aws/eks-anywhere-internal/issues/1041)
Validates that worker cluster Tinkerbell IP matches that of the management cluster for the cluster full lifecycle project. 
unit tests
=> validate worker tinkerbell IP matches management

pkg/providers/vsphere/defaults.go
Fix the log message to show the defaults properly as it was showing as below before:
```
non-string key argument passed to logging, ignoring all later arguments	{"invalid key": 22}
Warning: VSphereMachineConfig DiskGiB cannot be less than %s. Defaulting to %s.
```
new:
```
Warning: VSphereMachineConfig DiskGiB cannot be less than 22. Defaulting to 22.
```
functional testing
=> Fix integer log for vsphere template defaulting

pkg/aws/snowballdevice.go, pkg/aws/snowballdevice_test.go, pkg/providers/snow/aws.go, pkg/providers/snow/entry.go, pkg/providers/snow/mocks/aws.go, pkg/providers/snow/snow_test.go, pkg/providers/snow/validator.go
https://github.com/aws/eks-anywhere/issues/4880
Some snow instance types are only supported in specific snow device type. Add validation in CLI to check it.
Unit tests
=> Add snow instance type validation in CLI preflight

pkg/aws/ec2.go, pkg/aws/ec2_test.go, pkg/providers/snow/aws.go, pkg/providers/snow/mocks/aws.go, pkg/providers/snow/snow_test.go, pkg/providers/snow/validator.go
Add vCPU check for snow instance type as kubelet requires at least 2 vCPU.
Unit tests + manual e2e
=> Validate snow instance type has at least 2 default vCPU

cmd/eksctl-anywhere/cmd/root.go
*Issue #, if available:* 
*Description of changes:* Many Users have a lot failed runs, and each failed run creates a log file in the working directory. So a user can get a bloated folder quite easily. To mitigate the issue, all failed logs are now saved in a subfolder of the working directory.
1. make eks-a
2. eksa download artifacts, ctrl-c, and logs are saved in eksa-cli-logs
=> Move logs to a subfolder

config/crd/bases/anywhere.eks.amazonaws.com_snowmachineconfigs.yaml, config/manifest/eksa-components.yaml, internal/pkg/api/snow.go, internal/pkg/api/snowmachines.go, pkg/api/v1alpha1/snowmachineconfig.go, pkg/api/v1alpha1/snowmachineconfig_test.go, pkg/api/v1alpha1/snowmachineconfig_types.go, pkg/api/v1alpha1/snowmachineconfig_webhook_test.go, pkg/providers/snow/validator.go, test/e2e/snow_test.go
#4889 and #4891 introduced new snow instance type validation where we fetch the instance type metadata dynamically from aws go SDK `DescribeInstanceTypes` and see if the instance type specified in each `SnowMachineConfig` is within the supported instance type list and is valid.
This PR removes the exact match of the snow instance type in API context unaware validation, and replace it with regex, which is more flexible and will support newer instance type in the future.
Unit tests + manual e2e
=> Replace snow instance type exact match with regex validation

pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
This makes sure that even when a rolling upgrade is not needed, the eks-a objects reflect the latest state driven by the CLI. This includes new Bundles.
Before this, if there was a new Bundles that updated dependencies like CAPI or eks-a controller but didn't require a rolling upgrade, we didn't create the new Bundles in the cluster or update the cluster object to reference it. It's quite an edge case since most new Bundles come with new eks-d releases, which do trigger a rolling upgrade, so this probably never happened in prod.
Verified this works with docker provider and a new Bundles that only updates capi and cert-manager.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
=> Update eksa objects in cluster for skipped upgrade

pkg/providers/snow/defaults.go, pkg/providers/snow/defaults_test.go, pkg/providers/snow/validator.go
When each snow machine config has different device list, the ssh preflight validation can fail. For example, if CP machine config has `devices: [device_1]` and a worker machine config has `devices: [device_1, device_2]` where both config has sshKeyName with empty value, the validation fails with
```
setting defaults and validate snow config: invalid cluster config: aws key pair [eksa-default-joeywang-5ea18e76-0c09-4190-89df-306300f9c251] does not exist"
```
This is because we set the `keyGenerated` to `true` once the first machine config has the default key. And we skip the import for other machine configs even if they have different device list.
We first generate a SSH auth key if not exists yet. Then we loop through the devices in the …
=> Fix snow default ssh key validation error

release/pkg/bundles/package-controller.go, release/pkg/helm/helm.go, release/pkg/operations/upload.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.14-bundle-release.yaml
This will do 3 things which should help with package controller image tag/sha mismatch from the bundle and the helm chart that is causing installation/e2e issues.
1. Will override the Image SHA in the values.yaml for the packages helm chart on dev bundles. This is the function `OverWriteChartValuesImageSha` on line 447 of `release/pkg/helm/helm.go`
2. Will lookup and use the correct latest version/sha of the Token Refresher in the Dev Bundle when running a dev Release. This is on lines 58-61, and 84-89 on  `release/pkg/bundles/package-controller.go`
3. Will override the Image Version and SHA in the values.yaml for the packages helm chart on dev bundles, and push the helm chart to Public ECR that will be used in …
=> Attempt at fix for dev helm chart in dev bundles

test/e2e/SKIPPED_TESTS.yaml
Enable Nutanix 1.25 packages e2e tests
=> Enable Nutanix 1.25 packages e2e tests

pkg/api/v1alpha1/cluster_types.go, pkg/features/features.go, pkg/features/features_test.go, pkg/validations/cluster.go, pkg/validations/cluster_test.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations.go, test/e2e/awsiam_test.go, test/e2e/conformance_test.go, test/e2e/flux_test.go, test/e2e/labels_test.go, test/e2e/oidc_test.go, test/e2e/proxy_test.go, test/e2e/registry_mirror_test.go, test/e2e/simpleflow_test.go, test/e2e/stackedetcd_test.go, test/e2e/taints_test.go, test/e2e/upgrade_from_latest_test.go, test/e2e/upgrade_test.go
Removing 1.25 feature flag & adding 1.26 feature flag manually for 0.14 since the e2e test structure changed drastically since adding the feature flag, but there is not real need to backport all of those implementations to this branch 
=> Remove 1.25 flag & add 1.26 flag for 0.14 branch

release/pkg/aws/ecr/ecr.go
Sometimes when the image details gets checked it will multiple tags.
`["0.0.0.abcde", "latest"]`
This would technically pass the filter requirement where we are looking for the presence of the of the prefix `0.0.0` however it might return back the tag of latest for the actual bundle.
This function will check the slice once a match has been made, and remove out an items from the slice which also don't match the prefix requirement.
var newSlice []string
newSlice = removeStringSlice(["0.0.0.abcde", "latest"] "latest")
`["0.0.0.abcde", "latest"]`  becomes.... `["0.0.0.abcde"]`
=> Adding function for doubletagged images

release/pkg/aws/ecr/ecr.go
Reverts aws/eks-anywhere#4951
Looks like it failed when it ran in dev, looking into why.
=> Revert "Adding function for doubletagged images"

cmd/eksctl-anywhere/cmd/generatebundleconfig.go, internal/test/files.go, pkg/dependencies/factory.go, pkg/diagnostics/analyzers_test.go, pkg/diagnostics/collectors.go, pkg/diagnostics/collectors_test.go, pkg/diagnostics/interfaces.go, pkg/files/reader.go, pkg/files/reader_wb_test.go, test/framework/awsiam.go, test/framework/conformance.go, test/framework/reader.go, test/framework/releaseVersions.go, test/framework/vsphere.go
This should fix the "eks-a-unknown" user-agent in requests for the release and bundles manifests.
There is still cleanup due in the e2e framework where too many readers are instantiated. The cluster.Spec also does too many things, we should remove the read/load functionality it has and make it a pure data struct. However, that would blow up the scope of this change, so leaving that for other PRs.
=> Set user-agent in all file readers

pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go, pkg/curatedpackages/reader.go
Currently the packages source registry does not handle staging account. This points the sourceRegistry to staging during a staging run
=> Adding check for packages to handle staging account.

release/pkg/aws/ecr/ecr.go
Sometimes when the image details gets checked it will multiple tags.
`["0.0.0.abcde", "latest"]`
This would technically pass the filter requirement where we are looking for the presence of the of the prefix `0.0.0` however it might return back the tag of latest for the actual bundle.
This function will check the slice once a match has been made, and remove out an items from the slice which also don't match the prefix requirement.
var newSlice []string
newSlice = removeStringSlice(["0.0.0.abcde", "latest"] "latest")
`["0.0.0.abcde", "latest"]`  becomes.... `["0.0.0.abcde"]` 
Last PR was using `*detail.ImageTags[j]` which would get index out of length error, so changed function to not utilize index.
=> Add function remove doubletagged images

cmd/eksctl-anywhere/cmd/checkimages.go, cmd/eksctl-anywhere/cmd/common.go, cmd/eksctl-anywhere/cmd/downloadartifacts.go, cmd/eksctl-anywhere/cmd/downloadimages.go, cmd/eksctl-anywhere/cmd/importimages.go, cmd/eksctl-anywhere/cmd/internal/commands/artifacts/download.go, cmd/eksctl-anywhere/cmd/listimages.go, cmd/eksctl-anywhere/cmd/listovas.go
Adding bundles override to EKS-A `list` and `download` command sets.
=> Add bundles override flag for list and download commands

test/e2e/curated_packages_test.go
framework.WithBottleRocket125 is not present
=> Remove package test on 1.25 vSphere BottleRocket

test/framework/workload.go
Some of the API tests are failing while trying to create the cluster client, because `connect: no route to host` after waiting for the kubeconfig. This PR adds a wait for the control plane to be ready after waiting for the kubeconfig, since there may be a delay there.
=> Wait for control plane ready before using kubeconfig for validations in API e2e tests

docs/developer/local-quickstart.md
Small documentation note for configuring e2e build flags.
=> Document e2e Build Flag Configuration in Quick Start

internal/pkg/api/snow.go, internal/pkg/api/snowmachines.go, test/e2e/README.md, test/e2e/SKIPPED_TESTS.yaml, test/e2e/snow_test.go, test/framework/cluster.go, test/framework/snow.go
=> Add snow static ip e2e tests

docs/content/en/docs/getting-started/production-environment/baremetal-getstarted.md, docs/content/en/docs/getting-started/production-environment/cloudstack-getstarted.md, docs/content/en/docs/getting-started/production-environment/nutanix-getstarted.md, docs/content/en/docs/getting-started/production-environment/snow-getstarted.md, docs/content/en/docs/getting-started/production-environment/vsphere-getstarted.md
managementCluster is a critical field for workload clusters. It was only defined as the last sentence in a note here. Let's make it more obvious.
None
managementCluster is a critical field for workload clusters. It was only defined as the last sentence in a note here. Let's make it more obvious.
Markdown preview
=> docs: Make managementCluster defintion obvious

pkg/controller/runner.go, pkg/controller/runner_test.go, pkg/providers/docker/reconciler/reconciler.go, pkg/providers/snow/reconciler/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler_test.go, pkg/providers/vsphere/reconciler/reconciler.go
Tinkerbell upgrade validations require comparisons between the desired Cluster Spec state and the existing current state pulled from the CAPI objects at multiple phases of the reconciler. Caching the result of our comparisons and/or the desired CAPI state earlier on will allow us to reference these objects in later phases without repeatedly retrieving the CAPI state and running our comparisons.
The phase runner currently runs off the Cluster Spec object. We propose allowing the object type to be specified as needed to allow custom fields and values outside of Cluster Spec to be stored, referenced and modified in different phases - while being constrained to the scope of the `reconciler.Reconcile()` function for thread safety.
This update …
=> updating phase runner to accept generic objects

pkg/clustermanager/eksa_installer_test.go
Having this variable set would cause test failures, as the "noflags" variant of the test would assume that the value was unset.
=> Decouple a unit test from its environment

pkg/providers/tinkerbell/stack/stack.go, pkg/providers/tinkerbell/stack/stack_test.go, pkg/providers/tinkerbell/stack/testdata/expected_with_proxy_config.yaml, pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_proxy.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_proxy.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md_proxy.yaml, pkg/providers/tinkerbell/tinkerbell.go
This PR passes proxy variables to tinkerbell stack where hook bootkit grabs the variables and set those as environment variables for tink-worker and other action images. 
=> Tinkerbell proxy related changes for hook bootkit

pkg/cluster/build.go, pkg/cluster/cloudstack.go, pkg/cluster/cloudstack_test.go
https://github.com/aws/eks-anywhere-internal/issues/968
=> Add client processor for CloudStack datacenter config

docs/content/en/docs/tasks/cluster/cluster-upgrades/vsphere-and-cloudstack-upgrades.md
Add stronger warning about not deleting bootstrap cluster after failed upgrade.
=> Add bolded warning about deleting bootstrap cluster

test/e2e/SKIPPED_TESTS.yaml
Skipping external ETCD e2e test for tinkerbell as of now since we don't support external ETCD for tinkerbell.
=> Skip external ETCD e2e test for tinkerbell

pkg/files/reader.go
Sometimes during cluster creation, we encounter TLS handshake timeout errors like below
```
Error: initializing capi resources in cluster: can't load infrastructure bundle for manifest https://anywhere-assets.eks.amazonaws.com/releases/bundles/27/artifacts/cert-manager/manifests/v1.9.1/cert-manager.yaml: failed to load manifest: failed reading file from url [https://anywhere-assets.eks.amazonaws.com/releases/bundles/27/artifacts/cert-manager/manifests/v1.9.1/cert-manager.yaml]: Get "https://anywhere-assets.eks.amazonaws.com/releases/bundles/27/artifacts/cert-manager/manifests/v1.9.1/cert-manager.yaml": net/http: TLS handshake timeout
```
The default TLS handshake timeout is 10 seconds, bumping it to 60 seconds (which is a very generous amount).
By submitting this pull request, I confirm …
=> Increase TLS Handshake timeout for reading data from URLs

pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go
Depends on https://github.com/aws/eks-anywhere-packages/pull/842
Moves the release from default to the eksa-packages namespace. This will require manually uninstalling the packages chart and reinstalling it. This will be documented in a later PR.
=> Move the eksa-packages release out of default.

docs/content/en/docs/reference/clusterspec/vsphere.md
*Issue:* [#5077](https://github.com/aws/eks-anywhere/issues/5077)
*Description of changes:* Updated [vSphere configuration](https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/vsphere/) to add comments to each line of the example vSphere clusterspec file and links to longer descriptions.
=> Add links and comments to vSphere clusterspec docs

test/e2e/vsphere_test.go
Fixes capitalization for vsphere authenticated registry e2e tests from #5061 
=> Fix vsphere registry auth e2e tests

test/e2e/SKIPPED_TESTS.yaml
Some Snow tests were missing from the skip list, which caused them to run in CI and fail.
=> Add missing Snow E2E tests to skip list

pkg/providers/tinkerbell/reconciler/reconciler_test.go
Have been seeing intermittent test failures during test coverage for Tinkerbell Datacenter reconciler tests. This updates them to use the fake client to reduce failure points.
=> Update Tinkerbell reconciler tests to use fake client

pkg/features/features.go, pkg/features/features_test.go, pkg/providers/tinkerbell/reconciler/reconciler_test.go
This was added to use a default disk for the diskExtractor for Tinkerbell temporary, so that we could continue to test the new  controller, meanwhile the diskExtractor was being refactored/removed. Now it's no longer necessary.
=> Remove temporary TinkerbellUseDiskExtractorDefault feature gate

pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go, pkg/curatedpackages/testdata/values_empty.yaml, pkg/curatedpackages/testdata/values_empty_awssecret.yaml
As the region setting is optional, it can't be assumed to be set, as was happening in places.
Since it seems safe to have a default value set, and there was a default value already defined, I've gone ahead and set it.
Now things can assume the value of the eksaRegion field is a non-zero value.
=> set a default region for PackageControllerClient

docs/content/en/docs/getting-started/install/_index.md, docs/content/en/docs/getting-started/local-environment/_index.md
*Description of changes:* Documentation on setting up EKS Anywhere cluster creation for an airgapped environment is added to the install page here.
A cluster create command for airgapped will need to be added to each provider. So far, I have just added it to the local environment (Docker) provider. I'd like to keep this PR on hold until that provider's content looks okay. Then I'll add it to the others.
=> Added airgapped instructions to the docs

pkg/executables/kubectl_test.go, pkg/executables/testdata/kubectl_deployment.json, pkg/executables/testdata/kubectl_deployments.json, pkg/executables/testdata/kubectl_pods.json
Replace use of k8s.gcr.io with registry.k8s.io for tests
=> Remove other reference to k8s.gcr.io

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go
The `getWorkloadClusterKubeconfig` method already contains the retry logic as `clusterClient` is a retryClient: https://github.com/aws/eks-anywhere/blob/main/pkg/clustermanager/cluster_manager.go#L397.
Remove duplicate retry.
Unit tests
=> Remove duplicate retry when getting workload cluster kubeconfig

pkg/api/v1alpha1/tinkerbellmachineconfig.go, pkg/api/v1alpha1/tinkerbellmachineconfig_webhook_test.go, pkg/providers/tinkerbell/cluster_spec_builder_test.go
Add validation to check for empty ssh keys
=> Add validation to check for empty ssh keys

pkg/providers/tinkerbell/assert.go, pkg/providers/tinkerbell/assert_test.go, pkg/providers/tinkerbell/cluster_spec_builder_test.go, pkg/providers/tinkerbell/upgrade.go
[#1060](https://github.com/aws/eks-anywhere-internal/issues/1060)
Tinkerbell `AssertionsForScaleUpDown()` requires both the current clusterSpec and the desired clusterSpec when run by the cluster validator. The Cluster Full Lifecycle controller does not have current state cluster spec and pulls CAPI state instead. `AssertionsForScaleUpDown` minimum hardware requirements must still be run for scaling upgrades with the Cluster Full Lifecycle Controller.  
=> Tinkerbell Scaling Upgrade Validation

designs/nutanix-datacenterconfig-credentialref.md
The CredentialRef property will allow to transparently link credentials for a Prism Central with its corresponding EKS-A abstraction: NutanixDatacenter.
=> Add a design proposal on adding CredentialRef to NutanixDatacenter

docs/content/en/docs/concepts/clusterworkflow.md, docs/content/en/docs/reference/baremetal/bare-custom-hookos.md, docs/content/en/docs/reference/baremetal/bare-preparation.md, docs/content/en/docs/reference/baremetal/bare-prereq.md, docs/content/en/docs/reference/baremetal/netbooting-and-tinkerbell.md, docs/content/en/docs/reference/ports.md, docs/content/en/docs/tasks/troubleshoot/troubleshooting.md
Update docs around Tinkerbell:
- Capitalize all Tinkerbell service names, proper nouns should generally be capitalized.
- Update Rufio crds to the latest names.
- Update all references to IPMI to BMC so that both IPMI and Redfish are included.
- Update PXE to be network boot so that it includes both PXE and HTTP network booting.
=> Update docs around Tinkerbell:

test/e2e/metallb.go, test/framework/cluster.go
The test was constantly failing due to a duplicate package controller installation, removed the extra call and the function since this was the only place it was actually used.
```
--- PASS: TestDockerCuratedPackagesMetalLB (652.64s)
--- PASS: TestDockerCuratedPackagesMetalLB/TestPackagesMetalLB (647.85s)
--- PASS: TestDockerCuratedPackagesMetalLB/TestPackagesMetalLB/Basic_installation (87.66s)
--- PASS: TestDockerCuratedPackagesMetalLB/TestPackagesMetalLB/Address_pool_configuration (71.54s)
--- PASS: TestDockerCuratedPackagesMetalLB/TestPackagesMetalLB/BGP_configuration (72.76s)
PASS
```
=> Fixing metallb e2e test that keeps failing

cmd/eksctl-anywhere/cmd/constants.go, cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/deletecluster.go, cmd/eksctl-anywhere/cmd/options.go, cmd/eksctl-anywhere/cmd/upgradecluster.go, cmd/eksctl-anywhere/cmd/upgradeplancluster.go, pkg/clustermanager/client.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/eksa_installer.go, pkg/clustermanager/eksa_installer_test.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/retrier/retrier.go, pkg/retrier/retrier_test.go
#5104 
Introduce `--no-timeouts` flag to disable timeout for all the cluster operations.
This PR
- overrides the default cluster_manager retriers with a new retrier with no timeout, when the flag is presented.
- overrides all kubectl wait timeout with max time
Unit tests
=> Introduce --no-timeouts flag in create and upgrade CLI

pkg/providers/tinkerbell/assert.go, pkg/providers/tinkerbell/assert_test.go
AssertionsForScaleUpDown() was calling the current/old spec hardware selector which is not available in the CLI upgrade workflow causing a nil pointer exception in CLI upgrades and E2E tests.
This removes the call for hardware selector and updates AssertionsForScaleUpDown() to use the same desired clusterSpec that was previously being referenced.
Manually ran CLI upgrade workflow with no changes in spec. 
=> Fixing AssertionsForScaleUpDown currentSpec references

pkg/providers/tinkerbell/reconciler/reconciler.go
[1207](https://github.com/aws/eks-anywhere-internal/issues/1207)
Calling CleanupStatusAfterValidate to clear Tinkerbell cluster status if validations pass.
existing unit tests
=> adding cleanup phase to tinkerbell reconciler

test/e2e/SKIPPED_TESTS.yaml, test/e2e/cloudstack_test.go
Removing 1.21 CloudStack e2e & enabling more for 1.22 and 1.23
=> Enable more CloudStack 1.22 and 1.23 e2e tests

internal/test/e2e/registryMirror.go
Fix registry mirror tests to mount proper ca certs for tinkerbell tests
=> Fix registry mirror e2e for tinkerbell

designs/validations.md, pkg/cli/doc.go, pkg/cli/log.go, pkg/cli/log_test.go, pkg/defaulting/doc.go, pkg/defaulting/example_test.go, pkg/defaulting/runner.go, pkg/defaulting/runner_test.go, pkg/errors/aggregate.go, pkg/validation/doc.go, pkg/validation/errors.go, pkg/validation/errors_test.go, pkg/validation/example_test.go, pkg/validation/runner.go, pkg/validation/runner_test.go
In the past we have followed multiple approaches for validations and defaults but none of them seem to have succeeded. This proposed a holistic approach and a plan to make the different implementations consistent.
=> Revamp (again) API defaults and validations

pkg/api/v1alpha1/hostosconfig_types.go
Add omitempty to HostOSConfig fields as they are optional
=> Add omitempty to HostOSConfig fields

pkg/providers/tinkerbell/reconciler/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler_test.go
*Issue #5147*
The unit test `TestReconcilerValidateHardwareNoHardware` is flaky because it checks for an error string and the error string depends on the order of a Map.
https://github.com/aws/eks-anywhere/blob/main/pkg/providers/tinkerbell/validate.go#L136
The requirements object is a map and it swaps its order of objects, so sometimes the worker node condition gets checked first and we are looking for the control plane condition in the unit test error message.
=> Modified error msg check for unit test

cmd/eksctl-anywhere/cmd/constants.go, cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/deletecluster.go, cmd/eksctl-anywhere/cmd/options.go, cmd/eksctl-anywhere/cmd/upgradecluster.go, cmd/eksctl-anywhere/cmd/upgradeplancluster.go, pkg/clustermanager/client.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/eksa_installer.go, pkg/clustermanager/eksa_installer_test.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/retrier/retrier.go, pkg/retrier/retrier_test.go
Backport #5151 
Manual testing on docker provider w create/upgrade --no-timeouts
=> Introduce --no-timeouts flag in create and upgrade CLI (#5151)

test/e2e/registrymirror.go, test/framework/cluster.go
Add a cleanup step in tinkerbell registry mirror tests to cleanup the downloaded artifacts after the tests complete.
This is needed so the next set of tests don't run out of disk space.
=> Cleanup registry mirror artifacts after the tests for Tinkerbell

docs/content/en/docs/reference/clusterspec/optional/registrymirror.md
The registry mirror caCertContent __must__ be a singular ca cert, and it must be the cert used to sign the registry mirror cert.
Updating the registry mirror documentation about ca cert usage.
Markdown preview
=> docs: Clarify caCertContent documentation

cmd/integration_test/build/buildspecs/tinkerbell-test-eks-a-cli.yml
Adding required ENV var for 1.26 template for tinkerbell.
=> Adding 1.26 template env for tinkerbell

release/pkg/bundles/tinkerbell.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.14-bundle-release.yaml
The hard coded version populates the version key for CAPT in the bundle. It is used by EKS-A to determine if there's a change in the provider and if a new version needs rolling out. Because we always use the same version number, we never roll out the updated CAPT and consequently CAPT fails to launch correctly. This occurs during an upgrade from a v0.14 cluster to main only as that's the first time we've updated CAPT.
=> Remove hard coded Tinkerbell provider version

.github/workflows/golangci-lint.yml
This version works on mac with 1.20. The old version OOMs.
=> Update go-lint version

pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/cloudstack/validator.go, pkg/providers/cloudstack/validator_mocks.go, pkg/providers/cloudstack/validator_registry.go, pkg/providers/cloudstack/validator_test.go
moved validateSecretsUnchanged from cloudstack.go to validator.go
=> move validation

cmd/eksctl-anywhere/cmd/root.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/executables/clusterctl.go, pkg/executables/clusterctl_test.go, pkg/task/task.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
Backup CAPI objects before moving from management cluster to bootstrap cluster during upgrade
I have tested this feature by create/upgrade/delete of management and workload cluster.
=> Backup CAPI objects of management cluster

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/features/features.go, pkg/features/features_test.go
…ll providers
This validation currently blocks during preflight for unsupported providers. Use of flag this flag is to temporarily block support for registryMirror InsecureSkipVerify option is added for all providers.
Also, want to get this so that it will being binary built into the controller image which currently has the code enforcing insecureSkipVerify for only Snow compiled into it. So, this will allow for easier local testing.
=> Add registry mirror insecure skip verify support feature flag to enable for all providers.

cmd/eksctl-anywhere/cmd/root.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/executables/clusterctl.go, pkg/executables/clusterctl_test.go, pkg/task/task.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
Backup CAPI objects before moving from management cluster to bootstrap during upgrade.
=> Clusterctl backup of management resources before moving to bootstrap

pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go, pkg/providers/tinkerbell/reconciler/reconciler.go
Make labels and taints immutable for Tinkerbell
- unit test
=> Make labels and taints immutable for Tinkerbell

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/config/registry.go, pkg/config/registry_test.go, pkg/constants/constants.go, pkg/providers/nutanix/config/cp-template.yaml, pkg/providers/nutanix/config/md-template.yaml, pkg/providers/nutanix/template.go, pkg/providers/nutanix/template_test.go, pkg/providers/nutanix/testdata/eksa-cluster-registry-mirror.yaml, pkg/providers/nutanix/testdata/expected_results_registry_mirror.yaml, pkg/providers/nutanix/testdata/expected_results_registry_mirror_md.yaml, test/e2e/nutanix_test.go, test/framework/nutanix.go
To support EKS-Anywhere on Nutanix in air-gapped environments, we need to honor the
local registry mirror specified in the cluster config and propagate it forward.
Followed https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/optional/registrymirror/ to set up a
harbor registry with necessary projects and importing the images to the harbor registry.
```
$ bin/eksctl-anywhere import images -i eks-anywhere-images.tar --bundles eks-anywhere-downloads/bundle-release.yaml --registry ${REGISTRY_ENDPOINT}
```
Add the `registryMirrorConfiguration` property to the cluster spec pointing to the new registry.
```
kind: Cluster
metadata:
name: eksa-sid
spec:
...
registryMirrorConfiguration:
endpoint: …
```
=> Propagate registry mirror config for Nutanix provider

Makefile, controllers/factory.go, pkg/curatedpackages/mocks/installer.go, pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go, pkg/dependencies/factory.go
During development of curated packages support via full cluster lifecycle, these interfaces required different helm executable instantiations, but that requirement was removed, so now these can merge down into the same interface.
=> merge the chartInstaller and chartUninstaller

pkg/api/v1alpha1/nutanixdatacenterconfig_webhook.go, pkg/api/v1alpha1/nutanixdatacenterconfig_webhook_test.go, pkg/clustermanager/eksa_installer.go, pkg/clustermanager/eksa_installer_test.go
This ensures user doesn't have to set FULL_LIFECYCLE_API to true manually to use full cluster lifecycle features on Nutanix.
=> Remove Full Cluster Lifecycle feature gate for Nutanix

config/crd/bases/anywhere.eks.amazonaws.com_nutanixmachineconfigs.yaml, config/manifest/eksa-components.yaml, pkg/api/v1alpha1/nutanixmachineconfig.go, pkg/api/v1alpha1/nutanixmachineconfig_types.go, pkg/api/v1alpha1/nutanixmachineconfig_webhook.go, pkg/api/v1alpha1/nutanixmachineconfig_webhook_test.go, pkg/api/v1alpha1/zz_generated.deepcopy.go, pkg/providers/nutanix/client.go, pkg/providers/nutanix/config/md-template.yaml, pkg/providers/nutanix/mocks/client.go, pkg/providers/nutanix/template.go, pkg/providers/nutanix/template_test.go, pkg/providers/nutanix/testdata/eksa-cluster-project.yaml, pkg/providers/nutanix/testdata/expected_results_project.yaml, pkg/providers/nutanix/testdata/expected_results_project_md.yaml, pkg/providers/nutanix/testdata/machineConfig_project.yaml, pkg/providers/nutanix/validator.go, pkg/providers/nutanix/validator_test.go
These changes allow specifying an optional project in the NutanixMachineConfig
which, when specified, is propagated to the corresponding NutanixMachineTemplate
property. 
- Used a bundle-release.yaml with eksa-components.yaml and cluster-controller image overridden to
the ones corresponding to the changes in this PR.
- Set the `project` property in `NutanixMachineConfig` manifests to `my-project`: A project that already exists in Prism Central
```
kind: NutanixMachineConfig
metadata:
name: eksa-sid-cp
spec:
...
project:
name: my-project
type: name
...
---
kind: NutanixMachineConfig
metadata:
name: eksa-sid
spec:
...
project:
name: my-project
type: name
...
```
- …
=> Support linking VM resources with Projects on Nutanix

test/e2e/multicluster.go, test/e2e/tinkerbell_test.go, test/framework/workload.go
[1064](https://github.com/aws/eks-anywhere-internal/issues/1064)
Adding E2E create/delete test for Tinkerbell Cluster API
added e2e test
=> adding tinkerbell e2e clusterAPI test

pkg/providers/nutanix/config/cp-template.yaml, pkg/providers/nutanix/config/md-template.yaml, pkg/providers/nutanix/template.go, pkg/providers/nutanix/template_test.go, pkg/providers/nutanix/testdata/eksa-cluster-node-taints-labels.yaml, pkg/providers/nutanix/testdata/expected_results_node_taints_labels.yaml, pkg/providers/nutanix/testdata/expected_results_node_taints_labels_md.yaml, pkg/providers/nutanix/testdata/expected_results_oidc.yaml, pkg/providers/nutanix/testdata/expected_results_project.yaml, pkg/providers/nutanix/testdata/expected_results_registry_mirror.yaml
Ensure taints and labels are passed on for both controlplane and worker nodes for Nutanix provider.
- Created a cluster spec with `taints` and `labels` present in `controlPlaneConfiguration` and `workerNodeGroupConfigurations`
```
kind: Cluster
metadata:
name: eksa-sid
spec:
...
controlPlaneConfiguration:
...
taints:
- key: key1
value: val1
effect: PreferNoSchedule
labels:
key1-cp: value1-cp
key2-cp: value2-cp
workerNodeGroupConfigurations:
...
taints:
- key: key1
value: val1
effect: PreferNoSchedule
labels:
key1-md: value1-md
key2-md: value2-md
```
- Created a cluster with the above cluster spec successfully
```
$ bin/eksctl-anywhere create cluster -f eksa-sid.yaml --force-cleanup -v 10  --bundles-override …
```
=> Propagate cluster taints and labels for CAPX clusters

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/providers/tinkerbell/config/template-cp.yaml, pkg/providers/tinkerbell/config/template-md.yaml, pkg/providers/tinkerbell/controlplane_test.go, pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/workers_test.go, test/e2e/tinkerbell_test.go
#1647 following up on the introduction of InsecureSkipVerify flag, and introducing it to the other providers.
This PR adds InsecureSkipVerify option support for Tinkerbell.
Work on the other providers will continue in other PRs
=> Enabled registry mirror InsecureSkipVerify flag for Tinkerbell

docs/content/en/docs/reference/clusterspec/cloudstack.md, docs/content/en/docs/reference/clusterspec/optional/irsa.md, docs/content/en/docs/reference/clusterspec/vsphere.md, docs/content/en/docs/workshops/provision/vsphere.md
1. Replace usage of "IAM for Pods" with "IAM Roles for Service Accounts", using the correct name for the feature.
2. Teak the irsa.md docs to clarify the installation of the webhook and creation of a service account.
Tested with `make server` to make sure no links were broken.
=> docs: Update IAM Roles for Service Accounts docs

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/cloudstack/config/template-cp.yaml, pkg/providers/cloudstack/config/template-md.yaml, pkg/providers/cloudstack/testdata/expected_results_mirror_config_with_insecure_skip_and_cert_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_mirror_config_with_insecure_skip_and_cert_md.yaml, pkg/providers/cloudstack/testdata/expected_results_mirror_config_with_insecure_skip_cp.yaml, pkg/providers/cloudstack/testdata/expected_results_mirror_config_with_insecure_skip_md.yaml
#1647 following up on the introduction of InsecureSkipVerify flag, and introducing it to the other providers.
This PR adds InsecureSkipVerify option support for Cloudstack.
- Unit testing
- Manual e2e test (registry isn't set up for cloudstack to write an e2e test)
Add the registryMirrorConfiguration property to the cluster spec pointing to the new registry.
```
kind: Cluster
metadata:
name: mgmt
spec:
...
registryMirrorConfiguration:
endpoint: 1.2.3.4
port: 5000
insecureSkipVerify: true
```
Using a bundle-release.yaml with an image of the controller built from the changes in this PR as bundles override, create a cluster.
`bin/eksctl-anywhere import images -i …
=> Introduce registry mirror InsecureSkipVerify for cloudstack

pkg/providers/tinkerbell/hardware/catalogue_hardware.go, pkg/providers/tinkerbell/hardware/catalogue_hardware_test.go
`Removehardwares` was throwing an index out of bound panic because we were reducing the length of the `catalogue.Hardware` in-place. 
Fixed by storing a diff list and replacing.
=> Changing logic for removing hardware from catalogue

pkg/validations/cluster.go, pkg/validations/cluster_test.go, pkg/validations/kubectl.go, pkg/validations/mocks/kubectl.go, pkg/validations/upgradevalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations_test.go
Validates that the management cluster's bundle is the same version or newer than the bundle version used to upgrade a workload cluster.
https://github.com/aws/eks-anywhere/issues/5105
Validates that a management cluster's bundles rev >= the bundle used by CLI to upgrade a workload cluster.
Unit test and two manual tests:
Example error:
```
2023-03-15T17:13:16.583-0400    V0      ❌ Validation failed    {"validation": "validate management cluster bundle version compatibility", "error": "cannot upgrade workload cluster with bundle 29 while management cluster mgmt-v-jwmeier is on older bundle 28", "remediation": "upgrade management cluster mgmt-v-jwmeier before upgrading workload cluster wk-v-jwmeier"}
```
By …
=> Validate Mgmt Cluster Bundles Version on Upgrade

config/manifest/eksa-components.yaml, config/rbac/role.yaml, controllers/cluster_controller_legacy.go, pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go
Previously, the creation a of package bundle controller was executed via a helm chart release. Now that helm chart will create a package instead. The end result being the same, that the packages controller will notice the newly created resource and do what it needs to support curated packages on the new workload cluster.
One additional value is passed to the helm invocation to help the packages controller take the appropriate actions.
=> change signaling method for FCL curated packages support

docs/content/en/docs/reference/artifacts.md, docs/content/en/docs/reference/nutanix/domains.md
* Call out attention to prerequisites in all sections.
* Add image-builder OS/hypervisor combination support matrix.
=> Make image-builder OS support and prerequisites section more clear

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go
=> Fix kubectl get call to point to full API name

pkg/controller/clusterapi.go, pkg/controller/clusterapi_test.go, pkg/controller/clusters/workers.go, pkg/providers/tinkerbell/reconciler/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler_test.go, pkg/providers/tinkerbell/template.go
The tinkerbell reconcile phase omitting worker node machine templates was setting `nil` to the loop iterator and not the scope object.
Added `nil` for the right objects and also added Nil checks when applying worker node spec.
Built the controller and tested changes.
=> Fixing tink reconcile worker template omit and logs

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_types_test.go, pkg/dependencies/factory.go, pkg/networking/cilium/upgrader.go, pkg/validations/upgradevalidations/immutableFields.go, pkg/validations/upgradevalidations/immutableFields_test.go
Implement the behavior for the `SkipUpgrade` Cilium flag on CLI based clusters (i.e. not FLC).
When creating a cluster without specifying `SkipUpgrade` the cluster should continue updating the embedded Cilium. When `SkipUpgrade` is true on create the system should install embedded Cilium but not upgrade it. If a user toggles on `SkipUpgrade` after creating the cluster we should no longer attempt to upgrade it.
Toggling off `SkipUpgrade` is disabled until we've explored the implications.
=> Feature: Implement unmanaged CNI for CLI based clusters

docs/content/en/docs/getting-started/install/_index.md, docs/content/en/docs/reference/artifacts.md
We have some hardcoded version numbers in the artifacts docs that we are required to update for every release. Instead of doing that, we can use the releases manifest as the source of truth and programmatically get artifact URLs.
=> Remove hardcoded artifact links in docs

pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/createvalidations/preflightvalidations_test.go
Validates that the management cluster's bundle is the same version or newer than the bundle version used to create a workload cluster.
Follow up to https://github.com/aws/eks-anywhere/pull/5263#issuecomment-1476999424 for ticket https://github.com/aws/eks-anywhere/issues/5105.
Validates management/CLI bundles versions on workload cluster creation.
Ran create workload cluster commands with valid and invalid bundles, validations succeeded/failed as expected.
=> Validate Mgmt Cluster Bundles Version on Workload Cluster Create

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml, config/manifest/eksa-components.yaml, pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/api/v1alpha1/cluster_types.go, pkg/registrymirror/registrymirror.go, pkg/validations/cluster.go, pkg/validations/cluster_test.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations.go
#647 following up on the introduction of InsecureSkipVerify flag, and introducing it to the other providers. However, bottlerocket is not supported
Adds a preflight validation that checks if the OS is valid for the provided registry mirror configuration with insecure skip verify enabled.
Unit tests
Manual testing
=> Add validation for OS when using registry mirror InsecureSkipVerify

pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go
Passes the management cluster's name when installing curated packages on a workload cluster. Removes the workloadOnly flag, as it's no longer needed in this case, as the FCL/CLI curated packages installation for workload clusters is now triggered from the workloadPackageOnly flag.
=> set management cluster name helm value

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/validations/createvalidations/cluster_test.go
Expanding all kubectl calls to have their full qualified API names to avoid conflicts.
=> Expand all kubectl calls to fully qualified names

docs/content/en/docs/concepts/cluster-topologies.md, docs/content/en/docs/concepts/clusterworkflow.md, docs/content/en/docs/getting-started/local-environment/_index.md, docs/content/en/docs/getting-started/production-environment/snow-getstarted.md, docs/content/en/docs/getting-started/production-environment/vsphere-getstarted.md
*Issue:* [#5119](https://github.com/aws/eks-anywhere/issues/5119)
*Description of changes:* This PR starts the documentation process for adding cluster lifecycle features to EKS Anywhere docs. In particular, it notes the ability to use kubectl to create workload clusters for vSphere, Docker, and Snow. It also describes this feature in the cluster workflow and cluster topology docs.
I still have some questions, so I have not yet added cluster lifecycle content for Nutanix, Bare Metal, or Cloudstack. I also need more information on how cluster lifecycle should be described in relation to workload cluster upgrades and deletions. I will either add that information here or create new PRs after this one merges. …
=> Add cluster lifecycle information to docs

pkg/providers/nutanix/template.go, pkg/providers/nutanix/template_test.go, pkg/providers/nutanix/testdata/eksa-cluster-no-credentialref.yaml
Use `nutanix-credentials` as NutanixDatacenterConfig credentialRef name if it is not present. This ensures we don't get a nil-pointer dereference during upgrade and upgrade can happen smoothly.
* Created a cluster using a EKS-A CLI build before FCL changes were merged (NutanixDatacenterConfig spec had no credentialRef)
* Upgraded the cluster successfully using an EKS-A CLI build with these changes included and using the same cluster spec as above (no credentialRef set on NutanixDatacenterConfig). 
Full upgrade logs: https://app.warp.dev/block/w7d8Ic3TrSign6eYTeRv55
=> Use default credential names if credential names are not set

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml, config/manifest/eksa-components.yaml, pkg/api/v1alpha1/cluster_types.go
Removing defaults for `skipUpgrade` to handle unpredictable behavior from Flux controller.
=> Removing default value for skipUpgrade to fix flux errors

test/e2e/vsphere_test.go, test/framework/cluster.go, test/framework/testdata/hpa_busybox.yaml
Also adds a 1.24 Ubuntu test.
Seeing some unusual behavior in the Ubuntu Cluster Autoscaler tests. Something about Ubuntu + 1.25 kubernetes + vSphere and Nutanix CI environments seem to result in no Scale Up action. @junshun and I think the issue is the HPA failing to trigger new pods to scale out.
=> Reduce Autoscaler HPA Busybox Test Resources

Makefile, pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go, pkg/networking/cilium/installation.go, pkg/networking/cilium/installation_test.go, pkg/networking/cilium/reconciler/marker.go, pkg/networking/cilium/reconciler/reconciler.go, pkg/networking/cilium/reconciler/reconciler_test.go
This PR adds the business logic for Full Lifecycle Controller handling of the Cilium `skipUpgrade` flag in the EKS-A API.
The change relies on an annotation populated whenever we observe EKS-A Embedded Cilium is installed in the cluster. Using the annotation combined with the skip flag, we can determine if we need to install Cilium (for successful cluster creation) or treat the CNI as unmanaged and do nothing.
An edge case exists where a user may have uninstalled EKS-A Embedded Cilium and toggled skip on. In that case, we cannot identify if Cilium was ever installed and consequently will try to install it. Users can work around the problem by manually populating the annotation.
**Manual Tested Scenarios**
* Create a workload cluster and observe EKS-A Cilium installed and annotation …
=> Feature: Add unmanaged CNI for FLC

docs/content/en/docs/workshops/packages/prometheus/prometheus_grafana.md, internal/test/e2e/hostOSConfig.go, pkg/api/v1alpha1/hostosconfig_test.go, test/e2e/vsphere_test.go, test/framework/hostOSConfig.go, test/framework/vsphere.go
Fix regex for BR settings e2e test
Set correct template in 125To126 aws iam e2e test
=> Fix regex for BR settings e2e test

test/e2e/SKIPPED_TESTS.yaml
This change was supposed to have been made in another PR, but there was a conflict with 1.26 e2e test changes that overrided it.
=> Skip Tinkerbell airgapped 1.26 e2e test

pkg/providers/tinkerbell/upgrade.go
When Hardware are submitted to the cluster without baseboard management data they won't have a baseboard management controller reference. The upgrade procedure from pre v0.15 clusters to v0.15+ will panic if the reference is missing on Hardware objects. This change ensures a reference exists before trying to update it.
=> Fix panic on Tinkerbell custom resource conversion

internal/pkg/api/tinkerbell.go, test/e2e/multicluster.go, test/e2e/tinkerbell_test.go, test/e2e/upgrade.go, test/framework/tinkerbell.go
[1064](https://github.com/aws/eks-anywhere-internal/issues/1064)
Add e2e tests for Tinkerbell cluster API upgrades
- TestTinkerbellUpgrade125MulticlusterWorkloadClusterWorkerScaleupWithAPI
- workload cluster worker scale up
- TestTinkerbellUpgradeMulticlusterWorkloadClusterK8sUpgrade124To125WithAPI
- workload cluster k8s version upgrade
- TestTinkerbellKubernetes125UbuntuWorkerNodeScaleUpWithAPI
- worker node scale up
- TestTinkerbellKubernetes125UbuntuAddWorkerNodeGroupWithAPI
- add worker node group
Tests have passed local run
=> Tinkerbell ClusterAPI e2e upgrade test

test/e2e/vsphere_test.go, test/framework/cluster.go
Automated cherry-pick did not apply cleanly. cherry-picks https://github.com/aws/eks-anywhere/pull/5391 into release-0.15.
=> [release-0.15] Increase Autoscaler e2e Timeout

cmd/integration_test/build/script/upload_artifacts.sh
After the provider-specific e2e test split, it is the build stage that uploads artifacts and not the test stage, to avoid duplicate artifacts upload. So this check needs to test for the build stage.
=> Fix check for conditional CLI tarball upload path

pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go, pkg/providers/tinkerbell/upgrade.go
Cluster webhooks and preflights were failing for multiple worker node groups due to a pointer referencing error.
=> Referencing the right pointer for Tink validations

docs/content/en/docs/reference/clusterspec/baremetal.md, docs/content/en/docs/reference/clusterspec/optional/hostOSConfig.md, docs/content/en/docs/reference/clusterspec/vsphere.md
Add docs for hostOSConfig
Preview available here
https://anywhere-docs.abhnvp.people.aws.dev/docs/reference/clusterspec/optional/hostosconfig/
=> Add docs for hostOSConfig

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_wb_test.go
This is a manual cherry-pick of https://github.com/aws/eks-anywhere/pull/5441
=> [release-0.14] Fix clustermanager no-timeouts option

test/e2e/tinkerbell_test.go
Fix Kube version for e2e test and update it to 126.
=> Fix Kube version for e2e test

docs/content/en/docs/reference/artifacts.md
fixes #5273 
Adds raw.githubusercontent.com and objects.githubusercontent.com to image-builder prerequisites lists
Doc preview
=> Add missing domains to prerequisites list

test/e2e/tools/eks-anywhere-test-tool/pkg/filewriter/writer.go
`eksa-test-tool` panics when fetching tinkerbell artifacts for use cases where `/Test` is not found in the object key. This happens when tests have a SSM time out.
=> Adding a case for no substring match

release/pkg/helm/helm.go, release/pkg/operations/upload.go
Running Helm push command using CLI instead of library to make it more robust when working credentials from the env. This will unblock the bundle release.
=> Run Helm push command using CLI instead of library

release/Makefile, release/scripts/announce_eksa_release.sh
Make EKS-A release manifest URL overrideable to make out-of-band release announcements.
=> Make EKS-A release manifest URL overrideable

docs/content/en/docs/reference/clusterspec/optional/cni.md
*Issue #, if available:* https://github.com/aws/eks-anywhere/issues/5217
Add documentation for using custom CNIs.
=> Add documentation for using a custom CNI

test/e2e/tinkerbell_test.go
Fix e2e test names for 126 e2e tests.
=> Fix e2e test names

docs/content/en/docs/reference/changelog.md
This PR removes the “Latest” in “Latest support OS version details”, the idea is that this section will be under every new release, so saying “latest” doesn’t make much sense.
=> Update changelog supported OS version details title

internal/test/http.go, pkg/files/reader.go, pkg/files/reader_test.go
We need to preserve some of the defaults in the default transport. In particular Proxy, which is set to http.ProxyFromEnvironment. This will make the client honor the HTTP_PROXY, HTTPS_PROXY and NO_PROXY env variables.
=> Clone default transport to honor http proxy config

pkg/curatedpackages/packageinstaller.go, pkg/curatedpackages/packageinstaller_test.go
- Skip package installation when controller is disabled in cluster spec.
=> Skippackageinstallation

release/Makefile
=> Fix default EKS-A release manifest URL in Makefile

controllers/factory.go, pkg/providers/cloudstack/reconciler/mocks/reconciler.go, pkg/providers/cloudstack/reconciler/reconciler.go, pkg/providers/cloudstack/reconciler/reconciler_test.go
[976](https://github.com/aws/eks-anywhere-internal/issues/976)
Adding IPValidator interface for full lifecycle api reconciler
=> Added Cloudstack IPValidator for lifecycle api

pkg/executables/executables.go, pkg/executables/executables_test.go
#5143 
Redact authenticated registry mirror username and password from CLI logs and support bundle
With this PR, when we use authenticated registry mirror, username and password will not be displayed on eksa-cli log and support bundle. 
`{"L":"V6","T":"2023-04-05T18:50:10.254Z","M":"Executing command","cmd":"/usr/bin/docker login x.x.x.x:443 --username ***** --password-stdin"}`
`2023-04-05T18:34:32.005Z	V6	Executing command	{"cmd": "/usr/bin/docker exec -i -e HELM_EXPERIMENTAL_OCI=1 -e HTTPS_PROXY= -e HTTP_PROXY= -e NO_PROXY= eksa_1680719601281607613 helm registry login x.x.x.x:443 --username ***** --password ***** --insecure"}`
`2023-04-05T18:35:17.183Z	V6	Executing command	{"cmd": "/usr/bin/docker run -d -i -v …
=> Redact authenticated registry mirror creds

internal/test/timer.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/vsphere/testdata/expected_results_main_md_update_machine_template.yaml, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
#5313 
When updating the worker machine group ref names, we would run into an error:
`Error: failed to upgrade cluster: generating capi spec: generating cluster api spec contents: getting eksa vsphere cluster Error from server (NotFound): vspheremachineconfigs.anywhere.eks.amazonaws.com "taylor1" not found`
This happened because we were referring to the new machine config as the old one and vice versa. So when we tried to `kubectl get` the old machine config to compare it to the new one, we were actually attempting to get the new one which doesn't exist yet, causing the error above.
This PR assigns the appropriate configs and the upgrade is now successful.
Upgraded all machine group ref names on a vsphere …
=> Fix worker node machine group ref name update

pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
#5313 
As the management cluster field is not set, until later in the flow, the `validateMachineConfigNameUniqueness` panics when there is a change in MachineGroupRef.name during the upgrade. 
Tested manually for both management and workload clusters for Vsphere and Cloudstack provider and the CLI does not panic. The upgrade still fails while changing `machineGroupRef.name` during the upgrade. This change just fixes the panic caused during the upgrade while changing `machineGroupRef.name` field. 
=> Fix nil pointer panic during upgrade of machineConfigName

controllers/factory.go, pkg/providers/cloudstack/reconciler/mocks/reconciler.go, pkg/providers/cloudstack/reconciler/reconciler.go, pkg/providers/cloudstack/reconciler/reconciler_test.go
[Implement the ProviderClusterReconciler interface: CNI#977](https://github.com/aws/eks-anywhere-internal/issues/977)
unit-test
=> Cloudstack reconciler cni

pkg/clusterapi/name.go, pkg/clusterapi/name_test.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/controlplane.go, pkg/providers/cloudstack/controlplane_test.go, pkg/providers/cloudstack/template.go, pkg/providers/cloudstack/template_test.go, pkg/providers/cloudstack/workers.go, pkg/providers/cloudstack/workers_test.go, pkg/providers/vsphere/template.go
This PR generates implements `WorkerSpec` function that generates a CloudStack specific CAPI spec for an EKS-A cluster worker nodes. It talks to the cluster with a client to detect changes in immutable objects and generates new names for them.
It also refactors the `generateTemplateBuilder` function to not return an error, as these checks are already being made during cluster config validations. Additional CloudStackMachineConfig validations will also be made as a phase in the reconcile before reconciling the workers. Additionally, we've also decided to refactor the `CloudStackTemplateBuilder` in the near future. Its methods will rely only on the `cluster.Spec`, therefore, soon `generateTemplateBuilder` will no longer be necessary and …
=> Generate CloudStack Workers CAPI objects

docs/content/en/docs/tasks/cluster/manually-renew-certs.md
*Description of changes:* In bottlerocket, the pki directory is mount to the container. Changing directory name would not take effect in container.
=> Fix etcd certs backup instruction

pkg/executables/export_test.go, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go
This speeds up the kubectl executable tests x15 (~30s -> ~2s).
It's a combination of running tests in parallel plus avoiding unnecessary extra long waits when testing the exponential backoff retries. The backoff changes have the biggest impact (-25s).
I suspect this can be trimmed down even further, since the 2s duration is very consistent and makes me thing there are more "waits" hidden in the tests.
=> Make kubectl tests faster

pkg/dependencies/factory.go, pkg/dependencies/factory_test.go
Part of #5565 
Respect `--no-timeouts` for awsiamauth installer.
Unit tests
=> Add notimeouts for awsiamauth

controllers/cluster_controller.go, controllers/cluster_controller_test.go, pkg/config/registry.go, pkg/config/registry_test.go, pkg/providers/docker/config/template-cp.yaml, pkg/providers/docker/docker.go, pkg/providers/docker/testdata/expected_results_mirror_with_auth_config_cp.yaml, pkg/providers/tinkerbell/template.go
When customers set up authenticated registry mirrors, the eks-a controller does not have access to the required env variables. Hence adding logic to read from registry-auth secret and setting Env on the controller pod.
*Testing:*
Built the eks-a controller and pushed to private registry. Tested changes on vsphere.
=> Fix regauth FLC

pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/eksd/installer.go, pkg/eksd/installer_test.go, pkg/eksd/upgrader.go
Part of #5565 
Respect `--no-timeouts` in eksd installer and upgrader.
Unit tests
=> Add notimeouts to eksd installer and upgrader

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/cluster_manager_wb_test.go, pkg/executables/clusterctl.go, pkg/executables/clusterctl_test.go, pkg/executables/export_test.go
#5576 
During upgrade of a management cluster. we take the back of management cluster resources before moving it to the kind cluster. This PR adds retries around `clusterctl move --to-directory` command so if the command fails intermittently due to network error, timeout or any other similar error, it doesn't fail and retries to take the backup.
=> Add retries around clusterctl move --to-directory command

pkg/dependencies/factory.go
Part of #5565 
When adding the networking dependency in factory, the `networkingBuilder` was called out of the `f.buildSteps` causing networking builder to be executed before `WithNoTimeouts` are applied. Fix the issue by moving `networkingBuilder` to the `buildSteps`, so that the build happens in the end when calling `f.Build()`.
Unit tests
=> Fix notimeouts for cilium

internal/pkg/ssm/command.go, internal/test/e2e/artifacts.go, internal/test/e2e/fluxGit.go, internal/test/e2e/oidc.go, internal/test/e2e/registryMirror.go, internal/test/e2e/run.go, internal/test/e2e/setup.go, internal/test/e2e/tinkerbell.go
Add timeout to the e2e command. This makes sure that the e2e test command itself times out instead of the SSM command timing out. With this change, we will be able to get the results of the tests that finished even if the instance timed out.
=> Add timeout to the e2e command

test/e2e/tinkerbell_test.go
We cannot run skip power action e2e test because nodes timeout waiting for ipxe if we power it on before cluster creation starts. Thus, to test out skip power action, added a single node e2e test to test out functionality.
=> Tinkerbell skip power action e2e test for a singlenode cluster

pkg/executables/executables_test.go
The test was reliant on an env value not being set. Now that precondition is enforced.
=> fixes redaction test flappiness

cmd/eksctl-anywhere/cmd/deprecated_importimages.go
Renames the file and adds a comment to make it clear this command is deprecated.
=> add a comment, and rename to make deprecation more obvious

test/e2e/tinkerbell_test.go
Updating Tinkerbell E2E test names to ensure Flux Github tests match the setupFluxEnv() and setupFluxGitEnv() regex patterns.
=> renaming github e2e tests

config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, config/manifest/eksa-components.yaml, release/api/v1alpha1/bundle_types.go, release/config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, release/config/crd/bases/anywhere.eks.amazonaws.com_releases.yaml, release/pkg/assets/config/bundle_release.go, release/pkg/bundles/eksd.go, release/pkg/operations/bundle_release_test.go, release/pkg/test/testdata/main-bundle-release.yaml
Add containerd tarball to the EKS-D section of the bundle manifest.
=> Add containerd tarball to bundle release manifest

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml, docs/content/en/docs/reference/clusterspec/baremetal.md, pkg/api/v1alpha1/cluster_types.go, pkg/providers/tinkerbell/config/template-cp.yaml, pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_disable_kube_vip.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_disable_kube_vip.yaml, pkg/providers/tinkerbell/tinkerbell_test.go
*Description of changes:* Allow users to disable cp load balancer (kube-vip) in Tinkerbell if they have their own load balancer
- unit test for template-cp.yaml
- e2e test with eksa controller and --bundles-override. `k get pods -A` shows that kube-vip pod is not running
=> Add option to disable cp load balancer

controllers/resource/template.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/cloudstack/template.go
This contains no other changes other than separating the template builder into it's own file. This is easier to navigate.
=> Move cloudstack template builder to template file

docs/content/en/docs/getting-started/local-environment/_index.md
The notes describing the expected file name (eksa-cluster.yaml) is not accurate if the instructions were followed - it will be mgmt.yaml.  Also, the example yaml output shown indicates that the metadata:name = mgmt.
I update the notes to indicate the filename will be "mgmt.yaml" (and added verbiage to say "if the instructions were followed)
NOTE:  there are a numerous references to "eksa-cluster.yaml" in other *.md files.  I have not proceeded far enough (yet) to know whether this matters.  Example:
```
docs//content/en/docs/tasks/cluster/cluster-iam-auth.md:    clusters/$CLUSTER_NAME/eksa-system/eksa-cluster.yaml
docs//content/en/docs/tasks/cluster/cluster-iam-auth.md:    git add eksa-cluster.yaml
```
Or
``` …
```
=> Update inaccurate notes

docs/content/en/docs/concepts/eksafeatures.md
Add Nutanix to the EKS-A and EKS comparison page. 
=> Add Nutanix to Compare EKS Anywhere and EKS page

cmd/eksctl-anywhere/cmd/applypackages.go, cmd/eksctl-anywhere/cmd/common.go, cmd/eksctl-anywhere/cmd/createpackages.go, cmd/eksctl-anywhere/cmd/deletepackages.go, cmd/eksctl-anywhere/cmd/describepackages.go, cmd/eksctl-anywhere/cmd/generatepackage.go, cmd/eksctl-anywhere/cmd/get.go, cmd/eksctl-anywhere/cmd/getpackage.go, cmd/eksctl-anywhere/cmd/getpackagebundle.go, cmd/eksctl-anywhere/cmd/getpackagebundlecontroller.go, cmd/eksctl-anywhere/cmd/installpackagecontroller.go, cmd/eksctl-anywhere/cmd/installpackages.go, cmd/eksctl-anywhere/cmd/listpackages.go, cmd/eksctl-anywhere/cmd/upgradepackages.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/dependencies/testdata/cli_tools_bundle.yaml
Co-authored-by: a-cool-train <acool@amazon.com>
*Issue #5396 *
Adds bundles-override to package cli commands for generate, apply, create, get, delete, describe, and list.
Without override-bundles flag example for get package
```
./eksctl-anywhere get packages --cluster mgmt -v 4
2023-04-13T20:39:57.565Z        V4      Reading bundles manifest        {"url": "https://dev-release-assets.eks-anywhere.model-rocket.aws.dev/bundle-release.yaml"}
2023-04-13T20:39:57.590Z        V2      Pulling docker image    {"image": "public.ecr.aws/l0g8r8j6/eks-anywhere-cli-tools:v0.15.1-eks-a-v0.0.0-dev-build.6720"}
2023-04-13T20:39:57.723Z        V3      Initializing long running container     {"name": "eksa_1681418397590899255", "image": …
```
=> Adding bundles-override to package cli commands

pkg/executables/helm.go
Modifies the `helm registry login` command to use the `--password-stdin` flag which prevents leaking the password on the process table.
This might also be the cause of a bug: https://github.com/aws/eks-anywhere-packages/issues/923
Though as far as I can tell, the helm registry login command still accepts the `--password flag`, though it prints a warning.
=> use --password-stdin to prevent process table leaking

cmd/eksctl-anywhere/cmd/root.go, cmd/eksctl-anywhere/main.go, pkg/console/console.go, pkg/console/console_test.go, pkg/logger/init.go, pkg/logger/pause.go, pkg/logger/pause_test.go, pkg/signals/signals.go
_Depends on: #5206_
This PR changes the warning currently output when a user `Ctrl`+`C`s into an interactive Q&A asking the user to confirm they really want to cancel. The warning still exists in its original form but is followed by a question. If the user responds with anything other than a capital `Y` the program continues. This ensures the user has a combination keystroke (`Shift`+`Y`) mitigating the risk of entering the wrong thing.
While the question is posed, console logging is redirected to a buffer. If the user chooses to continue logging collected while paused is dumped to the console before resuming normal logging.
```
Warning: Terminating this operation may leave the cluster in an irrecoverable state.
Are you sure you want to exit? [Y/n]: Y
```
The logic is executed on every …
=> Confirm cancelling when user cancels (Ctrl+C) CLI execution

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, test/e2e/vsphere_test.go, test/framework/workload.go
Add a 20 minute timeout to calls that delete clusters with kubectl for full lifecycle api e2e tests
=> Add Timeout to Delete Full Lifecycle API E2E

pkg/providers/nutanix/config/cp-template.yaml, pkg/providers/nutanix/testdata/expected_results_node_taints_labels.yaml, pkg/providers/nutanix/testdata/expected_results_oidc.yaml, pkg/providers/nutanix/testdata/expected_results_project.yaml, pkg/providers/nutanix/testdata/expected_results_registry_mirror.yaml
These were initially introduced through [eks-anywhere#4111](https://github.com/aws/eks-anywhere/pull/4111) and were intended to be a temporary fix until the nutanix imagebuilder changes were merged upstream in [image-builder#1046](https://github.com/kubernetes-sigs/image-builder/pull/1046).
=> Remove apt commands and iscsid initiation from Nutanix control plane kubeadmconfig

docs/content/en/docs/reference/eksctl/anywhere_apply_package(s).md, docs/content/en/docs/reference/eksctl/anywhere_copy_packages.md, docs/content/en/docs/reference/eksctl/anywhere_create_package(s).md, docs/content/en/docs/reference/eksctl/anywhere_delete_package(s).md, docs/content/en/docs/reference/eksctl/anywhere_describe_package(s).md, docs/content/en/docs/reference/eksctl/anywhere_generate_packages.md, docs/content/en/docs/reference/eksctl/anywhere_get_package(s).md, docs/content/en/docs/reference/eksctl/anywhere_get_packagebundle(s).md, docs/content/en/docs/reference/eksctl/anywhere_get_packagebundlecontroller(s).md, docs/content/en/docs/reference/eksctl/anywhere_install_package.md, docs/content/en/docs/reference/eksctl/anywhere_install_packagecontroller.md, docs/content/en/docs/reference/eksctl/anywhere_list_packages.md, docs/content/en/docs/reference/eksctl/anywhere_upgrade_packages.md
#5396 
Update EKS-A official doc w the --bundles-override flag for curated packages cmd with `make docgen`
=> Update curated package cmd doc with bundles override

internal/pkg/api/tinkerbell.go, test/e2e/multicluster.go, test/e2e/upgrade.go, test/framework/tinkerbell.go
Add some Tinkerbell helper methods to support new upgrade tests.
=> Add missing methods to support Tinkerbell upgrade tests

cmd/integration_test/build/buildspecs/tinkerbell-test-eks-a-cli.yml, cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml
Add 1.27 template envs for e2e tests
=> Add 1.27 template env for e2e

test/e2e/SKIPPED_TESTS.yaml
Last PR in https://github.com/aws/eks-anywhere/issues/5690
Renamed TestVSphereUpgradeKubernetesUbuntuAPI->TestVSphereUpgradeKubernetes123to124UbuntuWorkloadClusterAPI in https://github.com/aws/eks-anywhere/pull/5689. This re-enabled the test as desired, but we still need to clean up the old name from SKIPPED_TESTS.
N/A 
=> Remove Renamed Test from SKIPPED_TESTS

cmd/eksctl-anywhere/cmd/options.go, docs/content/en/docs/reference/eksctl/anywhere_create_cluster.md, docs/content/en/docs/reference/eksctl/anywhere_upgrade_cluster.md
Related issue: #5637 
Display the timeout flags in CLI help and doc.
```
$ eksctl anywhere create cluster -h
This command is used to create workload clusters
Usage:
anywhere create cluster -f <cluster-config-file> [flags]
Flags:
--bundles-override string             Override default Bundles manifest (not recommended)
--control-plane-wait-timeout string   Override the default control plane wait timeout (default "1h0m0s")
--external-etcd-wait-timeout string   Override the default external etcd wait timeout (default "1h0m0s")
-f, --filename string                     Filename that contains EKS-A cluster configuration
--force-cleanup                       Force deletion of previously created bootstrap cluster
-z, …
```
=> Display timeout flags in help command and doc

controllers/resource/reconciler.go, controllers/resource/template.go, controllers/resource/testdata/cloudstackEtcdadmcluster.yaml, controllers/resource/testdata/cloudstackKubeadmconfigTemplateSpec.yaml, controllers/resource/testdata/cloudstackKubeadmcontrolplane.yaml, controllers/resource/testdata/cloudstackMachineConfigSpec.yaml, controllers/resource/testdata/eksa-cluster-cloudstack-etcd.yaml, controllers/resource/testdata/eksa-cluster-cloudstack.yaml, controllers/resource/testdata/eksa-cluster-cloudstack_no_changes.yaml, internal/pkg/api/cloudstackmachines.go, pkg/api/v1alpha1/cloudstackmachineconfig.go, pkg/dependencies/factory.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/cloudstack/controlplane.go, pkg/providers/cloudstack/controlplane_test.go, pkg/providers/cloudstack/reconciler/reconciler_test.go, pkg/providers/cloudstack/spec.go, pkg/providers/cloudstack/template.go, pkg/providers/cloudstack/template_test.go, pkg/providers/cloudstack/validator.go, pkg/providers/cloudstack/validator_mocks.go, pkg/providers/cloudstack/validator_registry.go, pkg/providers/cloudstack/validator_test.go, pkg/providers/cloudstack/workers.go, pkg/providers/cloudstack/workers_test.go, pkg/providers/vsphere/controlplane_test.go, pkg/providers/vsphere/workers_test.go
The [CloudStackTemplateBuilder](https://github.com/aws/eks-anywhere/blob/2ca366517b41fede3256ec0e47e5de37b9f59a2a/pkg/providers/cloudstack/cloudstack.go#L633) has dependencies on `controlPlaneMachineSpec`, `WorkerNodeGroupMachineSpecs`, and `etcdMachineSpecs`. According to [here](https://github.com/aws/eks-anywhere/blob/50ee3e1e0705b769039fdff04d53e471e198dd50/controllers/resource/template.go#L181), it seems as though it was made prohibiting control plane and ETCD updates, and these provided arguments help to override what's in the provided spec. Given we are working on the new controller, we don't need this limitation anymore, it also makes the code made the code more complex. 
This PR does the following:
1. Removes dependencies from the …
=> Simplify CloudStack template builder 

docs/content/en/docs/reference/clusterspec/optional/cni.md, docs/content/en/docs/tasks/cluster/cluster-replace-cilium.md
This PR adds documentation detailing how a user can uninstall the EKS Anywhere Cilium CNI and provides e2e walk throughs of the process.
=> Add docs detailing how to uninstall EKS-A Cilium

pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/cloudstack/controlplane_test.go, pkg/providers/cloudstack/spec.go, pkg/providers/cloudstack/template.go, pkg/providers/cloudstack/template_test.go, pkg/providers/cloudstack/validator.go, pkg/providers/cloudstack/validator_test.go
[Set Default And Validate Control Plane Host Port when generate CAPI object#1280](https://github.com/aws/eks-anywhere-internal/issues/1280)
When creating a CloudStack cluster, the endpoint provided by the user should have a port specified. This is already done for the CLI, but not for clusters created through the API yet. However, it modifies the user input in the cluster.Spec to achieve this: This PR:
- Validates and sets a default control plane host port when generating the CloudStack CAPI objects. This will allow clusters created through the API to utilize a default port for the control plane endpoint if not specified, bringing it up to parity with the CLI. 
- Removes the side effect of editing the user input in the `cluster.Spec`. The …
=> Set default and validate control plane host port when generating CloudStack CAPI objects

cmd/integration_test/build/buildspecs/snow-test-eks-a-cli.yml, internal/test/e2e/run.go, internal/test/e2e/setup.go, internal/test/e2e/snow.go, pkg/providers/snow/validator.go, test/e2e/SKIPPED_TESTS.yaml, test/framework/snow.go
*Issue #, if available:* https://github.com/aws/eks-anywhere-internal/issues/1192
*Description of changes:* Enable simple snow e2e tests using the new snow CI devices
*Testing (if applicable):* Manually invoked the tests with codebuild, test was successful and verified that snow devices have been cleaned after testing.
=> Enable simple snow e2e tests in CI

controllers/resource/template.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go
Renamed AnyImmutableFieldChanged -> NeedNewMachineTemplate due to misleading name 
Added call to MachineConfig's Webhook (ValidateUpdate) inside validateMachineConfigImmutability
=> Updated CloudStack immutable field validation

pkg/git/providers/github/github.go, pkg/git/providers/github/github_test.go
The current regular expression for GitHub personal access tokens only supports specifying classic PATs. If a user tries to use a fine-grained access token, EKS-A blocks it because it doesn't conform to the regex. This PR expands this regex to support both types of tokens.
Fixes: #5764
=> Expand GITHUB_TOKEN regex to support fine-grained access tokens

pkg/providers/tinkerbell/assert.go, pkg/providers/tinkerbell/assert_test.go, pkg/providers/tinkerbell/cluster.go, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_proxy.yaml
Add validation for HookImagesURLPath if proxy configuration is specified in cluster config file. Hook image need to be hosted locally and should be accessible without using proxy if proxy is specified. 
=> Add validation for HookImagesURLPath for proxy configuration

pkg/executables/helm.go, pkg/providers/tinkerbell/stack/mocks/stack.go, pkg/providers/tinkerbell/stack/stack.go, pkg/providers/tinkerbell/stack/stack_test.go, pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_proxy.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md_proxy.yaml, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/upgrade.go, pkg/providers/tinkerbell/upgrade_test.go
With this PR, I am adding a functionality to enable proxy configuration for workload cluster create and upgrade for tinkerbell provider.
I have ran the following tests manually,
1. Management cluster create
2. Management cluster upgrade
3. Workload cluster create
4. Workload cluster upgrade (TODO)
=> Enable proxy configuration for tinkerbell workload cluster

pkg/providers/nutanix/template.go, pkg/providers/nutanix/template_test.go, pkg/providers/nutanix/testdata/eksa-cluster-iamauth.yaml, pkg/providers/nutanix/testdata/eksa-cluster-irsa.yaml, pkg/providers/nutanix/testdata/expected_results_iamauth.yaml, pkg/providers/nutanix/testdata/expected_results_irsa.yaml, test/e2e/nutanix_test.go
* Propagate AWS IAM Authenticator config, CA key, and CA cert files to KubeadmControlPlane config
* Propagate ServiceAccountIssuer to the KubeadmControlPlane API Server ExtraArgs
- Create a cluster with identityProviderRefs set to the AWSIamConfig manifest present and podIamConfig.serviceAccountIssuer set to the keycloak uri as prescribed [here](https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/optional/iamauth/)
- Verified the generated Kubeconfig for the IAM user can authenticate with API Server and access the resources in the cluster
- Followed the guide to [configure IRSA](https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/optional/irsa/) to wire up cluster keys with Keycloak instance, configure AWS roles and policies, and get …
=> Add IRSA & IAM Auth Support for Nutanix

controllers/factory.go, pkg/providers/cloudstack/reconciler/reconciler.go, pkg/providers/cloudstack/reconciler/reconciler_test.go
closes [Validate Machine Config#1260](https://github.com/aws/eks-anywhere-internal/issues/1260)
use cmk client to perform run time machine config validation
unit tests and manual testing
- successfully create wl cluster
- fail on nonexistent secret
- fail on nonexistent template
- fail on unmatched template between cp and worker node
=> cloudstack validate machine config

pkg/api/v1alpha1/cloudstackmachineconfig_types.go, pkg/api/v1alpha1/cloudstackmachineconfig_types_test.go, pkg/api/v1alpha1/cloudstackmachineconfig_webhook.go, pkg/api/v1alpha1/cloudstackmachineconfig_webhook_test.go, pkg/api/v1alpha1/machine_types.go, pkg/cluster/cloudstack.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/validator.go
Part of [Provider validations for ssh key #1217]( https://github.com/aws/eks-anywhere-internal/issues/1217)
This PR adds user and ssh key validation to the `cloudstackmachineconfig` webhook. This doesn't affect the current behavior for the CLI, because it defaults users and ssh keys if not provided.
Unit tests
- Create and upgrade a mgmt cluster:
- Create workload cluster with API.
- No users, user with empty name,  user with empty SSHAuthorizedKeys throws webhook error
- User specified with name and valid sshAuthorizationKey succeeds
- Update workload cluster with API.
- No users, user with empty name,  user with empty SSHAuthorizedKeys throws webhook error
- User specified with name and valid …
=> Add Users and SSH key validation in cloudstackmachineconfig webhook

pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/cloudstack/validator_test.go
This change fixes an issue where the CloudStackMachineConfig's userCustomDetails field could have a key updated and not trigger a the creation of a new template. The issue occurs only when the value of a key-value pair is an empty string. See #5791 for more details.
The cyclomatic complexity of the `NeedsNewMachineTemplate` function violated linting rules so has been refactored.
Further refactoring will be done on the `NeedsNewMachineTemplate` unit tests to turn them into table tests.
Fixes #5791
=> Fix CloudStack userCustomDetails not triggering creation of templates

pkg/providers/nutanix/config/cp-template.yaml, pkg/providers/nutanix/config/md-template.yaml, pkg/providers/nutanix/template.go, pkg/providers/nutanix/template_test.go, pkg/providers/nutanix/testdata/eksa-cluster-proxy.yaml, pkg/providers/nutanix/testdata/expected_results_proxy.yaml, pkg/providers/nutanix/testdata/expected_results_proxy_md.yaml
Propagate Proxy config for Nutanix templates.
- Created a proxy with tinyproxy on a ubuntu server VM
- Configure `proxyConfiguration` on cluster spec to point to the proxy and create a cluster successfully ([logs](https://app.warp.dev/block/vBn52cJUC5EGcLJuEUZLSK))
- Correlate whether the traffic from cluster is being routed through  the proxy
=> Add Proxy support for Nutanix

pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/tinkerbell_test.go
We are disallowing the ability to specify a different workload cluster tinkerbellip from the management cluster as we only look at the management cluster one as the source of truth. It is misleading when we override the value specified by the user in the CLI, so this will throw an error if the wrong ip is specified. 
This behavior matches what we do in the controller now: https://github.com/aws/eks-anywhere/pull/4808
unit tests
=> Add validation for tinkerbell ip for workload cluster to match management cluster

test/e2e/tinkerbell_test.go
Tinkerbell does not support external etcd, removing e2e for 1.27 for external etcd.
=> Remove incorrect e2e for external etcd

pkg/api/v1alpha1/cloudstackmachineconfig_types_test.go, pkg/api/v1alpha1/cloudstackmachineconfig_webhook.go, pkg/api/v1alpha1/machine_types.go, pkg/api/v1alpha1/nutanixmachineconfig.go, pkg/api/v1alpha1/nutanixmachineconfig_webhook_test.go, pkg/api/v1alpha1/vspheremachineconfig.go, pkg/api/v1alpha1/vspheremachineconfig_test.go, pkg/api/v1alpha1/vspheremachineconfig_types.go, pkg/api/v1alpha1/vspheremachineconfig_webhook.go, pkg/api/v1alpha1/vspheremachineconfig_webhook_test.go, pkg/cluster/vsphere.go, pkg/providers/vsphere/defaults.go
closes [#1217](https://github.com/aws/eks-anywhere-internal/issues/1217)
- Unit tests
- Manual testing
- Create a management cluster:
- Create and update workload cluster with API .
- No users
- User with empty name
- User with empty SSHAuthorizedKeys
- User specified with name and valid sshAuthorizationKey (succeeds)
=> Add users and ssh key validation to all provider machineconfig webhooks

config/tilt/kustomization.yaml, manager/main.go, pkg/controller/clusters/ipvalidator.go
Defaulting to v=4 was printing a lot of client-go and controller-runtime "debug" logs that added a lot of noise but no value.
Now it defaults to 0 and for tilt we bump it to 2, which adds a little more information from controller-runtime, specially during startup, but still avoids unnecessary noise.
=> Reduce controller's log verbosity

controllers/cluster_controller.go, controllers/cluster_controller_test.go, controllers/factory.go, manager/main.go, pkg/features/features.go
This allows us to test management cluster CP upgrades through the controller.
Not intended for the final user, only for internal testing.
=> Add exp flag for self managed cluster API upgrades

pkg/providers/cloudstack/cloudstack_test.go
Refactor the CloudStable unit tests for `NeedNewMachineTemplate` into table tests to make the covered cases clear.
Some tests were missing and have been added.
This work builds on #5801.
=> Refactor CloudStack `NeedNewMachineTemplate` unit tests into table tests

test/e2e/vsphere_test.go
Fixes failing vsphere 1.27 e2e tests
=> fix 1-27 e2es

internal/test/e2e/registryMirror.go
Since Tinkerbell and CloudStack use the same Harbor registry for CI tests, modify the regex to pick CloudStack tests and point them to the same harbor registry.
=> Modify regex to pick Harbor Regsitry for CloudStack tests

pkg/providers/tinkerbell/stack/mocks/stack.go, pkg/providers/tinkerbell/stack/stack.go, pkg/providers/tinkerbell/stack/stack_test.go, pkg/providers/tinkerbell/upgrade.go, pkg/providers/tinkerbell/upgrade_test.go
Currently, we don't override HookImagesURLPath even if a user specifies that in the clusterconfig file during an upgrade operation of a cluster. Thus, during upgrade it takes hookImage from the bundle only. This PR enables HookImage override for the upgrade operation for Tinkerbell provider.
I have tested these changes by upgrading a Tinkerbell cluster.
=> Support overriding HookImage for tinkerbell cluster upgrade

test/e2e/SKIPPED_TESTS.yaml, test/e2e/tinkerbell_test.go
Some of the e2e tests can not be run due to CI limitations. Hence skipping.
=> Skipping tests that can not be run today

pkg/providers/vsphere/reconciler/reconciler_test.go, pkg/providers/vsphere/validator.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
#5524 
Update datastore usage validation to account for space that will free up during upgrade. 
When we validate datastore usage during upgrades, we will now check if the machine config already exists on the cluster. If it exists, we will get the space that it is already using and add that to the availableSpace to prevent inaccurate datastore usage errors when modifying the disk size/replica count in machine configs.
=> Update datastore usage validation to account for space that will free up during upgrade

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml
Adding vms clean up command.
`./bin/test e2e cleanup cloudstack --cluster-name "main-" -v9
`
=> Adding cloudstack clean vms command

config/manager/manager.yaml
By injecting the pod metadata as env vars in the controller, we allow ClusterCacheTracker to detect that a management cluster is self managed. Then it uses direct access to the control plane (through the host in the incluster config) instead of going through the host defined in the capi kubeconfig, which in our case goes through the kube-vip load balancer.
More info: https://github.com/kubernetes-sigs/cluster-api/pull/6836
=> Use controller direct access to management cluster

test/e2e/registrymirror.go
Make registry mirror e2es use bundles override to avoid failing with mismatched tags during create vs delete
=> Make registry mirror e2es use bundles override

go.mod, go.sum
This update includes an important fix that handles a bmclib panic.
https://github.com/bmc-toolbox/bmclib/pull/304
https://github.com/tinkerbell/rufio/pull/77
=> Updating rufio go mod version

internal/pkg/api/vspheremachines.go, test/framework/vsphere.go
Fixes vSphere API e2e tests failing with:
`workload.go:47: Failed to apply workload cluster config: executing apply manifest: The VSphereMachineConfig "worker-0" is invalid: spec.users: Invalid value: []v1alpha1.UserConfiguration{v1alpha1.UserConfiguration{Name:"", SshAuthorizedKeys:[]string{"ssh-rsa...}}}: users[0].name is not set or is empty for VSphereMachineConfig worker-0, please provide a username`
We validate the username and ssh authorization key in the webhook now instead of defaulting because reconciliation would throw an error on a missing ssh key in the vsphere API e2e tests. Currently, when new worker node groups are created using `vsphere.WithWorkerNodeGroup`, the corresponding `VSphereMachineConfigs` do not get initialized …
=> Update ssh authorized in new worker node groups in API tests

pkg/executables/cmk.go, pkg/executables/cmk_test.go
```bash
2023-05-10T23:27:45.958Z    V-2 Failed to cleanup e2e vms on cloudstack {"error": "running cleanup for cloudstack vms: cleaning up VMs: map[***:virtual machines for cluster main not found]"}
```
We dont want to error when VMs were not found.
*Testing:*
```bash
./test e2e cleanup cloudstack -n "not-a-vm"
```
Also tested delete still works fine by deleting existing VMs.
=> Not erroring on VMs not found for cloudstack cleanup

test/e2e/SKIPPED_TESTS.yaml, test/e2e/cloudstack_test.go, test/e2e/conformance_test.go, test/e2e/docker_test.go, test/e2e/metallb.go, test/e2e/nutanix_test.go, test/e2e/snow_test.go, test/e2e/tinkerbell_test.go, test/e2e/vsphere_test.go, test/framework/cloudstack.go, test/framework/nutanix.go, test/framework/snow.go, test/framework/tinkerbell.go, test/framework/vsphere.go
Remove 1.22 e2e tests since we are deprecating that version in next release 
Added block comments/TODOs on some cloudstack tests so that we dont potentially miss any test cases when adding 1.24 e2e tests for that provider
=> Remove 1.22 e2e tests

pkg/api/v1alpha1/cloudstackmachineconfig_types.go
The CloudStack API comments didn't stick with our guidance of avoiding excessively long lines. This change carves up code comments into appropriate length lines and removes unnecessary comments.
See https://github.com/aws/eks-anywhere/blob/main/docs/developer/best-practice.md#line-length
=> Rework CloudStack API comments

internal/test/e2e/registryMirror.go
We are setting the general registry mirror env var but using values from Tinkerbell i.e. the colo lab.
Hence moving the regex check around to set the right variables.
=> Moving cloudstack registry mirror regex checks

pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go, pkg/features/features.go
[can't scale mgmt cluster cp with experimentalSelfManagedUpgrade flag#1328](https://github.com/aws/eks-anywhere-internal/issues/1328)
unit test
=> mgmt cluster can reconcile cp with EXP_SELF_MANAGED_API_UPGRADE flag

config/crd/bases/anywhere.eks.amazonaws.com_nutanixmachineconfigs.yaml, internal/pkg/api/taints.go, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_types_test.go, test/framework/cluster.go, test/framework/cluster/validations/cluster.go, test/framework/cluster/validations/cluster_test.go, test/framework/taints.go
[#1019 internal](https://github.com/aws/eks-anywhere-internal/issues/1019)
Currently, the API e2e tests containing taints do not verify that they are added correctly. This PR adds that validation for the api e2e test to verify taints using the cluster state validator.
Locally ran the api e2e tests:
`--- PASS: TestVSphereUpgradeLabelsTaintsUbuntuAPI`
`--- PASS: TestVSphereUpgradeLabelsTaintsBottleRocketGitHubFluxAPI `
=> Add validation for taints for API E2E tests

test/e2e/cloudstack_test.go, test/e2e/cloudstack_upgrade.go, test/framework/cloudstack.go, test/framework/cluster.go, test/framework/clustervalidator.go
[#1237 (internal)](https://github.com/aws/eks-anywhere-internal/issues/1237)
This PR add an e2e test that that tests the following features for the CloudStack API. Here we create a management cluster and workload cluster(s) and test it's features using sub tests. The benefits of this approach is the test utilizes a single management cluster rather than spinning a new one up every time to test a workload cluster feature.
- create and delete workload clusters for all supported k8 versions
- add and remove labels and taints
- scale up cp and replace existing worker node groups
- scale down cp and scaling worker node groups
See the testing doc for the full list of scenarios we are going to eventually cover …
=> Add cloudstack workload cluster API e2e tests 

test/e2e/constants.go, test/e2e/vsphere_test.go
The individual e2e test binaries would not build because this was defined in a provider specific file. Moving this to a central location allows binaries to be built correctly
`make e2e-tests-binary`
=> Define KubeVersions in e2e framework for all providers to access

cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/upgradecluster.go, cmd/eksctl-anywhere/cmd/validatecreatecluster.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/providers/vsphere/workers_test.go, pkg/validations/createvalidations/cluster_test.go, pkg/validations/createvalidations/identityproviders_test.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/kubectl.go, pkg/validations/mocks/kubectl.go, pkg/validations/upgradevalidations/cluster_test.go, pkg/validations/upgradevalidations/poddisruptionbudgets.go, pkg/validations/upgradevalidations/poddisruptionbudgets_test.go, pkg/validations/upgradevalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations_test.go, pkg/validations/upgradevalidations/upgradeskipvalidations.go, pkg/validations/upgradevalidations/upgradeskipvalidations_test.go, pkg/validations/upgradevalidations/versions_test.go, pkg/validations/validation_options.go
https://github.com/aws/eks-anywhere/issues/5189
This PR introduces preflight upgrade validations for clusters having pod disruption budgets. If a cluster has any pod disruption budgets active on it, EKSA will error out for upgrade cluster command. We provide a flag for the users to skip the preflight validations if they wish to. 
The design doc for this issue is here https://github.com/aws/eks-anywhere/pull/5685
The help command looks like this:
```
This command is used to upgrade workload clusters
Usage:
anywhere upgrade cluster [flags]
Flags:
--bundles-override string             Override default Bundles manifest (not recommended)
.....
--per-machine-wait-timeout string     Override the default machine wait timeout per machine (default …
```
=> Preflight upgrade validations for pod disruption budgets 

test/e2e/docker_test.go, test/e2e/metallb.go, test/e2e/nutanix_test.go, test/e2e/tinkerbell_test.go, test/e2e/vsphere_test.go
Based on the current logic (https://github.com/aws/eks-anywhere/blob/main/test/framework/cluster.go#L1076-L1085), cluster name by default consists of default cluster name and hashing of the test name. This results in the same cluster name across loops within the same e2e test.
=> Make different cluster name across loops within the same e2e test

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml, cmd/integration_test/build/buildspecs/conformance-eks-a-cli.yml, pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/api/v1alpha1/testdata/cluster_1_25_cloudstack.yaml, pkg/providers/cloudstack/cloudstack_test.go, test/e2e/SKIPPED_TESTS.yaml, test/e2e/cloudstack_test.go, test/framework/cloudstack.go
The change adds support to Kubernetes 1.24 for Cloudstack provider. E2E tests were added to cover K8s 1.24 version. 
The pre-flight validation was changed to check for kubernetes version 1.25 or higher in the cluster spec.
The change was tested out manually using bundle override, and the cluster creation was successful.
=> Adding k8s 1.24 support for cloudstack provider

pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go
These tests validate the `NeedsNewTemplate()` algorithm behaves as expected when the disk offering turns to nil.
Related to an issue found where removing disk offerings doesn't trigger a new template to be created.
=> Add missing unit tests for CloudStacks needs template detection

go.mod, go.sum
Upgrading the etcdadm-controller to fix a security issue https://github.com/aws/etcdadm-controller/pull/29
=> Update etcdadm-controller to v1.0.6-rc3

pkg/task/task.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
#5891 
Moving the force cleanup to right before the creation of the bootstrap cluster to ensure we have the bootstrap cluster until it is absolutely needed to clean up. 
unit tests, functional test
=> Move force cleanup of bootstrap cluster after preflight validations

docs/content/en/docs/reference/packagespec/credential-provider-package/v0.1.0.md
=> changing example keys in doc to not get caught by appsec scans

internal/pkg/api/cloudstack.go, test/e2e/cloudstack_test.go, test/e2e/cloudstack_upgrade.go, test/framework/cloudstack.go, test/framework/cluster.go, test/framework/cluster/validations/cloudstack.go, test/framework/cluster/validations/cloudstack_test.go, test/framework/flux.go, test/framework/multicluster.go
[#1237 internal](https://github.com/aws/eks-anywhere-internal/issues/1237)
This PR add an e2e test that that tests the following features for the CloudStack API
- Added TestCloudStackKubernetes124RedHatAPI that tests the API with k8s 1.24
- Added new workload cluster TestCloudStackMulticlusterWorkloadClusterAPI that tests the API with k8s 1.24
- Added more upgrade tests to TestCloudStackMulticlusterWorkloadClusterAPI (and for GitOps):
- add and remove cloudstack availability zones
- update cilium enforcement policy mode to 'always'
- Added TestCloudStackMulticlusterWorkloadClusterWithNewSecretCredentialsAPI  (and for GitOps) that tests:
- creating new secret and creating a workload cluster that uses the new secret
See the testing doc for …
=> Add CloudStack API e2e tests

pkg/providers/cloudstack/machinetemplate.go, pkg/providers/cloudstack/testdata/test_worker_spec.yaml, pkg/providers/cloudstack/workers_test.go
A subset of fields for the EKSA CloudStack API do not trigger creation of new CAPI templates when they are removed. The issue stems from the DeepDerivative function used to compare old with new to identify a diff. It does not compare fields when their type is defaulted meaning removal of the data all together isn't considered a change.
This change ensures we identify a diff when removing the fields that would have previously gone unnoticed.
__Example__
```go
old := CloudStackMachineConfig{
... 
UserCustomDetails: map[string]string{"foo": "bar"}
}
new := CloudStackMachineConfig{
...
UserCustomDetails: nil
}
// DeepDerivative(new, old) wouldn't identify a diff because UserCustomDetails is set
// to its default value.
```
Also see https://github.com/aws/eks-anywhere-internal/issues/1327.
=> Patch incorrect CloudStack upgrade comparison

internal/aws-sdk-go-v2/service/snowballdevice/doc.go, internal/test/timer.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/clustermanager/retrier_client.go, pkg/executables/clusterctl.go, pkg/executables/clusterctl_test.go, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go, test/e2e/cloudstack_upgrade.go, test/e2e/constants.go
When a management cluster is getting upgraded, in the current workflow, all the CAPI clusters, their respective dependents including machines, secrets, etc get moved from the workload management cluster to bootstrap cluster. After the workload cluster gets upgraded, the management components are moved back from bootstrap cluster back to the workload cluster. This process is error prone and an issue could result in all CAPI objects being lost. Another issue with this is checking and expecting the status of all clusters to be ready during management cluster upgrade which is not always possible, especially in a more established environment.
This change only checks for management cluster's status and only moves the management cluster objects back and forth to the …
=> Only move management cluster objects during management cluster upgrade

test/e2e/SKIPPED_TESTS.yaml, test/e2e/tinkerbell_test.go
Skips `TestTinkerbellUpgrade127MulticlusterWorkloadClusterWorkerScaleup` and `TestTinkerbellUpgrade127MulticlusterWorkloadClusterWorkerScaleDown` due to hardware limitations
Skips `TestTinkerbellKubernetes127RedHatSimpleFlow` as it cannot be run in our CI right now
Re-enables a couple packages tests as well
=> Skip tinkerbell tests that cannot be run in CI

pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
#5517 
Adding a warning that this field and functionality will not be supporting starting from the next release. Making this the first warning that appears when running the CLI for create and upgrade if `disableCSI` is set to `false`, which means that the user expects to have the vsphere csi driver and storage class installed on the cluster. We have documentation today on what it entails to disable it and we will add more information to the docs about this deprecation: https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/vsphere/#disablecsi-optional
Output:
```
⚠️  Warning: Installing CSI through EKS Anywhere is deprecated. Refer to the official documentation for more details on the disableCSI field in VSphereDatacenterConfig
✅ …
```
=> Add warning to deprecate disableCSI through CLI

internal/test/e2e/ipmanager.go, internal/test/e2e/run.go
Currently, the regular and airgapped tinkerbell tests are using independent IP managers.
This causes these tests to potentially end up with the same IPs causing conflicts.
This PR solves this problem by reusing same IP Manager for all tinkerbell tests.
=> Reuse same IP Manager for all tinkerbell tests

docs/content/en/docs/tasks/cluster/cluster-upgrades/baremetal-upgrades.md, docs/content/en/docs/tasks/cluster/cluster-upgrades/vsphere-and-cloudstack-upgrades.md
Resolves #5212 
Callout in upgrade doc
- Minor version skip upgrade is not allowed
- New image/template should be built during version upgrade
- Upgrades should not be run from ephemeral nodes
=> Improve upgrade doc

test/e2e/docker_test.go, test/framework/workload.go
Skip Cilium upgrade tests introduced a problem where a subset of tests that validate a cluster was deleted failed because it attempted to build a client to the workload cluster. 
Building the clients isn't necessary for the Skip Cilium upgrade tests, this PR removes it.
=> Patch skip Cilium upgrade tests

pkg/executables/cmk.go, pkg/executables/cmk_test.go, test/framework/cloudstack.go, test/framework/executables.go, test/framework/template.go, test/framework/vsphere.go
For CloudStack e2e tests we get the template names from the secret value. When we change eks-d version, template names get out of sync which makes e2e test failure until we change the template name in the secret.
To avoid this, this PR includes a logic to select the right template from the test runner itself and by not depending on the secret value. It looks for template name in below order,
1. Look for explicit configuration through an env var: "T_CLOUDSTACK_TEMPLATE_{osFamily}_{eks-d version}" eg. T_CLOUDSTACK_TEMPLATE_REDHAT_KUBERNETES_1_23_EKS_22. This should be used for explicit configuration, mostly in local development for overrides.
2. If not present, look for a template if the default templates: "{eks-d version}-{osFamily}" eg. …
=> Improve CloudStack E2E template selection logic

test/e2e/cloudstack_upgrade.go
Unfortunately in CloudStack networks cannot be shared between zones. So that means each zone has its own set of unique networks. The ControlPlane IP must be in the same network as the zone for a cluster to utilize it, which means this test is invalid.
```
--- PASS: TestCloudStackMulticlusterWorkloadClusterAPI (2407.06s)
--- PASS: TestCloudStackMulticlusterWorkloadClusterAPI/add_and_remove_labels_and_taints#01 (698.41s)
--- PASS: TestCloudStackMulticlusterWorkloadClusterAPI/add_and_remove_labels_and_taints (935.45s)
--- PASS: TestCloudStackMulticlusterWorkloadClusterAPI/scale_up_and_down_cp_and_worker_node_group_#01 (330.54s)
--- PASS: TestCloudStackMulticlusterWorkloadClusterAPI/scale_up_and_down_cp_and_worker_no …
```
=> Remove invalid update availability zone API test

test/e2e/tinkerbell_test.go
*Description of changes:* Splitting package tinkerbell tests by K8 versions since the current infrastructure is not designed to handle multiple test cases together.
=> Update package tinkerbell tests

test/e2e/cloudstack_test.go
Cloudstack e2e for workload cluster proxy config using API.
```
--- PASS: TestCloudStackKubernetes123RedhatProxyConfigMulticluster (1069.59s)
PASS
```
=> Cloudstack e2e for workload cluster proxy config using API

internal/pkg/api/oidc.go, test/e2e/cloudstack_test.go, test/e2e/side_effects.go, test/framework/cloudstack.go, test/framework/cluster.go, test/framework/oidc.go
This makes the test more realistic. It uses more eks-a features which increases the tested surface area and reduces the chances of a bug eluding this check.
Ran the 1.23 test manually. The 1.24 won't pass until we cut a new release, since 0.15 didn't support kubernetes 1.24 for cloudstack.
=> Improve cloudstack side effects e2e test

test/e2e/SKIPPED_TESTS.yaml
Skip http proxy e2e tests. We don't yet have a tested set up for http proxy in our e2e infrastructure.
=> Skip http e2e tests

release/cmd/release.go, release/pkg/assets/archives/archives_test.go, release/pkg/assets/images/images_test.go, release/pkg/assets/manifests/manifests_test.go, release/pkg/filereader/file_reader.go, release/pkg/filereader/file_reader_test.go, release/pkg/images/images.go, release/pkg/operations/bundle_release_test.go, release/pkg/test/testdata/main-bundle-release.yaml
The bundle number for dev bundles currently are defaulted to 1. This prevents us from running E2E test for workload cluster creation with previous minor release when management cluster is created from main, as there is a pre-flight validation checking the bundle numbers of workload and management cluster. This change assigns the build number as bundle number for dev builds. 
=> Assign buildNumber as bundle number for Dev Build

docs/content/en/docs/clustermgmt/support/supportbundle.md
*Description of changes:* There was a small typo in the alias to redirect requests for https://anywhere.eks.amazonaws.com/docs/tasks/troubleshoot/supportbundle/ to https://anywhere.eks.amazonaws.com/docs/clustermgmt/support/supportbundle/. This PR fixes that.
=> Fixed broken alias to supportbundle

test/e2e/cloudstack_test.go, test/e2e/multicluster.go, test/e2e/upgrade_from_latest.go
E2E test for Creating Management Cluster with current eks-a version and create workload cluster with the previous eks-a version to check for backward workload cluster create support. The change also alters the pre-flight that checks for bundle number to skip the bundle validation during dev build to enable running this test against main. 
=> E2E test for workload cluster creation from prev eksa version

test/framework/vsphere.go
For vSphere provider, e2e tests for ex TestVSphereKubernetes124UbuntuUpgradeFromLatestMinorRelease, TestVSphereKubernetes123to124UpgradeFromLatestMinorReleaseBottleRocketAPI, etc to upgrade from minor latest release to current latest release were failing. This PR resolves that issue. 
=> Fixed minor version issue for getting template name for vSphere provider

pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go, pkg/api/v1alpha1/versionskew.go, pkg/api/v1alpha1/versionskew_test.go, pkg/validations/upgradevalidations/cluster_test.go, pkg/validations/upgradevalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations_test.go, pkg/validations/upgradevalidations/versions.go, pkg/validations/upgradevalidations/versions_test.go
https://github.com/aws/eks-anywhere-internal/issues/1252
Kubernetes version skew check for cluster webhook. This validation is a part of our cli validations, including it for the controller as well.
- unit tests
- Controller validations for docker
```
mpaygude@bcd0746652e3 eks-anywhere-1 % k apply -f docker-w1.yaml
dockerdatacenterconfig.anywhere.eks.amazonaws.com/docker124-w1 unchanged
The Cluster "docker124-w1" is invalid: spec: Invalid value: "1.26": only 1 minor version skew is supported
mpaygude@bcd0746652e3 eks-anywhere-1 % k apply -f docker-w1.yaml
dockerdatacenterconfig.anywhere.eks.amazonaws.com/docker124-w1 unchanged
The Cluster "docker124-w1" is invalid: spec: Invalid value: "2.26": major version …
```
=> Kubernetes version skew check for cluster webhook

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml, config/manifest/eksa-components.yaml, internal/pkg/api/cluster.go, pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_types_test.go, pkg/networking/cilium/templater.go, pkg/networking/cilium/templater_test.go, pkg/networking/cilium/upgrade_plan.go, pkg/networking/cilium/upgrade_plan_test.go, pkg/networking/cilium/upgrader.go, pkg/networking/cilium/upgrader_test.go
Adds support for configuring the egress-masquerade-interfaces option in Cilium CNI via eks-a cluster spec. This allows users to configure this setting at cluster create as well as upgrade the setting.
Users can configure this setting like so:
```yaml
clusterNetwork:
cniConfig:
cilium:
egressMasqueradeInterfaces: eth+
```
where `egressMasqueradeInterfaces` expects a string that is an interface name or an interface prefix.
For more context on `egressMasqueradeInterfaces`:
https://docs.cilium.io/en/v1.13/network/concepts/masquerading/#iptables-based
Checked the cilium config map to validate that the setting had been configured correctly, and validated that the setting could be changed via upgrades.
Also validated …
=> Add egress-masquerade-interfaces option to cilium

docs/content/en/docs/getting-started/ports/_index.md
Seems syslog messages are sent from the host that is getting provisioned to boots. Example logs from hubble observe (using host firewall with cilium community):
```
Jun  5 08:17:26.198: HOSTIP:56019 (remote-node) -> BOOTSIP:514 (host) policy-verdict:none INGRESS AUDITED (UDP)
Jun  5 08:17:28.266: HOSTIP:35963 (remote-node) -> BOOTSIP:514 (host) policy-verdict:none INGRESS AUDITED (UDP)
```
This PR will add the UDP 514 to the list of ports for bare-metal provider.
=> add syslog port to the list of used ports for Bare Metal provider

config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, config/manifest/eksa-components.yaml, release/api/v1alpha1/bundle_types.go, release/config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, release/pkg/assets/config/bundle_release.go, release/pkg/bundles/vsphere.go, release/pkg/operations/bundle_release_test.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.16-bundle-release.yaml
Remove vsphere-csi-driver project from bundle release. This will be removed in the next iteration.
=> Remove vsphere-csi-driver project from bundle release

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml, controllers/cluster_controller.go, controllers/cluster_controller_test.go, internal/test/testdata.go, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/condition_consts.go, pkg/api/v1alpha1/condition_types.go, pkg/controller/clusters/status.go, pkg/controller/clusters/status_test.go
#5628 
Changes to the Cluster status as per the [proposal](https://github.com/aws/eks-anywhere/pull/6005). Added:
- Added ObservedGeneration field
- ControlPlaneInitialized condition
- Unit testing
- Manual testing
=> Add observedGeneration and ControlPlaneInitialized condition to ClusterStatus

cmd/eksctl-anywhere/cmd/import_images.go, pkg/curatedpackages/curatedpackages.go, pkg/types/contextkey.go
*Issue #, if available:* When `--insecure` is passed `eksctl-anywhere import images` command, curated packages yaml bundles cannot be pushed to registry mirror with self generated cert. The following error will show:
`x509: certificate signed by unknown authority`
*Description of changes:* Insecure flag is applied to oras
*Testing (if applicable):* Manual invoked eksctl-anywhere import images with and without insecure flag.
=> Apply insecure flag to oras copy

release/api/v1alpha1/artifacts.go
These are being removed in #5659 but this is just a quick fix for the download/import tests.
=> Remove vsphere-csi-driver artifacts from images list

pkg/providers/vsphere/reconciler/reconciler.go, pkg/providers/vsphere/reconciler/reconciler_test.go
Set vsphere creds for CP and CSI. These weren't being set in the reconciler previously.
The data in the secret looks like this
```
password: UmlzaGx
passwordCP: UmlzaGx
passwordCSI: UmlzaGx
username: W1hem9uLmNvbQ==
usernameCP: W1hem9uLmNvbQ==
usernameCSI: W1hem9uLmNvbQ==
```
- Using updated controller image and tested it out on vsphere clusters.
=> Set vsphere creds for CP and CSI

test/e2e/cloudstack_test.go, test/e2e/cloudstack_upgrade.go, test/e2e/docker_test.go, test/e2e/side_effects.go, test/e2e/vsphere_test.go, test/framework/cloudstack.go, test/framework/cluster.go, test/framework/docker.go, test/framework/nutanix.go, test/framework/snow.go, test/framework/tinkerbell.go, test/framework/vsphere.go
E2E tests for modular upgrades. 
This verifies that upgrading the mgmt cluster EKS-A minor version does not affect workload custers
Ran docker E2E
=> Add e2e tests for modular upgrades

controllers/cluster_controller.go, controllers/cluster_controller_test.go, internal/test/testdata.go, pkg/api/v1alpha1/condition_consts.go, pkg/controller/clusterapi.go, pkg/controller/clusterapi_test.go, pkg/controller/clusters/status.go, pkg/controller/clusters/status_test.go
Issue #, if available:
#5628 
Changes to the Cluster status as per the the proposal [here](https://github.com/aws/eks-anywhere/pull/6005):
- WorkersReady condition
- Unit testing
- Manual testing
=> Add WorkersReady condition to cluster status

test/e2e/vsphere_test.go, test/framework/vsphere.go
CSI was removed but vSphere API e2e tests were not updated. 
This PR removes a validation that checks if the CSI driver is available and ready as well as removing attempts to delete CSI resources from a cluster.
vSphere API tests
=> Remove CSI related code from vSphere API E2E

pkg/providers/snow/validator.go, pkg/providers/snow/validator_test.go
The snow software version comparison used string, causing problem for Snowblade devices, which use version of 1012.
```
2023-06-23T23:04:00.510Z	V0	❌ Validation failed	{"validation": "snow Provider setup is valid", "error": "setting defaults and validate snow config: invalid cluster config: the software version installed [1012] on device [192.168.1.57] is below the minimum supported version [102]", "remediation": ""}
```
Convert the software version to integer and compare
* make, all unit tests passed
* patched eksa and successfully created cluster on snowblade devices.
=> Convert snow software version to integer and compare.

docs/content/en/docs/clustermgmt/cluster-scale/baremetal-scale.md, docs/content/en/docs/clustermgmt/cluster-upgrades/baremetal-upgrades.md, docs/content/en/docs/getting-started/baremetal/bare-preparation.md, docs/content/en/docs/getting-started/baremetal/baremetal-getstarted.md
Clarify multi workload cluster creation limits for Tinkerbell controller. This unblocks the users from being able to simultaneously create multiple workload clusters using the controller.
=> Clarify multi workload cluster creation limits for Tinkerbell controller

pkg/providers/tinkerbell/reconciler/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler_test.go
Fix reconcile return for tinkerbell hardware failures with controller. The controller was not reconciling for upgrades if changes were made to the hardware as they are not eksa objects.
- Manual testing using the controller.
=> Fix reconcile return for tink hardware failures with controller

pkg/cluster/config_manager.go, pkg/cluster/config_manager_test.go
#6096 
The config yaml is parsed by the [ConfigManager](https://github.com/aws/eks-anywhere/blob/d8575bbd2a85a6c6bbcb1a54868cf7790df56a63/pkg/cluster/config_manager.g) at the beginning of cluster creation/upgrade and added to an [ObjectLookup](https://github.com/aws/eks-anywhere/blob/d8575bbd2a85a6c6bbcb1a54868cf7790df56a63/pkg/cluster/config_manager.go#L156) that maps the objects with keys in the form of `<apiVersion><kind><name>`, and if the APIVersion field is empty then the resulting key would be `<kind><name>`.
Later on, it is attempted to be retrieved by dedicated object processors in a [ConfigManagerEntry](https://github.com/aws/eks-anywhere/blob/d8575bbd2a85a6c6bbcb1a54868cf7790df56a63/pkg/cluster/vsphere.go#L9). E.g. …
=> Validate APIVersion is set when parsing EKSA config yaml

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go
https://github.com/aws/eks-anywhere/issues/6097
don't support kindnetd except docker
unit tests
=> preflight block kindnetd

internal/test/files.go, pkg/executables/clusterctl.go, pkg/executables/clusterctl_test.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
https://github.com/aws/eks-anywhere-internal/issues/1429
In the event of an upgrade failure, take a backup of management components on bootstrap cluster to ensure latest backup is closest to cluster state.
Modified `BackupManagement` to not immediately overwrite existing backups unless `clusterctl move` succeeds. This is to prevent partial backups in the event of an error in `clusterctl move`
Unit tests and manually run
=> adding bootstrap backup for upgrade failure

.github/PULL_REQUEST_TEMPLATE.md
Add docs section to PR template so that we can be more mindful of adding docs changes when creating PRs.
=> Add docs section to PR template

pkg/networking/cilium/templater.go, pkg/networking/cilium/templater_test.go
These were added in Cilium v1.13.x, but it was not backported to v1.12.x, so we need to temporarily add these tolerations to account for the node role deprecations in different upstream Kubernetes versions. We can remove this we upgrade to Cilium v1.13.x
Upgrade cluster with Cilium v1.12
Skipping the unit test for now but it passes when running upgrade. I need to update the mapMatcher to accommodate this in the unit test
=> Add node role tolerations for cilium

docs/content/en/docs/packages/prereq.md, docs/content/en/docs/packages/troubleshoot.md
This PR removes associated docs for manually triggerring the` cron-ecr-renew` cronjob, which is only installed when BottleRocket semVersion is <= 1.13.1 according to [here](https://github.com/aws/eks-anywhere-packages/blob/cea344731eeded5b4b2b628f2752b199526cb4cd/charts/eks-anywhere-packages/templates/_helpers.tpl#L130C23-L130C23). In the [most recent minor version](https://github.com/aws/eks-anywhere-build-tooling/blob/release-0.16/projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES) of EKS-A uses BR version >= 1.14.0.  …
=> Remove deprecated docs referencing cron-ecr-renew cronjob

test/e2e/docker_test.go, test/e2e/vsphere_test.go, test/framework/cluster.go
We are setting OIDCConfig in the workload clusters in this test, so we need to set OIDC env vars in E2E infra for management cluster upgrade side effects tests by mentioning OIDC in test name
=> Fix side effects E2E tests

Makefile, scripts/prepare_release_artifacts.sh
Release artifact preparation is a manual task that requires downloading binaries and generating checksum files. This change simplifies the process by downloading all binaries and generating the checksums in a single Make target.
The result of the `prepare-release-artifacts` target is a directory, `release-artifacts` containing checksum files and tarballs. Additionally, this PR patches checksum generation to include arm64 binaries.
Example:
```
eks-anywhere > make prepare-release-artifacts                                                       
Using standard BUNDLE_MANIFEST_URL ... and RELEASE_MANIFEST_URL ...                              
scripts/prepare_release_artifacts.sh                                                                
Building checksum files... …
```
=> Simplify release artifact preparation

cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/options.go, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_types_test.go, pkg/cli/createclusterdefaulter.go, pkg/cli/createclusterdefaulter_test.go, pkg/cli/doc.go, pkg/cluster/defaults.go, pkg/cluster/defaults_test.go, pkg/config/config.go, pkg/config/vsphereuser.go, pkg/config/vsphereuser_test.go, pkg/defaulting/runner.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/providers/validator/validate.go, pkg/providers/validator/validate_test.go, pkg/providers/vsphere/reconciler/reconciler_test.go, pkg/providers/vsphere/validator_test.go
Set skip ip annotation on cluster create when skip ip check flag is passed to the CLI. This is done for future work where the CLI would be using the controller to create workload clusters and the control plane ip validation needs to be skipped by the controller.
- unit tests
- test manually on vsphere cluster
=> Set skip ip annotation on cluster create for skip ip check flag

docs/content/en/docs/getting-started/install/_index.md
https://github.com/aws/eks-anywhere/pull/5592/files#diff-c5bfbb0cb70e1d5c90670d23997ef3e806e7aec7afef035050f9a3dfe2312e08 remove the notes but not reference to the notes.
=> Remove missing link to newer ubuntu version support doc

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml, controllers/cluster_controller.go, controllers/cluster_controller_test.go, controllers/cluster_controller_test_test.go, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_types_test.go, pkg/controller/clusters/ipvalidator.go, pkg/controller/clusters/ipvalidator_test.go, pkg/controller/clusters/validations.go, pkg/controller/clusters/validations_test.go, pkg/providers/cloudstack/reconciler/reconciler.go, pkg/providers/cloudstack/reconciler/reconciler_test.go, pkg/providers/docker/reconciler/reconciler_test.go, pkg/providers/nutanix/reconciler/reconciler.go, pkg/providers/snow/reconciler/reconciler.go, pkg/providers/snow/reconciler/reconciler_test.go, pkg/providers/tinkerbell/reconciler/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler_test.go, pkg/providers/vsphere/reconciler/reconciler.go, pkg/providers/vsphere/reconciler/reconciler_test.go
Issue #, if available:
#5628 
Changes to the Cluster status as per the the proposal [here](https://github.com/aws/eks-anywhere/pull/6005):
- Added FailureReason
- Unit testing
- Manual testing
=> Add FailureReason to Cluster status

go.mod, go.sum
We patched a security vuln in our runc dep using a replace directive because dependencies couldn't build with a proper upgrade.
Our deps have since updated meaning the replace directive isn't required and we can just upgrade.
=> Remove runc replace directive in go.mod

pkg/clients/kubernetes/runtimeclient.go, pkg/clients/kubernetes/runtimeclient_test.go, pkg/clusterapi/machine_health_check.go, pkg/clusterapi/machine_health_check_test.go, pkg/clusterapi/name.go, pkg/clusterapi/name_test.go, pkg/clustermanager/cluster_manager.go
Refactor machine health checks to use cluster and kubernetes.Object. Also convert templater method that converts objects to yaml a generic method.
- unit tests
- manual tests
N/A
=> Refactor machine health checks to use cluster and kubernetes.Object

pkg/providers/tinkerbell/testdata/expected_results_bottlerocket_upgrade_cert_bundles_config_cp.yaml, pkg/providers/tinkerbell/testdata/expected_results_bottlerocket_upgrade_cert_bundles_config_md.yaml, pkg/providers/tinkerbell/tinkerbell_test.go
Verifies [6095](https://github.com/aws/eks-anywhere/pull/6095)  for cert bundles in `TinkerbellMachineTemplate` manifest.
The issue [6108](https://github.com/aws/eks-anywhere/issues/6108) was also happening due to same incorrect way of splitting yaml as mentioned in PR [6095](https://github.com/aws/eks-anywhere/pull/6095) and the #6095 PR helped fixing the same. 
This PR validates the same fix for cert bundles config as well.
=> Add test to validate generated tinkerbell manifests for upgrade with cert bundles

pkg/api/v1alpha1/nutanixdatacenterconfig_webhook_test.go, pkg/api/v1alpha1/nutanixmachineconfig_webhook_test.go
envtest was only being used to test the "setup with manager" method of some webhooks. There is no actual logic there, it's just boilerplate, so the benefit of unit testing it is minimal. However, adding envtest makes testing the package quite slower (from the milisecond range to 6s).
=> Remove dependency on envtest from api package

pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_types_test.go
Since Name is now required, we can use is as the key for the comparison lookup and stop relying on "serialization" for the compare logic.
=> Refactor WorkerNodeGroupConfiguration slice comparison

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml, config/manifest/eksa-components.yaml, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_types_test.go
Added secondary kubernetesVersion field under workerNodeGroupConfiguration
=> Modular k8s upgrade manifests

pkg/controller/serverside/reconcile.go, pkg/controller/serverside/reconcile_test.go, pkg/networking/cilium/client.go, pkg/networking/cilium/reconciler/fetch.go, pkg/networking/cilium/reconciler/reconciler.go
The new Cilium version changes the port number for `envoy-metrics` and `prometheus` but the field names remained the same. This caused "duplicate value" errors when upgrading to the new Cilium version using server-side apply because the merge key for these fields is the port number, not the name. See below:
`"err":"failed to reconcile object /v1, Kind=Service, kube-system/cilium-agent: Service \"cilium-agent\" is invalid: spec.ports[1].name: Duplicate value: \"envoy-metrics\"","errVerbose":"Service \"cilium-agent\" is invalid`
To alleviate this issue, we will use the client.Updatestrategy to update the object to be compatible with the new version of Cilium. We are only doing this for the Cilium Service, DaemonSet, and Deployment since …
=> Handle special cases for Cilium upgrades when using API

pkg/providers/vsphere/validator.go, pkg/providers/vsphere/validator_test.go
*Issue #5865:*
Modified to fail on vsphere missing user permissions.
*Testing:*
Created a user with missing permissions and tested validations. Now the error shows as
```bash
2023-07-14T20:09:04.809Z  V3  user ramaliar-test@vsphere.local missing vSphere permissions  {"Permissions": "- username: ramaliar-test@vsphere.local\n  objectType: Network\n  path: /Denver/network/Dev\n  permissions:\n  - VirtualMachine.Interact.PowerOff\n  - VirtualMachine.Interact.PowerOn\n- username: ramaliar-test@vsphere.local\n  objectType: Datastore\n  path: /Denver/datastore/datastore1.1\n  permissions:\n  - VirtualMachine.Interact.PowerOff\n  - VirtualMachine.Interact.PowerOn\n- username: ramaliar-test@vsphere.local\n  objectType: ResourcePool\n  path: …
```
=> Refactoring to fail on vsphere perms validations

pkg/validations/createvalidations/createvalidations.go, pkg/validations/skipvalidations.go, pkg/validations/skipvalidations_test.go, pkg/validations/upgradevalidations/poddisruptionbudgets.go, pkg/validations/upgradevalidations/poddisruptionbudgets_test.go, pkg/validations/upgradevalidations/preflightvalidations.go, pkg/validations/upgradevalidations/upgradevalidations.go
*Issue #5865:*
Refactoring constants and adding `vsphere-user-privilege` for upgrade.
*Testing:*
Tested creating a cluster by skipping the check
```bash
./eksctl-anywhere create cluster -f ./config.yaml
```
*Documentation added/planned :*
Plan to document the new flag and user experience.
=> Refactoring constants for skip validations

cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/deletecluster.go, cmd/eksctl-anywhere/cmd/generatebundleconfig.go, cmd/eksctl-anywhere/cmd/supportbundle.go, cmd/eksctl-anywhere/cmd/upgradecluster.go, cmd/eksctl-anywhere/cmd/upgradeplancluster.go, cmd/eksctl-anywhere/cmd/validatecreatecluster.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
*Issue #5865:*
The PR adds support for `--skip-validations` for create cluster and also pass's it to the provider level validations.
Originally we had it limited to upgrade cluster's preflight level checks alone.
*Testing:*
Created a user with missing permissions and tested validations. Now the error shows as
If we pass --skip-validations, the check is skipped.
```bash
root@ip-10-0-59-81:/home/ubuntu# ./eksctl-anywhere create cluster --help
This command is used to create workload clusters
Usage:
anywhere create cluster -f <cluster-config-file> [flags]
Flags:
...
--skip-validations stringArray        Bypass create validations by name. Valid arguments you can pass are --skip-validations=vsphere-user-privilege
...
```
Tested creating a cluster by skipping the check …
=> Adding skip validation support for vsphere validations

internal/test/e2e/run.go
Test if enabling the larger tests to run first makes the Tinkerbell CI runs more time efficient.
=> Sort Tinkerbell in reverse order to run larger tests first

docs/Makefile, docs/README.md, docs/content/en/docs/community/docs_contributing.md
This change improves the developers experience when wanting to detach the container hosting the docs site for local development and provies guidance on how to manage the submodules for the docs site.
=> Update docs development README guidance

release/pkg/bundles/cloudstack.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.16-bundle-release.yaml
Cloudstack E2Es are failing due to using a commit hash instead of a GIT TAG. This temporarily hardcodes it to the next rc version instead of that commit hash.
=> Override CAPC commit hash with temporary tag

pkg/controller/clusters/controlplane.go, pkg/controller/clusters/controlplane_test.go
When the controller reconciles the control plane for a cluster with an external ETCD configuration, the `KubeadmControlPlane.Spec.KubeadmConfigSpec.ClusterConfiguration.Etcd.External.Endpoints` field is defaulted to an empty slice. However,  at some point that field in KubeadmControlPlane object is filled and updated by another component 
During subsequent reconciliation loops, the controller applies a spec with an empty slice again, causing unnecessary updates to the `.metadata.generation` field, which is integral for tracking that object's status is up to date through it's `.status.observedGeneration` field. These unnecessary updates causes issues with getting correct timely status updates from the KubeadmControlPlane and is also causes …
=> Fix unnecessary KCP spec update when reconciler ControlPlane

pkg/controller/clusters/status.go, pkg/controller/clusters/status_test.go
When a workload cluster control plane is upgraded, it is marked "False" with the `ControlPlaneNotReady`. It is not re-evaluated after the control plane becomes ready, as the controller stops reconciling before then. So, this PR addresses the issue by removing the condition update's dependency on ControlPlaneReady. We only need to change this status when there is a. change in the state of the CNI detected.
- Unit test
- Manual test
- Create a workload cluster using the controller, then upgrade the control plane node count. The `DefaultCNIConfiguredCondition` should stay "True". …
=> Fix for Default CNI condition in Cluster status

pkg/api/v1alpha1/vspheredatacenterconfig_webhook.go, pkg/api/v1alpha1/vspheredatacenterconfig_webhook_test.go
https://github.com/aws/eks-anywhere/issues/6143
remove immutable check in webhook. It's already mutable in preflight check https://github.com/aws/eks-anywhere/pull/1880, which included in [release 0.9.0](https://github.com/aws/eks-anywhere/compare/v0.8.2...v0.9.0)
unit-test
e2e test in NN
=> make vsphere dc thumbprint mutable

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go
[1551](https://github.com/aws/eks-anywhere-internal/issues/1551)
Bootstrap cluster backup can fail if `clusterctl move` detects that infrastructure/objects are still being provisioned. This is not caught in retries.
Added `clusterctl move` provisioning errors to retries.
tested locally and added unit tests
=> add backup cluster retries on infrastructure error

controllers/cluster_controller_test.go, pkg/api/v1alpha1/condition_consts.go, pkg/controller/clusters/status.go, pkg/controller/clusters/status_test.go
While testing upgrades, we ran into an edge case where all the old control plane machines were removed and all the new control plane machines and nodes were all rolled out. However, an old node still remained in the cluster, which resulted in the   `ControlPlaneReady` condition being marked as ready when it was actually not. We use the status on the `KubeadmControlPlane` to compute this and determine the control plane is ready when there are no outdated CAPI machines, number of replicas  match the expected and all are ready. 
Example KCP status in this case
```
status:
conditions:
- lastTransitionTime: "2023-07-11T22:24:33Z"
status: "True"
type: Ready
- lastTransitionTime: "2023-07-11T22:01:55Z"
status: "True"
type: Available
- …
```
=> Add control plane components healthy check when computing ControlPlaneReady condition

test/e2e/SKIPPED_TESTS.yaml, test/e2e/cloudstack_test.go
Add E2E tests for Cloudstack Provider for K8s 1.27 version as follow up to [PR](#6167)  This also adds 1.25 and 1.26 E2E tests for some of the missing packages flow.
=> Add E2E tests for Cloudstack kubernetes 127 version

pkg/files/reader.go, pkg/files/reader_test.go
* Removing unnecessary code in test
* Making sure the connections are not closed until both routines are done piping to the dst connections.
=> Attempt to fix reader with http proxy flaky test

release/pkg/bundles/cloudstack.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.16-bundle-release.yaml
There is a new tag for CAPC, so we can remove the temporary overwrite for CAPC version
=> Remove temporary CAPC version overwrite

test/e2e/cloudstack_test.go
Fixes incorrect k8s versions in cloudstack e2e. There were a couple places where the wrong k8s version was used in the tests. This resolves that
=> Fix incorrect k8s versions in cloudstack e2e

docs/content/en/docs/clustermgmt/networking/cluster-replace-cilium.md
This reverts commit 05193320d345543e7e11494a78dd394fb72bca77.
The reference is unnecessary for the alert and is included in the ingress documentation.
=> Revert "[Docs]Add CNI chaining support with Cilium in EKS-A (#6215)"

pkg/providers/cloudstack/cloudstack.go, pkg/providers/docker/docker.go, pkg/providers/mocks/providers.go, pkg/providers/nutanix/provider.go, pkg/providers/nutanix/provider_test.go, pkg/providers/provider.go, pkg/providers/snow/snow.go, pkg/providers/tinkerbell/upgrade.go, pkg/providers/vsphere/config/ethtool_daemonset.yaml, pkg/providers/vsphere/mocks/client.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go, test/framework/template.go
This is only needed for EKS-A v0.17 because UDP offloading needs to be disabled for the new Cilium version to work with VSphere clusters. Since our templates that were shipped in v0.16 releases still have UDP offloading enabled in the nodes, we must apply this daemon set to disable UDP offloading in all the nodes before upgrading Cilium in that cluster. We will remove this in EKS-A release v0.18.0.
The new DS is using our kind node image because ethtool is installed there.
Manual testing
LatestMinorReleaseE2E passed
```
cluster.go:896: Skipping VM cleanup
--- PASS: TestVSphereKubernetes125To126UbuntuUpgradeFromLatestMinorRelease (2114.73s)
PASS
```
By submitting …
=> Apply DS to disable udp offloading before Cilium upgrades in VSphere

test/e2e/SKIPPED_TESTS.yaml
skips cloudstack E2E tests that cannot be run right now
=> Skip cloudstack E2E tests that cannot be run

cmd/integration_test/build/buildspecs/tinkerbell-test-eks-a-cli.yml
Bump up the max number of EC2 instances for Tinkerbell to enable running individual tests separately in an instance. 
=> Bump number of max EC2 instances to run one test per instance

pkg/validations/cluster.go, pkg/validations/cluster_test.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/createvalidations/preflightvalidations_test.go
Newly created clusters will not use bundlesref, so we should remove the create preflight validations for it. 
=> Remove Bundle Create Validation

test/e2e/vsphere_test.go, test/framework/vsphere.go
This adds coverage for latest minor release upgrades on VSphere with Redhat
```
cluster.go:896: Skipping VM cleanup
--- PASS: TestVSphereKubernetes126To127RedhatUpgradeFromLatestMinorRelease (2075.17s)
PASS
```
Ran e2e
=> Add E2E tests for Redhat latest minor release upgrades on vsphere

pkg/providers/vsphere/testdata/cluster_redhat_external_etcd.yaml, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
We do not need to apply the daemonset to disable udp offloading to ubuntu nodes, so updating that logic to only run for Redhat OS family on VSphere
We will add a note about this in the v0.17 Changelog
=> Only apply DS to vsphere redhat nodes

pkg/controller/clusters/status.go, pkg/controller/clusters/status_test.go, test/framework/clustervalidator.go
=> Fix test framework for eksa version

pkg/validations/cluster.go, pkg/validations/cluster_test.go, pkg/validations/upgradevalidations/preflightvalidations.go
This validation was using the wrong kubeconfig, so I fixed it to use the management cluster's kubeconfig
=> Fix preflight eksa version

test/e2e/side_effects.go, test/framework/cloudstack.go, test/framework/cluster.go, test/framework/docker.go, test/framework/nutanix.go, test/framework/snow.go, test/framework/tinkerbell.go, test/framework/vsphere.go
The mod upgrade e2e tests were using the dev release template when creating the cluster with the later minor release, resulting in errors. This passes in the `release` param to use the correct template. 
Confirmed that it now passes in the correct template in e2e test binary
=> Fix modular upgrade e2e test to grab the correct template 

test/e2e/harbor.go, test/e2e/tinkerbell_test.go
Curated Packages Harbor flow is failing for Tink CI as provider specific workflow is not addressed by the generic harbor simple flow function. This change adds a helper function to address the provider specific workflow for Tinkerbell which is similar to other packages test for Tinkerbell provider.
=> add helper function for Tinkerbell specific workflow for curated packages harbor flow

test/e2e/side_effects.go, test/framework/cluster.go
We never updated the cluster config to use the new template during upgrades in this test, so this PR does that.
```
--- PASS: TestVSphereKubernetes126ManagementClusterUpgradeFromLatestSideEffects (3425.69s)
PASS
```
=> Update cluster config for upgrades during modular upgrade e2e tests

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/executables/clusterctl.go, pkg/executables/clusterctl_test.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
Set the context to right management cluster when upgrading both mgmt and workload cluster for taking backup. 
Set cluster name filter for backing up the cluster that is getting upgraded.
=> Fix CAPI Backup and add filter for cluster name

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/executables/clusterctl.go, pkg/executables/clusterctl_test.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
Cherry pick of https://github.com/aws/eks-anywhere/pull/6313
=> Fix CAPI Backup and add filter for cluster name (#6313)

test/framework/tinkerbell.go
The Provider interface method `WithKubeVersionAndOS` was not implemented for Tinkerbell and so was causing a panic.
=> Implement Provider interface method for Tinkerbell tests

internal/test/files.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/cluster_manager_wb_test.go, pkg/executables/clusterctl.go, pkg/executables/clusterctl_test.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
Updating first workload cluster backup to be best effort. Will first attempt a backup with no cluster filter, then backup with filter if that fails.
Added a check to only take bootstrap cluster backup if bootstrap cluster reference is not nil. Also updated bootstrap backup to not overwrite workload backup and instead write to a separate folder.
unit tests added
=> best effort backup and bootstrap backup to different directory

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_types_test.go, pkg/clustermarshaller/testdata/expected_marshalled_cluster.yaml, pkg/clustermarshaller/testdata/expected_marshalled_cluster_flux_and_gitops.yaml, pkg/clustermarshaller/testdata/expected_marshalled_cluster_flux_config.yaml, pkg/clustermarshaller/testdata/expected_marshalled_snow.yaml, pkg/gitops/flux/files_test.go, pkg/gitops/flux/testdata/cluster-config-default-path-management.yaml, pkg/gitops/flux/testdata/cluster-config-default-path-workload.yaml, pkg/gitops/flux/testdata/cluster-config-user-provided-path.yaml
This PR adds a `ClusterSpecGenerate` struct when marshalling the cluster spec. We needed this specifically such that we could generate a yaml with bundlesRef null so that it would
not be omitted from the kubeapi-server.
There was an issue when upgrading from the latest minor release with gitps v0.16.2 to v0.17 during the "Applying eksa yaml resources to cluster" step stalled indefinitely because both the newly added eksaVersion field and the bundlesRef were populated in submission to the kubeapi server. There is a webhook validation that does not allow both to be set at the same time, so that was throwing an error in the kube-api-server pod. This is strange because, in the original submission of the Cluster resource yaml, bundlesRef was …
=> Fix stalling on upgrade from latest minor release with flux

pkg/api/v1alpha1/tinkerbelldatacenterconfig_webhook_test.go, pkg/providers/tinkerbell/upgrade.go, pkg/validations/upgradevalidations/preflightvalidations_test.go, test/e2e/tinkerbell_test.go
Make OS Image URL mutable to support upgrading OS version without upgrading Kubernetes version.
=> Make OS Image URL mutable for Tinkerbell

cmd/eksctl-anywhere/cmd/options.go
Add deprecation warning for machine health check timeout flags
*Testing:*
```
eksctl-anywhere upgrade cluster -h
This command is used to upgrade workload clusters
Usage:
anywhere upgrade cluster [flags]
Flags:
......
--kubeconfig string                   Management cluster kubeconfig file
--no-timeouts                         Disable timeout for all wait operations
--node-startup-timeout string         (DEPRECATED) Override the default node startup timeout (Defaults to 20m for Tinkerbell clusters) (default "10m0s")
--per-machine-wait-timeout string     Override the default machine wait timeout per machine (default "10m0s")
--skip-validations stringArray        Bypass upgrade validations by name. Valid arguments you can pass are …
```
=> Add deprecation warning for machine health check timeout flags

internal/test/e2e/run.go
Bump E2E test timeout from 120 to 150 mins to prevent Tinkerbell airgapped E2E tests from timing out. 
=> Increase end to end test timeout 

test/e2e/tinkerbell_test.go
Fixes incorrect kubernetes version on `TestTinkerbellUpgrade127MulticlusterWorkloadClusterWorkerScaleDown` 
=> Fix incorrect kubernetes version in tinkerbell E2E

docs/content/en/docs/clustermgmt/networking/cluster-replace-cilium.md
Fixes #6337.
Cilium CLI v1.14 works with Cilium v1.11 through 1.13. CLI v1.15 only works with Cilium v1.14. See the README for more details.
https://github.com/cilium/cilium-cli
=> Update custom CNI docs with specific Cilium CLI version

internal/pkg/api/cluster.go, test/e2e/upgrade_from_latest.go
Changes the `runMulticlusterUpgradeFromReleaseFlowAPI` and `runMulticlusterUpgradeFromReleaseFlowAPIWithFlux` test flows to use eksaVersion once mgmt upgrades to latest, and bundlesRef when creating a workload cluster with old bundle.
This will fix `TestCloudStackKubernetesRedHat123To124UpgradeFromLatestMinorReleaseAPI`
--- PASS: TestCloudStackKubernetesRedHat123To124UpgradeFromLatestMinorReleaseAPI
=> Fix upgrade from latest E2Es to use proper EksaVersion and bundesRef.

Makefile, scripts/validate_tinkerbell_hardware_file.sh
Dynamic hardware reservation #6127  introduces a hardware requirements file (tinkerbell_hardware_count.file) that maps each Tinkerbell tests to it's hardware requirements. This change adds a make target validation which checks if all the Tinkerbell tests defined in the current build is present in the hardware requirements file. This will help detect any newly added tinkerbell tests that is missed in the hardware requirements file.
=> Add Make target to validate the Tinkerbell hardware count file

pkg/clustermanager/eksa_installer.go, pkg/clustermanager/eksa_installer_test.go, pkg/features/features.go
If the envvar is set when the CLI installs the controller, pass the feature flag so the controller allows kindless upgrades.
=> Enable kindless upgrades in controller from CLI

pkg/api/v1alpha1/cloudstackmachineconfig_webhook.go, pkg/api/v1alpha1/cloudstackmachineconfig_webhook_test.go
Until now, any machine config belonging to a workload cluster was
skipping all webhook validations. All existing validations apply to both
management and workload cluster machine configs, so there is no need to
make a distinction here.
=> Validate all cloudstack machine configs in webhook

config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, config/manifest/eksa-components.yaml, release/api/v1alpha1/bundle_types.go, release/config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, release/pkg/assets/config/bundle_release.go, release/pkg/bundles/package-controller.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.16-bundle-release.yaml
*Issue #, if available:* credential-provider-package is missing in eksa bundle-release.yaml
*Testing (if applicable):* unit test "bundle_release_test.go"
=> Add credential provider package to bundle release yaml

internal/test/files.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/cluster_manager_wb_test.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/executables/clusterctl.go, pkg/executables/clusterctl_test.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go, pkg/workflows/upgrade.go, pkg/workflows/upgrade_test.go
Cherry pick of commits from main to 
- enable CAPI backup from bootstrap cluster on upgrade failures.
- add filter-cluster flags to capi backup
/hold
=> [release-0.16] Add CAPI backup from bootstrap cluster + filter-cluster flags for backups

pkg/validations/cluster.go, pkg/validations/cluster_test.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/createvalidations/preflightvalidations_test.go, pkg/validations/upgradevalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations_test.go
Remove validation that checks if mgmt cluster's bundle is compatible with workload cluster's bundle to enable 0.17 mgmt clusters with 0.16 workload clusters.
=> [release-0.16] Remove mgmt bundlesRef validation

pkg/providers/tinkerbell/upgrade.go
The bundle changes trigger a rolling upgrades but Tinkerbell currently doesn't account for them during preflights which causes the upgrade to fail if a bundle change happened alongside a scaling operation.
This PR adds a preflight to detect bundle changes and marks those also as a trigger for rolling upgrades.
So if a scaling operation happens along with bundle changes, the CLI will fail out early in preflights.
=> Fix Tinkerbell preflights to account for bundles changes

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go
Kubectl waits already have a retry policy which checks for both connection refused and IO timeouts. This change updates the regex to also include a tls handshake timeout so that the policy and retry on such occurrences.
=> Add retries for TLS handshake timeout on kubectl waits

docs/content/en/docs/packages/best_practice.md, docs/content/en/docs/packages/packagebundles.md, docs/content/en/docs/packages/packagecontroller.md, docs/content/en/docs/packages/packagelist.md, docs/content/en/docs/packages/packages.md, docs/content/en/docs/packages/prereq.md, docs/content/en/docs/packages/troubleshoot.md
https://github.com/aws/eks-anywhere-internal/issues/1568
This PR adds a page on package bundles. Additionally, it separates information from the prerequisites page into it's own page about the package controller.
Test by running docs server locally
=> Update package docs to include package bundle information

pkg/cluster/wait.go, pkg/cluster/wait_test.go
Helpful tool when waiting for an eksa cluster condition in the CLI. Will be used for kindless upgrades, etc.
=> Add helper to wait for cluster condition

internal/test/kubernetes.go, pkg/clients/kubernetes/client.go, pkg/clients/kubernetes/kubeconfig.go, pkg/clients/kubernetes/kubeconfig_test.go, pkg/clients/kubernetes/kubectl.go, pkg/clients/kubernetes/kubectl_test.go, pkg/clients/kubernetes/mocks/client.go, pkg/clients/kubernetes/mocks/kubectl.go, pkg/clients/kubernetes/unauth.go, pkg/clients/kubernetes/unauth_test.go, pkg/clustermanager/client.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/clustermanager/retrier_client.go, pkg/controller/clientutil/kubernetes.go, pkg/controller/clientutil/kubernetes_test.go, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go
This allows code shared between the CLI (where the a kubectl wrapper is used) and the controller (where the controller-runtime client.Client is used) to leverage server side apply.
Part of the kindless upgrades work.
=> Add apply server side to the k8s client interface

docs/content/en/docs/community/docs_contributing.md
Need to add information about creating and including images into the EKS Anywhere style guide.
Updated the EKS Anywhere  [Contributing to documentation] guide to include information about images.
*Documentation added/planned (if applicable):* This PR is documentation only.
=> Add image information to docs style guide

test/e2e/vsphere_test.go
Fixes incorrect kubernetes version in `TestVSphereKubernetes123to124UpgradeFromLatestMinorReleaseBottleRocketAPI`
=> Fix incorrect k8s version in vSphere E2E

controllers/cluster_controller.go, controllers/cluster_controller_test_test.go, manager/main.go, pkg/controller/clientutil/indexers.go, pkg/controller/clientutil/indexers_test.go, pkg/controller/clusters/management.go, pkg/controller/clusters/validations.go, pkg/controller/clusters/validations_test.go, pkg/providers/tinkerbell/reconciler/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler_test.go
Currently we make an assumption in our management cluster name validation for our workload cluster that both clusters exist in the same namespace. However, it is possible that the management cluster and the workload cluster are created in different namespaces. This is also how we get the cluster object through the CLI: https://github.com/aws/eks-anywhere/blob/2347399db3b997eddc9e2e770af1c1ef19bd6ccb/pkg/executables/kubectl.go#L1500
We are keeping the current check of getting the cluster based on the same namespace, but if we don't find it, we will fall back to looking for the cluster using the list api. If we still don't find the cluster or it errors out, we will tell the user that we were unable to find the cluster as we did before. If …
=> Add ability to list clusters across namespaces for validating management cluster name

internal/pkg/api/vsphere.go, test/e2e/vsphere_test.go
Test fails at waiting for external etcd to be ready because of the 2X replicas hard limit on etcd. This changes the checkpoint test to not fail at etcd rolling out but at cp rolling out to avoid the test timing out waiting for external etcd to be ready when more etcd nodes cannot be rolled out.
=> Fix checkpoint test to not fail at etcd rolling out

pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/tinkerbell_test.go, pkg/validations/createvalidations/gitops.go, pkg/validations/createvalidations/gitops_test.go
Builds off of #6414, however there are a few places outside of the controller where we make this assumption as well, which the `GetEksaCluster` function solves for.
unit testing
=> Retrieve management cluster namespace instead of assuming workload cluster namespace

pkg/providers/tinkerbell/rufiounreleased/baseboardmanagement.go
If you run `make generate` currently, it generates `pkg/providers/tinkerbell/rufiounreleased/zz_generated.deepcopy.go` which isn't needed. This PR removes the `//+kubebuilder:object:root=true` annotations from this file so `controller-gen` doesn't generate this file anymore.
=> Remove kubebuilder root tags from unreleased Rufio CRDs to avoid generating deepcopy

pkg/providers/cloudstack/cloudstack.go, pkg/providers/docker/docker.go, pkg/providers/nutanix/provider.go, pkg/providers/tinkerbell/upgrade.go, pkg/providers/vsphere/vsphere.go
Fixes #6330.
**Summary**
Manipulating labels on a single worker node group resulted in all worker node groups being rolled. This change ensures the worker node group with the adjusted labels is the only worker node group to be rolled out. 
The bug impacted the Docker, Tinkerbell, vSphere, Nutanix and CloudStack providers. It is only present for CLI based clusters.
Additional manual tests were run using the CloudStack provider.
Since the CLI will be changed to leverage the controller for all cases in future, no effort has been made to refactor the code so the fix isn't needed across all providers.
=> Fix all worker node groups being rolled when labels adjusted

docs/content/en/docs/clustermgmt/security/manually-renew-certs.md
Users have been confused by the [Certificate rotation](https://anywhere.eks.amazonaws.com/docs/clustermgmt/security/manually-renew-certs/) docs because it seems that all customers have to manually rotate certificates in EKS Anywhere. This doc update clarifies that EKS Anywhere automatically rotates certificates when new machines are rolled out in the cluster during lifecycle operations such as `upgrade`.
=> clarify certificate rotation docs

pkg/api/v1alpha1/cluster_types.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/docker/docker.go, pkg/providers/nutanix/provider.go, pkg/providers/tinkerbell/upgrade.go, pkg/providers/vsphere/vsphere.go
Fixes #6481 
When worker node group taints are adjusted it would roll out all worker node groups. This fix ensures the worker node group that has changed is the only group to be rolled out.
=> Fix worker node groups being rolled out when taints are changes

docs/content/en/docs/getting-started/optional/autoscaling.md, docs/content/en/docs/packages/cluster-autoscaler/addclauto.md
N/A
People are consistently confused by the many options we present for them to deploy cluster autoscaler.
This PR removes references to alternative deployment topologies. It recommends that all cluster autoscaler packages
be deployed to the management cluster, whether the deployment scales a workload or a management cluster.
This is the documentation :)
=> Simplify Cluster Autoscaler Docs

docs/OWNERS
Adding csplinter to docs OWNERS file.
=> Add Chris Splinter to docs OWNERS

cmd/eksctl-anywhere/cmd/options.go
When management cluster kubeconfig is not set during workload cluster create/upgrade, eks-a doesn't fail and incorrectly sets management cluster to same as workload cluster when `clusterspec.ManagementCluster` value is nil which is determined based on kubeconfig file being explicitly passed or set as env variable. This change tries to additionally find the kubeconfig file locally if the env variable is not set for kubeconfig and errors out when not able to find any valid kubeconfig file.  
=> Error out when management kubeconfig is not present for workload cluster operations

cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/flags.go, cmd/eksctl-anywhere/cmd/flags/cluster.go, cmd/eksctl-anywhere/cmd/flags/flag.go, cmd/eksctl-anywhere/cmd/flags/require.go, cmd/eksctl-anywhere/cmd/flags/require_test.go, cmd/eksctl-anywhere/cmd/flags/tinkerbell.go, cmd/eksctl-anywhere/cmd/generate.go, cmd/eksctl-anywhere/cmd/generate_tinkerbell_template_config.go, cmd/eksctl-anywhere/cmd/upgradecluster.go, pkg/utils/yaml/kubernetes.go
Closes #3588.
**Summary**
In Tinkerbell clusters users can customize the provisioning steps by specifying their own TinkerbellTemplateConfig as part of the cluster spec. However, to date its been difficult for users to determine what set of default actions are used as EKS-A generates the TinkerbellTemplateConfig when unspecified (default behavior).
This command generates a TinkerbellTemplateConfig using the users cluster spec giving them a functional template.
```
eksctl anywhere generate tinkerbelltemplateconfig -f <cluster spec path>
```
**Future work**
Further refactoring is necessary around flag names to deduplicate flag name strings. Some refactoring in validation logic is necessary to decouple output of warnings from the validation logic.
In addition to this new command, or as part …
=> Add generate TinkerbellTemplateConfig command

docs/content/en/docs/osmgmt/artifacts.md
Adding docs for cross-version image build support and UEFI support in `image-builder`.
=> Add documentation for cross-version image builds and UEFI support

Makefile
The current regex in `make clean` doesn't delete the `Test...` folders created for unit-tests.
This PR updates the regex to `.*\/Test.*-[0-9]{10}[\/]?.*` which matches the following folders created during unit tests.
```bash
./pkg/providers/cloudstack/TestSetupAndValidateSSHAuthorizedKeyEmptyCP-2071519390/generated
./pkg/providers/cloudstack/TestSetupAndValidateSSHAuthorizedKeyEmptyCP-2071519390
```
Here's the regex matching example https://rubular.com/r/pBaXKbK9yzTPKO
=> Fix regex for make clean

pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go, pkg/validations/cluster_test.go
Preflight validations currently see upgrading from a release build to dev build as a downgrade. This change lets you upgrade with a dev build in this scenario. 
=> fix upgrade from latest e2e

pkg/executables/builder.go
This is only used in E2E tests for convenience and only to run commands needed in the tests themselves, nothing for the normal lifecycle flows. Updating to the last version to get all dep patches and mostly because the new image is way smaller.
=> Update default CLI tools image to latest

internal/pkg/api/cluster.go, test/e2e/SKIPPED_TESTS.yaml, test/e2e/docker_test.go
This PR updates docker tests from using kindnetd to cilium again. This change was original made in [this](https://github.com/aws/eks-anywhere/pull/6296) PR due to issues upgrading from the latest release, specifically with docker.
I ran some of the affected e2e tests locally and they all succeeded.
=> Revert docker tests to use cilium instead of kindnetd

controllers/cluster_controller_test.go, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_webhook.go, pkg/validations/cluster.go, pkg/validations/cluster_test.go, test/e2e/upgrade_from_latest.go
This PR addresses two issues with the API upgrade from latest minor release tests:
1. These tests have a step where they create a new workload cluster after upgrading from latest minor release using the old bundle. After recent changes added to the latest minor release 0.17, the `bundleRef` on clusters is null so the test hits a nil pointer trying to use and panics. This PR fixes the test run flow to use the EksaVersion field instead of the BundleRef field to test creating clusters with an older bundle.
2. After fixing the above issue, the control plane on the new cluster still fails to come up due to a failure in the controller :
```
...
failureMessage: 'cannot upgrade workload cluster to v0.17.0 while management cluster
is an older …
```
=> Fix upgrade from latest minor release API tests

docs/content/en/docs/getting-started/install/_index.md
The method for installing the eksctl and associated commands is not secure as it creates a file in a system-wide directory owned by a user (user = whoever the person is logged in as).  
Instead of using mv (and chmod in some of the examples), use the "install" command with appropriate flags
ex - replace first line (mv) with the second (install)
```
sudo mv /tmp/eksctl /usr/local/bin/
sudo install -m 0755 /tmp/eksctl /usr/local/bin/eksctl
```
RHEL8
```
[jradtke@rhel8 ~]$ touch /tmp/test
[jradtke@rhel8 ~]$ ls -l /tmp/test
-rw-rw-r--. 1 jradtke jradtke 0 Apr 24 16:48 /tmp/test
[jradtke@rhel8 ~]$ sudo install -m 0755 /tmp/test /tmp/test1
[jradtke@rhel8 ~]$ ls -l /tmp | grep test
-rw-rw-r--. 1 jradtke jradtke  0 Apr …
```
=> Security Improvement for binary install

pkg/cluster/testdata/cluster_tinkerbell_1_19.yaml, pkg/cluster/tinkerbell.go, pkg/cluster/tinkerbell_test.go, pkg/cluster/validate_test.go
https://github.com/aws/eks-anywhere/issues/6452
=> cloudstack cluster/dc/mc should use same namespace

go.mod, go.sum, release/go.mod, release/go.sum
Manual cherry pick of #5785 and #5786
=> [release-0.17] Bump github.com/docker/docker from 23.0.2+incompatible to 23.0.3+incompatible

pkg/files/reader_test.go
I'm not completely sure this will fix this issue because I'm not completely sure what the actual issue is. But at least this should provide more info through test logs plus it handles an edge case where the connection had some buffered read data before we hijack it.
If this keeps failing and I'm not able to figure out the issue, I'll just delete the test.
=> Try to fix file reader proxy flaky test

docs/content/en/docs/osmgmt/artifacts.md
N/A
Bottlerocket did a key rotation and there is a new root.json used to pull from Bottlerocket's TUF repositories.
See previous update:
https://github.com/aws/eks-anywhere/pull/3310
N/A
=> artifacts.md: update checksum for Bottlerocket's new root.json

pkg/providers/vsphere/validator.go, pkg/providers/vsphere/validator_test.go, pkg/providers/vsphere/vsphere_test.go
Old code was not validating templates for etcd or CP, only for workers.
=> Fix vSphere template tags validation

pkg/providers/tinkerbell/stack/stack.go, pkg/providers/tinkerbell/stack/stack_test.go, pkg/providers/tinkerbell/stack/testdata/expected_upgrade.yaml, pkg/providers/tinkerbell/stack/testdata/expected_upgrade_with_proxy.yaml, pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_docker.yaml, pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_kubernetes.yaml, pkg/providers/tinkerbell/stack/testdata/expected_with_docker_options.yaml, pkg/providers/tinkerbell/stack/testdata/expected_with_envoy_enabled_false.yaml, pkg/providers/tinkerbell/stack/testdata/expected_with_envoy_enabled_true.yaml, pkg/providers/tinkerbell/stack/testdata/expected_with_hook_override.yaml, pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_false.yaml, pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_true.yaml, pkg/providers/tinkerbell/stack/testdata/expected_with_kubernetes_options.yaml, pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_false.yaml, pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_true.yaml, pkg/providers/tinkerbell/stack/testdata/expected_with_namespace_create_false.yaml, pkg/providers/tinkerbell/stack/testdata/expected_with_proxy_config.yaml, pkg/providers/tinkerbell/stack/testdata/expected_with_registry_mirror.yaml, pkg/providers/tinkerbell/upgrade.go
Closes #6442.
When upgrading bare metal clusters that use a custom pod CIDR Hegel looses the pod CIDR as a trusted proxy. It can be caused by either an upgrade of the management cluster or upgrade of a workload cluster. 
The problem stems from trusted proxies not being included in the values when upgrading the Tinkerbell helm chart and incorrectly identifying the need to upgrade when upgrading workload clusters.
This change has undergone extensive manual testing with both management and workload cluster creations and upgrades (scale ups and downs). 
Additionally, I found a programmer error in our unit tests where we incorrect deserialized YAML into map data structures which resulted in the comparison of 2 empty maps. Correcting the error revealed numerous unit test failures. I reworked …
=> Fix bare metal upgrade with custom pod CIDR

controllers/cluster_controller_test.go, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_webhook.go, pkg/validations/cluster.go, pkg/validations/cluster_test.go, test/e2e/upgrade_from_latest.go
This patch never applied to release 0.17. Originally, a patch was made such due to encountering an error upgrading from latest minor release in the controller on main.
```
status:
failureMessage: 'cannot upgrade workload cluster to v0.17.0 while management cluster is an older version: v0.0.0'
failureReason: EksaVersionInvalid
```
It only happened when trying to create a new cluster with the old bundle, but the old cluster created from the latest minor release will not have an EksaVersion, only BundlesRef.
=> Revert 6580 cherry pick 6576 to release 0.17
