aws/eks-anywhere

Makefile, pkg/cluster/config/releases.yaml, scripts/get_bundle.sh
=> Revert "Point staging e2e test EKS-A CLI to staging manifest"

docs/content/en/docs/concepts/cluster-topologies.md, docs/content/en/docs/concepts/clusterworkflow.md, docs/content/en/docs/getting-started/production-environment/baremetal-getstarted.md
=> Add docs for workload cluster support for tinkerbell

docs/content/en/docs/getting-started/production-environment/nutanix-getstarted.md, docs/content/en/docs/reference/artifacts.md, docs/content/en/docs/reference/clusterspec/nutanix.md, docs/content/en/docs/reference/nutanix/_index.md, docs/content/en/docs/reference/nutanix/domains.md, docs/content/en/docs/reference/nutanix/nutanix-preparation.md, docs/content/en/docs/reference/nutanix/nutanix-prereq.md, docs/content/en/docs/reference/ports.md, docs/content/en/docs/tasks/cluster/cluster-delete.md, docs/content/en/docs/tasks/cluster/cluster-scale/nutanix-scale.md, docs/content/en/docs/tasks/cluster/cluster-terraform.md, docs/content/en/docs/tasks/cluster/cluster-upgrades/vsphere-and-cloudstack-upgrades.md, docs/content/en/docs/tasks/cluster/etcd-backup-restore.md
This PR adds documentation for the Nutanix provider.
Compiled doc for review.
=> initial nutanix doc updates

pkg/providers/snow/reconciler/reconciler.go, pkg/providers/snow/reconciler/reconciler_test.go
#4375 
Update how we reconcile CP for Snow to account for the unstacked case
unit tests
=> Update snow control plane reconciler

test/framework/flux.go
Since now the cluster config is not stored in yaml form but as a cluster.Config, we need to read the cluster config file we pull from the repo. This one is generated by the CLI and contains fields that are necessary for a correct Flux operation, like defining a namespace for all resources. Moreover, this ensures we only modify what is explicitly defined in the tests as upgrade options.
=> Fix workload cluster Flux tests

docs/content/en/docs/tasks/cluster/cluster-upgrades/baremetal-upgrades.md
=> Single node upgrade exception for no additional hardware case

test/e2e/prometheus_test.go, test/framework/cluster.go
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/639
=> Add Prometheus e2e simple flow

pkg/api/v1alpha1/nutanixmachineconfig.go, pkg/api/v1alpha1/nutanixmachineconfig_test.go, pkg/api/v1alpha1/testdata/nutanix/machineconfig-with-no-user-name.yaml, pkg/providers/nutanix/provider.go, pkg/providers/nutanix/provider_test.go, pkg/providers/nutanix/template.go
=> added nil checks to avoid crash during ssh gen key

docs/content/en/docs/reference/changelog.md
This change hasn't landed yet.
=> Remove changelog reference to static IP setting in Bottlerocket:

docs/content/en/docs/reference/changelog.md
=> Remove registry auth from changelog for v0.13.0

test/e2e/prometheus_test.go
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/639
=> Add localStorageProvisioner to Prometheus e2e

docs/content/en/docs/concepts/cluster-topologies.md, docs/content/en/docs/getting-started/local-environment/_index.md, docs/content/en/docs/getting-started/production-environment/vsphere-getstarted.md, docs/content/en/docs/reference/clusterspec/optional/gitops.md, docs/content/en/docs/tasks/cluster/cluster-flux.md
*Issue #:* [1090](https://github.com/aws/eks-anywhere/issues/1090)
*Description of changes:* Update cluster creation in the vSphere getting started guide based on workload cluster lifecycle enhancements.
=> Revise vSphere Getting Started for full lifecycle changes

docs/content/en/docs/reference/changelog.md
=> added registry auth bug fix to the changelog

docs/content/en/docs/reference/changelog.md
Add PR link for vm tagging feature
=> Add PR link for vm tagging

docs/content/en/docs/reference/clusterspec/vsphere.md
=> Add vSphere tags docs

docs/content/en/docs/tasks/troubleshoot/packages.md
=> Region doc typo fix

docs/content/en/docs/reference/packagespec/best_practice.md, docs/content/en/docs/reference/packagespec/packages.md, docs/content/en/docs/tasks/packages/_index.md
https://docs.dx3ehyyttf163.amplifyapp.com/docs/overview/
https://docs.dx3ehyyttf163.amplifyapp.com/docs/reference/packagespec/
https://docs.dx3ehyyttf163.amplifyapp.com/docs/reference/packagespec/packages/
https://docs.dx3ehyyttf163.amplifyapp.com/docs/reference/packagespec/best_practice/
=> [Docs] Move pkg specs and add createNamespace mentions

docs/content/en/docs/reference/clusterspec/cloudstack.md, docs/content/en/docs/reference/clusterspec/vsphere.md, docs/content/en/docs/reference/vsphere/vsphere-ovas.md, docs/content/en/docs/tasks/cluster/cluster-upgrades/baremetal-upgrades.md, docs/content/en/docs/tasks/cluster/cluster-upgrades/vsphere-and-cloudstack-upgrades.md
Update docs to remove 1.20 references
=> Update docs to remove 1.20 references

docs/config.toml, docs/content/en/docs/getting-started/install/_index.md, docs/content/en/docs/reference/artifacts.md
=> Publish docs for release 0.13

docs/content/en/docs/concepts/cluster-topologies.md
*Description of changes:* Added the Docker provider to the list of EKS Anywhere providers that support the management/workload cluster topology.
=> Add Docker to provider list supporting workload clusters

docs/content/en/docs/reference/artifacts.md, docs/content/en/docs/tasks/troubleshoot/troubleshooting.md
=> Update vsphere docs (#4344)

internal/test/cleanup/cleanup.go, test/framework/nutanix.go
=> Add cleanup step for Nutanix E2E tests (#4418)

docs/content/en/docs/getting-started/production-environment/baremetal-getstarted.md
*Description of changes:* This PR fixes the overview section to say that the bare metal provider now supports combined management/workload clusters.
=> Fix bare metal sentence about cluster support

docs/content/en/docs/getting-started/local-environment/_index.md, docs/content/en/docs/getting-started/production-environment/vsphere-getstarted.md
=> More docs on using Gitops to create new workload clusters

docs/content/en/docs/getting-started/local-environment/_index.md, docs/content/en/docs/getting-started/production-environment/baremetal-getstarted.md, docs/content/en/docs/getting-started/production-environment/cloudstack-getstarted.md, docs/content/en/docs/getting-started/production-environment/nutanix-getstarted.md, docs/content/en/docs/getting-started/production-environment/vsphere-getstarted.md, docs/content/en/docs/tasks/packages/_index.md, docs/content/en/docs/tasks/troubleshoot/packages.md
=> Revert packages region doc changes

docs/content/en/docs/reference/changelog.md
=> Updating changelog for packages

docs/content/en/docs/reference/changelog.md
=> Remove unreleased section from changelog

docs/content/en/docs/reference/faq/_index.md
*Description of changes:* Trivial doc change
*Testing (if applicable):* `make container-serve`
=> Add single-node bare metal support to FAQ

internal/pkg/api/cluster.go, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/providers/tinkerbell/mocks/client.go, pkg/providers/tinkerbell/tinkerbell.go, test/e2e/autoscaler_test.go, test/e2e/curated_packages_test.go, test/e2e/emissary_test.go, test/e2e/vsphere_workload_api_test.go, test/e2e/workload_clusters_test.go, test/framework/cluster.go, test/framework/multicluster.go, test/framework/vsphere.go, test/framework/workload.go
=> Add e2e test prototype for Cluster lifecycle API

Makefile, test/e2e/adot_test.go, test/e2e/curated_packages_test.go, test/e2e/emissary_test.go, test/e2e/prometheus_test.go
=> Fix e2e test names

test/framework/cluster.go
Revert https://github.com/aws/eks-anywhere/pull/4285 for now
=> Revert e2e import images change

test/framework/cluster.go
=> Adding kubeconfig to packages cli command

internal/test/envtest/config/snow-crds.yaml, pkg/controller/clusters/workers.go, pkg/providers/snow/objects.go, pkg/providers/snow/objects_test.go, pkg/providers/snow/reconciler/reconciler.go, pkg/providers/snow/reconciler/reconciler_test.go
#3282 
Wait for #4455 to merge first.
Add ipPools objects to snow worker groups.
Unit tests
=> Support ip pools for snow worker groups

pkg/providers/vsphere/reconciler/reconciler.go, pkg/providers/vsphere/reconciler/reconciler_test.go, pkg/providers/vsphere/vsphere.go
CLI install storage class on vsphere cluster on creation, we should have the same thing on controller
=> Install Vsphere storage class

pkg/clusterapi/apibuilder.go, pkg/clusterapi/apibuilder_test.go, pkg/clusterapi/autoscaler_test.go, pkg/providers/cloudstack/apibuilder.go, pkg/providers/snow/apibuilder.go, pkg/providers/snow/controlplane.go, pkg/providers/snow/objects.go, pkg/providers/snow/objects_test.go, pkg/providers/snow/workers.go
https://github.com/aws/eks-anywhere/pull/4481#discussion_r1053468444
Refactor snow worker spec builder with the `clusterapi.Workers` API.
Unit tests
=> Refactor snow worker spec generation code

release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.13-bundle-release.yaml
=> Fix release tests

pkg/cluster/snow.go, pkg/cluster/snow_test.go
Currently CAPAS only supports creating an unstacked etcd machine with static IP.
Add validation so that etcd machine using DHCP will fail the preflight check.
Unit tests
=> Add validation to only support unstacked etcd with static ip for snow

pkg/providers/snow/snow.go, pkg/providers/snow/snow_test.go
Scaling up worker nodes triggers cluster upgrade with clusterctl move in snow. The expected behavior is not to create kind cluster and move capi components if only the worker node count changes.
The old `snow.UpgradeNeeded` logic is not wrong, but it makes assumption on the newer `cluster.BuildSpec` (https://github.com/aws/eks-anywhere/blob/main/pkg/cluster/fetch.go#L182) is being used in CLI instead of the deprecated `cluster.BuildSpecForCluster`. It turns out that the new `BuildSpec` is only used in controller v2 work.
This fix is necessary for `UpgradeNeeded` to work on snow since the `SnowMachineConfigs` and `SnowDatacenter` is not properly populated due to how the currentClusterSpec is being built.
We should deprecate the …
=> Fix snow UpgradeNeeded

docs/content/en/docs/getting-started/local-environment/_index.md
Apply expected indentation of manifest that _appears_ to be a 8s manifest (but I might be mistaken?)
=> indent like k8s manifest

docs/content/en/docs/getting-started/local-environment/_index.md, docs/content/en/docs/getting-started/production-environment/baremetal-getstarted.md, docs/content/en/docs/getting-started/production-environment/cloudstack-getstarted.md, docs/content/en/docs/getting-started/production-environment/nutanix-getstarted.md, docs/content/en/docs/getting-started/production-environment/vsphere-getstarted.md, docs/content/en/docs/tasks/packages/_index.md
=> adding region support back to docs

docs/content/en/docs/reference/changelog.md
=> Update changelog for v0.13.1

docs/content/en/docs/getting-started/install/_index.md, docs/content/en/docs/reference/artifacts.md
=> Update docs for v0.13.1

release/pkg/operations/bundle_release_test.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.13-bundle-release.yaml
Updates the test bundle files that the release presubmit uses
=> Update release tests

pkg/api/v1alpha1/cluster_types.go, pkg/features/features.go, pkg/features/features_test.go, pkg/validations/cluster.go, pkg/validations/cluster_test.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations.go
=> Add feature flag for kubernetes 1.25 support

config/manifest/eksa-components.yaml, config/rbac/role.yaml, controllers/cluster_controller.go, controllers/cluster_controller_legacy.go
=> Add snowippool rbac

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, test/e2e/prometheus_test.go, test/framework/awsiam.go, test/framework/cluster.go, test/framework/testdata/prometheus_package_deployment.yaml, test/framework/testdata/prometheus_package_statefulset.yaml
Also refactor some helper functions to better follow DRY principle
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/639
=> Add Prometheus e2e update workflow

docs/content/en/docs/tasks/packages/_index.md
=> Updating versions in package list

docs/content/en/docs/reference/artifacts.md
*Issue #, if available:* #4555
*Description of changes:* Move user back into home directory.
*Testing (if applicable):* Previewed markdown file, validated instruction change locally.
Matt Henslee / @henslma
AWS Professional Services
=> Move user back home after image-builder install

test/framework/cluster.go
Use existing ValidateEndpointContent and MatchLogs methods in package E2E testings
=> Refactor package E2E

cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/generateclusterconfig.go, pkg/features/features.go, pkg/providers/validator/validate.go, pkg/providers/validator/validate_test.go, pkg/validations/createcluster/createcluster.go
=> Remove snow provider feature gate

release/pkg/test/testdata/main-bundle-release.yaml
I have a PR to create a bot for this.
=> Update gold file again

test/e2e/workload_api_test.go
This PR adds an e2e test for the docker API  or scaling nodes and add/remove worker node group configurations.
`--- PASS: TestDockerUpgradeKubernetes123to124WorkloadClusterScaleupAPI (2017.01s)
`
`--- PASS: TestDockerUpgradeWorkloadClusterScaleAddRemoveWorkerNodeGroupsAPI (1167.16s)
`
=> Add Docker API E2E tests for scaling nodes and worker node groups

designs/Dockerfile
=> Use https to download plantuml

Makefile, cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/generateclusterconfig.go, internal/pkg/api/snowmachines.go, pkg/api/v1alpha1/snowmachineconfig.go, pkg/api/v1alpha1/snowmachineconfig_test.go, pkg/features/features.go, pkg/providers/validator/validate.go, pkg/providers/validator/validate_test.go, pkg/validations/createcluster/createcluster.go, release/pkg/test/testdata/main-bundle-release.yaml, scripts/golden_create_pr.sh
=> Update branch name and sync with main branch

pkg/api/v1alpha1/vspheredatacenterconfig_webhook.go
=> Remove vspheredatacenter feature gate check in validation webhook

test/e2e/curated_packages_test.go, test/e2e/metallb_test.go, test/framework/awsiam.go, test/framework/cluster.go, test/framework/conformance.go, test/framework/controlplaneNodes.go, test/framework/flux.go, test/framework/oidc.go, test/framework/vspherecsi.go, test/framework/wait.go, test/framework/workerNodes.go, test/framework/workload.go
Add e2e compatible with metallb 0.13.7 (latest release)
=> E2E metallb

pkg/providers/snow/snow.go, pkg/providers/snow/snow_test.go
=> Fix upgrade skip when removing device from snowmachine devices slice

test/e2e/adot_test.go, test/e2e/curated_packages_test.go, test/e2e/harbor_test.go, test/e2e/metallb_test.go, test/e2e/prometheus_test.go, test/framework/cluster.go
Fixes issues with packages installation namespace being passed by some tests.
=> Fix e2e tests for packages

pkg/registry/client.go, pkg/registry/copy.go, pkg/registry/copy_test.go, pkg/registry/mocks/storage.go, pkg/registry/storage.go
This adds the tags for the bundles.
=> Add tag for package bundle

OWNERS
=> Add Raymond to OWNERS

config/manifest/eksa-components.yaml, config/rbac/role.yaml, controllers/cluster_controller.go, controllers/cluster_controller_legacy.go
Adding watches for:
- TinkerbellDatacenterConfig
- TinkerbellMachineConfig
- DockerDatacenterConfig
Manually tested watches with tilt
=> adding watches for tinkerbell and docker configs

docs/content/en/docs/tasks/cluster/cluster-upgrades/vsphere-and-cloudstack-upgrades.md
=> Add snow in upgrade doc

docs/content/en/docs/reference/clusterspec/snow.md
=> Add cluster spec doc for snow

docs/content/en/docs/getting-started/production-environment/snow-getstarted.md, docs/content/en/docs/reference/ports.md
=> Add getting started guide for snow

docs/content/en/docs/reference/artifacts.md
=> Add snow in artifacts doc

docs/content/en/docs/reference/changelog.md
=> Log changes of v0.14.0

pkg/features/features.go, test/e2e/awsiam_test.go, test/e2e/conformance_test.go, test/e2e/labels_test.go, test/e2e/multiple_worker_node_groups_test.go, test/e2e/oidc_test.go, test/e2e/proxy_test.go, test/e2e/simpleflow_test.go, test/e2e/taints_test.go, test/e2e/upgrade_test.go
=> Cleanup Snow feature toggle

docs/config.toml, docs/content/en/docs/getting-started/install/_index.md, docs/content/en/docs/reference/artifacts.md
=> Update docs version for release 0.14

controllers/factory.go, pkg/cluster/tinkerbell.go, pkg/providers/tinkerbell/reconciler/mocks/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler_test.go
Add IP validator for tinkerbell reconciler
=> Add IP validator for tinkerbell reconciler

docs/content/en/docs/reference/changelog.md
=> Update changelog for packages

docs/content/en/docs/reference/clusterspec/optional/registrymirror.md
This could be a better, but I want to get something out there
=> Add mention of the copy packages command

test/e2e/docker_test.go, test/e2e/vsphere_test.go
=> Add feature flag back in 1.25 tests

test/e2e/vsphere_test.go
This PR adds vSphere E2E tests for the API with GitOps
=> Gitops Tests for vSphere lifecycle

internal/test/e2e/packages.go, test/e2e/docker_test.go, test/e2e/vsphere_test.go
=> Updating curated packages e2e test names to new regex

go.mod
This TODO I think was done already.
=> Remove TODO that is not going to happen

cmd/integration_test/build/buildspecs/nutanix-test-eks-a-cli.yml, test/e2e/conformance_test.go, test/e2e/nutanix_test.go, test/framework/nutanix.go
Add kubernetes 1.25 related e2e tests for Nutanix.
=> Update e2e tests for Nutanix

test/e2e/prometheus.go
=> Fix prometheus e2e

docs/content/en/docs/reference/faq/_index.md
Added FAQ items based on customer feedback to clarify EKS-A vs ECS-A and add more information about EKS-A cost.
Ran and verified documentation locally.
=> Update FAQ with cost and ECS comparison

pkg/providers/tinkerbell/stack/stack.go, pkg/providers/tinkerbell/stack/stack_test.go
The new version of Boots being used requires this additional environment variable.
=> Add Tinkerbell Boots in Docker on admin machine env var:

docs/content/en/docs/reference/eksctl/_index.md
=> Fix support bundle doc

internal/pkg/api/vsphere.go, test/e2e/vsphere_test.go, test/framework/vsphere.go
Add e2e tests for vSphere clone mode
=> Add e2e tests for vSphere clone mode

cmd/integration_test/build/buildspecs/snow-test-eks-a-cli.yml
Since all the Snow tests are skipped, no junit files are available, so this step fails trying to upload artifacts.
=> Remove reports section from Snow buildspec

test/e2e/nutanix_test.go
=> Fix Nutanix OIDC tests

docs/content/en/docs/reference/support/support-versions.md
*Description of changes:* Added support information to support-versions documentation for version 0.14.
=> Added 0.14 support info to versions page

docs/content/en/docs/reference/artifacts.md
Updating artifacts links in docs.
=> Update artifacts links in docs

config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, config/manifest/eksa-components.yaml, release/api/v1alpha1/bundle_types.go, release/api/v1alpha1/zz_generated.deepcopy.go, release/config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, release/pkg/assets/archives/archives.go, release/pkg/assets/config/bundle_release.go, release/pkg/bundles/eksd.go, release/pkg/filereader/file_reader.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.14-bundle-release.yaml
Adding Bottlerocket AWS variant to bundle manifest
=> Add Bottlerocket AMIs to bundle manifest

docs/content/en/docs/concepts/clusterworkflow.md, docs/content/en/docs/getting-started/install/_index.md, docs/content/en/docs/getting-started/production-environment/snow-getstarted.md, docs/content/en/docs/reference/clusterspec/snow.md, docs/content/en/docs/tasks/cluster/cluster-upgrades/vsphere-and-cloudstack-upgrades.md
=> Update EKS-A Snow doc based on AWS Snow doc

docs/content/en/docs/tasks/troubleshoot/troubleshooting.md
[#1111](https://github.com/aws/eks-anywhere/issues/1111)
=> Add snow troubleshooting guide

cmd/integration_test/build/buildspecs/build-eks-a-cli.yml
Too many dollars is sometimes a bad thing.
=> Fix variable substitution in buildspec

docs/content/en/docs/tasks/packages/troubleshoot.md
Secret creation for packages is no longer handled by CLI.
=> Remove outdated information

controllers/factory.go, pkg/providers/tinkerbell/reconciler/mocks/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler_test.go
Reconcile CNI in Tinkerbell cluster
=> Reconcile CNI for Tinkerbell provider

docs/content/en/docs/reference/packagespec/_index.md, docs/content/en/docs/reference/packagespec/adot/v0.25.0.md, docs/content/en/docs/tasks/packages/_index.md, docs/content/en/docs/tasks/packages/adot/_index.md
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/786
=> Update ADOT docs to v0.25.0

cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml, test/e2e/vsphere_test.go, test/framework/vsphere.go
=> Add BR 1.25 VSphere tests

internal/test/testdata.go, pkg/awsiamauth/reconciler/reconciler_test.go, pkg/providers/docker/reconciler/reconciler_test.go, pkg/providers/snow/reconciler/reconciler_test.go, pkg/providers/tinkerbell/cluster.go, pkg/providers/tinkerbell/reconciler/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler_test.go, pkg/providers/vsphere/reconciler/reconciler_test.go
Add cluster spec Validations for Tinkerbell Controller.
- unit tests
=> Cluster Spec assertions in Tinkerbell reconciler

docs/content/en/docs/reference/clusterspec/cloudstack.md
=> Use capitalized list name for consistency in doc

pkg/providers/tinkerbell/reconciler/reconciler_test.go
Add naming for package import
- make
=> Add naming for package import

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml
Adding back the cleanup flag for cloudstack
=> Adding the cleanup step for cloudstack

config/manifest/eksa-components.yaml, config/rbac/role.yaml, controllers/cluster_controller.go, controllers/cluster_controller_legacy.go
=> Add Tinkerbell resources to RBAC

docs/content/en/docs/reference/clusterspec/optional/registrymirror.md
=> update registry auth docs

config/manifest/eksa-components.yaml, config/rbac/role.yaml, controllers/cluster_controller.go, controllers/cluster_controller_legacy.go, internal/test/envtest/environment.go, manager/main.go, pkg/providers/tinkerbell/hardware/etcd.go, pkg/providers/tinkerbell/hardware/etcd_test.go, pkg/providers/tinkerbell/reconciler/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler_test.go
*Issue: https://github.com/aws/eks-anywhere-internal/issues/1045*
Adding hardware validations for tinkerbell controller.
*Testing:*
`make docker-build` and tested the controller to ensure validations work.
=> Tinkerbell controller hardware validations 

docs/content/en/docs/reference/clusterspec/snow.md
=> Remove bottlerocket in snow doc

docs/content/en/docs/getting-started/install/_index.md, docs/content/en/docs/reference/changelog.md
=> Update release branch changelog for release v0.14.1

docs/content/en/docs/getting-started/install/_index.md, docs/content/en/docs/reference/changelog.md
=> Update main branch changelog for v0.14.1

pkg/api/v1alpha1/snowmachineconfig.go, pkg/api/v1alpha1/snowmachineconfig_test.go, pkg/api/v1alpha1/snowmachineconfig_types.go
Part 1 of https://github.com/aws/eks-anywhere/issues/4880
Add instance types snowball newly supports. 
Unit tests
=> Add new instance type snow supports

docs/content/en/docs/reference/clusterspec/snow.md
PR that supports more instance type in snow: https://github.com/aws/eks-anywhere/pull/4881
=> Update snow doc

designs/package-spec.md
Proposed design for cluster specification change to configure package controller installation.
Partially fixes: https://github.com/aws/eks-anywhere-packages/issues/635
=> Package controller specification design

docs/content/en/docs/tasks/troubleshoot/troubleshooting.md
This PR adds a Nutanix troubleshooting section in the documentation
=> Added Nutanix troubleshooting section

docs/content/en/docs/concepts/clusterworkflow.md, docs/content/en/docs/getting-started/install/_index.md, docs/content/en/docs/getting-started/production-environment/snow-getstarted.md, docs/content/en/docs/reference/artifacts.md, docs/content/en/docs/reference/clusterspec/snow.md, docs/content/en/docs/reference/ports.md, docs/content/en/docs/tasks/cluster/cluster-upgrades/vsphere-and-cloudstack-upgrades.md, docs/content/en/docs/tasks/troubleshoot/troubleshooting.md
This reverts commit 804e5d8c686f04d2bd8c793886304e4a97ea8d74.
Release Snow doc for EKS-A Snow GA.
=> Revert "Revert Snow doc in release branch (#4784)"

config/crd/bases/anywhere.eks.amazonaws.com_snowmachineconfigs.yaml, config/manifest/eksa-components.yaml, internal/pkg/api/snow.go, internal/pkg/api/snowmachines.go, pkg/api/v1alpha1/snowmachineconfig.go, pkg/api/v1alpha1/snowmachineconfig_test.go, pkg/api/v1alpha1/snowmachineconfig_types.go, pkg/api/v1alpha1/snowmachineconfig_webhook_test.go, pkg/providers/snow/validator.go
Manually cherry-pick https://github.com/aws/eks-anywhere/pull/4895 as auto cherry-pick fails.
=> Replace snow instance type exact match with regex validation (#4895)

pkg/api/v1alpha1/cluster_types.go, pkg/features/features.go, pkg/features/features_test.go, pkg/validations/cluster.go, pkg/validations/cluster_test.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations.go, test/e2e/conformance_test.go, test/e2e/docker_test.go, test/e2e/nutanix_test.go, test/e2e/snow_test.go, test/e2e/tinkerbell_test.go, test/e2e/vsphere_test.go
=> Remove 1.25 feature flag and add 1.26 feature flag

docs/content/en/docs/getting-started/production-environment/snow-getstarted.md, docs/content/en/docs/reference/clusterspec/snow.md, docs/content/en/docs/tasks/cluster/cluster-upgrades/vsphere-and-cloudstack-upgrades.md
=> Insert AWS Snow doc links in eksa doc

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/clustermanager/eksa_installer_test.go, pkg/providers/tinkerbell/config/template-cp.yaml, pkg/providers/tinkerbell/config/template-md.yaml, pkg/providers/tinkerbell/create.go, pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/testdata/cluster_tinkerbell_proxy.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_proxy.yaml, pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md_proxy.yaml, pkg/providers/tinkerbell/tinkerbell_test.go
This PR is for adding support for proxy feature for tinkerbell provider management cluster creation. I will be adding more PRs to support this feature.
=> Added support for proxy feature for tinkerbell provider

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go
=> Update default kube version to 1.25

docs/content/en/docs/reference/baremetal/bare-custom-hookos.md
Changed git commit tag in the doc to point it to a newer commit.
=> Changed hook commit tag to  to correct commit

pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go
wait for a bundle to be active as well as eksa-packages-[clusterName] namespace to be created
=> Wait for eksa-packages-[clusterName] namespace

test/e2e/upgrade_test.go
This is a replacement of https://github.com/aws/eks-anywhere/pull/4945
=> Fix snow e2e error in release branch

docs/content/en/docs/getting-started/local-environment/_index.md, docs/content/en/docs/getting-started/production-environment/nutanix-getstarted.md, docs/content/en/docs/getting-started/production-environment/vsphere-getstarted.md, docs/content/en/docs/reference/artifacts.md, docs/content/en/docs/reference/clusterspec/baremetal.md, docs/content/en/docs/reference/clusterspec/nutanix.md, docs/content/en/docs/reference/clusterspec/snow.md, docs/content/en/docs/reference/clusterspec/vsphere.md, docs/content/en/docs/reference/support/support-versions.md, docs/content/en/docs/reference/vsphere/vsphere-ovas.md, docs/content/en/docs/tasks/cluster/cluster-upgrades/baremetal-upgrades.md, docs/content/en/docs/tasks/cluster/cluster-upgrades/vsphere-and-cloudstack-upgrades.md
=> Update docs for 1.25

test/framework/taints.go
Add validation to the release branch
=> Update control plane taints validation for e2e

test/e2e/curated_packages_test.go
=> Add package k8 1.25 tests

cmd/integration_test/build/buildspecs/conformance-eks-a-cli.yml, cmd/integration_test/build/buildspecs/test-eks-a-cli.yml, test/e2e/autoscaler_test.go, test/e2e/awsiam_test.go, test/e2e/flux_test.go, test/e2e/labels_test.go, test/e2e/proxy_test.go, test/e2e/registry_mirror_test.go, test/e2e/simpleflow_test.go, test/e2e/taints_test.go, test/e2e/upgrade_test.go, test/e2e/vsphere_autoimport_test.go, test/e2e/vsphere_disable_csi_test.go, test/framework/vsphere.go
=> Add BR tests to release-0.14 branch

docs/content/en/docs/getting-started/install/_index.md
*Description of changes:* alert section has issue support complicated content, the footnote was not rendered correctly because of this.
*Testing (if applicable):* make container-serve, and the rendered web page doesn't have the footer rendering issue.
=> Fix note section rendering issue

docs/content/en/docs/reference/clusterspec/optional/registrymirror.md
Closes: https://github.com/aws/eks-anywhere/issues/4985
Closes: https://github.com/aws/eks-anywhere/issues/4983
=> Make copy packages documents more precise

designs/autoscaler.md
=> Update autoscaler design doc

docs/content/en/docs/getting-started/production-environment/snow-getstarted.md, docs/content/en/docs/getting-started/production-environment/vsphere-getstarted.md, docs/content/en/docs/tasks/cluster/cluster-flux.md, docs/content/en/docs/tasks/cluster/cluster-terraform.md
Adding docs on using Terraform to fully manage clusters.
This PR also slightly reworks the existing full lifecycle API docs to provide more information
=> Add docs for Terraform full lifecycle api

internal/test/e2e/packages.go, internal/test/e2e/setup.go, test/framework/curatedpackages.go
=> Export environment variables to cert manager tests

docs/content/en/docs/getting-started/local-environment/_index.md, docs/content/en/docs/getting-started/production-environment/snow-getstarted.md
Updates docker full lifecycle docs to mention Terraform. 
Also fixes the path for the snow sshKeyName 
=> Add docs for using Terraform to create local workload clusters

pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/template.go, pkg/providers/vsphere/testdata/cluster_bottlerocket_ntp_config.yaml, pkg/providers/vsphere/testdata/cluster_ubuntu_ntp_config.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_ntp_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_ntp_config_md.yaml, pkg/providers/vsphere/testdata/expected_results_ubuntu_ntp_config_cp.yaml, pkg/providers/vsphere/testdata/expected_results_ubuntu_ntp_config_md.yaml
Pass NTP servers configured for ETCD to etcd nodes independently of control planes
=> Pass NTP servers configured for ETCD to etcd nodes

config/manifest/eksa-components.yaml, config/rbac/role.yaml, controllers/cluster_controller.go, controllers/cluster_controller_legacy.go
=> Add watches for CloudStack resources to controller

docs/content/en/docs/concepts/eksafeatures.md
*Issue #, if available:* [Issue #1479](https://github.com/aws/eks-anywhere/issues/1479)
*Description of changes:* Update the [Compare EKS Anywhere and EKS](https://anywhere.eks.amazonaws.com/docs/concepts/eksafeatures/) page in the EKS Anywhere docs to describe differences between EKS Anywhere and Outposts.
=> Add docs comparing EKS Anywhere to EKS on Outposts

pkg/cluster/build.go, pkg/cluster/cloudstack.go, pkg/cluster/cloudstack_test.go
=> Add client process for CloudStack machine configs

docs/content/en/docs/reference/artifacts.md, docs/content/en/docs/reference/support/support-versions.md
* Update bundle release number
* Adding 1.25 tags to artifacts docs
* Include missing commands for directory change, SSH directory, etc
=> Add 1.25 tags to artifacts docs, include missing commands

cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml, internal/pkg/api/vsphere.go, internal/test/e2e/ntp.go, internal/test/e2e/setup.go, pkg/executables/builder.go, pkg/executables/builder_test.go, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/executables/ssh.go, pkg/executables/ssh_test.go, test/e2e/ntp.go, test/e2e/vsphere_test.go, test/framework/executables.go, test/framework/ntp.go, test/framework/vsphere.go
Add e2e test for Bottlerocket and Ubuntu for configuring NTP
Ran and validated the tests locally
=> Add e2e test for NTP settings for vSphere

pkg/api/v1alpha1/tinkerbelltemplateconfig.go, pkg/api/v1alpha1/tinkerbelltemplateconfig_defaults.go, pkg/api/v1alpha1/tinkerbelltemplateconfig_defaults_test.go, pkg/providers/tinkerbell/template.go
Allow proxy support for stream image action OS URL Tinkerbell.
=> Allow proxy support for stream image action OS URL Tinkerbell

internal/test/cleanup/cleanup.go, pkg/executables/govc.go, pkg/executables/govc_test.go, pkg/providers/vsphere/mocks/client.go, pkg/providers/vsphere/validator.go, pkg/providers/vsphere/validator_test.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
1571
Validate template disk size for bottlerocket with Vsphere provider
Verified changes by testing.
=> Disk Size Validation for bottlerocket with Vsphere provider

controllers/cloudstack_datacenter_controller.go, controllers/cloudstack_datacenter_controller_test.go, controllers/factory.go, controllers/factory_test.go
Build and register new datacenter reconciler for CloudStack
=> register cloudstack datacenter reconciler

docs/content/en/docs/reference/artifacts.md
* Add subnet ID to AMI parameter list
* Clarify volume type support
=> Add subnet ID field to AMI docs

PROJECT, config/manifest/eksa-components.yaml, config/webhook/manifests.yaml, pkg/api/v1alpha1/cloudstackdatacenterconfig_test.go, pkg/api/v1alpha1/tinkerbellmachineconfig.go, pkg/api/v1alpha1/tinkerbellmachineconfig_types.go, pkg/api/v1alpha1/tinkerbellmachineconfig_types_test.go, pkg/api/v1alpha1/tinkerbellmachineconfig_webhook.go, pkg/api/v1alpha1/tinkerbellmachineconfig_webhook_test.go, pkg/api/v1alpha1/vspheremachineconfig.go, pkg/constants/constants.go
Add defaults for Tinkerbell Machine Config
- Unit tests
=> Add defaults for Tinkerbell Machine Config

PROJECT, config/manifest/eksa-components.yaml, config/webhook/manifests.yaml, pkg/api/v1alpha1/cloudstackdatacenterconfig_webhook.go, pkg/api/v1alpha1/cloudstackdatacenterconfig_webhook_test.go
=> Add cloudstack mutation webhook for datacenter config

conformance/Makefile, conformance/template/README.md.end, test/framework/conformance.go
=> Replace use of `k8s.gcr.io` with `registry.k8s.io`

docs/content/en/docs/reference/clusterspec/optional/irsa.md
=> Update pod IRSA doc

docs/content/en/docs/reference/changelog.md
Manual cherry-pick of changelog (auto process failed).
=> Add v0.14.3 changelog (#5133)

docs/content/en/docs/reference/baremetal/bare-prereq.md, docs/content/en/docs/reference/ports.md
Fixes incorrect information and adds missing details
=> Update docs around ports, protocols, and BMCs:

docs/content/en/docs/tasks/cluster/cluster-terraform.md
=> Mention that Terraform is supported with Snow clusters

docs/content/en/docs/tasks/troubleshoot/troubleshooting.md
https://cluster-api.sigs.k8s.io/clusterctl/commands/additional-commands.html#clusterctl-backup
=> clusterctl backup deprecated

docs/content/en/docs/tasks/packages/troubleshoot.md
Partial: https://github.com/aws/eks-anywhere/issues/4832
=> Clean up image pull backoff error

docs/content/en/docs/reference/artifacts.md
=> Remove snow from BR doc

internal/test/envtest/client.go
For objects without a status or with an empty status, we weren't waiting for them to be ready. So depending on the list of objects, it was possible for `CreateObjs` to return before all objects were available through the client.
Now for objects that don't require an status update, we skip the status update and just wait for the object to be readable.
=> Improve envtest obj creation

docs/content/en/docs/tasks/packages/_index.md
Closes: https://github.com/aws/eks-anywhere/issues/4832
=> Instructions on how to add package controller

docs/developer/best-practice.md
Simplify the best practice and lean into existing resources in an effort to stay up-to-date and reduce regurgitation.
=> Update best practice to simplify and reference established guidelines.

pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/upgrade.go
Remove redundant checks in the Tinkerbell CAPI object generation.
=> Remove superfluous logic in Tinkerbell template generation

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/clustermanager/retrier_client.go
Follow up on https://github.com/aws/eks-anywhere/pull/5151#discussion_r1130000128
=> Make cluster manager retrier a private field

test/e2e/docker_test.go, test/e2e/tinkerbell_test.go, test/e2e/vsphere_test.go, test/framework/cluster.go, test/framework/tinkerbell.go, test/framework/vsphere.go
=> Add simple flow 1.26 tests

pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go, pkg/api/v1alpha1/hostosconfig_test.go
Validation for rolling and scaling upgrades for Tinkerbell
- unit test
=> Validation for rolling and scaling upgrades for Tinkerbell

docs/content/en/docs/getting-started/production-environment/baremetal-getstarted.md
*Description of changes:* This updates the Bare Metal getting started guide to show how to create airgapped Bare Metal clusters.
=> Add airgapped to Bare Metal docs

pkg/api/v1alpha1/tinkerbellmachineconfig.go, pkg/api/v1alpha1/tinkerbellmachineconfig_webhook.go
Make ssh keys optional for tinkerbell cli
=> Make ssh keys optional for tinkerbell cli

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml
=> Increase cloudstack e2e log level

designs/snow-integration.md, docs/content/en/docs/reference/clusterspec/snow.md, pkg/api/v1alpha1/snowmachineconfig.go, pkg/api/v1alpha1/snowmachineconfig_test.go
Follow up on #5256
Add volume size validation, update eks-a doc and snow design doc.
=> Add volume size validation for snow non root volume, update doc

pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/testdata/expected_results_tinkerbell_pod_iam_config.yaml, pkg/providers/tinkerbell/tinkerbell_test.go
#4361
IRSA support for bare metal is implemented
Verified with E2E test.
=> IRSA support for baremetal

config/crd/bases/anywhere.eks.amazonaws.com_snowmachineconfigs.yaml, config/manifest/eksa-components.yaml, docs/content/en/docs/reference/clusterspec/snow.md, pkg/providers/snow/api/v1beta1/awssnowmachine_types.go, pkg/providers/snow/api/v1beta1/types.go
Update EKS-A Snow volume based on CAPAS v0.1.25 API https://github.com/aws/eks-anywhere-build-tooling/pull/2004
=> Update snow supported volume field

docs/content/en/docs/tasks/cluster/cluster-upgrades/baremetal-upgrades.md
=> Update outdated upgradeRolloutStrategy doc

test/framework/cluster.go
Increase wait time for harbor to be up so e2e test can pass
=> increase wait time for harbor to be up

docs/content/en/docs/reference/changelog.md
=> Update chagenlog for 0.14.4

docs/content/en/docs/reference/changelog.md
=> Add 0.14.4 Changelog

docs/content/en/docs/tasks/troubleshoot/troubleshooting.md
Doc update mentioning management cluster backup/restore feature for upgrade
=> Doc update: upgrade management cluster backup/restore feature

go.mod
This reverts commit b1681d65f6af1ee2b475916b1a4f51c2c4be3e99.
=> Revert "Update opencontainers/runc (#5306)"

Makefile
=> Update branch name to release-0.15

docs/content/en/docs/reference/clusterspec/nutanix.md, docs/content/en/docs/tasks/cluster/cluster-terraform.md
N/A
- Added projects documentation
- Modified Terraform note
- Added additionalTrustBundle example
=> Add doc for Nutanix projects and Terraform support

pkg/clustermanager/eksa_installer.go, pkg/clustermanager/eksa_installer_test.go
Enable full lifecycle support for Tinkerbell
=> Enable full lifecycle support for Tinkerbell

docs/content/en/docs/reference/clusterspec/optional/registrymirror.md, docs/content/en/docs/reference/eksctl/_index.md
=> Add insecureSkipVerify in registry mirror doc

pkg/executables/kubectl.go, pkg/validations/createvalidations/cluster_test.go
* Expand all kubectl calls to fully qualified names
=> Expand all kubectl calls to fully qualified names (#5332)

test/e2e/curatedpackages.go, test/e2e/docker_test.go, test/e2e/metallb.go
=> Update e2e pkg metallb && Wait for pkg controller installation

Makefile, test/e2e/cloudstack_test.go, test/e2e/curatedpackages.go, test/e2e/docker_test.go, test/e2e/metallb.go, test/e2e/nutanix_test.go, test/e2e/tinkerbell_test.go, test/e2e/vsphere_test.go, test/framework/cluster.go, test/framework/curatedpackages.go
Very basic e2e test for packages cluster spec
=> Packages e2e cluster spec

docs/content/en/docs/reference/changelog.md
Adding changelog for release v0.14.5.
=> Add changelog for release v0.14.5

test/framework/releaseVersions.go
It was failing when being run in a release branch for an not yet released minor version.
Manually ran e2e test
=> Fix next version detection in e2e tests

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml
=> Reduce logging verbosity in cloudstack e2e runner

docs/content/en/docs/reference/clusterspec/optional/etcd.md
N/A
Updated docs to indicate which Amazon EKS Anywhere deployment options do not support the unstacked etcd topology which is recommended.
N/A
=> Updated docs to indicate if unstacked etcd topology is supported

pkg/providers/tinkerbell/rufiounreleased/baseboardmanagement.go, pkg/providers/tinkerbell/tinkerbell.go, pkg/providers/tinkerbell/tinkerbell_test.go, pkg/providers/tinkerbell/upgrade.go, pkg/providers/tinkerbell/upgrade_test.go
Add missing unit tests for Rufio CRD conversions.
=> Add Tinkerbell stack upgrade unit tests

docs/content/en/docs/reference/changelog.md, docs/content/en/docs/reference/clusterspec/optional/registrymirror.md
This PR updates the changelog for release v0.15.0. 
Change to note: Courtesy of @panktishah26, added showing latest supported OS version per provider. This is helpful when customer uses older CLI versions and wants to update their OS.
=> Update changelog for  v0.15.0

docs/content/en/docs/reference/changelog.md
=> Fix changelog

docs/content/en/docs/tasks/cluster/etcd-backup-restore.md
=> Update etcd backup doc for snow

docs/config.toml, docs/content/en/docs/reference/artifacts.md, docs/content/en/docs/reference/support/support-versions.md
This PR updates docs necessary for release. It also makes changes to indicate how to grab artifacts for a specific release, defaulting to v0.15.0
=> Update docs for release-0.15

docs/content/en/docs/tasks/packages/_index.md
*Description of changes:* Add documentation for how to upgrade the package controller.
This commit is running here:
https://docs.dx3ehyyttf163.amplifyapp.com/docs/tasks/packages/
=> Add upgrade docs for pkg controller

docs/content/en/docs/reference/changelog.md
=> Remove unreleased from changelog

docs/content/en/docs/reference/changelog.md
Add changelog for EKS-A v0.14.6
=> Add changelog for EKS-A v0.14.6

docs/content/en/docs/reference/artifacts.md
=> Fix BR ova version in doc

docs/content/en/docs/reference/clusterspec/nutanix.md
Add `credentialRef` to the NutanixDatacenterConfig spec in docs.
=> Update NutanixDatacenterConfig docs

docs/content/en/docs/reference/changelog.md
=> Update changelog release for v0.15.1

docs/content/en/docs/reference/artifacts.md
This updates the changes in eksD versions, in addition to the references to the version 0.15.0 -> 0.15.1 in the docs.
=> Update docs for release v0.15.1

docs/content/en/docs/reference/changelog.md
=> Backport v0.15.1 changelog to main

docs/content/en/docs/reference/clusterspec/vsphere.md
Add docs for vSphere cloneMode feature implemented here https://github.com/aws/eks-anywhere/pull/4634
=> Add vSphere cloneMode docs

pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/controlplane.go, pkg/providers/cloudstack/controlplane_test.go, pkg/providers/cloudstack/machinetemplate.go, pkg/providers/cloudstack/template.go, pkg/providers/cloudstack/template_test.go
[Generate cp capi objects#971](https://github.com/aws/eks-anywhere-internal/issues/971)
=> Generate cloudstack CP CAPI objects

docs/content/en/docs/tasks/cluster/cluster-flux.md, docs/content/en/docs/tasks/cluster/cluster-terraform.md
=> Add upgrade examples for full lifecycle TF and Gitops

docs/assets/scss/_styles_project.scss, docs/content/en/docs/tasks/cluster/manually-renew-certs.md
=> Add manual certs renewal page

docs/content/en/docs/getting-started/local-environment/_index.md, docs/content/en/docs/getting-started/production-environment/nutanix-getstarted.md, docs/content/en/docs/getting-started/production-environment/vsphere-getstarted.md, docs/content/en/docs/reference/artifacts.md, docs/content/en/docs/reference/clusterspec/baremetal.md, docs/content/en/docs/reference/clusterspec/cloudstack.md, docs/content/en/docs/reference/clusterspec/nutanix.md, docs/content/en/docs/reference/clusterspec/snow.md, docs/content/en/docs/reference/clusterspec/vsphere.md, docs/content/en/docs/reference/support/support-versions.md, docs/content/en/docs/tasks/cluster/cluster-iam-auth.md, docs/content/en/docs/tasks/cluster/cluster-upgrades/vsphere-and-cloudstack-upgrades.md
Add docs to mention 1.26 support
=> Add docs to mention 1.26 support

cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/options.go, cmd/eksctl-anywhere/cmd/upgradecluster.go, pkg/clustermanager/kube_proxy.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go, pkg/networking/cilium/client.go, pkg/networking/cilium/client_test.go
Part of #5565
Respect `--no-timeouts` in cilium installer.
Unit tests
=> Add notimeouts option for cilium

docs/content/en/docs/tasks/cluster/etcd-backup-restore/_index.md, docs/content/en/docs/tasks/cluster/etcd-backup-restore/bottlerocket-etcd-backup.md, docs/content/en/docs/tasks/cluster/etcd-backup-restore/ubuntu-rhel-etcd-backup.md
https://github.com/aws/eks-anywhere/issues/5489
Add ETCD backup/restore docs for Bottlerocket
=> Add ETCD backup/restore docs for Bottlerocket

internal/test/envtest/environment.go, pkg/providers/cloudstack/reconciler/reconciler.go, pkg/providers/cloudstack/reconciler/reconciler_test.go
[Implement ReconcileControlPlane#1014](https://github.com/aws/eks-anywhere-internal/issues/1014)
unit test
=> cloudstack reconcile cp

pkg/clustermanager/cluster_manager.go
Part of #5565 
Added `--no-timeouts` flag support for clusterctl move operation during create and upgrade cluster operation. This no timeout includes clusterctl move operation while moving CAPI resources from source cluster to target cluster during create/upgrade and also includes no timeout for taking cluster resources backup during an upgrade process.
Create cluster
Stage: capi-management-move
```
V5	Retrier:	{"timeout": "2562047h47m16.854775807s", "backoffFactor": null}
V6	Executing command	{"cmd": "/usr/local/bin/docker exec -i eksa_1681352585161130000 clusterctl move --to-kubeconfig pjshah/pjshah-eks-a-cluster.kubeconfig --namespace eksa-system --kubeconfig pjshah/generated/pjshah.kind.kubeconfig"}
``` …
=> Added --no-timeouts support for clusterctl move operations

test/e2e/vsphere_test.go
UpgradeKubernetesCiliumDisableCSIUbuntuAPI produces inconsistent results every time it is run and takes far longer than other tests. Splitting it up into 2 tests should increase consistency. 
=> Split flaky VSphere full lifecycle E2E

pkg/providers/snow/snow.go, pkg/providers/snow/snow_test.go
Without this, the new kubectl implementation fails since it doesn't allow an empty string for namespace. Most of the time, users pass the eks-a objects with no namespace, which means they get created in the `default` namespace.
Before it was miraculously working since kubectl works even if you pass the `--namespace` flag with no value, it just uses `default`.
This makes sure all API calls that try to extract the namespace from the eks-a objects pass a namespace, even when the objects don't have it set.
It also ignores errors when trying to delete an object that doesn't exist.
@taneyland ran manual tests with snow for both upgrade and delete 🙏🏻 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
=> Handle snow objects with no namespace in api calls

docs/content/en/docs/reference/clusterspec/nutanix.md
Add optional config section for Nutanix
=> Add optional config section for Nutanix

controllers/cloudstack_datacenter_controller.go, controllers/cloudstack_datacenter_controller_test.go
[datacenter reconciler#1267](https://github.com/aws/eks-anywhere-internal/issues/1267)
=> reconcile cloudstack datacenter

docs/content/en/docs/reference/packagespec/credential-provider-package/_index.md, docs/content/en/docs/reference/packagespec/credential-provider-package/v0.1.0.md, docs/content/en/docs/tasks/packages/credential-provider-package/_index.md, docs/content/en/docs/workshops/packages/credential-provider-package/_index.md, docs/content/en/docs/workshops/packages/credential-provider-package/iam_roles_anywhere.md
Docs for new credential provider package
Original PR #5416
=> Manual cherry-pick of #5416 with one additional fix for casing of link

docs/content/en/docs/reference/changelog.md
=> Update changelog for version v0.15.2

docs/content/en/docs/reference/changelog.md
=> Backport changelog v0.15.2

test/e2e/curatedpackages.go, test/framework/cluster.go
=> Packages e2e support bundle

test/e2e/SKIPPED_TESTS.yaml
Skip vSphere Ubuntu upgrade API test
=> Skip vSphere Ubuntu upgrade API test

docs/content/en/docs/reference/changelog.md
=> Add Tinkerbell warning in changelog

pkg/providers/cloudstack/reconciler/reconciler.go, pkg/providers/cloudstack/reconciler/reconciler_test.go
https://github.com/aws/eks-anywhere-internal/issues/978
Manually tested adding labels, scaling up worker node on management cluster.
=> CloudStack reconcile worker node

manager/main.go
=> register datacenter reconciler

pkg/executables/kubectl.go, pkg/executables/kubectl_test.go
Even if `--save-config=false` is set (which is the default), kubectl replace will not only respect the last-applied annotation if present in the object, but it will update it with the provided state of the resource. This includes the `metadata.resourceVersion`. This breaks future uses of kubectl apply. Since those commands' input never provide the `resourceVersion`, kubectl will send a request trying to remove that field. That is obviously not a valid request, so it gets rejected by the kube API server. To avoid this, we simply remove the annotation when passing it to the replace command.
Important to note that it's not recommended to use both imperative and "declarative" commands for the same resource. Unfortunately our CLI makes extensive use of client side apply. Although not ideal, …
=> Remove last-applied annotation for kubectl replace

pkg/api/v1alpha1/cluster_types.go, pkg/features/features.go, pkg/features/features_test.go, pkg/validations/cluster.go, pkg/validations/cluster_test.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations.go
=> Add 1.27 feature flag

docs/content/en/docs/reference/changelog.md
Update changelog for EKS-A v0.15.3.
=> Update changelog for EKS-A v0.15.3

cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml, test/e2e/docker_test.go, test/e2e/tinkerbell_test.go, test/e2e/vsphere_test.go, test/framework/cluster.go, test/framework/tinkerbell.go, test/framework/vsphere.go
=> Add initial 1-27 simpleflow tests

docs/content/en/docs/reference/clusterspec/nutanix.md
=> Update Nutanix config doc with custom dns option

designs/isolate-cluster-upgrades.md
=> Add design for workload cluster upgrade isolation

docs/content/en/docs/reference/artifacts.md
=> Update snow node ami builder doc

docs/content/en/docs/tasks/cluster/cluster-upgrades/vsphere-and-cloudstack-upgrades.md
Add documentation on CloudStack immutable fields.
Closes #5312
=> Update CloudStack immutable fields docs

internal/test/e2e/fluxGit.go
Tinkerbell end to end tests are failing with an error for git private keys which are in invalid format. After looking into the ssm commands we run for e2e, what stood out was when the generated private key was getting written to a file on the instance, the format was getting messed up.
In this PR, we are encoding the generated private key, and then writing back the decoded value of that private key using base64. This will ensure that the format stays intact.
=> Encode git private key using base64

cmd/integration_test/build/buildspecs/tinkerbell-test-eks-a-cli.yml
=> Remove unused/unnecessary commands from tinkerbell buildspec

test/e2e/docker_test.go, test/e2e/tinkerbell_test.go, test/e2e/vsphere_test.go, test/framework/cluster.go, test/framework/tinkerbell.go
=> Add additional 1-27 e2e for docker, vsphere, and tinkerbell

pkg/providers/tinkerbell/assert_test.go, pkg/providers/tinkerbell/stack/stack_test.go, pkg/providers/tinkerbell/upgrade_test.go
=> Resolve unit test error

designs/pod-disruption-budget-preflights.md
https://github.com/aws/eks-anywhere/issues/5189
Upgrade preflight validations for PDB design doc. This has been moved to Github post the service team review on Quip.
=> Upgrade preflight validations for PDB design doc

pkg/providers/snow/reconciler/reconciler.go
=> Fix snow controller log

docs/content/en/docs/reference/clusterspec/optional/proxy.md
Added note for proxy configuration changes for Bare metal provider and Bottlerocket OS.
=> Proxy configuration changes for Bare metal provider and Bottlerocket OS

test/e2e/SKIPPED_TESTS.yaml
Enabling skipped test for cloudstack
=> Enabling skipped test

internal/test/e2e/fluxGit.go
Update fluxGit.go to fix base64 error.
- SSM command run
=> Update fluxGit.go to fix base64 error

internal/test/e2e/proxy.go
Added Tinkerbell in the list of proxy e2e tests.
=> change proxy config setting

test/e2e/vsphere_test.go
=> Fix TestVSphereKubernetes126To127OIDCUpgrade E2E test

test/e2e/SKIPPED_TESTS.yaml, test/e2e/tinkerbell_test.go, test/e2e/vsphere_test.go, test/framework/vsphere.go
Add 1-27 Bottlerocket E2E tests
=> Add BR 1-27 E2E tests

docs/content/en/docs/reference/changelog.md
=> Changelog for v0.15.4

docs/content/en/docs/reference/changelog.md
=> Changelog for v0.15.4 (#5869)

docs/content/en/docs/reference/changelog.md
Initially didn't include the PR link as I thought we were just adding issues links, but this gives necessary context for the issue that was resolved.
=> Add PR link to changelog item

test/e2e/cloudstack_test.go, test/e2e/docker_test.go, test/e2e/metallb.go, test/e2e/nutanix_test.go, test/e2e/tinkerbell_test.go, test/e2e/vsphere_test.go, test/framework/cluster.go
=> Support new kubeversion for curated package e2e tests

test/e2e/metallb.go
=> Update metallb e2e tests

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml, config/manifest/eksa-components.yaml, controllers/cluster_controller.go, controllers/cluster_controller_test.go, controllers/cluster_controller_test_test.go, pkg/api/v1alpha1/cluster_types.go
Implementation of proposed solution in #5622.
/hold
=> Isolate cluster upgrades for management and workload clusters

pkg/api/v1alpha1/cloudstackdatacenterconfig_webhook.go, pkg/api/v1alpha1/cloudstackdatacenterconfig_webhook_test.go, pkg/clustermanager/eksa_installer.go, pkg/clustermanager/eksa_installer_test.go
https://github.com/aws/eks-anywhere-internal/issues/1311
=> enable cloudstack flc

pkg/executables/executables.go, test/e2e/cloudstack_test.go, test/framework/awsiam.go, test/framework/cluster.go, test/framework/oidc.go, test/framework/workload.go
[E2E tests#1237](https://github.com/aws/eks-anywhere-internal/issues/1237)
=> add e2e cloudstack aws iam and oidc

internal/pkg/api/cluster.go, pkg/networking/cilium/installation.go, pkg/networking/cilium/reconciler/fetch.go, pkg/networking/cilium/reconciler/reconciler.go, test/e2e/docker_test.go, test/framework/cilium.go, test/framework/cluster.go, test/framework/cluster/validations/cluster.go, test/framework/clustervalidator.go, test/framework/multicluster.go, test/framework/release_versions.go, test/framework/workload.go
Add E2E tests for the new `skipUpgrade` Cilium CNI flag.
=> Implement skip Cilium upgrade E2Es

test/framework/cluster.go
=> Update ADOT e2e log comparison message

Makefile
=> update release branch name in makefile

docs/content/en/docs/getting-started/production-environment/cloudstack-getstarted.md, docs/content/en/docs/tasks/cluster/cluster-scale/cloudstack-scale.md, docs/content/en/docs/tasks/cluster/cluster-terraform.md
[Documentation cloudstack lifecycle support#998](https://github.com/aws/eks-anywhere-internal/issues/998)
[Adding mgmt cluster worker node lifecycle support in doc#1294](https://github.com/aws/eks-anywhere-internal/issues/1294)
=> add flc cloudstack doc

docs/content/en/docs/getting-started/local-environment/_index.md, docs/content/en/docs/getting-started/production-environment/nutanix-getstarted.md, docs/content/en/docs/getting-started/production-environment/vsphere-getstarted.md, docs/content/en/docs/reference/artifacts.md, docs/content/en/docs/reference/clusterspec/baremetal.md, docs/content/en/docs/reference/clusterspec/cloudstack.md, docs/content/en/docs/reference/clusterspec/nutanix.md, docs/content/en/docs/reference/clusterspec/snow.md, docs/content/en/docs/reference/clusterspec/vsphere.md, docs/content/en/docs/reference/support/support-versions.md, docs/content/en/docs/tasks/cluster/cluster-iam-auth.md, docs/content/en/docs/tasks/cluster/cluster-upgrades/vsphere-and-cloudstack-upgrades.md
Update docs to mention kubernetes 1.27 support
=> Add docs to mention 1.27 support

docs/content/en/docs/tasks/cluster/cluster-scale/baremetal-scale.md, docs/content/en/docs/tasks/cluster/cluster-upgrades/baremetal-upgrades.md
=> Fix small typos in docs

docs/content/en/docs/getting-started/production-environment/vsphere-getstarted.md, docs/content/en/docs/reference/changelog.md, docs/content/en/docs/reference/clusterspec/vsphere.md
https://github.com/aws/eks-anywhere/issues/5517
Add appropriate documentation for deprecating the field as added in the CLI here: https://github.com/aws/eks-anywhere/pull/5918
=> Add documentation for deprecating disableCSI

docs/config.toml, docs/content/en/docs/reference/artifacts.md, docs/content/en/docs/reference/support/support-versions.md
=> bump up doc site 0.16

docs/content/en/docs/reference/changelog.md
=> 0.16.0 changelog

docs/content/en/docs/whatsnew/changelog.md
*Description of changes:* Adding release-0.16 changelog back in from cherry pick.
=> 0.16.0 changelog (#5969)

docs/content/en/docs/workloadmgmt/ingress.md
https://github.com/aws/eks-anywhere/issues/5859
Updating docs based off GH issue suggestions.
=> Updating emissary docs based on GH issue suggestions

docs/content/en/docs/getting-started/optional/hostOSConfig.md
Add docs for kernel, boot and trusted cert bundle settings
=> Add docs for kernel, boot and trusted cert bundle settings

test/e2e/vsphere_test.go
=> Split out tests

test/e2e/docker_test.go
=> split out docker tests

docs/content/en/docs/whatsnew/changelog.md
N/A 
Add Nutanix changes to the v0.16.0 changelog
N/A
=> Added Nutanix changes to v0.16.0 changelog

designs/kindless-upgrades.md
=> Add design for kindless upgrades

docs/content/en/docs/packages/prereq.md, docs/content/en/docs/packages/troubleshoot.md, docs/content/en/docs/workloadmgmt/ingress.md
=> Updating emissary docs

test/e2e/cloudstack_test.go, test/e2e/upgrade_from_latest.go, test/framework/flux.go
=> Upgrade from latest minor release cloudstack API test

docs/content/en/docs/getting-started/docker/_index.md
Whitespace will always get us in trouble in YAML!
=> Fix whitespace issue on YAML sample in _index.md

docs/content/en/docs/getting-started/airgapped/_index.md
Minor typo in docs for air gapped method.
I've validated the command works.
=> Minor doc fix for extra space on CLI argument.

docs/content/en/docs/concepts/architecture.md
=> Update cluster deployment topology matrix

docs/content/en/docs/concepts/architecture.md
=> Reformat cluster deployment matrix

docs/content/en/docs/getting-started/docker/_index.md
In the "Install on Docker" section, instructions for deploying the test application were repeated. 
Removed duplicate text
=> docs: remove duplicate text

docs/content/en/docs/workloadmgmt/ingress.md
=> Add reference to Emissary's official documentation

docs/content/en/docs/whatsnew/changelog.md
=> 0.16.1 changelog

controllers/cluster_controller.go, controllers/cluster_controller_test.go, pkg/api/v1alpha1/condition_consts.go, pkg/controller/clusters/status.go, pkg/controller/clusters/status_test.go, pkg/networking/cilium/reconciler/reconciler.go, pkg/networking/cilium/reconciler/reconciler_test.go
#5628 
Changes to the Cluster status as per the the proposal [here](https://github.com/aws/eks-anywhere/pull/6005):
- Unit testing
=> Add DefaultCNIConfigured condition to cluster status

designs/bare-metal-out-of-band-webhook.md
The hash signature payload instructions were incorrect. This fixes them.
=> Correct the hash signature payload instructions.

docs/content/en/docs/getting-started/optional/autoscaling.md, docs/content/en/docs/packages/cluster-autoscaler/addclauto.md
Clarify docs:
- Provide strong recommendation on which deployment topology to follow
- Consolidate all necessary configs to a single place in the docs
The recommendations follows those in the design doc:
https://github.com/aws/eks-anywhere/blob/1e81579e0d8d8d997b1350985786fd24cbaa3109/designs/autoscaler.md#L131-L131
```
make serve
```
=> Recommend Cluster Autoscaler Deploy Topology

pkg/config/vsphereuser.go, pkg/config/vsphereuser_test.go, pkg/providers/vsphere/reconciler/reconciler_test.go, pkg/providers/vsphere/validator_test.go
Formatting fixes using gofumpt.
=> Formatting fixes

docs/content/en/docs/troubleshooting/troubleshooting.md
[1527](https://github.com/aws/eks-anywhere-internal/issues/1527)
Adds documentation for users on the WorkerNodeGroup NoSchedule/NoExecute validation.
=> adding NoSchedule taint troubleshooting documentation

Makefile
Update the branch name in the Makefile to the release branch name
=> Update branch name in Makefile

docs/content/en/docs/clustermgmt/cluster-upgrades/airgapped-upgrades.md, docs/content/en/docs/clustermgmt/cluster-upgrades/baremetal-upgrades.md, docs/content/en/docs/clustermgmt/cluster-upgrades/vsphere-and-cloudstack-upgrades.md, docs/content/en/docs/getting-started/airgapped/_index.md
[improve air gapped upgrade doc#1503](https://github.com/aws/eks-anywhere-internal/issues/1503)
=> airgap-upgrade-doc

docs/content/en/docs/clustermgmt/observability/cluster-verify.md
=> Update docs on cluster verification

internal/test/e2e/run.go
Fix Tinkerbell hardware reservation logic for CI. 
=> Tinkerbell CI dynamic hardware reservation logic fix

docs/content/en/_index.html
`failed to extract shortcode: shortcode "blocks/section" must be closed or self-closed` This allows the local build and serve to work.
properly.
=> Fix Hugo build issue:

docs/content/en/_index.html
The main page of the docs site had a broken footer due to a missing section close.
=> Fix broken index on docs site

docs/content/en/docs/clustermgmt/networking/cluster-replace-cilium.md
=> [Docs]Add CNI chaining support with Cilium in EKS-A

docs/content/en/docs/packages/best_practice.md, docs/content/en/docs/packages/harbor/_index.md, docs/content/en/docs/packages/harbor/addharbor.md
Update some of the harbor docs.
=> Harbor doc updates

pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_types_test.go, pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go, pkg/providers/cloudstack/cloudstack.go, pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/docker/docker.go, pkg/providers/nutanix/provider.go, pkg/providers/nutanix/provider_test.go, pkg/providers/tinkerbell/template.go, pkg/providers/tinkerbell/upgrade.go, pkg/providers/vsphere/vsphere.go, pkg/validations/upgradevalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations_test.go, pkg/validations/upgradevalidations/versions.go, pkg/validations/upgradevalidations/versions_test.go
Validations for modular k8s upgrades
=> K8s modular upgrade validations

docs/developer/cluster-lifecycle-api-provider-integration.md, manager/Tiltfile, pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go, pkg/api/v1alpha1/vspheredatacenterconfig_webhook_test.go, pkg/clustermanager/eksa_installer.go, pkg/clustermanager/eksa_installer_test.go, pkg/features/features.go, test/e2e/cloudstack_test.go
=> Remove full lifecycle API feature toggle

controllers/cluster_controller.go, controllers/cluster_controller_test.go, pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go, pkg/cluster/builder.go, pkg/cluster/fetch.go, pkg/controller/clusters/validations_test.go, pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go, pkg/validations/cluster.go, pkg/validations/cluster_test.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/createvalidations/preflightvalidations_test.go, pkg/validations/skipvalidations.go, pkg/validations/skipvalidations_test.go, pkg/validations/upgradevalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations_test.go, pkg/validations/upgradevalidations/upgradevalidations.go, pkg/validations/validation_options.go
Validations for EKSA Version field
=> Eksaversion validations

docs/content/en/docs/troubleshooting/troubleshooting.md
N/A
Updated troubleshooting guide for "No IP assigned to a VM" to help customers validate if it's a DHCP or EKS-A issue.
N/A
=> Update troubleshooting to include more details on how to trobleshoot IP exhauastion 

docs/content/en/docs/getting-started/baremetal/bare-prereq.md, docs/content/en/docs/getting-started/cloudstack/cloudstack-prereq.md, docs/content/en/docs/getting-started/nutanix/nutanix-prereq.md, docs/content/en/docs/getting-started/vsphere/vsphere-prereq.md
N/A
Add protocol and port to required asset endpoints.
N/A
=> Updated networking requirements to add asset endpoints / ports

internal/test/e2e/cloudstack.go, internal/test/e2e/run.go, test/framework/cloudstack.go
Update Cloudstack E2E to use ipman
=> Update Cloudstack E2E to use IP Manager 🫡

docs/content/en/docs/getting-started/nutanix/nutanix-spec.md
N/A
Add documentation for the the Nutanix additionalCategories feature
N/A
Yes
=> Add documentation for Nutanix additionalCategories feature

docs/content/en/docs/getting-started/optional/hostOSConfig.md
=> Add snow provider to host os config doc

docs/content/en/docs/getting-started/optional/hostOSConfig.md
This reverts commit 5982fb6534b9a75790f0353818ec904d263e9fcd.
=> Revert "Add snow provider to host os config doc (#6273)"

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go
Compare all versions bundle in cluster spec
=> Change compareEKSAClusterSpec

docs/content/en/docs/reference/eksctl/anywhere_create_cluster.md, docs/content/en/docs/reference/eksctl/anywhere_upgrade_cluster.md
Update flags for eksa commands in docs
Added.
=> Update flags for eksa commands in docs

pkg/providers/cloudstack/cloudstack_test.go, pkg/providers/cloudstack/testdata/cluster_main_worker_node_group_kubernetes_version.yaml, pkg/providers/cloudstack/testdata/expected_results_main_cp_kubernetes_version.yaml, pkg/providers/cloudstack/testdata/expected_results_main_md_worker_kubernetes_version.yaml, pkg/providers/cloudstack/validator.go, pkg/providers/cloudstack/validator_test.go
To support modular Kubernetes Version upgrades
=> cloudstack multi machine templates

pkg/cluster/builder.go, pkg/cluster/builder_test.go
=> Fix Airgap EksaVersion

pkg/providers/vsphere/defaults.go, pkg/providers/vsphere/vsphere_test.go
Currently, default templates are only being set in the worker nodes' `vsphereMachineConfig`. This changes it back to set the default templates for all `vsphereMachineConfig`, including the cp and etcd machine configs. 
Confirmed that  `TestVSphereKubernetes124BottlerocketAutoimport` passed locally. 
Manually ran an upgrade with modular Kubernetes Version upgrades with no templates specified to check that the proper templates get set for different node groups.
=> Set default templates for all vsphere machine configs

docs/content/en/docs/getting-started/optional/irsa.md
*Issue #, if available:* NA
1. Added minimum Go version 1.19 that required to run this code.
2. Added trust Policy Working Example for reference
*Testing (if applicable):* IAM Trust Policy tested twice in my AWS account
=> Adding required go version & Trust Policy Example

test/e2e/emissary.go, test/framework/cluster.go, test/framework/testdata/emissary_listener.yaml
Removing/changing tests to use images not from Dockerhub.
=> Fixing emissary tests

docs/content/en/docs/getting-started/baremetal/bare-prereq.md
*Description of changes:* Fix incorrect reference to Supermicro hardware in the docs.
=> Correct reference to Supermicro hardware

test/framework/cloudstack.go
=> Fix typo in Cloudstack e2e

test/framework/cluster.go, test/framework/tinkerbell.go
These variables needs to be added here so they're sent to the EC2 instance running the tests.
=> Add Ubuntu 22.04 images to required env vars

controllers/cluster_controller.go
Install health checks before the packages are reconciled
=> Install health checks before the packages are reconciled

pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go
=> block modular upgrades for tinkerbell

docs/content/en/docs/osmgmt/artifacts.md
https://github.com/aws/eks-anywhere-internal/issues/1604
=> efi image builder doc

docs/content/en/docs/getting-started/optional/cni.md
=> Add docs for egressMasqueradeInterfaces option in Cilium

internal/test/e2e/run.go
Add dynamic hardware reservation logic to be extended to airgapped tinkerbell tests. 
=> Make tinkerbell airgapped tests to dynamically reserve hardware

docs/content/en/docs/getting-started/docker/_index.md, docs/content/en/docs/getting-started/install/_index.md, docs/content/en/docs/osmgmt/artifacts.md
Update image-builder docs to include the recent enhancements:
* OS version configuration.
* Mounting additional files.
=> Update image-builder docs to include latest enhancements

internal/test/vsphere.go, pkg/providers/vsphere/reconciler/reconciler_test.go
Doing some prework to be to write unit tests for kindles upgrades easily. Just splitting this part.
=> Add helpers for vsphere cluster spec for tests

docs/content/en/docs/clustermgmt/cluster-upgrades/vsphere-and-cloudstack-upgrades.md, docs/content/en/docs/clustermgmt/observability/cluster-verify.md, docs/content/en/docs/clustermgmt/storage/_index.md, docs/content/en/docs/clustermgmt/storage/vsphere-storage.md, docs/content/en/docs/getting-started/overview.md, docs/content/en/docs/getting-started/vsphere/vsphere-getstarted.md, docs/content/en/docs/whatsnew/changelog.md
* Add a separate doc for vSphere CSI Driver with upgrade/self-installation instructions.
* Clean up CSI and StorageClass references from docs
=> Add separate vSphere CSI Driver guide

docs/content/en/docs/clustermgmt/cluster-upgrades/airgapped-upgrades.md, docs/content/en/docs/getting-started/airgapped/_index.md, docs/content/en/docs/packages/prereq.md
=> Add doc for managing curated packages in airgapped environment

docs/content/en/docs/osmgmt/artifacts.md, docs/content/en/docs/whatsnew/changelog.md
=> Update changelog for v0.16.3 

docs/content/en/docs/clustermgmt/cluster-upgrades/vsphere-and-cloudstack-upgrades.md
=> Update upgradeable attributes docs to include registryMirrorConfiguration

docs/content/en/docs/getting-started/baremetal/bare-spec.md, docs/content/en/docs/getting-started/cloudstack/cloud-spec.md, docs/content/en/docs/getting-started/nutanix/nutanix-spec.md, docs/content/en/docs/getting-started/snow/snow-spec.md, docs/content/en/docs/getting-started/vsphere/vsphere-spec.md, docs/content/en/docs/troubleshooting/troubleshooting.md
=> Add troubleshoot guide to fix MHC remediation not allowed

docs/content/en/docs/getting-started/baremetal/bare-spec.md
=> Update bare metal osFamily doc to include redhat

docs/content/en/docs/troubleshooting/troubleshooting.md
=> Add etcd NodeHealthy entry to troubleshooting docs

docs/content/en/docs/getting-started/baremetal/bare-spec.md
=> Fix Tinkerbell actions docs

controllers/cluster_controller.go, controllers/cluster_controller_test_test.go, manager/main.go, pkg/controller/clientutil/indexers.go, pkg/controller/clientutil/indexers_test.go, pkg/controller/clusters/management.go, pkg/controller/clusters/validations.go, pkg/controller/clusters/validations_test.go, pkg/providers/tinkerbell/reconciler/reconciler.go, pkg/providers/tinkerbell/reconciler/reconciler_test.go
=> Add ability to list clusters across namespaces for validating management cluster name (#6414)

pkg/controller/clusters/management_test.go, pkg/controller/clusters/validations_test.go
Builds off of https://github.com/aws/eks-anywhere/pull/6414, but just want to add unit tests for the new file we created.
unit testing
=> Add unit tests for management.go

pkg/controller/clusters/management_test.go, pkg/controller/clusters/validations_test.go
=> Add unit tests for management.go (#6441)

internal/pkg/api/vsphere.go, pkg/executables/kubectl.go, pkg/executables/kubectl_test.go, pkg/executables/testdata/kubectl_vspheremachine.json, test/e2e/multi_templates.go, test/e2e/vsphere_test.go, test/framework/multi_template.go, test/framework/multi_template_test.go, test/framework/vsphere.go
https://github.com/aws/eks-anywhere-internal/issues/1603
=> Vsphere multi template e2e

docs/content/en/docs/whatsnew/changelog.md
Update changelog for release v0.16.4
=> Update changelog for v0.16.4

release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.16-bundle-release.yaml
=> Update golden files

docs/content/en/docs/clustermgmt/support/cluster-license.md
=> license cluster doc improvements

docs/content/en/docs/osmgmt/artifacts.md, docs/content/en/docs/whatsnew/changelog.md
=> Update changelog for 0.16.5

docs/content/en/docs/getting-started/baremetal/baremetal-getstarted.md, docs/content/en/docs/getting-started/cloudstack/cloudstack-getstarted.md, docs/content/en/docs/getting-started/nutanix/nutanix-getstarted.md, docs/content/en/docs/getting-started/snow/snow-getstarted.md, docs/content/en/docs/getting-started/vsphere/vsphere-getstarted.md
https://github.com/aws/eks-anywhere-internal/issues/1668
Update optional steps for create cluster on all providers.
- live docs testing + preview
- yes
=> Update optional steps for create cluster on all providers

docs/content/en/docs/clustermgmt/support/supportbundle.md
We re-worded a few things & updated the output examples to the current version.
=> Update support bundle docs

docs/content/en/docs/getting-started/baremetal/bare-prereq.md
NA
Modified validated hardware list
NA
Modified EKS-A BM qualified hardware list
=> Update validated hardware list

docs/content/en/docs/concepts/architecture.md, docs/content/en/docs/getting-started/_index.md, docs/content/en/docs/getting-started/airgapped/_index.md, docs/content/en/docs/getting-started/baremetal/_index.md, docs/content/en/docs/getting-started/baremetal/overview.md, docs/content/en/docs/getting-started/baremetal/tinkerbell-overview.md, docs/content/en/docs/getting-started/cloudstack/_index.md, docs/content/en/docs/getting-started/docker/_index.md, docs/content/en/docs/getting-started/install/_index.md, docs/content/en/docs/getting-started/nutanix/_index.md, docs/content/en/docs/getting-started/nutanix/domains.md, docs/content/en/docs/getting-started/nutanix/nutanix-getstarted.md, docs/content/en/docs/getting-started/nutanix/overview.md, docs/content/en/docs/getting-started/optional/_index.md, docs/content/en/docs/getting-started/overview.md, docs/content/en/docs/getting-started/ports/_index.md, docs/content/en/docs/getting-started/snow/_index.md, docs/content/en/docs/getting-started/snow/snow-getstarted.md, docs/content/en/docs/getting-started/vsphere/_index.md, docs/content/en/docs/getting-started/vsphere/domains.md, docs/content/en/docs/getting-started/vsphere/overview.md, docs/content/en/docs/getting-started/vsphere/vsphere-getstarted.md
Improved the installation overview section based on the docs review
=> Overview review

docs/content/en/docs/osmgmt/artifacts.md, docs/content/en/docs/whatsnew/changelog.md
=> Update changelog for 0.17.0

docs/content/en/docs/osmgmt/artifacts.md, docs/content/en/docs/whatsnew/changelog.md
=> Update 0.17.0 changelog with minor changes

docs/content/en/docs/osmgmt/artifacts.md, docs/content/en/docs/whatsnew/changelog.md
=> 0.17.0 changelog

docs/config.toml, docs/content/en/docs/concepts/support-versions.md
=> Bump up docs site to 0.17.0

docs/content/en/docs/clustermgmt/cluster-flux.md, docs/content/en/docs/clustermgmt/cluster-scale/baremetal-scale.md, docs/content/en/docs/clustermgmt/cluster-status.md, docs/content/en/docs/clustermgmt/cluster-terraform.md, docs/content/en/docs/clustermgmt/cluster-upgrades/baremetal-upgrades.md, docs/content/en/docs/getting-started/baremetal/baremetal-getstarted.md, docs/content/en/docs/getting-started/cloudstack/cloudstack-getstarted.md, docs/content/en/docs/getting-started/snow/snow-getstarted.md, docs/content/en/docs/getting-started/vsphere/vsphere-getstarted.md
=> Add Cluster status docs

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml, config/manifest/eksa-components.yaml, pkg/api/v1alpha1/cluster_types.go, pkg/api/v1alpha1/cluster_webhook.go, pkg/api/v1alpha1/cluster_webhook_test.go, pkg/api/v1alpha1/etcdencryption_test.go, pkg/api/v1alpha1/etcdencryption_types.go, pkg/api/v1alpha1/etcdncryption.go
This PR adds APIs to support ETCD Encryption
=> Add APIs for ETCD Encryption

release/pkg/operations/bundle_release_test.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.17-bundle-release.yaml
=> Generate release testdata files

docs/content/en/docs/clustermgmt/cluster-upgrades/vsphere-and-cloudstack-upgrades.md, docs/content/en/docs/getting-started/cloudstack/cloud-spec.md, docs/content/en/docs/getting-started/nutanix/nutanix-spec.md, docs/content/en/docs/getting-started/snow/snow-spec.md, docs/content/en/docs/getting-started/vsphere/vsphere-spec.md
Documentation for the worker node level kubernetes version
=> Documentation for k8s modular upgrades

CHANGELOG.md, docs/content/en/docs/whatsnew/changelog.md
=> Update changelog to add machine health checks PR

docs/content/en/docs/clustermgmt/observability/fluentbit-logging.md
*Description of changes:* Headings related to some steps for configuring fluentbit observability were incorrect. This PR corrects that.
=> Fix fluentbit steps to use proper heading levels

pkg/api/v1alpha1/cluster_types.go, pkg/clustermanager/cluster_manager_wb_test.go
Add MHC to cluster spec generate
- manual test
NA
=> Add MHC to cluster spec generate

docs/content/en/docs/getting-started/optional/skipvalidations.md
Add docs for skip control plane ip check annotation
Added.
=> Add docs for skip control plane ip check annotation

docs/content/en/docs/getting-started/optional/healthchecks.md
Docs for machine health checks
Added
=> Docs for machine health checks

pkg/providers/vsphere/vsphere_test.go
This test was taking almost 3 minutes because it was using the default provider retrier.
=> Update test retrier to avoid long test

docs/content/en/docs/getting-started/install/_index.md
Updates to admin machine doc from doc review.
Incorporates and adds to changes from this PR:
https://github.com/aws/eks-anywhere/pull/6534/files
=> Admin doc update

pkg/providers/ssh_test.go
=> Fix ssh validation flaky test

docs/content/en/docs/overview/partner/_index.md
*Description of changes:* This PR adds a list of validated EKS Anywhere partners to the docs.
=> Add list of validated partners to docs

config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, config/manifest/eksa-components.yaml, release/api/v1alpha1/bundle_types.go, release/config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, release/pkg/test/testdata/release-0.17-bundle-release.yaml
=> Make credentialProvider field optional

docs/content/en/docs/getting-started/optional/registrymirror.md
=> Update registrymirror doc

docs/content/en/docs/getting-started/install/_index.md
cherry pick of #6536 
Updates to admin machine doc from doc review.
=> Improve the Admin Machine page of our docs

docs/content/en/docs/concepts/support-versions.md
=> Updated supported version docs with bundle and OS information

test/framework/vsphere.go
=> fix typo in vsphere framework

docs/content/en/docs/overview/partner/_index.md
*Issue #, if available:* Updated information on partner conformance based on the latest information.
=> Updated partners list in docs

docs/content/en/docs/concepts/eksafeatures.md
*Issue #, if available:* NA
*Description of changes:* As there is a section for Observability using CloudWatch in EKS Anywhere, correcting the comparison doc where only 3rd party solution is written for monitoring and logging.
*Testing (if applicable):* NA
*Documentation added/planned (if applicable):* Modified
=> modifying the comparison document

docs/content/en/docs/osmgmt/artifacts.md, docs/content/en/docs/whatsnew/changelog.md
=> Update changelog for v0.17.1

docs/content/en/docs/osmgmt/_index.md, docs/content/en/docs/osmgmt/overview.md
Depends on https://github.com/aws/eks-anywhere/pull/6205
=> docs: Add OS Management Overview page

docs/content/en/docs/clustermgmt/networking/networking-and-security.md
=> [Docs] Adding hyperlinks for Isovalent Enterprise Features

pkg/cluster/builder.go
When using verbose logging (verbosity level >= 4), CAPI provider versions will be visible in logs for easier debugging.
=> Add CAPI provider versions to logs

controllers/cluster_controller.go
... during management cluster upgrade due to package reconcile error
E2E test `TestDockerKubernetes126WithOIDCManagementClusterUpgradeFromLatestSideEffects` constantly failing with error:
```sh
2023-09-07T20:58:21.360Z	V0	🎉 Cluster upgraded!
2023-09-07T20:58:21.362Z	V4	Task finished	{"task_name": "delete-kind-cluster", "duration": "3.177917836s"}
2023-09-07T20:58:21.362Z	V4	----------------------------------
2023-09-07T20:58:21.362Z	V4	Tasks completed	{"duration": "18m44.684232162s"}
2023-09-07T20:58:21.364Z	V3	Cleaning up long running container	{"name": "eksa_1694119167170291469"}
side_effects.go:150: Checking for changes in machines for 10m0s
side_effects.go:155: Reading CAPI machines for cluster main-i-067a6-ccc8a7c-w-0
side_effects.go:52: The new controller …
```
=> Fix side effect of unnecessary workload cluster machine rollout 

go.mod, pkg/api/v1alpha1/cloudstackmachineconfig.go, pkg/api/v1alpha1/cloudstackmachineconfig_test.go, pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/api/v1alpha1/nutanixmachineconfig.go, pkg/api/v1alpha1/nutanixmachineconfig_test.go, pkg/api/v1alpha1/testdata/invalid_manifest.yaml, pkg/api/v1alpha1/testdata/tinkerbell_cluster_with_duplicate_mchine_config_fields.yaml, pkg/api/v1alpha1/tinkerbellmachineconfig.go, pkg/api/v1alpha1/tinkerbellmachineconfig_test.go, pkg/api/v1alpha1/vspheremachineconfig.go, pkg/api/v1alpha1/vspheremachineconfig_test.go, pkg/utils/file/reader.go, pkg/utils/yaml/yaml.go, pkg/utils/yaml/yaml_test.go
=> Backport #6170

release/pkg/assets/archives/archives.go, release/pkg/assets/archives/archives_test.go, release/pkg/assets/config/bundle_release.go, release/pkg/assets/types/types.go, release/pkg/operations/bundle_release_test.go, release/pkg/test/testdata/main-bundle-release.yaml, release/pkg/test/testdata/release-0.17-bundle-release.yaml
Backporting #6703 to release-0.17 and updating golden files.
=> [release-0.17] Source Bottlerocket artifacts from new upload location

docs/content/en/docs/reference/eksctl/anywhere_create_cluster.md, docs/content/en/docs/reference/eksctl/anywhere_generate.md, docs/content/en/docs/reference/eksctl/anywhere_generate_tinkerbelltemplateconfig.md, docs/content/en/docs/reference/eksctl/anywhere_upgrade_cluster.md
=> Update CLI doc with make docgen

docs/content/en/docs/clustermgmt/cluster-upgrades/airgapped-upgrades.md, docs/content/en/docs/getting-started/airgapped/_index.md, docs/content/en/docs/getting-started/airgapped/airgap-packages.md, docs/content/en/docs/getting-started/airgapped/airgap-steps.md, docs/content/en/docs/getting-started/baremetal/bare-prereq.md, docs/content/en/docs/getting-started/chooseprovider/_index.md, docs/content/en/docs/getting-started/install/_index.md, docs/content/en/docs/getting-started/optional/registrymirror.md, docs/content/en/docs/packages/prereq.md
*Description of changes:* This is a cherry pick of [PR 6672](https://github.com/aws/eks-anywhere/pull/6672) (Clean up airgapped docs).
=> Cherry-pick of PR6672

internal/pkg/api/nutanix.go
https://github.com/aws/eks-anywhere/security/code-scanning/5
Correct conversion between integer types
=> Correct conversion between integer types

internal/pkg/oidc/server.go
https://github.com/aws/eks-anywhere/security/code-scanning/3
=> Fix minimum bits code scanner error

docs/content/en/docs/whatsnew/changelog.md
Changelog for patch release v0.17.3
=> Changelog for patch release v0.17.3

docs/content/en/docs/whatsnew/changelog.md
Update Bottlerocket version in changelog and add v0.17.3 section.
=> Update Bottlerocket version in changelog

test/e2e/docker_test.go
=> Docker 1.28 E2E

test/e2e/docker_test.go
=> Fix Typos in Docker E2E

test/e2e/cloudstack_test.go
=> Add 1.28 CloudStack E2E

docs/content/en/docs/concepts/support-versions.md
=> Clarify EKS-A version support for enterprise customer

test/e2e/tinkerbell_test.go
=> Use Correct Template in Tinkerbell E2E

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml, go.mod, go.sum, internal/pkg/api/cluster.go, internal/pkg/oidc/keys.go, internal/pkg/oidc/server.go, internal/pkg/oidc/token.go, internal/test/e2e/etcdEncryption.go, internal/test/e2e/setup.go, pkg/api/v1alpha1/cluster_types.go, test/e2e/cloudstack_test.go, test/framework/config/aws-kms-encryption-provider.yaml, test/framework/config/pod-identity-webhook.yaml, test/framework/curatedpackages.go, test/framework/etcdencryption.go
=> Add E2E for Cloudstack Etcd Encryption

docs/content/en/docs/getting-started/baremetal/baremetal-getstarted.md
=> Baremetal Get Started Doc

docs/content/en/docs/getting-started/vsphere/vsphere-spec.md
Updated the vsphere configurations docs
- We opted to remove the "Provider specific values are in red" key because it wasn't clear enough and seemed redundant in some cases
- Added some links and more information to some fields.
=> Update vsphere configurations doc

docs/content/en/docs/whatsnew/changelog.md
=> Add changelog for release v0.17.4

test/e2e/cloudstack_test.go, test/e2e/conformance_test.go
=> Remove 1.23 E2E

test/e2e/cloudstack_test.go
=> Bump E2E tests that used 1.23

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go, pkg/features/features.go, pkg/features/features_test.go, pkg/validations/cluster.go, pkg/validations/cluster_test.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations.go, test/framework/cluster.go
=> Remove 1.28 feature flag and set it as default version

docs/content/en/docs/getting-started/baremetal/bare-spec.md
=> Bare Metal config page fix

pkg/clustermanager/applier.go, pkg/workflows/management/gitops.go, pkg/workflows/management/install_new_components.go, pkg/workflows/management/upgrade_cluster.go
Small fixes:
1. Suggested in [#6622](https://github.com/aws/eks-anywhere/pull/6622#discussion_r1326460262) PR. 
2. Suggested in [#6781](https://github.com/aws/eks-anywhere/pull/6781#discussion_r1348666852) PR.
=> Management cluster kindless upgrade fixes

OWNERS
=> add sp1999 to OWNERS

docs/content/en/docs/concepts/support-versions.md, docs/content/en/docs/getting-started/baremetal/bare-spec.md, docs/content/en/docs/getting-started/cloudstack/cloud-spec.md, docs/content/en/docs/getting-started/cloudstack/cloudstack-getstarted.md, docs/content/en/docs/getting-started/cloudstack/cloudstack-preparation.md, docs/content/en/docs/getting-started/docker/_index.md, docs/content/en/docs/getting-started/nutanix/nutanix-getstarted.md, docs/content/en/docs/getting-started/nutanix/nutanix-spec.md, docs/content/en/docs/getting-started/snow/snow-spec.md, docs/content/en/docs/getting-started/vsphere/vsphere-getstarted.md, docs/content/en/docs/getting-started/vsphere/vsphere-spec.md, docs/content/en/docs/osmgmt/artifacts.md, docs/content/en/docs/reference/eksctl/anywhere_list_packages.md
=> Add docs to mention 1.28 support

pkg/curatedpackages/packagecontrollerclient_test.go, pkg/curatedpackages/regional_registry.go
=> Add regional ECR map

docs/content/en/docs/osmgmt/overview.md
Update supported OS versions table.
=> Update supported OS versions table

.github/workflows/vulnerability.yml
=> Fix dependency-review for commits in main

docs/content/en/docs/getting-started/nutanix/nutanix-spec.md
=> Update Nutanix docs to mention RHEL support

docs/content/en/docs/getting-started/optional/etcdencryption.md, docs/layouts/shortcodes/details.html
=> Add etcd encryption docs

docs/content/en/docs/whatsnew/changelog.md
=> Add more info about kindless in the changelog

docs/content/en/docs/osmgmt/artifacts.md
* Update supported EKS-D release channels in image-builder docs
* Update latest EKS-A version
=> Update supported EKS-D release channels in image-builder docs

docs/config.toml
=> bump docs site to 0.18

docs/content/en/docs/osmgmt/artifacts.md
Clarify image download prerequisite step for building Nutanix OS images.
=> Improve Nutanix image-builder docs

scripts/brew_formula_update.sh, scripts/eks-anywhere.rb.tmpl
We support ARM CPUs so we should update our brew formula to reflect that. 
=> Update Brew Formula Update

docs/content/en/docs/osmgmt/artifacts.md
Doc changes for proxy as well as RedHat Satellite support on image-builder
=> Image builder docs for Proxy and RedHat Satellite support

docs/content/en/docs/clustermgmt/cluster-backup-restore/_index.md, docs/content/en/docs/clustermgmt/cluster-backup-restore/backup-cluster.md, docs/content/en/docs/clustermgmt/cluster-backup-restore/restore-cluster.md, docs/content/en/docs/clustermgmt/etcd-backup-restore/etcdbackup.md
=> Add instruction of management cluster backup and restore

docs/developer/CHANGELOG_TEMPLATE.md
This changelog template will be used for all future releases. Its designed to emphasize the the most important things to the user first and broken down so its easy to digest.
=> Add changelog template

docs/content/en/docs/clustermgmt/cluster-backup-restore/restore-cluster.md
=> Fix restore doc typo

config/crd/bases/anywhere.eks.amazonaws.com_cloudstackmachineconfigs.yaml, config/crd/bases/anywhere.eks.amazonaws.com_nutanixmachineconfigs.yaml, config/crd/bases/anywhere.eks.amazonaws.com_tinkerbelldatacenterconfigs.yaml, config/crd/bases/anywhere.eks.amazonaws.com_tinkerbellmachineconfigs.yaml, config/crd/bases/anywhere.eks.amazonaws.com_vspheremachineconfigs.yaml, docs/content/en/docs/clustermgmt/cluster-upgrades/baremetal-upgrades.md, docs/content/en/docs/clustermgmt/cluster-upgrades/vsphere-and-cloudstack-upgrades.md, docs/content/en/docs/getting-started/baremetal/bare-spec.md, docs/content/en/docs/getting-started/cloudstack/cloud-spec.md, docs/content/en/docs/getting-started/nutanix/nutanix-spec.md, docs/content/en/docs/getting-started/vsphere/vsphere-spec.md, docs/content/en/docs/troubleshooting/troubleshooting.md, pkg/api/v1alpha1/cloudstackmachineconfig_types.go, pkg/api/v1alpha1/nutanixmachineconfig_types.go, pkg/api/v1alpha1/tinkerbelldatacenterconfig_types.go, pkg/api/v1alpha1/tinkerbellmachineconfig_types.go, pkg/api/v1alpha1/vspheremachineconfig_types.go
Update docs about the changes that went in for the kindless upgrade task.
=> Update docs about changes that went in for kindless upgrade task

docs/content/en/docs/overview/partner/_index.md
*Description of changes:* Updated partners information based on the latest testing and partner lists.
=> Updated partner docs

cmd/integration_test/build/buildspecs/docker-test-eks-a-cli.yml, internal/test/e2e/packages.go, pkg/executables/kubectl.go, test/e2e/docker_test.go
*Description of changes:* Adding regional curated packages e2e test 
*Testing (if applicable):* Manually invoked the new e2e test, and the test passed.
=> Add docker regional curated packages e2e test

internal/test/e2e/run.go
=> Run larger tests for tinkerbell first for e2e runs

docs/content/en/docs/clustermgmt/cluster-backup-restore/restore-cluster.md
=> Update management cluster restore doc to always apply eks-a spec

docs/developer/CHANGELOG_TEMPLATE.md
Adds stronger guidance for compiling a changelog.
=> Update notes for CHANGELOG template

docs/content/en/docs/whatsnew/changelog.md
=> Add proxy and redhat satellite support in 0.18.0 changelog

docs/content/en/docs/packages/troubleshoot.md
=> Use kubectl instead of k in docs

pkg/files/reader_test.go, pkg/providers/cloudstack/reconciler/reconciler_test.go, pkg/providers/docker/reconciler/reconciler_test.go, pkg/providers/snow/reconciler/reconciler_test.go, pkg/providers/tinkerbell/reconciler/reconciler_test.go, pkg/providers/vsphere/reconciler/reconciler_test.go
We have a number of flaky tests. This skips the known flaky tests from the last 2 weeks. Each skip has an associated issue.
=> Skip flaky tests

cmd/integration_test/build/buildspecs/snow-test-eks-a-cli.yml
=> Run one snow e2e test case for each admin machine

docs/content/en/docs/getting-started/vsphere/vsphere-preparation.md
=> Update vSphere preparation content

docs/content/en/docs/whatsnew/changelog.md
=> 0.17.5 Changelog

docs/content/en/docs/osmgmt/artifacts.md
Docs for air-gapped image building.
=> Air-gapped image building docs

docs/content/en/docs/whatsnew/changelog.md
=> v0.17.5 Changelog

release/Makefile, release/cli/pkg/test/testdata/main-bundle-release.yaml
=> Fix release test golden files update target

config/manifest/eksa-components.yaml, config/rbac/role.yaml, controllers/controlplaneupgrade_controller.go, controllers/factory.go, controllers/machinedeploymentupgrade_controller.go, controllers/nodeupgrade_controller.go, manager/main.go, pkg/api/v1alpha1/controlplaneupgrade_types.go, pkg/api/v1alpha1/machinedeploymentupgrade_types.go, pkg/api/v1alpha1/nodeupgrade_types.go
=> Add in-place controllers to EKS-A manager

docs/content/en/docs/clustermgmt/cluster-rebootnode.md
https://github.com/aws/eks-anywhere-internal/issues/1528
Update cluster reboot docs to highlight the best practices when rebooting nodes
=> Update cluster reboot nodes doc

pkg/features/features.go, pkg/features/features_test.go
Add feature flag for unify controller CLI workflow.
- unit test
=> Add feature flag for unify controller CLI workflow

docs/content/en/docs/troubleshooting/troubleshooting.md
*Issue #, if available:* [Issue #5866](https://github.com/aws/eks-anywhere/issues/5866)
*Description of changes:* Added links to knowledge center troubleshooting articles from the EKS Anywhere troubleshooting docs.
=> Add links to knowledge center troubleshooting articles

docs/content/en/docs/getting-started/optional/irsa.md
- Restructure contents
- Fix broken link
=> Small fix on IRSA doc

docs/content/en/docs/whatsnew/changelog.md
=> Changelog for v0.18.3

docs/content/en/docs/getting-started/docker/_index.md, docs/content/en/docs/getting-started/install/_index.md
=> fix minimum Docker version

docs/content/en/docs/troubleshooting/troubleshooting.md
=> Add docker cluster pod errors due to too many open files

docs/content/en/docs/whatsnew/changelog.md
=> v0.17.6 changelog

docs/content/en/docs/clustermgmt/cluster-scale/cloudstack-scale.md, docs/content/en/docs/clustermgmt/cluster-scale/nutanix-scale.md, docs/content/en/docs/clustermgmt/cluster-scale/vsphere-scale.md, docs/content/en/docs/clustermgmt/cluster-upgrades/vsphere-and-cloudstack-upgrades.md
=> Add cluster full lifecycle support in upgrade docs

test/kube-bench/README.md
=> Update README to remove note

release/cli/cmd/release.go
Currently, the latest version in the EKS-A releases manifest is updated for every new production release, i.e., the version gets updated in a chronological order. This means that, because EKS-A version `v0.17.6` was released after `v0.18.3`, the latest version in the production manifest becomes `v0.17.6`. This deviates from the true meaning of "latest" because in the technical sense, v0.18.3 is a later mminor release. This PR fixes the assignment of latest version by comparing the semvers of the previous latest version and the version currently being released and updates the latest only if the current version is greater than the previous.
=> Update latest version only if semver is greater than previous latest

README.md
Bare Metal was missing from the introduction verbiage
added a blurb that indicates Bare Metal is a deployment option.
N/A
N/A - updated existing 
=> Updated to reflect that Bare Metal is an option

docs/content/en/docs/workloadmgmt/gpu-create-cluster-output.md, docs/content/en/docs/workloadmgmt/gpu-sample-cluster.md, docs/content/en/docs/workloadmgmt/using-gpus.md
=> add doc page for using GPUs with EKS-A

pkg/workflows/management/create.go, pkg/workflows/management/create_test.go, pkg/workflows/management/upgrade.go, pkg/workflows/management/upgrade_management_components_test.go, pkg/workflows/management/validate.go
Create management cluster using controller behind feature flag.
The original [PR](https://github.com/aws/eks-anywhere/pull/7110) is being split into smaller PRs. This PR is the first one.
- The whole workflow has been tested end to end for Docker, vSphere, and Cloudstack providers.
- Unit tests
=> Create management cluster using controller validation task

docs/content/en/docs/whatsnew/changelog.md
=> Update changelog to follow latest template

test/e2e/cloudstack_test.go
Fixed capitalization of cloudstack etcd scaling e2es
=> Fix cloudstack etcd scaling test names

test/e2e/nutanix_test.go
Resolve nutanix e2e test for management cluster API upgrade.
=> Resolve nutanix e2e test for management cluster API upgrade

pkg/workflows/workload/upgrade_test.go, pkg/workflows/workload/validate.go
=> Fix bug in provider validations for workload

docs/content/en/docs/troubleshooting/troubleshooting.md
Add troubleshooting section for labeling nodes with reserved labels
=> Add troubleshooting section for labeling nodes with reserved labels

config/manifest/eksa-components.yaml, config/rbac/role.yaml, controllers/factory.go, controllers/factory_test.go, controllers/kubeadmcontrolplane_controller.go, controllers/kubeadmcontrolplane_controller_test.go, controllers/machinedeployment_controller.go, controllers/machinedeployment_controller_test.go, controllers/machinedeploymentupgrade_controller_test.go, manager/main.go, pkg/constants/constants.go
Similar to https://github.com/aws/eks-anywhere/pull/7361, except for md. Also made some minor annotation and error string changes to kcp controller.
unit and functional testing
=> Add in-place upgrade controller for md

docs/content/en/docs/whatsnew/changelog.md
Update changelog for v0.18.5 release.
=> Update changelog for v0.18.5

config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml, config/manifest/eksa-components.yaml, release/api/v1alpha1/bundle_types.go, release/api/v1alpha1/zz_generated.deepcopy.go, release/cli/pkg/assets/config/bundle_release.go, release/cli/pkg/bundles/nutanix.go, release/cli/pkg/test/testdata/main-bundle-release.yaml, release/config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml
Add Nutanix Cloud Provider project to bundle
```
$ make dev-release
...
gitTag: v0.0.0-dev+build.0
number: 1
version: v0.0.0-dev+build.0
✅ Successfully completed dry-run of release process
```
=> Add Nutanix Cloud Provider project to bundle

docs/config.toml, docs/content/en/docs/concepts/support-versions.md, docs/content/en/docs/getting-started/baremetal/bare-spec.md, docs/content/en/docs/getting-started/vsphere/vsphere-spec.md, docs/data/version_support.yml, docs/layouts/shortcodes/eksa_support.html, docs/layouts/shortcodes/kube_support.html
Refactor the EKS-A and Kubernetes versioning information into a data separate data file.
=> Refactor versioning docs page

cmd/eksctl-anywhere/cmd/createcluster.go, cmd/eksctl-anywhere/cmd/upgradecluster.go
=> Enable controller workflow for workload on main

cmd/integration_test/build/buildspecs/build-eks-a-cli.yml
=> Enable cache for building cli and test binaries

pkg/workflows/management/create_install_resources.go, pkg/workflows/management/create_test.go, pkg/workflows/management/create_workload.go
Install management resources task for controller via CLI
unit tests
NA
=> Install management resources task for controller via CLI

pkg/workflows/management/create_install_resources.go, pkg/workflows/management/create_move_capi.go, pkg/workflows/management/create_test.go
Move CAPI resources task using controller behind feature flag
- unit test
=> Move CAPI resources task using controller behind feature flag

pkg/workflows/management/create_install_eksa.go, pkg/workflows/management/create_move_capi.go, pkg/workflows/management/create_test.go
Install EKSA components on workload task for controller via CLI
- unit tests
=> Install EKSA components on workload task for controller via CLI

internal/aws-sdk-go-v2/internal/auth/scheme_test.go, internal/aws-sdk-go-v2/internal/configsources/config.go, internal/aws-sdk-go-v2/internal/endpoints/awsrulesfn/arn_test.go, internal/aws-sdk-go-v2/internal/endpoints/awsrulesfn/partition_test.go, internal/aws-sdk-go-v2/internal/endpoints/endpoints_test.go, internal/aws-sdk-go-v2/internal/endpoints/v2/endpoints.go, internal/aws-sdk-go-v2/internal/endpoints/v2/package_test.go, test/e2e/docker_test.go
=> Fix gofumpt formatting

OWNERS
=> Remove Raymond from OWNERS

pkg/workflows/management/create_gitops.go, pkg/workflows/management/create_install_eksa.go, pkg/workflows/management/create_test.go
Add Gitops installation task for using controller via CLI
- unit test
=> Add Gitops installation task for using controller via CLI

pkg/workflows/management/create_gitops.go, pkg/workflows/management/create_test.go, pkg/workflows/management/gitops.go, pkg/workflows/management/write_cluster_config.go
Write cluster config task
- unit test
=> Write cluster config task

pkg/workflows/management/create_install_eksa.go
=> Add managed by CLI annotation

controllers/machinedeployment_controller.go
MDUpgrade objects need the machinespec data which is a base64 encoded copy of `md.Spec.Template.Spec` to update the machinesets with the latest machine spec once inplace upgrade is completed. This enables machineset controllers to sync with the latest state of the machine and preventing any machine roll over. This change populates the machinespec data on to the mdUpgrade object from the machine deployment. 
=> Populate machine spec data in from md to mdUpgrade object

pkg/clustermanager/deleter.go, pkg/clustermanager/deleter_test.go, pkg/dependencies/factory.go, pkg/dependencies/factory_test.go
=> Add Cluster Deleter

pkg/clustermanager/eksa_installer.go, pkg/clustermanager/eksa_installer_test.go
https://github.com/orgs/aws/projects/162?pane=issue&itemId=51431629
Updates the config map with the new upgrader images after EKSA Installer applies a new Bundles object to the cluster in order to support in-place upgrades.
=> Update Upgrader Images in EKSA Installer

pkg/workflows/management/create_curated_packages.go, pkg/workflows/management/create_delete_bootstrap.go, pkg/workflows/management/create_test.go
Enable curated packages installation for controller via CLI
=> Enable curated packages installation for controller via CLI

pkg/workflows/management/create_move_capi.go, pkg/workflows/management/create_test.go
https://github.com/orgs/aws/projects/162/views/1?pane=issue&itemId=46253068
=> Pause reconcile before moving CAPI

cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
=> Add one vsphere quick test

docs/content/en/docs/whatsnew/changelog.md
Updating changelog for v0.18.6.
=> Update changelog for v0.18.6

cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
=> Remove redundant platforms build

cmd/eksctl-anywhere/cmd/createcluster.go
Enable management cluster create behind feature flag
- docker e2e test
=> Enable management cluster create behind feature flag

cmd/eksctl-anywhere/cmd/createcluster.go, pkg/workflows/management/create.go, pkg/workflows/management/create_install_eksa.go, pkg/workflows/management/create_test.go, pkg/workflows/management/create_workload.go
Remove client factory dependency
=> Remove client factory dependency

pkg/diagnostics/collectors.go
Add in-place upgrade CRDs to diagnostic bundle collector so logs can be fetched for them.
=> Add in-place CRDs to diagnostics collector

Makefile, cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
=> Build EKS-A with pinned version for quick e2e tests

pkg/providers/nutanix/provider.go, pkg/providers/nutanix/provider_test.go
Fix nutanix create mgmt new workflow
- unit test
- manual test
=> Fix nutanix create mgmt new workflow

Makefile
This guarantees the right version is set at the beginning, no matter the target and the binary to be built. It avoids situations where different binaries generated from the same make command are built with different versions.
=> Set eks-a version globally in the Makefile

test/framework/release_versions.go
This guarantees that the CLI and the tests are always reading the dev release manifest from the same place.
=> Read release manifest from CLI manifest URL

pkg/clustermanager/cluster_manager.go, pkg/clustermanager/cluster_manager_test.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go, pkg/workflows/management/create_bootstrap.go, pkg/workflows/management/create_test.go, pkg/workflows/management/secrets.go
=> Fix registry secret

pkg/workflows/management/create_gitops.go, pkg/workflows/management/create_test.go, pkg/workflows/management/secrets.go
Continue create workflow post gitops failure
=> Continue create workflow post gitops failure

cmd/eksctl-anywhere/cmd/deletecluster.go, pkg/workflows/workload/delete.go, pkg/workflows/workload/delete_test.go, pkg/workflows/workload/deletecluster.go, pkg/workflows/workload/post_delete.go
=> Delete gitops workload cluster with controller

docs/content/en/docs/osmgmt/overview.md, docs/content/en/docs/whatsnew/changelog.md
=> Update OS versions in docs

release/cli/pkg/aws/s3/s3.go, release/cli/pkg/util/release/release.go
This avoid race conditions where a release process reads an outdated version of the manifest from a stale cloudfront cache and overwrites the changes made by a previous release process.
=> Read current release state directly from S3

pkg/providers/nutanix/provider.go
Update cluster spec with nutanix machine configs
- manual e2e test
=> Update cluster spec with nutanix machine configs

pkg/providers/tinkerbell/create.go
Update cluster spec with tinkerbell machine configs
- manual e2e
=> Update cluster spec with tinkerbell machine configs

controllers/kubeadmcontrolplane_controller.go, controllers/kubeadmcontrolplane_controller_test.go, controllers/machinedeployment_controller.go, controllers/machinedeployment_controller_test.go
Nodes will be down temporarily during inplace upgrades. We don't want CAPI to rollout new nodes because of this, so we will pause machine health checks during inplace upgrades by adding the `cluster.x-k8s.io/paused` annotation
unit tests
=> Pause machine health checks during inplace upgrades

pkg/awsiamauth/client.go, pkg/awsiamauth/client_test.go, pkg/awsiamauth/installer.go, pkg/awsiamauth/installer_test.go, pkg/awsiamauth/mock_test.go, pkg/clustermanager/cluster_manager.go, pkg/clustermanager/mocks/client_and_networking.go, pkg/workflows/interfaces/interfaces.go, pkg/workflows/interfaces/mocks/clients.go, pkg/workflows/management/create_test.go, pkg/workflows/management/create_workload.go
=> Write AWS IAM kubeconfig file

cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml
Fix indentation issue caused by #7586.
=> Fix indentation in VSphere E2E test buildspec

pkg/workflows/workload/create_test.go, pkg/workflows/workload/writeclusterconfig.go
Unit tests for aws iam kubeconfig write file
=> Unit tests for aws iam kubeconfig write file

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go
We should clarify that this is the case only for stacked etcd topology.
=> Clarify control plane node count error log

cmd/eksctl-anywhere/cmd/upgrademanagementcomponents.go
=> Fix a bug that bundlesOveride was not used

pkg/providers/snow/snow.go, pkg/providers/snow/snow_test.go
Update secrets for snow
- unit test
=> Update secrets for snow

test/e2e/SKIPPED_TESTS.yaml
=> Disable MultiEndpoint CloudStack Tests

test/e2e/SKIPPED_TESTS.yaml
Refer to #7617 for the reason.
=> Skip 1.29 OIDC side effects upgrade test for CloudStack

pkg/workflows/management/delete_install_eksa.go, pkg/workflows/management/delete_test.go
=> Fix delete workflow for different namespaces

pkg/workflows/management/create_install_eksa.go, pkg/workflows/management/create_test.go, pkg/workflows/workload/createcluster.go
Log the cluster spec while cluster creation
=> Log the cluster spec while cluster creation

test/e2e/QUICK_TESTS.yaml, test/e2e/SKIPPED_TESTS.yaml
=> Skip snow e2e tests

docs/content/en/docs/whatsnew/changelog.md
=> Changelog for v0.18.7

cmd/eksctl-anywhere/cmd/constants.go, cmd/eksctl-anywhere/cmd/options.go, pkg/api/v1alpha1/tinkerbelldatacenterconfig_webhook_test.go, pkg/dependencies/factory.go
Remove support for machine health check flags
=> Remove support for machine health check flags

cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
=> Add cleanups to quick E2E pipeline

docs/content/en/docs/clustermgmt/etcd-backup-restore/bottlerocket-etcd-backup.md, docs/content/en/docs/clustermgmt/etcd-backup-restore/etcdbackup.md, docs/content/en/docs/clustermgmt/etcd-backup-restore/ubuntu-rhel-etcd-backup.md, docs/content/en/docs/getting-started/nutanix/nutanix-spec.md, docs/content/en/docs/getting-started/optional/etcd.md
N/A
Adding Nutanix as supported platform for unstacked etcd topology 
N/A
Adding Nutanix as supported platform for unstacked etcd topology. 
=> Update Nutanix provider support details for unstacked etcd topology

docs/developer/CHANGELOG_TEMPLATE.md
Update the BR version in the template
=> Update changelog template

test/e2e/SKIPPED_TESTS.yaml
Unskipping cilium policy enforcement tests
=> Unskip cilium policy enforcement tests

pkg/providers/cloudstack/config/template-cp.yaml, pkg/providers/cloudstack/testdata/expected_results_encryption_config_cp_1_29.yaml, pkg/providers/snow/apibuilder.go, pkg/providers/snow/apibuilder_test.go, pkg/providers/snow/etcd.go, pkg/providers/tinkerbell/config/template-cp.yaml, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/testdata/expected_results_ubuntu_etcd_encryption_cp_1_29.yaml
This reverts commit 97053a9cdfeb82d0d7b9cbeaa10fc0964439a976.
=> Revert "[release-0.19] Disable ETCD Learner Mode (#7719)"

pkg/providers/cloudstack/config/template-cp.yaml, pkg/providers/cloudstack/testdata/expected_results_encryption_config_cp_1_29.yaml, pkg/providers/snow/apibuilder.go, pkg/providers/snow/apibuilder_test.go, pkg/providers/snow/etcd.go, pkg/providers/tinkerbell/config/template-cp.yaml, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/testdata/expected_results_ubuntu_etcd_encryption_cp_1_29.yaml
=> Revert "Revert "[release-0.19] Disable ETCD Learner Mode (#7719)""

docs/content/en/docs/clustermgmt/cluster-upgrades/baremetal-upgrades.md, docs/content/en/docs/clustermgmt/cluster-upgrades/vsphere-and-cloudstack-upgrades.md
=> Baremetal upgrade doc change

designs/in-place-upgrades-eksa.md
This PR aims to update the in-place upgrade design doc to reflect the changes in the current design.
Here are some of the main changes in the designs that we made and their justification:
- Relying on annotations on `KCP` and `MD` objects instead of CAPI runtime extensions to trigger in-place upgrades
- This was changed because the runtime extensions needed for this feature aren't defined in upstream CAPI yet but it will be added when in-place is officially supported upstream. Until then we would have to maintain a patch in our CAPI to add these runtime extensions which may or may not match what upstream CAPI would have. 
Therefore the initial investment in adding runtime extensions doesn't seem justified considering we can achieve similar functionality by using …
=> Update in-place upgrade design

release/cli/pkg/images/images.go, release/cli/pkg/operations/bundle_release.go, release/cli/pkg/operations/eksa_release.go, release/cli/pkg/operations/upload.go, release/cli/pkg/test/testdata/main-bundle-release.yaml
Cherrypicking #7741 and #7744 to `main`.
=> Fix signature digests computation and isolate packages processing to bundle release

docs/content/en/docs/concepts/support-versions.md, docs/content/en/docs/whatsnew/changelog.md, docs/data/version_support.yml
Adding changelog for EKS-A v0.19.0 release.
=> Update changelog for v0.19.0 release

pkg/providers/cloudstack/reconciler/reconciler_test.go
https://github.com/aws/eks-anywhere-internal/issues/2193
We have skipped a few unit tests which were failing randomly on a PR as a part of eks-anywhere-e2e-presubmit job. Un-skipping a few of those unit tests for CloudStack provider to make sure it doesn't fail.
=> Un-skipping randomly failing unit test for cloudstack provider

pkg/providers/cloudstack/config/template-cp.yaml, pkg/providers/cloudstack/testdata/expected_results_encryption_config_cp_1_29.yaml, pkg/providers/snow/apibuilder.go, pkg/providers/snow/apibuilder_test.go, pkg/providers/snow/etcd.go, pkg/providers/tinkerbell/config/template-cp.yaml, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/testdata/expected_results_ubuntu_etcd_encryption_cp_1_29.yaml
=> Revert "[main] Revert "Disable ETCD Learner Mode (#7719)""

docs/content/en/docs/osmgmt/artifacts.md
Add separate documentation for image-builder vSphere options, pointing to upstream documentation for more info.
=> Add documentation for image-builder vSphere options

docs/content/en/docs/getting-started/_configuration/cluster_clusterNetwork.html
=> hide cluster network config from side nav

docs/content/en/docs/osmgmt/overview.md
Align OS table with systems supported by Nutanix. 
*Testing (if applicable):* N/A
Align OS table to align systems supported by Nutanix.
=> Docs: Align OS table with systems supported by Nutanix

internal/test/e2e/run.go
This improves the concurrent code a little bit to handle results as they come, as opposed to wait until all tests are done before printing any results. This helps keeping track of the e2e test run progress since the logs indicate how many instances have finished and the total of instances.
I ran this in a pipeline manually, all good.
=> Log E2E test results as soon as they finish

docs/content/en/docs/whatsnew/changelog.md
Adding changelog for v0.19.1 patch release
=> Adding changelog for v0.19.1 patch release

cmd/eksctl-anywhere/cmd/generateclusterconfig.go, pkg/constants/constants.go
=> Update CLI generate clusterconfig description for provider flag

internal/pkg/api/cluster.go, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/config/template-md.yaml, pkg/providers/vsphere/template.go, pkg/providers/vsphere/testdata/cluster_bottlerocket_mirror_config_multiple_ocinamespaces.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_multiple_ocinamespaces_cp.yaml, pkg/providers/vsphere/testdata/expected_results_bottlerocket_mirror_config_multiple_ocinamespaces_md.yaml, pkg/providers/vsphere/vsphere_test.go, pkg/validations/cluster.go, pkg/validations/cluster_test.go, test/e2e/vsphere_test.go, test/framework/registry_mirror.go
*Issue #6418*
The PR includes the changes needed on EKS-A for enabling multiple registry mirrors to be setup for Bottlerocket OS. These consume the new API from CAPI patch https://github.com/aws/eks-anywhere-build-tooling/pull/2970.
Prior to these changes, only `public.ecr.aws` mirroring was supported for OS family bottlerocket. Now users  can specify more than one OCINamespace value and those registries would get mirrored on bottlerocket, through the bottlerocket settings.
For existing users who already have an EKS-A cluster with `public.ecr.aws` as an OCINamespace or have a `registryMirrorConfiguration` with no `ociNamespaces`; would not see changes in their CAPI API specs.
If a user wants to update their `ociNamespaces` by adding a new registry or if a user …
=> Adding support for mutliple oci namespaces in BR OS vSphere

release/cli/go.mod, release/cli/go.sum
Update Go modules in release/cli.
=> Update Go modules in release/cli

docs/content/en/docs/whatsnew/changelog.md
=> Changelog for v0.19.2

docs/content/en/docs/clustermgmt/etcd-backup-restore/ubuntu-rhel-etcd-backup.md
Updated etcd back-restore commands to include: 
- Default user for each supported provider 
- su command
=>  Added default user for each provider in the etcd backup restore commands 

scripts/golden_create_pr.sh
Fix release testdata update script to point to the correct folder.
=> Fix release testdata update script

cmd/eks-a-tool/cmd/nutanixrmvms.go, cmd/integration_test/build/buildspecs/nutanix-test-eks-a-cli.yml, cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml, cmd/integration_test/cmd/cleanupnutanix.go, internal/test/cleanup/cleanup.go, test/framework/nutanix.go
Nutanix ensure VMs cleaned up before and after tests
=> Nutanix ensure VMs cleaned up before and after tests

cmd/integration_test/build/buildspecs/nutanix-test-eks-a-cli.yml
=> Fix nutanix cleanup in e2e

pkg/api/v1alpha1/cluster_types.go, pkg/features/features.go, pkg/features/features_test.go, pkg/validations/cluster.go, pkg/validations/cluster_test.go, pkg/validations/createvalidations/preflightvalidations.go, pkg/validations/upgradevalidations/preflightvalidations.go, test/framework/cluster.go
Feature Gate Kubernetes version 1.30
=> Add K8s version 1.30 feature flag

docs/content/en/docs/whatsnew/changelog.md
=> Add 0.19.3 change

docs/content/en/docs/getting-started/baremetal/tinkerbell-overview.md
=> Fix typo in tinkerbell-overview.md

pkg/cluster/spec_test.go
=> Remove unused code

config/manifest/eksa-components.yaml, config/rbac/role.yaml, controllers/cluster_controller.go, controllers/factory.go, pkg/curatedpackages/mocks/installer.go, pkg/curatedpackages/packagecontrollerclient.go, pkg/curatedpackages/packagecontrollerclient_test.go
Cherry pick https://github.com/aws/eks-anywhere/pull/7971 https://github.com/aws/eks-anywhere/pull/8012 https://github.com/aws/eks-anywhere/pull/8017
=> 🍒 Cherry pick packages with registry mirror fixes

docs/content/en/docs/whatsnew/changelog.md
=> Add changelog for patch 19.4

docs/content/en/docs/clustermgmt/cluster-terraform.md
=> Fix typo in cluster-terraform.md

docs/content/en/docs/osmgmt/overview.md
=> Update operating system management overview in the docs

docs/content/en/docs/getting-started/baremetal/tinkerbell-overview.md
=> Fix word repetitions in tinkerbell docs

docs/content/en/docs/clustermgmt/security/best-practices.md
=> Update security best practices in the docs

docs/content/en/docs/whatsnew/changelog.md
=> Add warning to call out packages workflow for patch 19.4

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml, config/manifest/eksa-components.yaml, pkg/api/v1alpha1/cluster_types.go
=> Fix typo in registry mirror config comment

docs/content/en/docs/whatsnew/changelog.md
=> Add changelog for v0.19.5

docs/content/en/docs/troubleshooting/troubleshooting.md
=> Fix typos in general troubleshooting docs

docs/content/en/docs/getting-started/vsphere/vsphere-prereq.md
=> Update requirement doc to include vSphere 8 support

docs/content/en/docs/overview/partner/_index.md
*Description of changes:* This PR adds the latest partner information to the EKS Anywhere [Partners](https://anywhere.eks.amazonaws.com/docs/overview/partner/) page.
=> Update partner docs info

docs/content/en/docs/clustermgmt/security/manually-renew-certs.md
=> Refine Cert Renewal Docs

docs/content/en/docs/overview/partner/_index.md
*Description of changes:* Removed some partner information that didn't belong in this doc.
=> Fixed partner docs info

docs/content/en/docs/getting-started/airgapped/airgap-steps.md
=> Update docs packages instructions for airgapped env

docs/content/en/docs/whatsnew/changelog.md
=> Add Changelog for v0.19.6

docs/content/en/docs/whatsnew/changelog.md
=> Fix Bottlerocket bare metal deprecation callout in changelog

internal/test/e2e/run.go
=> Add succeeded variable in the e2e result log entry

test/e2e/SKIPPED_TESTS.yaml
=> Skip 130 multi endpoint test for cloudstack

pkg/providers/cloudstack/config/template-cp.yaml, pkg/providers/cloudstack/config/template-md.yaml, pkg/providers/cloudstack/template.go, pkg/providers/cloudstack/template_test.go, pkg/providers/nutanix/config/cp-template.yaml, pkg/providers/nutanix/config/md-template.yaml, pkg/providers/nutanix/template.go, pkg/providers/nutanix/template_test.go, pkg/providers/nutanix/testdata/eksa-cluster-invalid-kc.yaml, pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/config/template-md.yaml, pkg/providers/vsphere/template.go, pkg/providers/vsphere/template_test.go
=> Kubelet Configuration for cp and wn Cloudstack, Nutanix, vSphere

docs/content/en/docs/getting-started/baremetal/bare-spec.md, docs/content/en/docs/getting-started/cloudstack/cloud-spec.md, docs/content/en/docs/getting-started/nutanix/nutanix-spec.md, docs/content/en/docs/getting-started/snow/snow-spec.md, docs/content/en/docs/getting-started/vsphere/vsphere-spec.md
This is a manual cherry-pick of https://github.com/aws/eks-anywhere/pull/8241
=> [release-0.18] Update docs for worker node group config

pkg/api/v1alpha1/cluster.go, pkg/api/v1alpha1/cluster_test.go
Block settings for provider id and cloud provider
- unit test
=> Block settings for provider id and cloud provider

test/framework/cluster.go
=> Fix autoscaler test workflow

pkg/providers/cloudstack/template_test.go, pkg/providers/common/common.go, pkg/providers/common/common_test.go, pkg/providers/nutanix/template_test.go, pkg/providers/tinkerbell/template.go, pkg/providers/vsphere/template.go, pkg/providers/vsphere/template_test.go, pkg/providers/vsphere/testdata/cluster_main_br.yaml, pkg/providers/vsphere/testdata/expected_kcp_br.yaml, pkg/validations/cluster.go, pkg/validations/cluster_test.go
Bottlerocket settings for Kubelet Configuration - vSphere
- unit tests
- e2e test
```
"kubernetes": {
"api-server": "https://195.17.0.102:6443/",
"authentication-mode": "tls",
"bootstrap-token": "3rgav5.gkw1lnyct9ey9mrb",
"cloud-provider": "external",
"cluster-certificate": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1EWXhNekF5TURVek9Gb1hEVE0wTURZeE1UQXlNVEF6T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSm9zClNtQzZ5SWk4WXRMMDJnVTY4dzk2Skh2OXF0OENrQ1pWa1dtcFVLbk41YVJWY1BCbnczRWVUbE41dVRJTzlnV1gKR3hTUkthYlJ6NFhRLzN3Y0lkMlZPVVduZXdDTHlubjluY3ZIK3BQbllLR3piMn …
```
=> Bottlerocket settings for Kubelet Configuration - vSphere

Makefile
Update branch name to release-0.20 in Makefile
=> Update branch name to release-0.20 in Makefile

docs/content/en/docs/whatsnew/changelog.md
=> Add Changelog for v0.19.7

test/e2e/docker_test.go, test/e2e/suite.go, test/e2e/upgrade_from_latest.go, test/e2e/vsphere_test.go
=> Fix e2e tests creating old bundle workload clusters

test/framework/conformance.go
This PR skips the specific conformance test `Services should serve endpoints on same port and different protocols` in our suite for clusters running Kubernetes version 1.29.0 and above, because this test will not succeed with our configuration of Cilium.
For more information regarding the what and the why, please refer to the following links:
1. https://github.com/kubernetes/kubernetes/pull/120069
2. https://github.com/cilium/cilium/issues/29913
3. https://github.com/cncf/k8s-conformance/pull/3049
=> Skip multi-protocol Service test in conformance flow

docs/content/en/docs/getting-started/baremetal/customize/bare-custom-hookos.md
There is a new and much simpler process now.
=> Update the HookOS customization doc:

internal/pkg/api/cluster.go, internal/thirdparty/capc/api/v1beta3/cloudstackisolatednetwork_types.go, test/e2e/docker_test.go, test/e2e/kubeletconfig.go, test/e2e/upgrade_from_latest.go, test/e2e/vsphere_test.go, test/framework/kubeletconfig.go, test/framework/network.go, test/framework/vsphere.go
Kubelet config e2e tests for vsphere and Docker #8362
- e2e
=> Kubelet config e2e tests for vsphere and Docker

test/e2e/SKIPPED_TESTS.yaml
Add a comment describing why the cloudstack skipped tests are skipped.
=> Add comments about why cloudstack tests are skipped

internal/pkg/ssm/run_output.go
=> Handle nil commandOut

release/cli/pkg/assets/archives/archives.go, release/cli/pkg/operations/download.go, release/cli/pkg/operations/rename.go, release/cli/pkg/operations/upload.go
Adding descriptive error logs for download, rename and upload operations
=> Add descriptive error logs for download, rename and upload operations

test/framework/workload.go
=> Log workload cluster definition during e2e test

test/e2e/vsphere_test.go
Kubelet config e2e tests for vsphere Bottlerocket
- e2e
=> Kubelet config e2e tests for vsphere Bottlerocket

test/e2e/kubeletconfig.go, test/e2e/tinkerbell_test.go
Generate hardware csv file for kubelet configuration tests
=> Add hardware csv generation for kubelet config tests

test/e2e/kubeletconfig.go, test/e2e/tinkerbell_test.go
Fix kubelet config flow for all providers
=> Fix kubelet config flow for all providers

scripts/brew_formula_update.sh, scripts/common.sh
Fix function name in Brew update script to match the name in `common.sh`.
=> Fix function name in Brew update script

docs/config.toml, docs/content/en/docs/concepts/support-versions.md, docs/data/version_support.yml
Trigger docs deployment for release-20 branch
=> Trigger docs deployment for release-20 branch

cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml, cmd/integration_test/build/script/check_concurrent_pipelines.py
=> Add concurrent pipelines check before quick e2e test

docs/content/en/docs/troubleshooting/troubleshooting.md
Add troubleshooting documentation for capv session issue.
=> Add troubleshooting documentation for CAPV session issue

.github/dependabot.yaml
=> Ignore manually updated modules in dependabot

docs/content/en/docs/troubleshooting/troubleshooting.md
Add note saying the capv session issue is resolved in release-0.20
=> Add update about capv session issue in troubleshooting docs

docs/content/en/docs/whatsnew/changelog.md
=> Add changelog for release v0.20.1

docs/content/en/docs/whatsnew/changelog.md
=> Fix changelog for v0.20.1 to have proper links

internal/pkg/ssm/run_output.go
This is a manual cherry-pick of https://github.com/aws/eks-anywhere/pull/8361 and https://github.com/aws/eks-anywhere/pull/8403
=> [release-0.19] Cherry pick 8361 and 8403 to release 0.19

docs/content/en/docs/getting-started/baremetal/tinkerbell-overview.md
This is a manual cherry-pick of #8459
=> [release-0.19] fix tinkerbell doc link

docs/content/en/docs/whatsnew/changelog.md
Changelog for patch release v0.19.8
=> Add changelog for patch release v0.19.8:

docs/content/en/docs/whatsnew/changelog.md
=> Update v0.19.8 changelog:

docs/content/en/docs/whatsnew/changelog.md
=> Add v0.20.2 changes

docs/content/en/docs/getting-started/baremetal/bare-prereq.md, docs/content/en/docs/getting-started/cloudstack/cloudstack-prereq.md, docs/content/en/docs/getting-started/nutanix/domains.md, docs/content/en/docs/getting-started/vsphere/domains.md, docs/content/en/docs/troubleshooting/troubleshooting.md
=> Add requirement for sts.amazonaws.com connection

go.mod, go.sum, release/cli/go.mod, release/cli/go.sum, release/cli/pkg/operations/testdata/main-bundle-release.yaml
Combining
https://github.com/aws/eks-anywhere/pull/8563
https://github.com/aws/eks-anywhere/pull/8583
=> Docker dependabot gomod update

docs/content/en/docs/whatsnew/changelog.md
Adding changelog for release v0.20.3
=> Adding changelog for release v0.20.3

pkg/providers/common/common.go, pkg/providers/vsphere/template_test.go, pkg/providers/vsphere/testdata/expected_kcp_br_ntp.yaml
Fix Kubelet Configuration apply when host OS config is specified
#8594 
- unit test
- e2e test
=> Fix Kubelet Configuration apply when host OS config is specified

docs/content/en/docs/clustermgmt/etcd-backup-restore/bottlerocket-etcd-backup.md
=> Fix etcdctl command in bottlerocket etcd backup documentation

docs/content/en/docs/clustermgmt/security/manually-renew-certs.md
=> Update notes for bottlerocket cert

docs/content/en/docs/clustermgmt/security/manually-renew-certs.md, docs/content/en/docs/troubleshooting/troubleshooting.md
*Description of changes:* cherry-pick  https://github.com/aws/eks-anywhere/pull/8567 manually 
=> [release-0.20] Add some quick commands for checking certificates

release/Makefile, release/cli/cmd/release.go, release/cli/pkg/assets/types/types.go, release/cli/pkg/aws/ecr/ecr.go, release/cli/pkg/bundles/package-controller.go, release/cli/pkg/clients/clients.go, release/cli/pkg/helm/helm.go, release/cli/pkg/images/images.go, release/cli/pkg/operations/upload.go, release/cli/pkg/types/types.go, release/scripts/bundle-release.sh, release/scripts/docker-ecr-config.json, release/scripts/policy.json, release/scripts/release.sh, release/scripts/setup-aws-config.sh
Backporting #8628 to release-0.19 branch
=> [release-0.19] Add logic to source packages images from beta account

docs/content/en/docs/whatsnew/changelog.md
Change log for v0.19.9 release
=> Changelog for 0.19.9

release/Makefile, release/cli/cmd/release.go, release/cli/pkg/assets/types/types.go, release/cli/pkg/aws/ecr/ecr.go, release/cli/pkg/bundles/package-controller.go, release/cli/pkg/clients/clients.go, release/cli/pkg/helm/helm.go, release/cli/pkg/images/images.go, release/cli/pkg/operations/upload.go, release/cli/pkg/types/types.go, release/scripts/bundle-release.sh, release/scripts/docker-ecr-config.json, release/scripts/policy.json, release/scripts/release.sh, release/scripts/setup-aws-config.sh
Backporting #8628 to release-0.20 branch.
=> [release-0.20]Add logic to source packages images from beta account

test/framework/cluster.go
Prometheus pod labels changed from `app=prometheus,component=server` to `app.kubernetes.io/name=prometheus,app.kubernetes.io/component=server` as we bumped the Prometheus version to 2.52. Since we never built Prometheus with the updated version for K8s version 1.25, the e2e tests failed during validation with below error: 
```
cluster.go:1814: Reading package generated-prometheus pod prometheus-server logs cluster.go:1817: unable to get name of the prometheus-server pod: error: error executing jsonpath "'{.items[0].metadata.name}'": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
```
Add logic to check for the old labels for K8s version 1.25 as we still support 1.25 for 'n-1' branch. …
=> Update prometheus pod labels in e2e validations for version 1.25

release/cli/pkg/operations/upload.go
Fix condition for assignment of source ECR auth config.
=> Fix condition for assignment of source ECR auth config

docs/content/en/docs/whatsnew/changelog.md
Adding changelog for release v0.20.4
=> Adding changelog for release v0.20.4

OWNERS
=> Add Shizhao to OWNERS

internal/test/e2e/setup.go
This PR adds logic to parallelize download and upload operations of E2E binaries during tests using `errgroup`. This is identical to the change made in #7186.
=> Parallelize download and upload operations during tests

docs/content/en/docs/clustermgmt/support/purchase-subscription.md, docs/content/en/docs/concepts/support-scope.md
Backporting #8788 to release-0.19 branch.
=> Clarify subscription non-cancellation policy in case of support ticket creation

docs/content/en/docs/whatsnew/changelog.md
=> Update changelog for v0.20.6

docs/content/en/docs/whatsnew/changelog.md
=> Change log for release-0.19.11

docs/content/en/docs/whatsnew/changelog.md
Cherry-picked from https://github.com/aws/eks-anywhere/pull/8841
=> [release-0.19] Change log for release-0.19.11

docs/content/en/docs/packages/changelog.md
This PR updates changelog for curated package release
=> Update changelog for curated package release

docs/content/en/docs/whatsnew/changelog.md
This is a manual cherry-pick of [#8890](https://github.com/aws/eks-anywhere/pull/8890).
=> changelog for v0.20.8

docs/content/en/docs/whatsnew/changelog.md
Add changelog for minor release v0.21.0
*Commits:*
https://github.com/aws/eks-anywhere/commits/release-0.21?since=2024-06-27&until=2024-10-30&before=789cb126a4aa44f8e7dbd53ddebb9d86eb911c7a+35
=> Add changelog for v0.21.0

docs/config.toml
Update versions page to match with the latest v0.21
`make build`
=> [release-0.20] Update versions page to match with the latest v0.21

docs/content/en/docs/getting-started/nutanix/nutanix-spec.md
N/A
Add Nutanix documentation for the gpus field in NutanixMachineConfig
=> Add Nutanix documentation for the gpus field in NutanixMachineConfig

docs/content/en/docs/whatsnew/changelog.md
Add changelog for patch release v0.20.9
*Commits:*
https://github.com/aws/eks-anywhere-build-tooling/commits/release-0.20/?since=2024-10-23&until=2024-11-08
```
make -C docs build
```
=> Add changelog for v0.20.9

docs/content/en/docs/whatsnew/changelog.md
This is a manual cherry-pick of [#8987](https://github.com/aws/eks-anywhere/pull/8987). 
=> [release-0.20] Add changelog for v0.20.9

docs/content/en/docs/getting-started/optional/irsa.md
https://t.corp.amazon.com/P167988780
This PR addresses two security concerns:
1. Using S3 ACL to grant public read access to bucket objects is no longer a recommended way of making files public. The recommended best practice is to disable all ACL policies and provide access using [bucket policies](https://docs.aws.amazon.com/AmazonS3/latest/userguide/add-bucket-policy.html). 
2. General best practice for IAM role trust policy is to have both the "aud" and "sub" conditions. Access Analyzer has a policy check rule that detects when the "aud" condition is missing from the policy: https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-reference-policy-checks.html#access-analyzer-reference-policy-checks-suggestion-confirm-audience-cla …
=> Update irsa docs to follow best practices and address any security concerns

OWNERS
- Add `rajeshvenkata` to OWNERS
=> Add rajeshvenkata to OWNERS

OWNERS
=> add wantonglin to OWNERS

docs/content/en/docs/whatsnew/changelog.md
Add changelog for v0.21.2 release
=> Add changelog for v0.21.2 release

docs/content/en/docs/osmgmt/artifacts.md
Add section to image-builder docs regarding required dependency versions.
=> Add section on required image-builder dependency versions

docs/content/en/docs/whatsnew/changelog.md
Change log for release v0.20.10
=> Change log for release v0.20.10

docs/content/en/docs/whatsnew/changelog.md
=> [release-0.20] Change log for release v0.20.10

docs/content/en/docs/overview/partner/_index.md
N/A
Updating Conformitron Validated partners reports
=> Update Conformitron Validated Partner reporting

docs/content/en/docs/whatsnew/changelog.md
Adding change log for release v0.21.4
=> Adding changelog for release v0.21.4

OWNERS
=> add achen1210 to OWNERS

docs/content/en/docs/whatsnew/changelog.md
Adding changelog for EKS-A version `v0.20.11`.
=> Add changelog for EKS-A v0.20.11

docs/content/en/docs/getting-started/baremetal/bare-spec.md, docs/content/en/docs/getting-started/cloudstack/cloud-spec.md, docs/content/en/docs/getting-started/nutanix/nutanix-spec.md, docs/content/en/docs/getting-started/snow/snow-spec.md, docs/content/en/docs/getting-started/vsphere/vsphere-spec.md
Fix documentation for worker nodegroup Kubernetes version.
=> Fix documentation for worker nodegroup Kubernetes version

docs/content/en/docs/whatsnew/changelog.md
Add changelog for v0.21.5 and fix BR versions.
=> Add changelog for v0.21.5 and fix BR versions

docs/content/en/docs/getting-started/nutanix/nutanix-spec.md
Add docs for NutanixDatacenterConfig.ccmExcludeNodeIPs property
=> Add docs for NutanixDatacenterConfig.ccmExcludeNodeIPs property

docs/content/en/docs/whatsnew/changelog.md
=> Update changelog for v0.21.6

cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
=> Add CI e2e env var for quick e2e

OWNERS
*Description of changes: Adding parlakisik into owners list
=> Adding parlakisik into owners list

test/framework/vsphere.go
=> Fix typo in WithUbuntu132

docs/content/en/docs/whatsnew/changelog.md
=> Update changelog for v0.21.7

docs/content/en/docs/overview/partner/_index.md
Backporting #9286 to release-0.21
=> Remove AWS Outposts section from validated partners list

test/e2e/SKIPPED_TESTS.yaml, test/e2e/constants.go, test/e2e/snow_test.go, test/framework/snow.go, test/framework/tinkerbell.go, test/framework/vsphere.go
Cleanup 1.27 e2e variables, helper functions and test cases
make e2e-cross-platform
=> Cleanup 1.27 e2e variables and tests

OWNERS
=> Update OWNERS add peirulu (Amelia) in alphabetical order

OWNERS
=> add charles-large to owners file

docs/content/en/docs/osmgmt/overview.md
Bare-metal also supports RHEL9 os. Update the docs to reflect the same.
=> Update supported providers for rhel9 OS

docs/content/en/docs/clustermgmt/security/manually-renew-certs.md
=> Fix typo in cert rotation docs

docs/content/en/docs/whatsnew/changelog.md
=> Change log for v0.22.1

docs/content/en/docs/whatsnew/changelog.md
=> Changelog release 0.22.2

pkg/executables/govc.go, pkg/executables/govc_test.go, pkg/providers/vsphere/mocks/client.go, pkg/providers/vsphere/vsphere.go, pkg/providers/vsphere/vsphere_test.go
=> Revert "Add compute cluster failure domain validation"

pkg/constants/constants.go, pkg/signature/manifest.go, pkg/signature/manifest_test.go, release/cli/cmd/release.go, release/cli/pkg/clients/clients.go, release/cli/pkg/constants/constants.go, release/cli/pkg/operations/bundle_release.go, release/cli/pkg/signature/manifest.go, release/cli/pkg/signature/manifest_test.go
[#2994](https://github.com/aws/eks-anywhere-internal/issues/2994)
This PR adds eks distro manifest signing to the EKS-A release CLI to prevent tampering for extended kubernetes version support and also adds the signatures as annotations to the bundle so that it can be fetched by the CLI and controller for signature verification.
Doc:- https://quip-amazon.com/HHz8AFaq0CAF/EKS-Distro-Manifest-Signing
Ran the following commands from the root folder:
```
make -C release unit-test
CGO_ENABLED=0 make -C release dev-release
```
Verified that the generated bundle manifest has the expected annotations:
```
kind: Bundles
metadata: …
```
=> Sign eks distro manifest and add the signatures as annotations to the bundle

docs/content/en/docs/osmgmt/overview.md
https://github.com/aws/eks-anywhere-internal/issues/2381
Documentation change for RHEL 9 support on vSphere.
=> Documentation change for RHEL 9 support on vSphere

release/cli/pkg/bundles/package-controller.go
All the packages e2e tests failed with the following error:
```
{
"waiting": {
"reason": "ImagePullBackOff",
"message": "Back-off pulling image \"public.ecr.aws/x3k6m8v0/credential-provider-package@sha256:ad124fec2f3618a16abc0d3b0eaf83174913467b30945217996d4c12ed4f0b3c\""
}
},
```
This is because the sha256 digest for the image doesn't exist in the public ECR repository but it does exist in the private ECR repository.
This PR replaces the tag for the credential provider package image to use the tags starting with v0.0.0 for dev release.
Ran the following commands from the root folder:
```
make -C release unit-test
CGO_ENABLED=0 make -C release dev-release
```
By …
=> Fix credential provider package image tags for dev release

OWNERS
*Description of changes: I am a new member of EKS anywhere team. This is a PR to add myself to the owners list for further development activities on the team. 
=> Adding Subbu Vakati to the owners list

pkg/providers/vsphere/config/template-cp.yaml, pkg/providers/vsphere/config/template-md.yaml, pkg/providers/vsphere/template_test.go, pkg/providers/vsphere/testdata/expected_kcp_vcenter_tags.yaml, pkg/providers/vsphere/testdata/expected_kct_vcenter_tags.yaml
Manual cherry-pick of https://github.com/aws/eks-anywhere/pull/9703
=> Fix assigning multiple vcenter tags to a machine (#9703)

docs/content/en/docs/whatsnew/changelog.md
=> Changelog for v0.21.8

docs/content/en/docs/whatsnew/changelog.md
=> [release-0.22] Changelog for release-0.22.5

OWNERS
*Issue #, if available:* Onboarding smvikash git account to owner list
*Description of changes:* Onboarding
*Testing (if applicable):* None
=> Updating owner

test/e2e/constants.go, test/e2e/docker_test.go
=> Adds docker e2e tests for k8s 133

cmd/integration_test/build/buildspecs/conformance-eks-a-cli.yml, cmd/integration_test/build/buildspecs/nutanix-test-eks-a-cli.yml, cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml, test/e2e/QUICK_TESTS.yaml, test/e2e/nutanix_test.go, test/framework/nutanix.go
=> Remove wrongly added redhat8 tests for newer k8s versions

docs/content/en/docs/whatsnew/changelog.md
Add changelog for patch release v0.22.6.
=> Add changelog for patch release v0.22.6

Makefile
Update branch name to release-0.23 in Makefile
=> Update branch name to release-0.23 in Makefile

release/cli/pkg/operations/download.go
This is a manual cherry-pick of [#9848](https://github.com/aws/eks-anywhere/pull/9848)
=> [release-0.21] Fix conflicts for concurrent git operations

docs/content/en/docs/clustermgmt/certificate-management/manual-steps-renew-certs.md, docs/content/en/docs/clustermgmt/certificate-management/monitoring-certificates.md, docs/content/en/docs/clustermgmt/certificate-management/script-renew-certs.md
Adding a new page on ways to monitor cluster certificates.
=> Update doc on monitoring cluster certificates using ClusterCertificateInfo field

docs/content/en/docs/getting-started/baremetal/customize/bare-custom-hookos.md, docs/content/en/docs/getting-started/baremetal/tinkerbell-overview.md, examples/tinkerbell/adding-a-user-to-tinkerbelltemplateconfiguration.md, internal/test/testdata/bundles.yaml, release/cli/pkg/assets/config/bundle_release.go, release/cli/pkg/operations/testdata/main-bundle-release.yaml
Manual backport of https://github.com/aws/eks-anywhere/pull/9913.
=> Rename tinkerbell hub to actions

internal/pkg/api/tinkerbell.go, test/e2e/TINKERBELL_HARDWARE_COUNT.yaml, test/e2e/tinkerbell_test.go, test/framework/testdata/tinkerbell/custom_config.yaml, test/framework/tinkerbell.go, test/framework/tinkerbell_template_config.go
=> Test custom TinkerbellTemplateConfig in e2e (#9909)

docs/data/version_support.yml
Update docs for v0.23 support lifecycle
=> Update docs for v0.23 support lifecycle

docs/content/en/docs/getting-started/baremetal/bare-preparation.md
Add a new section to the baremetal preparation documentation that explains how EKS Anywhere handles hardware entries in the CSV file. Specifically, it clarifies that:
- Extra machines are automatically treated as spare nodes
- Spare node selection during operations like upgrades is not deterministic
- There are potential risks if machines are repurposed but still have Hardware objects in the system
The documentation also provides best practices for hardware lifecycle management to help users avoid unintended consequences when repurposing hardware.This change addresses a security finding related to unexpected behavior during cluster operations that could potentially lead to unintended re-imaging of repurposed machines.
*Documentation …
=> Add hardware management and spare nodes section to baremetal docs

docs/content/en/docs/whatsnew/changelog.md
=> Add changelog for patch release v0.22.7

docs/content/en/docs/whatsnew/changelog.md
=> [release-0.22] Add changelog for patch release v0.22.7 (#9944)

docs/content/en/docs/whatsnew/changelog.md
=> Add changelog for patch release v0.23.1

docs/content/en/docs/osmgmt/artifacts.md
Update docs to reflect the SHA-512 digest corresponding to the latest version of the Bottlerocket root.json.
=> Update Bottlerocket root.json checksum in docs

pkg/providers/nutanix/config/cp-template.yaml, pkg/providers/nutanix/testdata/expected_cluster_api_additional_trust_bundle.yaml
Passing AdditionalTrustBundle to CAPX via ConfigMap
=> Improvement - TrustBundle to CAPX via ConfigMap

docs/content/en/docs/clustermgmt/certificate-management/eksctl-renew-certs.md
Update eksctl renew certificates command doc.
=> Update eksctl renew certificates doc

pkg/curatedpackages/packagecontrollerclient_test.go
https://github.com/aws/eks-anywhere-internal/issues/3572
Unit tests for changes in [PR](https://github.com/aws/eks-anywhere/pull/10097)
=> Test package registries with registry mirror

docs/content/en/docs/whatsnew/changelog.md
=> [release-0.22] changelog for release v0.22.8

docs/content/en/docs/whatsnew/changelog.md
=> [release-0.23] Changelog for v0.22.8

docs/content/en/docs/whatsnew/changelog.md
=> Add changelog for release v0.23.3

release/cli/pkg/helm/helm.go
[#3622](https://github.com/aws/eks-anywhere-internal/issues/3622)
The dev-release job failed with the following error:
```
Error releasing bundle artifacts: uploading artifacts: modifying Chart.yaml and pushing Helm chart to destination: turning Chart.yaml to struct: the Chart.yaml file [/codebuild/output/src2844172234/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/release/tinkerbell-chart/tinkerbell-chart/Chart.yaml] is invalid or does not contain kind &{tinkerbell-chart  [] 0.2.7-latest-helm Helm chart to install Tinkerbell stack on Kubernetes [] []  v2   v0.7.0 false map[]  [] application}
--
make: *** [dev-release] Error 1
```
This PR fixes the above issue in the dev-release job.
By submitting this pull request, …
=> Fix dev release job failures
