aws/eks-anywhere

pkg/executables/govc.go
test/e2e/upgrade_from_latest.go
test/framework/release_versions.go

When workload cluster creation with previous eksa-version e2e test is run against release branch, the test incorrectly fetches 2 minor versions below the current release branch. For ex., when run against release-0.17 it fetches 15.x eks-a version while the correct previous version should be 16.x.This change fixes the logic to fetch the right latest minor version when run against both main and release branches. 
Ran the e2e test locally against both main and release branch.

Fix to fetch the correct prev minor release for e2e tests 

---

pkg/cluster/spec.go
pkg/cluster/tinkerbell.go
pkg/collection/convert.go
pkg/collection/convert_test.go
pkg/providers/tinkerbell/upgrade.go
pkg/providers/tinkerbell/upgrade_test.go
pkg/types/cluster.go

Closes #6615 
When adding worker node groups we were erroring out indicating you cannot add or remove machine configs. This change ensures a worker node group with a new machine config can be added to a cluster spec.

Patch the inability to add worker node groups in bare metal clusters

---

docs/content/en/docs/getting-started/baremetal/customize/bare-custom-hookos.md

There is a typo in the command line, so an error occurs when copying.

Fix custom HookOS docs typing error

---

pkg/providers/tinkerbell/config/template-cp.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_single_node.yaml

In scenarios where you create a cluster of size > 1 and where the control plane and worker nodes are all together this fixes an issue with k8s services interoperating properly with static pod deployment of kube-vip when the service uses `externalTrafficPolicy: Local`
Built the cli with this change and tested using the bare metal provider.

static pod kube-vip and externalTrafficPolicy: Local

---

cmd/eksctl-anywhere/cmd/createcluster.go
cmd/eksctl-anywhere/cmd/deletecluster.go
cmd/eksctl-anywhere/cmd/flags.go
cmd/eksctl-anywhere/cmd/options.go
cmd/eksctl-anywhere/cmd/supportbundle.go
cmd/eksctl-anywhere/cmd/upgradecluster.go
cmd/eksctl-anywhere/cmd/upgradeplancluster.go

https://github.com/aws/eks-anywhere/issues/5905
- deprecate `wConfig` in update and delete
- exit when use `wConfig`
- rename `wConfig` to `clusterConfig` to avoid confusion
- manual testing
- create mgmt cluster 
- rename cluster dir
- use --w-config leads to error
- use --kubeconfig to upgrade
- use --kubeconfig to delete

CLI deprecate wl kubeconfig flag

---

cmd/eksctl-anywhere/cmd/createcluster.go
cmd/eksctl-anywhere/cmd/deletecluster.go
cmd/eksctl-anywhere/cmd/flags.go
cmd/eksctl-anywhere/cmd/options.go
cmd/eksctl-anywhere/cmd/supportbundle.go
cmd/eksctl-anywhere/cmd/upgradecluster.go
cmd/eksctl-anywhere/cmd/upgradeplancluster.go

Reverts aws/eks-anywhere#6573
We found w-config is at least used in cilium and IAM, so we better not deprecate it.
The bug can be fixed by using kubeconfig instead of w-config in [validation](https://github.com/aws/eks-anywhere/blob/3df940e33d3126d87922927217080bbdb52230a1/cmd/eksctl-anywhere/cmd/upgradecluster.go#L194). Or we should validate both kubeconfig and w-config if they are not empty

Revert "CLI deprecate wl kubeconfig flag"

---

test/e2e/cloudstack_test.go
test/e2e/docker_test.go
test/e2e/upgrade_from_latest.go
test/e2e/vsphere_test.go
test/framework/clustervalidator.go

This CR updates from latest release API tests to:
1. Update the workload cluster config machines templates before creating the cluster with the old bundle.  
At the step of creating a new workload cluster with the old Eksa version, the test may fail validating template tags (particularly for vSphere)) if the old bundle is using a different eksd tags. So, we need to also update the workload cluster machine templates with a template appropriate for the Kubernetes version and the old release. 

Update API upgrade test to specify use appropriate templates

---

internal/pkg/api/cluster.go
test/e2e/cloudstack_test.go
test/e2e/docker_test.go
test/e2e/upgrade_from_latest.go
test/e2e/vsphere_test.go
test/framework/clustervalidator.go

Manual cherry pick of #6656 
The upgrade from latest minor release tests on this branch can't use EksaVersion for the creating the workload cluster with the old bundle, because it does not exist in 0.16.5. So we must use bundlesRef

[release-0.17] update api upgrade test to specifically use apropropriate templates

---

cmd/eksctl-anywhere/cmd/upgradecluster.go

https://github.com/aws/eks-anywhere/issues/5905
We decide to separate bug fix and flag deprecation.
`eksa upgrade cluster -f mgmt.yaml --kubeconfig cluster.kubeconfig` (only kubeconfig is provided)
- set wconfig to provided cluster.kubeconfig
- set mgmtkubeconfig to empty
input --w-config | input --kubeconfig | input file | actual wconfig value | actual mgmtkubeconfig value | expected behavior
-- | -- | -- | -- | -- | --
  | mgmt | mgmt | reset to mgmt | reset to "" | upgrade mgmt
  | wl | mgmt | wl | "" | error wl kubeconfig [doesn't have resource cluster](https://github.com/aws/eks-anywhere/blob/5cabd6fd5c7367c68e014fff0401c1275424f2f4/pkg/executables/kubectl.go#L1519)
  | mgmt | wl | default location | mgmt | upgrade wl cluster
  | wl …

fix cli upgrade mgmt kubeconfig flag

---

test/framework/cluster.go

This PR enables Kindless management cluster upgrade for vSphere provider. The feature is under feature flag so it won't impact the current upgrade process for other providers.

Enable Kindless management cluster upgrade for vSphere provider

---

docs/content/en/docs/osmgmt/artifacts.md
docs/content/en/docs/whatsnew/changelog.md

Update changelog and docs for v0.17.2

---

pkg/collection/set.go
pkg/providers/tinkerbell/upgrade.go
pkg/providers/tinkerbell/upgrade_test.go
pkg/validations/upgradevalidations/preflightvalidations_test.go

Closes #6633.
In bare metal clusters users shouldn't be able to change machine configs. However, EKS-A incorrectly allowed users to change the machine config references to existing machine configs.

Prevent bare metal machine config references from changing to existing machine configs

---

pkg/providers/tinkerbell/testdata/cluster_tinkerbell_mismatched_external_etcd.yaml
pkg/providers/tinkerbell/testdata/cluster_tinkerbell_mismatched_machine_config.yaml
pkg/providers/tinkerbell/tinkerbell.go
pkg/providers/tinkerbell/tinkerbell_test.go

Depends on https://github.com/aws/eks-anywhere/pull/6654.
Manual backport of #6171.

Backport #6171

---

go.mod
go.sum
pkg/curatedpackages/packagecontrollerclient.go
pkg/curatedpackages/packagecontrollerclient_test.go
pkg/curatedpackages/regional_registry.go
pkg/curatedpackages/regional_registry_test.go

*Description of changes:* Add curated packages regional registries for beta stage.
Manual:
1) Set EKSA_AWS_* credential environment variables which has access to regional curated package registry
2) install packagecontroller `eksctl-anywhere install packagecontroller`
3) verified the regional registry were used for defaultImageRegistry, defaultRegistry fields of PackageBundleController
4) verified the packages controller were running healthy, and all its dependencies are healthy 
5) manually installed hello package
6) verified the hello package was running healthy
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

Add regional registries

---

docs/content/en/docs/troubleshooting/troubleshooting.md

Add providerID not set issue and fix to troubleshooting guide

---

pkg/controller/clusters/controlplane.go
pkg/controller/clusters/controlplane_test.go
pkg/providers/cloudstack/reconciler/reconciler.go
pkg/providers/docker/reconciler/reconciler.go
pkg/providers/nutanix/reconciler/reconciler.go
pkg/providers/snow/reconciler/reconciler.go
pkg/providers/tinkerbell/reconciler/reconciler.go
pkg/providers/vsphere/reconciler/reconciler.go

In order to have more control over the upgrade process and make sure
than in case of error the cleanup is easier, we upgrade etcd separately
from the CP nodes for external etcd topologies. The controller will
apply etcd changes in isolation and wait for etcd to be ready before
moving on with the CP nodes.
These changes allows us to implement [this](https://github.com/aws/eks-anywhere/blob/main/designs/kindless-upgrades.md#separating-etcd-from-cp-changes).
Tested manually with vsphere

Separate etcd upgrade changes from kcp changes

---

pkg/collection/set.go
pkg/providers/tinkerbell/upgrade.go
pkg/providers/tinkerbell/upgrade_test.go
pkg/validations/upgradevalidations/preflightvalidations_test.go

Backport #6674: Prevent bare metal machine config references from changing to existing machine configs

---

pkg/networking/cilium/templater.go
pkg/networking/cilium/templater_test.go

The Cilium preflight DaemonSet is a part of Cilium Helm charts and is installed to act as helper during Cilium upgrades. Since it's a DaemonSet, it will target all nodes to schedule pods on, and tolerates some well-known taints defined [here](https://github.com/aws/eks-anywhere/blob/main/pkg/networking/cilium/templater.go#L51-L73) (this list is a modified version of [upstream's list](https://github.com/cilium/cilium/blob/v1.12.11/install/kubernetes/cilium/values.yaml#L1917-L1926) that includes the toleration to the `node-role.kubernetes.io/control-plane`  taint). However if a user configures taints in their EKS-A cluster config, then this preflight DaemonSet will not be able to schedule pods on those nodes since it only tolerates the static list of taints above. Thus cluster upgrades will …

Ignore node taints when scheduling Cilium preflight daemonset

---

pkg/providers/vsphere/vsphere.go

During upgrade of an EKS-A vSphere cluster, one of the preflight checks we do is to validate whether the cumulative disk size requirements of the `VSphereMachineConfig`s can be met by the vCenter datastore. For this, we get the previous disk size requirement for each `VSphereMachineConfig` and then add it to the value in the new cluster config, and we sum this value across all `VSphereMachineConfigs` and compare it to the available space in the datastore. The previous disk usage is obtained by performing a `kubectl get` call on the `VSphereMachineConfig` object in the old cluster, but we are also doing this for newly added `VSphereMachineConfig` which don't exist on the old cluster, which leads to errors like
```bash
Error: "Validation failed {"validation": "vsphere provider validation", …
```

Get previous disk usage only from existing machine configs

---

release/pkg/assets/archives/archives.go
release/pkg/assets/archives/archives_test.go
release/pkg/assets/config/bundle_release.go
release/pkg/assets/types/types.go
release/pkg/test/testdata/main-bundle-release.yaml

We upload Bottlerocket OS images to an OS version folder and we need to source it from the same folder during dev and staging releases.

Source Bottlerocket artifacts from new upload location

---

designs/k8s-modular-upgrade.md

k8s modular upgrade design doc

---

internal/test/e2e/testRunner.go

Instead of waiting for the job to clean the up, we now terminate the instance immediately. All logs and tests artifacts should already be uploaded by this time, that should be our tool to debug tests.
The main benefit here is we avoid lingering instances that might still be running something (like a kind cluster) that could keep hitting the infra APIs, which could overwhelm them if too many are doing that at the same time. This gets even worse when they overlap with the next test run.

Terminate ec2 instance runner after e2e tests

---

pkg/api/v1alpha1/cluster_defaults_test.go
pkg/api/v1alpha1/etcdencryption.go
pkg/api/v1alpha1/etcdencryption_test.go
pkg/clusterapi/extraargs.go
pkg/clusterapi/extraargs_test.go
pkg/providers/cloudstack/cloudstack_test.go
pkg/providers/cloudstack/config/template-cp.yaml
pkg/providers/cloudstack/template.go
pkg/providers/cloudstack/testdata/cluster_etcd_encryption.yaml
pkg/providers/cloudstack/testdata/expected_results_encryption_config_cp.yaml
pkg/providers/common/encryption_config_generator.go
pkg/providers/common/encryption_config_generator_test.go
pkg/providers/common/testdata/expected_encryption_config.yaml

Add support for ETCD Encryption in Cloudstack using KMS encryption provider.
Created a cluster, deployed `pod-identity-webhook` and configured IRSA, and deployed `aws-encryption-provider` daemonset to start the KMS provider. Then ran upgrade with the encryption config and verified on the etcd node that the secrets were encrypted.
Sample CloudStack cluster spec with encryption config:
```yaml
kind: Cluster
metadata:
name: test-workload-2
namespace: default
spec:
clusterNetwork:
cniConfig:
cilium: {}
pods:
cidrBlocks:
- 192.168.0.0/16
services:
cidrBlocks:
- 10.96.0.0/12
controlPlaneConfiguration:
count: 1
endpoint:
host: 10.80.193.31
machineGroupRef:
kind: CloudStackMachineConfig
name: …
```

Add support for ETCD encryption in Cloudstack

---

pkg/cluster/config.go
pkg/cluster/wait.go
pkg/cluster/wait_test.go
pkg/clustermanager/applier.go
pkg/clustermanager/applier_test.go
pkg/controller/clusters/status.go
pkg/controller/clusters/status_test.go
pkg/providers/cloudstack/controlplane_test.go
pkg/providers/cloudstack/reconciler/reconciler_test.go
pkg/providers/cloudstack/testdata/cluster_main.yaml
pkg/providers/cloudstack/testdata/cluster_main_with_cp_node_labels.yaml
pkg/providers/cloudstack/testdata/cluster_main_with_node_labels.yaml
pkg/providers/cloudstack/testdata/expected_results_main_autoscaling_md.yaml
pkg/providers/cloudstack/testdata/expected_results_main_cp.yaml
pkg/providers/cloudstack/testdata/expected_results_main_md.yaml
pkg/providers/cloudstack/testdata/expected_results_main_no_machinetemplate_update_cp.yaml
pkg/providers/cloudstack/testdata/expected_results_main_no_machinetemplate_update_md.yaml
pkg/providers/cloudstack/testdata/expected_results_main_node_labels_cp.yaml
pkg/providers/cloudstack/testdata/expected_results_main_node_labels_md.yaml
pkg/providers/cloudstack/testdata/expected_results_resourceids_cp.yaml
pkg/providers/cloudstack/validator.go
pkg/providers/cloudstack/validator_test.go

This PR includes fixes for below 3 issues,
1. Validates Cloudstack template name and kubernetes version from the controller side and waits for both to match for further reconciliation.
2. Since we have seperated ETCD and CP reconciliation, it waits for ETCD to be ready before marking ControlPlaneReady to true.
3. From the CLI side during management cluster upgrade, waits for Cluster FailureMessage to be nil before waiting for other condition to met.

Kindless upgrade changes for vSphere & CloudStack provider

---

docs/content/en/docs/getting-started/vsphere/customize/vsphere-ovas.md
docs/content/en/docs/getting-started/vsphere/vsphere-prereq.md

Update vSphere Prereq Doc

---

pkg/cluster/wait.go
pkg/cluster/wait_test.go
pkg/clustermanager/applier.go
test/framework/cluster.go

Increase the verbosity of upgrade command for e2e tests and added logs for debugging e2e tests failures.

Add extra logs and increase verbosity of upgrade command for e2e tests

---

test/framework/cluster.go

Enable kindless management cluster upgrade for the cloudstack provider.

Enable kindless management upgrade for cloudstack provider

---

pkg/clusterapi/constants.go
pkg/controller/clusters/clusterapi.go
pkg/controller/clusters/clusterapi_test.go

A part of kindless upgrade task for management cluster: https://github.com/aws/eks-anywhere/blob/main/designs/kindless-upgrades.md#waiting-for-control-plane-to-be-fully-upgraded
There a race condition where the status of the CAPI cluster is not updated fast enough after updating the KCP. Thus, before upgrading other components like CNI, worker nodes wait for CP to be fully upgraded before upgrading other components of the cluster. Now the controller will look at the KCP object instead of CAPI cluster to avoid outdated status reports. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …

Waiting for control plane to be fully upgraded 

---

pkg/curatedpackages/packagecontrollerclient.go
pkg/curatedpackages/packagecontrollerclient_test.go
pkg/curatedpackages/regional_registry.go
pkg/curatedpackages/regional_registry_test.go

*Description of changes:* When a user provides key/secret that has access to regional ECR, the package controller would automatically switch to the regional ECR. However when a user provides an AWS credential through AWS config file that has access to regional ECR, the curated packages controller would not use region ECR endpoint. This PR fixes this issue.
*Testing (if applicable):* Manuall invoked `eksa install packagecontroller` with config environment variable, and verified the config has been stored, and regional ECR endpoint is used.

Refactor registry tester to support aws config

---

pkg/executables/govc.go
pkg/executables/govc_test.go
pkg/providers/vsphere/mocks/client.go
pkg/providers/vsphere/spec.go
pkg/providers/vsphere/vsphere.go
pkg/providers/vsphere/vsphere_test.go

Add a preflight validation that checks for requested memory is available in the resource pool for the respective machine configs before proceeding with the create or upgrade operation. 

Validate Memory Usage for given resource pool for Vsphere provider

---

pkg/api/v1alpha1/cluster_webhook.go
pkg/api/v1alpha1/cluster_webhook_test.go

We don't allow to configure gitOps for management cluster upgrade. For kindless management upgrade flow, we use controller to upgrade our cluster so this PR allows configuring gitOps for the management cluster if the kindless feature is enabled.

Allow to configure gitOps during kindless management cluster

---

pkg/cluster/wait.go
pkg/cluster/wait_test.go
pkg/clustermanager/applier.go
pkg/clustermanager/applier_test.go

With the new kindless upgrade management task we have seen an error message like `kubernetes version v1.25.13-eks-a6e69b0 does not match expected version 1.26`. CLI relies on cluster status object field to decide on cluster upgrade process. This error happens due to cluster status field not being upgraded immediately due to certain race condition or just due to the lag. To fix these issues we have added a check to verify the conditions certain amount of times before moving to the next steps.

Verify the condition matches certain amount of times kindless upgrade

---

cmd/integration_test/build/buildspecs/conformance-eks-a-cli.yml
cmd/integration_test/build/buildspecs/nutanix-test-eks-a-cli.yml
test/e2e/nutanix_test.go

Add 1.28 Nutanix E2E

---

cmd/eksctl-anywhere/cmd/upgradecluster.go
pkg/validations/input.go
pkg/validations/input_test.go

https://github.com/aws/eks-anywhere/issues/6716
add validation checking cluster name provided in command matches with config
unit test

cli validate cluster name in cmd and config

---

pkg/clustermanager/cluster_manager.go
pkg/clustermanager/cluster_manager_test.go

#6453 
This PR addresses the issue where the CLI stalls on create/upgrade if it encounters a validation error at the point of force "Applying eksa yaml resources to cluster" near the end of cluster creation or upgrade, where it will stall indefinitely until it eventually times out. This is proposing opting to use a regular client side `kubectl apply` operation instead of the current client side`kubectl apply --force`, so that such issues are raised earlier and handle properly in the web-hooks
Normally, the `k --force apply` would delete the resource and just recreate it, but instead it the CLI gets stuck. This is because there is a finalizer on the Cluster object resecource. Typically, the `eksa-controller-manager` controls deletion of …

Update CLI to apply resources to using regular kubectl apply instead of with force

---

docs/content/en/docs/getting-started/install/_index.md

`eksctl` has now moved to a new GitHub Organisation so updating docs to reflect that.

Update Github organization for eksctl repository

---

pkg/api/v1alpha1/tinkerbellmachineconfig.go
pkg/api/v1alpha1/tinkerbellmachineconfig_webhook.go
pkg/api/v1alpha1/tinkerbellmachineconfig_webhook_test.go

We srtip the comments for tinkerbell cluster create and upgrade operations using CLI. If the `sshAuthorizedKey` is something like `ssh AAAAC3NzaC1lZD abc@xyz.com` we strip the comment portion and make it `ssh AAAAC3NzaC1lZD`. We did not implement this feature for eksa controller. This PR adds the same feature for controller using mutating webhook. 

Strip comments from ssh key from the controller using mutating webhook

---

internal/test/e2e/etcdEncryption.go
test/framework/etcdencryption.go

Fix Cloudstack Etcd encryption test

---

pkg/api/v1alpha1/condition_consts.go
pkg/controller/clusters/status.go
pkg/controller/clusters/status_test.go

We are having an issue in creating workload cluster using the controller if external Etcd is configured on the workload cluster. It used to fail with `failed calling webhook "mutation.vspheremachineconfig.anywhere.amazonaws.com` error. This issue happens because reconciler tries to get the CAPI cluster before the CAPI cluster becomes available for the workload cluster.
Added additional checks to make sure CAPI cluster are Etcdadm cluster are available before moving to check if the etcd machines are available or not.

Added an additional check to make sure etcdadm and capi clusters are available

---

test/framework/cluster.go

Enable kindless upgrade management test for baremetal provider.

Enable kindless upgrade management feature for baremetal

---

cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml
pkg/providers/vsphere/config/template-cp.yaml
pkg/providers/vsphere/template.go
pkg/providers/vsphere/testdata/cluster_ubuntu_etcd_encryption.yaml
pkg/providers/vsphere/testdata/expected_results_ubuntu_etcd_encryption_cp.yaml
pkg/providers/vsphere/vsphere_test.go
test/e2e/vsphere_test.go
test/framework/etcdencryption.go

Add support for etcd encryption in vSphere along with an e2e test
Ran the e2e test and verified it works 
```
cluster.go:913: Skipping VM cleanup
--- PASS: TestVSphereKubernetes128EtcdEncryption (1130.91s)
PASS
```

Add support for etcd encryption in vSphere

---

pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/cluster_types.go
pkg/api/v1alpha1/cluster_types_test.go
pkg/clustermarshaller/testdata/expected_marshalled_cluster.yaml
pkg/clustermarshaller/testdata/expected_marshalled_cluster_flux_and_gitops.yaml
pkg/clustermarshaller/testdata/expected_marshalled_cluster_flux_config.yaml
pkg/clustermarshaller/testdata/expected_marshalled_snow.yaml
pkg/gitops/flux/files_test.go
pkg/gitops/flux/testdata/cluster-config-default-path-management.yaml
pkg/gitops/flux/testdata/cluster-config-default-path-workload.yaml
pkg/gitops/flux/testdata/cluster-config-user-provided-path.yaml

This PR removes a patch that substitutes the ClusterSpec with a ClusterSpecGenerate so that the bundlesRef field on the would not use `omitempty` on it's JSON tag. This patch is no longer needed, the following was why it was added before.
There was an issue when upgrading from the latest minor release with gitops to v0.17 during the "Applying eksa yaml resources to cluster" step stalled indefinitely. This seems to happen when there is a web-hook validation error, triggering the `k --force apply` to delete the Cluster resource.
In this case, ghough the Cluster object that was force applied was valid with the `eksaVersion` specified and no  `bundlesRef` set, it was trying to do that 3 way strategic merge and added the old `bundlesRef` to …

Remove patch for bundlesRef and ClusterSpecGenerate struct

---

test/framework/config/aws-kms-encryption-provider.yaml

Fix etcd encryption test

---

docs/content/en/docs/getting-started/optional/registrymirror.md

#6418 
OCI namespaces docs addition/clarification on having at least one entry for public.ecr.aws

OCI namespaces docs addition/clarification

---

test/e2e/constants.go

Updated the e2e `kubeVersions` constant to remove 1.23 and add 1.28 to match current supported k8s versions.

Update e2e constants kubeVersion to remove 1.23 and add 1.28

---

pkg/providers/cloudstack/validator.go
pkg/providers/cloudstack/validator_test.go

We need to validate worker node specific kubernetes version (if present) in case of modular upgrade with the template name field. The template name field should contain the kubernetes version specified in the workernode configuration if the upgrade type is modular upgrade.

Validate worker node kubernetes version with the template name

---

test/framework/cluster.go

Enable kindless upgrade management test for Snow provider.

Enable kindless management cluster upgrade for snow provider

---

cmd/integration_test/build/buildspecs/nutanix-test-eks-a-cli.yml
pkg/api/v1alpha1/nutanixmachineconfig.go
test/e2e/nutanix_test.go
test/framework/nutanix.go
test/framework/os_versions.go

- add rhel8 and rhel9 tests for nutanix
- add rhel8 and rhel9 template vars
- add rhel9 constants
- change NutanixMachineConfig validation

Add RHEL8 and RHEL9 fix for validation webhook and tests for Nutanix

---

pkg/providers/cloudstack/validator.go
pkg/providers/cloudstack/validator_test.go

Template name field in each cloudstack machine object should contain Cluster object's kubernetes version and/or worker machine's kubernetes version.
Simple Upgrade:
Modular Upgrade: 

Add template name and k8s version check for all cloudstack machines

---

test/framework/cluster.go

Enable kindless upgrade feature for e2e tests for all the providers.

Enable kindless upgrade feature for all the providers

---

Makefile
internal/test/envtest/environment.go

Before this, running a test that required envtest without setting the KUBEBUILDER_ASSETS env var would fail. Now, if the env var is not set, the envtest setup will download the necessary assets and configure the tests to use them.
This means that `go test` (on individual tests or whole packages) now works out of the box.

Automate envtest setup from tests if not configured

---

docs/content/en/docs/clustermgmt/etcd-backup-restore/bottlerocket-etcd-backup.md

Fix comments that some steps need to be executed on etcd nodes instead of control plane nodes.
Also use `etcd` instead of `ETCD` for doc consistency.

Fix BR etcd backup and restore page

---

docs/content/en/docs/osmgmt/artifacts.md

Documenting some recent image-builder enhancements.

Add docs for recent image-builder enhancements

---

test/e2e/vsphere_test.go

This test was previously creating a workload cluster with 1.28 and then trying to downgrade to 1.24, which is not allowed. 
Now it creates with 1.24 and upgrades to 1.25.

Fix vsphere upgrade kubernetes flux e2e

---

test/e2e/vsphere_test.go

This e2e previously didn't set the Kubernetes version of the cluster so it used the default of 1.28, but expected a 1.27 template.

Fix multi templates e2e

---

cmd/eksctl-anywhere/cmd/upgradecluster.go
pkg/api/v1alpha1/cluster_webhook.go
pkg/api/v1alpha1/cluster_webhook_test.go
pkg/providers/cloudstack/config/template-cp.yaml
pkg/providers/cloudstack/testdata/expected_results_encryption_config_cp.yaml
pkg/providers/vsphere/config/template-cp.yaml
pkg/providers/vsphere/testdata/expected_results_ubuntu_etcd_encryption_cp.yaml
test/e2e/cloudstack_test.go
test/e2e/vsphere_test.go
test/framework/cluster.go
test/framework/config/aws-kms-encryption-provider.yaml
test/framework/etcdencryption.go

Update the path for the encryption config to be compatible with Bottlerocket and add an E2E test for validation]
Also added blocks to restrict etcd encryption to only the supported providers
Ran the E2E test and verified the changes

Fix etcd-encryption for bottlerocket

---

pkg/providers/nutanix/testdata/cluster_nutanix_with_trust_bundle.yaml
pkg/providers/nutanix/testdata/cluster_nutanix_with_upgrade_strategy_cp.yaml
pkg/providers/nutanix/testdata/cluster_nutanix_with_upgrade_strategy_md.yaml
pkg/providers/nutanix/testdata/eksa-cluster-invalid-pe-cluster-pc.yaml
pkg/providers/nutanix/testdata/eksa-cluster-invalid-pe-cluster-random-name.yaml
pkg/providers/nutanix/testdata/eksa-cluster-multiple-machineconfigs.yaml
pkg/providers/nutanix/testdata/eksa-cluster.yaml
pkg/providers/nutanix/validator.go
pkg/providers/nutanix/validator_test.go

Add template name and uuid name check for Nutanix kindless management cluster upgrade feature. This is needed for kubernetes version upgrade where the controller waits until the template name matches the kubernetes version before reconciling the objects. 
We rely on the eksa-controller from now onwards to upgrade the management cluster using CLI. Sometimes it happens that during the kubernetes version upgrade, when we apply the cluster spec changes to the cluster, the cluster object gets upgraded and starts reconciling immediately before machineconfig gets upgraded and it might upgrade the cluster with previous machine config's image UUID or name. To avoid this issue, we have made it mandatory for the image name and image we get from the UUID to have the cluster …

Add template name and uuid name check for Nutanix kindless feature

---

pkg/providers/docker/reconciler/reconciler.go

Installing flux on upgrade failed due to a transient error that never cleared for docker clusters. 
Clears the status on docker clusters during reconcile. 

Clear Status on Docker Reconcile

---

pkg/clustermanager/applier.go

For nutanix e2e tests, cluster controller takes some more time to reconcile generation and observered generation value and also takes some more time to reconcile cluster and machineconfig objects. Increased wait time to 10 minutes.

Increase timeout to wait for cluster generations to be same

---

cmd/eksctl-anywhere/cmd/upgradecluster.go
manager/main.go
pkg/api/v1alpha1/cluster_webhook.go
pkg/api/v1alpha1/cluster_webhook_test.go
pkg/api/v1alpha1/vspheremachineconfig_webhook.go
pkg/api/v1alpha1/vspheremachineconfig_webhook_test.go
pkg/awsiamauth/reconciler/reconciler_test.go
pkg/clustermanager/eksa_installer.go
pkg/clustermanager/eksa_installer_test.go
pkg/controller/clusters/clusterapi.go
pkg/controller/clusters/clusterapi_test.go
pkg/features/features.go
pkg/providers/cloudstack/reconciler/reconciler_test.go
pkg/providers/docker/reconciler/reconciler_test.go
pkg/providers/snow/reconciler/reconciler_test.go
pkg/providers/tinkerbell/reconciler/reconciler_test.go
pkg/providers/vsphere/reconciler/reconciler_test.go
pkg/workflows/management/upgrade_test.go
test/framework/cluster.go

Do not create a kind cluster to upgrade the management cluster of all the providers. 

Remove kindless upgrade feature flag for all the providers

---

controllers/cluster_controller.go
controllers/cluster_controller_test.go

Remove experimentalSelfManagedUpgrade flag and allow management cluster's worker nodes and control plane both to reconcile.
Tested cluster upgrade using CLI for docker and vSphere provider.

Remove experimentalSelfManagedUpgrade flag for management cluster controller

---

test/e2e/docker_test.go

Cilium Skip Upgrade tests fail when run against the release branch when the release isn't out already as it picks up the wrong latest minor version. Make the test to derive at the latest minor based on the test branch it is run against to rightly calculate the previous latest minor release.

Fix latest minor version issue in docker skip cilium upgrade E2E

---

.github/workflows/vulnerability.yml

This should prevent vulnerable deps from being added and also will scan our code to narrow down if we are affecting by new CEV or not. This will run on every PR, every commit to `main` and release branches and periodically every night.

Add actions for vulnerability scans

---

.github/dependabot.yaml

This configures dependabot to create PRs to update our dependencies even if there are not known vulnerabilities. It should facilitate to keep everything updated and not run into situations where we need to update everything at once, so we have more time to react.

Configure dependabot to keep dependencies updated

---

docs/content/en/docs/concepts/architecture.md
docs/content/en/docs/getting-started/vsphere/overview.md
docs/developer/development-lifecycle.md

Fix doc errors in concepts and getting started

---

pkg/files/reader_test.go

If we don't get to fix this eventually (I already tried twice) we should probably just delete it.

Skip flaky TestReaderReadFileHTTPSProxySuccess

---

docs/content/en/docs/concepts/support-versions.md
docs/content/en/docs/osmgmt/artifacts.md
docs/content/en/docs/whatsnew/changelog.md

0.18.0 Changelog

---

docs/content/en/docs/clustermgmt/cluster-upgrades/baremetal-upgrades.md
docs/content/en/docs/getting-started/baremetal/bare-spec.md
docs/content/en/docs/getting-started/vsphere/vsphere-spec.md

Document osImageURL field added to machine config object for bare metal. Call out osImageURL fields have to be non overlapping betweem datacenter and machine config objects.

Doc changes for modular upgrades in Bare Metal

---

go.mod
go.sum
release/go.mod
release/go.sum

Cherry-pick of #6895 and #6896
Bumps [google.golang.org/grpc](https://github.com/grpc/grpc-go) from 1.53.0 to 1.56.3.
- [Release notes](https://github.com/grpc/grpc-go/releases)
- [Commits](grpc/grpc-go@v1.53.0...v1.56.3)
/hold
until we tag v0.18.0, this will go out in v0.18.0 since we are not affected by it.

[release-0.18] Bump google.golang.org/grpc from 1.53.0 to 1.56.3

---

pkg/curatedpackages/packagecontrollerclient.go
pkg/curatedpackages/reader.go
pkg/curatedpackages/regional_registry.go

In the regional packages flow, we are using the eks-anywhere-packages, ecr-token-refresher and credential-provider-package from packages-beta public ECR account. So if access to regional registry is detected, then we need to set this public ECR as the sourceRegistry.

Use beta packages account public ECR as source registry for regional packages

---

designs/modular-kubernetes-version-upgrade.md

Add single pager for separating control plane and worker node Kubernetes version upgrades

Modular K8s Version Upgrade Doc

---

cmd/eksctl-anywhere/cmd/createcluster.go
cmd/eksctl-anywhere/cmd/deletecluster.go
cmd/eksctl-anywhere/cmd/generatebundleconfig.go
cmd/eksctl-anywhere/cmd/supportbundle.go
cmd/eksctl-anywhere/cmd/upgradecluster.go
cmd/eksctl-anywhere/cmd/upgradeplancluster.go
cmd/eksctl-anywhere/cmd/validatecreatecluster.go
pkg/dependencies/factory.go

Removes a superfluous use of `context.Context` when constructing the global factory data structure.

Remove supfluous context in `ForSpec()` func

---

test/e2e/autoscaler.go
test/e2e/tinkerbell_test.go

Tinkerbell Autoscaler tests use the common framework function used by other providers that does not cater to tinkerbell specific pre-requisites like generating hardware config. Add tinkerbell specific framework flow for autoscale tests.

Add tinkerbell specific framework flow for autoscaler e2e tests

---

docs/content/en/docs/clustermgmt/support/cluster-license.md
docs/content/en/docs/clustermgmt/support/create-subscription-output.md
docs/content/en/docs/clustermgmt/support/describe-subscription-output.md
docs/content/en/docs/clustermgmt/support/get-license-output.md
docs/content/en/docs/clustermgmt/support/list-subscription-output.md
docs/content/en/docs/clustermgmt/support/packages-registries.md
docs/content/en/docs/clustermgmt/support/purchase-subscription.md
docs/content/en/docs/clustermgmt/support/share-packages.md
docs/content/en/docs/clustermgmt/support/supportbundle.md
docs/content/en/docs/concepts/support-scope.md

Documentation for EKS-A subscriptions

---

docs/content/en/docs/concepts/support-versions.md

When a new EKS-A minor release n is out, make sure you always update the n-1 version to indicate it is no longer backported with CVE patches.

Update versioning page to indicate CVE patches not back ported in 0.17

---

test/e2e/SKIPPED_TESTS.yaml

*Description of changes:* Currently, only simpleflow snow e2e tests are enabled. We would like to gradually enable more snow e2e tests. Meanwile, we will fix any test failure caused by environment setup.

Enable snow ubuntu upgrade e2e test

---

docs/content/en/docs/getting-started/optional/packages.md
docs/content/en/docs/packages/overview.md
docs/content/en/docs/packages/packagebundles.md
docs/content/en/docs/packages/packagecontroller.md

This PR:
- Refines some of the packages overview section.
- Removes unsuitable reference to install package controller in Package CLI in package overview.
- Adds link to package management section in Optional Configuration section for packages controller.
- Update managing package controller and package bundles menu item titles.

Update package controller docs overview section

---

pkg/semver/semver.go
pkg/validations/cluster_test.go

The semver package unnecessarily uses uint64. This alters it to use int64 alleviating the problem.
Uses of uint should only be used when needed, typically when performing bitwise operations.

Patch incorrect conversion between uint64 and int64

---

cmd/eksctl-anywhere/cmd/import_images.go
pkg/constants/constants.go
pkg/curatedpackages/packagecontrollerclient_test.go
pkg/registrymirror/containerd/utils_test.go
pkg/registrymirror/registrymirror.go
pkg/registrymirror/registrymirror_test.go

Related to https://github.com/aws/eks-anywhere/security/code-scanning/4.
Registry mirror configuration using namespaced registries [requires users to specify the curated packages registry](https://anywhere.eks.amazonaws.com/docs/getting-started/optional/registrymirror/#__ocinamespaces__-optional).
We have special handling for the curated packages URL and identify URLs of any region using regex. However, the regex was incorrect and matched invalid URLs such as `783794618700&dkr&ecr&amazonaws&com`. This is because the string is also used in containerd config that supports wildcard matching (as used in the string).
This change separates regex uses from containerd uses ensuring we correctly match curated packages URLs.

Fix incorrect regex for matching curated package registry URL

---

docs/content/en/docs/getting-started/cloudstack/cloudstack-prereq.md
docs/content/en/docs/getting-started/nutanix/nutanix-prereq.md
docs/content/en/docs/getting-started/vsphere/vsphere-prereq.md

The titles for most requirements pages had an additional `#` making them inconsistent with other pages under the same sections.

Docs: make prereq titles consistent

---

pkg/tar/untar.go
pkg/tar/untar_test.go

Tarballs with files containing directory traversal components can write files to unintended locations. This change ensures the Untar function will error when a given tarball has a traversal component (..).
See https://cwe.mitre.org/data/definitions/22.html
Fixes https://github.com/aws/eks-anywhere/security/code-scanning/1

Patch malicious tarballs directory traversal vuln

---

docs/content/en/docs/clustermgmt/etcd-backup-restore/bottlerocket-etcd-backup.md

Sometimes, there are multiple etcd container running in BR node. Because of this, the below command from [bottlerocket-etcd-backup](https://anywhere.eks.amazonaws.com/docs/clustermgmt/etcd-backup-restore/bottlerocket-etcd-backup/) doc stored 2 container IDs for `ETCD_CONTAINER_ID` variable and the following ctr command to execute etcdctl failed with a cryptic error because of 2 container IDs instead of 1.
```
export ETCD_CONTAINER_ID=$(ctr -n k8s.io c ls | grep -w "etcd-io" | cut -d " " -f1)
ctr -n k8s.io t exec -t --exec-id etcd ${ETCD_CONTAINER_ID} etcdctl \
--endpoints=${ETCD_ENDPOINT} \
--cacert=/var/lib/etcd/pki/ca.crt \
--cert=/var/lib/etcd/pki/server.crt \
--key=/var/lib/etcd/pki/server.key \
snapshot save /var/lib/etcd/data/etcd-backup.db
```
*Description …

Update etcd backup restore doc cmd when grabbing etcd container id

---

pkg/providers/vsphere/validator.go
pkg/providers/vsphere/validator_test.go
test/framework/vsphere.go

https://github.com/aws/eks-anywhere-internal/issues/1636
Pass the full template path when validating template tags instead of just the name.

Use Full Template Path in Tag Validation

---

docs/content/en/docs/clustermgmt/cluster-upgrades/vsphere-and-cloudstack-upgrades.md
docs/content/en/docs/getting-started/baremetal/bare-spec.md
docs/content/en/docs/getting-started/cloudstack/cloud-spec.md
docs/content/en/docs/getting-started/nutanix/nutanix-spec.md
docs/content/en/docs/getting-started/optional/_index.md
docs/content/en/docs/getting-started/optional/cni.md
docs/content/en/docs/getting-started/optional/etcd.md
docs/content/en/docs/getting-started/optional/gitops.md
docs/content/en/docs/getting-started/optional/healthchecks.md
docs/content/en/docs/getting-started/optional/hostOSConfig.md
docs/content/en/docs/getting-started/optional/iamauth.md
docs/content/en/docs/getting-started/optional/oidc.md
docs/content/en/docs/getting-started/optional/proxy.md
docs/content/en/docs/getting-started/optional/registrymirror.md
docs/content/en/docs/getting-started/snow/snow-spec.md
docs/content/en/docs/getting-started/vsphere/vsphere-spec.md

Added a provider support matrix for optional configurations + update the supported optional configs on the provider-specific pages

Update docs for provider support of optional configurations

---

Makefile
build/lib/validate_bundle_numbers.sh

When cutting new releases it can be challenging to get the correct version/bundle numbers since they exists across release branches.  This helps validate the choices that the release manager has made by checking against the upstream releases file.
Modified trigger files locally and ran various combos.
None
Presubmits: https://github.com/aws/eks-anywhere-prow-jobs/pull/349

adds validate triggers script for bundles and versions

---

docs/content/en/docs/osmgmt/artifacts.md

Adding instructions to add `wget` to extra_rpms/debs for packer plugin goss to succeed at pulling the goss binary using proxy. Goss plugin doesn support adding proxy env vars to curl arguments and tries with wget if curl fails. Since wget by default read proxy env vars, adding wget to the OS will enable goss pluging to downlod goss and progress with image building.
/approve
/cherrypick release-0.18

[Docs] Add wget when using proxy-enabled env for image building

---

release/cli/pkg/assets/config/bundle_release.go
release/cli/pkg/test/testdata/main-bundle-release.yaml
release/cli/pkg/test/testdata/release-0.18-bundle-release.yaml

Add image repo prefix field for AWS upgrader project to fix the constructed URI for images in the `aws/upgrader` repository.

Add image repo prefix field for AWS upgrader project

---

pkg/providers/cloudstack/reconciler/reconciler_test.go
pkg/providers/docker/reconciler/reconciler_test.go
pkg/providers/snow/reconciler/reconciler_test.go
pkg/providers/tinkerbell/reconciler/reconciler_test.go
pkg/providers/vsphere/reconciler/reconciler_test.go

Code refactoring for unit tests. 

Make kcp and object of reconciler struct for different provider unit test

---

test/e2e/airgap.go
test/e2e/tinkerbell_test.go

TestTinkerbellAirgappedKubernetes128BottleRocketRegistryMirror
TestTinkerbellAirgappedKubernetes128BottlerocketProxyConfigFlow
TestTinkerbellAirgappedKubernetes128UbuntuProxyConfigFlow
Above e2e tests always used to download 1.24 kube version image and/or used to fail with below error,
`
❌ Validation failed	{"validation": "tinkerbell Provider setup is valid", "error": "missing kube version from OSImageURL: url=http://10.80.18.122:8080/bottlerocket.img.gz, version=1.28", "remediation": ""}
`
This PR fixes this issue. 

Fix tinkerbell airgapped e2e tests

---

release/cli/cmd/release.go
release/cli/pkg/bundles/package-controller.go
release/cli/pkg/images/images.go
release/cli/pkg/operations/upload.go
release/cli/pkg/types/types.go
release/scripts/bundle-release.sh
release/scripts/release.sh

Sign container images using AWS Signer profile and Notation CLI.

Sign container images using AWS Signer and notation CLI.

---

release/cli/pkg/aws/s3/s3.go
release/cli/pkg/bundles/bundles.go

The PR improves the logic to get the short Kubernetes version (`major.minor`) for the bundle manifest. The previous method strictly allowed the input full Kubernetes version to have only upto three fields, i.e., `major.minor.patch`, while the new logic doesn't have this restriction.

Fix short Kubernetes version in bundle manifest

---

controllers/cluster_controller.go
controllers/cluster_controller_test.go

This PR adds logic to consider the status of the `DefaultCNIConfiguredCondition` in the overall `Cluster` status `Ready` condition. However, it is only considered in the computation of the `Ready` status when the reason for  `DefaultCNIConfiguredCondition` not being ready is `SkipUpgradesForDefaultCNIConfigured`, which is used when skipUpgrades is enabled for the default cni.
- Created workload cluster using API
- Upgraded workload cluster from 1.27 to 1.28 using API
- Created workload cluster using CLI
- Upgraded workload cluster from 1.27 to 1.28 using CLI (using kindless upgrades) …

Consider DefaultCNIConfiguredCondition in Ready condition except when Skip Upgrades is enabled

---

pkg/providers/cloudstack/controlplane_test.go
pkg/providers/cloudstack/testdata/cluster_main.yaml
pkg/providers/cloudstack/testdata/cluster_main_with_cp_node_labels.yaml
pkg/providers/cloudstack/testdata/cluster_main_with_node_labels.yaml
pkg/providers/cloudstack/testdata/expected_results_main_autoscaling_md.yaml
pkg/providers/cloudstack/testdata/expected_results_main_cp.yaml
pkg/providers/cloudstack/testdata/expected_results_main_md.yaml
pkg/providers/cloudstack/testdata/expected_results_main_no_machinetemplate_update_cp.yaml
pkg/providers/cloudstack/testdata/expected_results_main_no_machinetemplate_update_md.yaml
pkg/providers/cloudstack/testdata/expected_results_main_node_labels_cp.yaml
pkg/providers/cloudstack/testdata/expected_results_main_node_labels_md.yaml
pkg/providers/cloudstack/testdata/expected_results_resourceids_cp.yaml
pkg/providers/cloudstack/validator.go
pkg/providers/cloudstack/validator_test.go

Template name field in each cloudstack machine object should contain Cluster object's kubernetes version and/or worker machine's kubernetes version.
Simple Upgrade:
Modular Upgrade:

Check for k8s version in the Cloudstack template name

---

docs/content/en/docs/getting-started/docker/_index.md
docs/content/en/docs/getting-started/install/_index.md

This fix the docs to show that eks now supports apple and arm processor. 
related issue https://github.com/aws/eks-anywhere/issues/182

fix: docs to show apple and arm support

---

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml
docs/content/en/docs/getting-started/optional/cni.md
internal/pkg/api/cluster.go
pkg/api/v1alpha1/cluster_types.go
pkg/networking/cilium/templater.go
pkg/networking/cilium/templater_test.go

Fixes  #3182
*Description of changes:* This adds two routing modes for CIlium to use in the CNI configuration. Tunneled keeps the default geneve tunnel mode.
Direct adds a no tunnel mode with native as routing mode
*Documentation added/planned (if applicable):* Added a part explaining the option and linking to Cilium documentation to the `cni.md` file.

Add a RoutingMode option to cniConfig

---

docs/content/en/docs/clustermgmt/networking/networking-and-security.md

*Description of changes:* Added Cilium features (EKS Anywhere, Open Source, and Cilium Enterprise) to the docs. The content is taken from the [Cilium in EKS Anywhere](https://isovalent.com/blog/post/cilium-eks-anywhere/#h-feature-availability) blog. This PR replaces [PR #5059](https://github.com/aws/eks-anywhere/pull/5059).

Add Cilium Features to docs

---

Makefile

N/A
Fixing linting errors now requires every developer to find the correct golangci incantation to resolve an issue.
By adding the --fix flag to the lint make target we automatically resolve most errors for developers.
```
make lint-fix
```
N/A

Automatically Fix Linting Issues

---

release/cli/cmd/release.go
release/cli/pkg/bundles/package-controller.go
release/cli/pkg/images/images.go
release/cli/pkg/operations/bundle_release.go
release/cli/pkg/operations/upload.go

Sign container images using shasum256 image digest(@sha256:...) instead of using image tag(:latest).
notation sign registry/repository@<sha256:shasum> --plugin com.amazonaws.signer.notation.plugin --id <signer_profile_arn>

Sign container images with notation CLI with image digest instead of image tag

---

docs/Makefile
docs/content/en/docs/clustermgmt/etcd-backup-restore/bottlerocket-etcd-backup.md
docs/content/en/docs/clustermgmt/etcd-backup-restore/ubuntu-rhel-etcd-backup.md

The v3.5.0 release of etcd saw the introduction of a new command-line tool called `etcdutl` that took over the snapshot/restore/backup functionalities of `etcdctl`. Hence, from etcd version v3.5.0, using `etcdctl` for creating and restoring snapshots is deprecated and using this command displays a deprecation warning which suggests to use `etcdutl` tool instead. This PR updates the docs to do the same based on etcd version. The `etcdutl` snapshot and restore commands are essentially drop-in replacements for their `etcdctl` counterparts.

Advocate using `etcdutl` instead of `etcdctl` for backup and restore

---

release/cli/cmd/release.go

Skip signing images and enable it after we resolve maximum artifacts limit issue on Public ECR

Skip signing images for now

---

Makefile
cmd/eksctl-anywhere/cmd/version.go
pkg/manifests/releases/read.go
pkg/version/version.go

The EKS Anywhere deliverables include not just the CLI but also a bundle of artifacts used to bring up a working EKS-A cluster. There have been many cases where EKS-A customers want to know what bundle will be used by default in the cluster creation. In our docs, we have some steps to get the bundle manifest associated with an EKS-A release but this requires the customer to download additional tools like `yq`. Most customers find this only when running cluster operations but only when verbose logging is enabled, which is not ideal. Instead of all this, we can present them this info as an output in the `eksctl anywhere version` command, with an optional output flag to print in json. This will also send the message that the bundle is as much a part of EKS-A as the CLI. This is analogous to …

Add bundle manifest URL to EKS-A version command

---

test/e2e/certmanager.go
test/framework/cluster.go

N/A
Prior to this PR, cert-manager package end to end tests were failing with the following error:
```
Exceeded limit on number of multi-record answer RRSets _acme-challenge.<domain>
```
This PR should permanently fix the issue they were running into.
For context, when cert-manager provisions a certificate signed by Let's Encrypt it needs a DNS provider
to create a TXT record to verify control of the domain.
We use Route53 for this purpose.
However, Route53 has a service limit of 100 records per-domain within a zone.
The cert-manager packages tests were not cleaning up their Route53 entries, and so it was filling up and hitting the service quota.
By deleting the let's encrypt cert and allowing the cert-manager controller to cleanup …

Cleanup E2E Let's Encrypt TXT Records

---

test/e2e/docker_test.go

Ran locally, the test passes, the test currently fails in CI with the following error:
```
=== RUN   TestDockerKubernetes127AirgappedUpgradeFromLatestRegistryMirrorAndCert
envars.go:10: Required env var [T_PRIVATE_REGISTRY_MIRROR_ENDPOINT] not present
--- FAIL: TestDockerKubernetes127AirgappedUpgradeFromLatestRegistryMirrorAndCert (15.68s)
FAIL
DONE 1 tests, 1 failure in 15.975s
```
Even after being updated to use the proper environment variables private registry mirror, and running it against the CI env, it fails with the following:
```
=== RUN   TestDockerKubernetes127AirgappedUpgradeFromLatestRegistryMirrorAndCert
registry_mirror.go:101: error logging into docker registry 196.18.89.98:443: Error response from daemon: Get …
```

Update docker airgap upgrade from latest minor releast test to use non-authenticated registry mirror

---

pkg/providers/nutanix/config/cp-template.yaml
pkg/providers/nutanix/template.go
pkg/providers/nutanix/template_test.go
pkg/providers/nutanix/testdata/expected_cluster_api_server_cert_san_domain_name.yaml
pkg/providers/nutanix/testdata/expected_cluster_api_server_cert_san_ip.yaml
pkg/providers/nutanix/testdata/expected_results_additional_categories.yaml
pkg/providers/nutanix/testdata/expected_results_iamauth.yaml
pkg/providers/nutanix/testdata/expected_results_irsa.yaml
pkg/providers/nutanix/testdata/expected_results_node_taints_labels.yaml
pkg/providers/nutanix/testdata/expected_results_oidc.yaml
pkg/providers/nutanix/testdata/expected_results_project.yaml
pkg/providers/nutanix/testdata/expected_results_proxy.yaml
pkg/providers/nutanix/testdata/expected_results_registry_mirror.yaml

Add audit log to Nutanix control plane template
- add extra args for audit logs
- add required extra volumes
- change test manifests
*Testing:*
**Ubuntu 20.04 K8S 1.27:**
```
$ eksctl anywhere create cluster -f ntnx-audit-log.yaml --bundles-override ./local-bundle-release.yaml
odd number of arguments passed as key-value pairs for logging	{"ignored key": "ntnx-audit-log"}
ValidateClusterSpec for Nutanix datacenter
✅ Nutanix Provider setup is valid
✅ Validate OS is compatible with registry mirror configuration
✅ Validate certificate for registry mirror
✅ Validate authentication for git provider
✅ Validate cluster's eksaVersion matches EKS-A version
...
GitOps field not specified, bootstrap flux skipped
Writing cluster config file …
```

Add audit log to Nutanix control plane template

---

pkg/providers/nutanix/config/cp-template.yaml
pkg/providers/nutanix/template.go
pkg/providers/nutanix/template_test.go
pkg/providers/nutanix/testdata/expected_results_additional_categories.yaml
pkg/providers/nutanix/testdata/expected_results_iamauth.yaml
pkg/providers/nutanix/testdata/expected_results_irsa.yaml
pkg/providers/nutanix/testdata/expected_results_node_taints_labels.yaml
pkg/providers/nutanix/testdata/expected_results_oidc.yaml
pkg/providers/nutanix/testdata/expected_results_project.yaml
pkg/providers/nutanix/testdata/expected_results_proxy.yaml
pkg/providers/nutanix/testdata/expected_results_registry_mirror.yaml

This is a manual cherry pick of https://github.com/aws/eks-anywhere/pull/7190 to release-0.18 branch.
Add audit log to Nutanix control plane template
- add extra args for audit logs
- add required extra volumes
- change test manifests
Fixed comments and missed unit test
```
#	pkg/providers/nutanix/config/cp-template.yaml
#	pkg/providers/nutanix/testdata/expected_cluster_api_server_cert_san_domain_name.yaml #	pkg/providers/nutanix/testdata/expected_cluster_api_server_cert_san_ip.yaml
```

Add audit log to Nutanix control plane template (#7190)

---

test/e2e/airgap.go

This PR adds a step to the test changes the security group of the EC2 instance back to the default security group. Otherwise, despite a successful run, uploading the test report will fail and so will the code build at the end of the test

Add change security group to default at the end of docker airgapped upgrade from release test

---

pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/cluster_test.go
pkg/api/v1alpha1/cluster_types.go
pkg/api/v1alpha1/cluster_webhook.go
pkg/api/v1alpha1/nodeupgrade_types.go
pkg/clustermanager/cluster_manager.go
pkg/clustermanager/cluster_manager_test.go
pkg/workflows/interfaces/interfaces.go
pkg/workflows/interfaces/mocks/clients.go

The unification of the controller and CLI requires the ability to create mgmt clusters via the controller. However, we should only allow this creation when it's initiated by the CLI. 
Modifies webhook create validations to return an error for self-managed clusters only if the managed-by-cli annotation is not present. 
Manually created mgmt clusters with CLI (both old and new workflows) and FLC. 

Allow mgmt create via controller if managed by cli

---

release/cli/cmd/release.go
release/cli/pkg/operations/bundle_release.go

We have added a feature to sign all the container images using AWS Signer and Notation CLI. Notation signs the images again even if the image is already signed which causes an issue in the particular public ECR repository and ran into maximum number of artifacts issue. 
With this PR, we have added a check to see if the image with particular digest is not signed then only sign the image.

Verify image signature and skip signing if already signed

---

config/crd/bases/anywhere.eks.amazonaws.com_controlplaneupgrades.yaml
controllers/controlplaneupgrade_controller.go
controllers/controlplaneupgrade_controller_test.go
controllers/nodeupgrade_controller.go
pkg/api/v1alpha1/controlplaneupgrade_types.go

Add CP uprgader controller logic that is responsible for scheduling node upgrade objects for all control plane nodes. Tested the  controller by manually applying the CP upgrade object.

Add CP upgrade reconciler logic

---

config/crd/bases/anywhere.eks.amazonaws.com_machinedeploymentupgrades.yaml
config/manifest/eksa-components.yaml
controllers/controlplaneupgrade_controller.go
controllers/machinedeploymentupgrade_controller.go
controllers/machinedeploymentupgrade_controller_test.go
controllers/nodeupgrade_controller.go
pkg/api/v1alpha1/machinedeploymentupgrade_types.go
pkg/nodeupgrader/testdata/expected_first_control_plane_upgrader_pod.yaml
pkg/nodeupgrader/testdata/expected_rest_control_plane_upgrader_pod.yaml
pkg/nodeupgrader/testdata/expected_worker_upgrader_pod.yaml
pkg/nodeupgrader/upgrader.go

Adding logic to reconcile MachineDeploymentUpgrade objects. This performs upgrades on the nodes in place but using the upgrade script provided in the node upgrader controller image.
Tilt with upgrader image. I observed the workers upgrade from 1.27 to 1.28

Add reconcile logic for MD Upgrade controller

---

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/docker-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/nutanix-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/snow-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/tinkerbell-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml

In the E2E pipelines, the build stage builds all the binaries required for the tests and then passes them through to the test stage, so they're available in test stage only when run through the pipeline. This also means you can't trigger E2E tests for individual providers since triggering the pipeline will make it run all the provider E2E tests. This PR allows them to be run standalone as a CodeBuild job by building the binaries _in situ_ in the test stage if the initiator is not CodePipeline.

Allow E2E tests for individual providers to be kicked off from CodeBuild

---

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml

The Cloudstack tests are all currently skipped due to the wrong indendation in the `pre_build` commands. Fix the indendation to pass the commands as an array to the `pre_build` phase. 

Fix typo in Cloudstack buildspec

---

docs/content/en/docs/getting-started/_configuration/cluster_clusterNetwork.html
docs/content/en/docs/getting-started/baremetal/bare-spec.md
docs/content/en/docs/getting-started/cloudstack/cloud-spec.md
docs/content/en/docs/getting-started/nutanix/nutanix-spec.md
docs/content/en/docs/getting-started/optional/cni.md
docs/content/en/docs/getting-started/snow/snow-spec.md
docs/content/en/docs/getting-started/vsphere/vsphere-spec.md
docs/layouts/shortcodes/include.html

Direct routing was added as part of #3182. This adds the API documentation to providers as well as other missing documentation.

Add docs for routing mode

---

cmd/eksctl-anywhere/cmd/createcluster.go
cmd/eksctl-anywhere/cmd/upgradecluster.go
controllers/cluster_controller.go
controllers/cluster_controller_test.go
controllers/cluster_controller_test_test.go
pkg/validations/cluster.go
pkg/validations/cluster_test.go
pkg/validations/createvalidations/preflightvalidations.go
pkg/validations/createvalidations/preflightvalidations_test.go
pkg/validations/upgradevalidations/preflightvalidations.go
pkg/validations/upgradevalidations/preflightvalidations_test.go
pkg/validations/validation_options.go

Verify eksarelease exists on mgmt cluster

---

test/e2e/TINKERBELL_HARDWARE_COUNT.yaml
test/e2e/cloudstack_test.go
test/e2e/nutanix_test.go
test/e2e/snow_test.go
test/e2e/tinkerbell_test.go
test/e2e/vsphere_test.go

Add e2e tests related to control plane upgrade using full life cycle controller. 

Add e2e tests for CP management cluster upgrade

---

docs/Makefile
docs/content/en/docs/getting-started/baremetal/bare-prereq.md

Also update the NPM arg so we can run `make server`.

Add bare metal OS requirements

---

release/cmd/release.go
release/pkg/util/semver/semver.go

Backporting #7237 to release-0.18. Copying over the `semver` package methods instead of importing to avoid having to do the release module refactor to change the direction of imports between the main module and release submodule.

Update latest version only if semver is greater than previous latest

---

test/e2e/airgap.go
test/framework/registry_mirror.go

Currently, when a docker air-gapped e2e test fails, it does not reset the security group to default so outgoing commands fail. We have a few SSM commands run during [post test processing](https://github.com/aws/eks-anywhere/blob/b84f94b08010b5469927593473b36b4223071bbe/internal/test/e2e/run.go#L279), that timeout because the airgapped security group does not allow the outgoing connection. This increases the duration of the resulting codebuild  by at least 30 minutes (10 minute timeout per ssm command for`uploadJUnitReportFromInstance`, `uploadGeneratedFilesFromInstance` and `uploadDiagnosticArchiveFromInstance`). This PR adds a cleanup to docker air-gapped registry mirror e2e test, that resets the security group back to the default. This …

 Add cleanup to reset security group on aigrapped registry mirror docker tests

---

cmd/eksctl-anywhere/cmd/upgrademanagementcomponents.go
pkg/workflows/management/core_components.go
pkg/workflows/management/install_new_components.go
pkg/workflows/management/upgrade_management_components.go
pkg/workflows/management/upgrade_management_components_test.go

*Description of changes:* Add "upgrade management-components" subcommand to allow users to upgrade their management components in management cluster.
*Testing (if applicable):* Manual test against docker and cloudstack. 1) upgrade management-components 2) upgrade the field of eksaVersion of a cluster object and observed that the clusters have been upgraded correctly. Notes, there is an issue with cluster-api 1.6.0 upgrade that requires restarting cluster-api controller to make the upgrade successful.

Add upgrade management components cmd

---

docs/content/en/docs/osmgmt/artifacts.md

…ability
The document reflects outdated values/recommendations for --os-version (which is only applicable for Ubuntu).  The previous value 2004/2204 now needs to be 20.04/22.04
* `--os-version`: `2004` or `2204` (default: `2004`)
* `--os-version`: `20.04` or `22.04` (default: `20.04`)
This was discovered while attempting to create Bare Metal artifacts.
```
mansible@thekubernerd:~$ image-builder build --help | grep os-version
--os-version string          Operating system version to use for EKS-A node image. Can be 20.04 or 22.04 for Ubuntu or 8 for Redhat.
mansible@thekubernerd:~$ image-builder version
v0.3.1
```
By submitting this pull request, I confirm that you …

Change 2004/2204 to 20.04/22.04 for image-builder --os-version compat

---

docs/content/en/docs/getting-started/docker/_index.md

The method for installing the eksctl and associated commands is not secure as it creates a file in a system-wide directory owned by a user (user = whoever the person is logged in as).
Cleanup aligned with previous PR
https://github.com/aws/eks-anywhere/pull/5680
Instead of using mv (and chmod in some of the examples), use the "install" command with appropriate flags
ex - replace first line (mv) with the second (install)
sudo mv /tmp/eksctl /usr/local/bin/
sudo install -m 0755 /tmp/eksctl /usr/local/bin/eksctl
N/A - this is an upd ate, not an add.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

Improve Binary Installation Process for K8s Tools

---

.github/labeler.yml

Labeler had a few breaking changes in their latest release https://github.com/actions/labeler/releases/tag/v5.0.0.
Hence updating the yaml format.

Fixing labeler after version update

---

test/e2e/docker_test.go

*Testing (if applicable):* Manually invoked the new e2e test, and it passed.

Add e2e test for upgrading management-components

---

pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/cluster_test.go
pkg/validations/cluster.go
pkg/validations/cluster_test.go

*Issue #6418*
Currently when we configure ociNamespaces, we are free to setup any values for registry and namespace fields. But the main registry lookup we perform in our codebase expects an entry for `public.ecr.aws` when OS Family is bottlerocket.
Given a configuration like
```
ociNamespaces:
- registry: "docker.io"
namespace: "library"
```
This would be accepted and proceed with cluster creation but cause the template CP and MD to get an empty string for registry mirror endpoint since we do a lookup for `public.ecr.aws`, Example [template.go#L217]( https://github.com/aws/eks-anywhere/blob/main/pkg/providers/vsphere/template.go#L217).
Hence we are adding a preflight to validate and error when osFamily is bottlerocket and the supported registry is not found. …

Validate oci namespaces for BR registry mirror

---

docs/content/en/docs/getting-started/optional/registrymirror.md

*Issue #6418*
Adding more context around ociNamespaces field in registry mirror. Also added a warning to specific that `public.ecr.aws` is the only supported registry on bottlerocket at the moment.

Rewording ociNamespaces documentation and adding warning

---

docs/content/en/docs/clustermgmt/cluster-flux.md
docs/content/en/docs/clustermgmt/cluster-scale/baremetal-scale.md
docs/content/en/docs/clustermgmt/cluster-scale/cloudstack-scale.md
docs/content/en/docs/clustermgmt/cluster-scale/nutanix-scale.md
docs/content/en/docs/clustermgmt/cluster-scale/vsphere-scale.md

Fix WNGC field name in docs: `workerNodeGroupsConfiguration` -> `workerNodeGroupConfigurations`.

Fix WNGC field name in docs

---

docs/content/en/docs/getting-started/cloudstack/cloudstack-getstarted.md

The `CLOUDSTACK_DISABLE_KUBE_VIP` is optional and doesn't feature in a typical EKS-A deployment. This docs change moves the configuration to a separate optional section leaving the cluster creation steps to represent a typical EKS-A cluster deployment.

Rework docs for CloudStack KubeVIP disable env flag

---

cmd/eksctl-anywhere/cmd/deletecluster.go
cmd/eksctl-anywhere/cmd/upgrademanagementcomponents.go
pkg/cluster/load.go
pkg/clustermanager/cluster_manager.go
pkg/clustermanager/cluster_manager_test.go
pkg/gitops/flux/flux.go
pkg/gitops/flux/flux_test.go
pkg/providers/cloudstack/cloudstack_test.go
pkg/providers/tinkerbell/tinkerbell_test.go
pkg/providers/vsphere/template_test.go
pkg/providers/vsphere/vsphere_test.go
pkg/task/task_test.go
pkg/types/cluster.go
pkg/validations/upgradevalidations/versions.go
pkg/workflows/create.go
pkg/workflows/create_test.go
pkg/workflows/delete.go
pkg/workflows/delete_test.go
pkg/workflows/management/upgrade_management_components_test.go
pkg/workflows/upgrade.go
pkg/workflows/upgrade_test.go
test/e2e/certmanager.go
test/e2e/curatedpackages.go

The function of this field was unclear and its name was confusing to say
the least. It seems like we now have a better way to achieve the same
thing and the resulting code is simpler and more expressive.

Remove ExistingManagement field from Cluster type

---

docs/content/en/docs/whatsnew/changelog.md

Add change log for patch 18.4

---

pkg/api/v1alpha1/cluster_webhook.go
pkg/api/v1alpha1/cluster_webhook_test.go
pkg/validations/upgradevalidations/immutable_fields.go
pkg/validations/upgradevalidations/preflightvalidations_test.go
test/e2e/cloudstack_test.go
test/e2e/docker_test.go
test/e2e/vsphere_test.go

Add support for etcd scaling

---

release/cli/pkg/operations/bundle_release.go

Image signing logs are bunched up due to the `Printf` string missing a `\n`. This PR fixes that.

Improve logging of image signing operations

---

cmd/eksctl-anywhere/cmd/deletecluster.go
pkg/cluster/load.go
pkg/providers/tinkerbell/tinkerbell_test.go
pkg/providers/vsphere/vsphere_test.go
pkg/task/task_test.go
pkg/workflows/delete_test.go
test/e2e/certmanager.go
test/e2e/curatedpackages.go

Fix formatting

---

cmd/eksctl-anywhere/cmd/applypackages.go
cmd/eksctl-anywhere/cmd/createpackages.go
cmd/eksctl-anywhere/cmd/deletepackages.go
cmd/eksctl-anywhere/cmd/describepackages.go
cmd/eksctl-anywhere/cmd/generatehardware.go
cmd/eksctl-anywhere/cmd/generatepackage.go
cmd/eksctl-anywhere/cmd/getpackage.go
cmd/eksctl-anywhere/cmd/getpackagebundle.go
cmd/eksctl-anywhere/cmd/getpackagebundlecontroller.go
cmd/eksctl-anywhere/cmd/installpackages.go

The `Alias` field in the Cobra cmd data structure should only include alias', not the actual command.

Remove redundant alias' from CLI cmds

---

config/manifest/eksa-components.yaml
config/rbac/role.yaml
controllers/cluster_controller.go

*Issue #, if available:* helm silently ignored the error of updating its secret.
*Description of changes:* "helm upgrade" invoked by the eksa reconciler  returns nil error, but in fact the release's status stuck at "pending-installation" as it fails to update the release status stored in secret.
Error is shown when "--debug" option is turned on for 'helm upgrade' command
```
sh.helm.release.v1.eks-anywhere-packages-workload-0.v1" is forbidden: User "system:serviceaccount:eksa-system:eksa-controller-manager" cannot update resource "secrets" in API group "" in the namespace "eksa-packages"
```
*Testing (if applicable):* 1. Manually reproduced the error with `kubectl exec eksa-controller helm ...." 2. Verified the issue is fixed when the missing permission is added manually.
*Documentation …

Add permission used by helm to update its secret

---

controllers/controlplaneupgrade_controller_test.go
controllers/machinedeploymentupgrade_controller_test.go
controllers/nodeupgrade_controller.go
controllers/nodeupgrade_controller_test.go
internal/test/cluster.go
pkg/clustermanager/cluster_manager.go
pkg/clustermanager/cluster_manager_test.go
pkg/clustermanager/mocks/client_and_networking.go
pkg/constants/constants.go
pkg/executables/kubectl.go

The eks-a controller will be responsible for creating the custom CP/MD upgrade resources for in-place upgrades. We need a way to fetch the upgrader image from the bundle so this adds methods that will be used in the controller to pull the bundle and fetch the images. The images will be stored in a config map. This upgrader config map will then be fetched by the node upgrader when the image is needed.
ConfigMap:
```
apiVersion: v1
data:
v1.25.16-eks-1-25-29: public.ecr.aws/l0g8r8j6/aws/upgrader:v1-25-29-eks-a-v0.0.0-dev-build.8103
v1.26.11-eks-1-26-25: public.ecr.aws/l0g8r8j6/aws/upgrader:v1-26-25-eks-a-v0.0.0-dev-build.8103
v1.27.8-eks-1-27-19: public.ecr.aws/l0g8r8j6/aws/upgrader:v1-27-19-eks-a-v0.0.0-dev-build.8103
v1.28.4-eks-1-28-12: …
```

Add methods to fetch upgrader image from bundle

---

test/e2e/constants.go
test/framework/cloudstack.go
test/framework/nutanix.go
test/framework/snow.go
test/framework/tinkerbell.go
test/framework/vsphere.go

Remove unused 1.23 and 1.24 methods from testing code.

Remove unused 1.23 and 1.24 methods from testing code

---

test/framework/cluster.go

Fix ADOT flaky test by checking the curl output instead of looking for logs that are causing race conditions.

Fix ADOT flaky test

---

test/framework/cluster.go

This reverts commit 4495d29ce273e2deab76e29ca93098b77ecc738f.
Revert "Fix ADOT flaky test (#7332)"

Revert "Fix ADOT flaky test (#7332)"

---

pkg/executables/kubectl.go
pkg/executables/kubectl_test.go
test/framework/cluster.go

We use `curl` commands to validate the curated packages installations in E2E tests. The default command used is just `curl <endpoint>`, but this was changed to `curl -I <endpoint>` (which gets only curl headers) in #7332 for fixing ADOT tests, which caused other packages to fail since they expect output present in the full `curl` output. This PR allows to pass in custom  `curl` options to the `ValidateCurlEndpoint` method so that each package can customize how the `curl` command is run.

Allow adding extra curl args while keeping default behavior

---

pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/cluster_test.go
pkg/providers/tinkerbell/assert.go
pkg/providers/tinkerbell/tinkerbell_test.go
pkg/providers/tinkerbell/validate.go

This adds the option for InPlace upgrade rollout strategy type in EKS-A spec. We will update the KCP/MD objects in a separate PR

Add in place rollout strategy option

---

pkg/clusterapi/apibuilder.go
pkg/clusterapi/apibuilder_test.go
pkg/clusterapi/rollout_strategy.go
pkg/clusterapi/rollout_strategy_test.go
pkg/providers/snow/apibuilder_test.go
pkg/providers/snow/snow.go
pkg/providers/snow/snow_test.go
pkg/providers/snow/testdata/expected_results_main_cp_bottlerocket.yaml
pkg/providers/snow/testdata/expected_results_main_cp_ubuntu.yaml
pkg/providers/snow/testdata/expected_results_main_md_bottlerocket.yaml
pkg/providers/snow/testdata/expected_results_main_md_ubuntu.yaml
pkg/providers/snow/testdata/expected_results_main_md_ubuntu_worker_version.yaml

Issue #, if available:
https://github.com/aws/eks-anywhere/issues/6719
Adding UpgradeRolloutStrategy knobs for workers and control plane to snow provider.
Updated cluster api apibuilder as well since this should be available for all providers. Other providers use templater, while snow uses apibuilder.
Updated unit tests.
Documentation added/planned (if applicable):
Planning on adding docs on knobs for other providers following the [Tinkerbell upgrade strategy format](https://anywhere.eks.amazonaws.com/docs/clustermgmt/cluster-upgrades/baremetal-upgrades/#upgraderolloutstrategy).

adding snow and cluster api upgrade rollout strategy

---

docs/content/en/docs/getting-started/nutanix/nutanix-spec.md

N/A
Update of the nutanix-spec.md to include "IAM Roles for Service Accounts" configuration
N/A
Update of the nutanix-spec.md to include "IAM Roles for Service Accounts" configuration

Add IAM Roles for Service Accounts to nutanix-spec.md doc

---

config/manifest/eksa-components.yaml
config/rbac/role.yaml
controllers/nodeupgrade_controller.go

Use r.client to always fetch from mgmt cluster. Add rbac for config maps in node upgrade controller.
tilt

Fetch config map from management cluster

---

test/framework/cloudstack.go

[#2001](https://github.com/aws/eks-anywhere-internal/issues/2001)
- Fix e2e test failure by adding the newly defined test env variables to the required env variables to export them in the ec2 instances launched for running tests
- Tested locally in dev and CI env

Add e2e test new env variables to required env variables

---

docs/content/en/docs/osmgmt/artifacts.md

The process to "install" the image-builder binary was not a best-practice.  Updated to reflect best-practice (aligned with PR# 5680 https://github.com/aws/eks-anywhere/pull/5680
replace
sudo cp ./image-builder /usr/local/bin
with
sudo install -m 0755 ./image-builder /usr/local/bin/image-builder
Also provided an advisory regarding where to run the image-builder process
However, see [Building node images]({{< relref "#building-node-images">}}) for information on how to build EKS Anywhere images from those Linux distributions.  Note:  if you utilize your Admin Host to build images, you will need to review  the DHCP integration provided by Libvirtd and ensure it is disabled.  If the Libvirtd DHCP is enabled, the "boots container" will detect …

Updated image-builder install.  Add warning about host to run builder

---

controllers/controlplaneupgrade_controller.go
controllers/controlplaneupgrade_controller_test.go
controllers/nodeupgrade_controller.go
controllers/nodeupgrade_controller_test.go

In-place upgrades directly upgrades the K8s components outside of the capi upgrade flow. This requires updating the K8s version on the capi objects once the in-place upgrade has been done to reflect the updated k8s version on the node. This change updates the K8s version on the capi machine once the nodeupgrader object has completed the upgrade on the node associated with the corresponding capi machine for the controlplane nodes. 
Manually tested with updating the KCP controller image with one that accommodates InPlace as upgrade strategy type.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

Update K8s version on Capi machine for in-place upgrades

---

pkg/executables/builder.go

Update CLI tools image to latest dev version for E2E tests.

Update CLI tools image to latest dev version

---

pkg/git/gitclient/gitclient.go

We updated the go-git version which now returns an error on commits with no changes. Adding this new commit option to keep our same behavior. See more here:
https://github.com/go-git/go-git/pull/623

Allow empty commits with GoGit update

---

pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/cluster_test.go
pkg/api/v1alpha1/testdata/cluster_valid_taints_workload_cluster.yaml
test/e2e/docker_test.go
test/e2e/multicluster.go
test/e2e/vsphere_test.go

[#1527](https://github.com/aws/eks-anywhere-internal/issues/1527)
The requirement that at least one worker node group must not have NoSchedule and NoExecute taints is only applicable to management clusters. This PR updates the validation to only apply to management clusters
added unit and docker/vsphere e2e tests. Tests run locally
Troubleshooting documentation previously added

updating taint validation to management cluster only

---

config/manifest/eksa-components.yaml
config/rbac/role.yaml
controllers/controlplaneupgrade_controller_test.go
controllers/factory.go
controllers/factory_test.go
controllers/kubeadmcontrolplane_controller.go
controllers/kubeadmcontrolplane_controller_test.go
manager/main.go
pkg/constants/constants.go

Adding a new controller for KCP to reconcile changes based on seeing the in place upgrade annotation. This would be a temporary controller until we implement runtime webhooks, removing the need for this annotation from cluster api. This will create a ControlPlaneUpgrade object when this annotation is detected and delete it after it sees that it has completed.
unit and functional testing

Add in-place upgrade controller for kcp

---

test/e2e/cloudstack_test.go
test/framework/cloudstack.go

Add rhel 9 simpleflow, upgrade and rhel8 to rhel9 upgrade tests for all kubernetes versions

Add initial set of cloudstack redhat 9 tests

---

release/cli/cmd/release.go
release/cli/pkg/operations/bundle_release.go

Move image signing feature to staging release and copy signatures from staging to prod account during prod bundle release.

Move image signing to staging release and copy sinatures from staging to prod account

---

config/crd/bases/anywhere.eks.amazonaws.com_controlplaneupgrades.yaml
config/manifest/eksa-components.yaml
controllers/controlplaneupgrade_controller.go
controllers/controlplaneupgrade_controller_test.go
controllers/kubeadmcontrolplane_controller.go
controllers/kubeadmcontrolplane_controller_test.go
pkg/api/v1alpha1/controlplaneupgrade_types.go

Add `ControlPlaneSpec` field in CPUpgrade which will store the base64 encoded KCP.Spec
This field is needed to update the CAPI objects to the desired state so CAPI and KCP controllers can determine that the in-place upgrade is complete.
This PR also uses this field to update the control plane machine annotation `controlplane.cluster.x-k8s.io/kubeadm-cluster-configuration` with the updated kubeadmClusterConfig.
This new field is needed because if we try to fetch the kcp.spec from the controlPlane ref, we get a dynamic copy of the the spec. It's possible that the KCP object was modified after the `ControlPlaneUpgrade` object was created. In cases like this, we need a static copy of KCP.Spec so we can update the relevant objects with the KCP.Spec values that were …

Add controlplane spec field in CPUpgrade

---

docs/content/en/docs/clustermgmt/cluster-upgrades/vsphere-and-cloudstack-upgrades.md

Part of https://github.com/aws/eks-anywhere/issues/6719
We do have docs on maxSurge and maxUnavailable Rollout strategy for baremetal providers. Updating the doc for rest all the providers since we have added support the same.

Document maxSurge and maxUnavailable Rollout strategy for all the providers

---

pkg/cluster/fetch.go
pkg/cluster/fetch_test.go
pkg/providers/docker/docker.go
pkg/providers/docker/docker_test.go

This PR extends the docker provider api surface to use management component to gradually introduce the changes outlined in [this PR](https://github.com/aws/eks-anywhere/pull/7353), split out into multiple. This is the first one.

  Extend docker provider api surface to use management components

---

pkg/providers/cloudstack/cloudstack.go
pkg/providers/cloudstack/cloudstack_test.go

This PR extends the cloudstack provider api surface to use management component to gradually introduce the changes outlined in https://github.com/aws/eks-anywhere/pull/7353, split out into multiple. This is the second one

Extend cloudstack providers api to use management components

---

pkg/providers/vsphere/vsphere.go
pkg/providers/vsphere/vsphere_test.go

This PR extends the vsphere provider api surface to use management component to gradually introduce the changes outlined in https://github.com/aws/eks-anywhere/pull/7353, split out into multiple.

Extend vsphere provider api surface to use  management component

---

pkg/providers/tinkerbell/tinkerbell.go
pkg/providers/tinkerbell/tinkerbell_test.go

This PR extends the tinkerbell provider api surface to use management component to gradually introduce the changes outlined in https://github.com/aws/eks-anywhere/pull/7353, split out into multiple.

Extend tinkerbell provider api surface to use  management components

---

pkg/workflows/management/create_bootstrap.go
pkg/workflows/management/create_install_capi.go
pkg/workflows/management/create_test.go

The original https://github.com/aws/eks-anywhere/pull/7110 is being split into smaller PRs. This PR is to install CAPI on bootstrap cluster.
- unit tests

Install CAPI task for controller via CLI

---

pkg/providers/nutanix/provider.go
pkg/providers/nutanix/provider_test.go

This PR extends the nutanix provider api surface to use management component to gradually introduce the changes outlined in https://github.com/aws/eks-anywhere/pull/7353, split out into multiple.

Extend nutanix  provider api surface to use  management components

---

release/cli/pkg/assets/config/bundle_release.go
release/cli/pkg/test/testdata/main-bundle-release.yaml

Fixing the issue of incorrect tagging of Nutanix cloud provider image.

Add image tag options for Nutanix cloud provider asset

---

pkg/api/v1alpha1/cluster_types.go
pkg/api/v1alpha1/cluster_types_test.go
pkg/cluster/fetch.go
pkg/cluster/fetch_test.go

This logic was split out from the following PR with some changes to use `ManagementComponents`: https://github.com/aws/eks-anywhere/pull/7353
The notable change since the PR above include the create of a new struct `ManagementComponents` struct to use instead of using the `VersionsBundle` directly, decoupling the rest the business logic that uses it from the API.
Adds logic to retrieve cluster.ManagementComponents from a cluster using a kubernetes client.
- Gets management components version or fallsback to cluster's `EksaVersion` for older clusters.
- Retrieves corresponding **EKSARelease** and **Bundles**
-  Builds **ManagementComponents** from **Bundles** and returns it.
*Documentation added/planned (if …

Add logic to get management components for cluster

---

pkg/workflows/management/upgrade_management_components_test.go
pkg/workflows/management/upgrade_test.go

This PR refactoring the management upgrade tests to use fake client. This is in response to the [PR](https://github.com/aws/eks-anywhere/pull/7353#discussion_r1465507677) comment here. This will make things a bit simpler when making more changes.

Refactor management upgrade tests to use fake client

---

config/manifest/eksa-components.yaml
config/rbac/role.yaml
controllers/controlplaneupgrade_controller.go
controllers/controlplaneupgrade_controller_test.go
controllers/kubeadmcontrolplane_controller_test.go
controllers/machinedeployment_controller_test.go
controllers/machinedeploymentupgrade_controller_test.go
controllers/nodeupgrade_controller_test.go

KCP controller expects `KubeadmConfig` corresponding to each control plane machine to match `KCP.Spec.KubeadmConfig` for a machine to be considered "UpToDate".
This PR updates the `KubeadmConfig` for each control plane machine as the in-place upgrade is done for that machine.

Update KubeadmConfig for cp machines when upgrade is complete

---

cmd/eksctl-anywhere/cmd/upgradeplancluster.go
pkg/clustermanager/cluster_manager.go
pkg/clustermanager/cluster_manager_test.go
pkg/clustermanager/eksa_installer.go
pkg/clustermanager/eksa_installer_test.go
pkg/clustermanager/mocks/client_and_networking.go
pkg/workflows/create.go
pkg/workflows/create_test.go
pkg/workflows/interfaces/interfaces.go
pkg/workflows/interfaces/mocks/clients.go
pkg/workflows/management/core_components.go
pkg/workflows/management/create_install_eksa.go
pkg/workflows/management/create_test.go
pkg/workflows/management/upgrade_management_components_test.go
pkg/workflows/management/upgrade_test.go
pkg/workflows/upgrade.go
pkg/workflows/upgrade_test.go

This changes here are split out from [this PR](https://github.com/aws/eks-anywhere/pull/7353) with some changes to use `ManagementComponents`. It also addresses [a particular comment](https://github.com/aws/eks-anywhere/pull/7353#discussion_r1465492542) by passing the ManagementComponents down to where it's need.
Updates the EKSA upgrader to use management components:
- Changes the EKSAChangeDiff method to compare management components
- Gets ManagementComponents for upgrade plan and uses it and the new management components to get the diff
- EKSA Upgrade uses management components to upgrade
- Ran upgrade plan to check the output
- Created a management cluster with v0.18.4 and ran upgrade plan to check the …

Change EKSA upgrader to use management components

---

pkg/workflows/management/create_install_eksa.go
pkg/workflows/management/create_test.go
pkg/workflows/management/create_workload.go

Create workload cluster controller via CLI
- unit test

Create workload cluster controller via CLI

---

test/e2e/docker_test.go
test/e2e/metallb.go

This should help with test failing due to taking too long. Now every k8s version will run in its own test, hence in a different instance.

Separate docker MetalLB e2e test to avoid timeouts

---

config/crd/bases/anywhere.eks.amazonaws.com_machinedeploymentupgrades.yaml
config/manifest/eksa-components.yaml
config/rbac/role.yaml
controllers/machinedeployment_controller_test.go
controllers/machinedeploymentupgrade_controller.go
controllers/machinedeploymentupgrade_controller_test.go
pkg/api/v1alpha1/machinedeploymentupgrade_types.go

Unlike KCP, machineDeployments use `machinesets` constructs which then are responsible for scaling the machines. During the regular flow for rolling upgrades, CAPI generates the updated machinesets based on the new spec, which then scales up new machines in the rolling fashion. Since for InPlace we do not want any new machines to roll over, we need to update the `machineset.Spec.Template.Spec`  to the current machine spec once the InPlace upgrade has been completed. This will ensure that the `machinesets` then syncs with the machines and updates the `Machine.Spec` field to reflect the current value on the `machinesets`. 
Tested manually using a custom `capi-controller` image built to handle InPlace and verified …

Update Template in MachineSet once InPlace upgrade is completed

---

config/manifest/eksa-components.yaml
config/rbac/role.yaml
controllers/controlplaneupgrade_controller.go
controllers/controlplaneupgrade_controller_test.go

Update the owned by annotation in the infra machine to match the name specified by the new kcp. This signifies to capi that a machine was rolled out due to it being an inplace upgrade.
unit testing and functional testing

Update infra machine annotation for cp in place upgrade

---

pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/cluster_test.go
pkg/api/v1alpha1/cluster_types.go
pkg/providers/tinkerbell/assert.go
pkg/providers/tinkerbell/assert_test.go
pkg/providers/tinkerbell/cluster.go
pkg/providers/tinkerbell/template.go
pkg/providers/tinkerbell/validate.go

This PR adds more validations for in place upgrades to ensure that:
- InPlace can only be specified for Tinkerbell provider with the Ubuntu OS family
- Cp and workers must have the same upgrade rollout strategy specified.
Unit tests

Add additional validations for in place upgrades

---

pkg/providers/vsphere/vsphere.go
pkg/providers/vsphere/vsphere_test.go

Update secrets for vsphere in Pre CAPI setup

Update secrets for vsphere in Pre CAPI setup

---

docs/content/en/docs/clustermgmt/verify-cluster-image.md
docs/content/en/docs/getting-started/baremetal/baremetal-getstarted.md
docs/content/en/docs/getting-started/cloudstack/cloudstack-getstarted.md
docs/content/en/docs/getting-started/nutanix/nutanix-getstarted.md
docs/content/en/docs/getting-started/snow/snow-getstarted.md
docs/content/en/docs/getting-started/vsphere/vsphere-getstarted.md

https://github.com/aws/eks-anywhere-internal/issues/1257
We are going to sign all the container images that we use using AWS CLI and notation CLI. Adding a doc on how to verify container images from the bundle manifest file.

Add doc on verifying container images from the bundle manifest file

---

pkg/workflows/management/create_delete_bootstrap.go
pkg/workflows/management/create_test.go
pkg/workflows/management/write_cluster_config.go

Delete bootstrap cluster for create management controller via CLI
- unit test

Delete bootstrap cluster for create management controller via CLI

---

docs/content/en/docs/clustermgmt/cluster-backup-restore/restore-cluster.md
docs/content/en/docs/clustermgmt/cluster-rebootnode.md
docs/content/en/docs/clustermgmt/etcd-backup-restore/bottlerocket-etcd-backup.md
docs/content/en/docs/clustermgmt/etcd-backup-restore/ubuntu-rhel-etcd-backup.md

Add instruction of workload cluster backup and restore

---

controllers/nodeupgrade_controller.go
pkg/nodeupgrader/testdata/expected_first_control_plane_upgrader_pod.yaml
pkg/nodeupgrader/testdata/expected_rest_control_plane_upgrader_pod.yaml
pkg/nodeupgrader/testdata/expected_worker_upgrader_pod.yaml
pkg/nodeupgrader/upgrader.go

This PR removes nginx container from the upgrader pod and replaces it with the upgrader container that prints out the status and performs cleanup.
Also sets the pod `restartPolicy` to never so the cleanup container doesn't try to restart every time and run into a crashloop backoff.

Remove nginx from upgrader pod

---

cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml

*Description of changes:* This new buildspec allow the test binary to run tests for all providers. And the additional build stage in the pipeline will be cleaned after this change. 
*Testing (if applicable):* Manually triggered the buildspec and verified the tests are invoked correctly.

Add quick test buildspec

---

cmd/eksctl-anywhere/cmd/upgradeplancluster.go
cmd/eksctl-anywhere/cmd/upgradeplanmanagementcomponents.go

[#2133
](https://github.com/aws/eks-anywhere-internal/issues/2133)
This PR adds an `upgrade plan management-components` subcommand, so that users may see the management components that would be upgraded when they run the new `upgrade management-components` subcommand.
**Created a management cluster with v0.18.4 and ran the follow checks**
*upgrade plan management-components on management cluster*
```
./bin/eksctl-anywhere upgrade plan management-components -f mgmt/mgmt-eks-a-cluster.yaml 
...
Checking new release availability...
NAME                 CURRENT VERSION   NEXT VERSION
EKS-A Management     v0.18.4+79b7f58   v0.0.0-dev+build.8277+49bcdf6
cert-manager         v1.13.0+343cf30   v1.13.2+a34c207 …
```

Add upgrade plan management-components subcommand

---

cmd/eksctl-anywhere/cmd/deletecluster.go
cmd/eksctl-anywhere/cmd/options.go
pkg/cli/deleteclusterdefaulter.go
pkg/cli/deleteclusterdefaulter_test.go
pkg/cluster/defaults.go
pkg/cluster/defaults_test.go
pkg/config/config.go
pkg/dependencies/factory.go
pkg/dependencies/factory_test.go

Adds a defaulter (for cluster namespace) in delete cluster command

Delete Cluster Defaulter

---

pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/cluster_test.go
pkg/features/features.go
pkg/features/features_test.go
pkg/providers/vsphere/config/template-cp.yaml
pkg/providers/vsphere/config/template-md.yaml
pkg/providers/vsphere/controlplane_test.go
pkg/providers/vsphere/template.go
pkg/providers/vsphere/workers_test.go

Adding a feature flag because we are using this provider to test in place upgrade changes, but it will only be supported on bare metal when the feature is initially released.
This PR also updates the vsphere capi specs to specify inplace if it is specified in the clusterspec
Unit test
Manual test for the validations step

Add feature flag for in place upgrades on vSphere

---

pkg/validations/runner.go
pkg/validations/runner_test.go
pkg/workflows/workload/create_test.go

This helps debugging since the validation errors are printed at the end of the program. Until now we only printed "validations failed" and the user needed to scroll through previous logs to find the different errors.

Aggregate validations errors in validator runner

---

test/framework/multicluster.go

Before, workload clusters added through the multicluster constructor had an already set config path that defaulted to the management cluster's config file. This meand workload cluster operations overwrote the same file.
---

Give e2e workload cluster config a unique name

---

docs/Makefile
docs/amplify.yml

[#1931](https://github.com/aws/eks-anywhere-internal/issues/1931)
Added a make target to compute the eks anywhere docs checksum from `public/index.html` and upload it to artifacts bucket with public access so that the docs canary can verify with the latest version
Tested locally in personal isengard account

Compute docs checksum and upload it to artifacts bucket

---

test/framework/cluster.go
test/framework/multicluster.go
test/framework/workload.go

The reading code was making assumptions about what the writing code did. This worked when the workload clusters were setup in a very specific way, but if custom folders were used, the assumptions were broken and the test can't find the kubeconfig file.
---

Fix e2e tests to search the kubeconfig consistently

---

cmd/eksctl-anywhere/cmd/upgradeplancluster.go
pkg/eksd/upgrader.go
pkg/eksd/upgrader_test.go
pkg/workflows/interfaces/interfaces.go
pkg/workflows/interfaces/mocks/clients.go
pkg/workflows/management/core_components.go
pkg/workflows/management/upgrade_management_components_test.go
pkg/workflows/management/upgrade_test.go
pkg/workflows/upgrade.go
pkg/workflows/upgrade_test.go

This changes here are split out from #7353 with some changes, passing the `ManagementComponents` object down to where it's needed to make comparisons.
Adds "kubernete" change entry as a cluster component to the upgrade plan:
- Change messaging  and interface of the EKSD upgrader to less confusing as to what it does: updates eks-d crds, not upgrading eks-d from one version to another.
- Remove types.ChangeDiff as a return from the EKSDUpgrader interface because it's unneeded.
- Created management cluster with v0.18.4 and check upgrade plan output
- Upgrade management-components and check the output upgrade plan
Before upgrade management-components
```
NAME                 CURRENT VERSION       NEXT VERSION
... …
```

Add kubernetes entry to upgrade plan

---

pkg/providers/mocks/providers.go
pkg/providers/provider.go
pkg/providers/snow/snow.go
pkg/providers/snow/snow_test.go

This PR extends the snow provider api surface to use management component to gradually introduce the changes outlined in https://github.com/aws/eks-anywhere/pull/7353, split out into multiple. 
After extending all the providers, we also now update the `Provider` interface with the new methods

Extend Snow provider surface API to use management components

---

.github/workflows/go-coverage.yml
.github/workflows/golangci-lint.yml

There are several automated PRs to the repo that update attribution text files or other YAML files that are not part of the source code. But we still run linter and test coverage on them which sometimes fails on unrelated issues and causes churn. This PR scopes down the `lint` Github action to only PRs containing Go code, and the test coverage Github action to only the code outside the `release` submodule.

Scope down lint and test coverage GitHub workflows on PRs

---

test/framework/cluster.go
test/framework/multicluster.go

Another bug discovered by changing the cluster name on the fly. The folder for the cluster config is not created on the fly.
I ran a new e2e test i wrote that hits this scenario.

Create config folder when update name in e2e test

---

pkg/clusterapi/upgrader.go
pkg/clusterapi/upgrader_test.go
pkg/executables/clusterctl.go
pkg/executables/clusterctl_test.go
pkg/providers/cloudstack/cloudstack.go
pkg/providers/cloudstack/cloudstack_test.go
pkg/providers/docker/docker.go
pkg/providers/docker/docker_test.go
pkg/providers/mocks/providers.go
pkg/providers/nutanix/provider.go
pkg/providers/nutanix/provider_test.go
pkg/providers/provider.go
pkg/providers/snow/snow.go
pkg/providers/snow/snow_test.go
pkg/providers/tinkerbell/tinkerbell.go
pkg/providers/tinkerbell/tinkerbell_test.go
pkg/providers/vsphere/vsphere.go
pkg/providers/vsphere/vsphere_test.go

Review #7462 first for a focused change.
The following changes and method are to split out the corresponding changes from the original PR [here](https://github.com/aws/eks-anywhere/pull/7353), without introducing bugs.
This is final step in refactoring the providers to use *cluster.ManagementComponents to reference management components. After expanding provider apis (#7376, #7390, #7391, #7393, #7395, and #7457), and using the new ones. We are now contracting the provider apis, removing the old methods and renaming the new ones.
This PR replaces the old:
- Deleted all the old `GetInfrastructureBundle(..)`, `Version(..)`, and `ChangeDiff(..)` methods
- Renamed the corresponding `*FromManagementComponents(..)` methods to the what they were …

Remove old provider methods to use new methods with management components

---

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml
config/crd/bases/anywhere.eks.amazonaws.com_controlplaneupgrades.yaml
config/crd/bases/anywhere.eks.amazonaws.com_machinedeploymentupgrades.yaml
config/crd/bases/anywhere.eks.amazonaws.com_nodeupgrades.yaml
config/manifest/eksa-components.yaml
pkg/api/v1alpha1/controlplaneupgrade_types.go
pkg/api/v1alpha1/machinedeploymentupgrade_types.go
pkg/api/v1alpha1/nodeupgrade_types.go

Add kubebuilder tags to print meaningful columns for in-place upgrade CRDs.
Also add shortnames for CRDs: `cpu` for `controlplaneupgrades`, `mdu` for `machinedeploymentupgrades`, and `nu` for `nodeupgrades`
```bash
k get cpu,mdu,nu -A                               
NAMESPACE     NAME                                                                               KUBEADMCONTROLPLANE      UPGRADED   PENDINGUPGRADE   READY   AGE   KUBERNETESVERSION
eksa-system   controlplaneupgrade.anywhere.eks.amazonaws.com/abhnvp-workload-ubuntu-cp-upgrade   abhnvp-workload-ubuntu   3          0                true    14m   v1.29.0-eks-1-29-3
NAMESPACE     NAME                                                                                         MACHINE DEPLOYMENT …
```

Add kubebuilder tags to print meaningful columns for in-place CRDs

---

pkg/curatedpackages/packagecontrollerclient.go

https://github.com/aws/eks-anywhere/issues/7336
The current log message mentioned on the issue #7336  doesn't properly mention what command is being used to use the fallback registry instead, and is just showing the command that failed with the regional access. 
Currently, we do not run any commands [here](https://github.com/aws/eks-anywhere/blob/main/pkg/curatedpackages/packagecontrollerclient.go#L282) while using the fallback registry. Changed the log message as below. 
```
Error pulling from regional registry    {"Registry": "067575901363.dkr.ecr.us-west-2.amazonaws.com", "RegionalRegistryAccessIssue": "{\"errors\":[{\"code\":\"DENIED\",\"message\":\"User: arn:aws:iam::189183948571:user/packagesECRRead is not authorized to perform: …
```

Update log to use fallback registry when not authorized to access regionalized packages

---

cmd/eksctl-anywhere/cmd/upgradeplanmanagementcomponents.go
pkg/cluster/fetch.go
pkg/clusterapi/installer.go
pkg/clusterapi/installer_test.go
pkg/clusterapi/manager.go
pkg/clusterapi/mocks/capiclient.go
pkg/clusterapi/upgrader.go
pkg/clusterapi/upgrader_test.go
pkg/clustermanager/cluster_manager.go
pkg/clustermanager/cluster_manager_test.go
pkg/clustermanager/mocks/client_and_networking.go
pkg/executables/clusterctl.go
pkg/executables/clusterctl_test.go
pkg/workflows/create.go
pkg/workflows/create_test.go
pkg/workflows/delete.go
pkg/workflows/delete_test.go
pkg/workflows/interfaces/interfaces.go
pkg/workflows/interfaces/mocks/clients.go
pkg/workflows/management/core_components.go
pkg/workflows/management/create_install_capi.go
pkg/workflows/management/create_test.go
pkg/workflows/management/create_workload.go
pkg/workflows/management/upgrade_management_components_test.go
pkg/workflows/management/upgrade_test.go
pkg/workflows/upgrade.go
pkg/workflows/upgrade_test.go

This changes here are split out from https://github.com/aws/eks-anywhere/pull/7353 with some changes to use ManagementComponents. It also addresses https://github.com/aws/eks-anywhere/pull/7353#discussion_r1465492542 by passing the ManagementComponents down to where it's need.
Updates the CAPI upgrader to use management components:
- CAPIChangeDiff -> ChangeDiff which takes and compares *cluster.ManagementComponents to get the plan change diff
- CAPI InitInfrastructure updated to use `cluster.ManagementComponents` to initialize infrastructure for the cluster.
- CAPI InstallEtcdadmProviders updated to use `cluster.ManagementComponents` to install etcdadm providers.
- CAPI Upgrade updated to use `cluster.ManagementComponents` for the …

Change CAPI upgrader to use management components

---

cmd/eksctl-anywhere/cmd/version.go
pkg/manifests/releases/read.go
pkg/manifests/releases/read_test.go

The code was panicking with a nil pointer when a release wasn't found for the current version.
Discovered when working on #7463. Splitting it since it's not part of the original intent.

Handle release not found from version command

---

cmd/eksctl-anywhere/cmd/upgradeplancluster.go
cmd/eksctl-anywhere/cmd/upgradeplanmanagementcomponents.go

This PR fixes some issues introduced to the upgrade plan <resource> output.
- Removes the newline added for the output when there is nothing to update. This was needed when using fmt.Print, but not when using the `logger.Info` to write the output.
- Show "All the components are up to date with the latest versions" instead of empty table when there is nothing to update
- Fix output when using `upgrade plan management-components` on a workload cluster. It was showing %s instead of the cluster name, after a change to use the logger to print the output instead of `fmt.Printf`
**upgrade plan cluster/management-components** when there is nothing to update
Before
```
./bin/eksctl-anywhere upgrade plan …
```

Fix upgrade plan output when all components are up-to-date and for workload clusters.

---

pkg/semver/identifiers.go
pkg/semver/semver.go
pkg/semver/semver_test.go

This will be used to retrieve the latest dev build for a particular pre-release: v0.1.0-dev+build.2 > v0.1.0-dev+build.1
I wrote this when working on https://github.com/aws/eks-anywhere/pull/7463. Splitting it since although required, this code can live by itself.

Add util to compare semvers build metadata

---

controllers/controlplaneupgrade_controller_test.go
controllers/kubeadmcontrolplane_controller.go
controllers/kubeadmcontrolplane_controller_test.go
controllers/machinedeployment_controller.go
controllers/machinedeployment_controller_test.go
controllers/machinedeploymentupgrade_controller_test.go

Fix deletion logic for in-place upgrade CRs to ensure ControlPlaneUpgrade and MachineDeploymentUpgrade objects get cleaned up after the upgrade is complete.

Fix deletion logic for in-place upgrade CRs

---

config/crd/bases/anywhere.eks.amazonaws.com_controlplaneupgrades.yaml
config/crd/bases/anywhere.eks.amazonaws.com_machinedeploymentupgrades.yaml
config/manifest/eksa-components.yaml
controllers/controlplaneupgrade_controller.go
controllers/controlplaneupgrade_controller_test.go
controllers/machinedeploymentupgrade_controller.go
controllers/machinedeploymentupgrade_controller_test.go
controllers/nodeupgrade_controller.go
pkg/api/v1alpha1/controlplaneupgrade_types.go
pkg/api/v1alpha1/machinedeploymentupgrade_types.go

This PR ensures that the `ControlPlaneUpgrade` (CPU) and `MachineDeploymentUpgrade` (MDU) CR statuses get updated properly on each reconcile. Currently, in `updateStatus` for CPU and MDU controllers, we are looping through the machine lists and checking the statuses of the corresponding `NodeUpgrade` objects. These objects are only created after the previous one has finished. This leads to a scenario where the status won't get updated until all the `NodeUpgrades` corresponding to a CPU or MDU exist. To prevent this from happening, this PR skips any `NodeUpgrade` objects that are not found and only errors out on other errors.
This PR also adds back the omitempty tags to the CPU and MDU status fields as they are also needed to ensure the status gets updated every …

Ensure the `ControlPlaneUpgrade` and `MachineDeploymentUpgrade` statuses get updated

---

docs/content/en/docs/clustermgmt/cluster-flux.md

This PR removes the note that GitOps is not suppported for BareMetal. It is support for all providers.

Remove note that gitops is not supported for BareMetal

---

test/e2e/multicluster.go

TestVSphereKubernetes127UbuntuWorkloadClusterTaintsFlow fails with template tag validation error. 
`Error: validations failed: template /SDDC-Datacenter/vm/Templates/kubernetes-1-27-eks-21-ubuntu is missing tag eksdRelease:kubernetes-1-28-eks-14`
Fixing the above error with this PR.

Resolve TestVSphereKubernetes127UbuntuWorkloadClusterTaintsFlow e2e test error

---

pkg/providers/cloudstack/config/template-cp.yaml
pkg/providers/nutanix/config/cp-template.yaml
pkg/providers/snow/apibuilder.go
pkg/providers/snow/apibuilder_test.go
pkg/providers/snow/objects_test.go
pkg/providers/snow/snow_test.go
pkg/providers/tinkerbell/config/template-cp.yaml
pkg/providers/vsphere/config/template-cp.yaml

Before Kubernetes v1.29, the default Kubeconfig file `admin.conf` generated by `kubeadm` was bound to `system:masters` Group. In Kubernetes v1.29, a [change](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.29.md#no-really-you-must-read-this-before-you-upgrade) was made to `kubeadm` to provision a separate Kubeconfig file called `super-admin.conf` which is a break-glass Group that can bypass RBAC, and in addition, scoping down the `admin.conf` User's access to the permissions provided by the `cluster-admin` `ClusterRole`. It is to be noted that in a multi-cluster setup, the `super-admin.conf` is only created on the primary control plane node, which runs `kubeadm init`. This causes a bootstrap issue with EKS-A's `kube-vip` deployment because the static pod …

Use super-admin Kubeconfig for kube-vip from Kubernetes v1.29 onwards

---

docs/developer/manifests.md
release/cli/cmd/release.go
release/cli/go.mod
release/cli/pkg/bundles/eksctl-anywhere.go
release/cli/pkg/filereader/file_reader.go
release/cli/pkg/filereader/file_reader_test.go
release/cli/pkg/images/images.go
release/cli/pkg/types/types.go
release/cli/pkg/types/types_test.go
release/cli/pkg/util/artifacts/artifacts.go
release/cli/pkg/util/release/release.go
release/cli/pkg/util/release/release_test.go
release/scripts/release.sh
scripts/eksa_version.sh

Each CLI is built with a particular EKS-A semver in its metadata. This pins each binary built to a particular EKS-A release. However, the Release and Bundles manifests are not included or shipped with the binary. These are served through cloudfront and the CLI dynamically fetches them during each command startup. The logic is as follows:
1. Fetch the Release manifest. As part of its metadata, the CLI is built with a static URL (is the same for all EKS-A releases) pointing to this manifest. Dev CLIs will use a different URL than prod CLIs.
1. Iterate over the available EKS-A releases in the manifest and look for an exact version match with semver included in the build metadata of the binary.
1.
1. Select the exact match release and continue.
1. Or return an error if the release it not …

Use real version for dev releases

---

test/e2e/cloudstack_test.go

`TestCloudstackKubernetes127To128RedHatManagementCPUpgradeAPI` fails because we [check](https://github.com/aws/eks-anywhere/blob/main/internal/test/e2e/cloudstack.go#L11) for string `CloudStack` which is case sensitive. Thus required env variables were not getting passed for this test. This PR fixes this issue. 

Preserve CloudStack case sensitivity for e2e tests

---

cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
test/e2e/QUICK_TESTS.yaml

This PR adds the one CloudStack test to the quick e2e test suite. 
To accommodate the introduction of more tests, the quick tests are now being filtered through retrieving a list of regex from a yaml file. 
- Ran the test against CI

Add one CloudStack test to quick e2e tests

---

pkg/providers/tinkerbell/reconciler/reconciler.go
pkg/providers/tinkerbell/upgrade.go

As part of our pre-flight assertions currently we check for extra hardware was available during an upgrade for baremetal. With InPlace upgrades we don't need to perform this check when the Upgrade Strategy is configured for InPlace.
This change skips the extra hardware availability validation for upgrades when the rollout strategy is configured to InPlace. 
Tested this manually.

Skip extra hardware validation for InPlace Upgrades

---

Makefile
pkg/manifests/releases/read.go
pkg/manifests/releases/read_test.go
test/framework/cloudstack.go
test/framework/cluster.go
test/framework/commands.go
test/framework/eksa_versions.go
test/framework/nutanix.go
test/framework/release_versions.go
test/framework/vsphere.go

Builds on top of #7463 
This changes the build process for local dev builds and for E2E test builds to use the new versioning schema.
Copy paste of the logic followed from the original PR:
When a CLI is built for dev E2E tests, it's given the latest available EKS-A dev version. This pins that particular binary to one EKS-A version and hence one Bundles manifest. This is important in order to guarantee that the same Bundles is used for the whole execution of the test pipelines and avoids a race condition where a new EKS-A dev release and Bundles are published during an E2E test run.
When writing and testing code for the CLI/Controller, most of the time we don't care about particular releases and we just want to use the latest available Bundles that contains the latest available set of …

Use new dev versions in local and E2E test builds

---

cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
test/e2e/QUICK_TESTS.yaml

Adding one Nutanix test to the e2e suite.
- Add all the required environment variables to the quick e2e code build spec yaml
- Had to include templates for kubernetes versions that won't be in the suite due to it being required to run the tests. Moving forward, we might need to look into scoping these more appropriately for the tests.
- Added `TestNutanixKubernetes127to128RedHat9Upgrade` to the `QUICK_TESTS.yaml`
- Manually invoked code build run

Add one nutanix test to quick e2e suite

---

pkg/clustermanager/eksa_installer.go
pkg/clustermanager/eksa_installer_test.go

We need to set the env var in the controller deployment for in place upgrades to work in the unified controller.CLI flow on vSphere
created cluster

Add env var to controller when in place upgrades on VSphere env var is set

---

pkg/manifests/releases/read.go
pkg/manifests/releases/read_test.go

Comparison on same pre-release and ordered build metadata should only be done if the build metadata in the provided version is "latest".

Fix bug when selecting release from CLI version

---

test/framework/eksa_versions.go

Without this, the command output is swallowed and it only returns "exit status 255".

Add version command output to error in e2e tests

---

cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
test/e2e/QUICK_TESTS.yaml

Adding one Snow test to the e2e suite.
- Added all the required environment variables to the quick e2e code build spec yaml
- Added `TestSnowKubernetes128SimpleFlow` to the `QUICK_TESTS.yaml`. It is disabled for now until we move the current tests to nightly, being cognizant of infrastructure limitations.
- Manually invoking the codebuild project and sourcing the changes on this branch

Add one Snow test to quick e2e test suite

---

Makefile

This bypasses the CloudFront cache and avoids race conditions where the CLI expects a release that is not yet available in the cached manifest in CF.

Use S3 release manifest URL in CI E2E tests

---

cmd/eksctl-anywhere/cmd/version.go
pkg/manifests/releases/read.go
pkg/manifests/releases/read_test.go
pkg/version/version.go
test/framework/eksa_versions.go

* Print manifest URL when readin it for debugging
* Print release manifest URL as part of the version output
* When desired version is not found in release manifest, include the latest available version in the error message
* Update E2E tests to reuse version.Info

Improve release handling in version command

---

pkg/awsiamauth/reconciler/reconciler_test.go
pkg/controller/clusters/clusterapi.go
pkg/controller/clusters/clusterapi_test.go
pkg/providers/snow/reconciler/reconciler_test.go

There seems to be a race condition where the observed generation gets updated but the status is updated separately, which results in our controller thinking kcp is ready and moving onto applying the md specs. Though we need to figure out a better way to cover more use cases in terms of changes to kcp spec, adding a check for version will at least stop this from happening for version upgrades, ensuring kcp rollout is fully complete before moving onto md.
unit testing and functional testing

Add additional version check for cp ready

---

release/api/v1alpha1/artifacts.go

Add upgrader image to import images so it can be imported and used with registry mirror

Add upgrader image to import images

---

pkg/providers/tinkerbell/assert.go
pkg/providers/tinkerbell/assert_test.go
pkg/providers/tinkerbell/cluster.go
pkg/providers/tinkerbell/validate.go

InPlace upgrades do not roll-over the nodes during an upgrade. In most cases customer might not even have a spare hardware for the node to roll-over in case of baremetal. Cluster autoscaler internally uses Machinesets constructs to scale the nodes based on demand. During or after an inplace upgrade is completed, machinesets might not reflect the true source of truth of the capi machine as we only patch the `machineset.Spec.Template.Spec` field on the machineset after inplace upgrade is done.  Moreover if autoscaler decides to scale the node during when an inplace upgrade is in progress, it can lead to undesirable side-effects. This change blocks Autoscaler configuration along with InPlace upgrades.   …

Block autoscaler configuration with Inplace upgrade strategy

---

test/framework/cluster/validations/cluster.go

In our e2e validations for InPlace we check for kcp/md.Spec.Replicas to be equal to the updated and ready replicas count. There was a bug in the validation logic wherein we checked for the addresses of these fields instead of dereferencing and checking for the exact value. 
This change dereferences the kcp/md.spec.replicas to check for the actual value instead of the addresses as it is a pointer.

Fix InPlace e2e validation  to check for actual values in kcp/md.spec.Replicas  

---

cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
test/e2e/QUICK_TESTS.yaml

Adding one Tinkerbell test to the e2e suite.
- Added all the required environment variables to the quick e2e code build spec yaml
- Added `TestTinkerbellKubernetes127UbuntuTo128Upgrade` to the QUICK_TESTS.yaml. It is disabled for now until we move the current tests to nightly, being cognizant of infrastructure limitations.
- Also, enables the snow tests in the suite, as there is not much concern of infrastructure not being able to handle conflicting runs with the current main test runs.
- Manual code build invocation

Add one Tinkerbell e2e test to the quick test suite

---

pkg/providers/nutanix/config/cp-template.yaml

Because this command was being placed in `postKubeadmCommands` section of the `preKubeadmCommands`, the control plane nodes were unable to get properly initialized since the `kube-vip` pod wouldn't have the necessary permissions to acquire the lease it needs to for managing the VIP.

Move kube-vip manifest modification step to pre-kubeadm commands for Nutanix

---

pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/cluster_test.go

We must use local etcd with in place upgrades. Bare metal currently only supports local etcd, but for dev testing with vsphere, I'm adding this validation. Without this, the error would happen later in the flow & it would be hidden in the controller logs. 

Add validation for stacked etcd with in place on vsphere

---

cmd/eksctl-anywhere/cmd/validations.go

Common validations is run before a few of our operations:
- [upgrade cluster](https://github.com/aws/eks-anywhere/blob/02225e79dddc967349d44b91c12b2b37b8ee25c1/cmd/eksctl-anywhere/cmd/upgradecluster.go#L107)
- [delete cluster](https://github.com/aws/eks-anywhere/blob/02225e79dddc967349d44b91c12b2b37b8ee25c1/cmd/eksctl-anywhere/cmd/deletecluster.go#L84)
- [generating the support bundle](https://github.com/aws/eks-anywhere/blob/02225e79dddc967349d44b91c12b2b37b8ee25c1/cmd/eksctl-anywhere/cmd/supportbundle.go#L60)
- [generating the upgrade plan for the cluster](https://github.com/aws/eks-anywhere/blob/02225e79dddc967349d44b91c12b2b37b8ee25c1/cmd/eksctl-anywhere/cmd/upgradeplancluster.go#L56)`
- [generating the upgrade plan for management …

Remove cluster config validation from common validations

---

pkg/workflows/management/upgrade_management_components.go

Adds a success log at the end of the `upgrade management-components` workflow.
- Ran `upgrade management-components`
Output
```
[ec2-user@ip-172-31-61-197 vsphere-cluster]$ eksctl-anywhere upgrade management-components -f mgmt/mgmt-eks-a-cluster.yaml
Warning: The recommended size of an external etcd cluster is 3 or 5
✅ Connected to server
✅ Authenticated to vSphere
✅ Datacenter validated
✅ Network validated
✅ cxbrowne@amazon.com user vSphere privileges validated
✅ Vsphere provider validation
✅ Control plane ready
✅ Cluster CRDs ready
Upgrading core components
🎉 Management components upgraded!
``` …

Add success log to upgrade management components flow

---

pkg/awsiamauth/installer.go
pkg/clustermanager/cluster_manager.go
pkg/clustermanager/mocks/client_and_networking.go
pkg/workflows/interfaces/interfaces.go
pkg/workflows/interfaces/mocks/clients.go
pkg/workflows/management/create_workload.go

Generate and write AWS IAM auth kubeconfig to disk

Generate and write AWS IAM auth kubeconfig to disk

---

pkg/providers/tinkerbell/assert_test.go
pkg/providers/tinkerbell/validate.go

Validation wasn't catching the case where there is none specified for worker node groups, so fixed it to follow the similar pattern used for cp.
unit testing

Fix validation to enforce same upgrade strategy for cp and workers for in place

---

cmd/eksctl-anywhere/cmd/createcluster.go
cmd/eksctl-anywhere/cmd/deletecluster.go
pkg/features/features.go
pkg/features/features_test.go
pkg/workflows/management/create_test.go
pkg/workflows/workload/create_test.go
pkg/workflows/workload/delete_test.go
pkg/workflows/workload/upgrade_test.go

Remove feature flag for controller via CLI

Remove feature flag for controller via CLI

---

cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
test/e2e/QUICK_TESTS.yaml

- Add existing tests from the e2e test suite to quick tests suite.
- Add new vSphere test variables
Manually invoke CI to run tests

Add tests to quick e2e suite from existing tests

---

cmd/eksctl-anywhere/cmd/createcluster.go
cmd/eksctl-anywhere/cmd/deletecluster.go
pkg/features/features.go
pkg/features/features_test.go
pkg/workflows/management/create_test.go
pkg/workflows/workload/create_test.go
pkg/workflows/workload/delete_test.go
pkg/workflows/workload/upgrade_test.go

This reverts commit 1034e5170ce84132d53da3d45657e18250cf648a.
Revert "Remove feature flag for controller via CLI (#7546)"

Revert "Remove feature flag for controller via CLI (#7546)"

---

pkg/api/v1alpha1/condition_consts.go
pkg/controller/clusters/status.go
pkg/controller/clusters/status_test.go

Update cluster status to show `RollingUpgradeInProgress` when the upgrade type is `rollingUpgrade` and `InPlaceUpgradeInProgress` when the upgrade type is `inPlace`. 
For worker nodes, it will show `RollingUpgradeInProgress` if all nodes have upgrade type `rollingUpgrade`, `InPlaceUpgradeInProgress` when the upgrade type is `inPlace`, and `UpgradeInProgress` if there is a combination of both upgrade types.
```
Status:
Children Reconciled Generation:  5
Conditions:
Last Transition Time:  2024-02-12T20:20:23Z
Message:               Control plane nodes not up-to-date yet, 3 upgrading (0 up to date)
Reason:                InPlaceUpgradeInProgress
Severity:              Info
Status:                False
Type: …
```

Update status message to show upgrade type

---

cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml

This allows to manually run a pipeline with this buildspec and running only one or a particular subset of tests.
It introduces the value "QUICK" that allows to run all configured tests for the quick pipeline without knowing the tests. This allows a manual pipeline to run all quick tests without passing an empty variable, which is not allowed.

Allow to set tests to run in quick e2e buildspec

---

go.mod
go.sum

Bump up Nutanix CAPX to v1.3.1.
Changes in CAPX are trivial (get rid of CAPX manager pod limits), but fix customer issue.
Related PR: https://github.com/aws/eks-anywhere-build-tooling/pull/2920

Bump up Nutanix CAPX to v1.3.1

---

test/e2e/QUICK_TESTS.yaml
test/e2e/vsphere_test.go

This PR adds the remaining new vSphere e2e tests to the quick test suite.
Manually invoked tests runs

Add quick e2e tests for vSphere

---

pkg/executables/clusterctl.go
pkg/executables/clusterctl_test.go
pkg/providers/cloudstack/cloudstack.go
pkg/providers/docker/docker.go
pkg/providers/mocks/providers.go
pkg/providers/nutanix/provider.go
pkg/providers/nutanix/provider_test.go
pkg/providers/provider.go
pkg/providers/snow/snow.go
pkg/providers/tinkerbell/tinkerbell.go
pkg/providers/vsphere/vsphere.go

*Context:*
The newly introduced upgrade `management-components` commands is currently building a new cluster spec and running validations against it. We do not want to do this because the users cluster spec updates are not applied while upgrading management components. Specifically, one problem  that arises is that  if your cluster is currently running a deprecated version of Kubernetes in EKS Anywhere (right now Kubernetes 1.24), the CLI will fail upgrading the management components  when [building the new cluster spec](https://github.com/aws/eks-anywhere/blob/4de7cda5ac1e6b571d769df82de2391634b750b8/cmd/eksctl-anywhere/cmd/upgrademanagementcomponents.go#L37). 
```
Error: failed to upgrade cluster: unable to get cluster config from file: kubernetes version 1.24 …
```

Generate snow provider environment variable map using management components

---

test/e2e/QUICK_TESTS.yaml
test/e2e/SKIPPED_TESTS.yaml
test/e2e/cloudstack_test.go
test/framework/cloudstack.go

Add Kubernetes v1.29 E2E tests for CloudStack provider.

Add 1.29 CloudStack E2E tests

---

pkg/providers/cloudstack/cloudstack.go
pkg/providers/docker/docker.go
pkg/providers/mocks/providers.go
pkg/providers/nutanix/provider.go
pkg/providers/provider.go
pkg/providers/snow/snow.go
pkg/providers/tinkerbell/upgrade.go
pkg/providers/tinkerbell/upgrade_test.go
pkg/providers/vsphere/vsphere.go
pkg/workflows/management/core_components.go
pkg/workflows/management/upgrade_management_components_test.go
pkg/workflows/management/upgrade_test.go
pkg/workflows/upgrade.go
pkg/workflows/upgrade_test.go

*Context:*
The newly introduced upgrade `management-components` commands is currently building a new cluster spec and running validations against it. We do not want to do this because the users cluster spec updates are not applied while upgrading management components. Specifically, one problem  that arises is that  if your cluster is currently running a deprecated version of Kubernetes in EKS Anywhere (right now Kubernetes 1.24), the CLI will fail upgrading the management components  when [building the new cluster spec](https://github.com/aws/eks-anywhere/blob/4de7cda5ac1e6b571d769df82de2391634b750b8/cmd/eksctl-anywhere/cmd/upgrademanagementcomponents.go#L37). 
```
Error: failed to upgrade cluster: unable to get cluster config from file: kubernetes version 1.24 …
```

Update PreCoreComponentsUpgrade to use management components

---

internal/pkg/api/vsphere.go
test/e2e/upgrade.go
test/e2e/vsphere_test.go

[#2008](https://github.com/aws/eks-anywhere-internal/issues/2008)
Added four inplace upgrades E2E tests for scaling control plane and worker nodes
- Scale up control plane nodes from 1 to 3
- Scale down control plane nodes from 3 to 1
- Scale up worker nodes from 1 to 2
- Scale down worker nodes from 2 to 1
Tested locally in vsphere dev env

Add inplace upgrade E2E tests for scaling nodes in vsphere

---

pkg/awsiamauth/reconciler/reconciler.go
pkg/constants/constants.go

Move aws kubeconfig secret to workload cluster

Move aws kubeconfig secret to workload cluster

---

pkg/awsiamauth/reconciler/reconciler.go

Fix docker nil pointer for endpoint host aws iam auth reconciler
- manual e2e

Fix docker nil pointer for endpoint host aws iam auth reconciler

---

pkg/validations/cluster.go
pkg/validations/cluster_test.go
pkg/validations/upgradevalidations/preflightvalidations.go
pkg/validations/upgradevalidations/preflightvalidations_test.go

https://github.com/aws/eks-anywhere-internal/issues/2189
We have enabled controller for all the cluster operations. Cluster upgrade process succeds and doesn't show any error if the customer pauses controller reconciler manually by annotating cluster with `anywhere.eks.amazonaws.com/paused=true` annotation. With this PR, the cluster upgrade command will give following error if the cluster reconciler is paused before upgrading the cluster.
`❌ Validation failed    {"validation": "validate eksa controller is not paused", "error": "remove cluster controller reconciliation pause annotation anywhere.eks.amazonaws.com/paused before upgrading cluster docker", "remediation": "ensure cluster controller reconciliation is not paused manually before …

Add a validation if the controller is paused during cluster upgrade

---

test/e2e/vsphere_test.go

Add base InPlace upgrade flows for vSphere. These include InPlace upgrading to all supported kubernetes versions 

Add base InPlace upgrade flows for vSphere

---

test/e2e/upgrade.go
test/e2e/vsphere_test.go
test/framework/vsphere.go

Adding e2e for modular inplace upgrades
--- PASS: TestVSphereKubernetes127UbuntuTo128InPlaceUpgradeWorkerOnly (705.86s)
--- PASS: TestVSphereKubernetes127UbuntuTo128InPlaceUpgradeCPOnly (937.91s)

Add in place modular upgrade e2e tests

---

test/e2e/multicluster.go
test/e2e/vsphere_test.go
test/framework/cluster/validations/cluster.go

[#2008](https://github.com/aws/eks-anywhere-internal/issues/2008)
Added four E2E tests for multicluster workload cluster k8s upgrade in vsphere
- 1.25 to 1.26
- 1.26 to 1.27
- 1.27 to 1.28
- 1.28 to 1.29
Tested locally in vsphere dev env

Add e2e tests for workload cluster k8s inplace upgrade

---

pkg/workflows/workload/writeclusterconfig.go

Write AWS IAM kubeconfig file for workload cluster
- manual tested e2e

Write AWS IAM kubeconfig file for workload cluster

---

pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/cluster_test.go
pkg/api/v1alpha1/cluster_types.go
pkg/providers/tinkerbell/create.go
pkg/providers/tinkerbell/template.go
pkg/providers/tinkerbell/template_test.go
pkg/workflows/management/create_install_eksa.go

Fix tinkerbell IP in hegel urls controller 
- manual test
- unit tests

Fix tinkerbell IP in hegel urls controller

---

pkg/awsiamauth/installer.go
pkg/awsiamauth/installer_test.go
pkg/dependencies/factory.go
pkg/dependencies/factory_test.go
pkg/kubeconfig/kubeconfig.go
pkg/kubeconfig/kubeconfig_writer.go
pkg/kubeconfig/mocks/writer.go
pkg/providers/docker/docker.go
pkg/workflows/management/create_test.go
pkg/workflows/management/create_workload.go
pkg/workflows/management/write_cluster_config.go

Docker's kubeconfig requires getting the load balancer's port and rewriting the kubeconfig to use that port. 
Use the existing Kubeconfig Writer interface for writing IamAuth's kubeconfig. Docker has its own implementation and the implementation of kubeconfig writer chosen when creating a cluster is determined by factory based on provider.

Use Kubeconfig Writer for IamAuth

---

cmd/eksctl-anywhere/cmd/createcluster.go
cmd/eksctl-anywhere/cmd/deletecluster.go

[Remove feature flag for create](https://github.com/aws/eks-anywhere/commit/d870a30a4cc0b395e8c2a4df3cddacdd9f790f36)

Remove feature flag for create

---

internal/test/cluster.go
internal/test/testdata.go
internal/test/testdata/releases.yaml
pkg/api/v1alpha1/cluster_types.go
pkg/cluster/fetch_test.go
pkg/clustermarshaller/testdata/expected_marshalled_cluster.yaml
pkg/clustermarshaller/testdata/expected_marshalled_cluster_flux_and_gitops.yaml
pkg/clustermarshaller/testdata/expected_marshalled_cluster_flux_config.yaml
pkg/curatedpackages/packagecontrollerclient_test.go
pkg/providers/common/common.go
pkg/providers/common/common_test.go
pkg/validations/createvalidations/preflightvalidations_test.go
pkg/validations/upgradevalidations/preflightvalidations_test.go
pkg/workflows/management/upgrade_management_components_test.go
pkg/workflows/management/upgrade_test.go

`GetExternalEtcdReleaseURL` doesn't work for dev builds currently cuz it only checks if the current cluster version is either equal to or greater than the bundle version. The equality check doesn't work for dev bundles because they are of the form `v0.19.0-dev+latest` which doesn't equal the bundle version `v0.19.0`
This PR updates this check to ensure that the cluster version is not less than bundle version.

Fix check for getting etcd url

---

controllers/controlplaneupgrade_controller.go
controllers/controlplaneupgrade_controller_test.go
pkg/constants/constants.go
pkg/nodeupgrader/testdata/expected_first_control_plane_upgrader_pod.yaml
pkg/nodeupgrader/testdata/expected_rest_control_plane_upgrader_pod.yaml
pkg/nodeupgrader/upgrader.go

Kube-vip is deployed as static pod which means during any eksd/k8s version upgrade InPlace, we need to also update the kube-vip manifest with the new image for InPlace upgrades. This change parses the udpated Kube-vip manifest from `KubeadmControlPlaneSpec.KubeadmConfigSpec` and uses a config map mounted to the upgrader pod to facilitate kube-vip update for InPlace.  The upgrader [script](https://github.com/aws/eks-anywhere-build-tooling/pull/2926) then uses the volume mount to update the kube-vip manifest onto the host. 
Tested the changes locally. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …

Update kube-vip for InPlace upgrades.

---

cmd/eksctl-anywhere/cmd/upgradecluster.go
pkg/api/v1alpha1/tinkerbelldatacenterconfig_webhook.go
pkg/api/v1alpha1/tinkerbelldatacenterconfig_webhook_test.go
pkg/controller/clientutil/annotations.go
pkg/controller/clientutil/annotations_test.go
pkg/workflows/management/upgrade_cluster.go
pkg/workflows/management/upgrade_test.go
pkg/workflows/workload/upgrade.go
pkg/workflows/workload/upgrade_test.go
pkg/workflows/workload/upgradecluster.go

After `upgrade management-components` operation, EKSA allows the user to upgrade the cluster one of two ways: through the CLI and through the API. Today, the `upgrade cluster` command will upgrade the Tinkerbell stack, but upgrading the cluster through the API does not. So, any fields changed in the spec after upgrading management components would not be respected if upgrade through the API, as there is no logic in the controller that upgrades the Tinkerbell stack. Overall, there is a discrepancy between the behavior of the CLI `upgrade cluster` command and `kubectl apply -f <cluster.yaml>` when there should not be.
This PR adds some immutability validation in the tinkerbelldatacenterconfig webhook on fields that should be reconciled with …

Validate immutable Tinkerbell Datacenter fields in web-hook when managing with the Full Lifecycle Controller API

---

cmd/eksctl-anywhere/cmd/upgradecluster.go
pkg/api/v1alpha1/cluster_webhook.go
pkg/providers/nutanix/config/cp-template.yaml
pkg/providers/nutanix/template.go
pkg/providers/nutanix/template_test.go
pkg/providers/nutanix/testdata/cluster_nutanix_etcd_encryption.yaml
pkg/providers/nutanix/testdata/expected_results_etcd_encryption.yaml

Add etcd encryption for Nutanix provider 
- change CP manifest templates
- add unit test
```
$ eksctl anywhere upgrade cluster -f ./cluster-etcd-enc-ntnx.yaml --bundles-override bin/local-bundle-release.yaml
✅ Nutanix provider validation
✅ SSH Keys present
✅ Validate OS is compatible with registry mirror configuration
✅ Validate certificate for registry mirror
✅ Control plane ready
✅ Worker nodes ready
✅ Nodes ready
✅ Cluster CRDs ready
✅ Cluster object present on workload cluster
✅ Upgrade cluster kubernetes version increment
✅ Upgrade cluster worker node group kubernetes version increment
✅ Validate authentication for git provider
✅ Validate immutable fields
✅ Validate cluster's eksaVersion matches …
```

Add etcd encryption for Nutanix provider

---

cmd/eksctl-anywhere/cmd/createcluster.go
pkg/clients/kubernetes/unauth.go
pkg/clients/kubernetes/unauth_test.go
pkg/clustermanager/cluster_manager.go
pkg/workflows/create_prep.go
pkg/workflows/create_prep_test.go
pkg/workflows/interfaces/interfaces.go
pkg/workflows/interfaces/mocks/clients.go
pkg/workflows/management/create.go
pkg/workflows/management/create_install_eksa.go
pkg/workflows/management/create_test.go
pkg/workflows/management/create_workload.go
pkg/workflows/workload/create.go
pkg/workflows/workload/create_test.go
pkg/workflows/workload/createcluster.go

use client factory to create namespace

---

internal/test/testdata/bundles.yaml
pkg/providers/cloudstack/cloudstack_test.go
pkg/providers/cloudstack/config/template-cp.yaml
pkg/providers/cloudstack/testdata/cluster_etcd_encryption_1_29.yaml
pkg/providers/cloudstack/testdata/expected_results_encryption_config_cp_1_29.yaml
pkg/providers/cloudstack/testdata/expected_results_minimal_md_1_29.yaml
pkg/providers/nutanix/config/cp-template.yaml
pkg/providers/nutanix/template_test.go
pkg/providers/nutanix/testdata/cluster_nutanix_etcd_encryption_1_29.yaml
pkg/providers/nutanix/testdata/expected_results_etcd_encryption_1_29.yaml
pkg/providers/vsphere/config/template-cp.yaml
pkg/providers/vsphere/testdata/cluster_ubuntu_etcd_encryption_1_29.yaml
pkg/providers/vsphere/testdata/expected_results_main_129_md.yaml
pkg/providers/vsphere/testdata/expected_results_ubuntu_etcd_encryption_cp_1_29.yaml
pkg/providers/vsphere/vsphere_test.go

The KMS v1 provider was deprecated in Kubernetes v1.28 and [disabled by default](https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/#kms-v1) in Kubernetes v1.29, in favor of the KMS V2 provider . To use KMS v1 in Kubernetes v1.29, we need to set the API server feature gate `KMSv1=true`. This PR adds the feature flag to our cluster templates, along with unit tests verifying the feature gate gets added for Kubernetes v1.29.

Add KMS v1 feature gate for Kubernetes v1.29

---

cmd/eksctl-anywhere/cmd/deletecluster.go
controllers/cluster_controller.go
controllers/cluster_controller_test.go
pkg/clustermanager/cluster_manager.go
pkg/workflows/interfaces/interfaces.go
pkg/workflows/interfaces/mocks/clients.go
pkg/workflows/management/delete.go
pkg/workflows/management/delete_bootstrap.go
pkg/workflows/management/delete_cluster.go
pkg/workflows/management/delete_create_bootstrap.go
pkg/workflows/management/delete_install_capi.go
pkg/workflows/management/delete_install_eksa.go
pkg/workflows/management/delete_move_capi.go
pkg/workflows/management/delete_test.go
pkg/workflows/management/upgrade_test.go
pkg/workflows/management/validate.go
pkg/workflows/workload/delete_test.go
pkg/workflows/workload/deletecluster.go
pkg/workflows/workload/post_delete.go
pkg/workflows/workload/upgrade_test.go

Adds a new delete workflow for mgmt clusters

Unify delete mgmt

---

test/framework/cluster.go

The e2e logs are becoming quite large with max verbosity. This PR lowers the verbosity to 6 so the logs are more manageable while also being useful

Lower E2E verbosity to 6

---

cmd/eksctl-anywhere/cmd/options.go
cmd/eksctl-anywhere/cmd/upgrademanagementcomponents.go
cmd/eksctl-anywhere/cmd/upgradeplanmanagementcomponents.go
pkg/dependencies/factory.go
pkg/eksd/upgrader.go
pkg/eksd/upgrader_test.go

*Context:*
The newly introduced sub command upgrade management-components currently has an issue where:
If you have an EKS Anywhere 1.24. You cannot update the management components if the cluster is using Kubernetes version 1.24, because the CLI runs into the following error: while [building the new cluster spec](https://github.com/aws/eks-anywhere/blob/4de7cda5ac1e6b571d769df82de2391634b750b8/cmd/eksctl-anywhere/cmd/upgrademanagementcomponents.go#L37)
```
Error: failed to upgrade cluster: unable to get cluster config from file: kubernetes version 1.24 is not supported by bundles
It occurs while building the new cluster spec, when trying to [pick the correct versions bundle](https://github.com/aws/eks-anywhere/blob/4de7cda5ac1e6b571d769df82de2391634b750b8/pkg/clus …
```

Fix management component upgrades and upgrade plan with Cluster using unsupported Kubernetes versions

---

test/e2e/upgrade.go
test/e2e/vsphere_test.go

[#2008](https://github.com/aws/eks-anywhere-internal/issues/2008)
Added E2E test for inplace upgrade from k8s 1.25 all the way to 1.28
Tested locally in vsphere dev env

Upgrade all the way from 1.25 to 1.28

---

test/e2e/upgrade_from_latest.go
test/e2e/vsphere_test.go

[#2008](https://github.com/aws/eks-anywhere-internal/issues/2008)
Added E2E test for inplace upgrade from latest minor release with k8s version upgrade from 1.28 to 1.29
Tested locally in vsphere dev env

Add e2e test for inplace upgrade from latest release

---

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml
controllers/controlplaneupgrade_controller.go
controllers/controlplaneupgrade_controller_test.go
controllers/factory.go
pkg/nodeupgrader/testdata/expected_first_control_plane_upgrader_pod.yaml
pkg/nodeupgrader/testdata/expected_rest_control_plane_upgrader_pod.yaml
pkg/nodeupgrader/testdata/expected_worker_upgrader_pod.yaml
pkg/nodeupgrader/upgrader.go

When updating kube-vip manifest for workload cluster, we need the remote client to be able to create the config map with kube-vip manifest data. This change uses remote client instead of management client to create the kube-vip config map for InPlace upgrades. Additionally the upgrader pod is also set to restart on failure as a retry mechanism. 
Tested locally for workload cluster upgrade using InPlace strategy

Fix workload cluster kube-vip update

---

test/e2e/SKIPPED_TESTS.yaml

Skip RHEL 1.29 e2e test for tinkerbell

Skip RHEL 1.29 e2e test for tinkerbell

---

Makefile

Update branch name to release-0.19 in Makefile.

Update branch name to release-0.19 in Makefile

---

scripts/eksa_version.sh

Just before we release a new minor version, we cut a release branch that we use to run tests and stabilize the release. At this point, there isn't yet any tag for the minor release. The old code was assuming there was one at thus picking the wrong tag. This solves the issue by running the same logic as for main where there are no tags that match the release branch minor version.
Tested manually

Fix script to get next eksa version

---

test/e2e/airgap.go

Bottlerocket support was removed for Tinkerbell provider starting with 1.29 k8s version. The Airgapped tests while downloading artifacts and verifying were failing due to missing Bottlerocket artifact present in the bundles. This change removes the validation.

Remove validation for Bottlerocket OS in bundles for Tinkerbell tests

---

pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/cluster_test.go
pkg/api/v1alpha1/testdata/cluster_in_place_upgrade.yaml
pkg/features/features.go
pkg/features/features_test.go
pkg/validations/cluster.go
pkg/validations/cluster_test.go
pkg/validations/createvalidations/preflightvalidations.go
pkg/validations/upgradevalidations/preflightvalidations.go
test/framework/cluster.go

This PR removes the feature flag for Kubernetes v1.29 support and make it the default cluster version.

Remove Kubernetes v1.29 feature flag and make it the default cluster version

---

test/e2e/QUICK_TESTS.yaml
test/e2e/SKIPPED_TESTS.yaml
test/e2e/cloudstack_test.go
test/e2e/nutanix_test.go
test/e2e/snow_test.go

This PR creates the remaining e2e tests for Cloudstack, Nutanix and Snow that we want to include in the quick e2e suite.
- Manually invoking code build to run tests

Add remaining quick e2e tests for cloudstack, nutanix and snow

---

pkg/dependencies/factory.go
pkg/workflows/management/delete_move_capi.go
pkg/workflows/management/delete_test.go

Pauses the mgmt cluster before moving CAPI for delete task. 
Also adds a 1 hour timeout for delete.

Pause eksa cluster before moving capi for delete

---

test/e2e/SKIPPED_TESTS.yaml

Temporarily skipping tests that are either broken due to feature changes introduced or test environment issues. Owners working on fixing these tests will enable these tests along with their fix's PR.

Skip E2E tests that are broken

---

pkg/executables/config/kind.yaml
pkg/executables/kind.go
pkg/executables/kind_test.go
pkg/executables/testdata/kind_config.yaml
pkg/executables/testdata/kind_config_docker_mount_networking.yaml
pkg/executables/testdata/kind_config_extra_port_mappings.yaml
pkg/executables/testdata/kind_config_registry_mirror_insecure.yaml
pkg/executables/testdata/kind_config_registry_mirror_with_auth.yaml
pkg/executables/testdata/kind_config_registry_mirror_with_ca.yaml

Override pod and service subnet for kind cluster

Override pod and service subnet for kind cluster

---

controllers/kubeadmcontrolplane_controller.go
controllers/kubeadmcontrolplane_controller_test.go
controllers/machinedeployment_controller.go
controllers/machinedeployment_controller_test.go

We noticed that after the `ControlPlaneUpgrade` (CPU) was complete and the corresponding CPU object was deleted, there was a race condition where if the KCP object statuses weren't updated on time, our KCP controller would create another CPU object and try to perform the upgrade again. 
This PR fixes this race condition issue by only deleting the CPU after the KCP object has reached the expected state.
The same fix is applied for in the MachineDeployment controller for cleaning up `MachineDeploymentUpgrade` objects.

Fix InPlace upgrade objects cleanup race conditions

---

pkg/api/v1alpha1/tinkerbelldatacenterconfig_types.go
pkg/api/v1alpha1/tinkerbellmachineconfig.go
pkg/providers/tinkerbell/assert_test.go
pkg/providers/tinkerbell/validate.go

- Make Ubuntu a default OS for Tinkerbell provider since we are deprecating support for BR for 1.29 k8s version.
- Add validation around osFamily field for controlplane and worker machine kubernetes version.

Add validation for 1.29 k8s version for BR family

---

internal/pkg/ssm/command.go

Currently, we don't set the delivery timeout for SSM commands. This defaults the delivery timeout to 3600s or 1 hour which is a really long time to wait for the command to just be delivered. If the SSM agent is unhealthy on the test runner, then waiting 1 hour doesn't make sense.
This PR configures the delivery timeout to 5 min. The tests also have another timeout called `Execution Timeout` which specifies how long the command has to finish execution, which is set separately and varies by command. 

Configure SSM delivery

---

controllers/cluster_controller.go
pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/cluster_test.go
pkg/api/v1alpha1/cluster_types.go
pkg/api/v1alpha1/cluster_types_test.go
pkg/workflows/management/delete_cluster.go
pkg/workflows/management/delete_install_eksa.go
pkg/workflows/management/delete_test.go

Deleting a mgmt cluster after upgrading managment-components caused new machines to rollout during delete. Rather than waiting for the machines to rollout during delete, we should keep the EKS-Anywhere cluster on the bootstrap paused, and allow the controller to delete while the cluster is still paused. 

Fix machine rollout during mgmt delete

---

test/e2e/docker_test.go

We have a validation that checks if the cluster is ready before performing an upgrade. So, it's possible that after replacing EKSA cilium with the OS cilium in the. `TestDockerCiliumSkipUpgrade_CLIUpgrade` , it can fail with the following error:
```
2024-02-21T20:43:15.230Z	V0	❌ Validation failed	{"validation": "control plane ready", "error": "1 control plane replicas are unavailable", "remediation": "ensure control plane nodes and pods for cluster release-i-0c0c6-2a90c82 are Ready"}
```
We should validate that the cluster is in a ready state after replacing EKSA cilium with OSS cilium before continuing with the upgrade because of that.
By submitting this pull …

Add validation of cluster state after replacing with oss cilium in docker e2e test

---

controllers/cluster_controller.go
controllers/cluster_controller_test.go
pkg/api/v1alpha1/cluster_types.go
pkg/api/v1alpha1/cluster_types_test.go

Failure messages are cleared in the reconciler loop after running validations. But sometimes,
it seems that Cluster failure messages on the status are is not cleared for some reason
after successfully passing the validation. The theory is that if the initial patch operation
is not successful, and the reconcile loop is skipped going forward, it may never be cleared.
This PR addresses this issue by clearing the Cluster failure status when there is no further processing to do for the controller (there is no difference between the aggregated generation and childrenReconciledGeneration, and there is no difference in the reconciled generation and .`metadata.generation` of the cluster). At this point, it starts to skip reconciliation denoting …

Clear Cluster failure in status on successful reconciliation

---

docs/content/en/docs/clustermgmt/cluster-upgrades/vsphere-and-cloudstack-upgrades.md
docs/content/en/docs/clustermgmt/storage/vsphere-storage.md
docs/content/en/docs/whatsnew/changelog.md

clarify vSphere CSI driver docs

---

go.sum

Adding changes to `go.sum` file after running `go mod tidy`.

Update go.sum for main module

---

scripts/eksa_version.sh

Limit Git tags to those matching semver, ignoring weekly
/cherrypick release-0.19

Limit tags to those matching semver

---

docs/content/en/docs/clustermgmt/cluster-upgrades/management-components-upgrade.md

Add user facing doc for management-components upgrade

---

controllers/factory.go
pkg/networking/cilium/reconciler/reconciler.go
pkg/networking/cilium/reconciler/reconciler_test.go

Cilium reconciler when generating manifests were not using the provider namespaces when generating cilium manifests. This is not a problem for the most scenarios except when running cilium in "always" policy enforcement mode, where cilium expects explicit network policies to enable routing between any pods/services. This change enables the cilium reconciler to generate network policy for the provider's namespace that allows routing between the provider's controller and other services like kubernetes.

Cilium reconciler to use provider namespace in generating network policy

---

pkg/providers/cloudstack/config/template-cp.yaml
pkg/providers/cloudstack/testdata/expected_results_encryption_config_cp_1_29.yaml
pkg/providers/snow/apibuilder.go
pkg/providers/snow/apibuilder_test.go
pkg/providers/snow/etcd.go
pkg/providers/tinkerbell/config/template-cp.yaml
pkg/providers/vsphere/config/template-cp.yaml
pkg/providers/vsphere/testdata/expected_results_ubuntu_etcd_encryption_cp_1_29.yaml

ETCD Learner Mode went to Beta in k8s 1.29 and is now default enabled (see [here](https://kubernetes.io/blog/2023/09/25/kubeadm-use-etcd-learner-mode/), [here](https://github.com/kubernetes/kubeadm/issues/1793#issuecomment-1380585530)).
When a new stacked etcd instance comes up, it joins the cluster in learner mode.
The API Server cannot perform rpc calls against its etcd instance, and fails to come online.
In theory the etcd instance should be promoted to a full member as done in kubeadm [here](https://github.com/kubernetes/kubernetes/blob/fc7325fbec0fe379694e58b82e09f99f166c5e6d/cmd/kubeadm/app/phases/etcd/local.go#L164).
This is not happening because our bottlerocket bootstrap container is not allowing [etcd phase to complete](https://github.com/aws/eks-anywhere-build-tooling/blob/main/ …

Disable ETCD Learner Mode

---

config/manifest/eksa-components.yaml
test/e2e/upgrade.go

For the InPlace E2Es it so happens that sometimes the CRDs are left behind after a successful upgrade. In such scenarios, the test fails as the validations do not succeed but since the CLI in itself didn't fail we do not have access to support bundles, which makes it hard to investigate the failure. This change generates support bundle for InPlace tests in case the validations on the cluster fail. 
Tested locally by mocking a failed scenario. 

Generate support bundle for InPlace test in case the validations fail

---

pkg/executables/kubectl.go
pkg/validations/upgradevalidations/preflightvalidations.go

* Add information to error messages regarding the total unavailable replicas
* Provide a more meaningful explanation when the API server isn't ready
* Lowercase the word 'Ready' which makes it seem like 'Ready' has special meaning in the error message.
* Removed redundant check for ready control plane nodes.

Improve validation error messages

---

docs/content/en/docs/concepts/architecture.md
docs/content/en/docs/concepts/deployment-architectures.md
docs/content/en/docs/concepts/support-versions.md
docs/content/en/docs/getting-started/overview.md

These changes include
1. Adding Components breakdown to the EKS Anywhere Architecture page
2. Cleaning up the descriptions of standalone and management cluster deployment architectures

cleanup and expand architecture page

---

release/cli/pkg/images/images.go
release/cli/pkg/operations/bundle_release.go

In the staging releases, when we push Helm charts to ECR, they get a specific image digest, and when we sign them, a new image index with reference `sha256-<image digest>` gets created. However, in the prod releases, we pull the Helm chart locally and modify it and then push it, which gives it a different image digest than the one in staging, leading to a different reference for the signature image index. But when copying the signatures from source to destination, we assume the same signature image index which leads to an issue. This can be solved by re-computing the image digest signatures separately for source and release images and using them instead of the same digest for both. 
**Note:** This is an issue only for Helm charts because we modify them before pushing, but the PR changes …

Compute signature digests separately for source and destination images

---

test/e2e/docker_test.go

Add a small wait time after replacing cilium in the test. Kind of a hack, but it’s annoying to fix without. The nodes basically can become unready / unavailable a bit after replacing cilium. The upgrade validates that the nodes are ready, so when this happens, it fails. I’m not sure exactly how long this time frame can be, but 5 minutes should be more than enough from what I’ve seen

Add wait after replacing cilium in E2E test

---

release/cli/pkg/operations/bundle_release.go
release/cli/pkg/operations/eksa_release.go
release/cli/pkg/operations/upload.go

This PR adds a check is we are performing a bundle release or CLI release, this ensures packages artifacts are processed only during bundle release.

Process packages artifacts only during bundle release

---

docs/config.toml

Bump docs site version to 0.19.

Bump docs site version to 0.19

---

pkg/providers/cloudstack/reconciler/reconciler_test.go

https://github.com/aws/eks-anywhere-internal/issues/2193
Skip flaky unit tests for CloudStack provider as a revert of this PR https://github.com/aws/eks-anywhere/pull/7738

Skip cloudstack reconciler unit tests

---

test/e2e/QUICK_TESTS.yaml

These were disabled to avoid conflict with the main pipeline running the full e2e suite. Now that it has been moved to run once nightly, we an re-enable these.

Enable Tinkerbell tests in quick-e2e suite

---

docs/content/en/docs/getting-started/baremetal/overview.md
docs/content/en/docs/getting-started/nutanix/overview.md

*Issue:*
For generating a config file, you need to use `eksctl anywhere "generate" clusterconfig` command.
`eksctl anywhere "create" clusterconfig` command does not work.
Change the incorrect command `eksctl anywhere create clusterconfig` to `eksctl anywhere generate clusterconfig`.
```
$ eksctl anywhere generate clusterconfig baremetal-test --provider tinkerbell
kind: Cluster
metadata:
name: baremetal-test
...
```
```
$ eksctl anywhere create clusterconfig baremetal-test --provider tinkerbell
Error: unknown flag: --provider
Usage:
anywhere create [command]
Available Commands:
cluster     Create workload cluster
package(s)  Create curated packages
Flags:
-h, --help   help for create
Global …
```

Modify the incorrect command for generating a config file

---

docs/content/en/docs/getting-started/optional/etcdencryption.md

N/A
Nutanix has added ETCD encryption capabilities in 0.19 release, however this is not reflected in the documentation.
N/A
This PR will update the documentation to reflect ETCD encryption support for Nutanix.

Add Nutanix as provider for ETCD encryption

---

controllers/factory.go
controllers/factory_test.go
controllers/kubeadmcontrolplane_controller.go
controllers/kubeadmcontrolplane_controller_test.go
controllers/machinedeployment_controller.go
controllers/machinedeployment_controller_test.go

Some of the InPlace tests fail intermittently after a successful upgrade during the validation phase as some of the InPlace CRs are not cleaned up. We use an `in-place-upgrade-needed` on the kcp and md objects to identify the InPlace flow and remove those annotations once the upgrade is successful. In some cases, after the InPlace upgrade is successful the cache used to read the state of objects doesn't get updated quick enough. This leads to our controllers creating the InPlace custom resources again which leads to another upgrade on the node. Moreover since the annotation is removed, cache does get updated eventually leaving these objects in an untracked state as the kcp and md controller do not reconcile for InPlace flow anymore after the removal of annotation. …

Use an uncached direct client to read the kcp and md to bypass delay in cache

---

docs/content/en/docs/getting-started/vsphere/vsphere-getstarted.md

Major contribution here. There was a rogue ‘ that should be a '.

Fixing a single quote

---

.github/workflows/go-coverage.yml

Without the token, the new v4 action fails when uploading coverage from the jobs in main. The PR actions don't need it and, in fact, github should not pass the token to PRs coming from a fork.
More info: `https://github.com/codecov/codecov-action/issues/1274`

Add token for codecov to fix coverage upload

---

cmd/eksctl-anywhere/cmd/upgrademanagementcomponents.go
pkg/validations/cluster.go
pkg/validations/cluster_test.go
pkg/workflows/management/upgrade_management_components.go

We have added to the [docs](https://github.com/aws/eks-anywhere/pull/7668/files#diff-82e16c4f0007f799c0aba82707c850bb5217d02327e0fcf935638382887fc342R8) that the suppported version difference of management components can be at most 1 EKS Anywhere minor version greater than the EKS Anywhere version of cluster components. However, we have no pre-flight validation that ensures that. This PR adds that preflight validation.
- Unit testing
- Manual testing:
- Created cluster with v0.19.0 release
- Upgraded management components with main 
```
s-1-27-eks-22"}
2024-03-06T22:22:54.328Z        V0      ✅ Vsphere provider setup and validation
2024-03-06T22:22:54.328Z        V6      Getting KubeadmControlPlane CRDs …
```

Add preflight validation to check management components vs cluster components version skew

---

docs/content/en/docs/packages/troubleshoot.md

Troubleshooting guide had extra character
removed the last 's' in this command
```
kubectl get ns | grep eksa-packagess
```
N/A

Fixed typo in command (extra 's' in word: packagess)

---

go.mod
go.sum
release/cli/go.mod
release/cli/go.sum

Using the latest available version for all modules:
* github.com/aws/aws-sdk-go v1.50.34
* github.com/aws/aws-sdk-go-v2 v1.25.3
* github.com/aws/smithy-go v1.20.1

Bump aws sdk modules

---

docs/content/en/docs/osmgmt/artifacts.md

By creating the ssh config file, we should set the correct permission for this file, otherwise, the below error would come up with:
```code
*********************************************************
qemu: fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Bad owner or permissions on /home/image-builder/.ssh/config", "unreachable": true}
qemu:
qemu: PLAY RECAP 
```
Yes

Setting the right permission for ssh config

---

release/cli/pkg/helm/helm.go
release/cli/pkg/operations/upload.go

* Remove unnecessary packages artifacts map assignment
* Bubble up errors in getting tags

Fix packages artifacts map assignment, bubble up errors returned

---

pkg/clustermanager/cluster_manager.go

We shouldn't encode registry mirror credentials during create because it gets encoded again during apply, leading to a double encoding.
/cherrypick release-0.19

Don't encode registry mirror credentials during create

---

test/e2e/adot.go

When running `CuratedPackagesAdotUpdateFlow` e2e tests we noticed random behavior where the package update happened at the same moment the package-controller reconciled and gets a latest image tag. When testing the workflow manually, we never ran into the issue. Hence this seems like a timing thing and adding a wait before trying to update Adot package gives the package-controller enough time to rollout to a newer image. 
```
T_BUNDLES_OVERRIDE=true ./e2e.test -test.v -test.run "TestVSphereKubernetes129CuratedPackagesAdotUpdateFlow"
```

Adding wait before updating adot package in e2e tests

---

pkg/clustermanager/eksa_installer.go
pkg/clustermanager/eksa_installer_test.go

Fix e2e test failures for api server extra args

Add api server extra args feature flag to eksa controller deployment

---

pkg/clustermanager/eksa_mover.go
pkg/clustermanager/eksa_mover_test.go
pkg/dependencies/factory.go
pkg/dependencies/factory_test.go

Currently for creation of management clusters, we apply EKS-Anywhere resources and waiting for conditions twice (once on bootstrap and again on workload). This causes the create command to take longer than necessary. This PR adds a way to move resources between clusters, which should shorten the time it takes to create management clusters.

Add Cluster Mover

---

pkg/providers/tinkerbell/template.go

*Issue https://github.com/aws/eks-anywhere-internal/issues/2242*
When user specifies OCINamespaces with a `namespace` value on their `registryMirrorConfiguration`, we construct the containerd endpoints as `<registr-endpoint>:<port>/v2/<namespace-project>/<image-path>`. This is required when setting mirrors with containerd configuration. Example
```
[plugins."io.containerd.grpc.v1.cri".registry.mirrors]
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."public.ecr.aws"]
endpoint = ["https://1.2.3.4:1234/v2/eks-anywhere"]
```
But when replacing the tinkerbell action image uri's on the `TinkerbellTemplateConfig` object; we are setting them up to be pulled down using docker running on Hook OS during the tinkerbell OS provisioning stage. This fails because docker …

Fixing replace tinkerbell action images with registry endpoint

---

test/framework/cluster.go

Emissary docker e2e tests were failing when trying to curl test deployed hello EKS Anywhere application. This worked manually and proved to be a timing issue as we were not giving enough time for the hello app to come up and start serving; hence curl vailed to hit the cluster endpoint.
```
./e2e.test -test.v --test.run "TestDockerKubernetes129CuratedPackagesEmissarySimpleFlow"
```

Fixing docker e2e emissary tests for hello application

---

docs/content/en/docs/whatsnew/changelog.md

Adding Nutanix external `etcd` support to changelog

Add Nutanix external `etcd` support to changelog

---

release/cli/go.mod
release/cli/go.sum

Bumping Go module versions in release/cli go.mod.

Update Go modules in release/cli

---

docs/content/en/docs/osmgmt/artifacts.md

This PR extracts the `image-builder` CLI download step from every Hypervisor section and places it as a common step at the start of the node image build documentation. Also it fixes the supported Kubernetes versions list for `image-builder`.

Add common step for downloading image-builder CLI

---

designs/api-server-extra-args.md
docs/content/en/docs/getting-started/baremetal/bare-spec.md
docs/content/en/docs/getting-started/cloudstack/cloud-spec.md
docs/content/en/docs/getting-started/nutanix/nutanix-spec.md
docs/content/en/docs/getting-started/optional/api-server-extra-args.md
docs/content/en/docs/getting-started/snow/snow-spec.md
docs/content/en/docs/getting-started/vsphere/vsphere-spec.md

[#2091](https://github.com/aws/eks-anywhere-internal/issues/2091)
- Added `controlPlaneConfiguration.apiServerExtraArgs` as an optional configuration to the docs
- Mini design doc for configuring api server extra args

Add apiServerExtraArgs as optional configuration to docs

---

pkg/curatedpackages/packagecontrollerclient.go
pkg/curatedpackages/testdata/values_empty.yaml
pkg/curatedpackages/testdata/values_empty_registrymirrorsecret.yaml

The `registry-mirror-secret` Kubernetes `Secret` is created by EKS-A in the `eksa-packages` namespace with the required basic authentication and certificate information pertaining to registry mirrors. If registry mirror configuration is not provided, the credentials are left as empty strings by default. The details in this secret are used by the package controller to create another secret `registry-mirror-cred` which contains a Docker auth configuration `config.json` as the data. This auth file is then parsed and used to broadcast credentials to pull images from a registry mirror. This credentials broadcast operation is done always even when there is no registry mirror configured. In this case, the auth file has an empty string for username and password.
So far the empty strings did not …

Set non-empty defaults for registry mirror secret credentials

---

test/e2e/curatedpackages.go
test/framework/cluster.go

This PR fixes the issue where the support bundle was being generated after the cluster was already deleted for packages test.
This also ensures the support bundle generation occurs for all the packages tests if they fail.
Before
```
2024-04-05T00:50:46.489Z	V0	🎉 Cluster deleted!
2024-04-05T00:50:46.489Z	V4	Task finished	{"task_name": "kind-cluster-delete", "duration": "2.045545406s"}
2024-04-05T00:50:46.489Z	V4	----------------------------------
2024-04-05T00:50:46.489Z	V4	Tasks completed	{"duration": "8m21.550512339s"}
2024-04-05T00:50:46.491Z	V3	Cleaning up long running container	{"name": "eksa_1712277744498997388"}
cluster.go:950: Generating support bundle for failed test
cluster.go:962: Running shell command [ /usr/bin/sh -c eksctl …
```

Properly generate support bundle for packages test failures

---

cmd/eks-a-tool/cmd/cloudstackrmvms.go
cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
cmd/integration_test/cmd/cleanupcloudstack.go
internal/test/cleanup/cleanup.go
pkg/executables/cmk.go
pkg/executables/cmk_test.go
pkg/executables/testdata/cmk_list_network_duplicates.json
test/framework/cloudstack.go

This PR ensures that there are no duplicate networks in CloudStack CI environment before running the e2e tests.
If it finds any duplicate networks that are not of type `Shared`, it deletes them.
This ensures that the tests don't run into duplicate network issues.
Ran the command manually and verified that it works
```
./test e2e cleanup cloudstack -n adhbsdhbsahbfsahj --delete-duplicate-networks -v9
2024-04-09T01:16:18.227Z        V5      Retrier:        {"timeout": "2562047h47m16.854775807s", "backoffFactor": null}
2024-04-09T01:16:18.227Z        V2      Pulling docker image    {"image": "public.ecr.aws/l0g8r8j6/eks-anywhere-cli-tools:v0.18.4-eks-a-v0.0.0-dev-build.8100"}
2024-04-09T01:16:18.227Z        V6      Executing command …
```

Ensure no duplicate networks in CloudStack

---

pkg/api/v1alpha1/cluster_webhook.go

Delete workflow uses mover to create a paused cluster on bootstrap with encrypted etcd configuration. Our webhook does not allow this, so we can skip this validation when paused to allow moving cluster to bootstrap.

Fix Delete Encrypted Etcd Cluster

---

test/e2e/SKIPPED_TESTS.yaml

Aigrapped environment in cloudstack CI is not completely set up. Skipping `TestCloudStackKubernetes128RedhatAirgappedProxy` until it can be run.

Skip airgapped proxy test until it can be run

---

docs/content/en/docs/getting-started/vsphere/vsphere-spec.md

The example config had an overlap between the POD cidr block and the control plane endpoint IP. Though it is documented in several places not to overlap this, the example config is confusing.

docs: Clarify the networking example config

---

controllers/factory.go
pkg/curatedpackages/mocks/installer.go
pkg/curatedpackages/packagecontrollerclient.go
pkg/curatedpackages/packagecontrollerclient_test.go

*Issue https://github.com/aws/eks-anywhere-internal/issues/2269:*
This solves part one of the issue when creating a workload clusters with an authenticated registry mirror. The EKS-A controller is responsible for performing a helm install of the `eks-anywhere-packages` helm chart for a workload cluster; this was failing because
1. We did pass the `--insecure-skip-tls-verify` flag during the helm install.
2. For authenticated registry mirrors; we did not perform a helm login before running the helm install.
The changes in this PR fixes both the issues, hence customers who use `kubectl` to create a workload cluster would now get have packages enabled successfully when having an auth registry mirror.
*Testing:*
```
eksctl-anywhere create cluster -f cluster.yaml …
```

Adding a helm login to packages reconcile flow for workload clusters

---

pkg/nodeupgrader/testdata/expected_first_control_plane_upgrader_pod.yaml
pkg/nodeupgrader/testdata/expected_rest_control_plane_upgrader_pod.yaml
pkg/nodeupgrader/testdata/expected_worker_upgrader_pod.yaml
pkg/nodeupgrader/upgrader.go

Consume Upgrader go binary for InPlace upgrades to upgrade nodes instead of using the upgrader script.
Manually tested K8s version upgrades from 1.25 all the way until 1.29 with the binary embedded in the upgrader image instead of invoking the upgrader script. 

Node upgrader changes to consume upgrader go binary instead of script

---

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml
test/framework/config/pod-identity-webhook.yaml
test/framework/etcdencryption.go

This PR replaces the amazon-eks-pod-identity-webhook image from DockerHub with its ECR Public counterpart.

Replace DockerHub amazon-eks-pod-identity-webhook image with ECR Public image

---

internal/test/e2e/registryMirror.go
test/framework/registry_mirror.go

E2e tests did not pass along the required env var for ocinamespaces tests to running test env.

Passing along ocinamespaces env var to tests

---

internal/test/e2e/registryMirror.go

Looks like the setup method was returning early and not checking the conditions below for Docker Airgapped and OCINamespaces.

Fixing registry mirror setup function return

---

pkg/curatedpackages/curatedpackages.go
pkg/docker/registry.go
pkg/docker/registry_test.go
pkg/helm/download.go
pkg/helm/download_test.go

Pulling images and charts can fail due to network blips, rate limits and more. This retries pulling artifacts that are required for the `download images` cmd.

Retry pulling artifacts when running download images cmd

---

internal/test/e2e/ecr.go
internal/test/e2e/setup.go

Some tests are being rate limited when pulling from public ECR. This logs all tests into public ECR when running the CI so we avoid the 100 pull rate limit.

Log in to public ECR for E2E test

---

internal/test/e2e/run.go
internal/test/e2e/setup.go
internal/test/e2e/testRunner.go
test/framework/cluster.go

Its difficult to understand what the configuration when launhcing a test runner is. This logs the configuration giving insight into IPs among other information.

Log test runner instance config in e2e

---

docs/config.toml

This PR adds the version 0.18 to the `Versions` dropdown on the EKS Anywhere docs site so that users can switch to that version.
/cherrypick release-0.19

Allow users to access docs for penultimate EKS-A version

---

docs/config.toml

Add release-0.19 to Versions dropdown so customers can switch to docs for that version.

Add release-0.19 to docs version dropdown

---

config/manifest/eksa-components.yaml
config/rbac/role.yaml
controllers/cluster_controller.go
pkg/curatedpackages/packagecontrollerclient.go

*Issue https://github.com/aws/eks-anywhere-internal/issues/2268*
To ensure the `registry-mirror-secret` is created from EKS-A controller and updated from EKS-A controller we need the role permissions for patch.

Adding permissions for controller packages helm upgrade

---

config/manifest/eksa-components.yaml
config/rbac/role.yaml
controllers/cluster_controller.go

*Issue #https://github.com/aws/eks-anywhere-internal/issues/2268*
eksa controller did not have permissions to read namespaces. The packages helm chart does a lookup to check if namespace needs to be created. This was failing and hence packages were not installed on workload cluster.
```
error calling lookup: namespaces \"eksa-packages-workload\" is forbidden: User \"system:serviceaccount:eksa-system:eksa-controller-manager\" cannot get resource \"namespaces\" in API group \"\" in the namespace \"eksa-packages-workload\"\
``` 

Adding namespaces read permissions to eksa-controller

---

docs/config.toml
docs/layouts/partials/navbar-version-selector.html

This PR adds the logic to navigate to the current page when switching EKS-A versions.

Navigate to same page when switching EKS-A versions

---

internal/pkg/ssm/command.go

*Description of changes:* Increase waiting time for running dummy ssm command. To address the following error during e2e test:
```
2024-04-22T10:28:22.673Z	V-2	Failed running e2e tests for instance	
{
"jobId": "aws-eks-anywhere-test-tinkerbell:371dbb84-1e72-4d38-8e59-90982e6d4aa7-30",
"instanceId": "mi-05f84d7f050847040",
"tests": "TestTinkerbellKubernetes129UbuntuWorkerNodeGroupsTaintsAndLabels",
"status": "fail",
"error": "waiting for ssm in new instance: waiting for ssm to be ready: ssm command returned not successful result Failed: "
}
```
*Testing (if applicable):* NA

Increase ssm wait time during e2e test

---

pkg/clusterapi/etcd.go
pkg/clusterapi/etcd_test.go
pkg/providers/cloudstack/template.go
pkg/providers/common/common.go
pkg/providers/common/common_test.go
pkg/providers/docker/docker.go
pkg/providers/nutanix/template.go
pkg/providers/snow/apibuilder.go
pkg/providers/tinkerbell/template.go
pkg/providers/vsphere/template.go

Related to https://github.com/aws/eks-anywhere/pull/7295
If a user has a management cluster with the new version but workload clusters created from pre 0.17, the eksaversion field is not set as bundlesRef was used then. Due to this for external etcd clusters, there would be a nil dereference, causing a panic in the controller. This will return an empty string if the cluster does not have the eksaversion set, which is usually set when a cluster is upgraded to a newer version.
unit testing and functional testing

Add check for nil eksaversion when setting etcd url

---

release/cli/cmd/release.go
release/cli/pkg/assets/archives/archives.go
release/cli/pkg/assets/config/bundle_release.go
release/cli/pkg/assets/manifests/manifests.go
release/cli/pkg/assets/types/types.go
release/cli/pkg/aws/s3/s3.go
release/cli/pkg/filereader/file_reader.go
release/cli/pkg/operations/upload.go
release/cli/pkg/types/types.go

This PR adds the EKS-A release logic for Ubuntu RTOS image.

Add release logic for Ubuntu RTOS image

---

release/cli/pkg/assets/archives/archives.go
release/cli/pkg/images/images.go
release/cli/pkg/operations/download.go
release/cli/pkg/util/artifacts/artifacts.go

This PR fixes the source path for the Canonical RTOS image for dev release and improves the logging in case of missing artifacts.

Fix dev release, log paths of missing artifacts

---

pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/cluster_test.go
pkg/validations/input_test.go

#7302 
#8016 
Updated the cluster config validation for the cluster name length to be not more than 35 characters. 
Tested locally with a cluster name length of more than 35 characters on docker provider

Update validation for the cluster name length

---

docs/content/en/docs/clustermgmt/cluster-flux.md

The GitOps link in the [docs](https://anywhere.eks.amazonaws.com/docs/clustermgmt/cluster-flux/#gitops-support-optional) is broken. So updating it with the older link from wayback machine. 

Update gitops hyperlink in the docs

---

docs/content/en/docs/whatsnew/changelog.md

Update call out on the packages workflow not working with the latest patch.

Add callout for packages not working with latest patch

---

internal/test/e2e/cloudwatch.go
internal/test/e2e/run.go

*Description of changes:* E2e test results nowadays doesn't provide good observability. This change is aimed to start addressing this issue by adding cloudwatch metrics. It can further allow us to auto cut ticket based on the new e2e test metrics.
*Testing (if applicable):* manually triggered the e2e test and verified new metrics were emitted correctly

Add emitting of e2e test instance metrics

---

cmd/eksctl-anywhere/cmd/common.go
cmd/eksctl-anywhere/cmd/generatepackage.go
cmd/eksctl-anywhere/cmd/installpackagecontroller.go
go.mod

*Issues*
https://github.com/aws/eks-anywhere-internal/issues/2252
https://github.com/aws/eks-anywhere-internal/issues/2270
Below changes ensure that if a customer has a registry mirror setup as part of their EKS-A cluster config; we ensure to perform eksctl anywhere CLI commands for packages using the mirror.
This is significant for folks with an airgapped admin machine; when running these commands the CLI dependencies will know to be pulled from their mirror and not use `public.ecr.aws `.
*Testing:*
```shell
./eksctl-anywhere install packagecontroller -f ./regauth-cluster/regauth-cluster-eks-a-cluster.yaml
./eksctl-anywhere generate package harbor --cluster ramaliar-tink-regauth --kubeconfig ./regauth-cluster/regauth-cluster-eks-a-cluster.kubeconfig
```
By …

CLI commands support for packages in airgapped admin

---

docs/content/en/docs/getting-started/airgapped/airgap-steps.md

Adding the `--insecure` flag to the airgapped docs when running the `eksctl anywhere import images` command to indicate skipping TLS verification when using a self-signed registry mirror.

Update airgapped configuration step

---

docs/content/en/docs/getting-started/baremetal/bare-spec.md
docs/content/en/docs/getting-started/cloudstack/cloud-spec.md
docs/content/en/docs/getting-started/nutanix/nutanix-spec.md
docs/content/en/docs/getting-started/optional/healthchecks.md
docs/content/en/docs/getting-started/snow/snow-spec.md
docs/content/en/docs/getting-started/vsphere/vsphere-spec.md

Add docs for granular MHC timeout and `maxUnhealthy` configuration.

Add docs for granular MHC timeout and `maxUnhealthy` configuration

---

pkg/dependencies/factory.go

On occasion we find the cluster directory created by EKS-A is created with root ownership.
When hostpaths used for bind mounting in Docker don't exist at the time the container is created, dockerd creates the directory. dockerd runs as root on most systems hence the directory is created with root ownership.
This ensures the directory exists before we attempt to launch the tools container that bind mounts the cluster directory.
---
The docker command was demonstrated to be executing before the directory is created through an strace.
```
3195314 21:24:01.454557 execve("/usr/bin/docker", ["docker", "run", "-d", "--name", "eksa_1715203440722790952", "--network", "host", "-w", "/home/chrisdoherty", "-v", "/var/run/docker.sock:/var/run/do"..., "-v", "/home/chrisdoherty:/home/chrisdo"..., "-v", …
```

Fix cluster directory being created with root ownership

---

docs/content/en/docs/clustermgmt/security/manually-renew-certs.md
docs/content/en/docs/troubleshooting/troubleshooting.md

Update Cert Renewal Docs

---

test/e2e/vsphere_test.go

The `TestVSphereKubernetes129To130StackedEtcdRedHatUpgrade` test was using the 1.29 template during the upgrade. Change fixes the test to use 1.30 template during the upgrade.  

Use right RHEL template during 1.30 upgrade

---

docs/content/en/docs/getting-started/cloudstack/cloudstack-getstarted.md
docs/content/en/docs/getting-started/docker/_index.md
docs/content/en/docs/getting-started/nutanix/nutanix-getstarted.md
docs/content/en/docs/getting-started/snow/snow-getstarted.md
docs/content/en/docs/getting-started/vsphere/vsphere-getstarted.md

Update create cluster docs to include command for airgapped env similar to what we have for baremetal [here](https://anywhere.eks.amazonaws.com/docs/getting-started/baremetal/baremetal-getstarted/#:~:text=For%20an%20airgapped%20cluster%20create%2C%20follow%20Preparation%20for%20airgapped%20deployments%20instructions%2C%20then%20type%20the%20following%3A)
make build

Update airgapped env command in create cluster docs

---

pkg/curatedpackages/regional_registry.go
test/e2e/curatedpackages.go
test/e2e/vsphere_test.go
test/framework/cluster.go

Currently we did not have any registry mirror tests that also tried to install curated packages. 
This tests adds support for creating a cluster with registry mirror and having the hello world packages installed and verified after cluster creation.
```
./e2e.test -test.v -test.run "TestVSphereKubernetes129UbuntuAuthenticatedRegistryMirrorCuratedPackagesSimpleFlow"
```

Adding a registry mirror packages test for vsphere

---

test/e2e/SKIPPED_TESTS.yaml
test/e2e/constants.go
test/e2e/docker_test.go

Add 1.30 E2E tests for Docker. 

Add 1-30 E2E tests for Docker

---

.github/workflows/vulnerability.yml

This PR changes the GitHub actions workflow configuration to skip the dependency review and govulncheck actions when only YAML files are changed.

Skip dependency review and govulncheck actions when only YAML files are changed

---

pkg/providers/nutanix/config/cp-template.yaml
pkg/providers/nutanix/controlplane.go
pkg/providers/nutanix/reconciler/reconciler.go
pkg/providers/nutanix/template.go
pkg/providers/nutanix/template_test.go
pkg/providers/nutanix/testdata/expected_cluster_api_additional_trust_bundle.yaml
pkg/providers/nutanix/testdata/expected_cluster_api_server_cert_san_domain_name.yaml
pkg/providers/nutanix/testdata/expected_cluster_api_server_cert_san_ip.yaml
pkg/providers/nutanix/testdata/expected_results_additional_categories.yaml
pkg/providers/nutanix/testdata/expected_results_etcd_encryption.yaml
pkg/providers/nutanix/testdata/expected_results_etcd_encryption_1_29.yaml
pkg/providers/nutanix/testdata/expected_results_external_etcd.yaml
pkg/providers/nutanix/testdata/expected_results_external_etcd_with_optional.yaml
pkg/providers/nutanix/testdata/expected_results_iamauth.yaml
pkg/providers/nutanix/testdata/expected_results_irsa.yaml
pkg/providers/nutanix/testdata/expected_results_node_taints_labels.yaml
pkg/providers/nutanix/testdata/expected_results_oidc.yaml
pkg/providers/nutanix/testdata/expected_results_project.yaml
pkg/providers/nutanix/testdata/expected_results_proxy.yaml
pkg/providers/nutanix/testdata/expected_results_registry_mirror.yaml

Cherry-pick: Fix bug causing installer doesn't create CCM secret for Nutanix worker cluster (#8191)
- fixed templates
- fixed reconciler
- improved tests
**Management cluster**
```
$ eksctl anywhere create cluster -f ./mgmt-cluster.yaml -v10 --bundles-override bin/local-bundle-release.yaml
2024-05-27T10:14:59.817Z	V6	Executing command	{"cmd": "/usr/bin/docker version --format {{.Client.Version}}"}
2024-05-27T10:14:59.838Z	V6	Executing command	{"cmd": "/usr/bin/docker info --format '{{json .MemTotal}}'"}
2024-05-27T10:14:59.888Z	V4	Reading bundles manifest	{"url": "bin/local-bundle-release.yaml"}
2024-05-27T10:14:59.907Z	V4	Using CAPI provider versions	{"Core Cluster API": "v1.6.0+ae39aac", "Kubeadm Bootstrap": "v1.6.0+49ef750", "Kubeadm …
```

Cherry-pick: Fix bug causing installer does not create CCM secret for Nutanix workload cluster (#8191)

---

test/e2e/SKIPPED_TESTS.yaml

Skip 1.30 latest minor tests that are creating a 1.30 cluster using previous release. These tests can be un-skipped once we have 0.20 minor release out as they are expected to only work after that. 

Skip latest minor tests creating 130 cluster on previous release

---

release/cli/pkg/assets/archives/archives.go
release/cli/pkg/assets/config/bundle_release.go
release/cli/pkg/assets/manifests/manifests.go
release/cli/pkg/aws/s3/s3.go
release/cli/pkg/clients/clients.go
release/cli/pkg/filereader/file_reader.go
release/cli/pkg/images/images.go
release/cli/pkg/operations/download.go
release/cli/pkg/operations/upload.go
release/cli/pkg/types/types.go
release/cli/pkg/util/artifacts/artifacts.go
release/cli/pkg/util/release/release.go

This PR adds the logic to download private source artifacts from S3 locally. This is achieved by leveraging the S3 Download Manager which effectively performs a `GetObject` API call on the private object.

Allow downloading private objects from S3

---

pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/cluster_test.go
pkg/api/v1alpha1/testdata/cluster_in_place_upgrade.yaml
pkg/features/features.go
pkg/features/features_test.go
pkg/validations/cluster.go
pkg/validations/cluster_test.go
pkg/validations/createvalidations/preflightvalidations.go
pkg/validations/upgradevalidations/preflightvalidations.go
test/framework/cluster.go

This change removes the feature flag for Kubernetes v1.30 support and makes it the default cluster version.

Remove K8s 1.30 feature flag and default as cluster version

---

docs/content/en/docs/getting-started/baremetal/bare-spec.md
docs/content/en/docs/getting-started/cloudstack/cloud-spec.md
docs/content/en/docs/getting-started/nutanix/nutanix-spec.md
docs/content/en/docs/getting-started/snow/snow-spec.md
docs/content/en/docs/getting-started/vsphere/vsphere-spec.md

Update docs for worker node group config

---

cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml

Fix missing env var error in quick E2E tests by adding Tinkerbell RTOS image env var.

Add Tinkerbell RTOS image env var to quick E2E tests

---

pkg/api/v1alpha1/tinkerbelldatacenterconfig.go
pkg/api/v1alpha1/tinkerbellmachineconfig.go
pkg/api/v1alpha1/tinkerbellmachineconfig_types.go
pkg/providers/tinkerbell/assert_test.go

Update generate command for Tinkerbell to populate Tinkerbell IP in the Datacenter config and OSImage URL in Machine config object as we have defaulted the OS from BR to Ubuntu. This change also adds a check when a modular K8s version is specified with a value above 1.28 and the OS family is set to BR.

Update generate cluster config command for Tinkerbell

---

Makefile
scripts/e2e_test_docker.sh
test/e2e/README.md

Ever since `TestDockerKubernetes125SimpleFlow` was removed from the codebase, no E2E tests have actually been running in presubmits, since the compiled E2E binary would not contain the test that it was being asked to run. This PR updates this to run the Kubernetes 1.30 Docker test which is a part of the test suite.
This PR also updates the bundle manifest URL defined in the Makefile. The URL hardcoded before is the old endpoint which we stopped updating a few months ago. We are now fetching it dynamically from the corresponding release manifest URL, which itself is also dynamically constructed based on the branch.

Update Docker test name for presubmit E2E

---

test/e2e/autoscaler.go
test/e2e/certmanager.go
test/e2e/curatedpackages.go
test/e2e/emissary.go

This PR cleans up the same function used for different packages in e2e tests and renames it for better clarity.
make eks-a, make lint, make unit-test, make e2e-cross-platform

Cleanup duplicate code in curated packages and rename function

---

docs/content/en/docs/osmgmt/artifacts.md

Updating this support matrix because it is misleading.
Ubuntu Raw builds only support EFI firmware, when you try to build one with bios enabled says it's not supported . 
```
image-builder@cxbrowne-dev:/home/eksadmin/workplace/cxbrowne-mgmt$ image-builder build --os ubuntu --hypervisor baremetal --release-channel 1-28 --firmware bios
Creating builder config
2024/05/31 14:08:23 Ubuntu Raw builds only support EFI firmware.
```

Update image-build support for baremental ubutu to uefi mode only

---

cmd/eksctl-anywhere/cmd/applypackages.go
cmd/eksctl-anywhere/cmd/createpackages.go
cmd/eksctl-anywhere/cmd/deletepackages.go
cmd/eksctl-anywhere/cmd/describepackages.go
cmd/eksctl-anywhere/cmd/getpackage.go
cmd/eksctl-anywhere/cmd/getpackagebundle.go
cmd/eksctl-anywhere/cmd/getpackagebundlecontroller.go
cmd/eksctl-anywhere/cmd/installpackages.go
cmd/eksctl-anywhere/cmd/upgradepackages.go
docs/content/en/docs/packages/packagebundles.md

*Issue https://github.com/aws/eks-anywhere-internal/issues/2270*
As described in the issue we want to mark packages commands as deprecated. For release v0.20.0 the commands are still present and in the next release we would remove the commands themselves.
*Documentation added/planned:*
Will update the docs and call out that these commands are not supported.

Marking packages commands as deprecated

---

docs/content/en/docs/getting-started/baremetal/bare-spec.md
docs/content/en/docs/getting-started/cloudstack/cloud-spec.md
docs/content/en/docs/getting-started/nutanix/nutanix-spec.md
docs/content/en/docs/getting-started/snow/snow-spec.md
docs/content/en/docs/getting-started/vsphere/vsphere-spec.md

Updated docs to change the worker nodes count field from "required" to "optional" and specifying the default value as 1.
make build

Update docs to make worker nodes count optional

---

designs/handle-autoscaler-cluster-status-reconciliation.md
docs/content/en/docs/clustermgmt/cluster-status.md
docs/content/en/docs/getting-started/baremetal/bare-spec.md
docs/content/en/docs/getting-started/cloudstack/cloud-spec.md
docs/content/en/docs/getting-started/nutanix/nutanix-spec.md
docs/content/en/docs/getting-started/optional/autoscaling.md
docs/content/en/docs/getting-started/snow/snow-spec.md
docs/content/en/docs/getting-started/vsphere/vsphere-spec.md
pkg/api/v1alpha1/condition_consts.go
pkg/clusterapi/autoscaler.go
pkg/controller/clusters/status.go
pkg/controller/clusters/status_test.go
pkg/providers/cloudstack/config/template-md.yaml
pkg/providers/cloudstack/testdata/expected_results_main_autoscaling_md.yaml
pkg/providers/docker/config/template-md.yaml
pkg/providers/docker/testdata/valid_autoscaler_deployment_md_expected.yaml
pkg/providers/nutanix/config/md-template.yaml
pkg/providers/nutanix/testdata/expected_results_autoscaling_md.yaml
pkg/providers/tinkerbell/config/template-md.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_autoscaler_md.yaml
pkg/providers/vsphere/config/template-md.yaml
pkg/providers/vsphere/testdata/expected_results_minimal_autoscaling_md.yaml
test/e2e/autoscaler.go
test/e2e/vsphere_test.go
test/framework/cluster.go
test/framework/testdata/autoscaler_package_workload_cluster.yaml

[#2231](https://github.com/aws/eks-anywhere-internal/issues/2231)
This PR updates the cluster status reconciliation logic for `workersReady` condition when the cluster autoscaler is configured to scale the worker nodes. It also removes the `replicas` field from the md template for worker node groups which have autoscaling configured. E2E test has been added to verify that the cluster status becomes ready when autoscaler is configured to scale the worker nodes.
Ran the E2E test case locally in vSphere Dev environment and it passed:
```
make local-e2e
```
Ran the following commands to test the EKS-A cli and e2e test binaries:
```
make eks-a
make e2e-cross-platform
```
Ran the following commands to check for …

Handle cluster status reconcile autoscaler

---

pkg/clusterapi/workers.go
pkg/clusterapi/workers_test.go
pkg/crypto/tls.go
pkg/providers/tinkerbell/config/template-cp.yaml
pkg/providers/tinkerbell/config/template-md.yaml
pkg/providers/tinkerbell/template.go
pkg/providers/tinkerbell/template_test.go
pkg/providers/tinkerbell/testdata/expected_kcp.yaml
pkg/providers/tinkerbell/testdata/expected_kct.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md_node_labels.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md_node_worker_version.yaml

This PR adds a new field KubeletConfiguration in the eksa spec for control plane and worker node configuration. This is an unstructured object that is of the kind value KubeletConfiguration. This PR adds the code for Tinkerbell provider.
- unit tests
- e2e tests

Kubelet Configuration for cp and wn Tinkerbell

---

docs/content/en/docs/packages/legacypackagesregions.md
docs/content/en/docs/packages/packagecontroller.md
docs/content/en/docs/packages/packagesecrmigration.md
docs/content/en/docs/packages/prereq.md

*Issue https://github.com/aws/eks-anywhere-internal/issues/2141*
Adding documentation for the steps that a user needs to perform to migrate their cluster to use an EKS Enterprise subscription granted regional curated packages from the legacy ECR registries. 

Adding docs for regional packages migration

---

pkg/providers/cloudstack/config/template-cp.yaml
pkg/providers/cloudstack/config/template-md.yaml
pkg/providers/cloudstack/template.go
pkg/providers/cloudstack/template_test.go
pkg/providers/cloudstack/testdata/expected_kcp.yaml
pkg/providers/cloudstack/testdata/expected_kct.yaml
pkg/providers/docker/config/template-cp.yaml
pkg/providers/docker/config/template-md.yaml
pkg/providers/docker/controlplane_test.go
pkg/providers/docker/docker.go
pkg/providers/docker/docker_test.go
pkg/providers/docker/reconciler/reconciler_test.go
pkg/providers/docker/testdata/valid_deployment_node_labels_cp_expected.yaml
pkg/providers/docker/testdata/valid_deployment_node_labels_md_expected.yaml
pkg/providers/nutanix/config/cp-template.yaml
pkg/providers/nutanix/config/md-template.yaml
pkg/providers/nutanix/template.go
pkg/providers/nutanix/template_test.go
pkg/providers/nutanix/testdata/expected_cp.yaml
pkg/providers/nutanix/testdata/expected_wn.yaml
pkg/providers/vsphere/config/template-cp.yaml
pkg/providers/vsphere/config/template-md.yaml
pkg/providers/vsphere/template.go
pkg/providers/vsphere/template_test.go
pkg/providers/vsphere/testdata/expected_kcp.yaml
pkg/providers/vsphere/testdata/expected_kct.yaml
pkg/providers/vsphere/testdata/expected_results_main_node_labels_md.yaml

This PR sets the kubelet configuration with `providerID` (Cloudstack) and `cloud-provider` (vSphere, Nutanix) setting which will be blocked for users to set. This setting is set by EKSA for kubelet extra args if Kubelet Configuration is not used.
- unit test
- E2E test

Remove kubelet extra args when kubelet configuration is set

---

designs/kubelet-cinfiguration.md

Doc for Kubelet Configuration

---

release/cli/pkg/assets/config/bundle_release.go
release/cli/pkg/operations/testdata/main-bundle-release.yaml

Set asset name to have -helm suffix for new tinkerbell charts so that they are handled properly for bundle creation.

Set asset name to have -helm suffix for new tinkerbell charts

---

pkg/api/v1alpha1/cluster.go
pkg/validations/cluster.go
pkg/validations/cluster_test.go
pkg/validations/createvalidations/preflightvalidations.go
pkg/validations/createvalidations/preflightvalidations_test.go
pkg/validations/upgradevalidations/preflightvalidations.go
pkg/validations/upgradevalidations/preflightvalidations_test.go

BR limited settings validations for Kubelet configuration. Bottlerocket only supports a subset of settings for Kubelet Configuration. This PR validates and makes sure that only those are configured in the cluster when Bottlerocket is being used. This PR includes preflights for CLI. Another PR will be created for controller validations.
- unit test
- E2E test

BR limited settings validations for Kubelet configuration

---

pkg/providers/vsphere/testdata/cluster_main_stacked_etcd.yaml
pkg/providers/vsphere/vsphere.go
pkg/providers/vsphere/vsphere_test.go

The vSphere datastore usage logic for `etcd` machine configs has a bug in the specific scenario where we upgrade from a stacked etcd cluster to an unstacked etcd cluster. In this case, the previous cluster's `ExternalEtcdConfiguration` object will be `nil`, but we try to access its `Count` field without checking for `nil`ness, which causes a panic in the validation phase. This PR adds a `nil` check to the object so that we can safely dereference it, along with unit tests to cover this logic.

Fix NPE in vSphere etcd machine datastore usage calculation

---

pkg/providers/tinkerbell/tinkerbell_test.go
pkg/providers/tinkerbell/upgrade.go

*Issue https://github.com/aws/eks-anywhere/issues/8190:*
In previous EKSA upgrade workflows we had operations that were performed on a bootstrap (KinD cluster) after it came up and after CAPI was installed on it.
https://github.com/aws/eks-anywhere/blob/main/pkg/providers/tinkerbell/upgrade.go#L186
https://github.com/aws/eks-anywhere/blob/main/pkg/providers/tinkerbell/upgrade.go#L208
Now looks like these are getting skipped since we have removed the KinD cluster requirement for upgrading. That lead to the above issue. These changes add back the steps for management and workload cluster upgrades. 
*Testing:*
```
./eksctl-anywhere upgrade cluster -f ./cluster.yaml -z ./new-node0102.csv
```
By submitting this pull request, I confirm that you can use, modify, copy, …

Adding logic to apply new hardware on tink upgrades

---

cmd/eksctl-anywhere/cmd/generatepackage.go
cmd/eksctl-anywhere/cmd/listpackages.go
pkg/curatedpackages/validations.go
pkg/curatedpackages/validations_test.go

*Issue https://github.com/aws/eks-anywhere-internal/issues/2270*
Added support for `list packages` in an air gapped admin env.
*Testing:*
```bash
./eksctl anywhere list packages --cluster airgap-cluster  --bundles-override ./release-bundle.yaml -v6
```

Adding airgap support for list packages command

---

release/cli/go.mod

Vulnerability checks were failing on release/cli. Bumping golang patch version to fix CVE
```
govulncheck -C ./release/cli -format text ./...
```

Bump patch version for golang

---

go.mod
go.sum

Update new CAPI tag for https://github.com/abhay-krishna/cluster-api/tree/v1.6.0-eksa.2

Update new CAPI tag

---

release/cli/pkg/bundles/tinkerbell.go
release/cli/pkg/operations/testdata/main-bundle-release.yaml

The asset name for Tinkerbell stack and CRDs Helm chart has the Helm suffix in `config/bundle_release.go`, which gets set as the key, so we need to use the same to fetch it from the map.

Fix asset name for Tinkerbell stack and CRDs artifacts in bundle

---

pkg/providers/tinkerbell/stack/stack.go
pkg/providers/tinkerbell/stack/stack_test.go
pkg/providers/tinkerbell/stack/testdata/expected_upgrade.yaml
pkg/providers/tinkerbell/stack/testdata/expected_upgrade_with_proxy.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_docker.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_kubernetes.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_docker_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_hook_override.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_false.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_true.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_kubernetes_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_false.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_true.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_proxy_config.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_registry_mirror.yaml

Nginx images were not getting overridden properly in the values file. This makes sure we are overriding the nginx image in the tinkerbell stack chart with the one in our bundles.

Override the nginx image properly in tinkerbell stack chart

---

docs/content/en/docs/packages/prometheus/prometheus_grafana.md
test/framework/cluster.go

Prometheus e2e test were failing with the error:
`
cluster.go:1814: Reading package generated-prometheus pod prometheus-server logs
cluster.go:1817: unable to get name of the prometheus-server pod: error: error executing jsonpath "'{.items[0].metadata.name}'": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
`
In the recent upgrade pod labels for prometheus charts were updated from `app=prometheus,component=server` to
`app.kubernetes.io/name=prometheus,app.kubernetes.io/component=server`, because of which above issue occured, update the prometheus label in `VerifyPrometheusPrometheusServerStates` method.
```
export LOCAL_E2E_TESTS=TestDockerKubernetes127CuratedPackagesPrometheusSimpleFlow
make local-e2e
```
By …

Updated prometheus pod labels for e2e test

---

release/cli/pkg/bundles/tinkerbell.go
release/cli/pkg/operations/testdata/main-bundle-release.yaml
release/cli/pkg/operations/upload.go

The Chart.yaml for Tinkerbell stack and CRDs did not have the modified Helm chart version with the release tag so the images were getting imported to Harbor with the incorrect Chart version. This caused issues during cluster creation when pulling images because Harbor did not have the tags matching the image URIs that were requested from the bundle.

Ensure Chart.yaml is modified for Tinkerbell stack and CRDs Helm charts

---

pkg/providers/tinkerbell/stack/stack.go

Fix issue where incorrect additional flags were being passed to the helm upgrade command. Pass in empty additional flags if none are provided to prevent reusing the flags from a previous helm command. 
We might want to revisit the logic regarding passing in helm opts to the upgrade and uninstall helm commands. We currently need it due to the changing `NO_PROXY` values during the create/upgrade flow using proxy configs. 

Fix issue where incorrect flag is getting passed to helm commands

---

internal/test/e2e/setup.go

The pre and post vm cleanup steps were failing with for cloudstack (an probably other providers) on the release branch
```
2024-06-17T05:38:03.656Z V0 virtual machines not found {"cluster": "release-0-20"}
```
We run the clean up commands before and after tests passing a `CLUSTER_PREFIX` based on the branch name. However, during setup, we seem to trim the branch name down to 7 characters when constructing the cluster name, thus, only having  "release" as the prefix
Removing the trim on the branch name preserves the full branch name, enabling us to run cleanups based on release branch name as the `CLUSTER_PREFIX`.
Additionally, the cluster name can only be < 36 characters, but we handle that by an overall trim before returning the cluster …

Ensure release branch is prefix of test cluster names

---

internal/pkg/ssm/run_output.go
internal/test/e2e/run.go

*Issue #, if available:* E2E test runner can quit unexpectedly, leaving no track to debug.
*Description of changes:* Log ssm status details which could explain why a test runner quitted. 
From AWS SDK doc: 
```
StatusDetails can be one of the following values:
Pending: The command hasn't been sent to the managed node.
In Progress: The command has been sent to the managed node but hasn't reached a terminal state.
Delayed: The system attempted to send the command to the target, but the target wasn't available. The managed node might not be available because of network issues, because the node was stopped, or for similar reasons. The system will try to send the command again.
Success: The command or plugin ran successfully. This is a terminal state.
Delivery Timed Out: The command wasn't …
```

Log ssm command details when an e2e test finishes

---

pkg/providers/tinkerbell/stack/stack.go
pkg/providers/tinkerbell/stack/stack_test.go
pkg/providers/tinkerbell/stack/testdata/expected_upgrade.yaml
pkg/providers/tinkerbell/stack/testdata/expected_upgrade_with_proxy.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_docker.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_kubernetes.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_docker_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_hook_override.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_false.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_true.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_kubernetes_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_false.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_true.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_proxy_config.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_registry_mirror.yaml

registry username and registry password is now expected as key value pairs of `SMEE_EXTRA_KERNEL_ARGS`. This PR updates how we set the registry username and password to be what is expected by the new version of smee.

Set registry username and password as expected with new tink stack

---

cmd/integration_test/build/script/create_infra_config.sh
scripts/e2e_test_docker.sh
test/e2e/E2E_AMI_FILTER_VARS

This PR adds the logic to dynamically fetch the latest AMI ID to use for E2E tests. We do this by calling the `DescribeImages` API with filters for the name, description and owner and then getting the latest image by creation time.

Fetch latest E2E test AMI ID dynamically

---

scripts/brew_formula_pr.sh
scripts/brew_formula_update.sh
scripts/common.sh
scripts/eks-anywhere.rb.tmpl

This PR improves the Brew update script to support updating Brew formulae for both the latest and second latest versions of EKS Anywhere.
Tested by generating a Brew formula for release-0.18 and installing from source and verifying the installed binary is good to use
```console
$ brew install --build-from-source Formula/eks-anywhere@0.18.rb
...
Fetching eks-anywhere@0.18
==> Downloading https://anywhere-assets.eks.amazonaws.com/releases/eks-a/59/artifacts/eks-a/v0.18.7/darwin/arm64/eksctl-anywhere
...
Installing eks-anywhere@0.18
...
$ eksctl anywhere version
Version: v0.18.7
Bundle Manifest URL: https://anywhere-assets.eks.amazonaws.com/releases/bundles/59/manifest.yaml                           
``` …

Support installing previous version of EKS-A CLI using Homebrew

---

pkg/dependencies/factory.go

Lots of E2E tests were failing timing out while a delete was in progress. Shorten the delete timeout to 30 mins so that we can more determine whether the test runners timed out or if the test timed out trying to delete.

Change delete timeout to 30 mins

---

release/cli/pkg/clients/clients.go

Create S3 downloader using source session instead of release session.

Create S3 downloader using source session instead of release session

---

internal/test/e2e/setup.go

Revert "Ensure release branch is prefix of test cluster names"

---

release/cli/pkg/assets/archives/archives.go
release/cli/pkg/assets/config/bundle_release.go
release/cli/pkg/assets/types/types.go
release/cli/pkg/constants/constants.go
release/cli/pkg/operations/upload.go
release/cli/pkg/types/types.go

Adding logic to upload RTOS artifacts to separate production bucket

Upload RTOS artifacts to separate bucket

---

release/cli/pkg/assets/archives/archives.go
release/cli/pkg/assets/config/bundle_release.go
release/cli/pkg/assets/tagger/tagger.go
release/cli/pkg/filereader/file_reader.go

Update RTOS image destination on S3 to include image release date.

Update RTOS image destination on S3

---

test/e2e/metallb.go

Metallb e2e tests were failing when running the BGP configuration test case. This is due to our tests statically defining what the expected `bgppeers.metallb.io` resource should have in the spec field. Defined here: https://github.com/aws/eks-anywhere/blob/main/test/e2e/metallb.go#L320
With the new version bump of metallb, they added support for BGP disableMP, which defaults to false. This results in `bgppeers.metallb.io`  to have an extra line in its spec, which differs from the statically defined "expected". Updated the expected value in the e2e.
prev spec: 
```
keepaliveTime: 30s
myASN: 123
peerASN: 55001
peerAddress: 12.2.4.2
peerPort: 179
```
current spec:
```
disableMP: false
keepaliveTime: 30s
myASN: 123
peerASN: 55001
peerAddress: …
```

Update expected values in MetalLB E2E tests based on the upstream updates

---

internal/pkg/ssm/run_output.go

Fix a nil pointer error

---

release/cli/pkg/helm/helm.go

Include Helm chart name in push error for easier debugging.

Include Helm chart name in push error

---

docs/content/en/docs/whatsnew/changelog.md

Add change log for release v0.20.0

Add changelog  for release v0.20.0

---

docs/content/en/docs/clustermgmt/cluster-delete.md
docs/content/en/docs/getting-started/baremetal/tinkerbell-overview.md

The tinkerbell boots service has been renamed to smee upstream. Update the docs to mention boots and smee refer to the same service.

Update boots reference in baremetal docs

---

cmd/integration_test/build/buildspecs/build-eks-a-cli.yml
cmd/integration_test/build/script/create_infra_config.sh

The changes fixes the error when running create_infra_config.sh
```
Running command source ${CODEBUILD_SRC_DIR}/cmd/integration_test/build/script/create_infra_config.sh
++ set -o pipefail
+++ git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /codebuild)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
++ REPO_ROOT=
```

Fixing dir for sourcing E2E_AMI_FILTER_VARS

---

.github/dependabot.yaml

Having one PR per module can be annoying. On top of that, a lot of the times, changes in main have effects in the release module (since we do an import with a replace from disk).
The drawback of this change is that when code changes are required for a particular module, the go.mod change will be mixed with other modules, thus requiring us to separate the problematic node from the rest before merging. From the experience running this bot during the past few months, there is usually no work to do except to approve, no code required most of the time. Hence this will reduce the amount of PRs we need to review and the amount of time we need to manually update them to simply run go mod tidy. …

Group all dependabot go changes in one PR a week

---

docs/content/en/docs/getting-started/optional/hostOSConfig.md
docs/content/en/docs/getting-started/optional/kubeletconfig.md

Documentation for Kubelet Configuration

Documentation for Kubelet Configuration

---

.github/workflows/vulnerability.yml

For some reason, we can't use `go 1.22` in the release/cli go.mod. It needs to have a patch version of `go mod tidy` will change it. I'm not sure why this is, since not specifying the patch is completely valid. I suspect one of our dependencies has set 1.22.0 in their go.mod, and that makes it a requirement for us, which is annoying.
The issue with selecting a particular patch is that, when a new version of go is required bc of a CVE, govulncheck will fail until the the go.mod is updated, it won't pull the latest version.
For now, we update the github action so we set the go version explicitly instead of reading from the go.mod file.
The drawback is the github action will also need to be updated when we bump to 1.23. But probably not a big deal.
*Documentation added/planned (if …

Set go version in govulncheck action for release

---

pkg/api/v1alpha1/condition_consts.go
pkg/controller/clusters/status.go
pkg/controller/clusters/status_test.go

[#2383](https://github.com/aws/eks-anywhere-internal/issues/2383)
Added a check on the `Ready` condition for the kcp and md objects as a final validation before marking the `controlPlaneReady` and `workersReady` condition to `True` in the cluster status.
make eks-a
make unit-test
make lint

Update cluster status

---

.github/dependabot.yaml

Ignore CAPI provider modules in dependabot config

---

test/framework/kubeletconfig.go

Fix get worker node logic for Kubelet config e2e. Tinkerbell tests had a different naming for nodes which caused failures for Kubelet config e2e tests.
- e2e

Fix get worker node logic for Kubelet config e2e

---

release/cli/pkg/bundles/package-controller.go
release/cli/pkg/helm/helm.go

Using sourceImageURI for packages Helm chart modifications.

Use sourceImageURI for packages Helm chart modifications

---

cmd/eksctl-anywhere/cmd/createcluster.go
pkg/workflows/management/create_install_eksa.go
pkg/workflows/management/create_move_capi.go
pkg/workflows/management/create_test.go
pkg/workflows/management/create_workload.go

This removes the confusion in the CLI logs when creating a management cluster as the log lines say it's creating a workload cluster. This is a leak of implementation details about how clusters are created. While CAPI calls the initial cluster a workload cluster and then pivots its control plane objects to make it a permanent management cluster this is an implementation detail we shouldn't expose to users. 

Update CLI logging output to be cluster type aware:

---

docs/content/en/docs/getting-started/baremetal/tinkerbell-overview.md

Fix link to tinkerbell docs (old URL no longer resolves)

fix tinkerbell doc link

---

pkg/cluster/cloudstack.go
pkg/cluster/cloudstack_test.go
pkg/cluster/docker.go
pkg/cluster/docker_test.go
pkg/cluster/nutanix.go
pkg/cluster/nutanix_test.go
pkg/cluster/tinkerbell.go
pkg/cluster/tinkerbell_test.go
pkg/cluster/vsphere.go
pkg/cluster/vsphere_test.go

When the config parser is unable to find a object such as Datacenter/MachineConfig due to a typo in the DatacenterRef name (or if it was never passed in the spec), parser just doesn't set that object and doesn't do any validations around it. Accessing those objects later leads to a panic at runtime. 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x148 pc=0x103493f20]
```
This change adds validations on the config, around the Datacenter obj if it's not found in the config to explicitly error out.
```
Error: unable to get cluster config from file: invalid cluster config: VSphereDatacenterConfig name rahul-130-br-tst1 not found
```
Fixes #7531  …

Fix panic when datacenter obj is not found

---

pkg/providers/nutanix/validator.go
pkg/providers/nutanix/validator_test.go

Fix Subnet Validation Bug for Nutanix provider
- fixed a bug causing subnet validation to be unaware of the cluster context
- made subnet requests by name cluster-aware
- updated unit tests to reflect these changes
```
$ eksctl anywhere create cluster -f cluster-aware-net.yaml --bundles-override bin/local-bundle-release.yaml -v10
2024-07-09T15:11:47.827Z	V6	Executing command	{"cmd": "/usr/bin/docker version --format {{.Client.Version}}"}
2024-07-09T15:11:47.849Z	V6	Executing command	{"cmd": "/usr/bin/docker info --format '{{json .MemTotal}}'"}
2024-07-09T15:11:47.904Z	V4	Reading bundles manifest	{"url": "bin/local-bundle-release.yaml"}
2024-07-09T15:11:47.924Z	V4	Using CAPI provider versions	{"Core Cluster API": "v1.7.2+96bbfc2", …
```

Fix Subnet Validation Bug for Nutanix provider

---

test/e2e/docker_test.go
test/e2e/suite.go
test/e2e/upgrade_from_latest.go
test/e2e/vsphere_test.go

This is a manual cherry-pick of https://github.com/aws/eks-anywhere/pull/8325

[release-0.19] Fix e2e tests creating old bundle workload clusters

---

internal/pkg/ssm/run_output.go
internal/test/e2e/run.go

This is a manual cherry-pick of https://github.com/aws/eks-anywhere/pull/8313

[release-0.19] Log ssm command details when an e2e test finishes

---

internal/test/e2e/run.go
internal/test/e2e/tinkerbell_hardware_queue.go

Shuffle hardware inventory before reserving hardware for Tinkerbell E2E tests. As we run quick e2e more frequently the boot entries on the boot list get populated quickly leading to an error when there's no space left to add to that boot list. Ideally we should have an automation around removing the boot entries periodically on the BMCs but until then we should try reserving the hardware  in random order for quick test to not burden the boot entries on the first few hardware. Also, with randomness we reduce the likelihood of picking up an erroneous hardware in case during repetitive quick E2E runs.
Kicked of [run](https://tiny.amazon.com/10c5mxgd8/IsenLink) against my branch and verified that the hardware reserved for the test were …

Shuffle hardware inventory for tinkerbell before reservation

---

pkg/cluster/cloudstack.go
pkg/cluster/cloudstack_test.go
pkg/cluster/nutanix.go
pkg/cluster/nutanix_test.go
pkg/cluster/testdata/cluster_tinkerbell_1_19.yaml
pkg/cluster/tinkerbell.go
pkg/cluster/tinkerbell_test.go
pkg/cluster/vsphere.go
pkg/cluster/vsphere_test.go

When the config parser is unable to find a object such as Datacenter/MachineConfig due to a typo in the MachineGroupRef name (or if it was never passed in the spec), parser just doesn't set that object and doesn't do any validations around it. Accessing those objects later leads to a panic at runtime.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x148 pc=0x103493f20]
```
This change adds validations on the config, around the MachineConfig obj if it's not found in the config to explicitly error out.
```
Error: unable to get cluster config from file: invalid cluster config: VSphereMachineConfig name rahul-130-br-tst-cp1 not found
```
Tested manually by …

Fix machine config panic when ref object not found

---

Makefile
config/crd/bases/anywhere.eks.amazonaws.com_awsdatacenterconfigs.yaml
config/crd/bases/anywhere.eks.amazonaws.com_awsiamconfigs.yaml
config/crd/bases/anywhere.eks.amazonaws.com_cloudstackdatacenterconfigs.yaml
config/crd/bases/anywhere.eks.amazonaws.com_cloudstackmachineconfigs.yaml
config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml
config/crd/bases/anywhere.eks.amazonaws.com_controlplaneupgrades.yaml
config/crd/bases/anywhere.eks.amazonaws.com_dockerdatacenterconfigs.yaml
config/crd/bases/anywhere.eks.amazonaws.com_fluxconfigs.yaml
config/crd/bases/anywhere.eks.amazonaws.com_gitopsconfigs.yaml
config/crd/bases/anywhere.eks.amazonaws.com_machinedeploymentupgrades.yaml
config/crd/bases/anywhere.eks.amazonaws.com_nodeupgrades.yaml
config/crd/bases/anywhere.eks.amazonaws.com_nutanixdatacenterconfigs.yaml
config/crd/bases/anywhere.eks.amazonaws.com_nutanixmachineconfigs.yaml
config/crd/bases/anywhere.eks.amazonaws.com_oidcconfigs.yaml
config/crd/bases/anywhere.eks.amazonaws.com_snowdatacenterconfigs.yaml
config/crd/bases/anywhere.eks.amazonaws.com_snowippools.yaml
config/crd/bases/anywhere.eks.amazonaws.com_snowmachineconfigs.yaml
config/crd/bases/anywhere.eks.amazonaws.com_tinkerbelldatacenterconfigs.yaml
config/crd/bases/anywhere.eks.amazonaws.com_tinkerbellmachineconfigs.yaml
config/crd/bases/anywhere.eks.amazonaws.com_tinkerbelltemplateconfigs.yaml
config/crd/bases/anywhere.eks.amazonaws.com_vspheredatacenterconfigs.yaml
config/crd/bases/anywhere.eks.amazonaws.com_vspheremachineconfigs.yaml
config/manifest/eksa-components.yaml
config/rbac/role.yaml
config/webhook/manifests.yaml

Update controller-gen version to v0.8.0
*Observations:*
For v0.9.0 and above, `make generate` fails because it couldn't find `go.mod` file in the [internal/aws-sdk-go-v2](https://github.com/aws/eks-anywhere/tree/main/internal/aws-sdk-go-v2) folder since the [replace](https://github.com/aws/eks-anywhere/blob/71a3e4e939c136cfa9dfe0e1d17b57dff11072d6/internal/aws-sdk-go-v2/internal/configsources/go.mod#L9) directive in multiple `go.mod` files expects that file to be present there.
For v0.15.0(latest), it requires go1.22 and currently the main go module is on [1.21](https://github.com/aws/eks-anywhere/blob/71a3e4e939c136cfa9dfe0e1d17b57dff11072d6/go.mod#L3)
make generate
make generate-manifests
make release-manifests
Created a docker …

Bump controller-gen version to v0.8.0

---

docs/content/en/docs/clustermgmt/security/manually-renew-certs.md

*Description of changes:* Elaborate the note when kubelet service failed to start, due to cert expiration.
*Testing (if applicable):* Manually checked the new doc with `hugo serve`

Elaborate the note when kubelet service failed to start

---

pkg/providers/tinkerbell/stack/stack.go
pkg/providers/tinkerbell/stack/testdata/expected_upgrade.yaml
pkg/providers/tinkerbell/stack/testdata/expected_upgrade_with_proxy.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_docker.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_kubernetes.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_docker_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_hook_override.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_false.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_true.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_kubernetes_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_false.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_true.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_proxy_config.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_registry_mirror.yaml

Enable `lb_class_only` env var on kube-vip so that it only manages IP for services with LoadBalancerClass set to `kube-vip.io/kube-vip-class` on the service. Without this env var, kube-vip is trying to manage IPs for any service requesting for a Load Balancer IP which isn't expected.  

Enable lb_class_only env var in tink stack kubevip

---

docs/content/en/docs/concepts/support-versions.md

Adding docs to reflect the N-1 EKS-A version support policy.

Add docs for N-1 EKS-A version support

---

docs/data/version_support.yml

Kubernetes version 1.30 support was added in EKS-A with release 0.20. Capture 1.30 as list of supported versions in the docs. 

Add K8s version 1.30 to supported versions list

---

pkg/curatedpackages/packagecontrollerclient.go
pkg/curatedpackages/packagecontrollerclient_test.go
pkg/curatedpackages/packagereader_test.go
pkg/curatedpackages/reader.go
pkg/curatedpackages/regional_registry.go
pkg/curatedpackages/registry_constants.go
pkg/docker/registry.go
pkg/docker/registry_test.go
pkg/executables/docker.go

Use correct registries to integrate with new packages workflows.

Use correct registries to integrate with new packages workflows

---

pkg/providers/tinkerbell/stack/stack.go
pkg/providers/tinkerbell/stack/testdata/expected_upgrade.yaml
pkg/providers/tinkerbell/stack/testdata/expected_upgrade_with_proxy.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_docker.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_kubernetes.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_docker_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_hook_override.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_false.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_true.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_kubernetes_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_false.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_true.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_proxy_config.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_registry_mirror.yaml

The tink-relay and relay-init images did not reference the URI in the bundle properly.

Fix tink-relay and tink-relay-init images

---

docs/content/en/docs/clustermgmt/security/manually-renew-certs.md

Our documentation manual cert renewal section, missed covering manual renewal of Kubelet client-cert on worker nodes in case they expire. Add documentation to manually renew them for worker nodes.  

Add docs for worker node kubelet client cert manual renewal

---

pkg/executables/sonobuoy.go
test/framework/conformance.go

The 129 and 130 conformance tests are failing currently because we are using the `e2e-skip` flag along with `--mode` flag, which is disallowed. 
This is from the test logs
```
conformance.go:68: Error running k8s conformance tests: executing sonobuoy: Error: mode flag and e2e-focus/skip flags both provided and may cause unintended behavior
```
To get around it and get the conformance tests passing, we are going to run 129 and 130 in the default mode so the validation doesn't fail. We can change this behavior to run with `--mode=certified-conformance` once we stop using `e2e-skip` for these versions.
Ran and verified the tests locally. …

Run conformance for 1.29 and above in default mode

---

pkg/curatedpackages/regional_registry.go

Check against regional public ECR for getting registry since we are using the same registry for testing regional and non-regional.

Check against regional public ECR for getting registry

---

release/cli/pkg/assets/archives/archives.go
release/cli/pkg/assets/config/bundle_release.go
release/cli/pkg/assets/tagger/tagger.go
release/cli/pkg/assets/types/types.go
release/cli/pkg/constants/constants.go
release/cli/pkg/filereader/file_reader.go
release/cli/pkg/operations/testdata/main-bundle-release.yaml
release/cli/pkg/operations/upload.go
release/cli/pkg/types/types.go

Remove release logic for RTOS images.

Remove release logic for RTOS images

---

docs/content/en/docs/clustermgmt/security/manually-renew-certs.md
docs/content/en/docs/troubleshooting/troubleshooting.md

*Issue #, if available:* https://github.com/aws/eks-anywhere-internal/issues/2452
*Description of changes:* We have documented the steps to check certificate expiration from within the nodes, but we had not previously covered how to perform this check from outside the nodes. The newly added steps address this gap, providing a useful method for automated certificate health checks

Add some quick commands for checking certificates

---

pkg/providers/common/common.go
pkg/providers/vsphere/template_test.go
pkg/providers/vsphere/testdata/expected_kcp_br_ntp.yaml

Fix Kubelet Configuration apply when host OS config is specified
https://github.com/aws/eks-anywhere/issues/8594
Cherrypick from https://github.com/aws/eks-anywhere/pull/8602
- unit test
- e2e test

Fix Kubelet Configuration apply when host OS config is specified (#8602)

---

docs/content/en/docs/packages/emissary/addemissary.md

*Description of changes:* customers have encountered emissary certificate expiring issue. The issue is fixed in their 4.0 release, but before that version, users have to manually rotate the certificate
*Testing (if applicable):* Manually tested the renewal steps in my dev environment

Document manual certificate renewal requirement for Emissary

---

test/e2e/SKIPPED_TESTS.yaml

Proxy config tests were skipped initially for cloudstack as we moved our Cloudstack env to Colo lab and didn't have proxy setup in the lab. Currently we do have a proxy configured for the lab which runs on the following address: `10.80.148.64:3128`. Updated the secrets manager to point to the given proxy and verified that the tests are pull from the proxy in the lab. Here's a quick test run on Cloudstack for just proxy tests: https://tiny.amazon.com/tm7ntzfv/IsenLink  

Unskip cloudstack proxy config tests

---

release/scripts/announce_eksa_release.sh

Because the latest version field does not change unless there's an update to the latest minor version, this script will send out announcements with the latest EKS-A minor release for patch releases for the `n-1` minor version. We fix this by getting the latest version based on the release that was last added to the list.

Fix latest EKS-A version assignment in announcement script

---

Makefile
scripts/eksa_version.sh

This PR adds some fixes to the EKS-A version assignment script:
1. Ensure checks are done on upstream remote when running locally to avoid out-of-date origin remote
2. Get latest tag for main builds from release manifest instead of Git tag chronological listing because if the latest release is an `n-1` release, it would provide an incorrect version
3. Extract minor release info from ancestor branch instead of using it directly.
4. Typo fix

Fix release version assignment for main and release branches

---

test/e2e/SKIPPED_TESTS.yaml

`TestTinkerbellKubernetes125UbuntuTo129MultipleUpgrade` was skipped as the test failed consitently on CI runs. on checking the logs from the runs the test consistently failed while upgrading to K8s version 1.28. Suspect this is due to a `KubeletCredentialProviders` being set in Kubelet extra args when a 1.25 cluster is created which is deprecated in version 1.28. Ran the test locally and verified that the test passes and is able to upgrade all the way upto 1.30. Also triggered a quick E2E against my local branch to verify that the test can pass on CI: https://tiny.amazon.com/1970e4lq7/IsenLink …

Unskip tinkerbell multiple upgrades test

---

internal/test/e2e/run.go

Tinkerbell E2E tests runner algorithm sorts the tests based on the hardware count and prioritize running the tests that require more hardware which typically take more duration to run first. Our test runners run concurrently and reserve the hardware from the available pool. The concurrent count is set to 20 as we have issues with VCenter environment when we bump this count to higher number. In current setup, the longer tests reserve the required hardware first and run for a really long time. So the first few runners that reserve the hardware do not free them up until the first couple of hours of the runtime. We do not know if this is the best way to use up the hardware as smaller tests like single node tests take 20-30% of the runtime as that of longer tests. We …

Change tinkerbell e2e run algorithm to schedule longer/smaller tests concurrently

---

release/cli/cmd/release.go
release/cli/pkg/clients/clients.go
release/scripts/bundle-release.sh
release/scripts/eks-a-release.sh
release/scripts/setup-aws-config.sh

PR #8628 added logic to setup the AWS profile for packages beta account in order to pull the dev private packages images, but we actually need to do this only for the dev release and staging bundle release. Other types of releases don't need this profile setup as we don't need to pull images from the packages beta account. So this PR adds checks to ensure the profile setup and clients creation for packages happens only where necessary.

Setup AWS profile for packages account only for bundle releases

---

test/e2e/SKIPPED_TESTS.yaml

Skip Tinkerbell worker node upgrade test while we investigate why it's failing continuously on CI.

Skip Tinkerbell worker node upgrade test

---

release/cli/cmd/release.go
release/cli/pkg/helm/helm.go
release/cli/pkg/images/images.go
release/cli/pkg/operations/upload.go
release/cli/pkg/types/types.go
release/cli/pkg/util/packages/packages.go

This PR adds logic to use packages-related clients and methods conditionally, only if the type of release is dev release or staging bundle release, and in other cases, using the default clients. We do this in order to prevent nil pointer errors when using a packages client when it's not defined in the first place.

Use packages-related clients and methods conditionally

---

test/framework/vsphere.go

We observed that for template generation, the staging E2E tests are not using the staging bundle manifest override (`bin/local-bundle-release.yaml`) but are using the dev-release manifest corresponding to the test EKS-A CLI, and sometimes the dev one has older EKS-D versions than the staging bundle manifest, for example, in case a dev release for the release branch had not been run after an EKS Distro version bump. In this case, CLI preflight tag validations would fail for vSphere because the template was generated using one EKS-D version while another EKS-D version was used for the tag validation. We are fixing this by always using the bundles override for template generation if available. …

Ensure bundles override is used for template generation if available

---

pkg/api/v1alpha1/cluster_types.go
pkg/features/features.go
pkg/features/features_test.go
pkg/validations/cluster.go
pkg/validations/cluster_test.go
pkg/validations/createvalidations/preflightvalidations.go
pkg/validations/upgradevalidations/preflightvalidations.go
test/framework/cluster.go

Add feature flag for Kubernetes v1.31 support in EKS-A.
make eks-a
make unit-test
make lint

Add feature flag for Kubernetes v1.31 support

---

Makefile
internal/test/e2e/run.go

Use correct Go version instead of old hardcoded Go version in E2E test JUnit files by dynamically retrieving the version from the `runtime` package in the Go standard library.

Use correct Go version in E2E test JUnit files

---

cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml
test/e2e/vsphere_test.go

This PR does the following in the vSphere E2E tests:
- For packages tests, it adds the missing E2E tests for kubernetes v1.29 as they weren't added when we first started supporting it in #7562.
- It also updates all the kubernetes v1.27 and v1.29 packages tests to regional curated packages tests as a follow-up to #8569.
- For all other tests, it adds the missing kubernetes v1.26 and v1.27 tests to cover all scenarios. For tests which have only test for an older kubernetes version, it updates that test to the latest kubernetes v1.30.
Overall, this PR adds 42 new vSphere tests and we had ~340 tests so far. So this will bring the total E2E tests count to ~380 which is above 360. This will set the [testPerInstance](https://github.com/aws/eks-anywhere/blob/69c906b2c139 …

Add missing vSphere E2E tests

---

pkg/providers/tinkerbell/assert.go
pkg/providers/tinkerbell/assert_test.go
pkg/providers/tinkerbell/reconciler/reconciler.go
pkg/providers/tinkerbell/reconciler/reconciler_test.go
pkg/providers/tinkerbell/template.go
pkg/providers/tinkerbell/upgrade.go
pkg/providers/tinkerbell/upgrade_test.go
pkg/providers/tinkerbell/validate.go

For Baremetal user might want to patch the nodes with updated OSImage while without upgrading the K8s version. Consequently user might also want to rollout nodes with any specific config change that doesn't involve a K8s version upgrade but warrants a node rollout. Ex. API server flags update. Issue: https://github.com/aws/eks-anywhere-internal/issues/2443
The upgrade flow only rolls out node on Tinkerbell provider for a K8s version change or when there's scale up of Control Plane or Workers. This is primarily due to the fact that there are hardware requirements for  node rollout on Tinkerbell and if EKS-A misses any of those validations during the upgrade and doesn't set an error message on the corresponding object like KCP/MD, once the …

Rollout new nodes for OSImageURL change on spec without changing K8s version

---

docs/content/en/docs/osmgmt/artifacts.md

Remove content library references from OVA build docs since our builds don't use content library anymore.

Remove content library references from OVA build docs

---

docs/content/en/docs/osmgmt/artifacts.md

* Make OVA template tagging instructions common across different OS's
* Scope Bottlerocket image URI retrieval instruction to a specific Kubernetes version
* Improve wording for artifact location information for baremetal and OVA images

Improve instructions for OVA template tagging and OS image URIs

---

cmd/eksctl-anywhere/cmd/upgrademanagementcomponents.go
docs/content/en/docs/clustermgmt/cluster-upgrades/management-components-upgrade.md
docs/content/en/docs/reference/eksctl/anywhere_upgrade_management-components.md
docs/content/en/docs/reference/eksctl/anywhere_upgrade_plan_management-components.md

Add documentation for management components upgrade commands.
Fixes: https://github.com/aws/eks-anywhere/issues/8679

Add documentation for management components upgrade commands

---

test/e2e/vsphere_test.go

`TestVSphereKubernetes129UbuntuTo130InPlaceUpgradeWorkerOnly` E2E test is failing with the following error:
```
2024-09-09T07:03:49.183Z	V0	❌ Validation failed	{"validation": "vsphere Provider setup is valid", "error": "template /SDDC-Datacenter/vm/Templates/kubernetes-1-30-eks-13-ubuntu is missing tag eksdRelease:kubernetes-1-29-eks-20", "remediation": ""}
```
This is due to an incorrect version configured in the test. This PR updates the kubernetes version in the test to fix the failure.

Fix kubernetes version in vSphere inplace E2E test

---

docs/content/en/docs/troubleshooting/troubleshooting.md

https://github.com/aws/eks-anywhere-internal/issues/2571
We have seen users running into an issue where the VMs IP get changed after reboot. There are 2 ways to resolve the issue listed in the doc.

Add steps on manually update etcd IPs for vShere Bottlerocket os

---

test/e2e/QUICK_TESTS.yaml
test/e2e/constants.go
test/e2e/docker_test.go

Add kubernetes v1.31 E2E tests for Docker provider. In general, this PR does either/all of the following:
- Add new 1.31 tests for features which have existing tests for all supported k8s versions and also for those which have tests for all _newer_ k8s versions if the test feature had been introduced in a relatively newer k8s version
- Update 1.30 tests to 1.31 tests for features which have existing tests only for the latest k8s version
- Remove any existing tests for k8s version less than or equal to 1.25
- Remove any non-existent tests from SKIPPED_TESTS
*Testing:*
make lint
By submitting this pull request, I confirm that you can use, modify, …

Add 1.31 E2E tests for Docker

---

test/e2e/SKIPPED_TESTS.yaml
test/e2e/constants.go
test/e2e/docker_test.go
test/e2e/snow_test.go
test/framework/snow.go

Remove kubernetes v1.26 E2E tests for Docker and Snow providers.
make lint

Remove 1.26 E2E tests for Docker and Snow

---

cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml

- Added missing ENV variable in quick e2e build spec

Add missing ENV var in quick e2e buildspec

---

test/e2e/SKIPPED_TESTS.yaml
test/e2e/cloudstack_test.go
test/framework/cloudstack.go

Remove kubernetes v1.26 E2E tests for CloudStack provider
make lint

Remove 1.26 E2E tests for CloudStack

---

pkg/controller/clientutil/kubernetes_test.go
test/e2e/conformance_test.go
test/framework/cluster.go

Remove conformance E2E tests for kubernetes version 1.26
make lint

Remove 1.26 conformance tests

---

pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/cluster_test.go
pkg/api/v1alpha1/testdata/cluster_in_place_upgrade.yaml
pkg/features/features.go
pkg/features/features_test.go
pkg/validations/cluster.go
pkg/validations/cluster_test.go
pkg/validations/createvalidations/preflightvalidations.go
pkg/validations/upgradevalidations/preflightvalidations.go
test/framework/cluster.go

This change removes the feature flag for Kubernetes v1.31 support and makes it the default cluster version.
make unit-test
make lint

Remove K8s 1.31 feature flag and default 1.31 as cluster version

---

docs/config.toml
docs/content/en/docs/concepts/support-versions.md
docs/content/en/docs/getting-started/baremetal/bare-spec.md
docs/content/en/docs/getting-started/cloudstack/cloud-spec.md
docs/content/en/docs/getting-started/cloudstack/cloudstack-getstarted.md
docs/content/en/docs/getting-started/cloudstack/cloudstack-preparation.md
docs/content/en/docs/getting-started/docker/_index.md
docs/content/en/docs/getting-started/nutanix/nutanix-getstarted.md
docs/content/en/docs/getting-started/nutanix/nutanix-spec.md
docs/content/en/docs/getting-started/vsphere/vsphere-getstarted.md
docs/content/en/docs/getting-started/vsphere/vsphere-spec.md
docs/content/en/docs/osmgmt/artifacts.md
docs/content/en/docs/reference/eksctl/anywhere_list_packages.md
docs/data/version_support.yml

This PR updates the docs to include k8s 1.31 support and also EKS-A v0.21.0 release.
make build

Update docs to add k8s 1.31 support

---

cmd/eksctl-anywhere/cmd/supportbundle.go
docs/content/en/docs/clustermgmt/support/supportbundle.md
docs/content/en/docs/reference/eksctl/anywhere_generate_support-bundle.md

*Issue #, if available: 5783
*Description of changes:
Currently eks-anywhere cannot generate support bundle in Airgap environment because eks-a needs to read bundle manifest from remote URL.
This PR fixed the issue by allowing user to specify path of local bundle manifest file so that eks-a does not need to read it from remote URL.
*Testing (if applicable):
Run eksctl to generate support bundle with bundle-manifest flag specified in the command, bundle can be generated successfully.
`eksctl-anywhere generate support-bundle -f eks-a-cluster.yaml --bundle-manifest eks-anywhere-downloads/bundle-release.yaml` …

Allow user to generate support bundle in Airgap environment

---

docs/content/en/docs/clustermgmt/support/purchase-subscription.md
docs/content/en/docs/concepts/support-scope.md

Updating our FAQ to mention the policy of not allowing for EKS-A subscription cancellations once a support case has already been created using that subscription. This clarification is necessary to avoid misuse of subscriptions.

Clarify subscription non-cancellation policy in case of support ticket creation

---

docs/content/en/docs/clustermgmt/cluster-upgrades/vsphere-and-cloudstack-upgrades.md
docs/content/en/docs/clustermgmt/cluster-upgrades/vsphere-credential-update.md

Documentation for updating vSphere credentials

---

config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml
config/crd/bases/anywhere.eks.amazonaws.com_eksareleases.yaml
config/manifest/eksa-components.yaml
internal/test/testdata/bundles.yaml
release/Makefile
release/api/v1alpha1/artifacts.go
release/api/v1alpha1/artifacts_test.go
release/api/v1alpha1/bundle_types.go
release/api/v1alpha1/zz_generated.deepcopy.go
release/cli/pkg/assets/config/bundle_release.go
release/cli/pkg/bundles/certmanager.go
release/cli/pkg/operations/testdata/main-bundle-release.yaml
release/config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml
release/config/crd/bases/anywhere.eks.amazonaws.com_eksareleases.yaml
release/config/crd/bases/anywhere.eks.amazonaws.com_releases.yaml

The `cert-manager-ctl` image was replaced with `cert-manager-startupapicheck` image in [#3790](https://github.com/aws/eks-anywhere-build-tooling/pull/3790) when cert-manager was bumped to v1.15.3. This PR updates the corresponding field in the EKS-A bundle to match the upstream image.
This PR also removes the `crd:trivialVersions=true,preserveUnknownFields=false` [CRD options](https://github.com/aws/eks-anywhere/blob/c7c5e480f1d0537abf7836b09cf26d0234d17e60/release/Makefile#L39) for controller-gen v0.8.0 as we bumped controller-gen from v0.6.1 to v0.8.0 in [#8531](https://github.com/aws/eks-anywhere/pull/8531) and controller-gen [v0.7.0](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.7.0) introduced a breaking change in …

Update cert manager image in the EKS-A bundle with new image

---

config/manifest/eksa-components.yaml

Updated the EKS-A components manifest file by running `make release-manifests`. The file wasn't updated in [#8812](https://github.com/aws/eks-anywhere/pull/8812) after marking the ctl field as deprecated instead of removing it completely.

Update EKS-A components manifest file

---

config/crd/bases/anywhere.eks.amazonaws.com_tinkerbelldatacenterconfigs.yaml
config/manifest/eksa-components.yaml
designs/tinkerbell-stack-load-balancer-interface.md
docs/content/en/docs/getting-started/baremetal/bare-spec.md
pkg/api/v1alpha1/tinkerbelldatacenterconfig_types.go
pkg/providers/tinkerbell/create.go
pkg/providers/tinkerbell/stack/stack.go
pkg/providers/tinkerbell/stack/stack_test.go
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_interface.yaml
pkg/providers/tinkerbell/tinkerbell_test.go
pkg/providers/tinkerbell/upgrade.go

[#1954](https://github.com/aws/eks-anywhere-internal/issues/1954)
This PR introduces `loadBalancerInterface` as an optional configuration in the `TinkerbellDatacenterConfig` spec in order to allow customers to override the default interface used by the current load-balancer(kube-vip) daemonset for the Tinkerbell stack. It also updates the EKS-A docs for that and adds the corresponding design doc.
```
make eks-a
make lint
make unit-test
make generate
make generate-manifests
make release-manifests
make verify-generate
make verify-generate-manifests
```
Successfully created and upgraded a tinkerbell cluster with a custom `loadBalancerInterface` specified in the cluster spec through the …

Customize tinkerbell load balancer interface

---

OWNERS

Add jhaanvi5 to OWNERS

---

docs/content/en/docs/whatsnew/changelog.md

* Update changelog for v0.20.7

Update changelog for v0.20.7

---

test/e2e/tinkerbell_test.go

'TestTinkerbellKubernetes131UbuntuWorkerNodeUpgrade' was using the wrong K8s version during init. Fix the test to use the template form the expected K8s version which 1.31.  

Fix K8s version for Tinkerbell E2E test

---

config/crd/bases/anywhere.eks.amazonaws.com_nutanixmachineconfigs.yaml
config/manifest/eksa-components.yaml

GPU support for Nutanix was added in [#8745](https://github.com/aws/eks-anywhere/pull/8745). This PR updates the `NutanixMachineConfig` CRD file and eksa-components manifest file by running `make generate-manifests` and `make release-manifests` to add GPU support for Nutanix.

Update NutanixMachineConfig crd and eksa-components manifest file

---

cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml

The max ec2 count is used to determine how many tests are to be run per instance
```
testPerInstance := len(testsList) / conf.MaxInstances
if testPerInstance == 0 {
testPerInstance = 1
}
```
Until few days ago, we only had ~380 vSphere tests so tests per instance was 380/200 = 1 after rounding off. After un-skipping bottlerocket 1.31 tests in [#8768](https://github.com/aws/eks-anywhere/pull/8768), CAPI 1.31 tests in [#8819](https://github.com/aws/eks-anywhere/pull/8819) and packages 1.31 tests in [#8825](https://github.com/aws/eks-anywhere/pull/8825), the total vSphere tests count went above 400 which caused the tests per instance to be 412/200 = 2 after rounding off so we run two tests per instance on 200 EC2 instances which can only run sequentially.
This PR …

Increase vSphere max EC2 count to 220

---

pkg/workflows/workload/writeclusterconfig.go

Workload cluster upgrade fails while upgrading from release-0.18 to release-0.19, on `write-cluster-config` step it is trying to look for secret for management Kubeconfig (`<mgmt-cluster>-aws-iam-kubeconfig`). 
In release-0.18, secret `<mgmt-cluster>-aws-iam-kubeconfig` is not created, there is precondition for creating secret it looks for AWS IAM configmap if it is not found it creates the secret, but in case of release-0.18 since clusterManager was CLI, it most probably created the configmap and secret was never created.
On workload cluster upgrade, this secret is required to generate the management cluster's AWS IAM Kubeconfig which is written to disk, this particular step can be skipped as there is no change to AWS IAM Kubeconfig on the cluster upgrade.
* Skipped generating AWS IAM …

Skip generating AWS IAM kubeconfig on cluster upgrade.

---

test/e2e/vsphere_test.go
test/framework/cloudstack.go
test/framework/nutanix.go
test/framework/template.go
test/framework/vsphere.go

`UpgradeFromLatestMinorRelease` tests fails with the template validation error, currently for these tests we use the staging bundle override to get the template which points to the latest release instead of getting the bundle from previous release.
This PR adds a parameter to disable bundles Override for e2e-test when upgrade is from latest minor release, to get the correct bundle for the release.
`./bin/e2e.test -test.v -test.run TestVSphereKubernetes127To128UbuntuUpgradeFromLatestMinorRelease`

Skip bundles override for e2e-test when upgrade is from latest minor release.

---

pkg/workflows/workload/upgrade_test.go
pkg/workflows/workload/writeclusterconfig.go

This PR introduces a change to the write-cluster-config step of the upgrade workflow. Specifically, it adds a check to skip writing the AWS IAM Kubeconfig to disk during this step. During a cluster upgrade, the AWS IAM Kubeconfig is not updated. As a result, the step to write the Kubeconfig to disk can be safely skipped without any impact on the upgrade process.
*Testing:*
Built eksa binary locally and tested upgrade workflow.

Skip generating AWS IAM Kubeconfig on cluster upgrade

---

test/e2e/vsphere_test.go
test/framework/cloudstack.go
test/framework/nutanix.go
test/framework/template.go
test/framework/vsphere.go

Cherry-picked from https://github.com/aws/eks-anywhere/pull/8807

[release-0.19] Skip bundles override for e2e-test when upgrade is from latest minor release

---

test/e2e/vsphere_test.go
test/framework/cloudstack.go
test/framework/nutanix.go
test/framework/template.go
test/framework/vsphere.go

[release-0.20] Skip bundles override for e2e-test when upgrade is from latest minor release

---

docs/content/en/docs/reference/eksctl/anywhere_apply_package(s).md
docs/content/en/docs/reference/eksctl/anywhere_create_package(s).md
docs/content/en/docs/reference/eksctl/anywhere_delete_package(s).md
docs/content/en/docs/reference/eksctl/anywhere_describe_package(s).md
docs/content/en/docs/reference/eksctl/anywhere_get_package(s).md
docs/content/en/docs/reference/eksctl/anywhere_get_packagebundle(s).md
docs/content/en/docs/reference/eksctl/anywhere_get_packagebundlecontroller(s).md
docs/content/en/docs/reference/eksctl/anywhere_install_package.md
docs/content/en/docs/reference/eksctl/anywhere_upgrade_packages.md

[#2270](https://github.com/aws/eks-anywhere-internal/issues/2270)
Packages commands were deprecated in [#8240](https://github.com/aws/eks-anywhere/pull/8240) from EKS-A v0.20.0 onwards. This PR updates the EKS-A docs to mark packages commands as deprecated.
`make -C docs build`

Update docs to mark packages commands as deprecated

---

Makefile

[#2402](https://github.com/aws/eks-anywhere-internal/issues/2402)
Update branch name to `release-0.21` in Makefile

[release-0.21] Update branch name to release-0.21 in Makefile

---

Makefile
scripts/e2e_test_docker.sh
test/e2e/README.md

[#2402](https://github.com/aws/eks-anywhere-internal/issues/2402)
Update docker test name for e2e presubmit

Update docker test name for e2e presubmit

---

scripts/eksa_version.sh

This PR fixes the EKS-A version script by getting latest Git tag by semver, as intended, instead of chronological order.

Get latest Git tag by semver instead of chronological order

---

release/cli/pkg/filereader/file_reader.go

Print output of Git checkout command instead of swallowing it.

Print output of Git checkout command

---

docs/content/en/docs/whatsnew/changelog.md

[release-0.20] changelog for v0.20.8

---

pkg/networking/cilium/upgrade_plan.go
pkg/networking/cilium/upgrade_plan_test.go

Display Cilium upgrade skipped status in `upgrade plan` command
Fixes: https://github.com/aws/eks-anywhere/issues/8853
```console
> ./eksctl-anywhere upgrade plan cluster -f $CLUSTER_NAME.yaml
Checking new release availability...
NAME                 CURRENT VERSION       NEXT VERSION
EKS-A Management     v0.20.5+edd7640       v0.21.0-dev+build.291+294dfde
cert-manager         v1.14.7+fe09cef       v1.16.1+5d8f23c
cluster-api          v1.7.2+9efc12c        v1.8.4+ab49b25
kubeadm              v1.7.2+d36e661        v1.8.4+d751002
docker               v1.7.2+b91f85f        v1.8.4+94e333f
kubeadm              v1.7.2+302c0db        v1.8.4+236f530
etcdadm-bootstrap    v1.0.13+fcf0999       v1.0.14+4bacd57
etcdadm-controller   v1.0.22+d178343       v1.0.24+a1c69ab
cilium …
```

Display Cilium upgrade skipped status in upgrade plan command

---

internal/test/e2e/run.go

At the end of test, even if cleanup-resources was set to false, the test would decommision the instance. With this change, the instance would not be deleted, leaving the environment in place for debugging. The instance should be manually deleted afterwards.

Skip cleaning up the instance if cleanup-resources is set to false

---

docs/config.toml

Add versions page for v0.19 so that it can still be referred later.
`make build`

Add versions page for v0.19

---

docs/config.toml

Fix URL for release-0.20 branch docs URL

Fix URL for release-0.20 branch docs URL

---

docs/Makefile
docs/amplify.yml
docs/patches/0001-Security-update.patch

git am is failing to apply the theme patch because amplify doesn't have a git user and email configured. This configures a user and email so the git am doesn't fail.

Fix "Committer identity unknown" when patching:

---

test/e2e/SKIPPED_TESTS.yaml

[#2402](https://github.com/aws/eks-anywhere-internal/issues/2402)
Unskip upgrade from latest minor tests now that the EKS-A latest minor release [v0.21.0](https://github.com/aws/eks-anywhere/releases/tag/v0.21.0) is out.

Unskip upgrade from latest minor tests

---

docs/patches/0001-Security-update.patch
docs/static/font/font-face.css

For security reasons, Amazon does not allow Webpage loads resources from CDN or domain with public access or elevated risk via link(s). For this reason we host the javascript files locally and reference them in the theme.

Security update:

---

cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml

Lower concurrent test count for vsphere to 60
/approve

Lower vsphere concurrent tests to 60

---

docs/content/en/docs/concepts/packages.md
docs/content/en/docs/concepts/support-scope.md

This PR removes the curated package list from concepts page as it is already being referenced on the same page above as a hyperlink to the updated list in the package management section. It makes sense to have a single source of truth for the updated list of curated packages. The PR also fixes the link for the EKS Distro documentation page.
`make build`

Remove curated package list from concepts page

---

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/docker-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/nutanix-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/snow-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/tinkerbell-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml
cmd/integration_test/cmd/run.go
internal/test/e2e/run.go
scripts/e2e_test_docker.sh

This PR removes the `--baremetal-branch` flag from the integration test CLI as we no longer run tinkerbell tests simultaneously on multiple branches. This flag was introduced in [#3201](https://github.com/aws/eks-anywhere/pull/3201) more than two years ago to set the branch name for baremetal tests to run on. We now have additional mechanisms to prevent tests from being triggered from different branches at the same time so this flag doesn't add any value anymore. Since we started supporting n-1 EKS-A release branch too, we keep doing patch releases every 3 out of 4 weeks which requires us to run tests on release branches frequently. This change will reduce the headache of changing the secret value every time we do a patch release from main to release branch and …

Remove baremetal-branch flag from the integration test CLI

---

docs/content/en/docs/getting-started/nutanix/nutanix-spec.md

N/A
Add documentation for workerMachineGroups in Nutanix failure domains

Add documentation for workerMachineGroups in Nutanix failure domains

---

docs/content/en/docs/getting-started/nutanix/nutanix-spec.md

Manual cherry-pick of https://github.com/aws/eks-anywhere/pull/8972

[release-0.21] Add documentation for workerMachineGroups in Nutanix failure domains

---

test/framework/cluster.go

This PR skips validating the pbc registry for non-regional curated packages flow as a follow-up to [#8910](https://github.com/aws/eks-anywhere/pull/8910).
```
make eks-a
make lint
make unit-test
make generate
make generate-manifests
make release-manifests
```

Skip validating the pbc registry for non-regional curated packages flow

---

release/cli/pkg/aws/ecrpublic/ecrpublic.go
release/cli/pkg/constants/constants.go
release/cli/pkg/images/images.go
release/cli/pkg/operations/upload.go

We have noticed that the image copy through Skopeo errors out when the destination repo has already hit the 10000 images mark or the 1000 tags per image mark, since these are the default limits set by ECR Public. In these cases, we should fail fast instead of retrying the image copy.
This PR adds logic to perform the check for images-per-repo and tags-per-repo on the destination ECR and fail early.
I tested this by building a small program with the actual ECR public bits (with credentials provided by my local AWS config file) and the checker method that returns the error. I created a repository and pushed 10000 images to it and tested the code against it. …

Check image pushability based on image/tag count limits prior to push

---

release/cli/pkg/images/images.go
release/cli/pkg/operations/upload.go

This PR fixes the image count verification for the prod bundle release by using the ECR Public source client instead of the ECR source client, which would be `nil` for prod bundle releases.

Use ECR Public source client for image checks in prod bundle release

---

internal/pkg/nutanix/prismclient.go
pkg/providers/nutanix/client.go
pkg/providers/nutanix/mocks/client.go
pkg/providers/nutanix/provider_test.go
pkg/providers/nutanix/validator.go
pkg/providers/nutanix/validator_test.go

FIQL is deprecated and contains well-known bugs. This patch get rid of FIQL for all list requests to Nutanix PC API.
```
$ eksctl anywhere create cluster -f ./cluster-eksa-ntnx-fiql-fix.yaml -v10 --bundles-override ./bin/local-bundle-release.yaml
2024-11-12T17:44:10.824Z	V6	Executing command	{"cmd": "/usr/bin/docker version --format {{.Client.Version}}"}
2024-11-12T17:44:10.844Z	V6	Executing command	{"cmd": "/usr/bin/docker info --format '{{json .MemTotal}}'"}
2024-11-12T17:44:10.887Z	V4	Reading bundles manifest	{"url": "./bin/local-bundle-release.yaml"}
2024-11-12T17:44:10.907Z	V4	Using CAPI provider versions	{"Core Cluster API": "v1.8.5+177bb52", "Kubeadm Bootstrap": "v1.8.5+206a28e", "Kubeadm Control Plane": "v1.8.5+68b2668", …
```

Get rid of FIQL in Nutanix API list methods

---

cmd/integration_test/build/buildspecs/docker-test-eks-a-cli.yml

Total docker tests are 92. Bringing the count down to 60.

Lower docker e2e tests max concurrency count

---

internal/pkg/ec2/create.go

Our e2e tests are failing with the below error,
```
InsufficientInstanceCapacity: We currently do not have sufficient t3.2xlarge capacity in the Availability Zone you requested (***a). Our system will be working on provisioning additional capacity. You can currently get t3.2xlarge capacity by not specifying an Availability Zone in your request or choosing ***b, ***c, ***d.
```
Getting a random subnet id from the string containing multiple subnet ids to fix the above issue.

Get a random subnet id from a list of subnet ids

---

pkg/clustermanager/cluster_manager.go
pkg/workflows/interfaces/interfaces.go
pkg/workflows/interfaces/mocks/clients.go
pkg/workflows/management/create_test.go
pkg/workflows/management/write_cluster_config.go
pkg/workflows/workload/create_test.go
pkg/workflows/workload/upgrade_test.go
pkg/workflows/workload/writeclusterconfig.go

fix iam kubeconfig generation in workload clusters

---

pkg/clustermanager/cluster_manager.go
pkg/clustermanager/cluster_manager_test.go

Sometimes the `clusterctl move` returns successfully, but the actual resource type isn't available in the management cluster until after sometime. During this edge condition, if we run the `kubectl wait` command on the management it throws the following error: 
`executing wait: error: the server doesn't have a resource type \"clusters\"\n",`
If the `clusterctl move` is successful and we still see this error, treat this as a transient error and add retries to make the cluster creation process more resilient. This should not affect the existing flow as the retries would only kick in if the kubectl wait errors out.

Retry for transient 'server doesn't have a Resource type errors' after clusterctl move

---

pkg/providers/tinkerbell/stack/stack.go
pkg/providers/tinkerbell/stack/stack_test.go
pkg/providers/tinkerbell/stack/testdata/expected_upgrade.yaml
pkg/providers/tinkerbell/stack/testdata/expected_upgrade_with_proxy.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_docker.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_kubernetes.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_docker_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_hook_override.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_false.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_true.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_kubernetes_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_false.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_true.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_interface.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_proxy_config.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_registry_mirror.yaml

Fix flags for smee version `v0.15.1` #4115.
Number of flags have changed in smee due to the above version bump. This PR sets the necessary flags to the smee deployment.

Update smee flags for the latest version bump

---

pkg/providers/tinkerbell/config/template-cp.yaml
pkg/providers/tinkerbell/config/template-md.yaml
pkg/providers/tinkerbell/stack/stack.go
pkg/providers/tinkerbell/stack/stack_test.go
pkg/providers/tinkerbell/testdata/expected_kct.yaml
pkg/providers/tinkerbell/testdata/expected_results_bottlerocket_cert_bundles_config_md.yaml
pkg/providers/tinkerbell/testdata/expected_results_bottlerocket_kernel_config_md.yaml
pkg/providers/tinkerbell/testdata/expected_results_bottlerocket_ntp_config_md.yaml
pkg/providers/tinkerbell/testdata/expected_results_bottlerocket_settings_config_md.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_autoscaler_md.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_bottlerocket_md_minimal_registry_mirror.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_bottlerocket_md_registry_mirror_with_auth.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_bottlerocket_md_registry_mirror_with_cert.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md_minimal_registry_mirror.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md_node_labels.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md_node_taints.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md_node_worker_version.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md_proxy.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md_registry_mirror_with_auth.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md_registry_mirror_with_cert.yaml
pkg/providers/tinkerbell/testdata/expected_results_md_template.yaml
pkg/providers/tinkerbell/testdata/expected_results_tinkerbell_md_multiple_node_groups.yaml
pkg/providers/tinkerbell/testdata/expected_results_ubuntu_ntp_config_md.yaml

Latest release of CAPT, supports `bootOptions` in the `TinkerbellMachineSpec`. In EKS-A this translates to `tinkerbellMachineTemplate` having those fields configurable for Control-Plane and MachineDeployment. Default `bootMode` to `netboot` in this change. I will follow up with the conditional logic to toggle between netboot and isoboot in a different PR that'll introduce L3 provisioning changes to EKS-A. 
Also, update Smee flags as all smee flags start with `SMEE_` prefix and the previous  `BOOTS_KUBE_NAMESPACE` was invalid. Remove `PUBLIC_SYSLOG_IP ` as it is not a valid flag in the latest [version](https://github.com/tinkerbell/smee/blob/main/README.md).
By …

Add bootOptions to cp/md tinkerbellmachine template, fix unit-tests

---

docs/content/en/docs/troubleshooting/troubleshooting.md

Added DNS troubleshooting tips in EKSA troubleshooting doc. 

Added DNS troubleshooting steps in EKS Anywhere troubleshooting doc

---

OWNERS

Adding @ndeksa to OWNERS file.

Add ndeksa to OWNERS file

---

docs/content/en/docs/getting-started/baremetal/customize/bare-custom-hookos.md

For EKS Anywhere >= v0.21.0 embedded images are required when building HookOS.

Add instructions for embedded images:

---

docs/content/en/docs/whatsnew/changelog.md

Change log for the release-0.21.3

Change log for the release-0.21.3

---

pkg/providers/tinkerbell/config/template-cp.yaml
pkg/providers/tinkerbell/testdata/expected_cluster_tinkerbell_api_server_cert_san_domain_name.yaml
pkg/providers/tinkerbell/testdata/expected_cluster_tinkerbell_api_server_cert_san_ip.yaml
pkg/providers/tinkerbell/testdata/expected_kcp.yaml
pkg/providers/tinkerbell/testdata/expected_results_bottlerocket_cert_bundles_config_cp.yaml
pkg/providers/tinkerbell/testdata/expected_results_bottlerocket_kernel_config_cp.yaml
pkg/providers/tinkerbell/testdata/expected_results_bottlerocket_ntp_config_cp.yaml
pkg/providers/tinkerbell/testdata/expected_results_bottlerocket_settings_config_cp.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_bottlerocket_cp_minimal_registry_mirror.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_bottlerocket_cp_registry_mirror_with_auth.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_bottlerocket_cp_registry_mirror_with_cert.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_awsiam.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_external_etcd.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_full_oidc.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_minimal_oidc.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_minimal_registry_mirror.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_node_labels.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_node_taints.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_proxy.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_registry_mirror_with_auth.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_registry_mirror_with_cert.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_single_node.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_single_node_in_place.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_single_node_skip_lb.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_stacked_etcd.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_disable_kube_vip.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_missing_ssh_keys.yaml
pkg/providers/tinkerbell/testdata/expected_results_cp_template.yaml
pkg/providers/tinkerbell/testdata/expected_results_tinkerbell_pod_iam_config.yaml
pkg/providers/tinkerbell/testdata/expected_results_ubuntu_ntp_config_cp.yaml

#9094 missed adding Bootoptions to the control plane TinkerbellMachineTemplate which is responsible for creating the necessary Tink workflows to boot the hardware. 

Add bootOptions to control plane tinkerbellmachinetemplate

---

config/crd/bases/anywhere.eks.amazonaws.com_clusters.yaml
config/manifest/eksa-components.yaml
pkg/api/v1alpha1/cluster_types.go
pkg/api/v1alpha1/cluster_types_test.go

This PR adds a new optional `licenseToken` string to the cluster spec for extended kubernetes version support.
```
make eks-a
make lint
make unit-test
make generate
make generate-manifests
make release-manifests
```

Add license token string to cluster spec

---

config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml
config/manifest/eksa-components.yaml
release/api/v1alpha1/bundle_types.go
release/cli/pkg/bundles/bundles.go
release/cli/pkg/filereader/file_reader.go
release/cli/pkg/operations/testdata/main-bundle-release.yaml
release/config/crd/bases/anywhere.eks.amazonaws.com_bundles.yaml

This PR adds the new `endOfStandardSupport` date to the EKS-A bundle for extended kubernetes version support. This date is fetched from the [EKSD_LATEST_RELEASES](https://github.com/aws/eks-anywhere-build-tooling/blob/main/EKSD_LATEST_RELEASES) file which was updated in [#4174](https://github.com/aws/eks-anywhere-build-tooling/pull/4174).
**NOTE:** The [testdata](https://github.com/aws/eks-anywhere/blob/main/release/cli/pkg/operations/testdata/main-bundle-release.yaml) file is not updated yet in this PR as [#4174](https://github.com/aws/eks-anywhere-build-tooling/pull/4174) is not merged yet. Once that is merged, I will re-run the `make -C release …

Add end of standard support field to EKS-A bundle

---

pkg/api/v1alpha1/thirdparty/tinkerbell/capt/v1beta1/groupversion_info.go
pkg/api/v1alpha1/thirdparty/tinkerbell/capt/v1beta1/tinkerbellcluster_types.go
pkg/api/v1alpha1/thirdparty/tinkerbell/capt/v1beta1/tinkerbellcluster_webhook.go
pkg/api/v1alpha1/thirdparty/tinkerbell/capt/v1beta1/tinkerbellmachine_types.go
pkg/api/v1alpha1/thirdparty/tinkerbell/capt/v1beta1/tinkerbellmachine_webhook.go
pkg/api/v1alpha1/thirdparty/tinkerbell/capt/v1beta1/tinkerbellmachinetemplate_types.go
pkg/api/v1alpha1/thirdparty/tinkerbell/capt/v1beta1/tinkerbellmachinetemplate_webhook.go

We added CAPT crds to a local package in #9114. The upstream CRDs contained kubebuilder annotations that was making EKS-A register additional webhooks for CAPT objects which shouldn't be there at first place. Here's reference to the [eksa-components.yaml](https://dev-release-assets.eks-anywhere.model-rocket.aws.dev/artifacts/v0.22.0-dev-build.105/eks-anywhere/manifests/cluster-controller/v0.21.3/eksa-components.yaml) post that change that has webhooks for tinkerbellcluster, tinkerbellmachine and tinkerbellmachinetemplate crds. 
This causes cluster creation process to fail when applying the spec for CAPT objects with the below error:
```
Internal error occurred: failed calling webhook …
```

Remove kubebuilder annotations from local copy of CAPT APIs

---

README.md

Reverts https://github.com/aws/eks-anywhere/pull/8145 because k8s v1.28 logos are missing
Related issue: https://github.com/cncf/artwork/issues/457

Revert "Update README.md conformance notification"

---

docs/content/en/docs/clustermgmt/observability/expose-metrics.md

Update the metrics doc for etcd metrics to specify explictily that proxy steps are only for stacked setup

For etcd metrics, specify explictily proxy steps are only for stacked etcd

---

docs/content/en/docs/osmgmt/artifacts.md

There is a trailing comma in the example provided that invalidates the json formating
removed the trailing comma (,)

Removed trailing comma (,) from json

---

docs/content/en/docs/whatsnew/changelog.md

Add changelog for EKS-A v0.20.11, re-order 0.20 releases to all be together.

Add changelog for EKS-A v0.20.11, re-order 0.20 releases

---

docs/content/en/docs/clustermgmt/networking/networking-and-security.md

* Update `docs/content/en/docs/tasks/workload/networking-and-security.md` to use Cilium CLI instead of connectivity check YAML manifest.

doc: update Cilium validation

---

pkg/api/v1alpha1/cluster_types.go
pkg/features/features.go
pkg/features/features_test.go
pkg/validations/cluster.go
pkg/validations/cluster_test.go
pkg/validations/createvalidations/preflightvalidations.go
pkg/validations/upgradevalidations/preflightvalidations.go
test/framework/cluster.go

Add feature flag for K8s 1.32

---

pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/testdata/cluster_1_20.yaml
pkg/api/v1alpha1/testdata/cluster_1_20_cloudstack.yaml
pkg/api/v1alpha1/testdata/cluster_1_20_namespace_mismatch_between_cluster_and_datacenter.yaml
pkg/api/v1alpha1/testdata/cluster_1_20_namespace_mismatch_between_cluster_and_machineconfigs.yaml
pkg/api/v1alpha1/testdata/cluster_1_20_with_non_eksa_resources.yaml
pkg/api/v1alpha1/testdata/cluster_invalid_cluster_name.yaml
pkg/api/v1alpha1/testdata/cluster_invalid_worker_node_count.yaml
pkg/api/v1alpha1/testdata/cluster_package_configuration.yaml
pkg/api/v1alpha1/testdata/incorrect_indentation.yaml
pkg/cluster/config_manager.go
pkg/cluster/testdata/cluster_1_19.yaml
pkg/cluster/testdata/cluster_1_20_cloudstack.yaml
pkg/cluster/testdata/cluster_cloudstack_missing_datacenter.yaml
pkg/cluster/testdata/docker_cluster_oidc_awsiam_flux.yaml
pkg/dependencies/testdata/cluster_tinkerbell.yaml
pkg/providers/cloudstack/testdata/cluster_main_worker_node_group_kubernetes_version.yaml
pkg/providers/nutanix/testdata/eksa-cluster-external-etcd-k8s-1-20.yaml
pkg/providers/tinkerbell/testdata/cluster_tinkerbell_worker_version.yaml
pkg/utils/yaml/yaml.go
pkg/utils/yaml/yaml_test.go
pkg/yamlutil/parser.go
pkg/yamlutil/parser_test.go
release/cli/pkg/assets/archives/archives.go
release/cli/pkg/assets/assets.go
release/cli/pkg/bundles/bundles.go

Ensure Kubernetes version in cluster config is always parsed as string regardless of whether it is quoted or not. Ref: #9184.

Ensure Kubernetes version is always parsed as string

---

docs/content/en/docs/getting-started/baremetal/bare-spec.md
docs/content/en/docs/getting-started/cloudstack/cloud-spec.md
docs/content/en/docs/getting-started/nutanix/nutanix-spec.md
docs/content/en/docs/getting-started/snow/snow-spec.md
docs/content/en/docs/getting-started/vsphere/vsphere-spec.md
docs/content/en/docs/troubleshooting/troubleshooting.md
docs/content/en/docs/whatsnew/changelog.md

Due to bugs ([1](https://github.com/go-yaml/yaml/issues/430), [2](https://github.com/go-yaml/yaml/issues/671)) in the underlying `gopkg.in/yaml.v2` parser used by the `sigs.k8s.io/yaml` module (same [issue](https://github.com/kubernetes-sigs/yaml/issues/45) also logged there) that we consume, the Kubernetes version with minor versions which is a multiple of 10, such as `1.30`, `1.40`, will be parsed as `float64` if specified without quotes in the cluster config file, which causes the trailing zero to get dropped, thereby leading to `1.3`, `1.4` which are incorrect. This can be prevented by using quotes around the Kubernetes version.

Document the need to use quotes around Kubernetes version

---

docs/content/en/docs/getting-started/cloudstack/cloud-spec.md
docs/content/en/docs/getting-started/nutanix/nutanix-spec.md
docs/content/en/docs/getting-started/snow/snow-spec.md
docs/content/en/docs/getting-started/vsphere/vsphere-spec.md

Remove duplicated line in Kubernetes version docs.

Remove duplicated line in Kubernetes version docs

---

docs/content/en/docs/whatsnew/changelog.md

* Add changelog for v0.21.5
* Fix BR version for some 0.21.x releases
* Re-order 0.20.x releases so they are all together.

Add changelog for v0.21.5, fix BR version and re-order 0.20.x releases

---

pkg/networking/cilium/templater.go
pkg/networking/cilium/templater_test.go
pkg/networking/cilium/testdata/cilium_manifest.yaml

`tunnel` was deprecated in cilium v1.14 and will be removed in v1.15.
For the previous `tunnel: "geneve"`, we now need to use
```
routing-mode: "tunnel"
tunnel-protocol: "geneve"
```
And for `tunnel: "disable"`, set `routing-mode `to `native `and remove `tunnel-protocol` entry.
Reference:
https://docs.cilium.io/en/v1.15/operations/upgrade/#removed-options
1. `make test` to run a capd simpleflow test.
2. Created an EKS-A cluster with cilium v1.15 and override eks-a controller with the change in this PR.

Remove tunnel from cilium template

---

pkg/clients/kubernetes/client.go
pkg/clients/kubernetes/client_test.go
pkg/clients/kubernetes/kubeconfig.go
pkg/clients/kubernetes/mocks/client.go
pkg/clients/kubernetes/unauth.go
pkg/controller/clientutil/kubernetes.go
pkg/controller/clientutil/kubernetes_test.go
pkg/validations/extendedversion.go
pkg/validations/extendedversion_test.go
pkg/validations/kubectl.go
pkg/validations/mocks/kubectl.go
pkg/validations/upgradevalidations/poddisruptionbudgets_test.go

#6793 
Validate the license token is not being used by multiple clusters for extended kubernetes version support for eks-a controller.

Validate LicenseToken field is not used by other clusters

---

cmd/eksctl-anywhere/cmd/createcluster.go
cmd/eksctl-anywhere/cmd/upgradecluster.go
cmd/eksctl-anywhere/cmd/validatecreatecluster.go
pkg/providers/tinkerbell/upgrade.go
pkg/validations/cluster.go
pkg/validations/cluster_test.go
pkg/validations/createvalidations/preflightvalidations.go
pkg/validations/createvalidations/preflightvalidations_test.go
pkg/validations/extendedversion.go
pkg/validations/upgradevalidations/preflightvalidations.go
pkg/validations/upgradevalidations/preflightvalidations_test.go
pkg/validations/validation_options.go

#6793 
Validate extended kubernetes version support for eks-a create and upgrade CLI operations.

Add extended kubernetes version support validations for create and upgrade CLI operations

---

.github/workflows/golangci-lint.yml
cmd/eksctl-anywhere/cmd/createcluster.go
cmd/eksctl-anywhere/cmd/upgradecluster.go
config/crd/bases/anywhere.eks.amazonaws.com_tinkerbelldatacenterconfigs.yaml
config/manifest/eksa-components.yaml
pkg/validations/cluster.go
pkg/validations/cluster_test.go
pkg/validations/createvalidations/preflightvalidations.go
pkg/validations/upgradevalidations/preflightvalidations.go
pkg/validations/validation_options.go

**Commit 1**
This commit updates the extended kubernetes version support validation to use the specified bundles file when a cluster is created or upgraded with `--bundles-override` CLI flag.
**Commit 2**
This commit removes the `skip-pkg-cache` option from the golangci-lint action as it has been removed in v5.0.0+ ([compatibility](https://github.com/golangci/golangci-lint-action/blob/master/README.md#compatibility)). This option was added in [#3888](https://github.com/aws/eks-anywhere/pull/3888) to avoid double cache with setup-go. The action throws the following error now with v6.0.0:
```
Warning: Unexpected input(s) 'skip-pkg-cache', valid inputs are ['version', …
```

Use specified bundles-override file to validate extended kubernetes version support

---

internal/pkg/api/cluster.go
test/framework/cluster.go

This PR updates all the E2E tests to include a valid and unexpired license token in the cluster spec by default. Before this change, all the 1.28 tests failed with the following error:
```
2025-02-11T16:42:49.120-0800    V0      ❌ Validation failed    {"validation": "validate extended kubernetes version support is supported", "error": "getting licenseToken: licenseToken is required for extended kubernetes support", "remediation": "ensure you have a valid license for extended Kubernetes version support"}
```
This is because kubernetes version `v1.28` is already under extended support so a valid and unexpired license token is required to create 1.28 clusters. Eventually, all …

Add license token in the cluster spec for all E2E tests

---

docs/content/en/docs/osmgmt/artifacts.md

Update docs to reflect the SHA-512 digest corresponding to the latest version of the Bottlerocket root.json.

Update Bottlerocket root.json checksum in docs

---

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/docker-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/nutanix-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/tinkerbell-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml
test/framework/cluster.go

*Issue:*
This PR retrieves the license token from secrets manager.

Retrieve license token from secrets manager

---

pkg/providers/cloudstack/config/template-cp.yaml
pkg/providers/cloudstack/controlplane_test.go
pkg/providers/cloudstack/testdata/expected_results_affinity_cp.yaml
pkg/providers/cloudstack/testdata/expected_results_main_cp.yaml
pkg/providers/cloudstack/testdata/expected_results_main_cp_kubernetes_version.yaml
pkg/providers/cloudstack/testdata/expected_results_main_no_machinetemplate_update_cp.yaml
pkg/providers/cloudstack/testdata/expected_results_main_node_labels_cp.yaml
pkg/providers/cloudstack/testdata/expected_results_main_with_taints_cp.yaml
pkg/providers/cloudstack/testdata/expected_results_mirror_config_cp.yaml
pkg/providers/cloudstack/testdata/expected_results_mirror_config_with_cert_cp.yaml
pkg/providers/cloudstack/testdata/expected_results_mirror_config_with_insecure_skip_and_cert_cp.yaml
pkg/providers/cloudstack/testdata/expected_results_mirror_config_with_insecure_skip_cp.yaml
pkg/providers/cloudstack/testdata/expected_results_resourceids_cp.yaml

In the etcdadm reconcile loop we make a [namespaced lookup](https://github.com/aws/etcdadm-controller/blob/main/controllers/controller.go#L123) for the etcdadm cluster object referenced in the capi cluster.  For Cloudstack provider, when we create the capi cluster object we missed referencing the namespace as we do for other providers. This fix adds in the namespace for the external etcd reference.
This was the panic on the etcd controller before the fix:
```
2025-02-17T19:07:35Z    ERROR   controllers.EtcdadmCluster      Failed to get etcdadm cluster   {"etcdadmcluster": {"name":"rahul-mgmt-cs-etcd"}, "error": "an empty namespace may not be set when a resource name is provided"}
github.com/aws/etcdadm-controller/controllers.(*EtcdadmClusterReconciler).Reconcile …
```

Add namespace to external etcd ref

---

test/e2e/QUICK_TESTS.yaml
test/e2e/constants.go
test/e2e/docker_test.go

Added k8s 1.32 e2e tests for Docker provider.
This PR will add 1.32 tests to the test cases that are expected to run on all k8s versions, and update version from 1.31 to 1.32 for tests that only runs on latest version.

Add Docker Provider e2e tests for 1.32

---

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/conformance-eks-a-cli.yml
cmd/integration_test/build/buildspecs/docker-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/nutanix-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/tinkerbell-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml
pkg/validations/extendedversion.go
pkg/validations/extendedversion_test.go
test/framework/cluster.go
test/framework/multicluster.go

This PR adds a new license token to the workload cluster E2E tests to have unique tokens for each cluster. Before this change, the workload cluster E2E tests failed with the following error:
```
2025-02-18T05:20:00.146Z	V0	❌ Validation failed	{"validation": "validate extended kubernetes version support is supported", "error": "validating licenseToken is unique for cluster <workload-cluster-name>: license key <license-token-string> is already in use by cluster <other-cluster-name>", "remediation": "ensure you have a valid license for extended Kubernetes version support"}
```
It also updates the error message to say license "token" instead of license "key" to be consistent …

Add new license token to the workload cluster e2e tests

---

pkg/controller/clusters/controlplane.go
pkg/controller/clusters/controlplane_test.go

It appears that our controller has always been emptying the capi cluster `ControlPlaneEndpoint` on every reconciliation. It seems to be a consequence of how server side apply works on top of go json marshaling of structs with zero values. Since the field is a struct a not a pointer, even when not set (zero value for all fields), it's being marshaled into a json object with fields set to the equivalent of the zero value of those types in go. We verified this by looking at the audit logs. In the request body from the eks-a controller we can see:
```json
"clusterNetwork": {
"services": {
"cidrBlocks": [
"10.96.0.0/12"
]
},
"pods": {
"cidrBlocks": [
"192.168.0.0/16"
]
},
"serviceDomain": "cluster.local"
},
"controlPlaneEndpoint": {
"host": "",
"port": 0
},
```
And we do see how the in the …

Preserve current capi cluster CP endpoint on updates

---

test/framework/common.go

This PR adds the workload cluster license token env variable to required common env vars. The new token was added in [#9262](https://github.com/aws/eks-anywhere/pull/9262) to fix the workload cluster e2e tests.

Add workload cluster license token env variable to required common env vars

---

pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/cluster_test.go
pkg/api/v1alpha1/testdata/cluster_in_place_upgrade.yaml
pkg/features/features.go
pkg/features/features_test.go
pkg/validations/cluster.go
pkg/validations/cluster_test.go
pkg/validations/createvalidations/preflightvalidations.go
pkg/validations/upgradevalidations/preflightvalidations.go
test/framework/cluster.go

Remove k8s 1.32 feature flag and make 1.32 the default version

---

test/e2e/docker_test.go

Fix the wrong k8s version due to copy-pasting in some e2e test cases

Fix the wrong k8s version in some e2e test cases

---

docs/content/en/docs/overview/partner/_index.md

Remove AWS Outposts section from validated partners list since EKS-A doesn't run on Outposts.

Remove AWS Outposts section from validated partners list

---

test/e2e/vsphere_test.go

This PR fixes incorrect template kubernetes versions for etcd scale tests.

Fix incorrect template kubernetes versions for etcd scale tests

---

test/e2e/flux.go
test/e2e/multicluster.go
test/e2e/vsphere_test.go
test/framework/cluster.go
test/framework/multicluster.go

This PR fixes the inplace upgrade tests and upgrade tests without cluster config generation failing with the following error:
```
2025-02-22T05:23:13.299Z	V0	❌ Validation failed	{"validation": "validate extended kubernetes version support is supported", "error": "getting licenseToken: licenseToken is required for extended kubernetes support", "remediation": "ensure you have a valid license for extended Kubernetes version support"}
```
It also fixes the workload cluster tests failing with the following error:
```
Error: validations failed: validating licenseToken is unique for cluster main-i-00821-76f2f36-w-0: license token <license-token-string> is already in use by cluster …
```

Fix e2e tests failures due to missing license token

---

test/e2e/vsphere_test.go

Fix the wrong k8s version in VSphere131UbuntuTo132InPlaceUpgradeWorker

Fix wrong k8s version in VSphere131UbuntuTo132InPlaceUpgradeWorker

---

test/e2e/docker_test.go
test/framework/cluster.go

This PR fixes the `TestDockerUpgradeFromLatestMinorReleaseCiliumSkipUpgrade_CLIUpgrade` test. It was failing with the following error:
```
Error: the cluster config file provided is invalid: unable to parse main-i-0ee7f-9546b4b/main-i-0ee7f-9546b4b-eks-a.yaml file: error unmarshaling JSON: while decoding JSON: json: unknown field "licenseToken"
```
This is because the test creates cluster with the latest minor release which is v0.21 and the license token field is only supported from v0.22.0 onwards.

Fix docker upgrade from latest tests

---

test/e2e/cloudstack_test.go

The 128 proxy config tests in Cloudstack were failing due to missing license token. This change adds the necessary license token for those tests.
`2025-02-24T03:09:05.289Z	V0	❌ Validation failed	{"validation": "validate extended kubernetes version support is supported", "error": "getting licenseToken: licenseToken is required for extended kubernetes support", "remediation": "ensure you have a valid license for extended Kubernetes version support"}
`
make e2e-cross-binary
make local-e2e

add license token to CloudStack proxy config tests

---

test/e2e/vsphere_test.go

Similar to [#9297](https://github.com/aws/eks-anywhere/pull/9297), this PR fixes more vSphere tests which are failing due to missing license tokens.

Fix more vsphere tests with missing license tokens

---

test/e2e/cloudstack_test.go

Similar to [#9304](https://github.com/aws/eks-anywhere/pull/9304), this PR adds license token to CloudStack tests.

Add license token to CloudStack tests

---

test/e2e/docker_test.go
test/e2e/nutanix_test.go

Similar to [#9304](https://github.com/aws/eks-anywhere/pull/9304), this PR adds license token to Docker and Nutanix tests.

Add license token to Docker and Nutanix tests

---

pkg/api/v1alpha1/cluster_types.go
pkg/clustermarshaller/clustermarshaller_test.go
pkg/clustermarshaller/testdata/expected_marshalled_cluster.yaml
pkg/clustermarshaller/testdata/expected_marshalled_cluster_flux_and_gitops.yaml
pkg/clustermarshaller/testdata/expected_marshalled_cluster_flux_config.yaml

https://github.com/aws/eks-anywhere/pull/9112 added licenseToken to cluster spec. The ConvertConfigToConfigGenerateStruct() function, which handles cluster marshalling, was not updated to include the LicenseToken field. This meant for some specific flows such as flux, local cluster spec written to disk, spec outputted in CLI during create - this field was always being dropped. 
- Add LicenseToken and EtcdEncryption fields to ClusterGenerate struct
- Ensure these fields are included when converting Cluster to ClusterConfig which is then written to disk
- Fix issue where license token was not persisting in Git config
Ran a local-e2e and verified that the flux tests passed. 
*Documentation added/planned (if …

include LicenseToken and EtcdEncryption in cluster config marshaling

---

test/e2e/cloudstack_test.go
test/e2e/nutanix_test.go
test/e2e/tinkerbell_test.go
test/e2e/vsphere_test.go
test/framework/cloudstack.go
test/framework/nutanix.go
test/framework/tinkerbell.go
test/framework/vsphere.go

RHEL 8 is currently using a kernel version of 4.18.0, which is not supported by kubeadm 1.32.
`[ERROR SystemVerification]: kernel release 4.18.0-553.40.1.el8_10.x86_64 is unsupported. Recommended LTS version from the 4.x series is 4.19. Any 5.x or 6.x versions are also supported. For cgroups v2 support, the minimal version is 4.15 and the recommended version is 5.8+`
so we remove all e2e tests running RHEL 8 on k8s 1.32 and cleanup all rhel8 1.32 helper function
Testing:
make e2e-cross-platform

Remove RHEL 8 K8s 1.32 tests

---

Makefile

[release-0.22] Update BRANCH_NAME on release-0.22

---

release/cli/pkg/assets/config/bundle_release.go
release/cli/pkg/bundles/eksd.go

Remove Bottlerocket AMI from release artifacts list.

Remove Bottlerocket AMI from release artifacts list

---

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/conformance-eks-a-cli.yml
cmd/integration_test/build/buildspecs/docker-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/tinkerbell-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml
cmd/integration_test/cmd/run.go
internal/test/e2e/common.go
internal/test/e2e/run.go
internal/test/e2e/setup.go

This PR updates the e2e tests to use the prod license tokens for the tests triggered by the staging pipeline. This is because we updated the extended support validations in [#9248](https://github.com/aws/eks-anywhere/pull/9248) to use a different public key for verifying the license tokens as we don't want the license tokens from non-production subscriptions to be valid in prod EKS-A releases.
The license token env variable value is overwritten with a different staging env variable from secrets manager with a logic similar to how it was done before for the regional packages test in [#6964](https://github.com/aws/eks-anywhere/pull/6964). …

Use the prod license tokens for staging tests

---

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/conformance-eks-a-cli.yml
cmd/integration_test/build/buildspecs/docker-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/nutanix-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/tinkerbell-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml

This PR fixes setting the stage variable in integration tests buildspec files for staging pipeline. The staging job was throwing the following error before this change:
```
/codebuild/output/tmp/script.sh: line 4: CODEBUILD_INITIATOR: command not found
```
This is because of the round brackets around that variable in the buildspec file. The round brackets in bash script makes it a command instead of a variable. Removing the brackets should fix this issue. This PR also updates the buildspec for Nutanix to use the prod license token for staging tests.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

Fix setting the stage variable in integration tests buildspec files

---

docs/content/en/docs/whatsnew/changelog.md

Changelog for v0.22.0

---

docs/config.toml

Reverts PR Add v0.22 to doc site versions config https://github.com/aws/eks-anywhere/pull/9344/files

Revert "Add v0.22 to doc site versions config"

---

docs/config.toml

Add v0.22 to doc site versions config

Add v0.22 to doc site versions config

---

docs/config.toml

Fix docs url for release 0.21, change 0.21 to 0-21

Fix docs url for release 0.21

---

docs/content/en/docs/getting-started/vsphere/vsphere-spec.md

https://github.com/aws/eks-anywhere-internal/issues/2441
This PR updates docs for VSphere failure domain support

Update docs for VSphere failure domain support

---

docs/content/en/docs/troubleshooting/troubleshooting.md

https://github.com/aws/eks-anywhere/issues/8517
Added verbiage about infra-specific commands 
capc-system vs capv-system (CloudStack vs vSphere - for example)

Added verbiage about infra-specific commands

---

test/framework/testdata/adot_package_daemonset.yaml
test/framework/testdata/adot_package_deployment.yaml

- This PR updates e2e testdata config for ADOT package by replacing logging exporter with debug exporter, logging exporter was removed from [upstream](https://github.com/open-telemetry/opentelemetry-collector/pull/11037) so this will resolve the failing e2e tests for ADOT.
- Verified the changes by successfully executing the local e2e-test `TestVSphereKubernetes131CuratedPackagesAdotUpdateFlow`.
By submitting this pull request, I confirm that you c an use, modify, copy, and redistribute this contribution, under the terms of your choice.

Updated testdata yaml for ADOT package

---

docs/content/en/docs/whatsnew/changelog.md

Listing the warning in our changelog based on https://github.com/aws/eks-anywhere-build-tooling/pull/4330. Once we get more details, will update the changelog here as well as the above issue.

Add cilium warning in docs

---

test/e2e/QUICK_TESTS.yaml
test/e2e/vsphere_test.go

Remove TestVSphereKubernetes131To132RedHatUpgrade from e2e tests since k8s 1.32 does not support RHEL 8.
Change quick e2e to run the 130to131 upgrade test.

Remove TestVSphereKubernetes131To132RedHatUpgrade from e2e tests

---

test/framework/cluster.go

#2855
This PR fixes the upgrade from latest minor release E2E tests for all providers. Some of these tests include:
```
TestDockerKubernetes128to129UpgradeFromLatestMinorRelease
TestVSphereKubernetes128UpgradeManagementComponents
TestVSphereKubernetes128To129RedhatUpgradeFromLatestMinorRelease
TestVSphereKubernetes128To129UbuntuUpgradeFromLatestMinorRelease
TestCloudStackKubernetes128WithOIDCManagementClusterUpgradeFromLatestSideEffects
```

Fix upgrade from latest minor release E2E test failures

---

test/framework/cluster.go
test/framework/common.go

This PR updates the upgrade from latest minor release tests to use the staging license token for extended support. This is because these tests first create a cluster from the latest production minor release binary for which the CLI and controller does the license token verification with a different KMS public key used specifically for production releases.
Ran a test locally and it passed

Use staging license token for upgrade from latest minor release tests

---

test/e2e/side_effects.go
test/framework/cluster.go
test/framework/common.go

This PR fixes the non-unique license token failures in upgrade from latest side effects tests. Before this change, the tests fail with the following error:
```
Error: validations failed: validating licenseToken is unique for cluster main-i-0612d-53a064b-w-0: license token <license-token-string> is already in use by cluster main-i-0612d-53a064b
```

Fix non-unique license token failures in upgrade from latest side effects tests

---

OWNERS

Add junpengdev to owners list

---

docs/content/en/docs/getting-started/optional/cni.md
pkg/api/v1alpha1/cluster.go
pkg/api/v1alpha1/cluster_test.go
pkg/networking/cilium/templater.go
pkg/networking/cilium/templater_test.go

*Description of changes: The routingMode parameter name injecting differently "routing-mode" This cause the wrong cilium configuration deployment.
With 1.15 , cilium also require ipv4NativeRoutingCIDR or ipv6NativeRoutingCIDR parameters if routingMode is set to native
*Testing (if applicable): Vsphere deployment is tested and  two unit tests are added  
*Documentation added/planned (if applicable):  Cilium documentation updated

Fixing cilium routingMode parameters in helm configuration

---

test/e2e/certmanager.go
test/e2e/curatedpackages.go

This PR fixes the packages workload cluster tests failing with the following error:
```
validating licenseToken is unique for cluster eksa-test-f4b7542-w-0: license token <license-token-string> is already in use by cluster eksa-test-f4b7542
```
This should fix the following tests:
```
TestVSphereKubernetes128UbuntuWorkloadClusterCuratedPackagesSimpleFlow
TestVSphereKubernetes128UbuntuWorkloadClusterCuratedPackagesEmissarySimpleFlow
TestVSphereKubernetes128BottleRocketWorkloadClusterCuratedPackagesSimpleFlow
TestVSphereKubernetes128BottleRocketWorkloadClusterCuratedPackagesEmissarySimpleFlow
TestVSphereKubernetes128UbuntuWorkloadClusterCuratedPackagesCertManagerSimpleFlow …
```

Fix non-unique license token errors in packages workload cluster tests

---

pkg/providers/vsphere/validator.go
pkg/providers/vsphere/vsphere.go
pkg/providers/vsphere/vsphere_test.go

[3055](https://github.com/aws/eks-anywhere-internal/issues/3055)
- When a user tries to create a vSphere cluster and does not have sufficient permissions, a documentation link to our vSphere permissions docs is now added along with a tip on increasing verbosity for additional info.
- Verbose logging output of missing permissions is now output in JSON and indicated as so, versus YAML for easier identification and parsing.
modified existing test in vsphere_test.go

Add doc in vsphere error message & improve verbose logging output

---

test/e2e/emissary.go

Similar to [#9416](https://github.com/aws/eks-anywhere/pull/9416), this PR fixes the emissary workload cluster tests.

Fix non-unique license token errors in emissary workload cluster tests

---

test/e2e/airgap.go
test/e2e/docker_test.go
test/e2e/multicluster.go
test/e2e/side_effects.go
test/e2e/tinkerbell_test.go
test/e2e/upgrade_from_latest.go
test/e2e/vsphere_test.go
test/framework/cluster.go
test/framework/multicluster.go

This PR fixes the following license token errors for e2e tests:
```
Error: the cluster config file provided is invalid: unable to parse release-i-0427d-e459c61-w-0/release-i-0427d-e459c61-w-0-eks-a.yaml file: error unmarshaling JSON: while decoding JSON: json: unknown field "licenseToken"
```
This error was observed in all `TestCloudStackKubernetes1XXWithOIDCManagementClusterUpgradeFromLatestSideEffects ` tests on staging pipeline for release-0.22 patch release. This is because when the test is triggered from 0.22 branch, the latest previous minor release is 0.21 which does not have extended support.
```
Error: validations failed: validating licenseToken is unique for …
```

Fix license token errors in e2e tests

---

pkg/executables/govc.go
pkg/executables/govc_test.go

See details here
[3097](https://github.com/aws/eks-anywhere-internal/issues/3097)
- Altered GroupExists method to account for change in govc response behavior
- Modified unit tests
Modified unit tests in govc_test.go to mimic new behavior
n/a

Fix vsphere group creation

---

docs/content/en/docs/packages/packagebundles.md

Enhances the Package Bundles documentation by adding a direct hyperlink to the ECR repository (https://gallery.ecr.aws/eks-anywhere/eks-anywhere-packages-bundles). Current documentation only references public.ecr.aws/eks-anywhere without a direct link
Adding the ECR repository link will:
- Improve user experience by providing quick access to the repository
- Enable users to easily discover and access historical package bundle versions
- Simplify the process of finding specific tags for packagebundles images
*Description of changes:*  docs/content/en/docs/packages/packagebundles.md | line 25 
*Documentation added/planned (if applicable):* https://gallery.ecr.aws/eks-anywhere/eks-anywhere-packages-bundles …

Add hyperlink to public.ecr repository

---

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/conformance-eks-a-cli.yml
cmd/integration_test/build/buildspecs/docker-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/nutanix-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/snow-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/tinkerbell-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml

https://github.com/aws/eks-anywhere/issues/9178
Updating code build spec to use role for fetching aws credentials and setting them as environment variables.
Tested the logic of getting credentials by running an code build with override.

Use roles to get access key details in build spec

---

test/e2e/QUICK_TESTS.yaml
test/e2e/vsphere_test.go
test/framework/vsphere.go

https://github.com/aws/eks-anywhere-internal/issues/2381
Add e2e tests for RHEL 9 on vSphere
Ran these tests locally:
- `TestVSphereKubernetes132RedHat9SimpleFlow`
- `TestVSphereKubernetes131To132RedHat9Upgrade`

Add e2e tests for RHEL 9 on vSphere

---

.github/workflows/golangci-lint.yml
.golangci.yml
controllers/cluster_controller.go
pkg/validations/cluster.go

https://t.corp.amazon.com/P211307329
**Commit 1**
Snow team ran into an issue with one of their airgapped upgrade tests for EKS-A v0.22.x versions where the test failed with the following validation error:
```
[ec2-user@ip-34-223-14-196 ~]$ eksctl anywhere upgrade cluster -f /home/ec2-user/eksa-cluster-eks-anywhere-cluster-1742487914005.yaml -v4 --bundles-override /usr/lib/eks-a/manifests/bundle-release.yaml
2025-03-20T20:21:16.949Z    V4  Reading release manifest    {"url": "https://anywhere-assets.eks.amazonaws.com/releases/eks-a/manifest.yaml"}
2025-03-20T20:21:17.016Z    V0  ❌ Validation failed {"validation": "validate extended kubernetes version support is supported", "error": "getting bundle for cluster: reading Releases file: …
```

Skip extended kubernetes version support validations for Snow provider

---

pkg/dependencies/factory.go
pkg/dependencies/factory_test.go
test/e2e/vsphere_test.go

- Updated `noProxyList` for package controller to include control plane endpoint, service CIDR and pod CIDR
- Added tests for curated packages simple flow with proxy configuration.
*Testing:*
`./bin/e2e.test -test.v -test.run TestVSphereKubernetes130CuratedPackagesProxyConfigFlow`

Update noProxyList for package controller to include control plane endpoint, service CIDR and pod CIDR

---

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/conformance-eks-a-cli.yml
cmd/integration_test/build/buildspecs/docker-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/nutanix-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/snow-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/tinkerbell-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml

#9178 
Updating the duration to the max set for the role as our tests run longer than the default duration of 15 min. Results in only the first few tests that run within 15 min of getting these assume role creds in the codebuild job.
Error:
```
2025-03-27T09:37:58.114Z	ECRCredInjector	Failed to inject ECR credential to docker config	{"error": "operation error ECR: GetAuthorizationToken, https response error StatusCode: 400, RequestID: 2310eae1-c207-48d9-8ac2-443cd40707a8, api error UnrecognizedClientException: The security token included in the request is invalid."}
github.com/aws/eks-anywhere-packages/pkg/registry.(*ECRCredInjector).Run
github.com/aws/eks-anywhere-packages/pkg/registry/ecr_cred_injector.go:56
```
*Testing (if …

Set duration of packages roles to 12 hours

---

cmd/integration_test/build/buildspecs/cloudstack-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/conformance-eks-a-cli.yml
cmd/integration_test/build/buildspecs/docker-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/nutanix-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/quick-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/snow-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/tinkerbell-test-eks-a-cli.yml
cmd/integration_test/build/buildspecs/vsphere-test-eks-a-cli.yml

Previous PR: https://github.com/aws/eks-anywhere/pull/9482
Need to set it to 1 hour as role chaining duration limit is only 1 hour
Error:
```
An error occurred (ValidationError) when calling the AssumeRole operation: The requested DurationSeconds exceeds the 1 hour session limit for roles assumed by role chaining.
```

Set duration of packages roles to 1 hour

---

cmd/eksctl-anywhere/cmd/upgrademanagementcomponents.go
pkg/api/v1alpha1/cluster_types.go
pkg/api/v1alpha1/cluster_types_test.go
pkg/api/v1alpha1/cluster_webhook.go
pkg/validations/upgradevalidations/preflightvalidations.go
pkg/workflows/management/upgrade_management_components.go
pkg/workflows/management/upgrade_management_components_test.go

Upgrade cluster command already supports a skip-validations flag that lets users skip a preflight that's skippable. Add similar functionality to upgrade management-components command. The only preflight that will be skippable in this command would be the 'eksa-version-skew' which checks for version skew during an upgrade is not more than 1 minor version. Also for the upgrade command controller wasn't honoring the skipped validations passed through the flag. This change also fixes the controller to respect the flag.
```
eksadmin@rahulgab-dev:~/L3/eks-anywhere$ ./bin/skip-skew/eksctl-anywhere upgrade management-components -h
The term 'management components' encompasses all Kubernetes controllers and their CRDs present in the management cluster that are responsible for reconciling your EKS …
```

Add skip-validations flag to upgrade management components command

---

release/cli/pkg/helm/helm.go

Use SourceImageURI for helm chart modifications for dev similar to how we did in [other helm chart modification step](https://github.com/aws/eks-anywhere/pull/8469/files) 
Context:
In dev bundle, package controller and ecr token refresher version tags are updated incorrectly (pointing to outdated images). This PR is an attempt to fix this issue by using source image uri instead of release image uri in helm chart modification step.

Use SourceImageURI for helm chart modifications for dev

---

release/cli/pkg/helm/helm.go

The dev release started failing after https://github.com/aws/eks-anywhere/pull/9497 was merged with the following error:
```
Error generating image digests table: generating image digests table: getting image digest for image public.ecr.aws/l0g8r8j6/tinkerbell/stack:0.6.2-eks-a-v0.23.0-dev-build.58: ImageNotFoundException: The image with imageId {imageDigest:'null', imageTag:'0.6.2-eks-a-v0.23.0-dev-build.58'} does not exist within the repository with name 'tinkerbell/stack' in the registry with id '857151390494'
```
I think this is because the `ModifyAndPushChartYaml` function is also being called during artifacts upload phase for the tinkerbell helm chart images [here](https://github.com/aws/eks-anywhere/blob/main/release/cli/pkg/operations/upload.go#L157) due …

Use SourceImageURI only for packages helm chart modification in dev release

---

release/cli/pkg/bundles/package-controller.go

We are seeing `ImagePullBackoff` error in the packages tests on main and release branches after merging #9497 and #9504.
Packages tests on main:
```
"message": "Back-off pulling image "public.ecr.aws/x3k6m8v0/ecr-token-refresher:latest"
```
Packages tests on release-0.22:
```
"message": "Back-off pulling image "public.ecr.aws/w9m0f3l5/ecr-token-refresher:release-0.22"
```
I believe this is because we didn't replace the ReleaseImageUri with SourceImageUri when updating the tags for the `eks-anywhere-packages` and `ecr-token-refresher` images.
This PR replaces the ReleaseImageUri with SourceImageUri in the logic for updating the image tags for the `eks-anywhere-packages` and `ecr-token-refresher` images. It also fixes the conditions for …

Use source image URI for replacing packages and ecr token refresher image tags

---

release/cli/pkg/bundles/package-controller.go

Following up to 9511, this PR also updates the release image URI with source image URI for helm charts too when replacing the tags.

Use source image URI for packages helm chart when replacing tags

---

release/cli/pkg/bundles/package-controller.go

The dev bundle had the latest tag for packages controller and ecr token refresher images after #9511 and #9514 were merged. But the sha256 digest still pointed to an older image from June 10, 2024. This is because we are looking for the latest tags with v0.0.0 prefix for images and 0.0.0 prefix for helm charts in the dev release which was implemented by the former packages team in [#4793](https://github.com/aws/eks-anywhere/pull/4793) and we stopped pushing dev images with those 0.0.0 tags since June 10, 2024 after we started building the packages only from regional beta account. This is why it has been using that old image with 0.0.0 prefix from last year.
This PR changes the prefix to be an empty string so that it looks for the absolute …

Find latest pushed image in ECR for packages without any prefix

---

release/cli/pkg/aws/ecr/ecr.go
release/cli/pkg/bundles/package-controller.go

After merging [#9519](https://github.com/aws/eks-anywhere/pull/9519), the dev bundle now has the latest tag but it still doesn't filter the tags based on branch name. This is why the dev bundle built from main has the tag from the release branch. The helm chart and the image for the eks-anywhere-packages repository both have the same tag but they are expected to have different tags. Helm chart tags start directly with the semver (ex:- 0.4.6) whereas image tags start with the 'v' followed by the semver (ex:- v0.4.6). 
This PR updates the logic to get the latest tag based on branch name and also uses different tags for helm charts and images based on whether the tag contains "helm" in it. 
*Documentation …

Filter images based on branch and get the latest tag

---

release/cli/pkg/aws/ecr/ecr.go
release/cli/pkg/bundles/package-controller.go

After merging [#9519](https://github.com/aws/eks-anywhere/pull/9519), the dev release started throwing this error message but the job itself didn't fail:
```
msg="initializing source docker://067575901363.dkr.ecr.us-west-2.amazonaws.com/ecr-token-refresher:v0.4.5-ee5506184b3dce86716eaf644d4b416661ae459f: reading manifest v0.4.5-ee5506184b3dce86716eaf644d4b416661ae459f in 067575901363.dkr.ecr.us-west-2.amazonaws.com/ecr-token-refresher: manifest unknown: Requested image not found"
Error happened during retry after 10 retries: executing skopeo copy command: exit status 1
Execution aborted by retry policy
Error copying dev EKS Anywhere package ecr token refresher image, to ECR Public: retries exhausted performing image copy from source …
```

Use correct registry account id when pulling latest image and cleanup old code

---

release/cli/pkg/helm/helm.go

After merging #9525, the dev-release is failing with the following error:
```
message": "Back-off pulling image \"public.ecr.aws/x3k6m8v0/ecr-token-refresher:latest\""
```
This is because the values.yaml file in the helm chart is modified to look for the latest tags in the regional beta public ECR where it doesn't exist.
This PR updates the logic to use tags from the release image URI instead of source image URI when modifying the helm chart so that it gets the correct tag from the build account public ECR. It was recently changed from release image URI to source image URI in #9497. …

Use tag from release image URI when overriding packages image tag in helm chart

---

release/cli/pkg/aws/ecr/ecr.go
release/cli/pkg/bundles/package-controller.go
release/cli/pkg/helm/helm.go

This PR reverts #9528, #9525, #9522 and #9519 and just updates the registry account id to the regional beta account to get the latest commit with prefix `0.0.0` for helm charts and `v0.0.0` for images.

Revert 9528 9525 9522 and 9519

---

release/cli/pkg/bundles/package-controller.go
release/cli/pkg/helm/helm.go

Even after reverting the prefix changes in #9531, we are still seeing `ImagePullBackOff` errors for packages images due to incorrect tags being set in the helm chart. This is because we replaced release image URI with source image URI for helm chart modifications.
```
"message": "Back-off pulling image "public.ecr.aws/w9m0f3l5/ecr-token-refresher:release-0.22"
```
This PR reverts #9514, #9511, #9504 and #9497.

Revert 9514 9511 9504 and 9497

---

release/cli/pkg/aws/ecr/ecr.go

[#3171](https://github.com/aws/eks-anywhere-internal/issues/3171)
This PR explicity sets the registry id in the describe-images API input to get the images from the registry in the appropriate account. For packages, we get the images from the regional beta account private ECR whereas for all other components, we get it from the build account private ECR.
Tested the dev-release by triggering the codebuild job manually and it gets the images from the correct account for packages

Use regional beta account for packages to get image digests

---

test/e2e/certmanager.go
test/framework/cluster.go
test/framework/curatedpackages.go
test/framework/testdata/certmanager/certmanager_letsencrypt_issuer.yaml
test/framework/testdata/certmanager/certmanager_package.yaml

https://github.com/aws/eks-anywhere/issues/9177
In testing cert manger, we use access key and Id (see [here](https://github.com/aws/eks-anywhere/blob/c966d16b5a654c07621171a43db3502f55b90e35/test/framework/cluster.go#L1823)) to test cert manager. ClusterIssuer does not have support for session token. One workaround is to use [Ambient credentials](https://cert-manager.io/docs/configuration/acme/dns01/route53/#ambient-credentials) approach where environment variables like AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN are set in the cert manager pod.
In this PR, I am adding a test data (with AWS credentials - key, id, sessiontoken) for cert manager and use that to create cert manager pod and remove the [current …

Set Aws credentials in cert manager package pod for e2e test

---

release/cli/pkg/aws/ecr/ecr.go

Account ID can be fetched directly from the image container registry since we are not calling this function with the public ECR registry. There is another [GetImageDigest](https://github.com/aws/eks-anywhere/blob/main/release/cli/pkg/aws/ecrpublic/ecrpublic.go#L29) function defined in the `ecrpublic` package for public ECR registries so that doesn't need to be handled here.

Get account id from the image registry instead of hardcoding

---

pkg/curatedpackages/packagecontrollerclient.go
pkg/curatedpackages/regional_registry.go
release/Makefile
release/api/v1alpha1/groupversion_info.go
release/cli/cmd/release.go
release/cli/pkg/assets/tagger/tagger.go
release/cli/pkg/aws/ecr/ecr.go
release/cli/pkg/bundles/package-controller.go
release/cli/pkg/git/git.go
release/cli/pkg/images/images.go
release/cli/pkg/types/types.go
release/scripts/release.sh

Currently, all the packages tests are failing on main with the following error:
```
2025-03-31T17:14:29.986Z        PackageBundleController Unable to get latest bundle     {"error": "pulling package bundle: fetch manifest: GET \"https://067575901363.dkr.ecr.us-west-2.amazonaws.com/v2/eks-anywhere-packages-bundles/manifests/v1-30-latest\": basic credential not found"}
```
This is because we recently moved away from long-term IAM user credentials and started using IAM roles to configure temporary credentials through session token for packages tests ([#2650](https://github.com/aws/eks-anywhere-internal/issues/2650)). We cut a new tag for the packages controller with those changes but the dev bundle still points to an older tag for the `eks-anywhere-packages` and …

Add logic to release packages images to beta account public ECR for dev release

---

release/cli/pkg/clients/clients.go
release/cli/pkg/images/images.go
release/cli/pkg/operations/upload.go

The `dev-release` on main failed with the following error:
```
time="2025-04-08T22:25:37Z" level=fatal msg="trying to reuse blob sha256:31edd427fc7a581b43b5bdf7025583aa4b3e73ee9809529c6065cdde0a5a738e at destination: failed to read from destination repository x3k6m8v0/credential-provider-package: 403 (Forbidden)"
time="2025-04-08T22:25:38Z" level=fatal msg="trying to reuse blob sha256:31edd427fc7a581b43b5bdf7025583aa4b3e73ee9809529c6065cdde0a5a738e at destination: failed to read from destination repository x3k6m8v0/ecr-token-refresher: 403 (Forbidden)"
time="2025-04-08T22:25:42Z" level=fatal msg="trying to reuse blob sha256:544036502652dfe56a7885ae1473056cabf38843c693d5ee62925ee1c4a831ac at destination: failed to read from destination repository …
```

Use packages-related clients for authenticating to packages release registry

---

release/cli/pkg/clients/clients.go
release/scripts/setup-aws-config.sh

The `dev-release` on main failed with the following error:
```
==========================================================
Dev Release Clients Creation
==========================================================
Error creating clients: UnsupportedCommandException: GetAuthorizationToken command is only supported in us-east-1.
```
This PR updates the packages public ECR client to use the IAD session for fixing the above issue.

Use IAD session for packages release public ECR client

---

release/cli/pkg/images/images.go
release/scripts/setup-aws-config.sh

This PR appends the IAD profile to the aws config file instead of overwriting as we need both the profiles for dev release. It also removes the verbose debug logging from skopeo command to reduce noise.

Append the IAD profile instead of overwriting

---

release/cli/pkg/bundles/package-controller.go

This PR fixes the public ECR release client used for packages images in the `Bundles Manifest Spec Generation` phase.

Fix public ECR release clients for packages

---

release/cli/pkg/operations/bundle_release.go

eksa dev build is failing with below error. This is because, we have changed to pull packages from packages dev account.
`
Error generating image digests table: generating image digests table: getting image digest for image public.ecr.aws/x3k6m8v0/eks-anywhere-packages:0.4.6-eks-a-v0.23.0-dev-build.71: RepositoryNotFoundException: The repository with name 'public.ecr.aws/x3k6m8v0/eks-anywhere-packages' does not exist in the registry with id 
`
In this PR, I am updating the imageDigest logic to use packages client for packages image uri

Use Packages client for fetching dev image digest for  package

---

release/cli/pkg/aws/ecr/ecr.go
release/cli/pkg/aws/ecrpublic/ecrpublic.go
release/scripts/setup-aws-config.sh

[#3171](https://github.com/aws/eks-anywhere-internal/issues/3171)
This PR exports the `AWS_SDK_LOAD_CONFIG` env variable to use the correct profiles for clients and reverts [#9534](https://github.com/aws/eks-anywhere/pull/9534) and [#9581](https://github.com/aws/eks-anywhere/pull/9581).
Manually kicked off a one-off job run with the env variable set and it succeeded
https://tiny.amazon.com/jxkct0gb/IsenLink

Export AWS_SDK_LOAD_CONFIG env variable to use the correct profiles for clients

---

pkg/curatedpackages/packagecontrollerclient.go

This PR fixes the condition in the package controller client to check for the regional beta account public ECR alias when setting the dev registry. This is because we recently updated the release CLI to push the packages images to beta account instead of build account public ECR.

Fix condition to check for packages dev registry

---

pkg/executables/govc.go
pkg/executables/govc_test.go
pkg/providers/vsphere/mocks/client.go
pkg/providers/vsphere/vsphere.go
pkg/providers/vsphere/vsphere_test.go

https://github.com/aws/eks-anywhere-internal/issues/3004
adds compute cluster validation for failure domains
See compute cluster validation fields
```
[ec2-user@ip-172-31-22-5 eks-anywhere]$ ./bin/eksctl-anywhere exp validate create cluster -f ~/vsphere/largchar-colo-mgmt-vsphere-fd.yaml
Warning: VSphereDatacenterConfig configured in insecure mode
Warning: The recommended size of an external etcd cluster is 3 or 5
Warning: VSphereDatacenterConfig configured in insecure mode
✅ Connected to server
✅ Authenticated to vSphere
✅ Datacenter validated
✅ Network validated
Start failure domain validation for 'fd-1' 
✅ Network validated
✅ Datastore validated
✅ Folder validated
✅ Resource pool validated
✅ Compute cluster …
```

Add compute cluster validations for failure domains

---

release/cli/pkg/aws/ecr/ecr.go
release/cli/pkg/bundles/package-controller.go
release/cli/pkg/operations/bundle_release.go

The dev bundle now has the latest tag but it still doesn't filter the tags based on branch name. This is why the dev bundle built from main has the tag from the release branch.
```
helmChart:
description: Helm chart for eks-anywhere-packages
imageDigest: sha256:52d1e552fd9ff933cc2d3ec2e57650294c23b4f6baecaab2108e8b01b27e09f8
name: eks-anywhere-packages
uri: public.ecr.aws/x3k6m8v0/eks-anywhere-packages:0.0.0-f34bb981a71e07b93ef8197b4937ca795f81d313-release-0.22-helm
```
This PR updates the logic to get the latest tag for helm chart images based on the branch name.
```
make -C release unit-test
```
By submitting this pull request, I confirm that you can use, modify, …

Add a filter to get the latest image based on branch for helm charts

---

release/cli/pkg/operations/bundle_release.go

After merging [#9578](https://github.com/aws/eks-anywhere/pull/9578), all the e2e tests started failing with the following error:
```
* metadata.annotations: Invalid value: "distro.eks.amazonaws.com/signature/1-31": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')
```
This PR fixes the above issue by replacing the '/' in the eks distro manifest signature annotations on the bundle with '-' to use a valid annotation key.
Ran the following …

Fix eks distro manifest signature annotations on the bundle

---

test/e2e/certmanager.go
test/framework/cluster.go

After merging [#9455](https://github.com/aws/eks-anywhere/pull/9455), all the cert manager e2e tests started failing with the following error:
```
cluster.go:2079: Error installing cert-manager pacakge: executing apply: Error from server (package test-cert-manager failed validation with error: package test-cert-manager should only be installed on a workload cluster): error when creating "STDIN": admission webhook "vpackage.kb.io" denied the request: package test-cert-manager failed validation with error: package test-cert-manager should only be installed on a workload cluster
``` 
This PR sets the workload cluster name in the `InstallCertManagerPackageWithAwsCredentials` function to install the cert-manager package on the workload cluster …

Fix cert manager e2e tests

---

controllers/cluster_controller.go
controllers/cluster_controller_test_test.go
pkg/validations/cluster.go
pkg/validations/cluster_test.go
pkg/validations/createvalidations/preflightvalidations_test.go
pkg/validations/extendedversion.go
pkg/validations/upgradevalidations/preflightvalidations_test.go

This change introduces version-based conditional validation for bundle signatures by skipping signature validation for EKS-A versions before v0.22.0. The change ensures backward compatibility while enforcing signature validation for newer EKS-A versions (v0.22.0 and above), which is when extended Kubernetes support was introduced.
When testing an LCM operation on workload cluster after upgrading the management cluster to v0.22.x notices the below error on reconciler for the workload cluster:
`{"ts":1744271253480.7832,"caller":"controller/controller.go:329","msg":"Reconciler error","controller":"cluster","controllerGroup":"anywhere.eks.amazonaws.com","controllerKind":"Cluster","Cluster":{"name":"rahul-tink-wkld","namespace":"default"},"na …

Skip bundle signature validation for EKS-A versions prior to v0.22.0

---

docs/content/en/docs/osmgmt/overview.md

Cherry-picked from https://github.com/aws/eks-anywhere/pull/9594
RHEL 9 is supported on vsphere since release v0.22.2 and is supported on baremetal since v0.20.0

[release-0.22] Documentation change for RHEL 9 support

---

docs/content/en/docs/osmgmt/overview.md

Doc change for rhel 9 support, RHEL 9 is supported on Nutanix, CloudStack and Baremetal since v0.20.0

[release-0.21] Doc change for rhel 9 support

---

docs/content/en/docs/getting-started/baremetal/bare-spec.md

Doc improvement for default OS on baremetal, we stopped supporting bottlerocket on baremetal since release 0.19 and are using Ubuntu as default OS.

Doc improvement for default OS on baremetal

---

.github/workflows/vulnerability.yml
go.mod
scripts/common.sh

Currently vulnerability check is failing with CVEs `GO-2025-3602` and `GO-2025-3601`, fixing them requires upgrading helm to 3.17.3 which would need upgrading controller-runtime to at least v0.18.x.
We will disable vulnerability check until controller-runtime is upgraded.
Also bumping go toolchain version to 1.23.8 to fix an vulnerability in 1.23.6
make eks-a
```
govulcheck ./...
Only has GO-2025-3601 and GO-2025-3602
```

Disable vulnerability check

---

docs/content/en/docs/clustermgmt/security/best-practices.md

https://github.com/aws/eks-anywhere-internal/issues/3219
Adding the other namespaces that were not called out

Add packages and etcdadm reserved namespaces in callouts for docs

---

controllers/cluster_controller.go
controllers/cluster_controller_test.go
pkg/signature/manifest.go
pkg/signature/manifest_test.go
pkg/validations/cluster.go
pkg/validations/extendedversion.go
pkg/validations/extendedversion_test.go
release/cli/pkg/signature/manifest_test.go

[#2994](https://github.com/aws/eks-anywhere-internal/issues/2994)
This PR adds a new extended support validation in the CLI and controller to verify the eks distro release manifest signature from the EKS-A bundle annotations.
Doc:- https://quip-amazon.com/HHz8AFaq0CAF/EKS-Distro-Manifest-Signing
Ran the following commands from the root folder:
```
make eks-a
make lint
make build-e2e-test-binary
make unit-test
```

Add extended support validation to verify the eks distro manifest signature

---

docs/content/en/docs/packages/credential-provider-package/iam_roles_anywhere.md

Mention in our documentation that the Credential Provider Package with IAM Roles Anywhere does not work on Bottlerocket due to an issue when executing the credential_process command on Bottlerocket.
https://github.com/aws/aws-sdk-go-v2/issues/2879

Doc improvement for Credential Provider Package with IAM Roles Anywhere

---

controllers/cluster_controller.go
controllers/cluster_controller_test.go
pkg/signature/manifest.go
pkg/signature/manifest_test.go
pkg/validations/extendedversion.go
pkg/validations/extendedversion_test.go
release/cli/pkg/operations/bundle_release.go
release/cli/pkg/signature/manifest.go
release/cli/pkg/signature/manifest_test.go

The 1.28 airgapped registry mirror tests failed with the following error:
```
"failureMessage": "reading eksd release manifest file: open eks-anywhere-downloads/1.28/eks-distro/kubernetes-1-28-eks-46.yaml: no such file or directory",
"failureReason": "ExtendedKubernetesVersionSupportNotSupported"
```
This is because the EKS-A controller is not able to access the local file path for the distro manifest on the admin machine. The controller should get the manifest from the Release object within the cluster once the EKS-D manifest is applied during cluster creation for any future upgrade validations. The CLI can get it from the local file path so this will require separate handling from the controller and the logic for eks distro manifest signature validation needs to …

Revert 9636 and 9609

---

test/e2e/tinkerbell_test.go

TestTinkerbellAirgappedKubernetes132UbuntuProxyConfigFlow has been failing with below error. This is because it is using 131 framework setup
```
Validation failed    {"validation": "tinkerbell Provider setup is valid", "error": "missing kube version from OSImageURL: url=http://10.80.18.43:8080/ubuntu/2004/ubuntu-1-31.gz, version=1.32", "remediation": ""}
```
In this PR, I am updating the test to use 132 framework setup

Fix framework setup for TestTinkerbellAirgappedKubernetes132UbuntuProxyConfigFlow

---

pkg/api/v1alpha1/vspheredatacenterconfig_types.go
pkg/api/v1alpha1/vspheredatacenterconfig_types_test.go
pkg/api/v1alpha1/vspheremachineconfig_types.go
pkg/api/v1alpha1/vspheremachineconfig_types_test.go
pkg/govmomi/client.go
pkg/govmomi/client_test.go
pkg/govmomi/mocks/client.go
pkg/providers/vsphere/validator.go
pkg/providers/vsphere/validator_test.go
pkg/providers/vsphere/vsphere.go
pkg/providers/vsphere/vsphere_test.go

[issue](https://github.com/aws/eks-anywhere-internal/issues/2985?issue=aws%7Ceks-anywhere-internal%7C3004)
- Adjusted missing permissions code to take a common interface between vspheremachineconfigs and failuredomains to compare similar values
- Added compute cluster permissions checking (using AdminPrivs file)
- Unit testing
- Here is an [example](https://tiny.amazon.com/x2boue8e/paste) missing permissions output when user has no permissions.

Add failure domains into missing permissions logic

---

release/cli/pkg/bundles/package-controller.go

All the packages E2E tests are failing on the release branch with the following error:
```
2025-04-20T03:46:56.748Z	V0	⚠️  Failed to install the optional EKS-A Curated Package Controller. Please try installation again through eksctl after the cluster creation succeeds	{"warning": "Error: public.ecr.aws/x3k6m8v0/eks-anywhere-packages:0.0.0-6b6163d76e817b54370ebe30334465d02363cfd9-release-0.22-helm: not found\n"}
```
This is because the packages helm charts for the release branch does not exist in the public ECR.
This PR updates the bundles manifest spec generation phase in the dev release to push the packages helm charts for all the branches and not just for the main branch to fix the above issue.
By submitting this pull request, I confirm …

Push packages helm chart to public ECR on all branches

---

cmd/eksctl-anywhere/cmd/upgradecluster.go

In the release-0.22, in an airgapped environment, upgrade command with the `--bunldles-override` flag panics during pre flight validation. This PR fixes that issue.
Created a cluster with the release version `v0.21.7` and upgraded it successfully with the release version `v0.22.x`.

Fix bundles override flag issue for upgrade cluster command

---

test/e2e/docker_test.go
test/e2e/upgrade_from_latest.go

The `TestDockerKubernetesUpgradeManagementComponents` and `TestDockerKubernetes132WithOIDCManagementClusterUpgradeFromLatestSideEffects` e2e tests have been failing on the `release-0.22` branch with the following error:
```
cluster.go:994: Command bin/v0.21.7/eksctl-anywhere [create cluster -f release-i-02fe7-b81ecc6/release-i-02fe7-b81ecc6-eks-a.yaml -v 6] failed with error: exit status 255: Error: unable to get cluster config from file: kubernetes version 1.32 is not supported by bundles manifest 91
```
This is because the latest minor release from 0.22 branch would be 0.21 which does not have kubernetes version 1.32 supported.
Failing upgrade from latest tests:
```
TestDockerKubernetesUpgradeManagementComponents …
```

Use 1.28 kubernetes version for docker upgrade from latest tests

---

test/e2e/SKIPPED_TESTS.yaml

The vSphere RHEL9 upgrade from latest tests have been failing on `release-0.22` branch because RHEL9 support for vSphere was added in v0.22.2 and the older EKS-D versions that comes with the v0.21.x latest minor release doesn't have the RHEL9 templates.
The CloudStack 1.32 upgrade from latest tests have been failing on `release-0.22` branch because the latest minor release v0.21.x doesn't support 1.32 version.
This PR skips those tests from running on `release-0.22` branch.

[release-0.22] Skip vSphere and CloudStack upgrade from latest tests

---

test/framework/curatedpackages.go

In e2e test, cert manager pod in worklaod cluster does not have session token set. This is because it is not in required env variables and hence we are not setting it. In this PR, I am adding to required env vars so that session token will be available in the cert manager pod def

Add ROUTE53_SESSION_TOKEN to required envs

---

docs/content/en/docs/whatsnew/changelog.md

This PR adds changelog for v0.22.4 patch release.

Add changelog for v0.22.4

---

pkg/diagnostics/collector_types.go
pkg/diagnostics/collectors.go
pkg/diagnostics/collectors_test.go
pkg/diagnostics/diagnostic_bundle.go
pkg/diagnostics/diagnostic_bundle_test.go
pkg/diagnostics/interfaces.go
pkg/diagnostics/interfaces/mocks/diagnostics.go

https://github.com/aws/eks-anywhere/issues/4179
Smee logs now accessible in support-bundle
The following gets added to support bundle yaml following troubleshoot docs [here](https://troubleshoot.sh/docs/host-collect-analyze/run/)
```
---
apiVersion: troubleshoot.sh/v1beta2
kind: HostCollector
metadata:
creationTimestamp: null
name: host-collector
spec:
collectors:
- run:
args:
- logs
- boots
collectorName: boots-logs
command: docker
outputDir: boots-logs
```
Creates a new nested directory at `host-collectors/run-host`
```
largchar@largchar-dev:~$ ls support-bundle-2025-04-24T04_37_28/host-collectors/run-host
```
Smee logs located here
```
largchar@largchar-dev:~$ ls support-bundle-2025-04-24T04_37_28/host-collectors/run-host/ …
```

Add boots/smee container logs to support bundle

---

pkg/executables/config/kind.yaml
pkg/executables/kind.go
pkg/executables/kind_test.go
pkg/executables/testdata/kind_config.yaml
pkg/executables/testdata/kind_config_docker_mount_networking.yaml
pkg/executables/testdata/kind_config_extra_port_mappings.yaml
pkg/executables/testdata/kind_config_registry_mirror_insecure.yaml
pkg/executables/testdata/kind_config_registry_mirror_with_auth.yaml
pkg/executables/testdata/kind_config_registry_mirror_with_ca.yaml

See [here](https://github.com/aws/eks-anywhere-internal/issues/3210) for details on change and verifications 
enables api server audit logs on kind bootstrap cluster
- unit tests
- tested on vsphere and docker providers

Enable api server audit logs on kind bootstrap cluster

---

pkg/providers/vsphere/config/template-cp.yaml
pkg/providers/vsphere/config/template-md.yaml
pkg/providers/vsphere/template_test.go
pkg/providers/vsphere/testdata/expected_kcp_vcenter_tags.yaml
pkg/providers/vsphere/testdata/expected_kct_vcenter_tags.yaml

Currently we aren't expanding the list as we are supposed to, causing the following error to happen:
```
Message:               failed to attach tags [urn:vmomi:InventoryServiceTag:a1d2082a-be0d-4601-b29d-1284214112ed:GLOBAL urn:vmomi:InventoryServiceTag:cc685066-57ff-420b-8d6f-a032c2382f43:GLOBAL] to VM mgmt-tags-test-md-0-zfpzj-6dvqc: [error: 0 type: cis.tagging.objectNotFound.error reason: Tagging object urn:vmomi:InventoryServiceTag:a1d2082a-be0d-4601-b29d-1284214112ed:GLOBAL urn:vmomi:InventoryServiceTag:cc685066-57ff-420b-8d6f-a032c2382f43:GLOBAL not found]
```
Now, we will be iterating through the list to be able to apply each of the tags to the machines if they exist. 
unit and functional testing …

Fix assigning multiple vcenter tags to a machine

---

pkg/api/v1alpha1/cluster_types.go
pkg/features/features.go
pkg/features/features_test.go
pkg/validations/cluster.go
pkg/validations/cluster_test.go
pkg/validations/createvalidations/preflightvalidations.go
pkg/validations/upgradevalidations/preflightvalidations.go
test/framework/cluster.go

https://github.com/aws/eks-anywhere-internal/issues/3286
Add feature flags for K8s 1.33
```
make eks-a
make unit-test
```

Add feature flags for K8s 1.33

---

cmd/eksctl-anywhere/cmd/generatebundleconfig.go
cmd/eksctl-anywhere/cmd/supportbundle.go
docs/content/en/docs/clustermgmt/support/supportbundle.md
docs/content/en/docs/reference/eksctl/anywhere_generate_support-bundle.md
pkg/clustermanager/cluster_manager.go
pkg/clustermanager/cluster_manager_test.go
pkg/diagnostics/collector_types.go
pkg/diagnostics/collectors.go
pkg/diagnostics/collectors_test.go
pkg/diagnostics/diagnostic_bundle.go
pkg/diagnostics/diagnostic_bundle_test.go
pkg/diagnostics/factory.go
pkg/diagnostics/interfaces.go
pkg/diagnostics/interfaces/mocks/diagnostics.go

https://github.com/aws/eks-anywhere-internal/issues/3210
Adds a flag `--audit-logs` to `generate support-bundle` command. When specified, will include the latest api server audit log file in the support bundle.
It achieves this by using troubleshoot, with the RunDaemonSet collector. It only runs on control plane nodes, via a node selector. Only the latest log file will be collected, which can be up to 512MB due to `audit-log-maxsize: "512"` on api server pods. With multiple control plane nodes, the max size of these logs included could be a few GB. 
Example run
```
./bin/eksctl-anywhere generate support-bundle -f ~/vsphere/largchar-colo-mgmt-vsphere.yaml --audit-logs
```
Example output from my support bundle
```
[ec2-user@ip-172-31-22-5 …
```

Add flag to include api server audit logs in support bundle

---

pkg/providers/tinkerbell/stack/stack.go
pkg/providers/tinkerbell/stack/stack_test.go

Manual backport of https://github.com/aws/eks-anywhere/pull/8760

[Release 0.22] Set some missing smee cli flags

---

test/e2e/SKIPPED_TESTS.yaml

The TestVSphereKubernetes132WithOIDCManagementClusterUpgradeFromLatestSideEffects e2e test have been failing on the release-0.22 branch with the following error:
Error: unable to get cluster config from file: kubernetes version 1.32 is not supported by bundles manifest 98
and test TestVSphereKubernetes132Redhat9UpgradeFromLatestMinorRelease fails with panic.
This is because the latest minor release from 0.22 branch would be 0.21 which does not have kubernetes version 1.32 supported.
Skipping these tests on the release-0.22 branch since the previous minor release-0.21 does not have 1.32 kubernetes support as well as RHEL9 support. 
This PR fixes the above issue by using kubernetes version 1.31 for these tests.

[release-0.22] Skip vSphere 1.32, RHEL9 e2e tests from latest minor release

---

pkg/api/v1alpha1/awsiamconfig_webhook.go
pkg/api/v1alpha1/awsiamconfig_webhook_test.go
pkg/api/v1alpha1/cloudstackdatacenterconfig_webhook.go
pkg/api/v1alpha1/cloudstackdatacenterconfig_webhook_test.go

Cloudstack E2E tests are failing with below error. This is because in the webhook validate method, code is still using receiver as new object but the receiver will be empty in the new webhook implementation in controller runtime.
In this PR I am fixing the issue to use new object instead of the receiver.
```
denied the request: CloudStackDatacenterConfig.anywhere.eks.amazonaws.com \"\" is invalid: spec.availabilityZone: Invalid value: []v1alpha1.CloudStackAvailabilityZone(nil): at least one AvailabilityZone must be shared between new and old CloudStackDatacenterConfig specs","errVerbose":"admission webhook \"validation.cloudstackdatacenterconfig.anywhere.amazonaws.com\" denied the request: …
```

Fix CloudstackDataCenter and awsiamconfig webhook update issue

---

docs/content/en/docs/troubleshooting/troubleshooting.md

Updated coredns troubleshooting steps
Coredns troubleshooting steps should add a note to perform validations on both management and workload clusters.
*Testing (if applicable):* n/a
*Documentation added/planned (if applicable):* yes

Updated coredns troubleshooting steps

---

pkg/providers/tinkerbell/stack/stack.go
pkg/providers/tinkerbell/stack/testdata/expected_upgrade.yaml
pkg/providers/tinkerbell/stack/testdata/expected_upgrade_with_proxy.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_docker.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_kubernetes.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_docker_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_hook_iso_override.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_hook_override.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_false.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_true.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_kubernetes_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_false.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_true.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_interface.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_proxy_config.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_registry_mirror.yaml

Current [version](https://github.com/aws/eks-anywhere-build-tooling/pull/4632) of Rufio supports [concurrent reconciliation](https://github.com/tinkerbell/rufio/issues/311) to be configured at the time of deployment. When provisioning higher number of nodes at the same time, a concurrent reconciliation of the queue helps in processing the BMC operations faster. 
Built cli and controller and verified that the bmc interactions for 20 nodes parallel provisioning  was way faster than the one without  any concurrent reconciliation.

Set concurrent reconciliation in Rufio

---

.github/workflows/golangci-lint.yml

The `golangci-lint` Github action workflow failed on [#9801](https://github.com/aws/eks-anywhere/pull/9801) with the following error:
```
Error: Failed to run: Error: requested golangci-lint version 'v2.0.1' isn't supported: we support only v2.1.0 and later versions, Error: requested golangci-lint version 'v2.0.1' isn't supported: we support only v2.1.0 and later versions
```
This is because we just bumped golangci-lint-action version to the latest v8.0.0 in [#9712](https://github.com/aws/eks-anywhere/pull/9712).
This PR bumps the `golangci-lint` version to latest v2.1.6 to fix the above issue.

Bump golangci-lint version to latest

---

config/manifest/eksa-components.yaml
controllers/cluster_controller.go
controllers/cluster_controller_test.go
controllers/cluster_controller_test_test.go
pkg/signature/manifest.go
pkg/signature/manifest_test.go
pkg/validations/cluster.go
pkg/validations/cluster_test.go
pkg/validations/createvalidations/preflightvalidations.go
pkg/validations/createvalidations/preflightvalidations_test.go
pkg/validations/extendedversion.go
pkg/validations/extendedversion_test.go
pkg/validations/upgradevalidations/preflightvalidations.go
pkg/validations/upgradevalidations/preflightvalidations_test.go
release/cli/pkg/signature/manifest_test.go

This is a manual cherry-pick of [#9801](https://github.com/aws/eks-anywhere/pull/9801).

[release-0.22] Validate eksd manifest signature for extended kubernetes version support

---

pkg/providers/nutanix/config/cp-template.yaml
pkg/providers/nutanix/testdata/expected_cluster_api_additional_trust_bundle.yaml

Passing AdditionalTrustBundle to CAPX using ConfigMap
Deployment CLI logs: 
[deployment.txt](https://github.com/user-attachments/files/20451778/deployment.txt)
Upgrade CLI logs after removing trustBunlde: 
[upgrade.txt](https://github.com/user-attachments/files/20451871/upgrade.txt)

Improvement: AdditionlTrustBundle using ConfigMap to CAPX

---

pkg/networking/cilium/templater.go
pkg/networking/cilium/templater_test.go

Replaces cilium-operator tolerations from tolerations: [{operator: Exists}] to
tolerations: [{key: "[node-role.kubernetes.io/control-plane](http://node-role.kubernetes.io/control-plane)", operator: "Exists"}, {key: "[node.kubernetes.io/not-ready](http://node.kubernetes.io/not-ready)", operator: "Exists"}, {key: "[node.cilium.io/agent-not-ready](http://node.cilium.io/agent-not-ready)", operator: "Exists"},]
Worker node upgrade workflow sometimes fail due to cilium operator getting scheduled onto the nodes marked for deletion as they have wildcard tolerations by default.
Performed manual testing by creating cluster with the change and verified that cilium-operator schedules similarly with the added tolerations. …

stops cilium operator from blocking draining of nodes

---

pkg/providers/cloudstack/cloudstack.go
pkg/providers/docker/docker.go
pkg/providers/mocks/providers.go
pkg/providers/nutanix/provider.go
pkg/providers/nutanix/provider_test.go
pkg/providers/provider.go
pkg/providers/snow/snow.go
pkg/providers/tinkerbell/tinkerbell_test.go
pkg/providers/tinkerbell/upgrade.go
pkg/providers/tinkerbell/upgrade_test.go
pkg/providers/vsphere/vsphere.go

There is an issue in the EKS-A bare metal upgrade flow where hardware was being applied with a new schema before the CRDs were updated, causing validation failures.
Key changes:
- Move hardware application logic from SetupAndValidateUpgradeCluster to PreCoreComponentsUpgrade to ensure hardware is applied after CRDs are updated
- Remove redundant PostBootstrapSetupUpgrade and PostBootstrapDeleteForUpgrade methods from the provider interface and all provider implementations
The issue was occurring because hardware was being generated and applied based on a new schema in the upgrade flow before the CRDs were actually updated, resulting in validation errors with messages like 
`unknown field 'spec.connection.providerOptions.preferredOrder'`. …

Fix hardware application sequence in Tinkerbell upgrade flow

---

docs/content/en/docs/getting-started/airgapped/airgap-steps.md
docs/content/en/docs/getting-started/optional/registrymirror.md
docs/content/en/docs/packages/prereq.md

https://github.com/aws/eks-anywhere-internal/issues/3337
Removed wrong packages copy command under Package Management -> Prerequisites and centralised packages copy documentation under package management. 

doc fixes for packages copy into airgapped registry

---

test/e2e/vsphere_test.go

Fix the wrong k8s version in TestVSphereKubernetes132To133OIDCUpgrade and TestVSphereKubernetes133BottlerocketEtcdScaleDown

Fix wrong k8s version in some 1.33 tests template

---

pkg/certificates/os.go
pkg/certificates/renewer.go
pkg/certificates/renewerubuntu.go

This PR enhances the certificate renewal functionality for EKS Anywhere clusters with external etcd configurations. The implementation removes the component parameter and now performs comprehensive certificate renewal for both etcd and control plane nodes when external etcd is present. Key improvements include skipping kubeadm certificate validation for external etcd setups to handle expired certificate scenarios, and deferring the API server etcd client secret update until after all control plane certificates are renewed. This ensures proper certificate propagation and cluster stability during the renewal process.
By submitting this pull request, I confirm that you …

update in ubuntu

---

docs/content/en/docs/getting-started/install/_index.md

The installation prerequisites [docs](https://anywhere.eks.amazonaws.com/docs/getting-started/install/) does not specify the required version of the yq dependency. A customer encountered issues with yq version 3.1.0-3 and upon investigating further, there are some significant syntax changes from minor version 3 to 4.
Ref:- https://t.corp.amazon.com/V1852316742
This PR updates the prerequisites docs to explicitly specify using version 4 or above for yq.
```
make -C docs build
```

Update installation docs to specify supported yq version

---

cmd/eksctl-anywhere/cmd/renewcertificates.go
pkg/certificates/config.go

This PR adds the ability to renew certificates by cluster name, discovering control plane and etcd node IPs using kubectl when the Kubernetes API server is reachable. When the API server is unreachable (which can happen during certificate expiration), it gracefully falls back to prompting users to provide node IPs in the configuration file. This improves user experience by reducing manual configuration steps when possible, while maintaining compatibility with scenarios where the API server is unavailable.

Fetch Control-Plane and etcd IPs for certificates renewal when API server is reachable

---

pkg/certificates/os.go
pkg/certificates/renewer.go
pkg/certificates/renewer_test.go
pkg/certificates/renewerbottlerocket.go
pkg/certificates/renewerubuntu.go
pkg/certificates/ssh.go

This PR adds the ability to renew certificates by component (etcd or control-plane) and improves the OS interface naming for better readability. Added `WithSSHLogging(false)` for Linux systems to prevent displaying sensitive information in logs.

Add certificates component renewal and improve OS interface readability

---

pkg/certificates/config.go
pkg/certificates/config_test.go
pkg/certificates/os_test.go
pkg/certificates/renewerbottlerocket_test.go
pkg/certificates/renewerubuntu_test.go

This PR adds unit tests for certificate renewal functionality, covering the implementation in renewerbottlerocket.go, renewerubuntu.go, config.go, and os.go files.

Add unit tests for bottlerocket/ubuntu/config/os

---

config/manifest/eksa-components.yaml
config/rbac/role.yaml
controllers/cluster_controller.go
controllers/cluster_controller_test_test.go
controllers/mocks/cluster_controller.go
pkg/api/v1alpha1/cluster_webhook.go
pkg/api/v1alpha1/cluster_webhook_test.go
pkg/awsiamauth/installer.go
pkg/awsiamauth/installer_test.go
pkg/awsiamauth/reconciler/reconciler.go
pkg/awsiamauth/reconciler/reconciler_test.go
pkg/controller/serverside/reconcile.go
pkg/controller/serverside/reconcile_test.go
pkg/filewriter/filewriter.go
pkg/filewriter/mocks/filewriter.go
pkg/filewriter/writer.go
pkg/filewriter/writer_test.go
pkg/validations/upgradevalidations/immutable_fields.go
pkg/validations/upgradevalidations/immutable_fields_test.go
pkg/workflows/interfaces/interfaces.go
pkg/workflows/interfaces/mocks/clients.go
pkg/workflows/management/write_cluster_config.go
pkg/workflows/workload/upgrade_test.go
pkg/workflows/workload/writeclusterconfig.go

https://github.com/aws/eks-anywhere-internal/issues/2455
Allows addition or deletion of aws iam authentication to an existing cluster using upgrade workflow. 

Allow aws iam config mutation for an existing cluster

---

pkg/providers/tinkerbell/stack/stack.go
pkg/providers/tinkerbell/stack/testdata/expected_upgrade.yaml
pkg/providers/tinkerbell/stack/testdata/expected_upgrade_with_proxy.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_docker.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_kubernetes.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_docker_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_hook_iso_override.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_hook_override.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_false.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_true.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_kubernetes_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_false.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_true.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_interface.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_proxy_config.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_registry_mirror.yaml

This change enables the controlPlaneTolerationsEnabled flag for all Tinkerbell stack components in the values override for the Tinkerbell Helm chart.
When enabled, this flag adds tolerations for the control plane taint while maintaining a preference for worker nodes through node affinity rules. This allows the Tinkerbell stack to be scheduled on control plane nodes when necessary (e.g., when worker nodes are unavailable), while still preferring worker nodes under normal circumstances.
This change restores the behavior that was present in EKS-A 0.19, where the Tinkerbell stack could be installed on both control plane and worker nodes, ensuring better availability during cluster lifecycle operations.
Built cli and …

Enable control plane tolerations for Tinkerbell stack components

---

test/e2e/constants.go
test/e2e/curatedpackages.go
test/e2e/vsphere_test.go
test/framework/cluster.go
test/framework/registry_mirror.go

https://github.com/aws/eks-anywhere-internal/issues/3276
Packages registry mirror e2e tests have been failing forever as we were not setting up the environment correctly. We missed copy packages to the registry mirror and adding an entry in ociNamespaces for the packages registry. 

Add missing copy packages cmd to fix e2e test

---

test/e2e/vsphere_test.go
test/framework/registry_mirror.go

*Description*
WithRegistryMirrorOciNamespaces uses regular registry and we need to be using private registry for authenticated registry mirror tests. Current test fails with error 
```
error logging into docker registry 196.18.8.18:443: Error response from daemon: Get "[https://196.18.8.18:443/v2/](https://196.18.8.18/v2/)": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
as wrong certificate is mounted on the machine.

fix RegistryMirrorCuratedPackages e2e wrong registry

---

test/e2e/constants.go
test/e2e/curatedpackages.go
test/e2e/vsphere_test.go
test/framework/cluster.go

AuthenticatedRegistryMirrorCuratedPackagesSimpleFlow test currently fails with error as it's trying to copy images into root of the mirror registry. This PR changes the destination project for package images. 
```
Error: cannot copy chart to repo: HEAD "https://196.18.89.98:443/v2/eks-anywhere-packages/manifests/sha256:14a559d530534fbc8af7ecfb520ad24f04be0e01ea319a3d9f569d3fd47709f9": response status code 400: Bad Request
```

fix registry mirror alias for curated package e2e

---

cmd/eksctl-anywhere/cmd/installpackagecontroller.go

https://github.com/aws/eks-anywhere-internal/issues/3528
Install package controller is not using the packages helm chart from bundles-override. This PR fixes that. 
Created a test cluster in vsphere and reinstalled package controller with custom helm chart. 

fix: install pkg ctlr not using helm chart from bundles override

---

test/e2e/constants.go
test/e2e/tinkerbell_test.go

[#3277](https://github.com/aws/eks-anywhere-internal/issues/3277)
This PR fixes the tinkerbell airgapped proxy tests by using the correct image URL path for the hook OS. The test was using a non-existent IP address which was the admin machine assigned to Jacob before but it doesn't exist anymore. That's why the test has been failing to bring up the control plane nodes since it is not able to install hookOS.
```
make eks-a
make lint
make unit-test
make e2e-tests-binary
```
Manually ran `TestTinkerbellAirgappedKubernetes133UbuntuProxyConfigFlow` test through Codebuild job and it passed
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …

Fix tinkerbell airgapped proxy tests

---

test/e2e/constants.go

[#3276](https://github.com/aws/eks-anywhere-internal/issues/3276)
The `TestVSphereKubernetes132UbuntuAuthenticatedRegistryMirrorCuratedPackagesSimpleFlow` test is failing with the following error:
```
Error: cannot fetch package bundle: public.ecr.aws/l0g8r8j6/eks-anywhere-packages-bundles:v1-32-latest: not found
cluster.go:995: Command failed, scanning output for error
cluster.go:1015: Command eksctl anywhere [copy packages 196.18.89.98:443/l0g8r8j6 --kube-version 1.32 --src-chart-registry public.ecr.aws/l0g8r8j6 --src-image-registry 067575901363.dkr.ecr.us-west-2.amazonaws.com --dst-insecure] failed with error: exit status 255: Error: cannot fetch package bundle: public.ecr.aws/l0g8r8j6/eks-anywhere-packages-bundles:v1-32-latest: not …
```

Use the correct dev public registry for registry mirror packages tests

---

pkg/providers/tinkerbell/stack/stack.go
pkg/providers/tinkerbell/stack/testdata/expected_tinkerbell_chart_overrides_with_all_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_upgrade.yaml
pkg/providers/tinkerbell/stack/testdata/expected_upgrade_with_proxy.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_docker.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_boots_on_kubernetes.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_docker_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_hook_iso_override.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_hook_override.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_false.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_host_port_enabled_true.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_kubernetes_options.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_false.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_enabled_true.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_load_balancer_interface.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_proxy_config.yaml
pkg/providers/tinkerbell/stack/testdata/expected_with_registry_mirror.yaml

Tink-worker image gets embedded into Hook-OS at build time. Pull the locally embedded image to circumvent against airgapped scenarios.
Tested with locally building cli and controller. 

Pull locally embedded tink-worker image

---

cmd/eksctl-anywhere/cmd/internal/commands/artifacts/import.go
codecov.yml
controllers/cluster_controller_test.go
controllers/controlplaneupgrade_controller_test.go
controllers/kubeadmcontrolplane_controller_test.go
pkg/executables/kubectl.go
test/framework/cluster.go

All the registry mirror tests are failing with the following error after the eks distro release version bump:
```
Error: writing images to destination with image mover: image processor worker failed, rest of jobs were aborted: unauthorized: project csi-components not found: project csi-components not found
```
This is because the latest EKS-D release removed all the CSI sidecar projects in [#3931](https://github.com/aws/eks-distro/pull/3931) but the csi-component images are still referenced in the manifest pointing to the [csi-components](https://gallery.ecr.aws/csi-components) registry instead of the original [eks-distro](https://gallery.ecr.aws/eks-distro) registry.
All the upgrade tests are failing with the following error after the eks distro release version bump:
```
cluster.go:770: …
```

Fix e2e test failures after bumping eks distro release

---

cmd/eksctl-anywhere/cmd/internal/commands/artifacts/import.go
codecov.yml
controllers/cluster_controller_test.go
controllers/controlplaneupgrade_controller_test.go
controllers/kubeadmcontrolplane_controller_test.go
pkg/executables/kubectl.go
test/framework/cluster.go

This is a manual cherry-pick of [#10044](https://github.com/aws/eks-anywhere/pull/10044) to release-0.22 branch.

[release-0.22] Fix e2e test failures after bumping eks distro release

---

docs/content/en/docs/clustermgmt/certificate-management/manual-steps-renew-certs.md

For Ubuntu and RHEL OS, the admin kubeconfig volume path is `/etc/kubernetes/admin.conf`. Updating our docs to the correct path.
Ex: [Tinkerbell template](https://github.com/aws/eks-anywhere/blob/main/pkg/providers/tinkerbell/config/template-cp.yaml#L329-L333)

Update admin conf file path for Ubuntu and RHEL

---

test/e2e/constants.go
test/e2e/curatedpackages.go
test/e2e/vsphere_test.go
test/framework/ecr.go

https://github.com/aws/eks-anywhere-internal/issues/3276
Fixes failing docker login as fetching ecr login-password was failing 
```
failed to fetch authorization token from ECR for registry 067575901363.dkr.ecr.us-west-2.amazonaws.com : %!w(*smithy.OperationError=&{ECR GetAuthorizationToken 0xc000c020f0})
```
```
./bin/e2e.test -test.run 'TestVSphereKubernetes130UbuntuAuthenticatedRegistryMirrorCuratedPackagesSimpleFlow' -test.v 9
```

Fix failing pkg registry docker login for pkg reg mirror e2e

---

docs/content/en/docs/clustermgmt/certificate-management/manual-steps-renew-certs.md

In a recent customer call, it was hard to update the apiserver-etcd-client secret as customer had to scramble for correct command under pressure. 
Tested updating on a test cluster

User friendly command to manual update apiserver-etcd-client secret

---

cmd/eksctl-anywhere/cmd/renewcertificates.go
cmd/eksctl-anywhere/cmd/renewcertificates_test.go
pkg/certificates/config.go

For workload cluster, for certificate renewal, the command used to fail with error 
```
error: the server doesn't have a resource type \"Machine\"\n"}
Error: cluster is not reachable, please provide control plane and/or external etcd IP addresses: listing machines: getting Machine.v1beta1.cluster.x-k8s.io
```
This PR adds a new field named `managementCluster` if the cluster for which we are renewing certs is a workload cluster to avoid running into this error.
I will create a separate PR for the doc change.

Add management cluster name for renew certificates command

---

test/e2e/metallb.go

- Remove `keepaliveTime` from the configuration
- configuration of `keepaliveTime` is not supported in BGP native mode
-  The speaker log is complaining about the `keepaliveTime` configuration
```
{"caller":"config_controller.go:140","controller":"ConfigReconciler","error":"peer 12.2.4.2 has keepalive-time set on native bgp mode","level":"error","ts":"2025-09-02T23:29:04Z"}
```
- [Upstream Source](https://github.com/metallb/metallb/blob/aa2fa5744e4bcd7ce5c44c8d3ba60c4fa360d303/internal/config/validation.go#L39)
- Change the expected output for the configuration
- In metallb v0.15.2, they added support for flag dualStackFamily defaults to false. This results in `bgppeers.metallb.io` to have an extra expected value `"dualStackAddressFamily":false` in its spec, …

Fix metallb BGPConfiguration e2e test

---

pkg/clusterapi/registry_mirror_test.go
pkg/constants/constants.go
pkg/curatedpackages/packagecontrollerclient.go
pkg/curatedpackages/registry_constants.go
pkg/executables/testdata/kind_config_registry_mirror_with_auth.yaml
pkg/providers/snow/apibuilder_test.go
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_cp_registry_mirror_with_cert.yaml
pkg/providers/tinkerbell/testdata/expected_results_cluster_tinkerbell_md_registry_mirror_with_cert.yaml
pkg/providers/vsphere/testdata/expected_results_mirror_config_with_cert_cp.yaml
pkg/providers/vsphere/testdata/expected_results_mirror_config_with_cert_md.yaml
pkg/registrymirror/registrymirror.go
pkg/registrymirror/registrymirror_test.go

https://github.com/aws/eks-anywhere-internal/issues/3572
Registry mirror lookup for curated packages is broken after adding support for regional registries. We lookup only for the old non-regional registry uri in the ociNamespaces list. Added support to handle regional registries. 
This PR also removes the problematic wildcard registry usage in registry mirror namespaces map. This breaks containerd v2 as it doesn't support adding mirror for registry url with wildcard. Wildcard key was added in NamespacedRegistryMap as a way to lookup curated packages mirror easily. …

Fix regional package registries with registry mirror

---

pkg/providers/tinkerbell/tinkerbell_test.go
pkg/providers/tinkerbell/upgrade.go
pkg/providers/tinkerbell/upgrade_test.go

Scale up for workload cluster fails with hardware validation errors as the hardware csv is not honored during upgrades of workload cluster. 
The hardware CSV entries provided during workload cluster upgrades were not being applied due to an early return in the PreCoreComponentsUpgrade function for managed clusters that was introduced in commit eafc9b0315f890968526821f8261176980362aa9.
This change modifies the PreCoreComponentsUpgrade function to ensure hardware entries are applied for workload clusters while still skipping the stack upgrade which is only needed for management clusters.
Tested by manually building the cli and controller, providing additional hardware during workload cluster upgrades. …

Apply hardware CSV entries during workload cluster upgrades

---

docs/content/en/docs/osmgmt/artifacts.md

Update document on vcenter image-builder role permissions. 
The `VirtualMachine.Inventory.Delete` and `VirtualMachine.Interact.PowerOff` permissions can be omitted from the image-builder user role. While this will result in non-critical error messages during the cleanup phase, it does not affect the image building process.
==> vsphere-iso.vsphere: Destroying VM...
==> vsphere-iso.vsphere: ServerFaultCode: Permission to perform this operation was denied.
==> vsphere-iso.vsphere: Closing sessions...
Note: This configuration requires manual cleanup of the VM after the build process.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …

Update document on vcenter image-builder role permissions

---

release/cli/go.mod
release/cli/go.sum
release/cli/pkg/assets/assets.go
release/cli/pkg/assets/config/bundle_release.go
release/cli/pkg/bundles/eksd.go
release/cli/pkg/operations/testdata/main-bundle-release.yaml

Periodic bundle update jobs have been failing due to containerd changes in build-tooling.
Update containerd configuration to use separate tags per k8s release channel and modify bundle generation to lookup containerd artifacts by release branch (e.g., containerd-1-28, containerd-1-29).

support release-branched containerd in bundle generation

---

release/cli/pkg/assets/archives/archives.go
release/cli/pkg/assets/config/bundle_release.go
release/cli/pkg/operations/testdata/main-bundle-release.yaml

*Issue:*
After the change of containerd to release branch specific builds, the built artifacts and their checkusms are different. But the artifacts are getting uploaded to same release bucket location during the release process. So, whatever k8s version artifact gets uploaded last will remain with other version artifacts getting overwritten. But the checksum entries in the bundle are still the ones computed from overwritten artifacts.
Change s3 folder path for containerd archive assets to be release channel specific. It will change from `artifacts/v0.24.0-dev-build.140/containerd/v1.7.28/containerd-v0.24.0-dev-build.140-linux-amd64.tar.gz` to `artifacts/v0.24.0-dev-build.140/1-28/containerd/v1.7.28/containerd-v0.24.0-dev-build.140-linux-amd64.tar.gz`
*Testing (if …

fix containerd artifact upload path for release branch builds

---

release/cli/pkg/bundles/cilium.go
release/cli/pkg/operations/testdata/main-bundle-release.yaml

[#3578](https://github.com/aws/eks-anywhere-internal/issues/3578)
This PR updates Cilium to the first-party supported version v1.17.6-0 in the dev bundles for v0.24.0 tests.
```
make eks-a
make lint
make unit-test
make -C release dev-release
make -C release update-bundle-golden-files
```
New dev bundle image URIs for Cilium:
```
cilium:
cilium:
arch:
- amd64
description: Container image for cilium image
imageDigest: sha256:07607f99e841df9d7087003ac3618ba6c3476b87163ddfb631ab6d3368a71ad2
name: cilium
os: linux
uri: public.ecr.aws/eks/cilium/cilium:v1.17.6-0
helmChart:
description: Helm chart for cilium-chart
imageDigest: …
```

Update Cilium to the first-party supported version v1.17.6-0

---

release/cli/pkg/helm/helm.go
release/cli/pkg/images/images.go

[#3622](https://github.com/aws/eks-anywhere-internal/issues/3622)
This PR fixes the rate limiting issue for pushing helm charts to the public ECR registry during dev-release job triggered by all the e2e tests pipelines.
```
make -C release unit-test
```

Add retry logic to helm chart push operations to handle rate limiting errors

---

test/e2e/certmanager.go

[#3627](https://github.com/aws/eks-anywhere-internal/issues/3627)
[#7163](https://github.com/aws/eks-anywhere/pull/7163) added a cleanup function in our cert-manager tests to cleanup the Let's encrypt certificates and the Route53 DNS TXT records that were created. But the cleanup happens only if the test succeeds and doesn't run on any test failures. This PR updates the cert manager test flow to ensure certificate cleanup happens even on failures to fix the above issue.

Fix cert-manager tests by ensuring certificate cleanup on failure
